microsoft/terminal

src/cascadia/WindowsTerminal/TrayIcon.cpp
src/cascadia/WindowsTerminal/TrayIcon.h

Currently, the monarch window will show itself when opening the tray icon context menu. This is because a window must be set as the foreground window when the context menu opens, otherwise the menu won't be able to be dismissed when clicking outside of the context menu.
This PR makes the tray icon create a non visible/interactable window for the sole purpose of being set as the foreground window when the tray icon's context menu is opened. Then none of the terminal windows should be set as the foreground window when opening the context menu.
Closes #10936

Create a window process for the tray icon

---

src/cascadia/TerminalApp/AppCommandlineArgs.cpp

This supports a future world where we give commandline-only invocations
their own tabs. It was easier to promote the commandline to a title at
the time of argument parsing, rather than later, but I am happy to
change this if anyone disagrees.

When there's no profile or title, invent a title from the commandline

---

src/cascadia/LocalTests_SettingsModel/TerminalSettingsTests.cpp
src/cascadia/LocalTests_TerminalApp/TabTests.cpp
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/Pane.h
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettings.idl
src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.h
src/cascadia/TerminalSettingsModel/TerminalSettings.idl

Right now, we store GUIDs in panes and most of the functions for interacting
with profiles on the settings model take GUIDs and look up profiles.
This pull request changes how we store and look up profiles to prefer profile
objects. Panes store strong references to their originating profiles, which
simplifies settings lookup for CloseOnExit and the bell settings. In fact,
deleting a pane's profile no longer causes it to forget which CloseOnExit
setting applies to it. Duplicating a pane that is hosting a deleted profile
(#5047) now duplicates the profile, even though it is otherwise unreachable.
This makes the world more consistent and allows us to _eventually_ support panes
hosting profiles that do not have GUIDs that can be looked up in the profile
list. This is a gateway to #6776 and …

Rely more on profile objects and less on GUIDs

---

src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/Pane.h
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

The original code for settings reload iterated the entire tree of panes
for every profile in the new settings (O(mn)) and constructed a
TerminalSettings object for every profile even if it later went unused.
This implementation:
1. Collects all new profiles keyed by guid
1.a. Adds the "defaults" profile to the map
2. Iterates every pane, just once, and updates its profile if it shows
up in the list by GUID.
I've merged all of the per-tab code into a single loop.
Because of 1.a., this code can now update panes that are hosting the
"base" profile.

Only iterate panes one time when updating settings

---

.github/actions/spelling/allow/names.txt
src/inc/til/u8u16convert.h

* Perform the handling of partial code points in the `u8u16` and `u16u8`
conversion functions without preparation in a preliminary buffer.
* Simplify partials handling in `u8u16` (perf).
* Declare the parameters for the incoming data as referenced
string_views.
* Simplify templatization.
* Simplify exception handling.
We complete the partial codepoint in the 4-bytes long cache and convert
it separately. This makes the cache ready for capturing the next
partials before the remaining string is converted. This way, we neither
need to copy the whole string into a buffer which contains complete
codepoints, nor do we need to allocate an unnecessarily long buffer
which exists for the life time of the state class instance.
Finding and capturing of partials is performed in a more linear code
using …

Refactor `u8u16` and `u16u8` conversion functions

---

.github/actions/spelling/allow/microsoft.txt
src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp

This PR converts the WSL distro generator to use the registry to lookup
WSL distros instead of trying to parse the results of `wsl.exe`.
`wsl.exe` sometimes takes a very long time to launch the WSL service,
which means that on the first launch of the Terminal, WSL distros can
sometimes be missing entirely!
* Also related is #6160, but I feel that deserves a separate PR for
warning when the default profile is a dynamic profile who's source
indicated it was gone. 
This is maybe a little BODGY, but hey we get tons of reports of this
root cause.
Ran it locally, it did well. Ran a `wsl --shutdown`, then booted the
terminal - seemed to do well. I never was able to repro the slowness
myself, but I'd suspect this'll fix it.

Lookup WSL distros in the registry

---

.github/actions/spelling/allow/apis.txt
src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/Pane.h

During startup we do not have real dimensions, so we have to guess what
our dimensions should be based off of the splits.
We'll augment the state of the pane search to also have a size in each
dimension that gets incrementally upgraded as we recurse through the
tree.
References #10978

Fix directional movement during startup

---

src/cascadia/LocalTests_SettingsModel/TerminalSettingsTests.cpp
src/cascadia/TerminalApp/AppCommandlineArgs.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.cpp

It was insufficient to only promote commandline components to titles
during commandline parsing, because we also have a whole complement of
actions that contain NewTerminalArgs. The tests caught me out a little
too late (sorry!). I decided it was better move promotion down to
TerminalSettings.
Fixes #6776
Re-implements #10998

Move commandline->title promotion into TerminalSettings

---

src/cascadia/TerminalApp/CommandPalette.cpp

Teach command palette to fill in selected commandline upon right arrow

---

src/cascadia/TerminalSettingsEditor/GlobalAppearance.cpp
src/cascadia/TerminalSettingsEditor/GlobalAppearance.h
src/cascadia/TerminalSettingsEditor/GlobalAppearance.idl
src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Adds toggle buttons to the settings UI for `minimizeToTray` and `alwaysShowTrayIcon` that I mistakenly left out.

Add Tray Icon settings to the SettingsUI

---

src/cascadia/TerminalApp/CommandPalette.cpp

The first time you open commandline mode, `recentCommands` doesn't exist yet. However, we immediately try to read the `Size()` in a couple places. This'll A/V and we'll crash 😨 
The fix is easy - don't try and read the size of the non-existent `recentCommands`
Found this while playing with #11069
Regressed in #11030 
Didn't bother filing an issue for it when I have the fix in hand

Fix a crash when there aren't any `recentCommands` yet

---

src/cascadia/TerminalApp/App.xaml
src/cascadia/TerminalApp/MinMaxCloseControl.xaml

Doing #10242 again.
The space around the tabs was made equal in windowed mode.
For maximized mode, I made the titlebar be 33px tall, to compensate for #10746.

Make TabView padding equal

---

src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/Pane.h
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

Make it so you can navigate pane focus without unzooming.
- Slight refactor to bring the MRU pane logic into the `NavigateDirection` function
- The actual zoom behavior was not a problem, the only issue is that because most of the panes weren't in the UI tree I had to disable using the actual sizes. There is nothing wrong with that, since the synthetic sizing is required anyways, but I'm curious what other peoples' thoughts are.

Maintain zoom when moving focus

---

doc/cascadia/profiles.schema.json

`useAcrylicInTabRow` was missing from the JSON schema, so I added it in.
#10864

Add `useAcrylicInTabRow` to JSON schema

---

src/cascadia/Remoting/Monarch.cpp
src/cascadia/Remoting/Monarch.h
src/cascadia/Remoting/Monarch.idl
src/cascadia/Remoting/Peasant.h
src/cascadia/Remoting/Peasant.idl
src/cascadia/Remoting/WindowManager.cpp
src/cascadia/Remoting/WindowManager.h
src/cascadia/Remoting/WindowManager.idl
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/AppLogic.idl
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/UnitTests_Remoting/RemotingTests.cpp
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/TrayIcon.cpp
src/cascadia/WindowsTerminal/TrayIcon.h

This PR adds a bit more information to each item in the Tray Icon's  window selection submenu. 
Currently it only shows the window ID and window name if given one. 
Now each item will instead show`{Window ID} : {Active Tab Title} [{Window Name}]`

Provide the focused tab title in the Tray Icon's context menu

---

src/cascadia/TerminalControl/SearchBoxControl.xaml
src/cascadia/TerminalSettingsEditor/Appearances.xaml
src/cascadia/TerminalSettingsEditor/Interaction.xaml
src/cascadia/TerminalSettingsEditor/Profiles.xaml

Disables autocorrect for command, path and find text inputs. Does not disable it for profile names, tab titles or colour scheme names.
Manually typed `bash -i -l` into the profile command text input and found it no longer auto-capitalised the I.

Disable autocorrect for command, path and find text inputs

---

src/cascadia/TerminalApp/TabManagement.cpp

Make sure to always synchronously set the selected tab. This way when changing tabs while running multiple actions further calls to _GetFocusedTab will return the correct one.
**Edit** #11146  discovered while trying to test this so while I fixed the case I wanted, things seem to be broken generally so it is hard for me to test if I broke anything else.
Ran the command specified in the issue and confirmed that the correct tab was focused and that the correct pane was zoomed.

Fix tab movement while running multiple actions

---

scratch/ScratchIslandApp/SampleApp/packages.config
scratch/ScratchIslandApp/WindowExe/packages.config
src/cascadia/Remoting/packages.config
src/cascadia/ShellExtension/packages.config
src/cascadia/TerminalApp/packages.config
src/cascadia/TerminalAzBridge/packages.config
src/cascadia/TerminalConnection/packages.config
src/cascadia/TerminalControl/packages.config
src/cascadia/TerminalCore/packages.config
src/cascadia/TerminalSettingsEditor/packages.config
src/cascadia/TerminalSettingsModel/packages.config
src/cascadia/WinRTUtils/packages.config
src/cascadia/WindowsTerminal/packages.config
src/cascadia/WindowsTerminalUniversal/packages.config
src/cppwinrt.build.post.props
src/cppwinrt.build.pre.props

This pull request moves us to Microsoft.Windows.CppWinRT 2.0.210825.3.
Notable improvements from 2.0.210309.3:
* Restored Windows 7 functionality
* C++20 ranges support
* `capture` now works with a raw pointer
* `hstring::starts_with` and `hstring::ends_with` (C++20)
Unit/Functional Tests:
Summary: Total=7728, Passed=7571, Failed=10, Blocked=0, Not Run=0, Skipped=147
Local Tests:
Summary: Total=163, Passed=158, Failed=5, Blocked=0, Not Run=0, Skipped=0
The above failures are (1) in UIA tests for conhost/WT (which do not work here) or
(2) in already known-broken local tests.

Upgrade to C++/WinRT 2.0.210825.3

---

src/cascadia/Remoting/Monarch.cpp
src/cascadia/UnitTests_Remoting/RemotingTests.cpp

Fix infinite loop when trying to summon a window after close.
In #10972 code was added to try to clean up state manually when a window
was closed instead of waiting for it to be detected as a dead peasant.
Unfortunately I didn't know any better and missed cleaning up
`_mruPeasants` as well. The result is there  would be an infinite loop
in `_getMostRecentPeasant` since `_getPeasant` will only clean up ids if
it finds a peasant, not if it doesn't find anything. This is the minimal
change to get this working, but it might be a good idea to make
`_getPeasant` be more thorough about cleanup.
Tested that before the change we infinitely loop, and after the change
we summon correctly.
Closes #11215

Make sure we fully clean up state when closing a peasant

---

src/cascadia/LocalTests_SettingsModel/SerializationTests.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.h

Fixes the serialisation of the findMatch action so that the direction is stored.
Added a test and tested manually.

Fix serialisation of findMatch action

---

src/cascadia/TerminalSettingsModel/defaults.json

We already had resetFontSize bound to ctrl+0. As discussed in
#11239 it should be possible to do the same with ctrl+numpad_0.
* Resetting the font size with ctrl+numpad_0 works

Bind resetFontSize to numpad_0

---

src/cascadia/TerminalApp/AppLogic.cpp

When we're elevated, we disable drag/dropping tabs when elevated, because of a platform limitation that causes the app to _crash_ (see #4874). However, if the user has UAC disabled, this actually works alright. So I'm adding it back in that case.
I'm not positive if this is the best way to check if UAC is disabled, but normally, you'll get a [`TokenElevationTypeFull`] when elevated, not `TokenElevationTypeDefault`. If the app is elevated, but there's not a split token, that kinda implies there's no user account separation. If I'm wrong, it's just code, let's replace this with something that does work.
Booted up a Win10 VM, set `enableLUA` to `0`, rebooted, and checked if this exploded. It didn't.
References #4874 
References #3581
Work done in pursuit of #11096
Closes #7754 …

Allow reordering tabs when UAC is disabled

---

src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/Resources/en-US/Resources.resw
src/cascadia/TerminalConnection/TerminalConnection.vcxproj
src/cascadia/TerminalConnection/TerminalConnection.vcxproj.filters

Process exit code now shows as hex not decimal. Format specification needs length "10" not "8" because the leading '0x' generated by the # symbol counts as part of the length.

Change exit code to hex; Fix format spec

---

src/terminal/adapter/charsets.hpp

Fixed typo.
```
alway -> always
```

Fix typo in charsets.hpp

---

src/cascadia/TerminalControl/TermControl.cpp

For some weird reason we sometimes receive a WM_KEYDOWN
message without vkey or scanCode if a user drags a tab.
The KeyChord constructor has a debug assertion ensuring that all KeyChord
either have a valid vkey/scanCode. This is important, because this prevents
accidential insertion of invalid KeyChords into classes like ActionMap.
* Tab dragging doesn't produce assertion failures anymore ✔️

Fix KeyChord constructor assertion failure during tab dragging

---

.github/actions/spelling/allow/allow.txt
.github/actions/spelling/allow/names.txt
tools/ReleaseEngineering/New-TerminalStackedChangelog.ps1

I've done this process enough times that I should have written a script
to do it a while ago. This one is rough, but the whole changelog process
is pretty rough.
This script takes multiple revision ranges and produces something that
looks like a rough untranslated changelog, with indicators for how many
of the provided ranges had the same change (deduplicated by title.)
I use a process like this to build the Stable and Preview release notes
out of a set of revision ranges.

releng: add New-TerminalStackedChangelog

---

.editorconfig

This commit configures compliant text editors to save our code as UTF-8.

.editorconfig: add utf-8 encoding 

---

src/Terminal.wprp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/terminalrenderdata.cpp
src/host/renderData.hpp
src/host/ut_host/VtIoTests.cpp
src/types/IUiaData.h
src/types/ScreenInfoUiaProviderBase.cpp
src/types/TermControlUiaProvider.cpp
src/types/TermControlUiaTextRange.cpp
src/types/UiaTextRangeBase.cpp

Adds a check before every UIA function call to ensure the terminal (specifically the buffer) is initialized before doing work. Both the `ScreenInfoUiaProvider` and the `UiaTextRange` are now covered.
Closes #11135 
#10971 & #11042
Originally, I tried applying this heuristic to all the `RuntimeClassInitialize` on `UiaTextRangeBase` with the philosophy of "a range pointing to an invalid buffer is invalid itself", but that caused a regression on [MSFT 33353327](https://microsoft.visualstudio.com/OS/_workitems/edit/33353327).
`IUiaData` also has `GetTextBuffer()` return a `TextBuffer&`, which cannot be checked for nullness. Instead, I decided to add a function to `IUiaData` that checks if we have a valid state. Since this is shared with Conhost and Conhost doesn't have this issue, I simply …

[a11y] Ensure buffer is initialized before interacting with it

---

src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

This commit fixes layering of fragment profiles without an update key.
The previous CascadiaSettings deserializer first assembled all builtin
profiles and only then parsed the user's settings.json file.
This meant that even though fragment profiles were added to `_allProfiles`
unconditionally, they did get layered properly with user profiles regardless,
as user profiles were always properly layered.
The new CascadiaSettings approach since 168d28b was a direct translation of this
approach but this is incorrect: As the new approach reads user profiles first,
all inbox profiles, including fragments, must equally use proper layering,
instead of adding profiles unconditionally.
While this commit fixes the bug it maintains a regression:
Duplicate fragment profile GUIDs will not be detected and …

Fix layering of fragment profiles

---

src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

`SettingsLoader::_parse` used to skip profiles which didn't have either a "guid"
or "name" field, due to #9962. This is however wrong for fragment loading, as
fragments can alternatively use an "updates" field instead of guid/name.
`SettingsLoader::_parse` was updated to allow profiles with this alternative
field during fragment loading.
* Wrote the following to
`%LOCALAPPDATA%\Microsoft\Windows Terminal\Fragments\test\test.json`:
```json
{
"profiles": [
{
"updates": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
"background": "#FFD700"
}
]
}
```

Fix fragments that update other profiles

---

doc/cascadia/profiles.schema.json

* fixes #11349
* Fix these two nulls
* While I'm here, fix the indenting around `SwitchToTabAction` that would prevent nice code folding

Replace `null` with `"null"` for types in the schema

---

doc/cascadia/profiles.schema.json

This fixes two issues with profiles.schema.json:
* The `$schema` should not end in a `#`
* `$defs` is the official reserved keyword for schema re-use
See: http://json-schema.org/draft/2020-12/json-schema-core.html
The previous schema didn't pass https://jschon.dev/, the new schema does.

Fix compatibility issues with profiles.schema.json

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/JsonUtils.h
src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw

Minor typos in 1.12 features in SUI

---

src/cascadia/TerminalSettingsModel/TerminalSettings.cpp

This logic was seemingly redundant. There's two cases I'm looking at here:
```jsonc
"defaults":
{
"opacity": 35
},
"list":
[
{
"commandline": "cmd.exe",
"name": "Command Prompt"
},
```
In this case, we wouldn't set the `TerminalSettings` Opacity to .35, we'd set it to 1.0, because the profile didn't have an `opactity`.
```jsonc
"defaults":
{
"useAcrylic": true
},
"list":
[
{
"commandline": "cmd.exe",
"name": "Command Prompt"
},
```
In this case we still want to have an acrylic effect. Previously, we'd default this effect to 50% opaque. I'm not sure that we can actually get that anymore. BUT it turns out, we _can_ have 100% opacity and HostBackdropAcrylic. It is very subtle, but is maybe something we should be allowing anyways. It kinda looks like:

Remove the fallback to 50% opacity when only `useAcrylic` is set

---

src/interactivity/onecore/BgfxEngine.cpp
src/interactivity/onecore/BgfxEngine.hpp
src/renderer/base/renderer.cpp
src/renderer/base/renderer.hpp
src/renderer/dx/DxRenderer.cpp
src/renderer/dx/DxRenderer.hpp
src/renderer/gdi/gdirenderer.hpp
src/renderer/gdi/paint.cpp
src/renderer/inc/IRenderEngine.hpp
src/renderer/uia/UiaRenderer.cpp
src/renderer/uia/UiaRenderer.hpp
src/renderer/vt/paint.cpp
src/renderer/vt/vtrenderer.hpp
src/renderer/wddmcon/WddmConRenderer.cpp
src/renderer/wddmcon/WddmConRenderer.hpp

This replaces the `GridLines` enum in the renderers with a `til::enumset` type, avoiding the need for the various `WI_IsFlagSet` macros and flag operators.
This is followup to PR #10492 which introduced the `enumset` class.
I've manually confirmed that all the different gridlines are still rendering correctly in both the GDI and DX renderers.

Use the til::enumset type for the GridLines enum in the renderers

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/TermControl.cpp

Missed this in #11180. I forgot to init the BG opacity with the renderer on startup, because that matters when you have `"antialiasingMode": "cleartype",`.
Repro json
```json
{
"commandline": "cmd.exe",
"guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
"hidden": false,
"opacity": 35,
"antialiasingMode": "cleartype",
"padding": "0",
"name": "Command Prompt"
},
```

Always init the BG opacity with the renderer

---

src/cascadia/TerminalApp/TerminalTab.cpp

DESPITE the fact that there's a `Background()` API that we
could just call like:
```c++
TabViewItem().Background(deselectedTabBrush);
```
We actually can't, because it will make the part of the tab that
doesn't contain the text totally transparent to hit tests. So we
actually _do_ still need to set `TabViewItemHeaderBackground` manually.
* Regressed in #11240
* Root cause up in https://github.com/microsoft/microsoft-ui-xaml/pull/3769

Allow the entire Tab to be hit testable again

---

src/cascadia/TerminalSettingsEditor/Appearances.xaml
src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsEditor/Profiles.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

All these controls didn't have `Name`s assigned, and Accessibility Insights doesn't like that. Their parents did, but the actual focusable elements themselves didn't. So I've just taken the nearby headers for these things and slapped them in as the Automation names for these controls.
I verified that each of these automated tests in Accessibility Insights pass again. 
* Will do the thing to #11155 but we need confirmation before that can be closed.

Add automation names to some controls that were missing them

---

src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/terminalrenderdata.cpp
src/types/TermControlUiaProvider.cpp

The deadlock was caused by `ScreenInfoUiaProviderBase::GetSelection()` calling `TermControlUiaProvider::GetSelectionRange` (both of which attempted to lock the console). This PR removes the lock and initialization check from `TermControlUiaProvider`. It is no longer necessary because the only one that calls it is `SIUPB::GetSelection()`.
Additionally, this adds some code that was useful in debugging this race condition. That should help us figure out any locking issues that may come up in the future.
#11312
Closes #11385 
✅ Repro steps don't cause hang

[deadlock fix] Remove lock for SIUP::GetSelectionRange()

---

src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalSettingsEditor/Appearances.cpp
src/cascadia/TerminalSettingsEditor/Profiles.cpp
src/cascadia/TerminalSettingsEditor/Utils.cpp
src/cascadia/TerminalSettingsEditor/Utils.h
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettings.idl
src/cascadia/WinRTUtils/Utils.cpp
src/cascadia/WinRTUtils/WinRTUtils.vcxproj
src/cascadia/WinRTUtils/inc/Utils.h
src/cascadia/WinRTUtils/pch.h

Just like in #9760, we can't actually use the UWP file picker API, because it will absolutely not work at all when the Terminal is running elevated. That would prevent the picker from appearing at all. So instead, we'll just use the shell32 one manually. 
This also gets rid of the confirmation dialog, since the team felt we didn't really need that. We could maybe replace it with a Toast (#8592), but _meh_
* This is a lot like #9760
* introduced in #11062
* megathread: #9700

Replace the UWP file export with the shell32 one

---

doc/cascadia/profiles.schema.json

The type of the `"id"` argument of the `focusPane` action under `"actions"` in the `settings.json` schema was incorrectly set to a string.
It's actually expecting a non-negative number, and defaults to 0.
So I fixed the schema.
I've validated that a string makes Windows Terminal complain it's a string and not a number, and that a number works as expected, and that the default is indeed zero.

Fix type of id in focusPane action in setttings schema

---

src/cascadia/TerminalApp/Pane.cpp

Try to save the working directory if we know what it is (just copied what was done in duplicating a pane). I overlooked this in my original implementation that always used the settings StartingDirectory.
#9800 
Tried setting the working directory using the OSC 9;9 escape and confirmed that the directory saves correctly.

Try to persist the Pane's working directory if we know what it is.

---

src/cascadia/WindowsTerminal/IslandWindow.cpp

The code saved `args.DropdownDuration()` to a local and then called the function again, instead of using the local.
Changed to use the local.
I think this getter simply accesses a member on `args`, it doesn't parse the settings or anything, so compiler optimizes it, but seemed to make more sense to use the local.

[IslandWindow.cpp] Avoid double-fetching dropdownDuration

---

src/cascadia/TerminalSettingsEditor/Profiles.h
src/cascadia/TerminalSettingsEditor/Profiles.xaml

Fixes the "Reset to inherited value" button for the opacity slider and removes the unwanted padding between the header and the control.
Manually tested

Ensure "Reset to inherited value" button works for opacity

---

src/cascadia/TerminalSettingsModel/ActionArgs.h

In `settings.json` there's an `actions` array to configure keybindings.
The action `globalSummon` has an argument called `dropdownDuration`.
The settings editor deleted this argument from the settings because of a typo in `ActionArgs.h`.
There was a `JsonUtils::GetValueForKey` instead of a `JsonUtils::SetValueForKey`.
This is what happens when such code is not autogenerated.
None

Fix globalSummon.dropdownDuration not saving correctly

---

src/cascadia/TerminalApp/TerminalTab.cpp

I've had a hard time with the tab colors this week.
Turns out that setting the background to nullptr will make the tabviewitem invisible to hit tests. `Transparent`, on the other hand, is totally valid, and the expected default. 
Tabs as of this commit:
This low-key reverts a bit of #11369, which fixed #11294, which regressed in #11240

Fix the tab color, part III

---

src/cascadia/LocalTests_SettingsModel/DeserializationTests.cpp
src/cascadia/LocalTests_SettingsModel/ProfileTests.cpp
src/cascadia/LocalTests_SettingsModel/SerializationTests.cpp
src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp
src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp

This commit fixes various failing TestHostApp unit tests.
Most of these broke as part of 168d28b (#11184).

Fix failing TestHostApp unit tests

---

src/cascadia/CascadiaPackage/Package.appxmanifest
src/features.xml

Uncommenting parts of stable's AppXManifest to allow defapp to work with it.

Enable DefApp hooks for stable

---

src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

`CascadiaSettings` is default constructed when human readable error messages are
returned. Even in such cases we need to ensure that all fields are properly
initialized, as a caller might decide to call a `GlobalSettings` getter.
Thus a crash occurred whenever a user was hot-reloading their settings file with
invalid JSON as other code then tried to compare the `GlobalSettings()`.
* Start Windows Terminal and ensure the settings load fine
* Add `"commandline": 123` to any of the generated profiles in settings.json
* The application doesn't crash and shows a warning message

Fix null pointer exceptions for default constructed CascadiaSettings instances

---

src/terminal/adapter/terminalOutput.cpp

There is a non-zero subset of applications that randomly output _Locking Shift_ escape sequences which will invoke a character set from G2 or G3 into the left half of the code table. If those G-sets are mapped to Latin1, that can result in the terminal producing output that appears to be broken. This PR now defaults all G-sets to ASCII, to prevent an unintentional _Locking Shift_ from having any effect.
Most other modern terminals also default to ASCII in all G-sets, so this shouldn't break any modern applications. Legacy 8-bit applications may still expect the G2 and G3 sets mapped to Latin1, but they would also need to have the ISO-2022 encoding enabled, so we can keep them happy by setting G2 and G3 correctly when the ISO-2022 encoding is requested.
I've manually confirmed that `echo …

Default all G-sets to ASCII unless ISO-2022 is requested

---

src/cascadia/TerminalConnection/ConptyConnection.cpp

Make sure to format the error message with an UNSIGNED int

---

src/cascadia/TerminalSettingsEditor/Profiles.h
src/cascadia/TerminalSettingsEditor/Profiles.idl
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/Profile.cpp
src/cascadia/TerminalSettingsModel/Profile.h
src/cascadia/TerminalSettingsModel/Profile.idl

The `ForceFullRepaintRendering` and `SoftwareRendering` are global only and for some reason were in profile. This commit removes them.
Reference: https://github.com/microsoft/terminal/pull/11416#discussion_r742030103

Remove unused rendering settings from profile

---

src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/AppLogic.idl
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/IslandWindow.h

Window sends an event that requests exit from fullscreen then SC_RESTORE messages is sent and it is in fullscreen mode.
Closes #10607
Border and tabbar now appear after exiting fullscreen via "win+arrow down".

Fix missing window border when use "win+arrow down" in fullscreen mode in Terminal

---

src/cascadia/WindowsTerminal/IslandWindow.cpp

#11404 and #11653 both added WM_SYSCOMMAND which prevents build. This fixes it.

fix build error at 74d21af 

---

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp

Fixes MSFT:34673647, at least I'm pretty sure. That's only ever hit a few
times externally, and internally it's hitting a lot on 1.9.1942 builds, which
doesn't really make any sense.

Don't crash if we fail to BeginBufferedPaint

---

doc/specs/#885 - Terminal Settings Model/#885 - Terminal Settings Model.md

Fixed typo.
```
ocurred -> occurred
```

doc: Fix typo in #885 - Terminal Settings Model.md

---

src/terminal/adapter/adaptDispatch.cpp

6140fd9 causes a binary size regression in conhost.
This PR fixes most if not all of the regression, by replacing `FMT_STRING`
with `FMT_COMPILE` allowing us to drop most of the formatters built
into fmt during linking (for instance floating point formatters).
Additionally `std::wstring` was replaced with `fmt::basic_memory_buffer`
in the same vein as was done for VtEngine. Stack is
cheap and this prevents any unnecessary allocations.
* vttest 11.2.5.3.6.7 and .8 (DECSTBM and SGR) complete successfully ✅

Fix a conhost binary size regression due to fmt

---

.github/ISSUE_TEMPLATE/Bug_Report.yml

We're getting a LOT of issues that are all "I cant ~read~ set the terminal as the default terminal" that would all be instantaneously diagnosable if we knew OP's terminal version. Weirdly, these posts always include the OS version. So I'm separating these out into two different line items.
I'm not marking them both as required, because for conhost bugs the Terminal version isn't relevant. I'm debating that with myself.
I might instead go for:
```yaml
- type: input
attributes:
label: Windows Terminal version
placeholder: "1.7.3651.0"
description: |
You can find the version in the about dialog, or by running `wt -v` at the commandline. If your bug doesn't involve the Windows Terminal (i.e. it's a conhost bug), then you can just put N/A
validations:
required: true
- type: input
attributes: …
```

Separate terminal version and Windows version in issue template

---

src/interactivity/win32/windowproc.cpp

Window exits out of fullscreen if it receives SC_RESTORE
Closes #10607

Fix missing window border when use "win+arrow down" in fullscreen mode in Conhost

---

.github/actions/spelling/allow/allow.txt
src/cascadia/TerminalSettingsEditor/Profiles.cpp
src/cascadia/TerminalSettingsEditor/pch.h
src/renderer/dx/DxFontInfo.cpp
src/renderer/dx/DxFontInfo.h
src/renderer/dx/DxFontRenderData.cpp
src/renderer/dx/DxFontRenderData.h
src/renderer/dx/lib/dx.vcxproj
src/renderer/dx/lib/dx.vcxproj.filters

This commit is a minimal fix in order to pass the
`IDWriteFontCollection` we create out of .ttf files residing next to our
binaries to the `IDWriteFontFallback::MapCharacters` call. The
`IDWriteTextFormat` is used in order to carry the font collection over
into `CustomTextLayout`.
* Put `JetBrainsMono-Regular.ttf` into the binary output directory
* Modify `HKCU:\Console\*\FaceName`  to `JetBrains Mono`
* Launch OpenConsole.exe
* OpenConsole uses JetBrains Mono ✔️
Closes #11032
Closes #11648

Use nearby fonts for font fallback

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/UnitTests_TerminalCore/TerminalApiTest.cpp
src/host/outputStream.cpp
src/host/outputStream.hpp
src/host/ut_host/ScreenBufferTests.cpp
src/terminal/adapter/ITermDispatch.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/conGetSet.hpp
src/terminal/adapter/termDispatch.hpp
src/terminal/adapter/ut_adapter/adapterTest.cpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp
src/terminal/parser/stateMachine.cpp
src/terminal/parser/stateMachine.hpp
src/terminal/parser/telemetry.cpp
src/terminal/parser/telemetry.hpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp

There are some code pages with "unmapped" code points in the C1 range,
which results in them being translated into Unicode C1 control codes,
even though that is not their intended use. To avoid having these
characters triggering unintentional escape sequences, this PR now
disables C1 controls by default.
Switching to ISO-2022 encoding will re-enable them, though, since that
is the most likely scenario in which they would be required. They can
also be explicitly enabled, even in UTF-8 mode, with the `DECAC1` escape
sequence.
What I've done is add a new mode to the `StateMachine` class that
controls whether C1 code points are interpreted as control characters or
not. When disabled, these code points are simply dropped from the
output, similar to the way a `NUL` is interpreted.
This isn't …

Disable the acceptance of C1 control codes by default

---

.vsconfig
build/scripts/Create-AppxBundle.ps1
build/scripts/Test-WindowsTerminalPackage.ps1
doc/cascadia/Unittesting-CppWinRT-Xaml.md
samples/ConPTY/EchoCon/EchoCon/EchoCon.vcxproj
scratch/ScratchIslandApp/Package/Package.appxmanifest
src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest
src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.AppxManifest.prototype.xml
src/cascadia/LocalTests_TerminalApp/TestHostApp/Package.appxmanifest
src/cascadia/WindowsTerminalUniversal/Package-Dev.appxmanifest
src/cascadia/WindowsTerminalUniversal/Package.appxmanifest
src/cascadia/ut_app/TerminalApp.Unit.Tests.AppxManifest.xml
src/common.build.pre.props
src/tools/MonarchPeasantPackage/MonarchPeasantPackage.wapproj
src/wap-common.build.pre.props

Upgrades our SDK from 19041 (Windows 10 20H1) to 22000 (Windows 11 RTM).
The newer SDK is  more compatible with /Zc:preprocessor
and will allow us to use newer Windows 11 APIs directly.
* Compiles ✔️
* Runs ✔️

Upgrade to Windows SDK 22000

---

scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj
src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
src/cascadia/TerminalAzBridge/TerminalAzBridge.vcxproj
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj

I'm working on making the FastUpToDate check in Vs work for the Terminal project. This is one of a few PRs in this area.
FastUpToDate lets vs check quickly determine that it doesn't need to do anything for a given project. 
However, a few of our projects don't produce all the right artifacts, or check too many things, and this eventually causes the `wapproj` to rebuild, EVERY TIME YOU F5 in VS. 
This third PR deals with the Actual fast up to date check for the CascadiaPackage.wapproj. When #11804, #11805 and this PR are all merged, you should be able to just F5 the Terminal in VS, and then change NOTHING, and F5 it again, without doing a build at all. 
The wapproj `GetResolvedWinMD` target tries to get a winmd from every cppwinrt
executable we put in the package. But we DON'T produce a …

Fixes the wapproj fast-up-to-date check

---

src/cascadia/TerminalConnection/TerminalConnection.vcxproj

I'm working on making the FastUpToDate check in Vs work for the Terminal project. This is one of a few PRs in this area.
FastUpToDate lets vs check quickly determine that it doesn't need to do anything for a given project. 
However, a few of our projects don't produce all the right artifacts, or check too many things, and this eventually causes the `wapproj` to rebuild, EVERY TIME YOU F5 in VS. 
This first PR deals with the `.copycomplete` file in `obj\x64\debug\terminalconnection\`. Below are my verbatim notes, which led to the solution in this PR. 
* There were missing `.copycomplete` files across the repo. 
```
obj\x64\debug\microsoft.terminal.settings.model.lib\microsoft.terminal.settings.modellib.vcxproj.copycomplete
obj\x64\debug\microsoft.terminal.settings.model\microsoft.terminal.s …
```

Fix for missing CopyComplete files in TerminalConnection.vcxproj

---

src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
src/cascadia/TerminalSettingsModel/dll/Microsoft.Terminal.Settings.Model.vcxproj

I'm working on making the FastUpToDate check in Vs work for the Terminal project. This is one of a few PRs in this area.
FastUpToDate lets vs check quickly determine that it doesn't need to do anything for a given project. 
However, a few of our projects don't produce all the right artifacts, or check too many things, and this eventually causes the `wapproj` to rebuild, EVERY TIME YOU F5 in VS. 
This second PR deals with some projects MYSTERIOUSLY depending on the `.xaml` files from `Terminal.Control`, even when they by all accounts shouldn't. TerminalSettingsModel ISN'T EVEN A XAML project, so I have no idea why it thinks it needs these xaml files. The TerminalAppLib project thinking it needs them - makes more sense, but is still confusing. 
Below are my verbatim notes, which led to the …

Fix missing .xaml references

---

build/rules/GenerateFeatureFlags.proj
src/host/ft_uia/Host.Tests.UIA.csproj
src/propsheet/propsheet.vcxproj

I'm pretty exactly following the diff from #917. These paths weren't wrapped in `&quot;`s, so building the solution in a directory with a space in it would explode.
Closes #917.
Turns out, the diff provided by that user wasn't exactly right. I've tested building in a directory with spaces now, and this seems to work. 
Also caught a bug in the Generate Feature Flags script.

Wrap these commands with quotes

---

src/inc/til/enumset.h
src/terminal/input/mouseInput.cpp
src/terminal/input/terminalInput.cpp
src/terminal/input/terminalInput.hpp
src/terminal/parser/stateMachine.cpp
src/terminal/parser/stateMachine.hpp
src/til/ut_til/EnumSetTests.cpp

This commit approximately doubles the performance of til::enumset
and reduces it's binary footprint by approximately 1kB.
Most of the binary size can be attributed to exception handling.
Unfortunately this commit removes assertions that the given values are less than
the number of bits in the `underlying_type`. However I believe this to be a good
trade-off as the tests previously only happened at runtime, while tests at
compile time would be highly preferable. Such tests are technically possible,
however MSVC fails to compile (valid) `static_assert`s containing
`static_cast`s over a parameter pack at the time of writing.
With future MSVC versions such checks can be added to this class.
This change was initially discussed in #10492, but was forgotten to
be considered before it was merged. …

Improve performance and binary size of til::enumset

---

src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp
src/cascadia/TerminalSettingsModel/IInheritable.h
src/cascadia/TerminalSettingsModel/Profile.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.cpp

This is a followup commit for 168d28b.
By renaming `IInheritable::InsertParent(com_ptr)` and
`InsertParent(size_t, com_ptr)` into `AddLeastImportantParent(com_ptr)`
and `AddMostImportantParent(com_ptr)` respectively, we can improve
the clarity of our code's intent without the need for comments.

Rename IInheritable::InsertParent to improve clarity of intent

---

build/pipelines/release.yml
build/pipelines/templates/build-console-audit-job.yml
build/pipelines/templates/build-console-steps.yml

Set fetch limit to a depth of 1 for our pipelines as they're just building off of one commit. Saves disk space at least. Might save time.
See also: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/pipeline-options-for-git?view=azure-devops&tabs=yaml#shallow-fetch

Use shallow fetch depth

---

.github/actions/spelling/allow/allow.txt
doc/building.md

Unfortunately, does not come up with a good inner loop for buidling the package from the commandline. The inner loop for the resources just sucks.

Add notes on building package from commandline

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

Since the settings UI's input fields behave similarly to the terminal's input,
`TerminalPage::_KeyDownHandler` also needs to behave similarly to
`TermControl::_KeyHandler`. This commit copies all relevant code
over from the latter into the former, including the suppression
of AltGr keys for keychord/action handling.
* Use a German keyboard layout
* Open 2 regular tabs and 1 settings tab and focus an input field
* AltGr+2 produces the character ² ✔️
* Ctrl+Alt+2 opens the second tab ✔️
(cherry picked from commit 80f838386075068d571099ad2888c6afc2f911a0)

Fix AltGr not working in the settings UI (#11808)

---

src/cascadia/TerminalControl/TermControl.cpp

This fixes a regression introduced in #10988 for the 1.11 release branch.
For later branches this issue was fixed in #11086.
* AltGr+Space produces "_" with the bépo keyboard layout

Fix AltGr+Space not working

---

.github/actions/spelling/expect/expect.txt
build/pipelines/release.yml
build/pipelines/templates/install-winsdk-steps.yml
build/scripts/Index-Pdbs.ps1
build/scripts/Install-WindowsSdkISO.ps1

We have been advised to give not only the PDB paths, but paths to the EXE and DLL files we produce, to the PublishSymbols build task. We are assured by our engineering systems teams that enlightening the task to all of this information helps it hook things up better somewhere between our build machine and the symbol server such that debugging is more robust, especially around thrown exception stacks.

Tell PublishSymbols task about binaries as well as the PDB files

---

doc/specs/drafts/576-ProfilesJumplistSpec.md

Fixed typo.
```
existant -> existent
```

specs: fix typo in 576-ProfilesJumplistSpec.md

---

src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h

Clean up an invalid access that I introduced in #11440

Make sure we dont access an invalid optional on close

---

src/cascadia/TerminalSettingsModel/ActionArgsMagic.h

I had these out of order, and apparently forgot to launch the Terminal before pushing that commit. This resulted in getting the following with the default settings:
So yea obviously, we should deserialize first, then check if the setting is valid.

Make sure to deserialize arg params _before_ validating

---

src/host/history.cpp

This is a primitive bug fix for GetConsoleCommandHistoryLengthA.

Fix length calculation of GetConsoleCommandHistoryLengthA

---

src/types/inc/sgrStack.hpp
src/types/sgrStack.cpp

This replaces the `std::bitset` for the `SgrSaveRestoreStackOptions` enum with a `til::enumset` type, thus avoiding the need to cast the `enum` to a `size_t` every time a value is set or tested.
This also fixes an issue with the handling of omitted and zero parameters in the `XTPUSHSGR` sequence, which are meant to be ignored, and not interpreted as "all".
In addition to dropping all the `static_cast` operations, the use of the `til::enumset` also allowed us to get rid of the `try`/`catch` handling that was previously required in a couple of places, since the `til::enumset` operations don't throw. 
And to fix the zero parameter handling, we just needed to add an additional lower bound when validating that options are in range - if an option is 0 (`All`), it will now just be ignored.
The …

Use the til::enumset type for the SgrSaveRestoreStackOptions enum

---

.github/actions/spelling/expect/expect.txt
src/buffer/out/UnicodeStorage.hpp
src/buffer/out/textBuffer.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.h
src/cascadia/TerminalSettingsModel/ActionArgs.idl
src/cascadia/TerminalSettingsModel/ActionArgsMagic.h
src/cascadia/TerminalSettingsModel/ActionMap.cpp
src/cascadia/TerminalSettingsModel/HashUtils.h
src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj.filters
src/host/alias.cpp
src/host/ut_host/TextBufferTests.cpp
src/inc/til/hash.h

This commit serves two purposes:
* Simplify construction of hashes for non-trivial structs
This is especially helpful for ActionArgs
* Improve hash quality by not needlessly throwing away entropy
`til::hasher` is modeled after Rust's `std::hash::Hasher` and works similar.
The idea is simple: A stateful hash function can hash multiple unrelated fields,
without loosing entropy by running a finalizer after hashing each interim field.
This is especially useful for modern hash functions, which often have a wider
internal state than the output width. Additionally this improves performance
for hash functions with complex finalizers.
Most of this is of course a bit moot right now, considering that `til::hasher`
is still based on STL's FNV1a algorithm, which offers a very poor hash quality.
But …

Introduce til::hasher for sucessive hashing of structs

---

src/cascadia/TerminalSettingsEditor/Appearances.cpp
src/cascadia/TerminalSettingsEditor/Appearances.h
src/cascadia/TerminalSettingsEditor/GlobalAppearance.h
src/cascadia/TerminalSettingsEditor/Interaction.h
src/cascadia/TerminalSettingsEditor/Launch.h
src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/MainPage.h
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj.filters
src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl
src/cascadia/TerminalSettingsEditor/Profiles.cpp
src/cascadia/TerminalSettingsEditor/Profiles.h
src/cascadia/TerminalSettingsEditor/Profiles.idl
src/cascadia/TerminalSettingsEditor/Profiles.xaml
src/cascadia/TerminalSettingsEditor/Utils.h

Cleans up `ProfileViewModel`, `Profiles`, and `ProfilePageNavigationState` to move all of the view model responsibilities over to `ProfileViewModel`. We don't actually store the `ProfilePageNavigationState` anymore. We only use it as a way to transfer information to the new page.
#9207 - Apply MVVM
- I pulled out `ProfileViewModel` into its own file to keep things cleaner. It was getting pretty big.
- The font lists are now stored in a static location in `ProfileViewModel`, which means that we can reuse the same list between pages.
- the profile pivot was also moved to the `ProfileViewModel` and stored as a static value.
✅ pivot behavior is the same
✅ font list is still populated

Apply MVVM for profiles in SUI

---

.vsconfig

Apparently it's called the Windows 11 SDK now

Apparently it's called the Windows 11 SDK now

---

src/cascadia/LocalTests_SettingsModel/KeyBindingsTests.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.h
src/cascadia/TerminalSettingsModel/ActionArgs.idl
src/cascadia/TerminalSettingsModel/ActionArgsMagic.h
src/cascadia/TerminalSettingsModel/ActionMap.cpp
src/cascadia/TerminalSettingsModel/HashUtils.h

00fe2b0 made the mistake of hashing the pointer of `NewTerminalArgs` instances
instead of their content. This commit calls `NewTerminalArgs::Hash` instead.
* New test passes ✅

Fix hashing of NewTerminalArgs

---

build/pipelines/release.yml

Microsoft will be providing a Software Bill of Materials for our products. This onboards the Windows Terminal product to the common engineering system task that can scavenge for this information within our build project (already recorded for internal compliance reasons) and present it in a machine-readable interchange format.
See also: https://devblogs.microsoft.com/engineering-at-microsoft/generating-software-bills-of-materials-sboms-with-spdx-at-microsoft/
This does not yet include packaging and distributing the SBOM with our final packages. We are waiting for that tooling to come online for MSIX. Guidance is "Coming Soon™️."
- https://github.com/microsoft/dropvalidator/issues/216 - `cgmanifest.json` are not being pulled in yet, but I've been told internally this will fix it. I will …

Enable SBOM generation for Windows Terminal

---

src/buffer/out/textBuffer.cpp

Properly handle UTF-16 surrogates when calculating the position of matched pattern.
Fix #8709
https://github.com/microsoft/terminal/blob/b88ffb21b0725331877ba76bac5a79a4c21eaa03/src/buffer/out/search.cpp#L335-L339
use `Utf16Parser::Parse` to handle code points from U+010000 to U+10FFFF in UTF-16.
also the case by @mas90  https://github.com/microsoft/terminal/issues/8709#issuecomment-884915485:

Parse UTF-16 surrogates pairs for calculating pattern's position

---

src/cascadia/TerminalSettingsModel/IInheritable.h

Consolidates the `INHERITABLE_SETTING` and `INHERITABLE_NULLABLE_SETTING` macros by introducing `_BASE_INHERITABLE_SETTING`.
Closes #9211

Consolidate IInheritable macros

---

src/host/screenInfo.cpp

When a conhost window is resized, the cursor is temporarily hidden, and the visibility is restored when the resize is finished. However, it wasn't taking into account that the cursor may already have been hidden to start with, in which case it would mistakenly force the cursor to be visible. This PR now saves the initial state of the visibility, so it can be correctly restored.
I've manually verified that this fixes the issue, and the cursor is no longer forced to be visible when the window is resized.

Preserve cursor visibility on resize in conhost

---

src/cascadia/TerminalControl/ControlCore.cpp
src/interactivity/win32/Clipboard.cpp

When copying content from the terminal to the clipboard (with
formatting), a default background color needs to be set to fill the
unused area of the pasted block. Prior to this PR, that color was not
correctly set, so the pasted content did not match what was seen on
screen.
Windows Terminal previously used the default background from the initial
color scheme, so it didn't take palette changes into account.
OpenConsole did use the active default color, but didn't take the
reverse screen mode into account, so could end up using the foreground
rather than the background color.
In both case I've changed the code to lookup the runtime colors in the
same way that renderer does, so they should now match what is seen on
screen.
I've manually confirmed that the background color is now correctly …

Use the correct background color when copying to clipboard

---

src/cascadia/PublicTerminalCore/HwndTerminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/terminalrenderdata.cpp
src/host/renderData.cpp
src/host/renderData.hpp
src/host/ut_host/VtIoTests.cpp
src/renderer/base/renderer.cpp
src/renderer/inc/IRenderData.hpp

The `IRenderData::GetDefaultBrushColors` method was intended to return
the default attributes from which the renderer would calculate the
default background color. It should always have been returning a default
`TextAttribute` object, but the conhost `RenderData` implementation was
mistakenly returning the active attributes instead. This resulted in
margin areas being filled with the wrong color. To correct that, this PR
simply replaces all usage of `GetDefaultBrushColors` with hardcoded
default attributes.
I've manually checked the test case described in issue #11976 and
confirmed that the conhost margin areas are now correctly filled with
the default background color.
Closes #11976

Replace GetDefaultBrushColors with hardcoded default attributes

---

src/cascadia/TerminalSettingsModel/PowershellCoreProfileGenerator.cpp

Ensures the PowerShell Core profile's commandline is quoted. This allows
the profile to work correctly if there are files in place on the machine
(e.g. one called `C:\Program`) that prevent `CreateProcess()` from
invoking the un-quoted commandline.
Created a file called `C:\Program` and opened the PowerShell profile in
terminal.
Closes #11717

Ensure PowerShell Core profile commandline is quoted

---

src/cascadia/TerminalApp/TerminalPage.cpp

fix #11432
compiled and verified that "\~"  ,  "/usr/bin"  ,  "~/.config" and "/" as stating directory didn't get relative path resolve
verified that '.' did

fix ~ not work as startingDirectory for WSL

---

src/cascadia/TerminalSettingsEditor/AddProfile.cpp
src/cascadia/TerminalSettingsEditor/AddProfile.h
src/cascadia/TerminalSettingsEditor/AddProfile.idl
src/cascadia/TerminalSettingsEditor/AddProfile.xaml

- Settings > Add a new profile
- Disable "Duplicate" button until a profile is selected

Disable duplicate button without selected profile

---

build/pipelines/release.yml
src/cascadia/ShellExtension/dllmain.cpp
src/cascadia/TerminalApp/Resources/en-US/ContextMenu.resw
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalAppLib.vcxproj

This is so that they can be localized separately, and into more
languages.

Move the context menu strings to a separate resw compartment

---

src/propsheet/ColorsPage.cpp

When editing colors in the conhost properties dialog, and you select an
item to update (e.g. Screen Text, or Screen Background), the associated
color swatch for that item would be highlighted, but the RGB color
values weren't updated to reflect that selection. This PR fixes it so
the RGB values are now correctly refreshed.
I just copied the three lines used up update the color value fields from
the code that handles changes to the color swatch selection. I didn't
think it was worth pulling those three lines out into a separate
function.
I've manually verified that the RGB values are now refreshed correctly
when selecting a color item to update.
Closes #1220

Update RGB values when selecting a conhost color property

---

src/cascadia/TerminalSettingsEditor/Profiles.cpp

This PR makes sure profile appearances in SUI set both focused and unfocused members of the control. I totally forgot about the fact that the control is _unfocused_ in the SUI. Verified manually, I didn't think it deserved a gif.
* regressed in #11619
* Closes #11893
* I work here

Fix scheme previewing on Appearances page of SUI

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/AppLogic.idl
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalSettingsEditor/Launch.cpp
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.h
src/cascadia/TerminalSettingsModel/ActionArgs.idl
src/cascadia/TerminalSettingsModel/AllShortcutActions.h
src/cascadia/TerminalSettingsModel/ApplicationState.cpp
src/cascadia/TerminalSettingsModel/ApplicationState.h
src/cascadia/TerminalSettingsModel/ApplicationState.idl
src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h
src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/IslandWindow.h

This commit adds additional information to the persisted window layouts.
- Runtime tab titles
- Focus, Maximized, and Fullscreen modes.
Also,
- Adds actions for Set{Focus,FullScreen} that take a boolean
to work in addition to the current Toggle{Focus, Fullscreen} actions.
- Adds SetMaximized that takes a boolean.
This adds the capability to maximize (resp restore) a window using
standard terminal actions.
This also involves hooking up a good amount of state tracking between
the terminal page and the window to see when maximize state has changed
so that it can be persisted.
- These actions are not added to the default settings, but they could be.
The intention is that they could assist with automation (and was originally)
how I planned on persisting the state instead of augmenting the …

Persist Runtime TabTitle and  Maximize/Focus/Fullscreen states

---

doc/specs/#653 - Quake Mode/#653 - Quake Mode.md

Fixed typo.
```
Quiting -> Quitting
```

Fix typo in #653 - Quake Mode.md

---

src/cascadia/TerminalControl/TermControl.cpp

I'm not 100% sure that this is the right solution, but it does seem to work well enough. This is unfortunately a classic heisenbug. It was already hard enough to repro originally, but attaching a debugger made it totally impossible to hit. 
My theory is that it's possible for the GotFocus event to fire before the LayoutUpdated event does. If that were to occur, then we'd try to turn on the cursor timer before it exists, gracefully do nothing, then create the timer. In that case, we'd never get a subsequent message to start the blinking. 
I tested that theory by just initializing the cursor blinker to our `_focused` state. In that case, if the control has already been focused at the time of the LayoutUpdated event, then we can init the cursor to the correct state. Testing that out, I …

Initialize cursorOn to match focus state

---

scratch/ScratchIslandApp/Package/Package.appxmanifest
src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest

As discussed. We're not going to be able to consistently get bugfixes below Vb anymore, so let's leave that as the MinVersion, so we can start adding features that depend on those bugfixes.

Bump the minversion of the Terminal

---

.github/actions/spelling/expect/expect.txt
src/inc/til/coalesce.h

This commit fixes the compilation under VS 2022.1 and clang, by evaluating a
`static_assert(false)` safety check only when the template is instantiated.
This is achieved by making the assertion depend on the template parameter.
* Host.EXE compiles under VS 17.1.0 Preview 3.0 (32110.40.d17.1) ✅

Fix compilation under VS 2022.1

---

src/cascadia/TerminalConnection/ConptyConnection.cpp
src/types/Environment.cpp
src/types/inc/Environment.hpp
src/types/precomp.h

Revert "Fix environment block creation (#7401)"
This reverts commit 7886f16714a734fe1a122b9f22986d283d0f0a41.
(cherry picked from commit e46ba65665610f2544414618b8a0de00c03e7903)
Revert "Always create a new environment block before we spawn a process (#7243)"
This reverts commit 849243af995a05bcce046df010894b60d20ea145.
(cherry picked from commit 4204d2535c82ebeef4f27c306b39ffbcca51a881)
(cherry picked from commit f8e8572c2314004da9c355ef4bfec33a56d54646)
(cherry picked from commit cb4c4f7b739708a4908067918f3e3f31bce1cfbf)
(cherry picked from commit afb0cac3e323f80d4df4804be2155bf317d8c33d)
(cherry picked from commit b25dc74a1d0ef47cf3d2fe599b9f788e89ccbc2f)
(cherry picked from commit 5f7c66bc0cc5d3f217a723ee7f92904fec6be91d)
Fixes #7418

Combined revert of Environment Block Changes

---

src/cascadia/LocalTests_SettingsModel/TerminalSettingsTests.cpp
src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/MainPage.h
src/cascadia/TerminalSettingsEditor/MainPage.idl
src/cascadia/TerminalSettingsEditor/MainPage.xaml
src/cascadia/TerminalSettingsEditor/SettingContainer.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/features.xml

Title says it all. This is on by default, and we've committed to keeping it around. Having a velocity flag for it is redundant now.

Remove unused `Feature_ShowProfileDefaultsInSettings`

---

src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp

This was a simple oversight. No user profile ever has `connectionType` set, because why would they. So even for the Azure Shell, which needed this, the check would fail and we'd forget to duplicate the connectionType to the new profile.

Make sure to copy `connectionType` for the azure shell

---

scratch/ScratchIslandApp/SampleApp/MyPage.cpp
scratch/ScratchIslandApp/SampleApp/MySettings.h
src/cascadia/UnitTests_Control/MockControlSettings.h
src/cascadia/UnitTests_TerminalCore/MockTermSettings.h
src/cascadia/inc/ControlProperties.h

When I added these macros in #11619, the real purpose was to make sure we don't forget to add new settings to these test mocks as well. However, I totally forgot to convert those. I guess that happens with a 1300 line diff ¯\\\_(ツ)_/¯

Use ControlProperties macros everywhere

---

src/cascadia/LocalTests_SettingsModel/ProfileTests.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

In previous releases, we had the commandlines for the Command Prompt and PowerShell profiles unqualified, as `cmd.exe` and `powershell.exe`. This was bad - theoretically, that would have preferred the cmd that was in the CWD over the one in System32. Or, something could insert itself into the path, and you'd end up with a malicious `cmd.exe` before the real one.
In #11437, we made sure that the `userDefaults` are initiated with the fully qualified paths. However, that didn't fix the issue for folks who already had settings files.
In an effort to better prevent this kind of badness, if we see a profile _with a default profile guid_, AND the unqualified version of the path, then we'll stealth replace it with the fully qualified one.
* Related to #11437

Manually replace unqualified cmd, powershell paths for the default profiles

---

build/pipelines/ci.yml
build/pipelines/templates/build-console-steps.yml
build/pipelines/templates/test-console-ci.yml
build/scripts/Run-Tests.ps1

This commit moves the unit and feature tests to a separate stage, which can be retried more easily.
Closes #11858

ci: run the tests as a separate build stage

---

src/host/CursorBlinker.cpp
src/host/CursorBlinker.hpp
src/host/_stream.cpp
src/host/consoleInformation.cpp
src/host/server.h

Up until this commit inputs of any size were processed in one go.
This can lead to issues where the console lock is held by the VT parser
for long periods of time. As with other Denial of Service attack solutions
this commit solves the issue by processing text input in smaller chunks.
The 4MiB chunk size was chosen as it's approximately up to half a second
of processing time for lowest end hardware, but still enough for about
20 characters of VT per cell on a large 500x200 viewport.
Additionally the console lock was replaced with a fair ticket lock
implementation, as only fair locks guarantee us that the renderer (or other
parts) can acquire the lock, once the VT parser has finally released it.
This is related to #11794.
* No obvious crashes ✅
* No text/VT performance regression ✅
* …

Improve responsiveness of conhost/ConPTY for large inputs

---

src/cascadia/TerminalApp/AppActionHandlers.cpp

Prevents a potential null pointer crash in the export buffer action.
Manually tested.

Prevent potential null pointer crash in export buffer action

---

build/pipelines/ci.yml
build/pipelines/templates/build-console-ci.yml
build/pipelines/templates/console-ci-helix-job.yml
build/pipelines/templates/helix-processtestresults-job.yml
build/pipelines/templates/helix-runtests-job.yml
build/pipelines/templates/test-console-ci.yml

This pull request moves the Helix queuing to a separate stage outside of the build stage.

ci: move helix queueing to a separate stage as well

---

src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/atlas/pch.h

This minor change makes it possible to hot-reload the AtlasEngine shaders under
Windows Terminal. Launching an UWP application from Visual Studio doesn't
necessarily result in a working directory inside the project folder,
which makes relative file paths impractical. While the `__FILE__` macro is
compiler dependent it works under our build setup with MSVC at least.
* Shader hot-reloading works under Windows Terminal ✅

AtlasEngine: Make shader hot-reloads possible in Windows Terminal

---

src/cascadia/TerminalApp/ActionPreviewHandlers.cpp
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl

This commit correctly restores the previous opacity when the command palette
preview is cancelled. It includes an additional change in order to make the
`AdjustOpacity` setter consistent and symmetric with the `Opacity` getter.
* Open Windows Terminal command palette
* Choose "Set background opacity..."
* Cycle through the items without selecting one
* Press Escape
* Previous opacity is restored ✅

Fix opacity restore for command palette previews

---

src/host/PtySignalInputThread.cpp
src/host/VtIo.cpp
src/host/output.cpp
src/interactivity/base/HostSignalInputThread.cpp
src/interactivity/base/ServiceLocator.cpp
src/interactivity/inc/ServiceLocator.hpp

The only way to notice that LeaveCriticalSection() was called more
often than EnterCriticalSection() is by calling EnterCriticalSection()
again in the future, which will then deadlock.
Since this bug occurs on exit it wasn't noticeable with the old console lock.
With the new, stricter ticket lock this bug causes a fail-fast exit.
* Launch and then exit Windows Terminal
* OpenConsole cleanly exits ✅

Fix unbalanced unlock in PtySignalInputThread::_Shutdown

---

src/host/ft_fuzzer/fuzzmain.cpp

Less "merge conflict" and more "something that got missed in a merge".
The offending commits are
*  68ab807
*  b3fab51
The Fuzzer build doesn't run on PR, so it didn't notice this couldn't build.
@carlos-zamora as an FYI

Fix a merge conflict that broke the build

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h

`Renderer` owns the information of the hovered interval in `_hoveredInterval`
and provides no access to this information. We can only infer it from calls
to `PaintBufferGridLines`, if we're given the request to draw an underline
despite the previous call to `UpdateDrawingBrushes` not specifying it.
While it'd be possible to fix this and pass the underline flag to
`UpdateDrawingBrushes`, I personally consider this aspect of `Renderer` to be
a "leaky abstraction" as it's inherently incompatible with any engine not
working like `DxEngine`, such as the `AtlasEngine`. It's likely more
worthwhile to fundamentally change the `Renderer` architecture in the future.
* Launch pwsh.exe
* Hyperlinks are underlined when hovered ✅
* Launch WSL / bash
* Run `printf '\e]8;;http://example.com\e\\This is a …

Add support for hyperlinks to AtlasEngine

---

src/cascadia/TerminalControl/ControlCore.cpp
src/renderer/base/renderer.cpp
src/renderer/base/renderer.hpp
src/renderer/base/thread.cpp
src/renderer/base/thread.hpp

Since `AtlasEngine` prefers drawing without alpha for performance reasons,
calls to `EnableTransparentBackground` require a draw cycle.
This PR makes `Renderer::_NotifyPaintFrame` public and calls it.
Related to #9999.
* Open Windows Terminal command palette
* Choose "Set background opacity..."
* Cycling through the items without selecting one
changes background opacity immediately ✅

AtlasEngine: Redraw immediately on opacity changes

---

src/cascadia/WpfTerminalTestNetCore/WpfTerminalTestNetCore.csproj

This gets rid of warnings like
```
NU1102: Unable to find package Microsoft.NETCore.App.Host.win-x64 with version (= 3.1.21)
- Found 1 version(s) in TerminalDependencies [ Nearest version: 3.1.18 ]
```
Technically, there's a `NETCore.App.Host.3.1.21` that's out now. We _could_
migrate to that, but then we'd have to make sure to manually re-upload that
nuget package to our nuget feed, and then we'd still get this warning the
next time that package is updated.
Theoretically, there's a 6.x version too, but considering this is a debugging
tool, we don't care all that much.

Pin the `NETCore.App.Host` version to appease nuget

---

src/cascadia/Remoting/WindowManager.cpp
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalSettingsEditor/GlobalAppearance.cpp
src/cascadia/TerminalSettingsEditor/GlobalAppearance.h
src/cascadia/TerminalSettingsEditor/GlobalAppearance.idl
src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
src/cascadia/WindowsTerminal/AppHost.cpp
src/features.xml

This will turn the feature on always from this point on. That means 1.13 Stble
would be the first Stable release to have this feature (unless we cherry-pick
this to 1.12 stable, which we may)

Remove the Tray Icon from velocity

---

src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/TermControl.cpp

More fallout from the settings refactor. Probably because testing on a Windows
10 device is hard, because you actually need a physical machine to get acrylic
to behave correctly.
Basically, the code is simpler now, but we missed the windows 10 only edge case
where acrylic can get turned on, but we forget to enable the acrylic brush, so
it just stays off.
Refer to #11619 where this regressed, and #11643, #12229, because this is just a
hard problem apparently
by-design, but it made me realize this regressed in 1.12.

Fix Opacity in Windows 10, again

---

build/packages.config
build/pgo/Terminal.PGO.props
src/cascadia/Remoting/packages.config
src/cascadia/TerminalApp/packages.config
src/cascadia/TerminalConnection/packages.config
src/cascadia/TerminalControl/packages.config
src/cascadia/TerminalSettingsEditor/packages.config
src/cascadia/TerminalSettingsModel/packages.config
src/cascadia/WindowsTerminal/packages.config
src/host/exe/packages.config

The PGO helpers NuGet had the Y2K22 bug. This receives and integrates the updated package in our project to restore NuGet functionality.

Update PGO helpers to mitigate Y2K22 bug

---

src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsModel/DefaultTerminal.h
src/cascadia/TerminalSettingsModel/DefaultTerminal.idl

Makes `Model::DefaultTerminal` an `IStringable`, which presents it as a string, when possible. This enables text search for defterm's setting. This also enables screen readers to identify the combo box items by their text content (app name, author, and version) as opposed to being treated as an item containing more text. As a part of that, I cleaned up the UIA tree to treat the item's name as "\<name\>, \<author\>, \<version\>". This is consistent with how the Settings App presents installed apps in Apps > Installed apps.
#11251 will be resolved upon verification by the accessibility team.
Verified using Narrator and Accessibility Insights.

Expose Defterm info to ComboBoxItem properly

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/Resources/en-US/Resources.resw

Expands on #9582. If the command palette finds results, the screen reader says "Suggestions available".
Makes the scenario mentioned in #7907 work.
This is sufficient for various reasons:
1. According to the bug report, saying that suggestions are available is sufficient
> Screen reader should provide the results info on searching commands like 10 results found or suggestions available when there are any search results (Source: #7907)
2. This is common practice. Settings app and XAML Controls Gallery do this for their search box.
Also, the user should be able to know how many results were found by tabbing/selecting a result item. When this is done, the screen reader will use `SizeOfSet` and `PositionInSet` to announce how many results were found and which one we're currently on.
Verified …

[Command Palette] Announce if suggestions were found to screen readers

---

.github/actions/spelling/expect/expect.txt
src/buffer/out/TextAttribute.cpp
src/buffer/out/TextAttribute.hpp
src/buffer/out/TextColor.cpp
src/buffer/out/ut_textbuffer/TextAttributeTests.cpp
src/cascadia/TerminalCore/TerminalDispatchGraphics.cpp
src/host/ut_host/ScreenBufferTests.cpp
src/host/ut_host/TextBufferTests.cpp
src/host/ut_host/VtRendererTests.cpp
src/inc/conattrs.hpp
src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
src/renderer/atlas/AtlasEngine.cpp
src/renderer/base/RenderSettings.cpp
src/renderer/dx/DxFontRenderData.cpp
src/renderer/dx/DxRenderer.cpp
src/renderer/vt/VtSequences.cpp
src/renderer/vt/Xterm256Engine.cpp
src/renderer/vt/paint.cpp
src/renderer/vt/vtrenderer.hpp
src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatchGraphics.cpp
src/terminal/adapter/ut_adapter/adapterTest.cpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp
src/types/UiaTextRangeBase.cpp
src/types/sgrStack.cpp

When we gave users the ability to configure how the `SGR 1` attribute
should be rendered, we described those options as "intense is bright"
and "intense is bold". Internally, though, we still referred to the `SGR 1`
attribute as bold. This PR renames all occurrences of "Bold" (when
referring to the `SGR 1` attribute) as "Intense", so the terminology is
more consistent now.
PR #10969 is where we decided on the wording to describe the `SGR 1`
attribute.
Specific changes include:
* `TextAttribute::IsBold` method renamed to `IsIntense`
* `TextAttribute::SetBold` method renamed to `SetIntense`
* `VtEngine::_SetBold` method renamed to `_SetIntense`
* `ExtendedAttributes::Bold` enum renamed to `Intense`
* `GraphicsOptions::BoldBright` enum renamed to `Intense`
* `GraphicsOptions::NotBoldOrFaint` …

Rename the "Bold" SGR attribute as "Intense"

---

src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/atlas/AtlasEngine.r.cpp
src/renderer/atlas/atlas.vcxproj
src/renderer/atlas/dwrite.cpp
src/renderer/atlas/dwrite.h
src/renderer/atlas/dwrite.hlsl
src/renderer/atlas/shader_ps.hlsl

This commit extracts DirectWrite related shader code into dwrite.hlsl
and adds support for ClearType blending.
Additionally the following changes are piggybacked into this commit:
* Some incorrect code around fallback glyph sizing was removed as
this is already accomplished by `CreateTextLayout` internally
* Hot-reload failed to work with dwrite.hlsl as the `pFileName`
parameter was missing
* Legibility of the dotted underline was improved by increasing
the line gap from 1:1 to 3:1
Part of #9999.
* Types are clear ✅

AtlasEngine: Implement ClearType blending

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/WindowsTerminal/AppHost.cpp

There are a couple places where we now bail immediately on startup, if we think the window is going to get created without any tabs. We do that to prevent a blank window from flashing on the screen when launching auto-elevate profiles. Unfortunately, those broke defterm in a particularly hard to debug way. In the defterm invocation, there actually aren't any tabs when the app completes initialization. We use the initialization to actually accept the defterm handoff. So what would happen is that the window would immediately close itself gracefully, never accepting the handoff.
In my defense, #8514, the original auto-elevated PR, predates defterm merging (906edf7) by a few months, so I totally forgot to test this when rolling it into the subsequent iterations of that PR.
* Related to: 
* …

Fix defterm in wake of auto-elevation

---

src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalSettingsModel/ActionArgs.cpp

Just like the shift+click and the alt click shortcuts, now Ctrl+Click will launch a new window with that profile, elevated.
I also found that the GenerateName wasn't updated for the elevate arg, so added that. I considered adding the following to the defaults, but decided against it. It added 10 more entries to the command palette that were only separated by the `elevate: true` param, so that didn't feel valuable. Those are posted below for posterity.
Considered new keybindings:
```jsonc
{ "command": { "action": "newTab", "index": 0, "elevate": true }, "keys": "ctrl+shift+alt+1" },
{ "command": { "action": "newTab", "index": 1, "elevate": true }, "keys": "ctrl+shift+alt+2" },
{ "command": { "action": "newTab", "index": 2, "elevate": true }, "keys": "ctrl+shift+alt+3" },
{ "command": { …
```

Add support for ctrl+click on the dropdown to launch elevated

---

src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl
src/cascadia/TerminalSettingsEditor/Profiles.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Add Elevate flag to the SUI

---

src/cascadia/TerminalApp/App.xaml
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalControl/ControlInteractivity.cpp
src/cascadia/TerminalControl/EventArgs.h
src/cascadia/TerminalControl/EventArgs.idl

Turns out, this bug only repros in Controls version 2. I'm not sure why, but it didn't repro only on main. So this fix does nothing until #11720 merges.
This PR prevents us from setting properties on the paste warning dialog unless we actually need to paste. 5f9c551b7edced4ed72a4b9694998143f96589a3 proves that settings these properties is what would cause the bug in the first place. 
I went a step further and cleaned this up a bit. This was always a little weird, having to get the `BracketedPasteEnabled` for the active control on the UI thread before we actually display the warning. In the post-#5000 future where going back to the control like this would be a x-proc hop, I figured I should just skip that entirely and plumb the `BracketedPaste` state out in the initial request. 
See also: …

Don't open a hole in the terminal window when pasting

---

src/cascadia/TerminalSettingsEditor/Appearances.h
src/cascadia/TerminalSettingsEditor/GlobalAppearance.h
src/cascadia/TerminalSettingsEditor/Interaction.h
src/cascadia/TerminalSettingsEditor/Launch.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
src/cascadia/TerminalSettingsEditor/Profiles.cpp
src/cascadia/TerminalSettingsEditor/Utils.h

This fixes a bug where several settings would not show the reset button. The root cause of this issue is two fold:
1. Hooking up `CurrentXXX`
- `GETSET_BINDABLE_ENUM_SETTING` was hooked up to the **settings** model profile object instead of the **view** model profile object. Since the settings model has no `PropertyChanged` system, any changes were directly being applied to the setting, but not notifying the view model (and thus, the view, by extension) to update themselves.
- This fix required me to slightly modify the macro. Rather than using two parameters (object and function name), I used one parameter (path to getter/setter). 
2. Responding to the `PropertyChanged` notifications
- Now that we're actually dispatching the `PropertyChanged` notifications, we need to actually respond to …

Fix broken reset button on some profile settings

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/atlas/AtlasEngine.r.cpp

This commit fixes the following issues when ClearType rendering is enabled:
* Colored glyphs are now drawn using grayscale AA, similar to all current
browsers. This ensures proper gamma correctness during blending in our
shader, while generally making no discernable difference for legibility.
* Our ClearType shader only emits fully opaque colors, just like the official
ClearType implementation. Due to this we need to force grayscale AA if the
user specifies both ClearType and a background image, as the image would
otherwise not be visible.
* Grayscale AA when drawing emojis ✅
* Grayscale AA when using a background image ✅

AtlasEngine: Fix various ClearType rendering issues

---

src/terminal/parser/IStateMachineEngine.hpp
src/terminal/parser/InputStateMachineEngine.cpp
src/terminal/parser/InputStateMachineEngine.hpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp
src/terminal/parser/stateMachine.cpp
src/terminal/parser/stateMachine.hpp
src/terminal/parser/ut_parser/StateMachineTest.cpp

There were a number of methods in the `IStateMachineEngine` interface
which controlled how the `StateMachine` interpreted escape sequences.
But essentially what it came down to was a bunch of a properties that
were always true for the `InputStateMachineEngine`, and always false for
the `OutputStateMachine` engine. To simplify the implementation, and
make things a little more efficient, I've now replaced all of those
virtual calls with a single boolean field in the `StateMachine` that is
initialised in the constructor. 
I started by adding an `isEngineForInput` parameter to the constructor
to indicate the the type of engine being passed in. But to keep things
simple for callers, and I also then added a constructor without that
parameter, which could derive the value automatically based on …

Simplify the IStateMachineEngine interface

---

src/cascadia/TerminalSettingsEditor/MainPage.xaml

According to https://github.com/microsoft/microsoft-ui-xaml/issues/1971, `PaneFooter` does not set the `SizeOfSet` or `PositionInSet` properties. However, `FooterMenuItems` does and works for our scenario. So we just replaced `PaneFooter` with `FooterMenuItems`.
Will handle #11154 upon verification from the accessibility team.
✅ Verified using Accessibility Insights
✅ "Open Json File" button can still be invoked and keyboard navigated to as expected

Fix SizeOfSet and PositionInSet for 'Open JSON File' nav item

---

src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/MTSMSettings.h

Introduced in #11416
We weren't using these macros for duplicating as well, so I forgot to duplicate a couple settings. This PR switches duplicating over to using the macros as well, which shou;d reduce future bugs. 
Also adds notes to which properties are intentionally omitted from these macros.

Use the macros for duplicating as well

---

src/interactivity/win32/SystemConfigurationProvider.cpp

The pull request fixes the issue where "sizeof" parameter was use instead of "ARRAYSIZE".
This was a pretty straight forward issue, i just replace sizeof which gives the byte size with ARRAYSIZE which give the number of elements in the array.

Replaced the sizeof parameter of the if statement with ARRAYSIZE

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/EventArgs.cpp
src/cascadia/TerminalControl/EventArgs.h
src/cascadia/TerminalControl/EventArgs.idl
src/cascadia/TerminalControl/Resources/en-US/Resources.resw
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

Basically, this is the same as #12266, but for the `SearchBoxControl`. Trickily, the ControlCore is the one that knows if there were search results, but the TermControl has to be the one to announce it.
* See also #3920

Make the SearchBox announce if it found results or not

---

build/pipelines/templates/pgo-merge-pgd-job.yml

I added a condition to exclude some of the NuGet PGO stuff when there was no build mode, but appear to not have propagated any of it in the PGD merge job. This sets it to Optimize here so it'll go through.

Add PGOBuildMode to PGD merge step

---

doc/cascadia/profiles.schema.json

Add `experimental.useAtlasEngine` to schema

---

src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h

`IDWriteTextAnalyzer::GetGlyphs` is not enough to get a
`DWRITE_SHAPING_TEXT_PROPERTIES::canBreakShapingAfter`
value that works for combining diacritical marks.
This requires an additional call to `GetGlyphPlacements`.
This commit increases CPU usage for complex text by ~10%.
* ``echo "[e`u{0301}`u{0301}]"`` prints an "e" with 2 accents ✅

AtlasEngine: Fix support for combining diacritics

---

src/internal/stubs.cpp

Since we turned this feature on in windows, and it relies on _lying
about the contents of the registry_, Terminal needs to be in on the
joke.
This will need to be reverted and serviced if we choose not to ship like
this.
Fixes #12308

Make sure Terminal Stable shows up as default on 22544+

---

src/cascadia/TerminalSettingsEditor/CommonResources.xaml
src/cascadia/TerminalSettingsEditor/Profiles_Base.cpp
src/cascadia/TerminalSettingsEditor/Profiles_Base.xaml

Adds some polish around the navigators in the profile page (i.e. "appearance" and "advanced" button) by doing the following:
- use the localized resources for the pivot on the navigators
- simplify the navigators to be buttons instead of toggle buttons
Doing so has Narrator identify these as buttons rather than toggle buttons. So now Narrator won't say that the button is "off", which just makes more sense.
✅ Narrator says "Advanced button" or "Appearance button" on the navigator
✅ The navigators look the same as before

Localize and polish Profile page navigators

---

src/cascadia/TerminalSettingsEditor/AddProfile.cpp
src/cascadia/TerminalSettingsEditor/AddProfile.xaml

When using a screen reader, the buttons on the "add a new profile" page were being read weirdly:
- "New empty profile" button read as "create new button button"
- "duplicate" button read as "duplicate button button"
It's generally standard to read out the text inside the button, so I did just that by reusing the existing localized resources. This also removes the redundant "button" that is said by the screen reader.
I also removed the unused `AutomationId` and unnecessary `Button.Content` tags. 
#11156 can be closed upon validation by the accessibility team.
✅ navigate to both buttons using Narrator; make sure it sounds right

Update accessible names for 'add profile' page buttons

---

src/cascadia/TerminalApp/App.xaml
src/cascadia/TerminalSettingsEditor/Actions.xaml
src/cascadia/TerminalSettingsEditor/AddProfile.xaml
src/cascadia/TerminalSettingsEditor/Appearances.xaml
src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml
src/cascadia/TerminalSettingsEditor/CommonResources.xaml
src/cascadia/TerminalSettingsEditor/MainPage.xaml
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.xaml
src/cascadia/TerminalSettingsEditor/Profiles_Base.xaml

- The add new profile page now uses a dropdown rather than radio buttons
- Subheaders, breadcrumb bar, buttons etc are now all centralized when the window is maximized (so they all align with the expanders now)
- We no longer override the titlebar colors and instead use the xaml defaults (these still aren't great but at least we will get the fix automatically when it happens upstream)
- Breadcrumb bar no longer has a negative margin, so there's no weird overlap that happens when the window becomes small
- The number boxes for launch size and font size now use the `Inline` placement mode rather than compact, allowing modification to the number with fewer clicks
- Textboxes now have a greater max width so they can occupy more space in the expander if needed

Fix more SUI and Rejuvenated UI issues

---

src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest
src/cascadia/TerminalApp/Resources/en-US/ContextMenu.resw

We have to do this so that the store sees us as one thing ("Windows
Terminal") and the Start menu sees us as another ("Terminal").
The store will reject our package if the value we use for "DisplayName"
here doesn't match the store's "reserved names".
This value is *not used* by the start menu.

appx: Use a different resource for the Properties DisplayName

---

build/pipelines/templates/build-console-steps.yml

We're investigating an issue where the build succeeded but something still got lost somewhere. If we had the binlogs, maybe we could diff and track it down faster.

Always publish the binlog

---

src/cascadia/TerminalSettingsEditor/CommonResources.xaml
src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml

Reducing the `MinWidth` of a toggle switch means it no longer needs a negative margin to align it correctly
Setting a different language no longer causes the toggle switch to fall out of the expander

Fix toggle switches needing a negative margin

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp

We no longer do anything when the rightmost breadcrumb is invoked
Tested manually, cannot repro #12325 anymore

Fix invoking the rightmost breadcrumb bringing you back to Profiles_Base

---

src/host/_stream.cpp

After 'must', the verb is used without 'to'. Correct: "must" or "have to".
Not required, only comment has been changed.

Fix the grammar in a comment

---

src/cascadia/TerminalApp/Jumplist.cpp

I have no idea how this is even possible to hit. If this is able to be null, then we failed to load the settings in such a catastrophic way that nothing should work. However, OP's Terminal seemed to have already loaded the settings. By all accounts, doesn't make sense.
Regardless, the code here would crash if this ever is null, so we may as well catch it.

Fix a potential crash when setting up the jumplist

---

src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml

The focus box around the color schemes combo box was getting cut off, this change adds a small margin to the stackpanel to allow space for the focus box

Fix focus box around color schemes combo box

---

.github/actions/spelling/expect/expect.txt
src/host/ut_host/VtRendererTests.cpp
src/renderer/vt/XtermEngine.cpp
src/renderer/vt/XtermEngine.hpp

This commit fixes an issue, where we failed to emit a DECTCEM sequence to hide
the cursor if it was hidden before XtermEngine's first frame was finalized.
Even in such cases we need to emit a DECTCEM sequence
in order to ensure we're in a consistent state.
* Added test✅
* Run #12401's repro steps around 30 times✅

XtermEngine: Explicitly emit cursor state on the first frame

---

src/cascadia/TerminalSettingsEditor/Appearances.xaml
src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml

Segoe Fluent isn't available on Windows 10, and doesn't stealthily ship with WinUI. So if we manually set the font family to `"Segoe Fluent Icons"`, then that will just display boxes in Win10.
This instead uses the resource `"{ThemeResource SymbolThemeFontFamily}"` which will gracefully fall back on Win10.
See:
* https://github.com/microsoft/microsoft-ui-xaml/issues/3745, which inspired this solution.
Guess what! The backgound image icons were also manually specifying this font, so they had to get updated too. I couldn't find any other `Segoe Fluent` references in the code.

Properly fall back to Segoe MDL2 for our icons on Win10

---

src/cascadia/TerminalSettingsEditor/Appearances.xaml
src/cascadia/TerminalSettingsEditor/CommonResources.xaml
src/cascadia/TerminalSettingsEditor/Profiles_Base.xaml

With the recent change to allow text boxes to be bigger, the `Browse` button that some of them have was getting cut off when the window was too narrow. This change puts the `Browse` button below the text box instead of next to it to prevent this issue.

Fix browse buttons getting cut off when the window is too narrow

---

.github/actions/spelling/expect/expect.txt
build/pipelines/release.yml

Closes #12203
[Tested here](https://microsoft.visualstudio.com/Dart/_build/results?buildId=44863418&view=results)
Tested downloading symbols for this build from MSDL!

Publish the symbols from our MSIX bundle to the public server

---

src/types/UiaTextRangeBase.cpp

This adds some validation in the `UiaTextRange` ctor for the cursor position.
#8730 was caused by creating a `UiaTextRange` at the cursor position when it was in a delayed state (meaning it's purposefully hanging off of the right edge of the buffer). Normally, `Cursor` maintains a flag to keep track of when that occurs, but Windows Terminal isn't maintaining that properly in `Terminal::WriteBuffer`.
The _correct_ approach would be to fix `WriteBuffer` then leverage that flag for validation in `UiaTextRange`. However, messing with `WriteBuffer` is a little too risky for our comfort right now. So we'll do the second half of that by checking if the cursor position is valid. Since the cursor is really only expected to be out of bounds when it's in that delayed state, we get the same result …

Validate cursor position in UIA UTR ctor

---

src/cascadia/TerminalCore/ITerminalApi.hpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/cascadia/TerminalCore/TerminalDispatch.cpp
src/cascadia/TerminalCore/TerminalDispatch.hpp
src/cascadia/TerminalCore/TerminalDispatchGraphics.cpp
src/cascadia/UnitTests_TerminalCore/TerminalApiTest.cpp
src/terminal/adapter/termDispatch.hpp

This PR updates the `ITerminalApi` and `TerminalDispatch` classes to
allow exceptions to be thrown in case of errors instead of using boolean
return values.
This brings the Terminal code into alignment with the `AdaptDispatch`
and `ConGetSet` changes made in PR #12247.
And while this isn't exactly a fix for #12378, it does at least stop the
app from crashing now.
where discussion took place: #12378
All the `TerminalDispatch` methods have had their `noexcept` specifiers
dropped, and any `try`/`catch` wrapping removed, so exceptions will now
fall through to the `StateMachine` class where they should be safely
caught and logged.
The same goes for the `ITerminalApi` interface and its implementation in
the `Terminal` class. And many of the methods in this interface have
also had their `bool` …

Allow exceptions from ITerminalApi and TerminalDispatch

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.idl

We absolutely cannot allow a defterm connection to
auto-elevate. Defterm doesn't work for elevated senarios in the
first place. If we try accepting the connection, the spawning an
elevated version of the Terminal with that profile... that's a
recipe for disaster. We won't ever open up a tab in this window.

Fix defterm + elevate by default

---

src/types/ut_types/UtilsTests.cpp
src/types/utils.cpp

Basically, some WSL distros ship fragments that replace the `commandline` with the executable for their distro (`ubuntu.exe`, etc.). We didn't expect that when we changed the `startingDirectory` for them all to `~`. 
Unfortunately, `~` is really never a valid path for a process on windows, so those distros would now fail with
```
[error 2147942667 (0x8007010b) when launching `ubuntu1804.exe']
Could not access starting directory "~"
```
If we find that we were unable to mangle `~` into the user's WSL `commandline`, then we will re-evaluate that `startingDirectory` as `%USERPROFILE%`, which is at least something sensible, if albeit not what they wanted. 
* regressed in #12315

Don't ever allow `~` as a startingDirectory

---

src/features.xml

Followup from our discussion during team sync, the 'automatic adjustment of indistinguishable text' setting is going to be enabled for dev builds only.
#12160 
Setting appears on dev build and the feature works

Enable the 'automatic adjustment of indistinguishable text' setting for Dev builds

---

.github/actions/spelling/expect/expect.txt
build/config/GitCheckin.json
build/pipelines/release.yml

We're now building a fully provenance, compliance, and security validated package (vpack) through our Release pipeline. This attaches the last phase which automates the submission into the Windows product. It will also automatically trace back the source, commit SHA, and build to the submission here from the Windows side.
* https://microsoft.visualstudio.com/Dart/_build/results?buildId=44914810&view=logs&j=dcd45bf9-728b-574c-bbda-47373b5c16e2&t=5f2db042-0803-5778-3c08-6bbbc7057964

Automate packaged submission into Windows

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Profiles with long names were having their titles cut off in the navigation view sidebar. This change adds tooltips to all nav view items so the full names can still be read.
#11353 
* [x[ I work here

Add tooltips for nav items in the SUI

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/Resources/en-US/Resources.resw

Updates this narrator announcement message to include the number of results it found. There are two versions:
* one for a singular result
* one for multiple results.
which should help with loc.
We're trying to get this in with the loc hotfix, so 👀 please 
verified with narrator locally.

Update the cmdpal narrator message to include the number of results.

---

build/pipelines/release.yml

Now that we've figured out how to publish the public symbols to the official Microsoft download server... we may as well embed the source code linking information inside of them given that it's right here on GitHub. This attempts to run our existing source linking scripts against the public copy of the symbols.

Source index the public symbols too

---

src/interactivity/base/ServiceLocator.cpp
src/interactivity/inc/ServiceLocator.hpp
src/interactivity/win32/window.cpp
src/interactivity/win32/window.hpp

AtlasEngine enables various debug options for D2D and D3D in Debug builds.
Among those are resource leak checks, which were broken in OpenConsole
due to the unclean exit in `ServiceLocator::RundownAndExit`.
This commit fixes the issue by running the destructors
of any renderers registered in the Window class first.
* Set `HKEY_CURRENT_USER\Console\UseDx` to `2`
* Run `OpenConsole.exe`
* Exit
* No exceptions are thrown ✅

AtlasEngine: Fix leak check report for OpenConsole

---

src/cascadia/TerminalApp/CommandPalette.xaml
src/cascadia/TerminalApp/SettingsTab.cpp
src/cascadia/TerminalApp/TabBase.cpp
src/cascadia/TerminalApp/TabHeaderControl.xaml
src/cascadia/TerminalApp/TabRowControl.xaml
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalControl/SearchBoxControl.xaml
src/cascadia/TerminalSettingsEditor/Profiles_Base.xaml
src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml
src/cascadia/TerminalSettingsModel/IconPathConverter.cpp

* use `FontFamily="{ThemeResource SymbolThemeFontFamily}"` where possible, in XAML
* use `FontFamily{ L"Segoe Fluent Icons, Segoe MDL2 Assets" }` in codebehind
Basically just a simple string replace.
* see also #12438
Actually, this is the last bullet in #11353, so I'm gonna say closes #11353. 
Screenshots below.

Updates all our icons to use Segoe Fluent

---

src/cascadia/LocalTests_SettingsModel/TerminalSettingsTests.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp

#12348 introduced an off-by-one bug. While the `NormalizeCommandLine` loop
should exit early when there aren't at least _two_ arguments to be joined,
the final argument-append needs to happen even if just _one_ argument exists.
This commit fixes the issue and introduces changes to additionally monitor
the early loop exit, as well as the call to `ExpandEnvironmentStringsW`.
* All `TerminalSettingsTests` tests pass ✅

Fix off-by-one bug in NormalizeCommandLine

---

src/cascadia/TerminalApp/App.xaml
src/cascadia/TerminalApp/TerminalPage.cpp

This has been a saga.
Basically, any resources in `App.xaml` aren't going to be able to reference other theme-aware resources. We can't change the theme of the app at runtime, only elements within the app. So we can't use `ApplicationPageBackgroundThemeBrush` in app.xaml, because it will ALWAYS be evaluated as the OS theme version of that brush.
* regressed in #12326
* See also #10864
* #3917 CANNOT be fixed in the same way. We're lucky here that the TabView uses a `{ThemeResource TabViewBackground}` in markup to set the bg. We're not similarly lucky with the Pane one.

Manually set the colors of the TabViewBackground

---

src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/Pane.h

I believe this fixes #12383, but I can't seem to find a way to set up a N SKU VM to confirm this.

DON'T default-construct the `MediaPlayer`

---

src/interactivity/onecore/ConIoSrvComm.cpp

As noted in #6759:
> `RtlCreateUnicodeString` creates a copy of the string on the process heap and the `PortName` variable has local-scope. The string doesn't get freed with `RtlFreeUnicodeString` before the function returns creating a memory leak.
> `CIS_ALPC_PORT_NAME` is a constant string and the `PortName` variable should instead be initialized using the `RTL_CONSTANT_STRING` macro:
>
> ```c++
> static UNICODE_STRING PortName = RTL_CONSTANT_STRING(CIS_ALPC_PORT_NAME);
> ```
I actually built this in the OS repo to make sure it'll still build, because this code doesn't even build outside Windows.
* I work here.

Fix a memory leak in onecore interactivity

---

build/pipelines/release.yml
build/scripts/Copy-ContextMenuResourcesToCascadiaPackage.ps1
src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest
src/cascadia/CascadiaPackage/Resources/en-US/Resources.resw

We chose to use the "ContextMenu" resource compartment when we
changed the package name to Terminal in #12264 because it was more
broadly localized than the rest of the application.
It appears as though some platform features have trouble with the
"more qualified" resource paths that #12264 required.
To fix this, we will:
1. Copy all of the ContextMenu localizations into CascadiaPackage's
resource root
2. Switch all manifest resource paths to use resources from the package
root.
Regressed in #12264
Closes #12384
Closes #12406 (tracked in microsoft/powertoys#16118)

Copy localized strings from ContextMenu into the resource root

---

build/pipelines/fuzz.yml

Modifies the OneFuzz CI Job so that it attempts to read the notification config from a file rather than the command line.
Potential oversight in #10431.
Noticed that the CI job was failing on main, so took a look. According to the [docs](https://github.com/microsoft/onefuzz/blob/7f7d76fa7fd0e351f8ffd8c7aa5c5729e30f9e8f/docs/notifications.md#implementation), files should be referenced using `@./` notation.

Potentially fix Submit OneFuzz CI Job

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalSettingsEditor/Launch.cpp
src/cascadia/TerminalSettingsEditor/Launch.h
src/cascadia/TerminalSettingsEditor/Launch.idl
src/cascadia/TerminalSettingsEditor/Launch.xaml
src/features.xml

Removes the `Feature_PersistedWindowLayout` feature flag so that it's always enabled.
Closes #12422

Remove "Window Persistence" feature flag

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

"Acrylic material" is the official name as used on Microsoft Docs
and should ensure it gets properly translated in all languages.
We originally intended to replace the strings with "acrylic transparency",
but "acrylic material" is actually the official term on Microsoft Docs.

Replace "acrylic" with "acrylic material" in i18n strings

---

src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/AppLogic.idl
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.idl
src/cascadia/TerminalApp/TerminalPage.xaml

Somehow, the controls v2 update caused an issue where if you as much as _load_ a content dialog when there's already one open, we get holes in the terminal window (#12447)
This commit introduces logic to `TerminalPage` to check whether there is a content dialog open before we try to load another one. 
Can no longer repro #12447

No longer load content dialogs when there is already one being shown

---

src/cascadia/LocalTests_SettingsModel/TerminalSettingsTests.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp

Prevents a crash that could occur when invoking `wt C:\`
Updates `CascadiaSettings::NormalizeCommandLine()` to check that there are a suitable number of command line arguments to be concatenated together, to prevent accessing an array index in `argv` that doesn't exist.
Also prevents a test flake that could occur in `TerminalSettingsTests::CommandLineToArgvW()`, due to generating an empty command line argument.
Added a test, and checked that invoking each of the command lines below behaved as expected:
```
wtd C:\ # Window pops up with [error 2147942405 (0x80070005) when launching `C:\']
wtd C:\Program Files # Window pops up with [error 2147942402 (0x80070002) when launching `C:\Program Files']
wtd cmd # cmd profile pops up
wtd C:\Program Files\Powershell\7\pwsh -WorkingDirectory C:\ # …
```

Don't crash trying to parse a command line that's a directory

---

src/cascadia/ut_app/TerminalApp.Unit.Tests.manifest

In PR #12462, a new `maxversiontested` entry was added to the
_WindowsTerminal.manifest_ file which now gets propagated to the
_TerminalApp.Unit.Tests.manifest_ file whenever a full build is
executed. This PR is just committing the updated test manifest.
where discussion took place: #12543

Commit updated TerminalApp.Unit.Tests.manifest file

---

src/cascadia/TerminalApp/CommandPalette.cpp

Fixes two crashes amounting to 14% of our crash burden in Simulated
Selfhost. I can't reproduce this organically, but I was able to do so by
forcing the command palette to be empty.

Protect the command palette against being paged with no items

---

src/renderer/atlas/shader_ps.hlsl

The previous implementation only inverted the RGB values of the cell,
but failed to account for situations where the `color` is transparent,
which is the case when `backgroundOpaqueMixin` is 0 (for instance if
acrylic backgrounds are enabled). In these situations the alpha
component remained 0 which caused the cursor to be invisible.
For some inexplicable reason this issue is only visible on a HDR display,
even though it should also effect regular ones. God knows why.
With this commit the cursor texture is treated as a mask that inverts the color.
We use branching here, because I couldn't come up with a more clever solution.
* Cursor is visible on a HDR display with acrylic background ✅
* TBD performance benchmark for `[branch]` ❌

AtlasEngine: Fix inverted cursor alpha

---

src/cascadia/TerminalApp/App.xaml

Changes the tab view BG to `#e8e8e8`, as discussed in mail thread.
Closes #12398

Update light theme tab background for greater contrast.

---

.github/actions/spelling/allow/microsoft.txt
build/pipelines/release.yml
build/scripts/Patch-ManifestsToWindowsVersion.ps1
common.openconsole.props
custom.props
scratch/ScratchIslandApp/Package/Package.wapproj
scratch/ScratchIslandApp/SampleApp/SampleAppLib.vcxproj
scratch/ScratchIslandApp/SampleApp/dll/SampleApp.vcxproj
scratch/ScratchIslandApp/SampleApp/packages.config
scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj
scratch/ScratchIslandApp/WindowExe/packages.config
src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
src/cascadia/LocalTests_SettingsModel/SettingsModel.LocalTests.vcxproj
src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/dll/TerminalApp.vcxproj
src/cascadia/TerminalApp/packages.config
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
src/cascadia/TerminalSettingsEditor/packages.config
src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
src/cascadia/TerminalSettingsModel/dll/Microsoft.Terminal.Settings.Model.vcxproj
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/cascadia/WindowsTerminal/packages.config
src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj
src/cppwinrt.build.pre.props

This pull request is broken down into a few individually reviewable units.
This required some changes in how we download artifacts to make sure
that we could control which version of Windows we were processing in any
individual step.
We're also going to patch the package manifest on the Windows 11 version
so the store targets it more specifically.
On top of the prior three commits, this lets us ship a Windows 11
package that costs only ~15MB on disk. The Windows 10 version, for
comparison, is about 40.
common.openconsole.props is a pretty good place to stash the XAML
version since it is included in every project (including the WAP
project (unlike the C++ build props!)).
I've gone ahead and added a "double dependency" on multiple XAML
versions. We'll toggle them with a build flag.
This …

build: ship a Win11 build of Terminal that's <=half the size

---

build/pipelines/feature-flag-ci.yml
build/pipelines/templates/build-console-ci.yml
src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
src/features.xml
src/host/proxy/Host.Proxy.vcxproj

This is intended to be a PR triggered build that only runs when
features.xml has been touched, to validate that the disabled features do
not cause compilation errors.

Add a pipeline that validates builds that touch features.xml

---

src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h

From MSFT:36797001. Okay so this is only .22% of our crashes, but every little bit helps, right?
Turns out this is also hitting in:
* MSFT:35726322
* MSFT:34662459
and together they're a fairly hot bug. 
There's a large class of bugs where we might get a callback to one of our event handlers when we call `app.Close()` in the `AppHost` dtor. This PR adds manual revokers to these events, and makes sure to revoke them BEFORE nulling out the `_window`. That will prevent callbacks during the rest of the dtor, when the `_window` is null.

Fix a crash setting the hotkey during teardown

---

src/server/IoDispatchers.cpp

2b202ce6 introduced a bug, where FreeProcessData was called without the console
lock being held. The previous code can be found in 40e3dea, on line 441-454.
None, as this fix is purely theoretic, but it matches the stack trace
and 40e3dea clearly wasn't correctly ported to strict C++ either.

Fix fail-fast due to unlocked FreeProcessData call

---

src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/host/ut_host/TextBufferTests.cpp

Fixes RTF generation for text with Unicode characters.
Added some unit tests.
Ran the following in PowerShell and copied the emitted text into WordPad.
```pwsh
echo "This is some Ascii \ {}`nLow code units: á é í ó ú `u{2b81} `u{2b82}`nHigh code units: `u{a7b5} `u{a7b7}`nSurrogates: `u{1f366} `u{1f47e} `u{1f440}"
```

Fix RTF generation for Unicode characters

---

build/pipelines/release.yml

in #12560, @dhowett split the build to Win10 and Win11. A few of the path variables didn't manage to move along with it in the Vpack pipeline.

Fix release YML paths for VPACK for Win10/11 split

---

src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

This makes it so that the settings.json backups are no longer created when the user saves their settings via the Settings UI.
Closes #11703

Stop making settings.json backups

---

.github/actions/spelling/allow/allow.txt
src/cascadia/TerminalControl/TermControl.xaml

BODGY: Controlsv2 changed the size of the scrollbars from 16dips to
12dips. This is harder for folks to hit with the mouse, and isn't
consistent with the rest of the scrollbars on the platform (as much
as they can be).
To work around this, we have to entirely copy the template for the
ScrollBar into our XAML file. We're then also re-defining
ScrollBarSize here to 16, so that the new template will pick up on
the new value.
This is kinda a pain, and we have to be careful to be sure to ingest
an updated version of the template any time we update MUX. The
latest Controlsv2 version of the template can be found at:
https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/CommonStyles/ScrollBar_themeresources.xaml#L218
We're also planning on making this adjustable in the future
(GH#9218), …

Make the Scrollbar 16dips again

---

src/cascadia/TerminalApp/App.xaml

Again, to reflect continuing discussion with the WinUI team. A doc may have been misread - these are the colors they're proposing, which are generally a lot better.
See also: #12400, #12356, #12398

Update the tab colors some more

---

src/host/init.cpp

This regressed in 2b202ce6, which removed `ACTCTX_FLAG_RESOURCE_NAME_VALID`
during `CreateActCtxW` under the assumption that an executable only has
one manifest. conhost has two however and we need to pick the correct one.
On OpenConsole this causes the expected `ERROR_SXS_PROCESS_DEFAULT_ALREADY_SET`.
Closes MSFT:38355907

Fix activation context generation for conhost

---

src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
src/features.xml
src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/base/FontCache.h
src/renderer/base/lib/base.vcxproj
src/renderer/base/lib/base.vcxproj.filters
src/renderer/dx/DxFontInfo.cpp
src/renderer/dx/DxFontInfo.h
src/renderer/dx/DxFontRenderData.cpp
src/renderer/dx/DxFontRenderData.h
src/renderer/dx/DxRenderer.cpp

By replacing `IDWriteFontSetBuilder2::AddFontFile` with
`IDWriteFactory5::CreateFontFileReference` and
`IDWriteFontSetBuilder1::AddFontFile` we add nearby
font loading support for Windows 10, build 15021.
This commit also fixes font fallback for AtlasEngine,
which was crashing during testing.
Finally it fixes a bug in DxEngine, where we only created a "nearby" font
collection if we couldn't find the font in the system collection. This doesn't
fix the bug, if the font is locked or broken in the system collection.
This is related to #11648.
* Build a Debug version of Windows Terminal
* Put Jetbrains Mono into the writeable AppX directory
* Jetbrains Mono is present in the settings UI ✅
* DxEngine works with Jetbrains Mono ✅
* AtlasEngine works with Jetbrains Mono ✅

Fix Windows 10 support for nearby font loading

---

src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalSettingsEditor/Profiles_Base.xaml

After the dialog is displayed, always clear it out. If we don't, we won't be able to display another!
* regressed in #12517.

Fix showing a dialog multiple times

---

doc/cascadia/profiles.schema.json
rectify-trailing-commas

Fixed #12639
Ran the file through a linter to check validity.

Remove trailing commas that break the json schema

---

src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

People get confused about this. This should help. It doesn't really fix it, but it should help.

Add some disclaimer text to the schemes page

---

src/cascadia/TerminalApp/MinMaxCloseControl.xaml

Just look at the screenshot. Above is before, below is now.
These paths were taken straight from WinUI versions of these icons, thanks @pratikone for the alley oop.

Round our Maximize button to match ControlsV2 styles

---

src/internal/stubs.cpp

This reverts commit 457738e388a60e3d2d62736e006e4e407d5e81e8.
Well, yeah.

Revert "Make sure Terminal Stable shows up default on 22544+"

---

src/renderer/atlas/AtlasEngine.cpp

The `bg != _r.backgroundColor` invalidation check wasn't symmetric with
us setting `_r.backgroundColor` to `bg | _api.backgroundOpaqueMixin`.
Due to this, when the `backgroundOpaqueMixin` changed,
we didn't always update the const buffer appropriately.
* Enable window transparency (`backgroundOpaqueMixin == 0x00000000`)
* Maximize window (ensure we have gutters in the first place)
* Disable window transparency (`backgroundOpaqueMixin == 0xff000000`)
* Gutters are filled ✅

AtlasEngine: Fix ConstBuffer invalidation for background color changes

---

.github/actions/spelling/allow/apis.txt
src/cascadia/Remoting/Monarch.cpp
src/cascadia/Remoting/Monarch.idl
src/cascadia/Remoting/WindowManager.cpp
src/cascadia/Remoting/WindowManager.h
src/cascadia/UnitTests_Remoting/RemotingTests.cpp

This fixes a pair of inbox bugs, hopefully.
* MSFT:35731327
* There's a small window where a peasant is being created when a monarch is exiting. When that happens, the new peasant will try to tell itself (the new monarch) when the peasant was last activated, but because the window hasn't actually finished instantiating, the peasant doesn't yet have a LastActivatedArgs to tell the monarch about.
* MSFT:32518679 (ARM version) / MSFT:32279047 (AMD64 version)
* This one's tricky. Not totally sure this is the fix, bug assuming my hypothesis is correct, this should fix it. Regardless, this does fix a bug that was in the code.
* If the king dies right as another window is starting, right while the new window is starting to ProposeCommandline to the monarch, the monarch could die. If it does, the …

Fix a pair of crashes, likely related to defterm

---

src/renderer/base/renderer.cpp
src/types/viewport.cpp

This removes one source of potential integer overflows from the Viewport class.
Other parts were left untouched, as this entire class of overflow issues gets
fixed all at once, as soon as we replace COORD with til::coord (etc.).
* Call `ScrollConsoleScreenBufferW` with out of bounds coordinates

Fix overflow in Viewport::FromDimensions

---

src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/atlas/dwrite.hlsl
src/renderer/atlas/shader_ps.hlsl

Many articles I read while writing this engine claimed that GPUs can't
do branches like CPUs can. One common approach to branching in GPUs is
apparently to "mask" out results, a technique called branch predication.
The GPU will simply execute all instructions in your shader linearly,
but if a branch isn't taken, it'll ignore the computation results.
This is unfortunate for our shader, since most branches we have are
only very seldomly taken. The cursor for instance is only drawn
on a single cell and underlines are seldomly used.
But apparently modern GPUs (2010s and later?) are actually entirely
capable of branching, _if_ all lanes ("pixels") processed by a
wave (""GPU core"") take the same branch.
On both my Nvidia GPU (RTX 3080) and Intel iGPU (Intel HD Graphics 530)
this change has a …

AtlasEngine: Reduce shader power draw with explicit branching

---

src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj

This regressed recently in cfaa315.
Initially I tried to migrate TestHostApp to C++/WinRT, but due to the
unbearable compile times I've reverted it back to C++/CX (>20x difference).
Unfortunately I then forgot to fix the underlying issue before submitting a PR.

Fix broken TestHostApp build

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

This commit fixes a stray exception during settings loading,
caused by a failure to obtain the app's extension catalog.
I'm unable to replicate the issue. ❌
However an error log was provided in #12305 with which
the function causing the exception could be determined.

Fix "Element not found" error during settings loading

---

build/pipelines/release.yml

The store did not like when I uploaded two Windows Terminal packages
built on the same date, because the appxbundle version defaulted to
YYYY.MMDD.something.
There is a risk that using *this* version number will fail because it is
thousands of numbers less than "2022". We'll have to see if the store
rolls it out properly. I cannot find any documentation on how the store
rolls out *bundle* versions (it is very aware of .appx versions...).
A local test with 1.14.72x (Preview) published via the store seems to
have worked.

Fix the appxbundle version to be the appx version

---

src/cascadia/WindowsTerminal_UIATests/WindowsTerminal.UIA.Tests.csproj
src/cascadia/WindowsTerminal_UIATests/app.config
src/host/ft_uia/Host.Tests.UIA.csproj
src/host/ft_uia/app.config
src/tools/vtapp/App.config
src/tools/vtapp/VTApp.csproj

Closes #12670 
Visual Studio 2022 offered to upgrade .NET Framework from an unsupported 4.5 to a supported 4.8.  I let it do its thing (and undid a number of whitespace-only changes that aren't necessary).  The project still builds after this.  The UIA tests fail to run but I think that is preexisting and will be filing a new issue momentarily.
The solution compiles in VS2022 (except for #12673).

Update .NET from unsupported 4.5 to 4.8 to silence VS2022

---

src/cascadia/LocalTests_SettingsModel/DeserializationTests.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

After this commit we only set the default fields of a profile - primarily the
name field - as late as possible, after layering has already completed.
This ensures that we pick up any modifications from fragments.
* Add a fragment at
`%LocalAppData%\Microsoft\Windows Terminal\Fragments\Fragment\fragment.json`
with
`{"profiles":[{"updates":"{61c54bbd-c2c6-5271-96e7-009a87ff44bf}","name":"NewName"}]}`
* Windows PowerShell profile is created with the name "NewName" in settings.json ✅

Allow fragments to override the name of new profiles

---

src/renderer/uia/UiaRenderer.cpp

`std::basic_string_view::substr` throws an exception if the first argument
(offset) is out of range. If UIA is running, this creates _a lot_ of exceptions
and associated log output. This trivial change takes care of that.

Fix exception spam if UIA is running

---

src/host/ut_host/ApiRoutinesTests.cpp

`WideCharToMultiByte` doesn't write a final null-byte by default.
`til::u16u8` avoids the problem.
* Test passes in Debug builds ✅

Fix uninitialized memory access in GetConsoleTitleA test

---

src/renderer/atlas/AtlasEngine.h
src/renderer/atlas/shader_ps.hlsl

HLSL uses 32-bit booleans, while C++ uses 8-bit ones aligned by 32-bit.
This meant that the shader was accessing uninitialized memory
forcing ClearType blending to be randomly enabled.
This regressed in commit 5964060.
* ClearType blending works ✅
* Enabling transparent backgrounds forces grayscale blending ✅

AtlasEngine: Fix ClearType being always enabled

---

src/host/history.cpp
src/host/ut_host/CommandLineTests.cpp

The legacy console used to use case-sensitive history deduplication and
this change reverts the logic to restore ye olde history functionality.
This commit additionally changes the other remaining `std::equal` plus
`std::towlower` check into a `CompareStringOrdinal` call,
just because that's what MSDN suggests to use in such situations.
* Enter `test /v`
* Enter `test /V`
* Browsing through the history yields both items ✅

Make conhost history deduplication case-sensitive

---

src/inc/test/CommonState.hpp

The x86 Conhost UTs were failing because--when run in a specific order
(SearchTests, then SelectionInputTests)--PrepareGlobalScreenBuffer would
attempt to enable painting on a renderer that was dead and gone and
pushing up daisies.

Clear out g.pRender on cleanup so further tests don't explode

---

src/host/_stream.cpp

Fixes a bug in ConHost where Narrator wouldn't read the deleted letter after the user pressed backspace.
MSFT:31748387
`WriteCharsLegacy()` already calls `NotifyAccessibilityEventing()` when text is inserted into the buffer ([see code](https://github.com/microsoft/terminal/blob/855e1360c0ff810decf862f1d90e15b5f49e7bbd/src/host/_stream.cpp#L559-L563)). However, when backspace is pressed, the entire if-condition is skipped over, resulting in the accessibility event not being fired. `WriteCharsLegacy()` has a separate branch that is dedicated to handling backspace, so I added a call to the relevant logic to notify UIA at the end of that.
✅ <kbd>Backspace</kbd> deletes a character and Narrator reads it
✅ <kbd>Backspace</kbd> still works with NVDA and JAWS (unchanged behavior)
✅ if the input …

[Conhost] Notify UIA when letter deleted via backspace

---

src/renderer/atlas/dwrite.hlsl
src/renderer/atlas/shader_ps.hlsl

5964060 contains a regression were the grayscale blending algorithm used the
gamma corrected foreground color as the pixel color, instead of blending that
color with the background color first. Due to that the background color
got lost / got set to black. This breaks any dark-on-bright outputs.
All 3 "antialiasing" settings work just like in DxEngine. ✅

AtlasEngine: Fix grayscale blending shader

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/TerminalSettingsModel/TerminalSettings.h
src/cascadia/TerminalSettingsModel/defaults.json
src/cascadia/inc/ControlProperties.h

Changed the default value of `"trimBlockSelection"` to `true`.
Without editing the setting, the toggle switch was enabled by default in the settings UI.

Change trimBlockSelection default to true

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h

Previously we would only call `SetWindowSize` and `TriggerRedrawAll` if the
viewport size in characters changed. This commit removes the limitation.
Since the if-condition limiting full redraws is now gone, this commit
moves the responsibility of limiting the calls up the call chain.
With `_refreshSizeUnderLock` now being a heavier function call
than before, some surrounding code was thus refactored.
Test relevant for #11317:
* Print text, filling the entire window
* Move the window from a 150% scale to a 300% scale monitor
* The application works as expected ✅
Regression tests:
* Text zoom with Ctrl+Plus/Minus/0 works as before ✅
* Resizing a window works as before ✅
* No deadlocks, etc. during settings updates ✅

Fix engine size not being changed on DPI changes

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

In two instances, the help text for the settings UI refers to _transparency_ when we're really talking about _opacity._ This PR changes those occurences to more accurately reflect the setting being described.

Fix transparency/opacity inconsistency in help text (#12592)

---

src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest

If we do not include mp:PhoneIdentity in our AppxManifest, the store
will edit our package and re-sign it for distribution. When that
happens, it creates a divergence: there are now two versions of our
package with the same name and version number, but different contents.
This breaks everything.

Add mp:PhoneIdentity to stop Store from rewriting our packages

---

src/cascadia/UnitTests_Control/ControlCoreTests.cpp
src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
src/cascadia/UnitTests_TerminalCore/ScrollTest.cpp
src/cascadia/UnitTests_TerminalCore/TerminalBufferTests.cpp
src/host/ut_host/ScreenBufferTests.cpp
src/inc/TestUtils.h

The `cascadia/` directory straight up isn't checked into the OS. So adding a test dependency on code in there was a BAD IDEA.

Fix the OS build

---

src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.xaml

Does what it says on the tin. This is maximal BODGE. 
`TeachingTip` doesn't provide an `Opened` event.
(https://github.com/microsoft/microsoft-ui-xaml/issues/1607). But we
want to focus the renamer text box when it's opened. We can't do that
immediately, the TextBox technically isn't in the visual tree yet. We
have to wait for it to get added some time after we call IsOpen. How do
we do that reliably? Usually, for this kind of thing, we'd just use a
one-off LayoutUpdated event, as a notification that the TextBox was
added to the tree. HOWEVER:
* The _first_ time this is fired, when the box is _first_ opened,
yeeting focus doesn't work on the first LayoutUpdated. It does work on
the second LayoutUpdated. Okay, so we'll wait for two LayoutUpdated
events, and focus on the second.
* On …

Auto-focus window renamer textbox on open

---

build/pipelines/release.yml
build/pipelines/templates/build-console-audit-job.yml
build/pipelines/templates/build-console-compliance-job.yml
build/pipelines/templates/build-console-fuzzing.yml
build/pipelines/templates/build-console-steps.yml
build/pipelines/templates/restore-nuget-steps.yml

Prevents the Fuzz pipeline from failing by refactoring the nuget restore pipeline steps.
Broken in #12778.

Prevent Fuzz pipeline failure by refactoring nuget restore pipeline steps

---

src/host/ft_fuzzer/Host.FuzzWrapper.vcxproj

Adds the common nuget import to the Fuzz project so that it compiles.
Broken in #12778, Issue identified by #12796
`Host.FuzzWrapper` project builds.

Add common nuget import to Fuzz project so that it compiles

---

build/pipelines/release.yml

Before #12691, the msixbundle version was of the format YYYY.MM.DD.0.
After #12691, it became the same as the build of Terminal it contained.
This caused some trouble for _some_ systems: major version 1 is much,
much smaller than 2022.
Adding 3000 to the major version component, _only for the bundle_, gets
around this. Ugh.
Fixes #12816.

Force the bundle major version to be over 3000

---

src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj

Adds &quot; around the GenerateHeaderForJson.ps1 to support directories with a space as described in #12745 
Closes #12745

Add a quote to fix the build for paths with spaces

---

src/cascadia/TerminalControl/TermControl.cpp

Followed reproduction steps from linked issue #12818, wt.exe shows
expected behaviour for capslock, scrolllock and numlock (assuming
numlock is an "enhanced" key):
```
C:\Users\Kaas\source\Playground\x64\Debug>Playground.exe
KeyState:   Up, KeyCode: 0x0d, ScanCode: 0x1c, Unicode:   (0x000d), Modifiers: 0x0000
KeyState: Down, KeyCode: 0x41, ScanCode: 0x1e, Unicode: a (0x0061), Modifiers: 0x0000
KeyState:   Up, KeyCode: 0x41, ScanCode: 0x1e, Unicode: a (0x0061), Modifiers: 0x0000
KeyState: Down, KeyCode: 0x53, ScanCode: 0x1f, Unicode: s (0x0073), Modifiers: 0x0000
KeyState:   Up, KeyCode: 0x53, ScanCode: 0x1f, Unicode: s (0x0073), Modifiers: 0x0000
KeyState: Down, KeyCode: 0x44, ScanCode: 0x20, Unicode: d (0x0064), Modifiers: 0x0000
KeyState:   Up, KeyCode: 0x44, ScanCode: 0x20, Unicode: d …
```

Include keyboard modalities when processing key events

---

src/api-ms-win-core-synch-l1-2-0/main.cpp
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
src/propsheet/dbcs.cpp
src/propsheet/misc.cpp
src/propsheet/preview.cpp
src/renderer/gdi/state.cpp
tools/packages.config

This commit fixes some formatting bugs by upgrading clang-format and ensures
that our code is again formatted the same way Visual Studio 2022 would do it.

Upgrade clang-format to 13.0.1

---

src/cascadia/Remoting/ProposeCommandlineResult.h
src/cascadia/Remoting/SummonWindowBehavior.h
src/cascadia/Remoting/WindowManager.cpp

This is like, 2-4% of our crashes. Impossible to say for sure, but this _looks_ like it's the root cause. This is just another one of our `HandleCommandlineArgs` buckets, hopefully the last.

Cache ProposeCommandlineResult locally

---

doc/specs/#1790 - Font features and axes-spec.md
doc/specs/#5000 - Process Model 2.0/#1032 - Elevation Quality of Life Improvements.md
doc/specs/#5000 - Process Model 2.0/#5000 - Process Model 2.0.md
doc/specs/#607 - Commandline Arguments for the Windows Terminal.md
src/buffer/out/AttrRow.cpp
src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
src/host/CopyFromCharPopup.cpp
src/host/exe/CConsoleHandoff.cpp
src/host/ft_host/API_TitleTests.cpp
src/host/ft_host/Message_KeyPressTests.cpp
src/host/ft_uia/AccessibilityTests.cs
src/host/settings.cpp
src/host/ut_host/ScreenBufferTests.cpp
src/renderer/dx/CustomTextRenderer.cpp

Mostly this is dropping doubled words. There's one brand fix.
I'm close to shipping an [upgrade to check-spelling](https://github.com/check-spelling/check-spelling/releases/tag/v0.0.20-alpha5), but in testing it against this repository, I see one behavior change that I'd like to resolve. So, while I try to figure out how, I figured I'd at least leave the fixes submitted.
(I have some ideas, as I've been slowly working towards a solution to this problem, but it isn't a simple one line change.)
[Ran check-spelling v0.0.20-alpha5](https://github.com/check-spelling/terminal/actions/runs/2100515961) w/ a refresh of the configuration based on https://github.com/check-spelling/spell-check-this/tree/prerelease/.github/workflows/
(It identified one minor bug which is fixed in 0.0.20-alpha6 - …

Spelling / Grammar

---

src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/AppLogic.idl
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.idl
src/cascadia/TerminalApp/TerminalPage.xaml

After switching to ControlsV2, it seems that
delay-loading a dialog causes the ContentDialog to be assigned a
Height equal to it's content size. If we DON'T assign the
ContentDialog a Row, I believe it's assigned Row 0 by default. So,
when the dialog gets opened, the dialog seemingly causes a giant
hole to appear in the body of the app.
Assigning all the dialogs to Row 2 (where the rest of the content
is) makes the "hole" appear in the same space as the rest of the
TabContent, fixing the issue.
Note that the actual content in a content dialog gets parented to
the PopupRoot, so it actually always appeared in the correct place, it's
just this weird hole that appeared in Row 0.
* See also: 
* #12202 was fixed by #12208
* #12447 was fixed by #12517

Manually put our ContentDialogs in the tab content, rather than above

---

src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp

If we delete a scheme, and the next scheme we've loaded is an inbox one
that _can't_ be deleted, then we need to toss focus to something
sensible, rather than letting it fall out to the tab item.
When deleting a scheme and the next scheme _is_ deletable, this isn't an
issue, we'll already correctly focus the Delete button.
125e9c479018ac648c80554ef3ce69f7b637857d focused the SelectionBackground
button, which is the _previous_ focusable control, rather than the
following one.
However, it seems even more useful for focus to ALWAYS land on the
scheme dropdown box. This forces Narrator to read the name of the newly
selected color scheme, which seemed more useful.
I'm waiting on feedback from a11y team to see if this solution is
acceptable.

Manually focus the scheme dropdown when deleting a scheme

---

src/tools/closetest/closetest.cpp

Fix retail build breaks with unreferenced locals (Closes #12769)

---

src/buffer/out/OutputCellIterator.cpp
src/buffer/out/OutputCellIterator.hpp
src/buffer/out/textBuffer.cpp
src/host/ut_host/ScreenBufferTests.cpp

855e136 contains a regression which breaks buffer reflow if wide surrogate
characters are present. This happens because we made use of the
`TextBufferCellIterator` whose increment operator skips 2 cells for wide
characters. This created a "misalignment" in the reflow logic which was written
for cell-wise iteration. This commit fixes the issue, by reverting back to the
previous algorithm without iterators.
Closes #12837
Closes MSFT-38904421
* Run ``pwsh -noprofile -command echo "`u{D83D}`u{DE43}"``
* Resizing conhost preserves all contents ✅
* Resizing Windows Terminal doesn't crash it ✅
* Added a test covering this issue ✅

Fix DBCS attribute corruption during reflow

---

src/cascadia/Remoting/Monarch.idl
src/cascadia/Remoting/WindowManager.cpp
src/cascadia/Remoting/WindowManager.h

This is all of course, conjecture. This crash is totally wild and makes no sense at all. But, we're hoping that this fixes it. This should also make calls to the Monarch a little easier.
You may be asking yourself - why aren't I doing this for the Peasant too? Well, because the Peasant simply doesn't crash like the monarch does. I'm not gonna touch something that's not broken _during ask mode_.

Remove `default_interface` from Monarch

---

.github/actions/spelling/allow/names.txt
doc/specs/#4066 - Theme-controlled color scheme switch.md

Specs for feature request "Theme-controlled color scheme switch".
#4066

Create #4066 - Theme-controlled color scheme switch.md

---

src/renderer/base/FontCache.h

The original research for a solution all the way back in #11032 contained an
unfortunate flaw. The nearby font loading code was written under the assumption
that Cascadia is missing in the system font collection, leading to our issues.
Adding nearby fonts last into the collection would thus ensure that we use
the system fonts whenever possible, but only have nearby fonts as a fallback.
This didn't work and we figured that we'd have to always prefer loading nearby
fonts over system fonts. #12554 tried to achieve this, but failed to change
the order in which the font set is built. In order to prefer nearby fonts
over system ones, we have to add the system font collection last.
* Put Jetbrains Mono into the AppX directory of the Debug build
* Jetbrains Mono shows up in the font selector and …

Another attempt at fixing nearby font loading

---

src/cascadia/LocalTests_SettingsModel/ProfileTests.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

#12149 introduced a bug where `ClearCommandline()` is called on any user
profile containing the non-canonical strings "cmd.exe" or "powershell.exe"
in the "commandline" field. If you happen to have set the "commandline"
field in your `profiles.defaults`, this will cause these user profiles
to adopt the base layer command-line instead of the defaults layer one.
This commit fixes the issue, by checking the command-line after the call
to `ClearCommandline()` and ensuring it's the expected string.
Additionally this moves the migration logic to `SettingsLoader` as this allows
us to write the fixed settings to disk, if any fixed had to be applied.
* The modified unit test fails without these changes ✅
* The modified unit test succeeds with these changes ✅
* Setting …

Fix profile commandlines being overwritten by profile.defaults

---

src/cascadia/WindowsTerminal/IslandWindow.cpp

This PR adds some missing `break` commands in `IslandWindow::MessageHandler` switch statement.

add missing breaks

---

src/cascadia/TerminalApp/App.xaml
src/cascadia/TerminalApp/ColorPickupFlyout.cpp
src/cascadia/TerminalApp/ColorPickupFlyout.xaml
src/cascadia/TerminalApp/MinMaxCloseControl.xaml
src/cascadia/TerminalApp/TabHeaderControl.xaml
src/cascadia/TerminalApp/TabRowControl.xaml
src/cascadia/TerminalApp/TerminalPage.xaml
src/cascadia/TerminalApp/TitlebarControl.xaml
src/cascadia/TerminalControl/TermControl.xaml

Fixed various small issues:
* Made TabView bottom border span the entire window width
* Made ScrollBar inner thumb rounded again
* Made SplitButton look more like the new add tab button
* Adjusted rename box height (24px, like the official compact sizing height)
* Adjusted caption button colors to match Windows 11
* ColorPicker can now escape window bounds
* Tweaked ColorPicker buttons

Misc visual fixes

---

src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.xaml
src/cascadia/TerminalApp/pch.h
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/IControlSettings.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.h
src/cascadia/inc/ControlProperties.h

Fixes #6028
Setting is "experimental.useBackgroundImageForWindow"
https://github.com/microsoft/terminal/issues/6028
Set ` "experimental.useBackgroundImageForWindow": true` and a bg image for one profile, then make splits and tabs and make sure the bg updates accordingly:
I also did the same with the setting off to make sure it still works correctly and didn't break. And I made sure opening the settings tab does not crash or show the bg image.

Add experimental setting to make bg images fit the whole tab

---

build/pipelines/release.yml

If we are building a branch called "release-*", we will also change the
NuGet suffix to "preview". If we don't do that, XES will set the suffix
to "release1" because it truncates the value after the first period. In
general, though, we want to disable the suffix entirely if we're Release
branded while on a release branch.
In effect:
BRANCH / BRANDING | Release                | Preview
------------------|------------------------|------------------------
release-*         | 1.12.20220427          | 1.13.20220427-preview
all others        | 1.14.20220427-mybranch | 1.14.20220427-mybranch

Exclude the NuGet prerelease suffix in branded release-* builds

---

src/cascadia/TerminalApp/App.xaml
src/cascadia/TerminalApp/ColorPickupFlyout.xaml
src/cascadia/TerminalSettingsEditor/Actions.xaml
src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml
src/cascadia/TerminalSettingsEditor/CommonResources.xaml
src/cascadia/TerminalSettingsEditor/Converters.cpp
src/cascadia/TerminalSettingsEditor/Converters.h
src/cascadia/TerminalSettingsEditor/Converters.idl
src/cascadia/TerminalSettingsEditor/MainPage.xaml
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.xaml
src/cascadia/TerminalSettingsEditor/Profiles_Base.xaml

Some changes to the Settings UI:
* Removed borders, made Settings use a single background
* Updated color schemes buttons
* Created DeleteButtonStyle based on accent button - closes #10454

Settings UI tweaks

---

src/renderer/base/renderer.cpp

Don't clamp here, it's unnecessary. See notes in https://github.com/microsoft/terminal/issues/12917#issuecomment-1101423091
Closes #12917

Fix a crash when resizing conhost in Debug

---

build/pipelines/release.yml

Yes, more version shenanigans. I'm probably done now.
Here's an update to the table from the original version work:
BRANCH / BRANDING | Release                    | Preview
------------------|----------------------------|----------------------------
release-*         | 1.12.20220427              | 1.13.20220427-preview
main              | 1.14.20220427-experimental | 1.14.20220427-experimental
all others        | 1.14.20220427-mybranch     | 1.14.20220427-mybranch

Make package builds from main end with -experimental

---

src/cascadia/TerminalApp/TerminalTab.cpp

Ensures the tab close button color matches the text color.
Also re-ordered and aligned the properties cleared in the `_ClearTabBackgroundColor()` method to match `_ApplyTabColor()`.
Manually tested

Ensure tab close button color matches the text color

---

src/host/getset.cpp
src/host/outputStream.cpp
src/host/screenInfo.cpp
src/host/screenInfo.hpp
src/host/selection.cpp
src/host/selectionInput.cpp
src/host/ut_host/ScreenBufferTests.cpp

The "virtual bottom" marks the last line of the mutable viewport area,
which is the part of the buffer that VT sequences can write to. This
region should typically only move downwards as new lines are added to
the buffer, but there were a number of cases where it was incorrectly
being moved up, or moved down further than necessary. This PR attempts
to fix that.
There was an earlier, unsuccessful attempt to fix this in PR #9770 which
was later reverted (issue #9872 was the reason it had to be reverted).
PRs #2666, #2705, and #5317 were fixes for related virtual viewport
problems, some of which have either been extended or superseded by this
PR.
`SetConsoleCursorPositionImpl` is one of the cases that actually does
need to move the virtual viewport upwards sometimes, in particular when
the …

Prevent the virtual viewport bottom being updated incorrectly

---

src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj

There are 3 en-dashes`(U+2013)` in the file when they should be hyphen `(U+002D)`.
This character causes the file to fail to compile in a non-utf8 encoding environment.
Just modified 3 characters to make it fall within the scope of ascii and keep it consistent with other files of the project.

change 3 en-dash to hyphen in Microsoft.Terminal.Settings.ModelLib.vcxproj

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/base/renderer.cpp
src/renderer/base/renderer.hpp
src/renderer/vt/state.cpp

`_api.cellCount` caches the `TextBuffer` size in AtlasEngine.
Calculating it based on the `_api.sizeInPixel` is incorrect as the
`TextBuffer` size doesn't necessarily have to be the size of the window.
This can occur when the window is resized, as the main thread is receiving its
`WM_SIZE` message and resizing the `TextBuffer` concurrently with the render
thread performing a render pass and AtlasEngine checking the `GetClientRect`.
In order to inform `AtlasEngine` about the initial buffer size, `Renderer`
was modified to also invoke `UpdateViewport()` on the first render cycle.
The only other user of `UpdateViewport()` is `VtEngine` which used to call
`InvalidateAll()` in these situations. In order to prevent the `InvalidateAll()`
call, `VtEngine::UpdateViewport()` was modified to …

Fix resize crash in OpenConsole with AtlasEngine

---

src/cascadia/TerminalControl/TSFInputControl.cpp

Modified the scope of input control, it used to be `Text`, now it is
`AlphanumericHalfWidth`.  This input scope actually accepts any
characters, but English characters are preferred, and the soft keyboard
also displays English by default.
This should improve user friendliness for users using composition mode
input methods.
As a user who uses the composition mode input method, in applications
like windows terminal that should usually be input in English, it is
always required to manually switch to English mode by pressing Shift
before entering commands.
One keystroke is not a problem, but often for some reason there is no or
no successful switching, and additional more keystrokes are required to
clear the wrong input.
The input method that comes with windows will automatically switch to …

Change TSFInputControl inputScope to AlphanumericHalfWidth

---

src/host/conimeinfo.cpp

As noted in the issue. There's a case where backing up the `lineEnd` can result in the `lineEnd` pointing at exactly the `lineBegin`, which results in an empty view, which causes all sorts of pain later. 
Instead, just return early in this case.
* tested with an 80x24 conhost
* tested with an 79x24 conhost
I also tried making this a FAILFAST or a THROW_HR, but the failfast immediately died (of course it did), and the throw would result in a few frames where the composition was just... entirely not displayed? Probably not what we wanted.

Fix a crash when entering lots of text in the Japanese IME

---

src/cascadia/TerminalSettingsEditor/SettingContainer.cpp
src/cascadia/TerminalSettingsEditor/SettingContainer.h
src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml

Make sure we set `Name` and `FullDescription` on expander-style settings in the SUI
Accessibility insights now shows the name/full description for the expander-style settings

Add automation properties to expander-style settings

---

src/cascadia/WindowsTerminal/WindowsTerminal.manifest
src/host/exe/openconsole.exe.manifest

To quote an internal wiki:
> It generally provides improved footprint and performance over the
> existing default heap for native win32 applications.
It is apparently the default heap on ARM64, and for all UWPs.
This heap has different allocation and compaction characteristics.
I am not sure how it will impact terminal.

Switch WT and OpenConsole to the Segment Heap

---

src/cascadia/TerminalCore/TerminalApi.cpp

When `TerminalDispatch` was merged with `AdaptDispatch` in PR #13024,
that broke the Terminal's `EraseAll` operation in the alt buffer. The
problem was that the `EraseAll` implementation makes a call to
`SetViewportPosition` which wasn't taking the alt buffer into account,
and thus modified the main viewport instead.
This PR corrects that mistake. If we're in the alt buffer, the
`SetViewportPosition` method now does nothing, since the alt buffer
viewport should always be at 0,0.
This was a regression introduced in PR #13024.
I've confirmed that the test case reported in issue #13038 is no longer
failing. I've also made sure the `ED 2` and `ED 3` sequences are still
working correctly in the main buffer.

Stop the viewport being moved when in the alt buffer

---

.github/actions/spelling/allow/allow.txt
src/cascadia/TerminalSettingsEditor/MainPage.cpp

Turns out if you add that Delete handler there, then every time you navigate to the profile, we'll add another Delete handler to the list of handlers. That's bad - that'll cause us to try and delete the profile multiple times.
The repro I had before was 100%, now it's fixed.

Only add the `ProfileVM.DeleteProfile` handler once

---

src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
src/features.xml

The setting will still be available, but be considered even more
"advanced" than the advanced section of the settings.

Hide the VT Passthrough Mode switch from the Settings UI in Preview

---

src/host/screenInfo.cpp
src/host/ut_host/ScreenBufferTests.cpp

When calculating the position of the virtual bottom after a resize with
reflow, it was possible for it to end up less than the height of the
viewport. This meant that the top of the virtual viewport would be
negative, which resulted in other operations failing further down the
line. This PR updates the virtual bottom calculation to fix that
scenario.
This was probably a regression introduced in PR #12972.
I wasn't able to replicate the exact case described in issue #13034,
because I don't have Windows 11, so can't configure the default
terminal. However, I was able to reproduce a similar failure using a
`SetConsoleScreenBufferInfoEx` call, and I've confirmed that this PR
has fixed that.
I've also added another screen buffer test to make sure the
`ResizeWithReflow` method doesn't shrink …

Make sure the virtual viewport doesn't go negative

---

doc/cascadia/profiles.schema.json

WIP for adding BellSound to schema

---

doc/cascadia/profiles.schema.json

Adds the `selectAll` action to the schema...because I forgot to do that in #13045.

Add 'selectAll' to schema

---

src/cascadia/TerminalApp/App.xaml
src/cascadia/TerminalSettingsEditor/MainPage.xaml

Fixes the SUI background being red in high contrast mode. The issue was
that `SolidBackgroundFillColorTertiary` purposefully has a bad High
Contrast color[^1].
The fix was to be explicit in the theme resources so that
`SolidBackgroundFillColorTertiary` is used in light and dark mode, but
the standard high contrast one is used in high contrast mode. Since the
page is the top-level XAML element in the Editor project, I had to
introduce this in the App.xaml resources so that the page can find the
theme resource.
Closes #13065 
Closes #13070
[^1]: https://github.com/microsoft/microsoft-ui-xaml/blob/40df43a61c013a6763f47dd7d89ed54f35999340/dev/CommonStyles/Common_themeresources_any.xaml#L650-L651

[High Contrast] Fix red SUI background

---

src/buffer/out/TextColor.h
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/host/ut_host/ScreenBufferTests.cpp
src/renderer/base/RenderSettings.cpp
src/renderer/base/renderer.cpp
src/renderer/base/renderer.hpp
src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/ITermDispatch.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/termDispatch.hpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp
src/terminal/parser/telemetry.cpp
src/terminal/parser/telemetry.hpp

The `DECAC` (Assign Colors) escape sequence controls which color table
entries are associated with the default foreground and background
colors. This is how you would change the default colors on the the
original DEC VT525 terminals.
But `DECAC` also allows you to assign the color table entries for the
"window frame", which in our case is mapped to the tab color (just the
background for now). So this now gives us a way to control the tab color
via an escape sequence as well.
DETAILS
-------
The way this works is there are now two new entries in the color table
for the frame colors, and two new aliases in the color alias table that
are mapped to those color table entries. As previously mentioned, only
the background is used for now.
By default, the colors are set to `INVALID_COLOR`, which …

Add support for the DECAC escape sequence

---

src/host/screenInfo.cpp
src/host/ut_host/ScreenBufferTests.cpp

When the buffer is resized with a reflow, we were previously calculating
the new virtual bottom based on the position of last non-space
character. If the viewport was largely blank when resized, this could
result in the new virtual bottom being higher than it should be.
This PR attempts to address that problem by restoring the virtual bottom
to a position that is the same distance from the cursor row as it was
prior to the resize.
This was a regression introduced in PR #12972.
We still take the last non-space row into account when determining the
virtual bottom, because if the content of the screen is forced to wrap,
the virtual bottom will need to be lower (relative to the cursor) than
it was before.
We also need to check that we don't overflow the bottom of the buffer,
which can occur …

Restore virtual viewport position after resize with reflow

---

src/cascadia/WindowsTerminal_UIATests/SmokeTests.cs

For some reason, the PGO tests (specifically the `RunMakeKillTabs` test) started to fail after #12979 merged. After closer inspection, the test was actually improperly written. We should be using <kbd>ctrl+shift+t</kbd> to open new tabs, not <kbd>alt+shift+t</kbd>. Presumably, the <kbd>alt</kbd> was copied over from the previous test, because they look _very_ similar.
So I went ahead and fixed the test, and it now (1) tests what it's intended to test and (2) doesn't fail. Why did #12979 cause the tests to fail? idk, but it works now.
#10071 - Introduce PGO Tests
Ran PGO tests locally and confirmed that it works.
Ran PGO pipeline and confirmed that it works.

Fix the 'RunMakeKillTabs' PGO test

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.h
src/cascadia/TerminalSettingsModel/TerminalSettings.idl

Fixes the following issues:
* `desktopWallpaper` not working
* switching tabs/panes causes the background to flicker
* settings preview having a transparent background
Tested the 3 cases above. ✅

Fix various issues with useBackgroundImageForWindow

---

src/types/inc/Utf16Parser.hpp

This trivial commit simplifies `Utf16Parser::IsLeading/TrailingSurrogate`
methods, by replacing `<bitset>` with a simple, equivalent range check.

Simplify Utf16Parser

---

src/inc/til/at.h
src/inc/til/bit.h
src/inc/til/hash.h
src/inc/til/point.h
src/inc/til/rect.h
src/inc/til/size.h
src/renderer/dx/DxRenderer.cpp
src/terminal/adapter/FontBuffer.cpp
src/terminal/adapter/FontBuffer.hpp
src/til/ut_til/PointTests.cpp
src/til/ut_til/RectangleTests.cpp
src/til/ut_til/SizeTests.cpp

This commit includes various minor improvements to til::hash/point/size/rect
which accumulated while working on #4015.
* Allow xvalue containers and non-`size_t` indices in `til::at`.
* `til::as_unsigned` can be used to reinterpret a potentially signed integer
as a unsigned one. This can potentially enable some optimizations as no sign
extension is needed anymore. `til::hash` can make use of this to drop about
20% of the hashing of signed integers <= 32 bit. On x86 this translates to
a `mov` (virtually no latency) or no instructions at all, instead of
requiring a `movsx` (some latency) for sign extension.
* `til::point` operators that prefer mutability.
This is a opinionated change, but it follows the STL style beter and
generates less assembly.
* Simpler `rect` scale_up/down and `size` …

Various improvements for til::hash/point/size/rect

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl

Add `Find` to tab context menu as describe in issue #5633.
Just wanted to solve `Easy Starter` issue, so any corrections/suggestions welcome. There's a couple of points I'm not sure of
* Placement of item within menu, currently it's at the end before close tab block.
* Should it be named longer, something like `Find in Tab` of just `Find` is fine?
* The workaround for focus similar to tab rename is a bit annoying, especially because it required adding a method to `TermControl` but without it find window obviously opens without focus which is bad.
Open menu, press menu item try to find things via opened find dialog.

Add find item to tab menu

---

doc/cascadia/profiles.schema.json

Adds the `experimental.useBackgroundImageForWindow` global setting introduced in #12893 to the schema.

Add `experimental.useBackgroundImageForWindow` to schema

---

src/renderer/atlas/AtlasEngine.api.cpp

This regressed in ad2358d.
We're interested in the size of the viewport only, but it can shift up/down
during scrolling. In these situations we shouldn't resize our buffers of course.
* Scroll
* Not setting `ApiInvalidations::Size` ✅

AtlasEngine: Stop resizing buffers on scroll

---

src/host/getset.cpp
src/terminal/adapter/InteractDispatch.cpp

When the conpty passthrough mode is enabled, it often needs to send `DSR-CPR` queries (cursor position reports) to the client terminal to obtain the current cursor position. However, the code that originally handled the responses to these queries got broken by the refactoring of the `ConGetSet` API. This PR is an attempt to correct that regression.
The conpty passthrough mode was introduced in PR #11264.
The refactoring that broke the cursor position handling was in PR #12703.
Prior to the `ConGetSet` refactoring, the code that handled `DSR-CPR` responses (`InteractDispatch::MoveCursor`) would pass the cursor position to `ConGetSet::SetCursorPosition`, which in turn would forward it to the `SetConsoleCursorPositionImpl` API, and from there to the `VtIo` class.
After the refactor, all of …

Fix handling of cursor position reports in passthrough mode

---

src/renderer/dx/CustomTextRenderer.cpp
src/renderer/dx/CustomTextRenderer.h
src/renderer/dx/DxRenderer.cpp
src/renderer/dx/DxRenderer.hpp

This PR adds support for the VT line rendition attributes in the DirectX
renderer, which allows for double-width and double-height line
renditions.
Line renditions were first implemented in conhost (with the GDI
renderer) in PR #8664.  Supporting them in the DX renderer now is a
small step towards #11595.
The DX implementation is very similar to the GDI one. When a particular
line rendition is requested, we create a transform that is applied to
the render target. And in the case of double-height renditions, we also
initialize some clipping offsets to allow for the fact that we only
render half of a line at a time.
One additional complication exists when drawing the cursor, which
requires a two part process where it first renders to a command list,
and then draw the command list in a …

Add support for line renditions in the DX renderer

---

src/cascadia/TerminalConnection/ConptyConnection.cpp

Well this one feels dumb.
Make sure to also initially set the visibility of ConPTY windows created for DefTerm connections.

Fix ShowHide for DefTerm

---

src/cascadia/TerminalApp/TabRowControl.xaml
src/cascadia/TerminalApp/TerminalPage.cpp

We're doing it this way because ThemeResources are tricky. We
default in XAML to using the appropriate ThemeResource background
color for our TabRow. When tabs in the titlebar are _disabled_,
this will ensure that the tab row has the correct theme-dependent
value. When tabs in the titlebar are _enabled_ (the default),
we'll switch the BG to Transparent, to let the Titlebar Control's
background be used as the BG for the tab row.
We can't do it the other way around (default to Transparent, only
switch to a color when disabling tabs in the titlebar), because
looking up the correct ThemeResource from and App dictionary is a
capital-H Hard problem.

Add the background back to `showTabsInTitlebar: false`'s tab row.

---

src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h

Use a throttled update to update our window state. Throttling should prevent scenarios where the Terminal window state and PTY window state get de-sync'd, and cause the window to minimize/restore constantly in a loop.  "Should" is doing a lot of work in this sentence. 
A 200ms delay was chosen because it's the typical animation timeout in Windows. This does result in a delay between the PTY requesting a change to the window state and the Terminal realizing it, but should mitigate issues where the Terminal and PTY get desync'd.
I think we're overall not super confident that this fixes the root causes of the issue. Rather, we're hopeful that a small amount of throttling here should leave time for the Terminal and pty to sync back up. We're comfortable enough with that as a bandaid for 1.14 …

Debounce window state changes caused by the PTY

---

src/cascadia/TerminalApp/TerminalPage.cpp

Prevents a null pointer dereference when attempting to split a settings tab, due to it not being a terminal tab.
Manually tested.

Don't attempt to split settings tabs

---

src/interactivity/base/InteractivityFactory.cpp

This is a big hammer to put out this fire. We're keeping the hiding around for now, cause we think that's likely the one that the internal tests use that we really care about here. If we need to bring this back, we can.

Prevent ConPTY from de-snapping the terminal

---

src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl
src/cascadia/TerminalCore/TerminalSelection.cpp
src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
src/cascadia/TerminalSettingsModel/AllShortcutActions.h
src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/defaults.json

This introduced the `toggleBlockSelection` action to allow users to create a block selection using only the keyboard. This is not bound to any keys by default, however it is added to the command palette.
#4993 - Epic
#5804 - Spec

Introduce `toggleBlockSelection` action

---

src/cascadia/TerminalSettingsEditor/MainPage.xaml

"Save" is now the first button, "Discard changes" is now the second button

Reorder "save" and "discard changes" buttons in the SUI

---

.github/actions/spelling/expect/expect.txt
src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest
src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/DefaultTerminal.cpp
src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw
src/host/exe/CConsoleHandoff.h
src/host/exe/exemain.cpp
src/host/globals.h
src/host/proxy/IConsoleHandoff.idl
src/host/srvinit.cpp
src/inc/conint.h
src/internal/stubs.cpp
src/propsheet/TerminalPropsheetPage.cpp
src/propsheet/console.cpp
src/propsheet/console.h
src/propsheet/console.rc
src/propsheet/globals.cpp
src/propsheet/globals.h
src/propslib/DelegationConfig.cpp
src/propslib/DelegationConfig.hpp
src/server/IoDispatchers.cpp

If we want to make Windows Terminal the default terminal under Windows,
we'll have to make conhost "handoff" incoming connections by default.
But this poses a problem: How can the seldomly updated conhost know
whether the routinely updated Windows Terminal version is actually willing
to accept such handoffs by default (it might be unwilling due to bugs, etc.)?
This commit solves the issue by introducing:
* A marker interface (`IDefaultTerminalMarker`): If it exists,
Windows Terminal indicates its willingness to accept the handoff.
* Turning the all-0 GUID from being synonymous for conhost,
to being synonymous for "Let Windows decide". Without this we wouldn't
be able to differentiate between users who consciously chose conhost
as their default terminal, vs. users who want the standard …

Use feature markers during terminal-by-default handoff

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp

When a profile gets deleted, we were navigating to the next item assuming it was a profile when it may not be. This commit fixes this by checking the tag of the next menu item before we navigate to it. 
Deleting the last profile in the SUI doesn't cause a crash

Fix deleting the last profile crashing Terminal

---

src/host/scrolling.cpp
src/host/scrolling.hpp

ed27737 contains a regression where (pseudocode)
```c
unsigned long ulActualDelta;
short ScreenInfo.WheelDelta;
delta *= (ScreenInfo.WheelDelta / (short)ulActualDelta);
//                                ^^^^^^^
```
was changed to
```c
delta *= (ScreenInfo.WheelDelta / ulActualDelta);
```
Due to `ulActualDelta` being unsigned, the new code casts the signed integer
to a unsigned one first, before doing the division. This causes scrolling
downwards (`WheelDelta` is negative) to appear as a large positive `delta`.
* Scrolling up/down works in OpenConsole again ✅

Fix signed/unsigned arithmetic bug during scrolling

---

src/audio/midi/MidiAudio.cpp
src/cascadia/TerminalControl/TerminalControlLib.vcxproj
src/features.xml

* conhost requires an additional dependency in Windows, which might
cause us trouble in WPG
* Terminal requires an additional *package* dependency, which *will*
cause us trouble in WPG (since GmDls is about 3MB)
I chose to scope the feature checks to MidiOut directly, as I wanted to
keep the delay behavior in MidiAudio::PlayNote. This is negotiable.
References #13252

Hide the use of MIDI behind velocity

---

src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw

Add "JSON" to the "Open settings file" command names

---

.github/actions/spelling/allow/allow.txt
README.md
doc/roadmap-2022.md

I threw that Gannt chart that I whipped up a few weeks ago in here, but if we feel that should be pulled because it's more a set of [guidelines than actual rules](https://c.tenor.com/aeV80XD4CSgAAAAC/guidlines-pirates-of-the-caribbean.gif), then we can pull it.

Update roadmap for 1.13, 1.14.

---

src/cascadia/TerminalCore/Terminal.cpp
src/types/UiaTextRangeBase.cpp
src/types/viewport.cpp

This fixes the crashes caused by using a screen reader when in an app that uses the alt buffer via two changes:
1. Fix `Terminal::ViewEndIndex()`
- `UiaTextRangeBase` receives a coordinate that is outside of the bounds of the text buffer via the following chain of functions... `_getDocumentEnd()` --> `GetLastNonSpaceCharacter()` --> `_getOptimizedBufferSize()` --> `GetTextBufferEndPoisition()` --> `ViewEndIndex()`
- Since support for the alt buffer was added recently, `ViewEndIndex()` was recently changed, so that explains why this issue came up recently. We were accidentally setting the view end index to `height` instead of `height-1`. Thanks @j4james for finding this!
- The UIA code would get the "exclusive end" of the alt buffer. Since it was using `ViewEndIndex()` to calculate that, …

Fix a11y crash in alt buffer apps

---

src/cascadia/TerminalSettingsModel/ColorScheme.cpp

When loading color schemes from Json, check if GetValueForKey failed. If
it did, and we were searching for the colors "purple"/"brightPurple",
swap out the color name with "magenta"/"brightMagenta" and try again.
This was tested manually by creating a new color scheme using the colors
"magenta"/"brightMagenta" and loading it, then printing colored text in
the terminal to assure that the colors were correctly assigned as
purple.
This changes the color loader to use an index pair table to add support
for alternate color names.
- Manually edit settings.json, creating a new color scheme with colors
"magenta" and "brightMagenta"
- View the color scheme in settings - the colors will appear as "purple"
and "brightPurple" in the UI
- Run a program that prints colored text, purple and brightPurple …

Accept color name "magenta" instead of "purple"

---

.github/actions/spelling/allow/allow.txt
src/terminal/adapter/ut_adapter/inputTest.cpp
src/terminal/input/terminalInput.cpp
src/types/FocusEvent.cpp
src/types/inc/IInputEvent.hpp

As described in #13238. libuv sends a focus event to jiggle the handle. Now that we support focus events as VT input (#12900), we'd translate those focus events to VT input as well. That combination of things caused exiting neovim to emit a `\x1b[O` to the input line of the shell when exited. 
To fix this, we're going to secretly filter out any focus events that came from the API, before translating to VT. We're fortunate here, the `FOCUS_EVENT_RECORD` version of the ctor is only called by the API.

Filter focus events that came from the API

---

src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/parser/stateMachine.cpp
src/terminal/parser/stateMachine.hpp

Up to now we haven't supported passing `DCS` sequences over conpty, so
any `DCS` operations would just be ignored in Windows Terminal. This PR
introduces a mechanism whereby we can selectively pass through
operations that could reasonably be handled by the connected terminal
without interfering with the regular conpty renderer. For now this is
just used to support restoring the `DECCTR` color table report.
Support for `DECCTR` was originally added to conhost in PR #13139.
checked, I'm ready to accept this work might be rejected in favor of a
different grand plan. Issue number where discussion took place: #xxx
The way this works is we have a helper method in `AdaptDispatch` that
`DCS` operations can use to create a passthrough `StringHandler` for the
incoming data instead of their usual …

Restore the DECCTR color table report over conpty

---

src/cascadia/TerminalApp/Resources/en-US/ContextMenu.resw

Adds an accelerator key for the shell extension: `T` for stable, `P` for preview and `D` for dev.
Ran a dev build and saw the keyboard accelerator assigned.
Closes #13061

Add an accelerator key for the shell extension

---

src/interactivity/win32/WindowIme.cpp
src/interactivity/win32/window.cpp
src/renderer/dx/DxRenderer.cpp
src/renderer/gdi/paint.cpp
src/renderer/gdi/state.cpp

ed27737 contains a regression were a `RECT` in `GdiEngine` wasn't properly
initialized anymore. Due to this, rendering during scrolling behaved erratic.
To find other cases of this bug in ed27737 the following regex was used:
```
^-.* = \{\s*\d*\s*\};
```
It appears that only `GdiEngine` was affected by a bug of this kind,
but just to be sure, this PR reverts all other instances.
This bug was likely caused when I tried to undo some of the changes in
ed27737 to make the PR smaller, but failed to revert the code properly.
I'm unable to reproduce the issue on my hardware and am unable to test
this change, but the uninitialized struct is clearly a bug regardless.
Co-authored-by: James Holderness <j4_james@hotmail.com>

Fix uninitialized memory bug in GdiEngine

---

src/cascadia/TerminalControl/ControlCore.cpp

When I moved this into ControlCore, I forgot that UserScrollViewport is usually triggered by the scrollbar updating, so it doesn't ask the UI to update. Since this logic is in ControlCore, it's sorta in a weird place where it needs to communicate both up and down:
* update the `Terminal`'s viewport position
* update the `TermControl`'s scrollbar position
Checklist:
* See also #11000

Update the scrollbar postiton on `scrollToMark`

---

src/host/outputStream.cpp

When we send this ShowWindow message, if we send it to it's
going to need to get processed by the window message thread before
returning. We're handling this message under lock. However, the first
thing the conhost message thread does is lock the console. That'll
deadlock us. So unlock here, first, to let the message thread deal with
this message, then re-lock so later on this thread can unlock again
safely.

Fix a deadlock in ShowWindow

---

src/host/_output.cpp
src/host/getset.cpp

When you execute a `cls` in the cmd shell, or `Clear-Host` in
PowerShell, we have a pair of shims that attempt to detect those
operations and forward an `ED3` sequence to conpty to clear the
scrollback.
If there was a linefeed at the bottom of the viewport immediately 
prior to those functions being called, that event might still be
pending, and only forwarded to conpty after the `ED3`. The result
then is a line pushed into the scrollback that shouldn't be there.
This PR tries to avoid that situation by forcing the renderer to
flush before the `ED3` sequence is sent.
The `cls` and `Clear-Host` shims were originally added in PR #5627.
checked, I'm ready to accept this work might be rejected in favor of a
different grand plan. Issue number where discussion took place: #xxx
I've manually …

Make sure conpty is flushed before clearing scrollback

---

src/cascadia/TerminalApp/TerminalPage.cpp

It's not useful to notify users that WT can be made the default if it's already
clearly being used for handoff. This commit will suppresses the banner then.
* Modify `TerminalPage::ShowSetAsDefaultInfoBar` to not check for
`CascadiaSettings::IsDefaultTerminalSet()`
* Set Terminal Dev as the default
* Set incoming connections to open in the latest Terminal window
* Delete `state.json` after every test below
* Launching Terminal Dev shows the banner ✅
Launching `cmd.exe` dismisses the banner in the current Terminal ✅
* Launching `cmd.exe` launches Terminal Dev without banner ✅

Dismiss Terminal-by-default banner on handoff

---

src/cascadia/TerminalCore/TerminalSelection.cpp

Introduced in #10824, this fixes a bug where you could use keyboard selection to move below the scroll area. Instead, we now clamp movement to the mutable viewport (aka the scrollable area). Specifically, we clamp to the corners (i.e. 0,0 or bottom right cell of scroll area).
✅ (no output) try to move past bottom of viewport
✅ (with output, at bottom of scroll area) try to move past viewport
✅ (with output, NOT at bottom of scroll area) try to move past viewport
✅ try to move past top of viewport

Fix moving selection past scroll area

---

.vscode/settings.json
src/server/ConsoleShimPolicy.cpp
src/server/ConsoleShimPolicy.h
src/server/ProcessHandle.cpp

In #6810, we introduced a "quirk" for all known versions of PowerShell
that suppressed their requests for black background/gray foreground.
This was done to avoid an [issue in PSReadline] where it would paint
black bars all over the screen if the default background color wasn't
the same as the ANSI black color.
Years have passed since that quirk was introduced. The underlying bug
was fixed, and the fix was released broadly long ago. It's time for us
to remove the quirk... almost.
Terminal still runs on versions of Windows that ship a broken version of
PSReadline. We must maintain the quirk there -- the user can't do
anything about it, and we would make their experience worse if we
removed the quirk entirely.
PowerShell 7.0 also ships a broken version of PSReadline. It is still in
support …

Disable the VT color quirk for pwsh and modern inbox powershell

---

src/cascadia/TerminalCore/TerminalSelection.cpp

A port of commit 0c5a1e9 from #13358.
This fixes an oversight from #13353. That ended up not fixing when trying to move past the top boundary.
This is also a better fix overall. By moving the fix to `_MoveByChar`, we have consistency between all the `_MoveByX` functions in that they automatically clamp to be within the scroll area.

[1.14] Properly fix keyboard sln at top/bot

---

src/renderer/atlas/AtlasEngine.api.cpp

This commit fixes a bug causing the OpenConsole to get increasingly larger
every time the font is changed when the AtlasEngine is active.
The only impact this bug had on Windows Terminal is that the
`font-size` in HTML and RTF selection copies are too large.
* OpenConsole window size doesn't change when
switching between main and alt buffer ✅

Fix coordSizeUnscaled calculation in AtlasEngine

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlInteractivity.cpp
src/cascadia/TerminalControl/ControlInteractivity.h
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalSelection.cpp

⚠️This targets release-1.14⚠️
Backport of #13358
This PR fixes a number of interactions between `copyOnSelect` and keyboard selection. Sometimes the selection just wouldn't be cleared or copied appropriately. 
I wrote a whole flowchart of expected behavior with copy on select:
- enable `copyOnSelect`
- make a selection with the mouse
- ✅ right-click should copy the text --> clear the selection --> paste
- use keyboard selection to quick-edit the existing selection
- ✅ `copy` action should clear the selection
- ✅ right-click should copy the text --> clear the selection --> paste

[1.14] Fix keyboard selection and copyOnSelect interaction

---

src/buffer/out/textBuffer.cpp
src/cascadia/TerminalCore/TerminalSelection.cpp
src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
src/types/UiaTextRangeBase.cpp
src/types/inc/viewport.hpp
src/types/viewport.cpp

Replaces most uses of `Viewport::CompareInBounds()` with `til::point`'s `<` and `>` operators. `CompareInBounds` has been the cause of a bunch of UIA crashes over the years. Replacing them entirely ensures that the `FAILFAST_IF` isn't ever touched.
Unfortunately, we still need `IncrementInBounds` and `DecrementInBounds` to have support for that exclusive end.
#13183

Remove most uses of `CompareInBounds`

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalSelection.cpp
src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
src/cascadia/TerminalSettingsModel/AllShortcutActions.h
src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/defaults.json

Introduces the `switchSelectionEndpoint` action which switches whichever selection endpoint is targeted when a selection is present. For example, if you are targeting "start", `switchSelectionEndpoint` makes it so that now you are targeting "end". This also updates the selection markers appropriately.
Spec - #5804 
#13358
Closes #3663
Most of the code is just standard code of adding a new action. Other than that, we have...
- if there is no selection, the action fails and the keybinding is passed through (similar to `copy()`)
- when we update the selection endpoint, we need to also update the "pivot". This ensures that future calls of `UpdateSelection()` respect this swap.
- [Corner Case] if the cursor is being moved, we make it so that you basically "anchored" an endpoint and you don't …

Introduce `switchSelectionEndpoint` action

---

src/cascadia/TerminalControl/ControlCore.cpp

In #13370, we should be notifying the renderer that the selection changed. Minor oversight and simple fix.
#4993
#13370 
Closes #13413

Update renderer on `SwitchSelectionEndpoint`

---

src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp

The main result of this fallback is that we attempt to launch wsl.exe
when the user hasn't installed or interacted with WSL. On our test
machines, that results in the creation of a wsl.exe process that tells
us precisely nothing; on WDAC managed machines it results in an Event
Log entry about spawning another (possibly blocked) process.
The registry is more reliable, and if the "API" it provides changes we
can just rev terminal.
Closes #11716

Remove the fallback to wsl.exe when HKCU\...\Lxss doesn't exist

---

src/cascadia/TerminalApp/TerminalTab.cpp

The hover tab color used to be generated from the selected tab color, which would end up lighter or darker, and white-gray colors would end up pink.
It is now simply the selected tab color with 60% opacity. This is also how brushes are created for accent buttons and color buttons (although with different opacity levels).

Update tab hover colors

---

tools/ReleaseEngineering/ServicingPipeline.ps1

```
% .\tools\ReleaseEngineering\ServicingPipeline.ps1
Inferred servicing version 1.14
PICK f025c53dbab37a5a55ac23a51aba03e36467315f: Remove the fallback to wsl.exe when HKCU\...\Lxss doesn't exist (#13436)
OK
```

RelEng: Teach ServicingPipeline to infer the version if it's null

---

src/cascadia/TerminalControl/TermControl.cpp

This one's pretty obvious. I added another scrollbar sized grid to the terminal,
but I forgot to collapse it when the user requests `"scrollbarState": "hidden"`.

Also hide the scroll marks when hiding the scrollbar

---

src/cascadia/TerminalSettingsEditor/Launch.cpp
src/cascadia/TerminalSettingsEditor/Launch.h
src/cascadia/TerminalSettingsEditor/Launch.idl
src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
src/cascadia/TerminalSettingsEditor/LaunchViewModel.h
src/cascadia/TerminalSettingsEditor/LaunchViewModel.idl
src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj.filters

Implements a `LaunchViewModel` for the Launch page in the SUI
Launch page still works

Implement MVVM for the Launch page

---

src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalSettingsEditor/GlobalAppearance.cpp
src/cascadia/TerminalSettingsEditor/GlobalAppearance.h
src/cascadia/TerminalSettingsEditor/GlobalAppearance.idl
src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/EnumMappings.cpp
src/cascadia/TerminalSettingsModel/EnumMappings.h
src/cascadia/TerminalSettingsModel/EnumMappings.idl
src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h

Adds ability to select where new tab will appear: at the end or after currently selected tab.
PR adds setting "NewTabPosition" in global appearances with dropdown list and uses it then creating new tabs. This setting does not affect settings tab position (should it?).
There should also be a documentation update, I'm just waiting to see if this change even acceptable.

Add ability to select where new tab will appear

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj.filters
src/cascadia/TerminalSettingsEditor/Rendering.cpp
src/cascadia/TerminalSettingsEditor/Rendering.h
src/cascadia/TerminalSettingsEditor/Rendering.idl
src/cascadia/TerminalSettingsEditor/Rendering.xaml
src/cascadia/TerminalSettingsEditor/RenderingViewModel.cpp
src/cascadia/TerminalSettingsEditor/RenderingViewModel.h
src/cascadia/TerminalSettingsEditor/RenderingViewModel.idl

Implements a `RenderingViewModel` for the Rendering page in the SUI
Rendering page still works

Implement MVVM for the Rendering page

---

src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/atlas/AtlasEngine.r.cpp

So far AtlasEngine would only grow the backing texture atlas once it gets full,
without the ability to reuse tiles once it gets full. This commit adds LRU
capabilities to the glyph-to-tile hashmap, allowing us to reuse the least
recently used tiles for new ones once the atlas texture is full.
This commit uses a quadratic growth factor with power-of-2 textures,
resulting in a backing atlas of 1x to 2x the size of the window.
While AtlasEngine is still incapable of shrinking the texture, it'll now at
least not grow to 128MB or result in weird glitches under most circumstances.
* Print `utf8_sequence_0-0x2ffff_assigned_printable_unseparated.txt`
from https://github.com/bits/UTF-8-Unicode-Test-Documents
* Scroll back up to the top
* PowerShell input line is still there rendering as ASCII. ✅

AtlasEngine: Implement LRU invalidation for glyph tiles

---

src/host/alias.cpp
src/host/alias.h
src/host/ut_host/AliasTests.cpp

When you create a console alias that overrides an existing command, it
should still be possible to execute the original command by prefixing it
with a space. However, at some point in the past, there was an attempt
to improve the usability by trimming leading spaces, and that ended up
breaking this functionality. This PR reverts that change, so leading
spaces can once again be used to bypass an alias.
where discussion took place: #4189
I've updated the existing alias unit test for leading spaces to match
the new behavior, i.e. it now confirms that a command with leading
spaces will not match the alias.
I've also manually confirmed that the `doskey` test case reported in
issue #4189 is now working as expected.

Allow leading spaces to bypass console aliases

---

src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/atlas/AtlasEngine.r.cpp

#13458 added the ability to reuse tiles from our glyph atlas texture
so that we stop running out of GPU memory for complex Unicode.
This however can result in our glyph generation being a performance issue in
edge cases, to the point that the application may feel outright unuseable.
CJK glyphs for instance can easily exceed the maximum atlas texture size
(twice the window size), but take a significant amount of CPU and GPU time to
rasterize and draw, which results in "jelly scrolling" down to ~1 FPS.
This PR improves the situation of the latter half by directly drawing
glyphs into the texture atlas without an intermediate scratchpad texture.
This reduces GPU usage by 96% on my system (33% -> 2%) which improves general
render performance by ~100% (15 -> 30 FPS). CPU usage remains the same …

AtlasEngine: Improve glyph generation performance

---

src/cascadia/TerminalApp/AppLogic.cpp

If launch mode is set to full screen quake window is opened in full
screen.
- Set startup > launch mode > full screen
- Launch quake window
- Quake window shouldn't be opened in full screen
Closes #12894

Don't set full screen to quake window

---

src/cascadia/TerminalApp/DebugTapConnection.cpp

When the debug tap converts control characters into visible glyphs, it
ends up losing the structure of the output, and that can sometimes make
things difficult to read. This PR attempts to alleviate that problem by
reinjecting an actual line break in the debug stream whenever an `LF`
control is received.
where discussion took place: #12312
I've tested the updated debug tab with a number of different shells, and
also a couple of different apps. When there aren't many linefeeds in the
output, it's obviously not going to make much of a difference, but when
there are, I think it definitely improves the readability.

Add line breaks in the debug tap output

---

src/host/ft_host/CJK_DbcsTests.cpp

`TestDbcsWriteRead` failed to properly test all text input scenarios.
In order to write wide characters with `CHAR_INFO` structs using the `W` APIs
one must still repeat the `CHAR_INFO` twice, once with `COMMON_LVB_LEADING_BYTE`
and once with `COMMON_LVB_TRAILING_BYTE` set in the attributes. This is because
`CHAR_INFO` APIs are column oriented. `TestDbcsWriteRead` on the other hand
only tested the scenario of sending wide characters without those flags.
This commit fixes the problem by introducing a `UnicodeDoubled` mode and
increases the number of test patterns from 14 to 17. Due to the existing
code having been written with the false assumption in mind, a simpler
modification resulted in +1100 LOC. As such I opted to rewrite the code instead
and replaced the potentially buggy output …

Extend test coverage of TestDbcsWriteRead

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h

Does what it says on the tin. When we get focused, temporarily turn off readonly mode, as to not pop the dialog when the focus sequence is eventually sent to the connection. 
* closes #13461

Send focus events even in ReadOnly mode

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalSelection.cpp
src/cascadia/TerminalSettingsModel/defaults.json

Adds support to navigate to clickable hyperlinks using only the keyboard. When in mark mode, the user can press [shift+]tab to go the previous/next hyperlink in the text buffer. Once a hyperlink is selected, the user can press <kbd>Ctrl+Enter</kbd> to open the hyperlink.
#4993 
- Main change
- The `OpenHyperlink` event needs to be piped down to `ControlCore` now so that we can open a hyperlink at that layer.
- `SelectHyperlink(dir)` searches the buffer in a given direction and finds the first hyperlink, then selects it.
- "finding the hyperlink" is the tough part because the pattern tree takes in buffer coordinates, searches through the buffer in that given space, then stores everything relative to the defined space. Normally, the given buffer coordinates would align with the viewport's …

Add keyboard navigation to hyperlinks

---

src/cascadia/TerminalApp/TerminalPage.cpp

Yep this is my bad. I was trying to fix a bug where only having one of `background` or `unfocusedBackground` would cause the other to never get set to the default. In attempting to force all the logic into an if statement, I messed up the order of operations. My bad 😢 
Regressed in #13456

Fix a bad null deref

---

build/Helix/PrepareHelixPayload.ps1

Moving to VS 2022 and C++20 in #13368 introduced a new dependency on an
as-yet-nonexistent VC Runtime library: msvcp140_atomic_wait.dll. That
library is not installed on the 21H1 machines that run our PGO tests.
Fortunately, the app platform will--largely--handle this dependency for
us on machines in the wild.
Fixes #13500

Fix PGO by "installing" a newer version of VCLibs to our app folder

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/AppLogic.idl
src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
src/cascadia/TerminalSettingsEditor/GlobalAppearanceViewModel.h
src/cascadia/TerminalSettingsEditor/GlobalAppearanceViewModel.idl
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/IslandWindow.h

Added setting for for hide window when it loses focus.
Works on normal window and quake window.
- Enable **Settings > Appearance > Automatically hide window**
- Terminal window should be minimized on taskbar when it loses focus
- Quake window should be minimized on system tray when it loses focus
- Enable also **Settings > Appearance > Hide Terminal in the notification area when it is minimized**
- Terminal window should be minimized on system tray when it loses focus
- Quake window should be minimized on system tray when it loses focus

Setting for hide window when it loses focus

---

src/cascadia/TerminalApp/MinMaxCloseControl.xaml

The min/max/close buttons now use the same font glyphs used in Windows instead of paths.
They will also look different depending on whether you use Windows 10 or 11.

Update caption buttons to use glyphs

---

src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/features.xml
src/renderer/base/RenderSettings.cpp
src/renderer/inc/RenderSettings.hpp
src/terminal/adapter/adaptDispatch.cpp

Re-enable the setting to adjust indistinguishable text, with some changes:
- We now pre-calculate the nudged values for 'default bright foreground' as well
- When a color table entry is manually set (i.e. via VT sequences) we re-calculate the nudged values
#11095 #12160
Indistinguishable text gets adjusted again

Re-enable the setting to adjust the colors of indistinguishable text

---

src/terminal/parser/ft_fuzzer/fuzzing_directed.h

2b202ce6 changed this code to fix 2-phase name lookup, but accidentally
changed `&m_tInit` to `&CFuzzType::m_tInit` (pointer-to-member¹)
instead of `&this->m_tInit` (a regular pointer to some value).
This should not be confused with `&(CFuzzType::m_tInit)`
of course which is _not_ a pointer-to-member.
¹ To simplify things, a pointer-to-member is basically the byte offset of a
member within a struct. For instance given `struct T { char a, b, c, d; }` then
`&T::c` would commonly "store" the value 2, equivalent to `offsetof(T, c)`.
Closes #13501

Fix bad code in fuzzing_directed.h

---

src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/atlas/AtlasEngine.r.cpp

We only process glyphs within the dirtyRect, but glyphs outside of the dirtyRect
are still in use and shouldn't be discarded. This is critical if someone uses
a tool like tmux to split the terminal horizontally. If they then print a lot
of Unicode text on just one side, we have to ensure that the (for example)
plain ASCII glyphs on the other half of the viewport are still retained.
The cursor was drawn without a clip rect, causing the entire atlas
texture to be filled with black. This just so happened to work fine 
in Windows Terminal but relied on a race condition.
Closes #13490
* Disappearing glyphs
* Start `tmux` in `wsl`
* Split horizontally with `Ctrl+B`, `"`
* `cat` a huge Unicode text file on the bottom
* Ensure ASCII glyphs in the top half don't disappear ✅
* Black viewport after …

AtlasEngine: Fix bugs introduced in 66f4f9d and d74b66a

---

build/pipelines/templates/build-console-compliance-job.yml

#13368 (bd403dc) failed to increment the VS version
in our compliance pipeline which broke it.

Fix VS version for compliance build

---

src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h

The current TextBuffer implementation will happily overwrite the
leading/trailing half of a wide glyph with a narrow one without
padding the other half with whitespace. This could crash AtlasEngine
which aggressively guarded against such inconsistencies.
Closes #13522
* Run .bat file linked in #13522
(Override wide glyph with a single space.)
* `AtlasEngine` doesn't crash ✅

AtlasEngine: Improve robustness against TextBuffer bugs

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.xaml

Added two new buttons to the About dialog. Source Code and Send Feedback buttons link directly to the Terminal project on GitHub and to the Issues page respectively.
#13371
Performed manual testing and confirmed that the implementation works.

Added Source Code and Send Feedback buttons to About dialog

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/CommandPalette.h

The behaviour of the 'go back' button in the command palette was changed to return to the previously selected element rather than the root.
Instead of returning to the root, the go back button now returns to the previously selected item in the filtered action list. The previously selected item is selected by default and the view is scoped to the item.
Manually tested by going back and forth between nested actions in the command palette.
Closes #13457

Make cmd palette 'go back' button return to previously selected action

---

src/cascadia/WindowsTerminal/AppHost.cpp

Fix a crash when showTabsInTitlebar:false

---

src/cascadia/TerminalApp/Resources/en-US/ContextMenu.resw

On occasion, when we submit to the store we get a package rejection
because the app name has changed for the `qps-*` locales. Instead of
constantly reserving new pseudolocalized app names every time the
pseudolocalization seed changes, we should just lock our app name so
that it does not get pseudolocalized.

Lock the app names in the pseudoloc locales

---

src/host/directio.cpp
src/host/ft_host/CJK_DbcsTests.cpp

#8000 will change the way we store text from a strict grid/matrix where
one UTF16 character or surrogate pair always equals 1 column with the
possibility of joining exactly 2 to a wide character pair, to a dynamic
buffer where 1 or more characters can form 1 or more columns in any
arbitrary combination. Our long term goal is to properly support both
complex grapheme clusters like Emojis and complex ligatures that a wider
than 2 columns.  This change requires us to break our API as
`ReadConsoleOutputA/W` assumes the existence of exactly this grid/matrix
storage. Since we store wide characters like "い" as a single codepoint
that is simply marked as being 2 columns wide in the future, we cannot
reconstruct trailing DBCS characters that were written to the buffer
like we used to.  On the …

Introduce breaking changes to ReadConsoleOutput

---

src/renderer/atlas/AtlasEngine.cpp

This change adds support for the `IntenseIsBold` rendering setting.
Windows Terminal for instance defaults to `false` here, causing
intense colors to only be bright but not bold.
* Set "Intense text style" to "Bright colors"
* Enable AtlasEngine
* Print ``echo "`e[1mtest`e[0m"``
* "test" appears as bright without being bold ✅

AtlasEngine: Handle IntenseIsBold

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h

Renames `newTabPosition` strings and enums.
Also fixes the schema, noted in https://github.com/microsoft/terminal/pull/13469#discussion_r928138496
Closes #13597

Rename newTabPosition values

---

src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
src/cascadia/TerminalSettingsEditor/LaunchViewModel.h
src/cascadia/TerminalSettingsEditor/LaunchViewModel.idl

The xaml file no longer directly accesses the settings model object, and the settings model object is no longer exposed on the view model
#13377 
Still works

Improve Launch MVVM

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.r.cpp

66f4f9d had another bug: Just like how we scroll our viewport by `memmove`ing
the `_r.cells` array, we also have to `memmove` the new `_r.cellGlyphMapping`.
Without this fix drawing lots of glyphs while only scrolling slightly
(= not invalidating the entire viewport), would erroneously call
`makeNewest` on glyphs now outside of the viewport. This would cause
actually visible glyphs to be recycled and overwritten by new ones.
* Switch to Cascadia Code
* Print some text that fills the glyph atlas
* Scroll down by a few rows
* Write a long "==========" ligature (this quickly fills up
any remaining space in the atlas and exacerbates the issue)
* Unrelated rows don't get corrupted ✅

AtlasEngine: Fix LRU state after scrolling

---

src/renderer/atlas/AtlasEngine.cpp

We recently figured that we can drop support for Windows 7. Coincidentally
AtlasEngine never actually supported Windows 7 properly, because it called
`ResizeBuffers` with `DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT`
no matter whether the swap chain was created with it enabled.
The new minimally supported version is Windows 8.1.

AtlasEngine: Remove support for Windows 7

---

src/cascadia/LocalTests_SettingsModel/SerializationTests.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp

Cleans up a couple local test failures.

Two sets of localtest fixes for July 2022

---

scratch/ScratchIslandApp/Package/Package.wapproj
src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
src/common.build.pre.props

This removes outdated checks for MSVC versions that we don't support anymore.

Remove outdated MSVC checks

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/atlas/AtlasEngine.r.cpp
src/renderer/atlas/DWriteTextAnalysis.cpp
src/renderer/atlas/DWriteTextAnalysis.h
src/renderer/atlas/atlas.vcxproj

This commit contains 3 improvements for glyph rendering:
* Scale block element and box drawing characters to fit the cell size
"perfectly" without leaving pixel gaps between cells.
* Use `IDWriteTextLayout::GetOverhangMetrics` to determine whether glyphs
are outside the given layout box and if they are, offset their position
to fit them back in. If that still fails to fit, we downscale them.
* Always scale up glyphs that are more than 2 cells wide
This ensures that long ligatures that mimic box drawing characters like
"===" under Cascadia Code are upscaled just like regular box drawings.
Unfortunately this results in ligature-heavy text (like Myanmar) to get an
"uneven" appearance because some ligatures can suddenly appear too large.
It's difficult to come up with a good heuristic here. …

AtlasEngine: Scale glyphs to better fit the cell size

---

src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml
src/cascadia/TerminalSettingsEditor/ColorSchemesPageViewModel.cpp

- When 'discard changes' is hit, we re-initialize our list of color scheme view models but forgot to tell xaml about it, this commit fixes that. 
- Make sure to exit rename mode when 'update settings' gets called
color schemes mvvm added in #13179 
Hitting discard changes doesn't cause an inconsistency with the currently selected scheme anymore

Fix a couple of issues with color scheme MVVM

---

src/cascadia/TerminalApp/AppLogic.cpp

07d58a8 contains a regression where the settings' `Themes()` property is
accessed without checking whether it's a `nullptr`. This can happen because
the invalid settings modal is shown with a empty settings model object.
This commit fixes the issue by deferring the update of `_settings` until
after we ensured that the `_settings` object is valid (besides warnings).
Closes #13543
* Replace any string value with `123`
* Application doesn't crash ✅

Fix a crash on settings reload

---

src/renderer/atlas/AtlasEngine.r.cpp

This commit makes AtlasEngine recognize Powerline glyphs as box drawing ones.
The extra pixel offsets when determining the `scale` caused weird artifacts
and thus were removed. It seems like this causes no noticeable regressions.
Closes #13029
* Run all values of `wchar_t` through `isInInversionList`
and ensure it produces the expected value ✅
* Powerline glyphs are correctly scaled with Cascadia Code PL ✅

AtlasEngine: Recognize Powerline glyphs

---

src/renderer/gdi/invalidate.cpp

This fixes an issue were overwriting parts of a row would only trigger
that specific portion of the row to be redrawn. This isn't just
problematic for combining characters, but also for things like
the new `TestDbcsBisectWriteCells` test introduced in #13626.
Benchmarks showed no impact on performance whatsoever.
* Pick this commit into #13626
* Run the `TestDbcsBisectWriteCells` test and break before OpenConsole exits
* A correct "QいかなZYXWVUTに" output is visible ✅

GdiEngine: Invalidate entire rows at a time

---

doc/cascadia/profiles.schema.json

Updates the schema such that the scroll mark settings are defined as profile settings instead of global settings (because they're actually profile settings).
Separately (but still relevant), I've also updated the release notes.
Closes #13583

[Schema] Move scroll mark settings from global to profile settings

---

src/cascadia/TerminalCore/TerminalSelection.cpp

In general, when a selection marker is shown, we should scroll to it. The `selectAll` action adds a selection marker, but we don't scroll to it. This PR makes it such that we do do that.
Epic: #4993 
Closes #13485

Scroll to top when select all action is invoked

---

src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalSelection.cpp

Adds `ScrollToPoint()` from #13405 to be able to scroll to the selection marker when (1) mark mode is entered and (2) `selectAll` is called.
This change is a combination of #13656 and a minor part of #13405.
Epic: #4993

[1.15] Scroll to sln marker for Mark Mode & SelectAll

---

src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/Pane.h

In #13560 we added a member to `Pane` that lets it know if it was spawned as a default terminal session, but did not propagate that value when the pane gets split or when the pane closes. This commit fixes that. 
A session spawned by a def term invocation remembers it even as it goes through splits

Fix _isDefTermSession not propagating upon pane split/close

---

src/terminal/parser/stateMachine.cpp
src/terminal/parser/stateMachine.hpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp

We must use 65535 as `MAX_PARAMETER_VALUE` in order for us to properly parse
win32-input-mode sequences, which transmit UTF-16 characters as parameters.
Closes #12977
* Call `SendInput` with 🙁 (`L'\xD83D'`, `L'\xDE41'`)
* 🙁 appears on the input line ✅

Fix input corruption for high code points

---

src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

- We only ever have 1 color picker now, instead of each tab having its own
- `TerminalPage` constructs this color picker (upon first request for it)
- `TerminalPage` attaches the color picker to the tab that requested for it
- `TerminalTab` detaches the color picker when it is done with it, so that `TerminalPage` can attach it to another tab later on
#5907 
User-end behaviour is the same

Use only one tab color picker for all tabs, delay load it

---

src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
src/host/ut_host/ConptyOutputTests.cpp
src/inc/TestUtils.h
src/renderer/vt/paint.cpp

This bug arose from a "race condition" in the first frame handling of conpty. We'd try to optimize out spaces if we've cleared the entire frame (which always happens on the first frame). However, doing that even for colored spaces meant that things like powerline prompts could be emitted to conhost during the first frame, and we'd optimize the spaces out. That's silly. 
This is hard to repro naturally, but this comment has another repro I used
https://github.com/microsoft/terminal/issues/8341#issuecomment-731310022
Modified to facilitate simpler testing, it looks like:
Co-authored by @DHowett

Fix conpty not emitting colored spaces on the VERY FIRST frame

---

src/cascadia/TerminalApp/Jumplist.cpp
src/cascadia/TerminalApp/Jumplist.h

This commit simplifies `Jumplist::UpdateJumplist` by using exceptions 
instead of returning error codes. Otherwise the code is identical to before.

Replace result codes with exceptions in JumpList

---

src/cascadia/TerminalControl/TSFInputControl.cpp
src/cascadia/TerminalControl/TSFInputControl.h

While working on #13398 I felt that `TSFInputControl` wasn't up to sniff.
This commit is a minor cleanup of the class:
* default member initializers
* Simplified use of STL classes which already perform boundary checks
* Correctly check text buffer emptiness in `_SendAndClearText`
* Track selection range as mandated by the API
* Japanese IME (Full-Width Katakana)
Typing "saitama" produces "サイタマ" ✅
* Korean IME
Typing "gksrmf" produces "한글" ✅
* Vietnamese IME
Typing "xin chaof" continues to produce broken "xin xinchaof"
(It's supposed to produce "xin chào")
* Emoji Picker (Win+.)
✅

Clean up TSFInputControl a bit

---

src/cascadia/TerminalSettingsModel/Theme.cpp
src/cascadia/TerminalSettingsModel/Theme.h

Other settings model classes call `JsonUtils::SetValueForKey` with the
private `_##value` member as the value. Since `_##value` is an optional,
this prevented writing out unset, optional fields. The new `Themes` class
deviated from this and this commit brings it back in line with the others.
Closes #13544
* Create a `{ "name": "test" }` theme
* Save settings via the UI
* Optional/Defaulted fields aren't written ✅

Stop writing optional theme fields

---

src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Due to the way our localization pipeline works, we cannot delete
resources in main until the resources in question are totally flushed
out of the active-servicing release branches. Unfortunately, in #13179,
we _did_ remove resource keys. Because the Color Schemes page in 1.14
and 1.15 uses the resources directly (rather than by way of x:Uid), it
is easier for us to backport the resource changes now than to
reintroduce the old keys on main.
Closes #13606

[1.14/5] Propagate the color scheme resw changes from df671377

---

.vsconfig
CONTRIBUTING.md
README.md

bd403dc made VS 2022 mandatory, but failed to update the README and .vsconfig.
Closes #13708

Update prerequisites to include VS 2022

---

.github/actions/spelling/expect/expect.txt
NOTICE.md
oss/wyhash/LICENSE
oss/wyhash/MAINTAINER_README.md
oss/wyhash/cgmanifest.json
src/buffer/out/UnicodeStorage.hpp
src/inc/til/hash.h
src/til/ut_til/HashTests.cpp
src/til/ut_til/til.unit.tests.vcxproj
src/til/ut_til/til.unit.tests.vcxproj.filters

wyhash was chosen based on the results found in `smhasher`, were it proved
itself as an algorithm with little flaws and fairly high output quality.
While I have a personal preference for xxhash (XXH3 specifically), wyhash is a
better fit for this project as its source code is multiple magnitudes smaller,
simplifying the review and integration into the header-only `hash.h` file.
For use with hashmaps the hash quality doesn't actually matter much for
optimal performance and instead the binary size usually matters more.
But even in that scenario wyhash is fairly close to FNV1a (aka "FNV64").
The result is that this new hash algorithm will only have little impact on
hashmap performance if used over the standard FNV1a as used in the STL,
while simultaneously offering a vastly better hash …

Use wyhash for <til/hash.h>

---

src/cascadia/TerminalApp/TabManagement.cpp
src/inc/til/string.h

Added control in code for not allowed characters in the filename when saving a
tab.
Closes #13664

Disallow certain non-filename characters in Export Text

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/XamlLights.cpp

Adds a variable `_isBackgroundLight` that is updated when the background
color is changed. When it is `true`, the BEL indicator flash will darken
the screen instead of brightening.
`_isColorLight(bg)` returns `true` if the average of `r`, `g`, and `b`
is >127
I was unsure of an appropriate way to change the color of the
`CompositionLight` based on the background, so I changed it to always be
gray and adjusted the intensity values of the original animation to have
roughly the same visual effect as the white.
* Tested the two flashes on the default color schemes and some custom
background colors to see if they look consistent
* Used tracepoints and visual to check that the right animation is used
(including multiple tabs, split windows with different themes, and
changing settings while …

Flash the pane dark when BEL is emitted in a light terminal

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalControl/TSFInputControl.cpp
src/cascadia/TerminalControl/TermControl.cpp

This commit builds directly on the changes made in #13677 and fixes:
* TSF resetting to AlphaNumeric ("ASCII") input mode when pressing enter
* Vietnamese IME not composing a new word after pressing whitespace, etc.
Closes #11479
Closes #13398
* Japanese IME (Full-Width Katakana)
Typing "saitama" produces "サイタマ" ✅
* Korean IME
Typing "gksrmf" produces "한글" ✅
* Vietnamese IME
Typing "xin chaof" produces "xin chào" ✅
* Emoji Picker (Win+.)
✅

Fix issues with Japanese & Vietnamese IME

---

src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp
src/cascadia/TerminalApp/AppCommandlineArgs.cpp

Changes the way `_addCommandsForArg` determines if the delimiter was at the beginning of the argument so that it accounts for the fact that match includes the last character of the string before it.
`wt -p "u"; nt -p "u"` does not cause an error

Fixe arg parsing when one-character argument is followed by `;`

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h

We have a number of theories why #12607 is happening, one of which is that
some GPU drivers somehow rely on Win32 messages or similar which we process
on the main thread. If we then try to acquire the console lock on the main
thread, while the GPU-driver thread itself is holding that lock, we've got
ourselves a deadlock. This PR makes this less likely by running the repeat
offender `UpdatePatternLocations` on a background thread instead.
We have a number of other locations which acquire the console lock on the
main thread and a thorough bug fix must be done in a different way.
* After pasting an URL it gets underlined on hover ✅

Call UpdatePatternLocations from a background thread

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl
src/cascadia/TerminalSettingsEditor/Profiles_Advanced.xaml
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/features.xml
src/interactivity/win32/window.cpp
src/interactivity/win32/window.hpp

Repurpose `Feature_AtlasEngine` to enable the atlas engine by default in Dev and Preview builds.
Introduce `Feature_ConhostAtlasEngine` to solely control atlas engine inclusion in conhost.
Closes #13745

Enable AtlasEngine by default in Preview

---

build/packages.config
common.openconsole.props
dep/nuget/packages.config
src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/dll/TerminalApp.vcxproj
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
src/cascadia/TerminalSettingsModel/dll/Microsoft.Terminal.Settings.Model.vcxproj
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/common.nugetversions.targets

Does two things:
* the first two commits: shakes up the way we reference MUX in our projects so we can actually just 
```xml
<PropertyGroup Label="NuGet Dependencies">
<TerminalMUX>true</TerminalMUX>
</PropertyGroup>
```
Like every other dependency we have
* the last commit: update to MUX.2.7.3
This is the 1.14 PR, which should be appropriately cherry-picked through to `release-1.15` and `main`

[1.14] Update the MUX package to 2.7.3

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/types/inc/utils.hpp
src/types/ut_types/UtilsTests.cpp
src/types/utils.cpp

Skips whitespace removal if pasted string is multiline
Tests passed
The last command in multiline paste now executes

Skip whitespace removal for multiline pastes

---

src/renderer/vt/paint.cpp

PR #13665 reverted this part of paint.cpp to a time before #13097 and #12975.
This commit restores those changes.

Restore type inference and integer casting changes in VtEngine

---

src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h

`debugGlyphGenerationPerformance` used to only test the performance of
text segmentation/parsing, so I renamed it to `debugTextParsingPerformance`.
The new `debugGlyphGenerationPerformance` actually clears the glyph atlas now.
Additionally this fixes a bug with `debugGeneralPerformance`:
If a `DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT` is requested,
it needs to be used. Since `debugGeneralPerformance` is for testing without
V-Sync, we need to ensure that the waitable object is properly disabled.

AtlasEngine: Fix debugGlyphGenerationPerformance

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.xaml

We shouldn't add URLs into our binaries that we can't directly control.
This commit fixes the issue for URLs recently introduced in #13510.
Closes #13541
This change is trivial enough that I simply opened the new redirects
in my browser, ensuring that they open the expected websites.

Use the redirection service for recently added URLs

---

src/cascadia/TerminalSettingsModel/KeyChordSerialization.cpp
src/inc/til/string.h
src/til/ut_til/string.cpp

Rename `til::form_wchars` to `til::to_ulong` and
allow it to work with narrow `char`s.
This change will be used in #13429.
* Loads `sc(...)` key bindings as expected ✅
* The change is thankfully fairly trivial if viewn with whitespace suppressed

Allow til::from_wchars to work with chars

---

src/host/VtIo.cpp

Fixes MSFT:40853556
There's a small race here. The renderer thread in ConPTY might notice the terminal is gone, call CloseOutput, and release the vt renderer, and then the window proc fires and decides to minimize/restore the window, triggering an A/V.
I'm 100% confident that this has NEVER happened to a real user. But the test labs hit it so much that it makes up ~26% of our crashes.
I haven't tested this cause again, _it doesn't hit in the wild_

Fix a crash in `_WritePseudoWindowCallback`

---

src/cascadia/TerminalApp/CommandPalette.cpp

Fixes MSFT:38775539
Might also fix MSFT:38614563
Looking at this code should be pretty clear what's going on. On exit, the XAML root is already nulled out. But here, we're just yolo'ing and assuming it exists (why wouldn't it). So yea. This is like weirdly high percent of crashes internally, but that's not from real users. Real users, I suspect hit this as like .3% of our crashes. Not zero, but _low_.
<hr>
May also be related to...
* MSFT:40602905
* MSFT:40602904
* MSFT:40412800
* MSFT:35213459 <---has links

Fix a crash on exit with the command palette open

---

src/renderer/atlas/AtlasEngine.cpp

The absolute disgrace of a fix called 65b71ff failed to account for `std::move`
being unsafe to use for overlapping ranges. While `std::move` works for trivial
types (it happens to delegate to `memmove`), we need to dynamically switch
between that and `std::move_backward` to be correct.
Without this fix the LRU refresh is incorrect and might lead to crashes.
I'm working on a new, pure D2D renderer inside AtlasEngine, which uses
the iterators contained in `_r.cellGlyphMapping` to draw text.
I noticed the bug, because scrolling up caused the text to be garbled
and with this fix applied it works as expected.

AtlasEngine: Fix the fix for LRU state after scrolling

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp

In #13024, we removed `Terminal::GetCursorPosition` from TerminalCore.
This has been widely regarded as a good move.
Now, you might rightly be wondering: why didn't compilation immediately
fail? Well. It turns out that there were _two_ copies of
`GetCursorPosition`. One for `const Terminal`, and one for `Terminal`.
This is important.
`Terminal::GetCursorPosition()` returned the cursor position relative to
the viewport. `Terminal::GetCursorPosition() const`, however, returns
the cursor position in absolute.
We removed the non-`const` one. Fortunately, thanks to the lookup rules
for `const`-qualified members, this didn't matter. Code that called
`GetCursorPosition()` still called `GetCursorPosition()`, and everything
was fine.
Except that part about the relative coordinates. That was not …

[1.14] Use the viewport-rel. cursor pos for CursorPosition

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp

In #13024, we removed `Terminal::GetCursorPosition` from TerminalCore.
This has been widely regarded as a good move.
Now, you might rightly be wondering: why didn't compilation immediately
fail? Well. It turns out that there were _two_ copies of
`GetCursorPosition`. One for `const Terminal`, and one for `Terminal`.
This is important.
`Terminal::GetCursorPosition()` returned the cursor position relative to
the viewport. `Terminal::GetCursorPosition() const`, however, returns
the cursor position in absolute.
We removed the non-`const` one. Fortunately, thanks to the lookup rules
for `const`-qualified members, this didn't matter. Code that called
`GetCursorPosition()` still called `GetCursorPosition()`, and everything
was fine.
Except that part about the relative coordinates. That was not …

Use the viewport-relative cursor pos for CCore.CursorPosition

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/TermControl.cpp

This PR moves the key handling for mark mode into a helper method that is then called before an action/key binding is attempted. 
Epic: #4993 
Closes #13533
- Add custom keybinding to "down" arrow key
- in mark mode --> selection updates appropriately
- out of mark mode --> keybinding executed

Make Mark Mode keybindings precede custom keybindings

---

src/host/VtIo.cpp
src/host/VtIo.hpp
src/interactivity/base/InteractivityFactory.cpp
src/interactivity/base/InteractivityFactory.hpp
src/interactivity/base/ServiceLocator.cpp
src/interactivity/inc/IInteractivityFactory.hpp
src/interactivity/inc/ServiceLocator.hpp

This commit fixes two race conditions:
* `SetPseudoWindowCallback` set the `_pseudoWindowMessageCallback`
callback after the Win32 message thread was already spawned.
This issue was fixed by instead using the `ServiceLocator` to get
a hold of the global `VtIo` instance which is created statically.
* `XtermEngine::SetWindowVisibility` was called without holding the
console lock. This issue was fixed by simply acquiring it first.
Closes MSFT:40913882
* Add `IsConsoleLocked()` assertion in `VtEngine::_Write`
* Run Windows Terminal
* No assertion failures ✅

Fix two race conditions around pseudo window visibility

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.r.cpp

After some deliberation I noticed that rounding the glyph advance up to yield
the cell width is at least just as wrong as rounding it. This is because
we draw glyphs centered, meaning that (at least in theory) anti-aliased
pixels might clip outside of the layout box on _both_ sides of the glyph
adding not 1 but 2 extra pixels to the glyph size. Instead of just `ceilf`
we would have had to use `ceilf(advanceWidth / 2) * 2` to account for that.
This commit simplifies our issue by just going with what other applications do:
Round all sizes (cell width and height) to the nearest pixel size.
Closes #13812
* Set a breakpoint on `scaling Required == true` in `AtlasEngine::_drawGlyph`
* Test an assortment of Cascadia Mono, Consolas, MS Gothic, Lucida Console
at various font sizes (6, 7, 8, 10, …

AtlasEngine: Round cell sizes to nearest instead of up

---

src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.h
src/cascadia/TerminalSettingsEditor/ColorSchemesPageViewModel.cpp
src/cascadia/TerminalSettingsEditor/ColorSchemesPageViewModel.h
src/cascadia/TerminalSettingsEditor/GlobalAppearanceViewModel.h
src/cascadia/TerminalSettingsEditor/InteractionViewModel.h
src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h

While debugging #13694, we discovered a very subtle bug we had accidentally introduced in a few places. `ViewModelHelper` defines a `PropertyChanged` event, backed by a `_propertyChangedHandlers` `event`. All opbservable properties in the viewmodels are supposed to run through that event. However, if you do `WINRT_CALLBACK(PropertyChanged, Windows::UI::Xaml::Data::PropertyChangedEventHandler)` in a derived class, it'll override that original method with the new one. XAML will subscribe to the second one, which is backed by `_PropertyChangedHandlers`, but the properties will still raise notifications on the callbacks registered to `_propertyChangedHandlers`. 
This change makes it more explicit in these derived classes, that the `PropertyChanged` method exposed by these classes is indeed …

Fix a subtle issue with PropertyChanged in ViewModels

---

src/types/UiaTextRangeBase.cpp

Apparently, calling `GetText(INT_MAX)` causes a HUGE memory spike for a few seconds each time this is called. The [UIA docs](https://docs.microsoft.com/en-us/windows/win32/api/uiautomationcore/nf-uiautomationcore-itextrangeprovider-gettext#parameters) say to put `-1` if no limit is required, but I assume a few people have been hit by this before.
This addresses this issue (and similar ones) in two ways:
1. as we iterate over the lines of text, if we're already past the max length, just break out of the loop
2. _only_ resize if the max length is actually less than the current length. This prevents us padding the string with `L'\0'` erroneously (which is probably what causes the memory spike).

[UIA] Prevent erroneous `L'\0'` padding in `GetText(INT_MAX)`

---

build/pipelines/release.yml

I got tired of renaming the packages that came out of our build
pipeline. I also got tired of the fact that every appxbundle artifact we
upload comes with another whole copy of Terminal for every architecture,
plus all their symbols. Those are reflected in other artifacts, so
there's no reason to duplicate them.

release yml: name the package correctly, don't duplicate appx

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/CommandPalette.h
src/cascadia/TerminalApp/CommandPalette.xaml

The command palette (and tab search by extension) doesn't ever tell screen readers what is selected. Here, we simply hook up the selection changed event to a function that tells the screen reader what is selected. With this, the user no longer has to tab into the list view to know what is selected!
Will resolve the following bug upon validation from a11y team: #12065 
Performed repro steps from #12065.
NOTE: we do NOT read the selected item when the command palette is first opened. I think that's ok.

[a11y] Make CommandPalette announce selected item

---

src/cascadia/TerminalSettingsModel/IconPathConverter.cpp

While having a debugger attached, opening the settings tab generates an
uncomfortable amount of exceptions. This change reduces this by a lot.
* Icons still appear ✅

Stop throwing exceptions for FontIcons

---

src/cascadia/LocalTests_SettingsModel/ThemeTests.cpp
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/TerminalSettingsModel/Theme.idl

It's not making it for 1.16, so it's out.
Closes a bullet point in #13725

Remove the `useMica` key

---

src/cascadia/TerminalControl/ControlCore.cpp

See https://github.com/microsoft/terminal/issues/12176#issuecomment-1199488906, and MSFT:39723014.
I have literally no idea how to repro this one, or debug it. The dump I looked at looked like there was a `SwapChainScaleChanged` that was being dispatched as the app was tearing down. The `ControlCore` had started closing, but the `TermControl` hadn't yet. Apparently, just none of the `_refreshSizeUnderLock` callers checked if we were already closing.
All the callers appear to be on the main thread.
Closes #12176
Since there's no real way for me to repro this manually, I'm thinking we fire this fix off to the OS terminal build, where we'll pretty quickly be able to see if this fixed it or not.

Attempt to fix the _refreshSizeUnderLock crash

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl

Since locking the console can take a non-trivial amount of time,
the main thread might have already released the ControlCore instance, while the
`UpdatePatternLocations` background thread is holding the last active reference.
If the function call goes out of scope, we destroy the instance, which might
not be safe, considering its members are usually only used by the main thread.
This commit fixes the issue by only holding a reference of the `Terminal`.
* Patterns are recognized ✅

Fix a race condition in UpdatePatternLocations

---

dep/CLI11/cgmanifest.json
dep/jsoncpp/cgmanifest.json
oss/boost/cgmanifest.json
oss/chromium/cgmanifest.json
oss/dynamic_bitset/cgmanifest.json
oss/fmt/cgmanifest.json
oss/interval_tree/cgmanifest.json
oss/libpopcnt/cgmanifest.json
oss/pcg/cgmanifest.json
oss/wyhash/cgmanifest.json
oss/xorg_apps_rgb/cgmanifest.json

This pull request adds the JSON schema for `cgmanifest.json`.
A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.
Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.
Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.
To deserialize the `cgmanifest.json` file, …

Add `$schema` to `cgmanifest.json`

---

src/host/history.cpp

When selecting candidate history, priority is given to histories with empty commands list.
I think lazily calling `s_Allocate` will require a ton of rewriting. Also I think it is not an unexpended behavior that buffer is allocated when an application connects.
Closes #13571

Discard empty command histories before discarding LRU non-empty ones

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h

This commit implements support for `experimental.rendering.software`.
There's not much to it. It's just another 2 if conditions.
* `"experimental.rendering.software": false` renders with D3D ✅
* `"experimental.rendering.software": true` triggers the new code path ✅

AtlasEngine: Add support for SetSoftwareRendering

---

src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalSettingsModel/ApplicationState.h
src/cascadia/TerminalSettingsModel/ApplicationState.idl
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettings.idl
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/FileUtils.cpp
src/cascadia/TerminalSettingsModel/FileUtils.h

This commit stores a hash of the `settings.json` file in `ApplicationState`
with which we can detect whether the settings contents actually changed.
Since I only use a small 64-bit hash as opposed to SHA2 for instance,
I'm taking the last write time of the file into account as well.
This allows us to skip calling `UpdateJumplist` at least the majority of app
launches which hopefully improves launch performance on devices with slower IO.
Part of #5907.
* Delete some profiles (see above), save settings, tasks are gone ✅
FYI For some (...) inexplicable reason, shell task lists are preserved forever
even if msix applications are uninstalled, etc. So to test whether tasks are
properly written on first app launch we have to delete some profiles/tasks
first, otherwise we can't see whether …

Call UpdateJumplist only if the settings changed

---

src/cascadia/TerminalApp/App.xaml

As noted in https://github.com/microsoft/microsoft-ui-xaml/issues/7674#issuecomment-1234088616
Screenshot below.

Remove the 1px gap under inactive tabs

---

src/renderer/atlas/AtlasEngine.cpp

We do this by detecting whether the shader is using variable 0 in
constant buffer 0 (typically "time", but it can go by many names.)
Closes #13901

atlas: only enable continuous redraw if the shader needs it

---

src/cascadia/TerminalSettingsEditor/ColorSchemesPageViewModel.cpp

Fix a bug where if you pressed the "Save" button, WT would crash. This was caused by adding the possibility that no color scheme is selected in the main page. With no "current scheme", attempting to get its "name" would cause a null ptr exception.
The fix is simple: just check if we actually have a current scheme.
Bonus points: if we don't have a current scheme, don't bother looking throught the color schemes for a match because we'll never find one.
#13269 - Color Schemes Rejuv

Fix crash on save in rejuv'd Color Schemes page

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControlAutomationPeer.cpp
src/cascadia/TerminalControl/TermControlAutomationPeer.h

This is conjecture - I was totally unable to repro the original crash here.
Based on the stacks in MSFT:39994969, it looks like we try to fire off a
`RaiseAutomationEvent`, which calls through UIA core, eventually to the point of
calling `ComPtr<WUX::Automation::Peers::IAutomationPeer>::{dtor}`. I'm guessing
based on the stacks that the TermControl has already been released and cleaned
up. However, the lambda in the `RunAsync` calls here only takes a ref to the
TCAP. The TCAP has an outstanding reference (maybe on the other side of the UIA
fence), and gets successfully resolved as strong, but when calling to
`RaiseAutomationEvent`, the `owner` we passed in is gonezo.
This explicitly passes a `weak_ref` to `TermControlAutomationPeer`, rather than
a raw ptr, so we can actually check if the …

An attempted fix for the `SignalTextChanged` crash

---

src/buffer/out/textBuffer.cpp
src/cascadia/TerminalCore/TerminalSelection.cpp
src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
src/types/UiaTextRangeBase.cpp
src/types/inc/viewport.hpp
src/types/viewport.cpp

This reverts commit f785168aacf79e2923f0d140e17fdd4c9364e51d (PR #13244)
The error logged to NVDA was caused by the following line of code in `_getTextValue()`:
`THROW_HR_IF(E_FAIL, !bufferSize.IsInBounds(_start) || !bufferSize.IsInBounds(_end));`
NVDA would expand a text range to encompass the document in the alt buffer. This means that the "end" would be set to the dangling "endExclusive" point (x = left, y = one past the end of the buffer). This is a valid range!
However, upon extracting the text, we would hit the code above. The exclusive end doesn't actually point to anything in the buffer, so we would falsly throw `E_FAIL`.
Though this could be fixed by adding a special check for the `endExclusive` in the line above, I suspect there are other places throughout the UIA code that hit …

Revert "Remove most uses of `CompareInBounds` (#13244)"

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/TermControl.cpp
src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/atlas/AtlasEngine.r.cpp
src/renderer/atlas/pch.h
src/renderer/dx/DxRenderer.cpp
src/renderer/dx/DxRenderer.hpp
src/renderer/inc/IRenderEngine.hpp

In testing the following issues were found in AtlasEngine and fixed:
1. "Toggle terminal visual effects" action not working
2. `d2dMode` failed to work with transparent backgrounds
3. `GetSwapChainHandle()` is thread-unsafe due to it being called outside
of the console lock and with single-threaded Direct2D enabled
4. 2 swap chain buffers are less performant than 3
5. Flip-Discard and `Present()` is less energy efficient than
Flip-Sequential and `Present1()`
6. `d2dMode` used to copy the front to back buffer for partial rendering,
but always redraw the entire dirty region anyways
7. Added support for DirectX 9 hardware
8. If custom shaders are used not all pixels would be presented
Closes #13906
1. Toggling visual effects runs retro shader ✅
With a custom shader set, it toggles the shader …

AtlasEngine: Fix various bugs found in testing

---

src/cascadia/TerminalConnection/AzureConnection.cpp
src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h

As noted by the `winrt::event` documentation:
> [...] But for asynchronous events, even after revoking [...], an in-flight
> event might reach your object after it has started destructing.
This is because while adding/removing/calling event handlers might be
thread-safe, there's no guarantee that they run mutually exclusive.
This commit fixes the issue by reverting 6f0f245. Since we never checked
the result of closing a terminal connection anyways, this commit simply drops
the wait on the connection being teared down to ensure #1996 doesn't regress.
Closes #13880
* Open tab, close tab, open tab, close tab, open tab, close tab
* ConPTY ✅
* Azure ✅
* Closing a tab with a huge amount of panes ✅
* Opening a bunch of tabs and then closing the window ✅
* Closing a tab while it's busy with VT ✅ …

Fix a ControlCore race condition on connection close

---

src/cascadia/TerminalApp/TabManagement.cpp

Takes title from the tab instead of the TermControl
Closes #13909

Use the tab's active title for `Export Text`

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalSelection.cpp

- fix: if a selection exists, mark mode should promote the existing selection instead of creating one at the cursor
- fix: mark mode --> move to middle of a word --> ExpandSelectionToWord --> Shift+Right/Left had some weird behavior. Fix that
- fix: Ctrl+enter on random selection clears selection. It should try to treat selection as a URL.
#13854
NOTE: 3b53f3c can be serviced

Polish MarkMode interactions with ExpandSelectionToWord and existing selection

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/Profiles_Advanced.xaml
src/cascadia/TerminalSettingsEditor/Rendering.xaml
src/cascadia/TerminalSettingsEditor/RenderingViewModel.cpp
src/cascadia/TerminalSettingsEditor/RenderingViewModel.h
src/cascadia/TerminalSettingsEditor/RenderingViewModel.idl
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/MTSMSettings.h

With AtlasEngine being enabled by default in 1.16 Preview it would look weird
if the `useAtlasEngine` option would still be called "experimental".
Additionally we're interested in how many users opt out of useAtlasEngine,
indicating major issues that would require us to disable it by default again.
Related to #13936
* Toggling `useAtlasEngine` works as expected ✅
* Observe new event with TVPP ✅

AtlasEngine: Remove experimental tag and add tracing

---

dep/CLI11/cgmanifest.json
scratch/ScratchIslandApp/SampleApp/SampleAppLib.vcxproj
src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj

When Leonard updated CLI11 in #12658, he imported a version that no
longer requires RTTI. Since CLI11 was the only reason we had enabled
RTTI in any of our projects, we're finally able to turn it off.
|        | TerminalApp.dll | MSIX Package |
| ------ | ---------------:| ------------:|
| Before |         3180KiB |      6545KiB |
| After  |         1970KiB |      6426KiB |
| Delta  |    **-1210KiB** |  **-119KiB** |

Disable RTTI on TerminalApp and friends

---

src/host/VtIo.cpp

It's not supported, and it shouldn't be. 
But this is the absolutely most minimal way to get the crash to go away. 
Closes #13914

Fix conhost crashing on `--headless` without `--signal`

---

src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/main.cpp
src/inc/WilErrorReporting.h

This commit reduces the amount of telemetry during general usage by about half.
8 events that weren't really used anymore were removed.
1 new event was added ("AppInitialized") which will help us investigate #5907.
During review 9 events were found that were incorrectly tagged as perf. data.
* Launch Windows Terminal
* The "latency" field "AppInitialized" matches the approx. launch time ✅

Reduce amount of telemetry events

---

src/inc/til/color.h
src/til/ut_til/ColorTests.cpp

The color of inactive tab text is incorrect since #13689 due to the introduction
of `til::color::layer_over` which incorrectly calculated the RGB values.
* Added unit tests ✅
Co-authored-by: Leonard Hecker <lhecker@microsoft.com>

Fix til::color::layer_over

---

src/renderer/atlas/AtlasEngine.h

`ATLAS_POD_OPS` doesn't check for `has_unique_object_representations` and so a
bug exists where `CachedCursorOptions` comparisons invoke undefined behavior.

AtlasEngine: Fix a correctness bug

---

build/config/GitCheckin.json
build/pipelines/release.yml

Our Windows branch name changed, and I took this opportunity to resolve
an issue where vpack builds would occasionally fail due to GitHub rate
limiting the Azure DevOps IP addresses.

vPack: fix submit branch, add github token from consvc

---

src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/base/RenderEngineBase.cpp
src/renderer/dx/DxRenderer.cpp
src/renderer/dx/DxRenderer.hpp
src/renderer/gdi/gdirenderer.hpp
src/renderer/gdi/state.cpp
src/renderer/inc/IRenderEngine.hpp
src/renderer/inc/RenderEngineBase.hpp
src/renderer/vt/paint.cpp
src/renderer/vt/state.cpp
src/renderer/vt/vtrenderer.hpp

This PR introduces a mechanism for passing through line rendition
attributes to the conpty client, so we can support double-width and
double-height text in Windows Terminal.
Line renditions were first implemented in conhost (with the GDI
renderer) in PR #8664, and were implemented in the DX renderer in PR
#13102.
By default this won't add any additional overhead to the conpty output,
but as soon as there is any usage of double-size text, we switch to a
mode in which every line output will be prefixed with a line rendition
sequence. This is to ensure that the line attributes in the client
terminal are always in sync with the host.
Since this does add some overhead to the conpty output, we'd prefer not
to remain in this mode longer than necessary. So whenever there is a
full repaint of the …

Pass through line rendition attributes over conpty

---

src/cascadia/TerminalCore/Terminal.cpp
src/terminal/parser/stateMachine.cpp
src/terminal/parser/stateMachine.hpp

When we added support for the `DECAC1` control sequence, which
determines whether `C1` controls are accepted or not, the intention was
that conhost would be making that determination, and Windows Terminal
would always be expected to accept any passed-through `C1` controls.
However, this didn't take into account that a passed-through `RIS`
sequence could end up disabling `DECAC1`, and that would leave Windows
Terminal incapable of processing any `C1` controls. This PR attempts to
fix that oversight.
The `DECAC1` sequence was added in PR #11690, when we disabled `C1`
acceptance by default.
This is a bit of a hack, but I've added a new `AlwaysAcceptC1` mode to
the state machine, which is enabled at startup in the Terminal, and is
never disabled. The parser then just needs to check whether …

Make sure Terminal state machine always accepts C1 controls

---

src/renderer/vt/Xterm256Engine.cpp
src/renderer/vt/paint.cpp
src/renderer/vt/state.cpp
src/renderer/vt/vtrenderer.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp

This PR introduces a mechanism for passing through downloadable soft
fonts to the conpty client, so that we can support DRCS (Dynamically
Redefinable Character Sets) in Windows Terminal.
Soft fonts were first implemented in conhost (with the GDI renderer) in
PR #10011, and were implemented in the DX renderer in PR #13362.
The way this works is by passing through the `DECDLD` sequence
containing the font definition, but with the character set ID patched to
use a hardcoded value (this is to make sure it's not going to override
the default character set). At the same time we send through an `SCS`
sequence to map this character set into the G1 table so we can easily
activate it.
We still need to process the `DECDLD` sequence locally, though, since
the initial character set mapping take place …

Pass through soft fonts over conpty

---

.github/workflows/addToProject.yml

docs: https://github.com/marketplace/actions/add-to-github-projects?version=v0.3.0
Hey maybe we should use more actions. This was thrown out during the last GH sync. Hopefully this doesn't explode.
This _should_ add all issues that don't have one of `Issue-Feature`, `Needs-Triage`, `Needs-Author-Feedback`, `Issue-Scenario` to the project board. That should just leave all the bugs and tasks that have been triaged.
I didn't go for 
```yml
labeled: Issue-Task, Issue-Bug
label-operator: OR
```
since those would include untriaged ones.
There's also no way to filter on milestone currently, so this will likely add icebox issues. We'll need to remove those manually as needed.

This is a test of the add-to-project action

---

src/cascadia/TerminalCore/TerminalSelection.cpp
src/renderer/atlas/AtlasEngine.cpp

Disables strictness and warnings as errors for custom pixel shaders in
RELEASE. Windows terminal is not telling the user why the shader won't
compile which makes it very frustrating for the shader hacker.
After trying the recent preview none of my shaders loaded anymore in
Windows Terminal Preview which made me very sad. I had no idea what was
wrong with them. After cloning the git repo, building it, fighting an
issue that prevent DEBUG SDK from being used I finally was able to
identify some issues that were blocking my shaders.
> error X3556: integer modulus may be much slower, try using uints if possible.
> error X4000: use of potentially uninitialized variable (rayCylinder)
While the first one is a good warning I don't think it is an error and
the tools I use didn't flag it so was hard …

Relax shader strictness in RELEASE mode

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.cpp

This commit fixes several issues:
* Some fonts set a line-gap even though they behave as if they
don't want any line-gaps. Since Terminals don't really have
any gaps anyways, it'll now not be taken into account anymore.
* Center alignment breaks bitmap glyphs which expect left-alignment.
* Automatic "opsz" axis makes Terminus TTF's italic glyphs look quite
weird. I disabled this feature as we might not need it anyways.
A complete fix depends on #14013
Closes #14006
* Use Terminus TTF at 13.5pt
* Print UTF-8-demo.txt
* No gaps between block characters ✅

AtlasEngine: Fix bugs around bitmap font rendering

---

doc/cascadia/profiles.schema.json
src/cascadia/PublicTerminalCore/HwndTerminal.cpp
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/ControlInteractivity.cpp
src/cascadia/TerminalControl/ControlInteractivity.h
src/cascadia/TerminalControl/IControlSettings.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl
src/cascadia/TerminalSettingsEditor/Appearances.idl
src/cascadia/TerminalSettingsModel/ActionArgs.h
src/cascadia/TerminalSettingsModel/ActionArgs.idl
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/FontConfig.idl
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/TerminalSettingsModel/TerminalSettings.h
src/cascadia/inc/ControlProperties.h
src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/base/FontInfoDesired.cpp
src/renderer/inc/FontInfoDesired.hpp

After this commit a user may specify fractional font sizes.
Support was only implemented for AtlasEngine however.
DxEngine continues to use rounded (integer) font sizes.
Closes #6678
* Install a bitmap font that requires fractional font sizes
(e.g. Terminus TTF, https://files.ax86.net/terminus-ttf/)
* Set font size to something integer (e.g. 14pt)
Glyphs are blurry ✅
* Set font size to something fractional (e.g. 13.5pt)
Glyphs are crisp ✅

Add support for fractional font sizes

---

src/buffer/out/TextAttribute.cpp
src/buffer/out/TextAttribute.hpp
src/buffer/out/ut_textbuffer/TextAttributeTests.cpp
src/host/ut_host/ScreenBufferTests.cpp
src/inc/conattrs.hpp
src/renderer/vt/paint.cpp
src/terminal/adapter/adaptDispatchGraphics.cpp

This PR attempts to simplify the `TextAttribute` class by merging the
two fields that were previously storing the "legacy" attributes and the
"extended" attributes separately.
When the `TextAttribute` class is initialized with a legacy value, we
were masking off the `META_ATTRS` bits to store in the `_wAttrLegacy`
field, and then additionally clearing the `COMMON_LVB_SBCSDBCS` bits,
so there were only 5 bits that were actually used in the end. We also
had an additional `_extendedAttrs` field holding other VT attributes,
which only used 8 of its available 16 bits.
In this PR I've now merged the the two sets of attributes into one enum,
so they all fit in a single 16-bit value. The legacy attributes retain
the same bit positions they originally had, so we can mask them off from
an incoming …

Merge the legacy and extended attributes

---

src/cascadia/TerminalSettingsEditor/Appearances.cpp
src/cascadia/TerminalSettingsEditor/Appearances.xaml
src/cascadia/TerminalSettingsEditor/pch.h

This fixes an issue with c51bb3a, where some fractional font
sizes are displayed as something like 13.600000000001.
Closes #14024
* Enter a font size of 13.6 and save
* NumberBox displays "13.6" ✅

Fix font size rounding in the settings UI

---

src/renderer/atlas/AtlasEngine.cpp

There's a different behavior regarding cursors between conhost and Windows
Terminal. In case of the latter we don't necessarily call `PaintCursor`
during cursor movement, because the cursor blinker never stops "blinking".
Closes #14028
* Enter text until after the line wraps
* Hold backspace until the line unwraps
* No leftover cursor on the second line ✅

AtlasEngine: Fix cursor invalidation

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalControl/IControlSettings.idl
src/cascadia/TerminalControl/ScrollBarVisualStateManager.cpp
src/cascadia/TerminalControl/ScrollBarVisualStateManager.h
src/cascadia/TerminalControl/ScrollBarVisualStateManager.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.xaml
src/cascadia/TerminalControl/TerminalControlLib.vcxproj
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h

This fixes #3454 by adding support for an "always" mode for the scroll bar.
This change uses a custom VisualStateManager to keep the scroll bar from collapsing if the profile is using the 'always' setting.
Tried updating settings.json directly and using the UI and making sure the scroll bar behaves as expected.
Closes #3454

Add support for scroll bar 'always' setting

---

src/cascadia/ShellExtension/OpenTerminalHere.cpp
src/cascadia/ShellExtension/OpenTerminalHere.h

When we first introduced the shell extension, it didn't work properly
for some folders (such as the Desktop, or perhaps any "background"
click) due to a bug in Windows. We worked around that bug with the help
of an awesome community member, who contributed code that would pull up
the topmost Explorer window and query its location.
That Windows bug was eventually fixed, but we still had trouble with
items appearing correctly. On Windows 11, the Open in Terminal menu item
appears and disappears at random when you right-click the desktop, but
it always appears when you right-click a folder. It sometimes appears
for Quick Access, even though it shouldn't.
We tried to fix that in #13206, but the fix caused more issues than it
solved. We reverted it for 1.15 and 1.16.
At the end of the day, it …

OpenHere: Replace explorer window lookup code w/ site lookup

---

src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/ConptyConnection.h
src/inc/conpty-static.h
src/interactivity/base/ServiceLocator.cpp
src/interactivity/inc/ServiceLocator.hpp
src/winconpty/dll/winconpty.def
src/winconpty/ft_pty/ConPtyTests.cpp
src/winconpty/winconpty.cpp
src/winconpty/winconpty.h

`ConptyClosePseudoConsole` blocks until OpenConsole exits.
This is problematic for the changes in 666c446, which stopped calling that
function on a background thread to solve a race condition. This commit fixes
the potential lags/deadlocks from waiting on OpenConsole's exit, by adding
`ConptyClosePseudoConsoleNoWait` which only closes the IO handles and allows
OpenConsole to exit naturally. This uncovered another potential deadlock
in `ServiceLocator::RundownAndExit` which might call itself recursively.
Closes #14032
* Print tons of text and concurrently close the tab.
Tab closes, OpenConsole/pwsh exits instantly ✅
* Use `Enter-VsDevShell` and close the tab.
Tab closes instantly, OpenConsole/pwsh exits after ~5 seconds ✅

Fix potential lags/deadlocks during tab close

---

src/renderer/atlas/AtlasEngine.h
src/renderer/atlas/AtlasEngine.r.cpp

This commit changes the glyph scale algorithm to prefer aligning glyphs to
their baseline. This improves the visual appearance of simulated italic glyphs.
However wide Emojis in narrow cells now look slightly worse without centering.
Closes #13987
* Use FiraCode which has no italic variant and instead uses simulated italics
* Write italic text
* Baseline is consistent ✅

AtlasEngine: Fix uneven baselines when scaling glyphs

---

src/renderer/atlas/AtlasEngine.r.cpp

This change fixes issues with certain fonts that draw _way_ outside the advance
width/height black box and expect to remain centered on the baseline.
* Use MesloLGM Nerd Font
* Print U+E0B0
* Ensure it's centered, even if it's cut off ✅

AtlasEngine: Partially revert glyph scaling changes

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TabBase.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalTab.cpp

Add tooltips to the tab context menu and the tab dropdown menu.
Closes #13243

Add tooltips to context menus

---

.vsconfig
README.md
build/scripts/Create-AppxBundle.ps1
build/scripts/Test-WindowsTerminalPackage.ps1
doc/cascadia/Unittesting-CppWinRT-Xaml.md
samples/ConPTY/EchoCon/EchoCon/EchoCon.vcxproj
scratch/ScratchIslandApp/Package/Package.appxmanifest
src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest
src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.AppxManifest.prototype.xml
src/cascadia/LocalTests_TerminalApp/TestHostApp/Package.appxmanifest
src/cascadia/WindowsTerminal/WindowsTerminal.manifest
src/cascadia/ut_app/TerminalApp.Unit.Tests.AppxManifest.xml
src/cascadia/ut_app/TerminalApp.Unit.Tests.manifest
src/common.build.pre.props
src/tools/MonarchPeasantPackage/MonarchPeasantPackage.wapproj
src/wap-common.build.pre.props

The diff between the 22000 and 22621 SDKs is fairly small, but it does include
a number of C++ correctness fixes, updates to libraries like DirectXMath and
the latest updates to DirectWrite and DXGI which I make heavy use off.
* It builds ✅

Upgrade to Windows SDK 22621

---

scratch/ScratchIslandApp/SampleApp/packages.config
scratch/ScratchIslandApp/WindowExe/packages.config
src/cascadia/TerminalApp/packages.config
src/cascadia/TerminalSettingsEditor/packages.config
src/cascadia/WindowsTerminal/packages.config

And the prerelease version of it

Update to XAML 2.7.3

---

src/cascadia/TerminalApp/TabHeaderControl.xaml
src/cascadia/TerminalApp/TerminalTab.cpp

It turns out that the negative margin for the progress ring is causing
the clipping in case the tab title gets too long:
https://github.com/microsoft/terminal/blob/43dbbd590fa4b46c37e9970415f8150d3c399598/src/cascadia/TerminalApp/TabHeaderControl.xaml#L18-L27
The negative margin was introduced in #8113 because the progress ring is
supposed to replace the tab icon but the `TabView` still reserves space
even if no icon is set (see
https://github.com/microsoft/terminal/pull/8133#issuecomment-739098014).
However, it is not actually the `TabView` reserving space even when
there is no icon, but a workaround for a crash in the
`IconPathConverter` that returns a `BitmapIconSource` with a `nullptr`
source instead of a `nullptr` `IconSource`: …

Fix clipped progress ring in tab when tab title is too long

---

src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/ut_adapter/inputTest.cpp
src/terminal/input/terminalInput.cpp
src/terminal/input/terminalInput.hpp

This PR adds support for the `DECARM` (Auto Repeat Mode) sequence, which
controls whether a keypress automatically repeats if you keep it held
down for long enough.
Note that this won't fully work in Windows Terminal until issue #8440 is
resolved.
Every time we receive a `KeyDown` event, we record the virtual key code
to track that as the last key pressed. If we receive a `KeyUp` event the
matches that last key code, we reset that field. Then if the Auto Repeat
Mode is reset, and we receive a `KeyDown` event that matches the last
key code, we simply ignore it.
I've manually tested the `DECARM` functionality in Vttest and confirmed
that it's working as expected. Although note that in Windows Terminal
this only applies to non-alphanumeric keys for now (e.g. Tab, BackSpace,
arrow keys, etc.) …

Add support for DECARM (Auto Repeat Mode)

---

src/cascadia/TerminalSettingsEditor/MainPage.h
src/cascadia/TerminalSettingsEditor/MainPage.idl

The breadcrumbs in the SUI were not readable by screen readers because they are represented as a button with a text block inside of it. Turns out, if you make the DataTemplate's item `IStringable` (meaning it has a `ToString()`), it all magically works! Allowing the screen reader to read the button as text.
Closes #13826

Make SUI breadcrumb readable by screen readers

---

src/cascadia/LocalTests_TerminalApp/TabTests.cpp
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

Instead of using the currently focused tab when an unfocused tab is duplicated, the `_MakePane(...)` function now uses an optional source tab argument that points to the correct tab being duplicated.
Manually tested on multiple tabs with different profiles. Performed steps:
* Construct at least two tabs with different profiles.
* Select `Duplicate Tab` option from the dropdown menu of the unfocused tab.
* Verify that the new tab has the same profile as the tab it was duplicated from.
Closes https://github.com/microsoft/terminal/issues/13942

Fix duplication issue for unfocused tabs

---

src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Addressing post-hoc comments on the launch parameters expander in the SUI (added in #13605)
- Use more contextually appropriate strings (`Centered` instead of `On` / `Off`)
- Don't emit an extra `NotifyChanges`
References #13605

Fix some issues with the launch parameters in the SUI

---

src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl

Since #13730 merged, when we parse LaunchPosition we treat the
coordinates as `int32_t`. This PR updates the actual `LaunchPosition`
struct to also use `int32_t` for consistency.
Terminal still builds and runs

Update LaunchPosition to use int32_t instead of int64_t

---

src/cascadia/TerminalControl/ControlCore.cpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp

https://github.com/gnachman/iTerm2/commit/c0b2f488c1bde541676edd50ed9d3cb12a061275
Unlike iTerm2, we're not planning on making it configurable.
This commit also adds a max length of 1024 characters on the "display URI" that we pass up to XAML, so as to not inundate the UI.
Fixes #14200

Add a maximum OSC 8 URI length of 2MB following iTerm2

---

src/host/VtInputThread.cpp
src/host/VtInputThread.hpp
src/host/VtIo.cpp
src/host/VtIo.hpp
src/interactivity/base/ServiceLocator.cpp
src/interactivity/inc/ServiceLocator.hpp
src/renderer/vt/paint.cpp
src/renderer/vt/state.cpp
src/renderer/vt/vtrenderer.hpp
src/winconpty/ft_pty/ConPtyTests.cpp

Problem:
* Calling `RundownAndExit` tries to flush out the last frame from `VtEngine`
* `VtEngine` indirectly calls `RundownAndExit` if the pipe is gone via `VtIo`
* `RundownAndExit` is called by other parts of OpenConsole
* `RundownAndExit` must be `[[noreturn]]` for most parts of OpenConsole
* `VtIo` itself has a mutex ensuring orderly shutdown
* In short, doing a thread safe orderly shutdown requires us to hold both,
a lock in `RundownAndExit` and `VtIo` at the same time, but while other parts
need a blocking `RundownAndExit`, `VtIo` needs a non-blocking one
* Refactoring the code to use optionally non-blocking `RundownAndExit`
requires refactoring and might prove to be just as buggy
Solution:
* Simply don't call `RundownAndExit` in `VtEngine` at all
* In case the write pipe breaks:
* …

Fix a deadlock during ConPTY shutdown

---

src/terminal/input/terminalInput.cpp
src/terminal/input/terminalInput.hpp

The way `DECARM` was initially implemented, we checked for repeated key
presses by matching the last recorded virtual key code, and used a 0 key
code to indicate that no key was pressed. This caused the VT query
responses to fail, because they generated key events with a 0 key code,
and that would end up being detected as a repeated key that should be
suppressed.
This PR fixes that issue by using a `std::optional` to track the last
key code, so if no key has been pressed we can represent that with
`std::nullopt`, and there's no way that can be confused with a genuine
key press.
The `DECARM` mode was introduced in PR #13981.
I've manually tested in Vttest to confirm that the query reports are now
working again, even when `DECARM` is disabled. I've also checked that
`DECARM` itself it still …

Make sure VT reports still work when DECARM is disabled

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.idl

This pull request operates on the same theory as #14217, but at a lower
level. Carlos and I discovered that TerminalPage *already* has an
action-dispatching key preview handler, and that my implementation of
`IDirectKeyListener` handles focus-tree bubbling mostly correctly.
Because of that discovery, we learned we could move the
`IDirectKeyListener` into TerminalPage itself and not have to complicate
the SUI or the Command Palette with the DirectKey interface.
Validation:
When bound to Alt+Space, the system menu works in the command palette,
the settings UI, and in read-only panes.
Fixes #11970
Closes #14217
Fixes MSFT-41390832

Pipe DirectKey events into TerminalPage for Alt+Space

---

doc/cascadia/profiles.schema.json

Fix a missing entry in the JSON schema for `intenseTextStyle`.
The JSON schema was missing an entry in the Profile section for
`intenseTextStyle`. I have added it as it appears in AppearanceConfig.
Note that this is currently duplicated in the schema -- however, this is
the pattern used already in Profile as AppearanceConfig entries have
alternate descriptions (and I have updated the description in that
section to make it clear it applies to unfocused terminals).
Longer-term, it likely makes sense to consolidate all entires into
ApperanceConfig and rely on the description for the `unfocusedApperance`
object/the name of the object to make the limited scope of those keys
clear, so that Profile can simply extend ApperanceConfig and the
duplication in the schema can be reduced.
Validation …

Fix a missing entry for intenseTextStyle in the Profile schema

---

src/cascadia/WindowsTerminal/IslandWindow.cpp

We'll just ping the window and give it a chance to respond before we
bunk with it.
Fixes #14131

Disallow a window waiting on system() to block DefTerm startup

---

src/cascadia/TerminalConnection/ConptyConnection.cpp

The `BSTR` arguments originate from COM calls who own them.
Found via AppVerifier.

Stop freeing BSTRs that do not belong to us

---

src/cascadia/TerminalApp/AppLogic.cpp

Override the center on launch setting when a position is specified on the commandline.
1. Set center on launch in the SUI.
2. Run `wtd` - the new window is centered.
3. Run `wtd --pos 100,200` - the new window is positioned at (100,200).
Closes #14176

Override center on launch setting when position specified on cmdline

---

.config/dotnet-tools.json
build/pipelines/templates/check-formatting.yml

Updates the version of XamlStyler to one with support for .NET 6.0. The version used before this depended on .NET 3.1, [which goes out of support on 2022-12-13.](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)
This shouldn't be controversial as .NET 6.0 is included with VS 2022, unlike .NET 3.1.

Update XamlStyler version

---

.gitmodules

Remove vestigial submodule entry
#12778 removed the actual WIL submodule, but there was still an entry left in the `.gitmodules` file that was causing me confusion about an orphaned submodule directory I had in an old copy of the repo.
- Official validation checks passed
- Build still works locally after a `git clean -fdx`

Remove vestigial submodule entry

---

src/til/ut_til/HashTests.cpp

744ca24 broke `HashTests` as it renamed a preprocessor definition.

Fix a test failure in HashTests

---

src/types/ColorFix.cpp
src/types/inc/ColorFix.hpp

This is just a quick drive-by improvement. Switching from double to float
roughly doubles performance on a contemporary x86 CPU with `/fp:fast`.
* Patch `RenderSettings.hpp` to include `Mode::AlwaysDistinguishableColors`
* Run a color intense application in AtlasEngine and observe CPU usage

Use float throughout ColorFix

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsEditor/SettingContainer.cpp

This removes all of the redundant tooltips from the settings UI. Since all of the settings are added through the SettingsContainer, it's a pretty simple change.
Closes #14184

Remove redundant tooltips from settings UI

---

src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/ITermDispatch.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/termDispatch.hpp
src/terminal/adapter/ut_adapter/adapterTest.cpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp

The original implementation of the _Device Status Report_ sequence was
only capable of handling ANSI status queries. This PR adds the ability
to respond to private DEC queries as well.
To prove it's working as intended, I've also included support for the
DEC extended cursor position report (`DECXCPR`), which is essentially
the same as the ANSI cursor position report, but with an additional
parameter indicating the page number. Until we support paging, though,
that value is just hardcoded to 1.
The method for distinguishing between ANSI options and the private DEC
options is based on the updates made to the `SM`/`RM` mode sequences in
PR #8469.
I've added a couple of unit tests covering the `DECXCPR` report, and
also manually confirmed we now pass the _Extended Cursor-Position_ test
in …

Add support for private options in DSR queries

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/ConptyConnection.h
src/cascadia/TerminalConnection/ConptyConnection.idl
src/host/srvinit.cpp

- Pipe the `ShowWindow` value through to `ConptyConnection`
- When `TerminalPage` receives the new connection, it checks the `ShowWindow` value and maximizes *IF* there were no other pre-existing tabs (in glomming mode, we don't want to maximize sessions that did not ask for it)
#12154 
This is just a temporary solution until we change our defterm handoff process. Because of the way the process currently works, we have no way of knowing that the connection has requested the window to be maximized until after we have already started a terminal session. This means that we have to manually maximize the window upon receiving the connection, instead of having the session _start_ maximized, as it probably should. 
`start /max python` with defterm enabled opens up python in a maximized WT window

Respect the "/max" parameter when starting console apps with defterm enabled

---

src/cascadia/TerminalControl/TermControl.cpp
src/common.build.pre.props
src/inc/til.h
src/project.inc
src/til/ut_til/SizeTests.cpp
src/types/ColorFix.cpp

Lately I've been a bit concerned about issues resulting from b036cab enabling
`/fp:fast` throughout the entire project. This commit reverts that change and:
* Enables `/fp:contract` which defaults to off since VS 17.0
This re-enables FMA for floats on ARM64. Since this doesn't affect NANs, etc.
I don't expect any issues apart from a slight change in float accuracy.
* Introduces `TIL_FAST_MATH_BEGIN` with which `/fp:fast` can be selectively
enabled for code that benefits from it like `ColorFix.cpp`.
Without `TIL_FAST_MATH_BEGIN` `ColorFix` is about twice as slow
(which is actually very noticeable in real life).
This PR doesn't produce any noticeable performance regressions.
* Patch `RenderSettings.hpp` to include `Mode::AlwaysDistinguishableColors`
* Run a color intense application in …

Disable /fp:fast by default

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/UnitTests_Control/ControlCoreTests.cpp
src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp

If the opacity is set to 100%, the background becomes solid instead of 'fully opaque acrylic'. If the opacity is below 100% the acrylic material is re-enabled (depending on the user's settings).
I updated two unit tests to reflect the change in behavior and manually tested the transition from <100% opacity to 100% opacity (and vice versa) on win11.
Steps:
1. Start with 100% opacity and acrylic material enabled.
2. Decrease opacity and observe acrylic effect.
3. Increase opacity back to 100% and disable the acrylic effect.
4. Decrease opacity and notice that acrylic effect is no longer there.
Closes #12880

Disable acrylic material (temporarily) when opacity is set to 100%

---

src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml

XAML has an issue in windows 10 where `Width="*"` does not work properly
inside the `DataTemplate` for a `ListView`. Because of this, the color
scheme list view items looked very strange in windows 10 (see #14187).
Thanks to that, we thought up a few new designs for the color schemes
page and selected a new one that blends the color chips with a region
that shows the foreground and background color with the text preview.
Closes #14187

Reorder the color chips grid in the color schemes page

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.cpp

`TextBuffer` is buggy and allows a `Trailing` `DbcsAttribute` to be written
into the first column. Since other code then blindly assumes that there's a
preceding `Leading` character, we'll get called with a X coordinate of -1.
This issue will be fixed by #13626 and this commit fixes it in the meantime.
Additionally fixes an unimportant crash when the window height is 0px,
because it was annoying during testing and doesn't hurt to be fixed.
* Run a stress test that prints random Unicode at random positions
* Resize the window furiously at the same time
* Doesn't crash / fail-fast ✅

AtlasEngine: Fix a heap overflow bug

---

src/cascadia/TerminalSettingsEditor/SettingContainer.cpp

We already were setting the automation properties on the expander, however, we were not setting it on the content when an expander was present. This change applies the automation properties to both the expander and the child content (i.e. TextBox).
Closes #13827

Apply AutoProps to TextBox settings in SUI

---

src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp

The following members were not initialized during construction:
* `CursorType _defaultCursorShape`
* `bool _suppressApplicationTitle`
* `bool _bracketedPasteMode`
* `size_t _hyperlinkPatternId`
* `SelectionExpansion _multiClickSelectionMode`
* `til::CoordType _scrollbackLines`
Unlike gcc and clang, MSVC is fairly tame when it comes to removing code
tainted by undefined behavior, so the most likely affect this had is that
we were reading uninitialized memory.
Related to #14129.

Initialize all members of Terminal

---

build/Helix/global.json

This mirrors microsoft/WinUI !8045797 and appears to resolve our recent Helix
pipeline failures, due to a python script issue (see Helix logs).

Fix Helix failures by updating the SDK

---

src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/cascadia/TerminalCore/TerminalSelection.cpp
src/cascadia/TerminalCore/lib/terminalcore-lib.vcxproj
src/cascadia/TerminalCore/terminalrenderdata.cpp
src/host/renderData.cpp
src/host/renderData.hpp
src/host/ut_host/VtIoTests.cpp
src/renderer/inc/IRenderData.hpp

AuditMode was accidentally disabled in 1c6aa4d, around 2 years ago.
This should fix this issue and address all the warnings it now generates.
Related to #14129.

Re-enable AuditMode for TerminalCore

---

src/cascadia/TerminalCore/Terminal.cpp

Compiler was raising the error: `expression did not evaluate to a constant.`, causing the solution to fail when building. Removing this `constexpr` fixes it.
Solution builds now

Remove `constexpr` from `_altBufferMarks`

---

src/host/screenInfo.cpp

Prior to this PR, the conhost vertical scrollbar would be forced to be
visible whenever the "Disable Scroll-Forward" option was set. It was
assumed that it would be needed as soon as the current viewport was
filled, so it was better to start off visible and disabled.
When the viewport height and buffer height are the same, though, the
scrollbar is never needed, and conhost compensates for that by making
the window narrower. But since we were still forcing the scrollbar to be
visible, that would result in it overlapping content in the rightmost
columns.
This PR attempts to fix that issue by simply leaving the scrollbar to
decide the visibility itself. This is perhaps not as aesthetically
pleasing when it starts off hidden and then later becomes visible, but
that seems better than having it …

Prevent conhost scrollbar overlapping content

---

src/buffer/out/TextAttribute.cpp
src/buffer/out/TextAttribute.hpp
src/host/ut_host/ScreenBufferTests.cpp
src/inc/conattrs.hpp
src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/ITermDispatch.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/adaptDispatchGraphics.cpp
src/terminal/adapter/termDispatch.hpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp
src/terminal/parser/telemetry.cpp
src/terminal/parser/telemetry.hpp

This PR adds support for the rectangular area escape sequences:
`DECCRA`, `DECFRA`, `DECERA`, `DECSERA`, `DECCARA`, `DECRARA`, and
`DECSACE`. They provide VT applications with an efficient way to copy,
fill, erase, or change the attributes in a rectangular area of the
screen.
where discussion took place: #14112
All of these operations take a rectangle, defined by four coordinates.
These need to have defaults applied, potentially need to be clipped
and/or clamped within the active margins, and finally converted to
absolute buffer coordinates. To avoid having to repeat that boilerplate
code everywhere, I've pulled that functionality out into a shared method
which they all use.
With that out of the way, operations like `DECFRA` (fill), `DECERA`
(erase), and `DECSERA` (selective erase) are …

Add support for the rectangular area operations

---

src/host/ut_host/VtIoTests.cpp

1774cfd added a debug assertion in `CreateIoHandlers` which broke this test.

Fix VtIoTests for debug builds

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/UnitTests_Control/ControlCoreTests.cpp

Ensures that reading the buffer content actually returns the content.
Regressed in #13626.
Added a test.

Ensure reading the buffer content actually returns the content

---

.github/ISSUE_TEMPLATE/Bug_Report.yml

Due to https://github.com/microsoft/terminal/issues/14335 using `wt -v` is not recommended. BTW, it might be nice if Ctrl-Shift-P and typing "about" or "version" gave the version, too.

Update bug template to help find the version number accurately

---

src/cascadia/TerminalSettingsEditor/Interaction.xaml
src/cascadia/TerminalSettingsEditor/InteractionViewModel.h
src/cascadia/TerminalSettingsEditor/InteractionViewModel.idl
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

This commit adds the setting "confirmCloseAllTabs" to SUI.
The setting was added to the Interactions pane of Global Settings.
Closes #14413
Closes #14033

Add the setting "confirmCloseAllTabs" to SUI

---

src/host/PtySignalInputThread.cpp
src/host/PtySignalInputThread.hpp

This changeset consists of two parts:
* Refactor `PtySignalInputThread` to move more code from `_InputThread`
into the various `_Do*` handlers. This allows us to precisely control
console locking behavior which is the cause of this bug.
* Add the 1-line fix to `_DoSetWindowParent` to unlock the console before
calling foreign functions (`SetWindowLongPtrW` in this case).
This fix is theoretical in nature, based on a memory dump from an affected user
and most likely fixes: https://developercommunity.visualstudio.com/t/10199439
* ConPTY tests complete. ✅

Fix a potential deadlock for PtySignal::SetParent

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Remove "Requires relaunch" from "use acrylic in tab row" text

---

src/cascadia/WpfTerminalControl/TerminalContainer.cs

Watson reports show that Visual Studio terminal attempts to render a string that is null causing the renderer to crash.
More specifically, we see "NULL_POINTER_WRITE_c0000005_PublicTerminalCore.dll!TextBuffer::WriteLine" with the following stack:
PublicTerminalCore!TextBuffer::WriteLine+0x1da
PublicTerminalCore!TextBuffer::Write+0x191
PublicTerminalCore!Microsoft::Terminal::Core::Terminal::_WriteBuffer+0x1d3
PublicTerminalCore!Microsoft::Terminal::Core::Terminal::PrintString+0x9
PublicTerminalCore!TerminalDispatch::PrintString+0x22
PublicTerminalCore!Microsoft::Console::VirtualTerminal::OutputStateMachineEngine::ActionPrintString+0x42
PublicTerminalCore!Microsoft::Console::VirtualTerminal::StateMachine::ProcessString+0x123
PublicTerminalCore!TerminalSendOutput+0x68 …

Added null check before rendering a string from the terminal connection

---

src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp

This change should have been a part of #14190 but was missed. 
Setting launch position in the settings UI works now

Fix setting launch position in the Settings UI not working

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Giving a warning sounds better in my opinion.
attempts to fix #14433

reword en-US value for confirmCloseAllTabs

---

src/cascadia/TerminalApp/App.xaml
src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/Pane.h
src/cascadia/TerminalApp/TerminalPage.cpp

We couldn't do this before, because `App::Current().Resources().Lookup()` would always return the OS theme version of a resource. That thread has lengthy details on why.
FORTUNATELY FOR US, this isn't the first time we've dealt with this. We've come up with a workaround in the past, and we can just use it again here. 
Closes #3917
This will also make #3061 easy 😉

Make the Pane inactive border respect the `theme.window.applicationTheme`

---

src/cascadia/WindowsTerminal/IslandWindow.cpp

I should have checked the `wparam`. 
Regressed in #14064.
Tested manually. No more crashy. 
Closes #14504

Don't crash when turning on Voice Access

---

dep/nuget/packages.config
scratch/ScratchIslandApp/SampleApp/App.cpp
scratch/ScratchIslandApp/SampleApp/App.h
scratch/ScratchIslandApp/SampleApp/App.idl
scratch/ScratchIslandApp/SampleApp/App.xaml
scratch/ScratchIslandApp/SampleApp/SampleAppLib.vcxproj
scratch/ScratchIslandApp/SampleApp/dll/SampleApp.vcxproj
scratch/ScratchIslandApp/SampleApp/pch.h
src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
src/cascadia/TerminalApp/App.cpp
src/cascadia/TerminalApp/App.h
src/cascadia/TerminalApp/App.idl
src/cascadia/TerminalApp/App.xaml
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/dll/TerminalApp.vcxproj
src/cascadia/TerminalApp/pch.h
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/common.nugetversions.props
src/common.nugetversions.targets

We originally needed this library (or a separate DLL in our own project)
to handle hooking up the XAML resource loader to the providers that our
application needed. It was introduced in its nascent form in 2019, in a
PR titled "Make XAML files work."
It appears we no longer need it, and the provider hookup is being
handled by our `AppT2` base class override. I've tested this in Windows
10 Vb running unpackaged, and it seems to work totally fine. Crazy.
Removing this dependency saves us a couple hundred kilobytes on disk and
removes one consumer of the App CRT from our package.

Remove our dependency on Microsoft.Toolkit.Win32.UI.XamlApplication

---

src/cascadia/WindowsTerminal/AppHost.cpp

Fix a crash when the theme doesn't have a `window`

---

src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp

Ensures the X & Y XAML controls are updated when the default launch position checkbox is toggled.
References #14518

Ensure X/Y controls are updated when default launch pos selected

---

src/cascadia/TerminalSettingsEditor/ColorSchemesPageViewModel.idl

Didn't know the code formatter won't hit `idl` files

Fix use of tabs instead of spaces in ColorSchemesPageViewModel.idl

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Similar to #14519.
Voice Access allows for functionality like "click <name>" to automatically move the cursor and click on a control. The Search Box had an AutoProp.Name that didn't match the button text, leading to confusion because Voice Access wouldn't be able to find a control named "Create".
To fix this, we simply aligned the button text and the AutoProp.Name.
Closes #13808

Match 'add appearance' button text to AutoProp.Name

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/MainPage.h
src/cascadia/TerminalSettingsEditor/MainPage.xaml

Use mica in the SUI if mica is enabled in the theme

---

src/cascadia/TerminalSettingsEditor/CommonResources.xaml
src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Performs some cleanup in the Settings UI for the Launch Parameters settings:
1. Updates all `NumberBox` controls in the Settings UI to have a `Compact` `SpinButtonPlacementMode` instead of an inline one. This alleviates the XAML bug where the spin button would appear over the number box's input value.
2. Fixes an issue where a long X/Y value would resize the settings controls weirdly. This was fixed by introducing a `Grid` inside the main grid and applying a width to the number boxes.
3. Rename "Use system default" checkbox to be more clear. Propagate the new localized string into expander preview.
Closes #14558

[SUI] Polish Launch Parameters setting controls

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/ConptyConnection.h
src/host/PtySignalInputThread.cpp
src/host/VtIo.cpp
src/host/VtIo.hpp
src/host/output.cpp
src/inc/conpty-static.h
src/winconpty/dll/winconpty.def
src/winconpty/ft_pty/ConPtyTests.cpp
src/winconpty/ft_pty/winconpty.FeatureTests.vcxproj
src/winconpty/winconpty.cpp
src/winconpty/winconpty.h

2 new ConPTY APIs were added as part of this commit:
* `ClosePseudoConsoleTimeout`
Complements `ClosePseudoConsole`, allowing users to override the `INFINITE`
wait for OpenConsole to exit with any arbitrary timeout, including 0.
* `ConptyReleasePseudoConsole`
This releases the `\Reference` handle held by the `HPCON`. While it makes
launching further PTY clients via `PROC_THREAD_ATTRIBUTE_PSEUDOCONSOLE`
impossible, it does allow conhost/OpenConsole to exit naturally once all
console clients have disconnected. This makes it unnecessary to having to
monitor the exit of the spawned shell/application, just to then call
`ClosePseudoConsole`, while carefully continuing to read from the output
pipe. Instead users can now just read from the output pipe until it is
closed, knowing for sure that no …

Add support for start /B and FreeConsole

---

src/types/UiaTextRangeBase.cpp

This PR replaces the uses of `Viewport::CompareInBounds()` in the UIA code with `til::point` comparators. Additionally, it simplifies the logic further by using `std::max` and `std::min`.
In doing so, we are no longer hitting the `assert` in `CompareInBounds()`.
Closes #14542

Replace UIA CompareInBounds with til::point comparators

---

.github/workflows/addToProject.yml

This PR adds explicit [permissions section] to workflows. This is a
security best practice because by default workflows run with [extended
set of permissions] (except from `on: pull_request` [from external
forks]). By specifying any permission explicitly all others are set to
none. By using the principle of least privilege the damage a compromised
workflow can do (because of an [injection] or compromised third party
tool or action) is restricted.
It is recommended to have [most strict permissions on the top level] and
grant write permissions on [job level] case by case.
[permissions section]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
[extended set of permissions]: https://docs.github.com/en/actions/security-guides/automatic-token-auth …

GitHub Workflows security hardening

---

src/cascadia/WindowsTerminal/IslandWindow.cpp

Fix access violation on lParam when constructing wstring.
Per the [WM_SETTINGSCHANGE docs], NULL is a valid value for lParam. A
null lParam was observed when using the 'Switch User' feature of Windows
while developing the Terminal app.
Reproduced the scenario w/ the check in place and verified no crash.
Closes #14652
[WM_SETTINGSCHANGE docs]: https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-settingchange

Check for null lParam in WM_SETTINGSCHANGE

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/dll/TerminalControl.vcxproj
src/cascadia/TerminalControl/pch.h

Grab all paths from `DROPFILES` struct provided in drag event data
`GetStorageItemsAsync()` only giving up to 16 items when items are dropped from any archives
- When this occurs, we should look into `FileDrop` key for a stream of the [`DROPFILES struct`](https://learn.microsoft.com/en-us/windows/win32/shell/clipboard#cf_hdrop)
- This struct contains a null-character delimited string of paths which we can just read out
Closes #14628

Fix missing paths when items dropped from archive

---

src/renderer/base/renderer.cpp

Depending on the line rendition, and whether the cursor is over a wide
character or not, it's possible for the width to take up anywhere from 1
to 4 cells. And when it's more than 1 cell wide, part of the cursor may
end up off screen. However, our bounds check requires the entire cursor
to be on screen, otherwise it doesn't render anything, and that can
result in cursor droppings being left behind. This PR fixes that.
The bounds check that is causing this issue was introduced in #13001 to
fix a debug assertion.
To fix this, I've removed the bounds checking, and instead clip the
cursor rect to the boundaries of the viewport. This is what the original
code was trying to do prior to the #13001 fix, but was mistakenly using
the `Viewport:Clamp` method, instead of `TrimToViewport`. Since this …

Correct the cursor invalidation region

---

src/interactivity/base/InteractivityFactory.cpp
src/interactivity/base/InteractivityFactory.hpp
src/interactivity/base/PseudoConsoleWindowAccessibilityProvider.cpp
src/interactivity/base/PseudoConsoleWindowAccessibilityProvider.hpp
src/interactivity/base/lib/InteractivityBase.vcxproj
src/interactivity/base/lib/InteractivityBase.vcxproj.filters
src/interactivity/base/sources.inc

In order to modify the accessibility information for the PseudoConsoleWindow, it needs to have a UIA provider registered. This PR introduces `PseudoConsoleWindowAccessibilityProvider` and registers it as a UIA provider appropriately. The registration process is based on that of the `WindowUiaProvider` for ConHost.
Closes #14385
Run Accessibility Insights FastPass on the window. The PseudoConsoleWindow no longer is tagged as missing a name.

Introduce PseudoConsoleWindow a11y provider

---

src/host/output.cpp
src/host/ut_host/ScreenBufferTests.cpp
src/terminal/adapter/adaptDispatch.cpp

When the buffer contains wide characters that occupy more than one cell,
and those cells are scrolled horizontally by exactly one column, that
operation can result in the wide characters being completely erased.
This PR attempts to fix that bug, although it's not an ideal long term
solution.
Although not really to blame, it was PR #13626 that exposed this issue.
The root of the problem is that scrolling operations copy cells one by
one, but wide characters are written to the buffer two cells at a time.
So when you move a wide character one position to the left or right, it
can overwrite itself before it's finished copying, and the end result is
the whole character gets erased.
I've attempt to solve this by getting the affected operations to read
two cells in advance before they start …

Prevent horizontally scrolling wide chars erasing themselves

---

.github/actions/spelling/expect/expect.txt
doc/cascadia/profiles.schema.json
src/cascadia/WindowsTerminal/IslandWindow.cpp

This is just #14666 ported to 1.16. Only diff is that useMica is removed. 
Related to https://github.com/microsoft/terminal/issues/14560

Add the Theme schema for 1.16

---

src/cascadia/TerminalSettingsModel/JsonUtils.h

CascadiaSettings relies on getting a JsonUtils::DeserializationException
from the various JSON Utility functions, and then formatting that into
an error message. Well, DeserializationException tries to include an
object representation in its what() message . . . and generates an
exception trying to do so. CascadiaSettings never gets the
DeserializationException, and displays a weird message.
It's safe to remove the stringification in DeserializationException
because CascadiaSettings was never using it (_and_ because
CascadiaSettings was using an even better version of the same logic.)
Fixes #14373

Fix an issue where JsonUtils produces a bad error message

---

src/cascadia/PublicTerminalCore/HwndTerminal.cpp

#14461 is caused by a null pointer exception in `TerminalIsSelectionActive()`. Since this reveals that it is possible to enter a state where `_terminal` is null, I've gone ahead and added null-checks throughout the code to make it more stable.
Closes #14461
Ran locally. Still works.

[WPF] Add TermCore null checks to HwndTerminal

---

src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp

This builds upon #10749. When we added a separate pivot to track the "active" anchor, we forgot to update the pivot while circling. What does that mean? Moving the mouse would trigger us to update the selection using new endpoint and the old _pivot_, which hadn't been updated. 
There's probably a more elegant way of doing this, but it's good enough. 
Updated the test to cover this as well. 
Closes #14462

Make sure to update the selection pivot while circling

---

src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

Updates the tab event handling so that the "Export Text" and "Find" tab context menu items work when a tab isn't focused.
Manually tested.

Ensure export and find tab context menu items work for unfocused tabs

---

src/cascadia/TerminalApp/TabBase.cpp

Basically what it says on the tin. For transparent tabs, we should layer on to the tab row to evaluate what the actual color of the tab will be. We did this for deselected tabs, but not for selected ones.
Gif below.
Closes #14561

Make sure focused tab text color accounts for alpha

---

src/cascadia/TerminalControl/TermControlAutomationPeer.cpp
src/cascadia/TerminalControl/TermControlAutomationPeer.h
src/cascadia/TerminalControl/pch.h

Some investigation revealed that `_keyEvents` would get a `NULL_POINTER_READ` error. On the main thread, `RecordKeyEvent()` would be called, which mainly updates `_keyEvents`. On the renderer thread, `NotifyNewOutput()` would be called, which starts by iterating through `_keyEvents` and slowly clearing it out. On occasion, these two threads are modifying `_keyEvents` simultaneously, causing a crash.
The fix is to add a mutex on this variable. 
Closes #14592

Add mutex to keyEvents in TermControlAutomationPeer

---

src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp

As of about 2022, the one's digit of the Build of our version is a placeholder value to differentiate the Windows 10 build from the Windows 11 build. Let's trim that out, it's only a source of confusion.
For additional clarity, let's omit the Revision, which _must_ be `.0`, and doesn't provide any value to report.
We will need to make sure we report releases as `1.17.ABC` now, instead of `1.17.ABC1.0`/`1.17.ABC2.0`
Let's not backport this. 1.17 will be the start of the new numbering scheme. Otherwise, `1.16.EFG` < `1.16.ABC1.0`, for an old version `ABC1` and a new version `EFG`.
* closes #14106
* As summarized here: https://github.com/microsoft/terminal/issues/14106#issuecomment-1289462310

Remove the win10/win11 digit from our version number. 

---

src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp
src/cascadia/TerminalSettingsEditor/ColorSchemes.h

When we navigate to the color schemes page, find the default color scheme (if present) and manually set the container's automation name to include the word 'default'. 
Note that we don't want to change the actual `ColorSchemeViewModel`'s name since that name is used internally to identify schemes. We only want to change the `ListViewItem`'s name, i.e. the container in the SUI.
Screen reader reads out the 'default' text now. It also correctly reads out the new default scheme if the default scheme is changed via SUI or json.

Manually set the automation name of the default color scheme for screen reader

---

src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml

Specify the resource to use for the list view item background when selected.
References #14693 
Background is no longer blue, it is light gray (like in Windows 11). Screenshots below.

Fix the selected color scheme list item container background being blue in Windows 10

---

src/cascadia/WindowsTerminal/AppHost.cpp

We forgot to updateTheme again when we change the titlebar color. That would result in us setting the titlebar visibility only when the settings were reloaded, but if the unfocused BG was opaque, and the focused was transparent, we'd use the current _unfocused_ color to set the titlebar visibility. 
Also, this fixes a bug with `tabRow.BG: terminalBackground`
from teams for brevity 
> tabRow.BG = terminalBackground might not work, and here's why
>
> the termcontrol's BG brush might be (r,g,b, 255), with an Opacity of 0
> 
> so my "use mica when the brush's A is <1.0" doesn't work
> 
closes #14563

Update the titlebar visibility when we gain/lose focus too

---

build/config/ESRPSigning_Terminal.json
build/pipelines/release.yml

Up until now, we have been relying on the catalog signature produced for our MSIX package.
There are some things (Packaged COM, Process Explorer as of 2022) that cannot handle catalog-signed
files. It's easier and safer for us to simply sign all the executables we produce before packaging them.
Unfortunately, we can't do it before we package them. We have to unpack and re-pack our package.
In the future, this will allow us to provide a codesigned distribution that is not in an MSIX package.
Ran a build and checked out the contents of the package. They were all signed!
Closes #13294
Closes #12695
Closes #9670

Code sign the contents of the Terminal package

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControlAutomationPeer.cpp
src/cascadia/TerminalControl/TermControlAutomationPeer.h

The `SignalTextChanged` crash seems to be occurring due to the `TermControlAutomationPeer` being destructed by the time the UIA event is actually dispatched. Even though we're already checking if TCAP and TermControl still exist, it could be that the TermControl is being closed as text is being output.
The proposed fix here is to record when the closing process starts and exposing that information directly to the TCAP. If TCAP sees that we're in the process of closing, don't bother sending a UIA event.
Closes #13978

Ensure TermControl is not closing when firing UIA events

---

src/cascadia/WindowsTerminal/IslandWindow.cpp

Major thanks to @dongle-the-gadget in https://github.com/microsoft/microsoft-ui-xaml/issues/3577#issuecomment-1399250405 for coming up with this workaround.
This PR will manually forward a `WM_SIZE` message to our `CoreWindow`, to trigger the `ContentDialog` to resize itself. 
We always closed these issues as dupes of the upstream one, so this doesn't actually close anything.
HOWEVER, these are the following issues that reported this bug:
- #2380
- #4463
- #5252
- #5810
- #6181
- #7113
- #7225
- #8245
- #8496
- #8643
- #9336
- #9563
- #5808
- #10351
- #10634
- #10995
- #11770
- #13796

Resize our ContentDialog's when the window resizes

---

src/renderer/uia/UiaRenderer.cpp

For some reason, Windows Terminal stops dispatching UIA TextChanged events sometimes. There isn't a reliable repro for this bug.
However, under NVDA's logger, it appears that when the bug does occur, we still dispatch UIA notifications (which may be ignored by NVDA in some configurations). A "quick fix" here is to dispatch a TextChanged event if we're going to dispatch a notification. Since we're just enabling a flag, we won't send two events at once.
Closes #10911

[UIA] Dispatch a TextChanged event on new output

---

tools/ReleaseEngineering/New-TerminalStackedChangelog.ps1

New-TerminalStackedChangelog used to generate logs that looked like this:
```
* [3] A commit that was seen 3 times
* A commit that was only seen once
* [2] Some other commit
```
Now it will generate logs that look like this:
```
/ base..branch-1
|/ base..branch-2
||/ base..branch-3
* [XXX] A commit that was seen 3 times
* [ X ] A commit that was only seen once
* [XX ] Some other commit
```
This format is more expressive, as it indicates _which branches_ contain which commits.
As a reminder, my release note writing style starts with a stacked changelog. It's how I tell (1) which commits are in the new preview release only, (2) which commits are in the new preview and the new stable release and (3) which commits were already released in a previous stable release.
Changes from 1 get included …

When generating a stacked changelog, note which branch/es contain a commit

---

src/host/_stream.cpp
src/host/ft_host/API_ModeTests.cpp
src/host/getset.cpp
src/host/outputStream.cpp
src/host/renderData.cpp
src/host/screenInfo.cpp
src/host/settings.cpp
src/host/settings.hpp
src/host/srvinit.cpp
src/host/telemetry.cpp
src/host/ut_host/TextBufferTests.cpp

The original console output modes were considered attributes of the
buffer, while later additions were treated as global state, and yet both
were accessed via the same buffer-based API. This could result in the
reported modes being out of sync with the way the system was actually
behaving, and a call to `SetConsoleMode` without updating anything could
still trigger unpredictable changes in behavior.
This PR attempts to address that problem by making all modes part of the
buffer state, and giving them predictable default values.
While this won't solve all the tmux layout-breaking issues in #6987, it
does at least fix one case which was the result of an unexpected change
in the `DISABLE_NEWLINE_AUTO_RETURN` mode.
All access to the output modes is now done via the `OutputMode` field in …

Make all console output modes more strictly buffer state

---

src/host/dbcs.cpp
src/interactivity/win32/windowio.cpp
src/types/KeyEvent.cpp
src/types/inc/IInputEvent.hpp

When working on #14745 I found `KeyEvent`s a little hard to read in the
debugger. I noticed that this is because of sign extension when converting
`char`s to `wchar_t`s in `KeyEvent::SetCharData`.

Make KeyEvent char data a little less confusing

---

src/host/misc.cpp

When working on #14745 I noticed that `SplitToOem` was in a bit of a poor state
as well. Instead of simply iterating over its `deque` argument and writing the
results into a new `deque` it used `pop` to advance the head of both queues.
This isn't quite exception safe and rather bloaty. Additionally there's no need
to call `WideCharToMultiByte` twice on each character if we know that the most
verbose encoding is UTF-8 which can't be any more than 4 chars anyways.
Related to #8000.
* 2 unit tests cover this ✅

Minor improvements for SplitToOem

---

.github/actions/spelling/allow/apis.txt
.github/actions/spelling/expect/expect.txt
build/config/ESRPSigning_Terminal.json
build/pipelines/release.yml
build/pipelines/templates/build-console-compliance-job.yml
build/scripts/Test-WindowsTerminalPackage.ps1
dep/nuget/packages.config
scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalConnection/AzureClient.h
src/cascadia/TerminalConnection/AzureConnection.cpp
src/cascadia/TerminalConnection/AzureConnection.h
src/cascadia/TerminalConnection/TerminalConnection.vcxproj
src/cascadia/TerminalConnection/pch.h
src/common.nugetversions.targets
src/features.xml

This pull request removes, in full, our dependency on cpprestsdk. This
allows us to shed 500KiB-1.2MiB from our package off the top and enables
the following future investments:
- Removal of the App CRT forwarders to save an additional ~500KiB
- Switching over to the HybridCRT and removing our dependency on _any
CRT_.
cpprest was built on my dev box two or so years ago, and is in _utter_
violation of our compliance guidelines on SBOM et al.
In addition, this change allows us to use the proxy server configured
in Windows Settings.
I did this in four steps (represented roughly by the individual commits):
1. Switch from cpprest's http_client/json to Windows.Web.Http and
Windows.Data.Json
2. Switch from websocketpp to winhttp.dll's WebSocket implementation¹
3. Remove all remaining utility …

AzureConnection: remove our dependency on cpprestsdk

---

src/cascadia/TerminalApp/TabManagement.cpp

Dragging and dropping tabs now selects them
Closes #12473

Update tab drop behavior to select dropped tab

---

src/cascadia/TerminalSettingsEditor/Appearances.cpp
src/cascadia/TerminalSettingsEditor/Appearances.h
src/cascadia/TerminalSettingsEditor/Appearances.idl
src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.cpp
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.h
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.idl
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.xaml
src/cascadia/TerminalSettingsEditor/Profiles_Base.cpp
src/cascadia/TerminalSettingsEditor/Profiles_Base.h

Let the profile pages' views have access to the window root, rather than the `ProfileViewModel`. The window root is passed along when the page is navigated to.
Clicking `Browse` no longer crashes.

Pass the window root to the profile page views, instead of the view model

---

src/buffer/out/OutputCellIterator.cpp
src/buffer/out/OutputCellIterator.hpp
src/buffer/out/Row.cpp
src/host/ft_host/CJK_DbcsTests.cpp

#13626 contains a small "regression" compared to #13321:
It now began to store trailers in the buffer wherever possible to allow a region
of the buffer to be backed up and restored via Read/WriteConsoleOutput.
But we're unfortunately still ill-equipped to handle anything but UCS-2 via
WriteConsoleOutput, so it's best to again ignore trailers just like in #13321.
* Added unit test ✅

Ignore CHAR_INFO trailers during WriteConsoleOutput

---

src/cascadia/TerminalCore/lib/terminalcore-lib.vcxproj

It was just by luck that TerminalCore usually built after MidiAudio

Add a proper reference from TermCore to MidiAudio

---

src/cascadia/LocalTests_SettingsModel/JsonTestClass.h
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalSettingsModel/ApplicationState.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/Command.cpp
src/cascadia/WindowsTerminal/BaseWindow.h
src/host/ut_host/ClipboardTests.cpp
src/propsheet/console.def
src/propslib/DelegationConfig.cpp
src/renderer/inc/IRenderEngine.hpp
src/terminal/adapter/adaptDispatchGraphics.cpp
src/terminal/adapter/telemetry.cpp
src/terminal/parser/telemetry.cpp
src/tools/lnkd/main.cpp
src/tools/pixels/main.cpp
src/tools/test/main.cpp

* `lld-link` is more strict about the casing of keywords in `.def` files
* `[[nodiscard]]` must come before `virtual` and `static` qualifiers
* `precomp.h` is never to be included with `<>`
* We were calling the jsoncpp constructors directly (oops) as functions (oops)
* ClipboardTests constructed `KeyEvent`s by copy instead of directly
I don't know about the Dispatcher one, but it looks more correct this way. Also, it compiles. That was done before the C++/WinRT update, so maybe they fixed it as well.

Fix a number of minor correctness issues that Clang flagged

---

dep/nuget/packages.config
scratch/ScratchIslandApp/SampleApp/packages.config
scratch/ScratchIslandApp/WindowExe/packages.config
src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
src/cascadia/WindowsTerminal/AppHost.cpp
src/common.nugetversions.props
src/common.nugetversions.targets

Interesting things we could do after this:
- remove all `InitializeComponent` calls - they do it automatically
- have some Clang support (!)
- use `std::optional`<->`IReference` automatic binding
- use `std::format` support (!) for json/uri/hostname/http stuff/all `IStringable`s
- potentially move to `/await:strict` for C++20 coroutines
I've also fixed up a couple ambiguities introduced by this change.

Move to CppWinRT 2.0.230207.1

---

src/cascadia/LocalTests_SettingsModel/SettingsModel.LocalTests.vcxproj
src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
src/cascadia/TerminalSettingsModel/IconPathConverter.cpp
src/cascadia/TerminalSettingsModel/JsonUtils.h
src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
src/cascadia/WinRTUtils/inc/Utils.h
src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj

Our templates were declared in the wrong order in JsonUtils, so all we needed to do was reorder them. The tests bear this out.
This allows us to disable two-phase template name lookup. I also fixed a minor issue that resulted in the inclusion of too many copies of expandIconPath.

Correctness: Remove JsonUtils and IconConverter's 2-phase lookup bugs

---

src/renderer/atlas/AtlasEngine.api.cpp

Woops. Closes #14878
* Font Family: Iosevka Term (v19.0.1)
* Font Size: 11pt (or 10px cell height in conhost)
* Display Scale: 100%
* "--------------" leaves no gap between the text and the cursor ✅

AtlasEngine: Fix calculation of advanceScale

---

src/buffer/out/cursor.cpp
src/buffer/out/cursor.h
src/buffer/out/textBuffer.cpp
src/host/ut_host/ScreenBufferTests.cpp
src/renderer/vt/paint.cpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp

When a character is written in the last column of a row, the cursor
doesn't move, but instead sets a "delayed EOL wrap" flag. If another
character is then output while that flag is still set, the cursor moves
to the start of the next line, before writing to the buffer.
That flag is supposed to be reset when certain control sequences are
executed, but prior to now we haven't always handled that correctly.
With this PR, we should be resetting the flag appropriately in all the
places that it's expected to be reset.
For the most part, I'm following the DEC STD 070 reference, which lists
a bunch of operations that are intended to reset the delayed wrap flag:
`DECSTBM`, `DECSWL`, `DECDWL`, `DECDHL`, setting `DECCOLM` and `DECOM`,
resetting `DECCOLM`, `DECOM`, and `DECAWM`, `CUU`, `CUD`, `CUF`, …

Ensure that delayed EOL wrap is reset when necessary

---

src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalSelection.cpp

This fixes a couple of audit failures in `TerminalCore` where the
compiler was complaining about functions that should have been declared
as `noexcept`.
These failures have actually existed for a while, but you'd only see
them if you ran the audit build locally. They only recently started
showing up on the CI build server - I'm guessing because the compiler
there has now been upgraded.
Compiled the audit build locally and it no longer fails.

Fix audit failures in TerminalCore

---

samples/PixelShaders/Outlines.hlsl

The `Sample` method has an offset parameter which we can use here.
The result is not identical to the old shader, as the older shader
used the height of the terminal for drawing horizontal edges and so
the result looked way fatter than it was seemingly originally intended.
On my 150% scale display I found an offset of +/- 2px to produce an
acceptable result, although in the future it might be worthwhile to
make the offset dependent on the UI scale.
Closes #14953

Fix offset calculation in the outlines shader

---

src/cascadia/TerminalApp/TerminalPage.cpp

Does two things related to URLs emitted via OSC8. 
* Allows `wsl$` and `wsl.localhost` as the hostname in `file://` URIs
* Generally allows _all_ URIs that parse as a URI. 
The relevant security comments: https://github.com/microsoft/terminal/pull/7526#issuecomment-764160208
> this doesn't let a would-be attacker specify command-line arguments (ala "cmd.exe /s /c do_a_bad_thing") (using somebody else's reputation to cause mayhem)
> 
> `ShellExecute` de-elevates because it bounces a launch request off the shell
> 
> "Works predictably for 15% of applications" (h/t to PhMajerus' AXSH, and other on-Windows requestors) is better in so many ways than "Works for 0% of applications", in my estimation. Incremental progress :smile: while we work on features that'll make it even more broadly …

Allow wsl$ in file URIs; generally allow all URI schemes

---

src/cascadia/WpfTerminalControl/TerminalControl.xaml.cs

Azure Devops jumps to these as the first "error" when you open a failing build. But these are warnings, not errors. So you're left hunting for the real error. _If only someone had scrollbar marks for indicating lines with error messages..._
May as well clean them up.

Fix some simple C# linter warnings

---

src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/ut_adapter/adapterTest.cpp

This PR adds support for querying the color indices set by the `DECAC`
control, using the existing `DECRQSS` implementation.
The initial `DECRQSS` support was added in PR #11152.
The `DECAC` functionality was added in PR #13058, but at the time we
didn't know how to format the associated `DECRQSS` query.
For most `DECRQSS` queries, the setting being requested is identified by
the final characters of its escape sequence. However, for the `DECAC`
settings, you also need to include a parameter value, to indicate which
color item you're querying.
This meant we needed to extend the `DECRQSS` parser, so I also took this
opportunity to ensure we correctly parsed any parameter prefix chars. We
don't yet support any setting requiring a prefix, but this makes sure we
don't respond incorrectly if an …

Add support for querying the DECAC settings

---

.github/actions/spelling/expect/expect.txt
src/host/inputReadHandleData.cpp
src/host/readDataCooked.cpp
src/host/stream.cpp

#14745 contains two regressions related to console alias handling:
* When `ProcessAliases` expands the backup buffer into (an) aliased
command(s) it changes the `_bytesRead` field of `COOKED_READ_DATA`,
requiring us to re-read it and reconstruct the `input` string-view.
* Multiline aliases are read line-by-line whereas #14745 didn't treat
them any different from regular single-line inputs.
In `cmd.exe` run
```
doskey test=echo foo$Techo bar$Techo baz
test
```
The output should look exactly like this:
```
C:\>doskey test=echo foo$Techo bar$Techo baz
C:\>test
foo
C:\>bar
C:\>baz
C:\>
```

Fix console aliases not working

---

.github/workflows/winget.yml

[The winget-releaser action] automatically generates manifests for the
[Winget Community Repository] and submits them.
I suggest adding Dependabot to keep the action up to date. There were
many cases where the action was failing due to an outdated version.
Closes #14795
[The winget-releaser action]: https://github.com/vedantmgoyal2009/winget-releaser
[Winget Community Repository]: https://github.com/microsoft/winget-pkgs

Add a Winget Releaser workflow

---

.github/workflows/winget.yml

It was brought to my attention that we should be more restrictive in which tasks we ovver a GitHub token to. Sorry!
With thanks to sitiom for the version parsing and the magic GitHub action syntax incantation for determining what is a prerelease.

winget.yml: switch to manually using wingetcreate

---

src/host/ut_host/ScreenBufferTests.cpp
src/terminal/adapter/adaptDispatch.cpp

When a `DECCRA` operation is copying content that spans a double width
line, it's possible that some range of the bounding rectangle will be
off-screen, and that range is not supposed to be copied. However, the
code checking for off-screen positions was using incorrect coordinates,
so we would mistakenly copy content that shouldn't be copied, and drop
content that should have been copied. This PR fixes that.
This was a regression introduced in PR #14650 when fixing an issue with
horizontal scrolling of DBCS characters.
I manually verified this fixes the test case in #15019, and I've also
added a unit test that replicates that case.
Closes #15019

Fix DECCRA when copying from a double-width line

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalSettingsModel/VsDevCmdGenerator.cpp

The PowerShell equivalent was added in the initial pull request, #7774.
Closes #13721

VsDevCmdGenerator: respect the user's startingDirectory

---

src/cascadia/TerminalApp/TerminalWindow.cpp
src/cascadia/WindowsTerminal/AppHost.cpp

If we get initialized with a window name, this will be called before XAML is stood up, and constructing a PropertyChangedEventArgs will throw. So don't.
Regressed in #14843 
Related to #5000, #14957

Fix `wt -w _quake` by not throwing when setting the window name

---

src/cascadia/TerminalSettingsEditor/AddProfile.xaml
src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/WpfTerminalControl/TerminalContainer.cs

* These `Icon` bindings were to `Profile`s which aren't Observable, but it also doesn't matter
* More c# warnings
hopefully we'll just jump straight to real errors now.

Clean up more warnings

---

src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest

[Flexible Virtualization] is a little more restrictive than `unvirtualizedResources`, but it's more descriptive and stands a chance of working on Windows 10.
This makes `unvirtualizedResources` actually work for us - we can tell the system exactly which registry keys we want to use. This is required for our registry writes to work on Windows 10.
[Flexible Virtualization]: https://learn.microsoft.com/en-us/windows/msix/desktop/flexible-virtualization

Add flexible virtualization rules for HKCU\Console\Startup

---

src/host/ut_host/ScreenBufferTests.cpp
src/terminal/adapter/adaptDispatch.cpp

When saving and restoring the cursor position with origin mode enabled,
we originally matched the behavior of the early DEC terminals, which
stored the position as an absolute offset. But if the margin boundaries
were changed prior to restoring the position, that could result in the
cursor being outside the margins, potentially with negative coordinates.
Our implementation avoided that bug by clamping the coordinates back
into range, but that's not how DEC ultimately fixed the issue. Starting
with the VT420, they began using relative coordinates (i.e. relative to
the margin origin), so a restored position could never end up negative.
This PR updates our implementation to match that newer behavior.
Thank to testing performed by @al20878, we know this was the algorithm
used on the VT420, …

Update DECSC/DECRC to match the newer DEC terminals

---

src/server/ApiMessage.cpp
src/server/ApiMessage.h

#14745 removed the only user of `GetAugmentedOutputBuffer`.

Minor cleanups after #14745

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

Due to a bad merge a few commits back. This event should have had a revoker. 
Probably regressed in #14851

Fix a crash in the rclick context menu

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalSettingsEditor/MainPage.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettings.idl
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/FileUtils.cpp
src/cascadia/TerminalSettingsModel/FileUtils.h
src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw

This pull request implements portable mode for Windows Terminal, which
will make side by side deployment of different versions generally more
feasible.
Portable mode was specified in #15032.
There are three broad categories of changes in this PR:
1. Changes to settings loading.
2. A new indicator in the settings UI plus a link to the portable mode
docs.
3. A new application display name, `Terminal (Portable)`, which users
will hopefully include in their bug reports.
It's surprisingly small for how big a deal it is!
Related to #15034
Closes #1386

Add "portable mode", where settings load from the install path

---

src/cascadia/TerminalControl/ControlCore.cpp
src/renderer/base/renderer.cpp
src/renderer/base/renderer.hpp
src/renderer/dx/DxRenderer.cpp
src/renderer/dx/DxRenderer.hpp
src/renderer/inc/IRenderEngine.hpp

Rendering hyperlinks is unneccessarily complex at the moment, because
it requires you to implement `UpdateDrawingBrushes`, manually extract
the hyperlink flag from the given `TextAttribute` and save it until the
next call to `PaintBufferGridLines` which does not get that flag.
This isn't particularly clean as it assumes that `PaintBufferGridLines`
will be called after `UpdateDrawingBrushes` in the first place.
Instead, we can simply pass the hyperlink flag to `UpdateDrawingBrushes`
so that the renderers don't need to deal with this anymore.
* Hyperlinks show up with a dotted line ✅
* Hovering hyperlinks underline them ✅

Expose hyperlink attributes in PaintBufferGridLines

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalControl/TermControl.cpp

This will reduce the incidence of confusables, RTL, and non-printables messing with the display of the URL.

Format URLs for display when we show the tooltip

---

src/cascadia/ShellExtension/OpenTerminalHere.cpp
src/cascadia/ShellExtension/OpenTerminalHere.h
src/cascadia/WinRTUtils/inc/WtExeUtils.h

This pull request adds support for holding the control key and clicking the Open Terminal Here context menu item to elevate the request.
14810
- [ x] Closes #14810

Enable holding ctrl to open the Terminal elevated from File Explorer

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp
src/cascadia/WindowsTerminal/AppHost.cpp
src/inc/til/math.h

I noticed this bug while resizing my window on my 150% scale display.
Every 3 "snaps" of the window size, it would fail to resize the text
buffer. I found that this occurs, because we convert the swap chain
size from a float into a double, which converts my 597.333313 height
into 597.33331298828125, which then multiplied by 1.5 results in
895.999969482421875. If you just cast this to an integer, it'll
result in a height of 895px instead of the expected 896px.
This PR addresses the issue in two ways:
* Replace casts to integers with `lrint` or `floor`, etc.
* Remove many of the redundant double <> float conversions.
* Resizing my window always resizes the text buffer ✅

Fix accuracy bugs around float/double/int conversions

---

build/scripts/Test-WindowsTerminalPackage.ps1
dep/nuget/packages.config
scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj
scratch/ScratchIslandApp/WindowExe/packages.config
src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/common.nugetversions.targets

The upgrade to Microsoft.UI.Xaml 2.8 was the last piece we needed to
break our dependency on the App CRT *and* any CRT whatsoever.

Remove our dependency on any CRT--AppX or forwarders

---

.github/actions/spelling/expect/expect.txt
src/host/ut_host/ScreenBufferTests.cpp
src/terminal/parser/OutputStateMachineEngine.cpp

On a real VT terminal, most of the control characters that don't do
anything are supposed to be filtered out, and not written to the buffer.
Up to to now, though, we've only been filtering out `NUL`. This PR
extends our control processing to filter the remaining characters that
aren't supposed to be displayed.
We introduced filtering for the `NUL` control in PR #3015.
The are two special cases worth mentioning.
1. The `SUB` control's main purpose is to the cancel a control sequence
that is in progress, but it also needs to output an error character (a
reverse question mark) to the display.
2. The `DEL` control is typically filtered out, but when a 96-character
set is designated, it can sometimes be mapped to a printable glyph that
needs to be displayed.
I've manually tested that all the …

Filter out control characters that don't do anything

---

src/buffer/out/Row.cpp
src/buffer/out/Row.hpp
src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp

This will allow us to share the same fundamental text insertion
logic for both `ResizeTraditional` and `Reflow`, because both
can be implemented with `ROW::CopyRangeFrom`. It also replaces
the `BufferAllocator` struct with a `_allocateBuffer` function
which will help us allocate scratch buffer rows in the future.
Closes #14696
* Disable reflow resize in conhost
* Print "zhwik8.txt" - a enwik8.txt equivalent of Chinese Wikipedia
* Run `color 80` in cmd
* Resize windows from 120 to 119 columns
* Wide glyphs disappear and are replaced with whitespace ✅
* Resizing the window to >120 columns adds gray whitespace ✅

Use new row primitives for ResizeTraditional

---

.clang-format
.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlSettings.h
src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h
src/cascadia/TerminalSettingsEditor/ViewModelHelpers.idl.h
src/cascadia/TerminalSettingsModel/ActionArgs.h
src/cascadia/TerminalSettingsModel/IInheritable.idl.h
src/cascadia/inc/cppwinrt_utils.h
src/inc/til/bytes.h
src/inc/til/pmr.h
src/renderer/atlas/AtlasEngine.h
tools/packages.config

Upgrading clang-format lead to a few changes in the formatting
of code inside macros. Apart from the upgrade, I've also spent
some time removing all options from .clang-format that are
redundant with `BasedOnStyle: Microsoft`.

Upgrade clang-format to 15.0.7

---

src/cascadia/Remoting/WindowManager.cpp

Unpackaged installations don't have the luxury of magic package
isolation to stop them from accidentally touching each other's monarchs.
We need to enforce that ourselves by making their monarch CLSIDs unique
per install.
We'll use a v5 UUID based on the install folder to unique them.
Closes #15117

When unpackaged, isolate the monarch by the install path

---

src/host/stream.cpp

This is a regression caused by 599b550. If I'm reading `stream.cpp`
in cf87590 right, it returns `STATUS_SUCCESS` if `ReadCharacterInput`
read at least 1 character. I think? this PR makes the code behave
exactly equivalent. The old code is a bit of an "acquired taste"
so it's a bit hard to tell.
Closes #15116
* Run `more long_text_file.txt` in cmd
* Press Spacebar
* Scrolls down ✅
* Press Q
* Exits ✅

Return success if ReadCharacterInput read >0 characters

---

src/cascadia/TerminalSettingsEditor/GlobalAppearanceViewModel.cpp
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/defaults.json

This is a minimal version of the requests for #14858. In that thread we discussed FULL reverting the default themes to the old ones. In later discussion, we decided _meh_, let's just ship the legacy themes too, so it's easy to go back if you should choose. The default still remains the sane `dark`, but the `legacy*` themes are all right there, and given the same special treatment as the other inbox themes.
Closes #14858
Closes #14844

Add "legacy" themes

---

build/Helix/PrepareHelixPayload.ps1
src/cascadia/WindowsTerminal_UIATests/Elements/TerminalApp.cs

The unpackaged distribution was made for this exact use, so let's *do it*!

PGO: Update the Helix payload to rely on the unpackaged distribution

---

src/cascadia/PublicTerminalCore/HwndTerminal.cpp

This was an oversight in the original implementation

wpf: Bump the history length to 9001 instead of 1000

---

src/features.xml
src/host/exe/exemain.cpp

Some of our automated tooling detects this as being a private API that we're accessing via LoadLibrary/GetProcAddress. It's not *wrong*, but it's also not *right*.
It's easier for us to just not do it (and save all the code for it!) in OpenConsole.

Only try to hand off to ConhostV1 if building for Windows

---

src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

Yep, I forgot to not write them back to the settings file here.
Regressed in #15108 
Closes #15152

Fix re-persisting the new legacy themes

---

src/cascadia/TerminalCore/Terminal.cpp

When win32-input-mode is enabled, we generate an input sequence for both
key down and key up events. However, in the initial implementation the
key up sequence for most keypresses would be faked - they were generated
at the same time as the key down sequence, regardless of when the key
was actually released. After this PR, we'll only generate the key up
sequence once a key has actually been released.
The initial implementation of win32-input-mode was in PR #6309.
The spec for win32-input-mode was in PR #5887.
I've manually tested this with an app that polls `ReadConsoleInput` in a
loop and logs the results. With this PR applied, I can now see the key
up events as a key is released, rather than when it was first pressed.
When compared with conhost, though, there are some differences. When …

Send a KeyUp sequence only once a key has been released

---

src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp

Don't generate a profile for rancher-desktop utility WSL distro
Adds a check for rancher-desktop as well as docker. As mentioned in the discussion of this issue. This becomes much more difficult to maintain once other folks inevitably start to follow this pattern. But the easy win was up for grabs so I took it :)
Closes #12757

Skip generating a profile for rancher-desktop

---

src/cascadia/WindowsTerminal/AppHost.cpp

Moves our `GetWindowLayoutRequested` handler AFTER the xaml island is started. The `AppHost::_GetWindowLayoutAsync` handler requires us to be able to work on our UI thread, which requires that we have a `Dispatcher` ready for us to move to. If we set up this callback in the ctor, then it is possible for there to be a time slice where
* the monarch creates the peasant for us,
* we get ctor'ed (registering the callback)
* then the monarch attempts to query all _peasants_ for their layout, coming back to ask us even before XAML has been created.
I believe this was the source of the crash that was reported in a mail thread. It actually happened to me once while debugging another branch. Alas, this was realy hard to hit in the first place, so I'm not _totally_ certain this fixes it.
Related to …

Register the GetWindowLayoutRequested handler only when ready

---

src/cascadia/TerminalApp/TerminalWindow.cpp

Fixes an issue when using both:
```json
"centerOnLaunch": true,
"firstWindowPreference": "persistedWindowLayout",
```
In this case, the Terminal would ignore the persisted location and still just center on launch. This has been really annoying while testing tear-out, as we keep re-opening all my debug windows as a stack on top of each other.

Actually use the persisted position with `centerOnLaunch:true`

---

src/cascadia/TerminalApp/Pane.LayoutSizeNode.cpp
src/cascadia/TerminalApp/Pane.h

This pull request updates the implementation of the copy assignment operator for Pane::LayoutSizeNode to a more efficient version and eliminates the need for the _AssignChildNode code block. 
#11965 #11963 
My understanding of the discussion and intent of the two linked issues is that this is a more efficient way to implement the copy assignment operator for Pane.LayoutSizeNode and eliminates the need for the code block _AssignChildNode. Since both were relatively small changes, I combined the two in one PR. If that is not desirable, I can separate them. All existing tests continue to pass.
All existing tests pass. No visible changes in behavior of the terminal.

A more efficient copy assignment operator for Pane.LayoutSizeNode

---

src/cascadia/WpfTerminalControl/TerminalContainer.cs

Hides the cursor when null, shows it when not.
Clear the screen any time the connection is changed.
Prevents the WPF Control from crashing when set back to null, clears the console and hides the mouse as well.
#15061
It say 3 ansi commands as well now:
1) When the Connection is set to null the cursor is hidden (reflects what the default state is)
2) When the Connection is set to a value and it was null before we show the cursor (not a breaking change as requires it to have been null which previously would cause a crash, except for for set)
3) When the Connection is changed the screen is cleared.  A breaking change officially although not sure if there are use cases where this behavior is not desired.  For added safety we could make sure we are not being set to the same value we currently …

fix: WpfTerminalControl allow Connection set to null

---

src/buffer/out/textBuffer.cpp
src/terminal/adapter/adaptDispatch.cpp

The code changes are mostly self-explanatory: Just skip glyphs
that can never be inserted. I implemented it slightly incorrectly
(a newline will be inserted every time you write such a wide glyph),
but it's a niche issue and I think the simplicity of the fix is
more important than its exact correctness.
It also contains a fix for some severe log spam due to
`_PrepareForDoubleByteSequence` complaining in this situation.
The spam is so bad that it freezes the app for a few seconds
during text buffer reflow.
Closes #7416
* Open an extra pane and run `TerminalStress.exe` in there
* Resize to 1 column
* Doesn't hang ✅

Fix a hang when writing wide glyphs into a 1 column terminal

---

src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalWindow.cpp

TL;DR: we stopped getting `TabView.TabItemsChanged`. This meant that the tab view would change its apparent order, but we wouldn't change the backing tab order. 
I'm fixing this by grabbing the index of the tab that starts the drag, and the index of the tab view item at the end of the drag, and using that to reorder our backing list. 
Closes #15121
Upstream https://github.com/microsoft/microsoft-ui-xaml/issues/8388
Regressed in #15078 - I'm pretty confident about this, since I've got a 1.18.931 build of the Terminal with tear-out, but not MUX 2.8.

Fix reordering tabs mysteriously shuffling the actual backing tabs

---

dep/nuget/packages.config
src/common.nugetversions.props
src/common.nugetversions.targets

This fixes the BreadcrumbBar issue that would crash into the debugger anytime you open the SUI on a second thread.
See #14957.
Maybe also tracked in #15144 - let's have @j4james test when this merges.

Update to MUX 2.8.3

---

src/cascadia/LocalTests_TerminalApp/TabTests.cpp
src/cascadia/TerminalApp/AboutDialog.cpp
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.xaml

This sets `x:Load` to `false` for the two elements.
On my system, with Windows Defender disabled, this reduces CPU
usage by 15ms and the visual delay during launch by 40ms.
Part of #5907
* Ctrl+Shift+P opens command palette ✅
* Context menu opens command palette ✅
* Context menu opens about dialog ✅

Lazy load CommandPalette and AboutDialog

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Add subtext that lets the user know why Always show tabs is not toggleable in SUI. Also adds some additional information to the comment for this value that points to the Globals_ShowTitlebar.Header setting.
#13984 
Simple updates to the resources that add some additional helpful information for the user.
Verified the updates show in the SUI and that they render correctly.

Add subtext to why Always show tabs is not toggleable in SUI.

---

src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h

`WM_ACTIVATE` is sent on window creation, whereas `WM_SHOWWINDOW` is
sent when the window is shown. Before we call `Peasant::ActivateWindow`
in the `WM_ACTIVATE` handler, we try to get the virtual desktop GUID of
our window, but since it's not shown yet during startup, there's also
no GUID that can be retrieved. This results in an error log message and
an all 0 GUID to be sent via `Peasant::ActivateWindow`.
The GUID of the window that actually spawned on the other hand is never
reported until the first time you reactivate it again, leading to a
number of subtle bugs around window activity.
Additionally, this commit fixes a race condition and pointer unsafety,
by pulling all relevant member variables onto the coroutine's stack,
before it yields itself to a background thread.
- Set a trace …

Fix Peasant::ActivateWindow being called with an all 0 GUID

---

src/cascadia/TerminalApp/App.xaml
src/cascadia/TerminalApp/SettingsTab.cpp
src/cascadia/TerminalApp/SettingsTab.h
src/cascadia/TerminalApp/TabBase.cpp
src/cascadia/TerminalApp/TabBase.h
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.xaml

This fixes 3 sources for animations:
* `TabView`'s `EntranceThemeTransition` causes tabs to slowly slide in
from the bottom. Removing the transition requires you to override the
entire list of transitions obviously, which is a global change. Nice.
Am I glad I don't need to deal with the complexity of CSS. /s
* `TabBase`, `SettingsTab` and `TerminalTab` where using a lot of
coroutines with `resume_foreground` even though almost none of the
functions are called from background tabs in the first place. This
caused us to miss the initial XAML drawing pass, which resulted in
animations when the tab icons would asynchronously pop into existence.
It also appears as if `resume_foreground`, etc. have a very high CPU
cost attached, which surprises me absolutely not at all given WinRT.
The …

Avoid animations during startup

---

src/cascadia/TerminalApp/AboutDialog.xaml

Add automation heading level 1 to fix the about dialog by adding an automation property.
Allows screen reader to pick up that this is a heading and read properly.
Closes #11912

Add automation heading level 1 to fix about dialog

---

src/cascadia/TerminalApp/TerminalWindow.cpp

Default to XamlRoot when unable to find a focused object in DirectKeyEvents
This may not be the most appropriate "fix" for this. Certainly open to criticism and feedback. We are trapping the alt+space key chord on the win32 side and forwarding it to the xaml side. There we try to find a focused object by walking the xaml tree. If we are unable to find a focused object we return false and do nothing.  I suspect that the area that has focus that prevents this from working normally is on the win32 side.  Since we want to handle the system menu anyway and are explicitly trapping that key combo and forwarding it on I thought this was the best approach. If we cant find a focused object default to the xaml root.
System menu opens as it should.
Closes #14397

Default to XamlRoot when unable to find focused object

---

src/cascadia/TerminalApp/TerminalPage.cpp

Fixes a crash when pressing a keybinding in the settings tab. 
Regressed in #15203
Noted in #14051

Make sure the command palette isn't null

---

src/cascadia/TerminalApp/TabBase.cpp

Just changing the Theme also doesn't seem to work by itself - there seems to be a way for the tab to set the deselected foreground onto itself as it becomes selected. If the mouse isn't over the tab, that can result in mismatched fg/bg's 
Regressed around #15078 
Closes #15184

Also do the VisualState dance on the tab item

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/CommandPalette.h
src/cppwinrt.build.pre.props

`WINRT_LEAN_AND_MEAN` removes a bunch of less often used parts of the C++/WinRT headers:
- `std::hash` specializations for every object
- `operator <<(ostream)` overloads for any `IStringable`
- Interface producers for interfaces that are marked "exclusive"
There's only one place where we were using even one of these.
Enabling this saves us (optimistically) 30 seconds of build time on the CI agents and shrinks our largest PCH (TerminalApp, x64, Debug) by about 150MiB.
It's not huge, but it's not nothing.

Enable WINRT_LEAN_AND_MEAN

---

src/cascadia/TerminalApp/TerminalPage.cpp

Original bug report #15049
Relates to feature #1571 
MenuFlyoutSubItem, when collapsing from profile selection, move focus back to the titlebar. 
An extra Closing event handler is needed to keep focus on the command shell.
Closes #15049

Fix focus issue when profile selected from nested menu entry

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h

Apparently, `std::function` is bad and we should feel bad. I friggen hate the c++ function pointer syntax, but [I do what I'm told](https://getyarn.io/yarn-clip/85c318d8-f4a7-4da6-ae20-23d7b737e71c)
I missed this comment in #15020. Sorry!

Switch to function pointers

---

src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/Pane.h

It seemed dangerous to just have places all over Pane where we manipulate the whole cadre of TermControl events. Seemed ripe for a copypasta error. This moves that around, so there's only two methods for messing with the TermControl callbacks: `_setupControlEvents` and `_removeControlEvents`.
Closes: nothing. This was an off-the-cuff commit that seemed valuable.

A very sensible Pane refactoring

---

src/cascadia/TerminalControl/ControlCore.cpp
src/renderer/base/renderer.cpp
src/renderer/base/renderer.hpp

This bug causes AtlasEngine to render buffer contents with an incorrect
`cellCount`, which may either cause it to draw the contents only
partially, or potentially access the TextBuffer contents out of bounds.
`EnablePainting` sets the `_viewport` to the current viewport for some
unfortunate (and quite buggy/incorrect) caching purposes, which causes
`_CheckViewportAndScroll()` to think that the viewport hasn't changed
in the new window. We can ensure `_CheckViewportAndScroll()` works
by also setting `_forceUpdateViewport` to `true`.
Part of #14957
* Tear out a tab from a smaller window to a larger window
* Renderer contents adept to the larger window size ✅

Fix missing call to UpdateViewport::UpdateViewport during tearout

---

src/cascadia/WindowsTerminal/WindowEmperor.cpp

We had a report in a mail thread that someone's Terminal windows were getting created hidden, and never showing themselves.
As a theory, I'm guessing that dwFlags didn't say that we should actually use `wShowWindow`. So, to be more correct, let's actually obey that.
I'm gonna send this package to them to see if it fixes them.
Related to #14957.
Likely regressed in #13838.

A hypothetical fix for hidden windows

---

src/terminal/adapter/DispatchTypes.hpp
src/terminal/parser/ut_parser/StateMachineTest.cpp

There are certain escape sequences that use the `VTParameters::subspan`
method to access a subsection of the provided parameter list. When the
parameter list is empty, that `subspan` call can end up using an offset
that is out of range, which causes the terminal to crash. This PR stops
that from happening by clamping the offset so it's in range.
This bug effected the `DECCARA` and `DECRARA` operations introduced in
PR #14285, and the `DECPS` operation introduced in PR #13208.
I've manually confirmed that the sequences mentioned above are no longer
crashing when executed with an empty parameter list, and I've added a
little unit test that checks `VTParameters::subspan` method is returning
the expected results when passed an offset that is out of range.

Prevent crash when VTParameters::subspan is out of range

---

src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/ut_adapter/adapterTest.cpp

This is an update of our Primary Device Attributes report, which better
indicates the feature extensions that we now support.
This first parameter of the response is 61, representing a conformance
level of 1. The subsequent parameters identify the supported feature
extensions.
1 = 132 column mode
6 = Selective erase
7 = Soft fonts
22 = Color text
23 = Greek character sets
24 = Turkish character sets
28 = Rectangular area operations
32 = Text macros
42 = ISO Latin-2 character set
Most of these features are handled entirely within `AdaptDispatch`, so
they apply to all clients. However, 132 column mode is only supported by
ConHost, so we don't report that for conpty clients.
And note that soft fonts won't necessarily work in all conpty clients,
but we don't have an easy way of determining …

Provide a more detailed Device Attributes report

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

Adding a 'Close Pane' menu item in the context menu.
#13580 
If a user decides to split a tab to create multiple panes through the context menu, they should be able to then close the pane via the context menu too. This PR introduces a new context menu item, 'Close Pane', that only appears when a user has 2 or more panes in a tab. When a user clicks close pane, the _active_pane will be closed.
As it's my first PR, I still need to understand how to go through the testing suite.

Added Close Pane to Context Menu

---

src/cascadia/TerminalApp/Jumplist.cpp
src/cascadia/TerminalSettingsModel/IconPathConverter.cpp
src/inc/til/string.h

Adds support to jump list generation for icon paths that include an indirect reference e.g. `c:\windows\system32\shell32.dll,214`
If given a path that has an indirect icon reference parse the path into component parts `filePath` and `iconIndex` and use `IShellLinkW::SetIconLocation` to set the Icon for the entry. Otherwise do what we always do.
This PR also introduces `til::to_int`, which is based on `til::to_ulong` and supports signed integers.
Icons were visible in the jump list and in terminal next to the profiles.
Closes #15205

Add jump list support for indirect icon references

---

src/renderer/atlas/AtlasEngine.r.cpp

This PR gives the atlas engine an attempt to retry a couple operations where it asks for debug flags when we're in debug mode. If you don't have the Graphics debugger and GPU profiler for DirectX installed, then these calls will fail, and we end up blowing up the renderer. Instead, just try again. 
Originally, I actually thought I had hit #14082, but after sorting this out, it was just #14316.
closes #14316

Don't just die if the user doesn't have the dx debugging tools

---

src/cascadia/TerminalApp/TabBase.cpp
src/cascadia/TerminalApp/TabBase.h
src/cascadia/TerminalApp/TerminalTab.cpp

A resurrection of the original nested "Close" menu from #7728. We discovered that nested flyouts crash in #8238. Those are fixed now though! So we can bring this back. 
This also includes the "Close Pane" item from #15198.

Move the Close... actions to a nested menu on the tab

---

src/cascadia/WindowsTerminal/AppHost.cpp

If you were really fast, and closed one window, and then tried to drag the only tab out of the last remaining window, the Terminal could explode. It'd attempt to restore the previous window state, and explode.
Easy way to stop this (also, be more robust): just don't attempt to restore windows during tear-out. That's obvious.
This is a part of #14957

Don't explode when we tear out the last tab of the window

---

src/host/outputStream.cpp
src/host/ut_host/ScreenBufferTests.cpp

When the screen is resized in ConHost via a VT escape sequence, the
active text attributes could end up being corrupted if they were set to
something that the legacy console APIs didn't support (e.g. RGB colors).
This PR fixes that issue.
The way a resize is implemented is by retrieving the buffer information
with `GetConsoleScreenBufferInfoEx`, updating the size fields, and then
writing the data back out again with `SetConsoleScreenBufferInfoEx`.
However, this also results in the active attributes being updated via
the `wAttributes` field, and that's only capable of representing legacy
console attributes.
We address this by saving the full `TextAttribute` value before it gets
corrupted in the `SetConsoleScreenBufferInfoEx` call, and then restore
it again afterwards.
I've added a unit …

Preserve active attributes during VT resize operations

---

src/cascadia/TerminalApp/ColorPickupFlyout.xaml
src/cascadia/TerminalApp/Resources/en-US/Resources.resw

Make the reset button accessible by adding description in reset.
Closes #12044

Make reset button accessible
