src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h

Apparently, `ShowWindow` also sends a `WM_MOVE`, which we then turn around and use to dismiss open dialogs. 
Closes #15170
Regressed in #13811

Don't auto-dismiss the warning dialog on launch

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h
src/cascadia/TerminalSettingsModel/Theme.idl

This MR introduces `activeOnly ` for the `showCloseButton` theme option causing the close button only to appear on the active tab.
This is more or less following the approach explained here https://github.com/orgs/microsoft/projects/686/views/2?pane=issue&itemId=19775774 which indeed just works 😄 .
You notice when switching theme the close buttons is back on all tabs again as well.
Closes #13672
I didn't check specific unit tests for this. I hope by making this MR the pipeline will show if I broke something. Or just let me know if you want me to add something specific for this.

Add support to show close button for active tab only.

---

src/features.xml
src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.r.cpp
src/renderer/atlas/common.h

This commit makes a few changes to avoid bugs, but they basically boil
down to: When we scroll by an entire viewport worth of content, we must
ensure that the scroll offset is 0, because otherwise the scroll rect
(that's basically the viewport, but excluding the scroll offset) will
end up being empty, which the `Present1` API chokes on. This commit
avoids this situation by shuffling around some code to first calculate
the dirty rows, _then_ check if it affects all of them and in that case
sets the scroll offset to 0, and only then finally actually does any
scrolling if there's still something to scroll.
* Start pwsh
* Zoom in twice with Ctrl+Scrollwheel
* Print a few viewports worth of text
* Press Ctrl+L
* No errors ✅

Fix Present1 params when scrolling the entire viewport

---

.github/actions/spelling/allow/names.txt
.github/actions/spelling/excludes.txt
.github/actions/spelling/expect/expect.txt
NOTICE.md
doc/color_nudging.html
src/buffer/out/TextColor.cpp
src/buffer/out/TextColor.h
src/cascadia/TerminalCore/Terminal.cpp
src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/BackendD3D.h
src/renderer/base/RenderSettings.cpp
src/renderer/inc/RenderSettings.hpp
src/terminal/adapter/adaptDispatch.cpp
src/types/ColorFix.cpp
src/types/inc/ColorFix.hpp

Oklab by Björn Ottosson is a color space that has less irregularities
than the CIELAB color space used for ΔE2000. The distance metric for
Oklab (ΔEOK) is defined by CSS4 as the simple euclidian distance.
This allows us to drastically simplify the code needed to determine
a color that has enough contrast. The new implementation still lacks
proper gamut mapping, but that's another and less important issue.
I also made it so that text with the dim attribute gets adjusted just
like regular text, since this is an accessibility feature after all.
The new code is so much faster than the old code (12-125x) that I
dropped any caching code we had. While this increases the CPU overhead
when printing lots of indexed colors, the code is way less complex now.
"Increases" in this case however means …

Use Oklab for text and cursor contrast adjustments

---

src/host/VtIo.cpp
src/host/VtIo.hpp

We need to act like a ConPTY just a little earlier in startup. My relevant notes start here: https://github.com/microsoft/terminal/issues/15245#issuecomment-1536150388. 
Basically, we'd create the first screen buffer with 9001 rows, because it would be created _before_ VtIo would be in a state to say "yes, we're a conpty". Then, if a CLI app emits an entire screenful of text _before_ the terminal has a chance to resize the conpty, then the conpty will explode during `_DoLineFeed`. That method is absolutely not expecting the buffer to get resized (and the old text buffer deallocated). 
Instead, this will treat the console as in ConPty mode as soon as `VtIo::Initialize` is called (this is during `ConsoleCreateIoThread`, which is right at the end of `ConsoleEstablishHandoff`, which is before …

Make conhost act in VtIo mode earlier in startup

---

dep/nuget/packages.config
src/cascadia/TerminalApp/MinMaxCloseControl.xaml
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TabRowControl.xaml
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/common.nugetversions.props
src/common.nugetversions.targets

Reverts #15164, because that's fixed upstream now.
Closes #15139. 
Reverts #15178, but also closes #15121, because that's fixed upstream.
see also:
* https://github.com/microsoft/microsoft-ui-xaml/pull/8430
* https://github.com/microsoft/microsoft-ui-xaml/pull/8420

Update MUX to 2.8.4

---

src/cascadia/TerminalApp/TerminalWindow.cpp

As discussed in https://github.com/microsoft/terminal/issues/14051#issuecomment-1517973776
regressed in #15189

Fix an infinite loop when pressing `alt`

---

src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl
src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
src/cascadia/TerminalSettingsModel/AllShortcutActions.h
src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/defaults.json

Adds 
```
{ "command": "showContextMenu", "keys": "menu" },
```
as a default action. This will manually invoke the control context menu (from #14775), even with the setting disabled.
As discussed with Dustin.

Add an action for manually invoking the control context menu

---

src/cascadia/Remoting/Monarch.cpp

As on the tin.
Blocking for 1.18.
Tracked in #14957

Don't let a window be created with the literal name "new"

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

After retrieving the items via `GetStorageItemsAsync()` inside a try
clause it fails to check if the pointer is actually non-null.
Apart from this this commit fixes the unsafe use of `this` by properly
using `get_weak()`. Finally it allows >1 paths to be dropped.
* Dropping >1 file works ✅
* Dropping >1 directory works ✅

Fix theoretical new-tab file drop crash

---

src/cascadia/Remoting/Peasant.idl
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.idl
src/cascadia/TerminalApp/TerminalWindow.cpp
src/cascadia/TerminalApp/TerminalWindow.h
src/cascadia/TerminalApp/TerminalWindow.idl
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/WindowEmperor.cpp
src/types/inc/utils.hpp
src/types/ut_types/UtilsTests.cpp
src/types/utils.cpp
tools/bcz.cmd

Before process model v3, each Terminal window was running in its own process, each with its own CWD. This allowed `startingDirectory: .` to work relative to the terminal's own CWD. However, now all windows share the same process, so there can only be one CWD. That's not great - folks who right-click "open in terminal", then "Use parent process directory" are only ever going to be able to use the CWD of the _first_ terminal opened. 
This PR remedies this issue, with a theory we had for another issue. Essentially, we'll give each Terminal window a "virtual" CWD. The Terminal isn't actually in that CWD, the terminal is in `system32`. This also will prevent the Terminal from locking the directory it was originally opened in. 
* Closes #5506
* There wasn't a 1.18 issue for "Use parent process …

Use a "virtual CWD" for each terminal window

---

src/cascadia/TerminalApp/App.xaml
src/cascadia/TerminalApp/MinMaxCloseControl.xaml

Honestly, I don't really know where it regressed. There isn't time for me to go digging.
See also
* #15313
* #15164
Closes #15326

Restore the tab padding

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/UnitTests_Control/pch.h

`ControlCore` contained two bugs:
* Race condition on access of the 3 throttled funcs which may now
be `reset()` during tear out
* The `ScrollPositionChanged` event emitter was written incorrectly
and would emit the event from the background thread without
throttling during tear out

Fix race conditions in ControlCore

---

src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/Pane.h

We don't need to recreate the `MediaPlayer` to avoid the influence of
media keys if we simply opt out of media key controls.
* Set a random .wav as the bell sound
* Bell is audible ✅
* Media keys have no effect while the sound plays ✅

Avoid recreating the bell MediaPlayer every time

---

src/cascadia/WindowsTerminal/WindowEmperor.cpp
src/cascadia/WindowsTerminal/WindowEmperor.h
src/cascadia/WindowsTerminal/WindowThread.cpp
src/cascadia/WindowsTerminal/WindowThread.h

`WindowEmperor` would exit as soon as the last window would enter
`RundownForExit()`, which is too early and triggers leak checks.
This commit splits up the shutdown up into deregistering the window from
the list of windows and into actually decrementing the window count.
Closes #15306
* D2D leak warnings seem to disappear ✅

Fix WindowEmperor exiting too early

---

src/cascadia/Remoting/WindowManager.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalSettingsModel/PowershellCoreProfileGenerator.cpp
src/types/utils.cpp
src/winconpty/winconpty.cpp

`native()` returns a `const std::wstring&`, whereas `wstring()`
returns a copy. Use the former to make path conversions cheaper.

Make path-string conversions cheaper

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

Transient UIs are hard.
Regressed in #15077.
Closes #15305

Don't dismiss the command palette when the new tab menu closes

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/WindowsTerminal/AppHost.cpp

Don't even try to MoveContent to the same window you started in

---

src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/host/outputStream.cpp
src/host/outputStream.hpp
src/host/ut_host/ScreenBufferTests.cpp
src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/ITerminalApi.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/ut_adapter/adapterTest.cpp
src/terminal/input/terminalInput.cpp
src/terminal/input/terminalInput.hpp

This PR adds support for the ANSI Line Feed/New Line mode (`LNM`), which
determines whether outputting a linefeed control should also trigger a
carriage return, and whether the `Return` key should generate an `LF` in
addition to `CR`.
In ConHost, there was already a console mode which handled the output
side of things, but I've now also added a `TerminalInput` mode that
controls the behavior of the `Return` key. When `LNM` is set, both the
output and input modes are enabled, and when reset, they're disabled.
If they're not already matching, then `LNM` has no effect, and will be
reported as unknown when queried. This is the typical state for legacy
console applications, which expect a linefeed to trigger a carriage
return, but wouldn't want the `Return` key generating both `CR`+`LF`.
As …

Add support for LNM (Line Feed/New Line Mode)

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h
src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/IslandWindow.h
src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
src/cascadia/WindowsTerminal/NonClientIslandWindow.h
src/cascadia/WindowsTerminal/WindowThread.cpp

XAML/WinUI may pump the event loop internally. One of the functions
that does this right now is `DesktopWindowXamlSource::Close()`.
This is problematic in the previous code, because we'd set `_window`
to `nullptr` before calling `Close()` and so any of the `IslandWindow`
callbacks may be invoked during shutdown, which then try to potentially
access `_window` and end up crashing. This commit fixes the issue by
simply not nulling out the `_window` and calling `Close()` directly.
Furthermore, `NonClientIslandWindow` may directly access WinUI
objects in its message handlers which also crashes.
I've had this happen roughly ~1% of my test exits in a debug build
and every single time on a (artificial) very slow CPU.
* Closing a window destroys the rendering instance ✅

Fix DesktopWindowXamlSource related crashes when closing a window

---

src/inc/til/flat_set.h
src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/Backend.cpp
src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/common.h

This commit fixes 3 bugs that I found while working on another feature:
* `GetGlyphIndices` doesn't return an error when the codepoint couldn't
be found, it simply returns a glyph index of 0.
* `_resetGlyphAtlas` failed to reset the `linear_flat_set` "load" to 0
which would result in an unbounded memory growth over time.
* `linear_flat_set` was missing move constructors/operators, which
would've led to crashes, etc., but thankfully we haven't made use
of these operators yet. But better fix it now than never.

AtlasEngine: Fix multiple minor issues

---

src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/DWriteTextAnalysis.cpp
src/renderer/atlas/DWriteTextAnalysis.h

This commit ensures that we pass the user's locale to `MapCharacters`.
See: https://heistak.github.io/your-code-displays-japanese-wrong/
After modifying the `userLocaleName` to contain `ja-JP`, `zh-CN` and
`zh-TW`, printing "刃直海角骨入" produces the expected, localized result.

AtlasEngine: Fix han unification issues

---

src/renderer/atlas/AtlasEngine.r.cpp

We need to avoid calling `Present1()` with an empty dirty rect, but the
backends are what determines the resulting dirty rect, so we need to
first run the backend code and then decide if we `Present1()` or not.
* `Animate_scan.hlsl` shows a smoothly animated line ✅

AtlasEngine: Fix animated shaders

---

src/inc/til/flat_set.h
src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/BackendD3D.h

Overhangs for box glyphs can produce unsightly effects, where the
antialiased edges of horizontal and vertical lines overlap between
neighboring glyphs and produce "boldened" intersections.
This avoids the issue in most cases by simply clipping the glyph to the
size of a single cell. The downside is that it fails to work well for
custom line heights, etc.
* With Cascadia Code, printing ``"`u{2593}`n`u{2593}"`` in pwsh
doesn't produce a brightened overlap anymore ✅
* ``"`e#3`u{2502}`n`e#4`u{2502}"`` produces a fat vertical line ✅

AtlasEngine: Clip box glyphs to their cells

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Some of these were reundant, and some didn't feel right when I read them.
Oh, and I got rid of all of these particularly unhelpful or non-additive resources:
```
Color Scheme        [                     v ]
Is a color scheme
```
The only one I am truly _iffy_ about is the one that newly says `OSC 2`.

Reword or remove a bunch of subheadings in the SUI

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl
src/cascadia/TerminalSettingsEditor/PreviewConnection.cpp
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.cpp
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.xaml

Our existing preview text was not very helpful in learning how different settings impacted the display of text in Terminal.
This new preview text contains:
* Bold text, which is controlled by intenseTextStyle
* Colors
* Emoji
* A cursor, which overlaps a single character to show inversion behavior

Add a fun new preview text in the SUI, enable the cursor

---

src/cascadia/TerminalApp/AboutDialog.cpp
src/cascadia/TerminalApp/AboutDialog.h
src/cascadia/TerminalApp/AboutDialog.idl
src/cascadia/TerminalApp/AboutDialog.xaml

It turns out that the store API *doesn't* tell us what the new version is. We were loading up our own package and checking its version instead.
The best we can do is tell users that an update--any update--is available.

Remove the pending update version from the About dialog

---

src/cascadia/WindowsTerminal/AppHost.cpp

As discussed. Closes #15364.
Prevents one crash on Windows 10. Opens the door to may more horrors.
Co-authored by: @j4james

Manually close the ContentDialog in teardown

---

src/cascadia/WindowsTerminal/IslandWindow.cpp

Re: #15384
Basically, when we close a `DesktopWindowXamlSource`, it calls to `Windows_UI_Xaml!DirectUI::MetadataAPI::Reset`, which resets the XAML metadata provider _for the process_. So, closing one DWXS on one thread will force an A/V next time another thread tries to do something like... display a tooltip. Not immediately, but surely soon enough.
This was fixed in Windows 11 by os.2020!5837001. That wasn't backported to Windows 10.
This will cause a ~15MB memory leak PER WINDOW. OBVIOUSLY, this is bad, but it's less bad than crashing. 
We're gonna keep using #15384 for other ideas here too.

Leak the window when it closes on Windows 10

---

src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.r.cpp
src/renderer/atlas/BackendD2D.cpp
src/renderer/atlas/BackendD2D.h
src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/BackendD3D.h
src/renderer/atlas/common.h

`til::rect`'s truthiness check (= rect is valid) returns `false` for
any rects that have negative coordinates. This makes sense for buffer
handling, but breaks AtlasEngine, where glyph coordinates can go out
of bounds and it's entirely valid for that to happen.
Closes #15416
* Use MesloLGM NF and print NF glyphs in the first row
* Text rendering, selection, etc., still works ✅

AtlasEngine: Fix Present() of out of bounds glyphs

---

src/renderer/atlas/BackendD3D.cpp

Woops. Regressed in #15343. Fixes #15409.
* Run `RenderingTests.exe`
* Soft fonts work ✅

AtlasEngine: Fix nullptr crash when using soft fonts

---

src/cascadia/TerminalSettingsModel/VsDevCmdGenerator.cpp

This regressed in f06cd17. It seems like the change went untested,
because it appends an extra " after -startdir=none.
This changeset also avoids calling `append()` twice.
Closes #15436
* VS Developer Command Prompt works ✅

Fix VS profile command generation

---

src/renderer/atlas/BackendD2D.cpp

TIL: `CreateCompatibleRenderTarget` does not initialize the bitmap
it returns. You got to do that yourself just like in D3D.
* Set `ATLAS_DEBUG_FORCE_D2D_MODE` to 1
* Changing the cursor in the settings immediately updates it ✅

AtlasEngine: Fix cursor invalidation for BackendD2D

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

Add the "Move Tab to New Window" item to the context menu of the tabs 
https://github.com/microsoft/terminal/issues/15127
Add the "Move Tab to New Window" item to the context menu of the tabs. 
Checked Code Style
https://github.com/microsoft/terminal/blob/main/doc/STYLE.md
- [ V] Closes #15127
-  [?] Tests added/passed
- [ X] Documentation updated
- [ V] Schema updated (if necessary)

Add support for a "Move Tab to New Window" tab context menu item

---

src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

Because this looks like it's entirely broken in `main`, and possibly in 1.17(?)
We didn't take a strong ref to the coroutine parameter. As to be expected, that explodes. 
Closes #15412

Fix `focusFollowMouse`

---

src/cascadia/WindowsTerminal/WindowEmperor.cpp

This is a resurrection of #5629. As it so happens, this crash-on-exit was _not_ specific to my laptop. It's a bug in the XAML platform somewhere, only on Windows 10. 
In #14843, we moved this leak into `becomeMonarch`. Turns out, we don't just need this leak for the monarch process, but for all of them. 
It's not a real "leak", because ultimately, our `App` lives for the entire lifetime of our process, and then gets cleaned up when we do. But `dtor`ing the `App` - that's apparently a no-no.
Was originally in #15424, but I'm pulling it out for a super-hotfix release. 
Closes #15410
MSFT:35761869 looks like it was closed as no repro many moons ago. This should close out our hits there (firmly **40% of the crashes we've gotten on 1.18**)

AGAIN, intentionally leak our App, so that we DON'T crash on exit

---

src/inc/til/env.h

Make sure we always expand path env vars, even if they're REG_SZ in the registry.
On some systems path vars are REG_SZ instead of REG_EXPAND_SZ. We need to make sure we always expand them. We looked at the system code, and it also makes to sure to always expand them.
Built locally and made sure the problem went away. Also stepped through in the debugger to make sure things were working correctly.
Closes #15442

env: always expand PATH vars

---

src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/atlas/AtlasEngine.r.cpp

`_p.MarkAllAsDirty()` sets `_p.scrollOffset` to 0, so we need to use
that instead of `_api.scrollOffset` when getting the offset.
Additionally, the previous code failed to release the swap chain
when recreating the backend, which is technically not correct.
I'm not sure to what issues this might have led, as it didn't had any
negative effects on my PC, but it's definitely not according to spec.
Difficult to test but it seems alright.

AtlasEngine: Improve scroll and swap chain invalidation

---

src/cascadia/WindowsTerminal/IslandWindow.cpp

RE: 
* #15454
* MSFT:44725712 "WindowsTerminal.exe!NonClientIslandWindow::OnSize"
* MSFT:44754014 "NonClientIslandWindow::GetTotalNonClientExclusiveSize"
I think this should fix all of those, but I want to ship and verify live, since I can't repro this locally.

Theoretical fix for some crashes

---

src/interactivity/win32/Clipboard.cpp

This regressed in a1f42e8 which only made changes to Windows Terminal
but forgot to make equivalent ones in OpenConsole/conhost.
Without this fix, line breaks in block selections are missing if the
line doesn't force a wrap via an explicit newline.
Closes #15153
* Run Far or print long lines of text
* Trigger block selection via Ctrl+M or Edit > Mark
* Clipboard contains N-1 newlines lines for N selected rows ✅

Hotfix block selection linebreaks in conhost

---

src/cascadia/WindowsTerminal/WindowEmperor.cpp

Yep it's that dumb
Closes #15443

Exit the process after commandline-only invocations

---

src/cascadia/TerminalSettingsModel/KeyChordSerialization.cpp
src/inc/til/static_map.h
src/types/colorTable.cpp

I wanted to show `til::static_map` to someone and noticed it hasn't been
updated since we updated to C++20. We can now make use of `constexpr`
`std::sort` and `constinit` to skip the initialization of the maps in
`KeyChordSerialization.cpp`. Also, I removed the comparator argument
to make the map a little more compact.

Modernize til::static_map with C++20

---

src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp
src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.h
src/cascadia/TerminalSettingsEditor/ColorSchemes.h
src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml

This removes the "default" text box from the UI Automation tree, thus preventing screen readers from navigating to it. This was a confusing scenario for users because the "default" tag was unclear if it was a part of the previous or next color scheme (i.e. consider hearing "Campbell, default, Campbell PowerShell"; it's unclear which one is default).
This also appends the "default" string to the `ToString` function of the color scheme view model. This makes it so that the combo box and list view visually appear the same, but can be quick searched or read out by the screen reader with the 'default' tag.
- Scenarios tested:
Closes #14401

Expose 'Default' tag to Screen Readers in Color Schemes page

---

src/renderer/atlas/BackendD2D.cpp
src/renderer/atlas/BackendD3D.cpp

This fixes a couple spots where I wasn't properly checking
for the existence of some optional D2D interfaces.
I haven't tested this and don't intend to do it just yet.
Windows Terminal requires build 19041 at least anyways.

AtlasEngine: Fix some Windows 10 <14393 bugs

---

build/rules/GenerateSxsManifestsFromWinmds.targets
src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
src/cascadia/WindowsTerminal_UIATests/WindowsTerminal.UIA.Tests.csproj
src/common.nugetversions.targets

Fixing a problem where the repo build failed when the project location path contained space character.
Closes #15370 
Placing missing quote, amp and apos symbols when calling commands with filepath parameters.
Built locally.

Project build with space in filepath fix

---

.github/actions/spelling/allow/apis.txt
.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalControl/Resources/en-US/Resources.resw
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

06174a9 didn't properly fix the issue of us showing homoglyphs in our
URI tooltip. This commit introduces a different approach where we
display both, the Punycode and Unicode encoding, whenever we encounter
an IDN. This isn't perfect but simple to implement.
Closes #15432
* `https://www.xn--fcbook-3nf5b.com/` (which contains confusing glyphs)
is shown both in its Punycode and Unicode form simultaneously. ✅

Display Unicode URIs side-by-side with their Punycode encoding

---

src/inc/til/small_vector.h
src/til/ut_til/SmallVectorTests.cpp

This commit achieves fixes the issue as described in the title by
checking whether the `this` and `other` pointer are identical.
As an added bonus it makes the copy and move constructors slightly
cheaper, as they don't try to destruct existing data anymore,
which doesn't exist anyways.
* It blends ✅

Fix small_vector issues when assigning it to itself

---

.github/actions/spelling/allow/allow.txt
src/cascadia/TerminalSettingsEditor/Appearances.cpp
src/cascadia/TerminalSettingsEditor/Appearances.h
src/cascadia/TerminalSettingsEditor/Appearances.idl
src/cascadia/TerminalSettingsEditor/PreviewConnection.cpp
src/cascadia/TerminalSettingsEditor/PreviewConnection.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.cpp
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.h

When we detect a font that has a glyph for `U+E0B6`, we will switch the preview connection text to contain a special powerline prompt. This will allow people to see how different settings might impact their real-world environment.
When we _don't_ detect such support, we fall back to the CMD-style `C:\>` prompt.
Pros:
- It's beautiful.
Cons:
- More code
Risks:
- `U+E0B6` is part of the private use area, and fonts that have symbols there (such as Cirth as sub-allocated by the ConScript Unicode Registry) will result in something unexpected.
- Actually, `E0B6` isn't part of base powerline... but I think this specific set of characters looks too good to pass up.

Detect likely Powerline fonts, add a special powerline preview

---

.github/actions/spelling/allow/allow.txt
.github/actions/spelling/expect/expect.txt
build/scripts/Run-Tests.ps1

Improvements and explanations:
* Added proper indentation and spacing for better readability.
* Added comments to explain the purpose of different sections of the
code.
* Utilized the $LASTEXITCODE variable instead of $lastexitcode to ensure
consistency.
* Changed the variable name from $testdlls to $testDlls for better
naming convention.
* Moved the Exit 0 statement to the end (outside the if condition).
* Since Exit statements terminate the script immediately, it's better to
have them at the end of the script to ensure that all necessary
cleanup or additional operations are performed before exiting.
* These improvements enhance the code's readability, maintainability,
and adherence to best practices.

Improve Run-Tests.ps1's maintainability and readability

---

tools/ConsoleTypes.natvis

Fixes the broken types for `TextAttribute`, `til::size`, `til::point`
and `til::rect` and adds a new type for `TextBuffer` which without
this would now be much harder to inspect due to introduction of
the manual virtual memory management in 612b00c.

Various fixes and improvements for ConsoleTypes.natvis

---

src/buffer/out/Row.cpp
src/buffer/out/Row.hpp
src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/host/outputStream.cpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp

This commit makes 2 changes:
* Expose dirty-range information from `ROW::CopyTextFrom`
This will allow us to call `TriggerRedraw`, which is an aspect
I haven't previously considered as something this API needs.
* Add a `FillRect` API to `TextBuffer` and refactor `AdeptDispatch`
to use that API. Even if we determine that the new text APIs are
unfit (for instance too difficult to use), this will make it simpler
to write efficient implementations right inside `TextBuffer`.
Since the new `FillRect` API lacks bounds checks the way `WriteLine`
has them, it breaks `AdaptDispatch::_EraseAll` which failed to adjust
the bottom parameter after scrolling the contents. This would result
in more rows being erased than intended.
* `chcp 65001`
* Launch `pwsh`
* ``"`e[29483`$x"`` fills the viewport with …

Move AdaptDispatch::_FillRect into TextBuffer

---

.github/actions/spelling/candidate.patterns
src/common.build.pre.props
src/host/readData.hpp
src/host/renderData.hpp
src/host/server.h
src/renderer/dx/CustomTextLayout.cpp
src/renderer/dx/DxSoftFont.cpp
src/renderer/dx/DxSoftFont.h
src/renderer/inc/RenderEngineBase.hpp
src/renderer/vt/vtrenderer.hpp
src/server/IWaitRoutine.h
src/types/ScreenInfoUiaProviderBase.h
src/types/UiaTextRangeBase.hpp
src/winconpty/winconpty.cpp

* Fixes warnings related to missing `const` in 2 places, which seems
to be something that's being detected more reliably by 17.6 now.
* Fixes `DxSoftFont` not initializing all members,
which is also suddenly being detected by 17.6 now.
* Fixes 1 new VS 17.7 warning (C26435) by removing `virtual` from
methods declared as `override` already.
* Disables 2 new VS 17.7 warnings that are part of C++ Core Guidelines
c.128, because they don't really bring any benefit to this project.
As an additional bonus it disables a spellcheck warning that has been
going around ever since I put a Punycode URL in a comment.

Fix new AuditMode failures up to VS 17.7 Preview 2

---

src/cascadia/TerminalApp/TerminalPage.cpp

When `elevate` is set to `true`, `_maybeElevate` would try to
modify `newTerminalArgs` and crash, because during tab duplication
there aren't any `newTerminalArgs`. This issue may happen for instance
when receiving hand-off from a non-elevated client and then trying
to duplicate that tab.
Closes #15534
* Launch with `"elevate": false`
* Set `"elevate": true`
* Duplicate a tab

Fix a crash when duplicating tabs with elevate:true

---

.github/actions/spelling/allow/apis.txt
.github/actions/spelling/expect/expect.txt
.github/actions/spelling/patterns/patterns.txt
src/buffer/out/Row.cpp
src/buffer/out/Row.hpp
src/inc/til.h

Performance of printing enwik8.txt at the following block sizes:
4KiB (printf): 51MB/s -> 54MB/s
128KiB (cat): 92MB/s -> 103MB/s
* Rows are properly filled with whitespace at various
window sizes as observed under a debugger ✅

Vectorize ROW initialization

---

.vscode/settings.json

Don't exclude nuget `packages/` in vscode. Excluding via `file.exclude` also excludes them from c++ language extension's `includePath` and generates missing include files and header errors.
We might still like to exclude them from full text search, so we do it using `search.exclude`.
Closes #15578

unhide nuget `packages/` for VSCode

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/EventArgs.h
src/cascadia/TerminalControl/EventArgs.idl
src/cascadia/TerminalControl/ICoreState.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.h
src/cascadia/TerminalSettingsModel/ActionArgs.idl
src/cascadia/TerminalSettingsModel/AllShortcutActions.h
src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/defaults.json

Added `searchWeb` command to search the selected text on the web.
Arguments:
- `queryUrl`: URL of the web page to launch (the selected text will be appended to it)
- `wrapWithQuotes`: whether the selected text should be wrapped with quotes (true/false)
To make the search text more "compact" and handle multi-line selections, I'm concatenating the selected lines and replacing consecutive whitespaces with a single space (we may change this with something more clever in case).
Manual testing with single, multi-line, block selections.
Enable/disable the `wrapWithQuotes` argument.
Closes #10175

Search web for selected text

---

src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp

As a shortcut, GetLastNonSpaceCharacter can start with the last committed row. It's guaranteed that there isn't anything of worth below that point, so why bother checking?
Without this, Terminal immediately commits the entire 9031-line buffer on startup while trying to--get this!--clear the screen!

Stop committing the whole buffer when determining if it's empty

---

build/pipelines/release.yml

I originally intended to add the Drop Validator (which is a compliance requirement) task to the build, but I quickly realized that we weren't generating a complete SBOM manifest covering every artifact that we produced.
We were generating the SBOM manifest, and then re-packing the Terminal app which very likely invalidated all of the hashes and signatures in the SBOM manifest!
We were also missing the unpackaged build.
I've removed the `appx-PLATFORM-CONFIG` and `unpackaged-PLAT-CONF` artifacts and combined them into a single one, `terminal-PLAT-CONF`.

Add the drop validator task, rework some build artifacts

---

.github/actions/spelling/expect/expect.txt
src/buffer/out/Row.cpp
src/buffer/out/Row.hpp

By rewriting the first major copy loop in `CopyRangeFrom` to use
pointers/iterators instead of indices for iteration, the autovectorizer
kicks in end neatly rewrites it as an unrolled SIMD loop. This improves
performance during traditional window resizes by roughly 2x and will
be quite helpful in the future for our more complex reflow resize.
Unfortunately, MSVC unrolls the loop by 4x which is too much for our
purpose, but there's no option to change that. It's still better than
not having any vectorization however, since it kicks in at 32 columns.
It also renames the function to `CopyTextFrom` be more in line with
the others and to avoid confusion, because it doesn't copy attributes.
* Traditional resizing works ✅

Allow ROW::CopyRangeFrom to be vectorized

---

src/buffer/out/Row.cpp
src/buffer/out/Row.hpp
src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/host/_stream.cpp
src/host/_stream.h
src/host/cmdline.cpp
src/host/output.cpp
src/host/output.h
src/host/readDataCooked.cpp

I've removed these because it made some of my new code pretty
convoluted for now good reason as most of these functions aren't
exception safe to begin with. Basically, their boolean status
is often just a pretense because they can crash or throw anyways.
Furthermore, `WriteCharsLegacy` failed to check the status code
returned by `AdjustCursorPosition` in some of its parts too.
In the future we should instead probably strive to continue
make our legacy code more exception safe.

Remove boolean success return values from TextBuffer

---

src/host/ApiRoutines.h
src/host/VtApiRoutines.cpp
src/host/VtApiRoutines.h
src/host/directio.cpp
src/host/readDataDirect.cpp
src/host/readDataDirect.hpp
src/server/ApiDispatchers.cpp
src/server/IApiRoutines.h

`(Peek|Read)ConsoleInput(A|W)Impl` make a distinction that doesn't make
a lot of sense in our code base: On the calling side (`ApiDispatchers`)
there's just one function calling all 4 (`ServerGetConsoleInput`) and
on the callee side they all 4 just call `_DoGetConsoleInput` anyways.
* It compiles ✅

Deduplicate INPUT_RECORD based ApiRoutines

---

src/host/input.cpp
src/host/inputBuffer.cpp
src/host/inputBuffer.hpp
src/interactivity/win32/windowio.cpp
src/terminal/adapter/InteractDispatch.cpp
src/terminal/adapter/ut_adapter/inputTest.cpp
src/terminal/input/terminalInput.cpp
src/types/inc/IInputEvent.hpp

This is an improved fix for #13238. Instead of handling focus events in
the `TerminalInput::HandleKey` function and the need to filter them
out depending on where they came from, we simply don't call `HandleKey`
in the first place. This makes the somewhat unreliable `CameFromApi`
function unnecessary and the code a bit more robust.
This change is required because `CameFromApi` is not representable
in a `INPUT_RECORD` and I'm getting rid of `IInputEvent`.
* No `[O` when exiting nvim ✅
* Mouse input in nvim works ✅

Properly filter focus events from the console API

---

.github/actions/spelling/allow/apis.txt
src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.cpp
src/cascadia/PublicTerminalCore/HwndTerminalAutomationPeer.hpp
src/cascadia/PublicTerminalCore/PublicTerminalCore.vcxproj

UiaRaiseNotificationEvent is not present on Windows Server 2016, even though it is documented as being present.
This also removes the cost of loading up UIAutomationCore from the critical path.

wpf: delay-load UIAutomationCore because it's incomplete in RS1

---

src/renderer/base/thread.cpp

This commit reduces GdiEngine's average display latency by 8ms,
which caused it to miss a v-blank about half the time at 60Hz.
Closes #15607
Input latency with `frarees/typometer` matches conhost from Win10 ✅

Reduce GdiEngine input latency

---

src/cascadia/TerminalApp/App.base.h
src/cascadia/TerminalApp/App.cpp
src/cascadia/TerminalApp/App.h
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/TerminalPage.cpp

Due to an implementation detail in the Xaml compiler--which wants to ensure that all metadata providers on an App are available immediately--we were eagerly loading the settings UI DLL and all of its dependencies, even in sessions where the user was not going to open Settings.
By turning off eager provider generation and handling it ourselves, we get to control exactly when the settings UI is loaded.
This required some gentle poking-through of the barrier between App and Page, but it is almost certainly worth it.
Turning on the Xaml code generation flag to not generate providers automatically adds an `AddProvider` member to the internal interface for the autogenerated XamlMetadataProvider. We needed to switch to using the internal interface rather than the projected type in our custom App …

Lazily load the settings UI DLL

---

src/common.build.pre.props
src/terminal/parser/ft_fuzzer/fuzzing_directed.h

This commit removes some flags that we don't need anymore, and adds all
those `/Zc` (standard conformance) switches that aren't enabled by
default yet. This will help us and the MSVC team detect bugs early.
This removes:
* `/fp:contract`: With the addition of `TIL_FAST_MATH_BEGIN`
all the code that benefits from FMA now uses `/fp:fast`.
* `/Zc:lambda`: Automatically enabled with C++20.
This adds:
* `/Zc:__cplusplus` / `/Zc:__STDC__`: Without these `__cplusplus`
defaults to `199711L` and `__STDC__` remains undefined.
* `/Zc:enumTypes`: The C++ standard specifies that an enum with
unspecifies size has a size that fits its members exactly.
An enum with byte-sized members has a `sizeof` of 1 and not 4.
* `/Zc:templateScope`: Emit errors when shadowing template parameters.
And most …

Update /Zc build flags to be more standard conforming

---

src/cascadia/WindowsTerminal_UIATests/SmokeTests.cs

When we moved the settings UI to lazy initialization in #15628, we broke PGO. Apparently, we were PGOing the tiny part of Settings that was being loaded on every launch (e.g. the XAML metadata provider 🤦)
Let's actually PGO launching the settings.

Launch the settings in the PGO harness

---

src/inc/til/bitmap.h
src/til/ut_til/BitmapTests.cpp

This fixes a bug reported internally that occurs when resizing the
terminal while also scolling the contents. The easiest way to reproduce
it is to resize the terminal to 0 rows, but it's much more prominent
in a debug build where everything goes out of sync almost immediately.
The underlying issue is that `VtEngine::_wrappedRow` may contain an
offset that is outside of the viewport bounds, because reflowing and
scrolling aren't properly synchronized. The previous `bitmap` code
would then throw an exception for such invalid coordinates and cause
the internal `VtEngine` state to be broken. Once `_wrappedRow` got
to a negative value at least once, it would stay that way unless you're
scrolling up. If the contents are actively scrolling it would quickly
reach a negative value from which it …

Fix VtEngine hang when resizing while scrolling

---

src/terminal/parser/stateMachine.cpp
src/terminal/parser/stateMachine.hpp

The added explicit vectorization allows us to skip plain text faster
and pass it immediately to the deeper `TextBuffer` parts.
Performance of printing enwik8.txt at the following block sizes:
4KiB (printf): 54MB/s -> 58MB/s
128KiB (cat): 103MB/s -> 116MB/s
* Works on x64 ✅
* Works on ARM ✅

Vectorize StateMachine::ProcessString

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/common.h

The WPF control has a minor bug where it initializes the renderer
when there isn't even a window yet. When it then calls `SetWindowSize`
it'll pass the result of `GetWindowRect` which is `0,0,0,0`.
This made AtlasEngine unhappy because it restricted the glyph atlas
size to some multiple of the window size. If the window size is `0,0`
then there couldn't be a glyph atlas and so it crashed.
* Fixes WPF test control crash on startup ✅

 AtlasEngine: Harden against empty target sizes

---

src/buffer/out/Row.cpp
src/buffer/out/Row.hpp

Performance of printing enwik8.txt at the following block sizes:
4KiB (printf): 78MB/s -> 93MB/s
128KiB (cat): 117MB/s -> 156MB/s
The change itself is rather self-explanatory.
A tighter, simpler loop runs faster.
Mixed ASCII/Unicode text output looks generally correct. ✅

Add an ASCII fast-pass to ROW

---

dep/nuget/packages.config
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/IslandWindow.h
src/common.nugetversions.targets

The DWMWA for this has been documented for quite a while now!
I've also updated to a version of TerminalThemeHelpers that removes all the Dark Theme exports.

Remove TerminalTrySetDarkTheme, use the DWMWA directly

---

src/host/inputBuffer.cpp
src/host/inputBuffer.hpp
src/host/ut_host/InputBufferTests.cpp

This reverts a number of changes to input handling to how it used to be
in conhost v1. It merges the input event coalescing logic into a single
function and inlines the console suspension event handling, because
soon these functions will receive `std::span` arguments which cannot
be preprocessed anymore, unlike a `std::deque`.
It also adds back support for Ctrl-S being an alias for VK_PAUSE
which was lost in commit fccc7410 in 2018.
Closes #809
* Unit and feature tests are ✅
* Ctrl-S pauses output 🎉

Clean up InputBuffer coalescing and preprocessing

---

src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalControl/TermControl.cpp

Fix C2664 errors under latest compiler.
#15309
- Latest compilers are more strict
- Internal background of change: [DevDiv:1810844](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1810844)
- Now successfully builds under VS `17.8.0 Preview 1.0 `
- Still successfully builds under VS `17.6.5`

Fix C2664 errors

---

src/cascadia/TerminalApp/CommandPalette.xaml

Adds a background to key chord border in the CommandPalette Screen. This prevents certain accent colors from rendering the KeyChords unreadable.
Before (where the text is unreadble);
After (from this PR):
See #15228 for more details

Added background to CommandKeyChord

---

src/host/directio.cpp
src/host/ft_host/CJK_DbcsTests.cpp

This commit inlines `EventsToUnicode` into `WriteConsoleInputAImpl`
because soon we'll not use deques for events anymore and so the old
code won't work. It cleans up the implementation because I intend to
move all this code directly into `InputBuffer` to have a better and
tighter control over how text gets converted. UTF-8 input for instance
requires the storage of up to 3 input events and this code is not fit
to handle that. It's also unmaintainable because our input handling
code shouldn't be spread over a dozen files either. 😄
* Unit and feature tests are ✅

Clean up WriteConsoleInputA conversion

---

src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/adaptDispatchGraphics.cpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp
src/terminal/parser/stateMachine.cpp
src/terminal/parser/stateMachine.hpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp

Adds support for colon `:` separated sub parameters in parser. Technically, after this PR, nothing should change except, now sub parameters are parsed, stored safely and we don't invalidate the whole sequence when a `:` is received within a parameter substring.
In this PR:
- If sub parameters are detected with a parameter, but the usage is unrecognised, we simply *skip* the parameter in `adaptDispatch`. 
- A separate store for sub parameters is used to avoid too many changes to the codebase.
- We currently allow up to `6` sub parameters for each parameter, extra sub parameters are *ignored*.
- Introduced `VTSubParameters` for easy access to underlying sub parameters.
> **Info**: We don't use sub parameters for any feature yet, this is just the core implementation to support newer …

Add support for colon separated sub-parameters

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

Add support for running profiles in the Add Tab drop down as administrator without a keyboard.
#14517 
This pull request adds a FlyoutMenu to each Profile entry in the Add New tab drop down. When a profile is right clicked or held for 2 seconds in the case of no mouse input will present a MenuItem to allow the user to click and run the selected profile as administrator
- Responds to pointer input events (mouse, pointer, touchpad)
- Adjusts to theme changes.
- Only shows when a profile is selected. Will not show on settings or pallete entries

Add support for running profiles from Add tab menu as admin without a keyboard

---

src/cascadia/WindowsTerminal/AppHost.cpp

Replace deprecated winrt::apartment_context pattern
I only found 2 instances of this pattern in use and one of them was
actually already replaced but the `co_await winrt::apartment_context`
code was still there.
Tested both window renaming and opening terminal with persisted layouts.
Both still work.
Closes #12982

Replace deprecated await winrt::apartment_context pattern

---

build/pipelines/release.yml
build/pipelines/templates/build-console-audit-job.yml
build/pipelines/templates/build-console-ci.yml
build/pipelines/templates/build-console-fuzzing.yml
build/pipelines/templates/build-console-pgo.yml
build/pipelines/templates/test-console-ci.yml

Using our own pools like this gives us a lot of freedom in the tooling that's installed, the OS versions it targets, and when we take on Visual Studio updates.
As part of this effort, I've also stood up a "small" agent pool. At the time of this PR, that pool is using D2ads-v5 SKU VMs (2 vcore 8 GiB) versus the "large" agent pool's D8as-v5 (8 vcore 32 GiB). Smaller build tasks have been moved over to the small pool. Compilation's the hard part, so it gets to stay on the large pool.

Switch away from the WinDev agent pools

---

src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml

Adds an `AutomationProperty.Name` to the main grid in the `SettingContainer`. Doing so makes it so that the group of elements is considered a "group \<header\>".
Now, when navigating with a screen reader, when you enter the group of elements, the "group \<header\>" will be presented. Thus, if the user navigates to the "reset" button, it'll be prefaced with a "group \<header\>" announcement first. If the user navigates to it from the other direction (the setting control), this announcement isn't made, but the user already has an understanding of what group of settings they're in, which is standard practice.
Closes #15158

Add UIA element grouping to SettingsContainer

---

build/pipelines/ci.yml
build/pipelines/templates/test-console-ci.yml

This pull request introduces the arm64 testing agents and a few build
phases to use them.
In addition to running the ARM64 tests in CI, it makes the following
changes:
- The x64 tests now run on equivalent x64 testing agents
- We now run ARM64 builds (and tests!) on all pull requests
- I've deduplicated a lot of the build and test stages
- New queue-time parameters have been added to control various phases,
for quick pipeline testing
- A bunch of conditions have been promoted to compile-time checks to
control the existence of stages and steps more tightly

Add support for ARM64 testing, reintroduce it in CI

---

src/cascadia/TerminalSettingsEditor/Appearances.xaml
src/cascadia/TerminalSettingsEditor/Launch.xaml

When the OS' "text size" setting gets set to 200% and the display resolution is reduced quite a bit, we get some cropped text in the SUI's Default Terminal ComboBox. Turns out, we have a height set on the items. I went ahead and removed that so we don't crop the text. Everything looks good still!
A similar issue occurs in the Profile > Appearance > Color Scheme ComboBox. I went ahead and fixed that too by removing the height restriction.
Other minor changes:
- fixed the comments
- changed "author and version" row to "auto" instead of "*" (star sizing is great for proportional sizing, so we're not really taking advantage of it)
Closes #15149

Fix Default Terminal and Color Scheme ComboBoxes cropping at 200% Text Size

---

doc/cascadia/profiles.schema.json

Adds proper `type` for `SchemePair` definition to avoid warnings about matches of multiple schemas.
Same fix as https://github.com/microsoft/terminal/pull/4045
- Pointed $schema to local file instead of https://aka.ms/terminal-profiles-schema
- Confirmed warning goes away when using a string
- Confirmed using the light/dark object format still passes validation
- Confirmed values like `"colorScheme": 3` no longer incorrectly pass validation whereas they would before

Fix matches of multiple schemas on "colorScheme"

---

src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/inc/til/unicode.h
src/terminal/adapter/adaptDispatch.cpp

`COOKED_READ_DATA` is a little special and requires cursor navigation
based on the raw (buffered) text contents instead of what's in the
text buffer. This requires the introduction of new helper functions
to implement such cursor navigation. They're made part of `TextBuffer`
as these helpers will get support graphemes in the future.
It also helps keeping it close to `TextBuffer` as the cursor
navigation should optimally behave identical between the two.
Part of #8000.

Add text based cursor movement helpers

---

src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
src/host/ApiRoutines.h
src/host/VtApiRoutines.cpp
src/host/VtApiRoutines.h
src/host/readDataCooked.cpp
src/host/readDataCooked.hpp
src/host/stream.cpp
src/inc/test/CommonState.hpp
src/server/ApiDispatchers.cpp
src/server/IApiRoutines.h

This is a minor cleanup to deduplicate the two ReadConsole methods
and will help with making changes to how `COOKED_READ_DATA` is called.
It additionally changes the initial data payload from a `string_view`
to a `wstring_view` as it is guaranteed to be `wchar_t`.
This matches the current `COOKED_READ_DATA` implementation which
blindly assumes that the initial data consists of `wchar_t`.
Closes #5618

Merge ReadConsoleA/W API routines

---

src/host/ft_host/Message_KeyPressTests.cpp
src/interactivity/win32/windowio.cpp

Applications like PowerToys, with their keyboard remapping features frequently (i.e whenever a remapped shortcut is triggerred) send `KeyEvent` with out-of-range virtual keycode values (E.g. 0xFF). This is fixed for WT in #7145, we just needed it in our good ol' `conhost`.
After this PR, Key events with an invalid virtual keycode and scancode==0 are ignored, and are not added to the `InputBuffer`. Incase, only virtual keycode is valid but not scancode, we will try to infer the correct scancode using the virtual keycode mapping.
#7145 
#7064 
- Triggered a remapped shortcut and verified that `showkey -a` doesn't output `^@` unexpectedly.
- Key events with an Invalid virtual Keycode and Scancode == 0 are ignored.
- This PR doesn't include any changes for `WM_[SYS][DEAD]CHAR` messages, they …

ConHost: Ignore WM_[SYS]KEYDOWN/WM_[SYS]KEYUP events with an invalid virtual keycode and a scan code of 0

---

README.md

I updated the note prefix for blockquotes with GitHub latest built-in styles.
- https://github.com/orgs/community/discussions/16925
This PR fixed the broken style due to their format change.
- https://github.com/microsoft/terminal/pull/13615

Fix GitHub built-in highlight styles

---

src/cascadia/WpfTerminalControl/TerminalContainer.cs

Seems like the compiler cares about them more than our formatter. Possibly introduced in https://github.com/microsoft/terminal/pull/15062
- Tests passed

Fix C# warnings during a clean build

---

build/pipelines/templates-v2/job-build-package-wpf.yml
build/pipelines/templates-v2/job-build-project.yml
build/pipelines/templates-v2/job-merge-msix-into-bundle.yml
build/pipelines/templates-v2/job-package-conpty.yml
build/pipelines/templates-v2/job-submit-windows-vpack.yml

The OneBranch build system relies on the *build container host* being able to publish all artifacts all at once. Therefore, our build steps must not publish any artifacts.
I made it configurable so that the impact on existing pipelines was minimal.
For every job that produces artifacts and is part of the release pipeline, I am now exposing two variables that we can pass to OneBranch so that it can locate and name artifacts:
- `JobOutputDirectory`, the output folder for the entire job
- `JobOutputArtifactName`, the name of the artifact produced by the job
I have also added a `variables` parameter to every job, so consuming pipelines can override or insert their own variables.

Allow skipping artifact publication in all release build jobs

---

src/terminal/adapter/ut_adapter/adapterTest.cpp

Add test for subparameter based `GraphicOptions`.
`GraphicsSingleWithSubParamTests` is added for subparameter based `GraphicOptions`. This should've been included with #15729.
Also, while working on #15795, I realized creating and passing subparameters for the tests is painful right now. I've added a small util `MakeSubParamsAndRanges(...)` that eases creating subparameters and subparameter ranges from a simple list of (lists of) subparameters.
- All tests passed.

[Tests] Add test for subparameter based GraphicOptions

---

src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

Switch the schema depending on the branding we're being built for
Ever since we started writing the entire settings file out ourselves,
we've had the opportunity to control which schema it uses.
This is a quality-of-life improvement for Preview users, and might make
life easier for Dev users as well.
For Debug builds, it even switches over to a local `file://` path to
the schema in the source directory!
Closes #6601

Use a different schema for each branding

---

src/cascadia/TerminalConnection/AzureClientID.h

Some folks over in MSAL land told us that client IDs don't need to be kept secret.
This reduces the delta between "public" terminal and "release build" terminal by one more file, leaving only the telemetry header left (which won't be going public for obvious reasons).
This will also make it easier for contributors to test out Azure Cloud Shell changes... and testing out VT without ConPTY interfering[^1].
[^1]: When Dev branding is selected, Azure Cloud Shell has the added perk of being wired directly to TerminalCore rather than going through ConPTY.

Include our Azure client ID in AzureConnection

---

src/host/readDataCooked.cpp
src/host/readDataCooked.hpp

This is a small optimization that makes COOKED_READ_DATA erase short
runs of text more quickly. It's not really necessary to do this as
this code is not a hotpath, but I felt like it's neater this way.
It requires no heap allocations even for long runs of text.
* Deleting text anywhere in a prompt erases it ✅

A small optimization of COOKED_READ_DATA::_erase

---

src/cascadia/TerminalCore/Terminal.cpp

Pattern tree coordinates are viewport-relative.
Closes #15891
* Print some text so the viewport scrolls down
* Print a URL
* URL is underlined on hover ✅

Fix pattern coordinates to be viewport relative

---

src/renderer/atlas/AtlasEngine.cpp

Font features require us to skip the fast path via `GetTextComplexity`.
`IDWriteTextLayout` handles it the same way internally.
Closes #15896
* Use Cascadia Code
* Set `features: { "ss19": 1 }`
* "0" has a dash in it instead of a dot ✅

AtlasEngine: Fix support for font features

---

src/renderer/atlas/AtlasEngine.cpp

`PaintCursor()` is only called when the cursor is visible, but we need
to invalidate the cursor area even if it isn't. Otherwise a transition
from a visible to an invisible cursor wouldn't be rendered.
I'm confident that this closes #15199
* Set blink duration extremely high
* Launch pwsh.exe
* Press Enter a few times
* Press Ctrl+L
* There are never 2 cursors visible, not even briefly ✅

AtlasEngine: Fix invalidation when the cursor is invisible

---

src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/BackendD3D.cpp

When marking newly scrolled in rows as invalidated we used:
```
if (offset < 0)
...
else
...
```
But it should've been:
```
if (offset < 0)
...
else if (offset > 0)
...
```
Because now it always set the start of the invalidated rows range to 0.
Additionally, this includes a commented debug helper which I've used
to figure out an unrelated bug. During that search I found this bug.

AtlasEngine: Fix overly aggressive invalidation

---

src/cascadia/TerminalSettingsModel/DefaultTerminal.cpp

I manually changed the permissions on `HKCU\Console` to deny "Create subkey" to myself. Then confirmed that it explodes before this change, and not after this change.
Closes #15458

Don't explode if HKCU\Console is write-protected

---

src/cascadia/TerminalApp/TabBase.cpp
src/cascadia/TerminalApp/TabBase.h
src/cascadia/TerminalApp/TabBase.idl
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalTab.cpp

`TerminalTab::_RecalculateAndApplyReadOnly` didn't know about whether a tab should be closable or not, based on the theme settings. Similarly (though, unreported), the theme update in `TerminalPage::_updateAllTabCloseButtons` didn't really know about readonly mode.
This fixes both these issues by moving responsibility for the tab close button visibility into `TabBase` itself.
Closes #15902

Update close button visibility based on BOTH settings and readonly mode

---

src/cascadia/TerminalSettingsEditor/Launch.xaml

Added a style that allows negative values in the launch position parameters.

Allows negative values in launch parameters

---

src/cascadia/CascadiaPackage/Package-Can.appxmanifest

This commit fixes the identity of our new canary packages.
Additionally, it slightly reorders one block so that the file is
almost entirely in the same layout as the preview appxmanifest,
allowing for a better direct comparison (with git diff, etc.).

Fix identity of canary appxmanifest

---

src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
src/host/_stream.cpp
src/host/output.cpp
src/host/output.h
src/host/readDataCooked.cpp
src/host/readDataCooked.hpp

This commit fixes 3 bugs:
* `COOKED_READ_DATA` failed to initialize its `_distanceCursor` and
`_distanceEnd` members. I took this as an opportunity to make them
`ptrdiff_t`, to reduce the likelihood of overflows in the future.
* `COOKED_READ_DATA::_writeChars` added `scrollY` to the written
distance, even though `WriteCharsLegacy` writes a negative value into
that out parameter. This was fixed by changing `WriteCharsLegacy` to
write positive values and by adding a debug assertion.
* `StreamScrollRegion` calls `IncrementCircularBuffer` which causes a
synchronous (!) ConPTY flush to the output pipe (side note: this is
the primary reason why newlines are so slow in ConPTY).
Since cooked reads are supposed to behave like a pager and not write
into the scrollback, we temporarily mark the …

COOKED_READ_DATA: Fix scrolling under ConPTY

---

src/buffer/out/ut_textbuffer/TextBuffer.Unit.Tests.vcxproj
src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/interactivity/win32/windowproc.cpp
src/renderer/atlas/BackendD3D.h
src/renderer/vt/tracing.cpp
src/terminal/input/terminalInput.hpp

* `[[nodiscard]]` and `[[maybe_unused]]` must come before `virtual` and `static` qualifiers
* We were calling the jsoncpp constructors directly (again) as functions (again)
* Some of our preprocessor `#endif` lines were quite messed up (`-Winvalid-token`)
* One of our test projects was using somebody else's `precomp.h`
Related to #14871

Fix a number of minor issues that Clang flagged (again!)

---

src/cascadia/WindowsTerminal_UIATests/Init.cs
src/cascadia/WindowsTerminal_UIATests/WindowsTerminal.UIA.Tests.csproj
src/host/ft_uia/Host.Tests.UIA.csproj
src/host/ft_uia/Init.cs

WinAppDriver depends on a bunch of .NET assemblies that collide *big time*. Let's just quarantine it.
I kept the fallback to $TESTDIR\WinAppDriver.exe because there's a chance that the Windows build depends on it.

Stage WinAppDriver into its own folder

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/Backend.h
src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/BackendD3D.h

This is a theoretical improvement for #15553 where Windows Terminal
crashed due to AtlasEngine accessing the soft font bitmap outside of
bounds. The problem is that the soft font cell size was non-zero.
This PR hardens against such situations by checking whether the
requested soft font index is inside the bounds of the bitmaps.
The improvement couldn't be tested as it couldn't be reproduced.

AtlasEngine: Harden against invalid soft fonts

---

src/cascadia/TerminalApp/TabManagement.cpp

Previously, the duplication method considered only the next to the selected tab(`tab.TabViewIndex() + 1`) as the insert position. Changed that to consider the setting.
Closes #15776

Make duplicate tabs consider the existing configuration option for its insertion

---

.github/actions/spelling/allow/apis.txt
src/cascadia/PublicTerminalCore/HwndTerminal.cpp
src/cascadia/PublicTerminalCore/HwndTerminal.hpp
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/cascadia/TerminalCore/TerminalSelection.cpp
src/cascadia/TerminalCore/terminalrenderdata.cpp

`Terminal` is used concurrently by at least 4 threads. The table
below lists the class members and the threads that access them
to the best of my knowledge. Where:
* UI: UI Thread
* BG: Background worker threads (`winrt::resume_background`)
* RD: Render thread
* VT: VT connection thread
|                                    | UI | BG | RD | VT |
|------------------------------------|----|----|----|----|
| `_pfnWriteInput`                   | x  | x  |    | x  |
| `_pfnWarningBell`                  |    |    |    | x  |
| `_pfnTitleChanged`                 |    |    |    | x  |
| `_pfnCopyToClipboard`              |    |    |    | x  |
| `_pfnScrollPositionChanged`        | x  | x  |    | x  |
| `_pfnCursorPositionChanged`        |    |    |    | x  |
| `_pfnTaskbarProgressChanged`       | …

Add missing lock guards on Terminal access

---

src/cascadia/TerminalSettingsEditor/EditColorScheme.cpp

Since the "delete color scheme" button is filled with an icon and a Text Box, the text is not automatically exposed as the autoProp.Name for the button. We have to do it manually just like we do for "delete profile".
Validated manually using accessibility insights
Closes #15984

Add Auto Prop Name to 'Delete Color Scheme' button

---

src/cascadia/LocalTests_SettingsModel/ThemeTests.cpp
src/cascadia/TerminalApp/SettingsTab.cpp
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h
src/cascadia/TerminalSettingsModel/IconPathConverter.cpp
src/cascadia/TerminalSettingsModel/IconPathConverter.h
src/cascadia/TerminalSettingsModel/IconPathConverter.idl
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h
src/cascadia/TerminalSettingsModel/Theme.idl

Adding enum iconstyle for hiding the icon in the tab #8157 
Please confirm if I am on the right track.

Option to default to show icon in tab, hide tabicon or make icon in tab monochrome.

---

src/cascadia/TerminalApp/AboutDialog.cpp

You can't catch an A/V. 
Closes #15459

Don't crash when the checking for updates without a network

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.xaml

This replaces the use of a `<Canvas>` with an `<Image>` for drawing
scrollbar marks. Otherwise, WinUI struggles with the up to ~9000 UI
elements as they get dirtied every time the scrollbar moves.
(FWIW 9000 is not a lot and it should not struggle with that.)
The `<Image>` element has the benefit that we can get hold of a CPU-side
bitmap which we can manually draw our marks into and then swap them into
the UI tree. It draws the same 9000 elements, but now WinUI doesn't
struggle anymore because only 1 element gets invalidated every time.
Closes #15955
* Fill the buffer with "e"
* Searching for "e" fills the entire thumb range with white ✅
* ...doesn't lag when scrolling around ✅
* ...updates quickly when adding newlines at the end ✅
* Marks sort of align with their scroll position ✅

Improve performance of scrollbar marks

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

I noticed this last week, but forgot to file. If you have a pair of splits, and `exit -1` the first, you can't use `enter` to restart it. 
This PR fixes that. Basically, `TerminalPage` registers it's `_restartPaneConnection` handler when it makes a new `Pane` object. It registers the callback straight to the `Pane`. However, when a `Pane` gets split, it makes a _new_ `Pane` object, and moves the original content into the new pane. `TerminalPage` however, would never hook up its own callback to that newly created pane. 
This fixes that.

Fix `enter` to restart the first pane in a split

---

src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/IslandWindow.h

`ImmersiveColorSet` gets sent more often than just on a theme change. It notably gets sent when the PC is locked, or the UAC prompt opens.
Tested manually by setting the font to `garbo`and:
* locking, then logging back in. No dialog ✅ 
* UAC via run dialog + `regedit`. No dialog ✅ 
* Actually changing the OS theme. Dialog ✅

Don't update the settings, unless the theme actually changed

---

src/host/VtIo.cpp
src/host/VtIo.hpp
src/host/_stream.cpp
src/host/getset.cpp
src/host/inputBuffer.cpp
src/host/inputBuffer.hpp
src/renderer/vt/XtermEngine.cpp
src/renderer/vt/invalidate.cpp
src/renderer/vt/paint.cpp
src/renderer/vt/state.cpp
src/renderer/vt/vtrenderer.hpp

Previously, all unknown escape sequences would lead to an immediate call
to `VtEngine::_Flush()`. This lead to problems with nushell which uses
FTCS marks that were unknown to us. Combined with the linewise redrawing
that nushell does, Terminal would get the prompt in two separate frames,
causing a slight flickering.
#14677 fixed this by suppressing the `_Flush()` call when unknown
sequences are encountered. Unfortunately, this triggered a bug due
to our somewhat "inconsistent" architecture in conhost:
`XtermEngine::WriteTerminalW` isn't just used to flush unknown sequences
but also used directly by `InputBuffer::PassThroughWin32MouseRequest`
to write its mouse sequence directly to the ConPTY host.
`VtEngine` already contains a number of specialized member functions
like …

ConPTY: Fix missing flush on console mode changes

---

src/cascadia/TerminalControl/TermControl.cpp

When launching a debug Terminal, `_initializedTerminal` might still be false and the scrollbar might still be 0px tall. This causes the `assert(false)` condition within `_throttledUpdateScrollbar` to be hit.
Regressed in #16006

Don't assert in debug before we're initialized

---

src/cascadia/TerminalApp/AboutDialog.cpp
src/cascadia/TerminalApp/pch.h

With us adding a .appinstaller distribution of Canary, the Store
services update checker has beome insufficient to determine whether
there are package updates.
App Installer supports us checking for updates by using PackageManager
and the Package interfaces.
We'll use those instead of the Store services interface, and bail out
early if the App Installer gives us an answer.

About: check PackageManager for updates in addition to Store

---

src/cascadia/TerminalApp/TabManagement.cpp

One day into 1.19, and there's a LOT of hits here (**76.25%** of our ~300 crashes). A crash if the Theme doesn't have a `tab` member. 
Regressed in #15948
Closes MSFT:46714723

Fix a crash for users without a `tab` theme

---

.github/actions/spelling/allow/apis.txt
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/inc/cppwinrt_utils.h

f1aa699 was fundamentally incorrect as it used `IdnToAscii` and
`IdnToUnicode` on the entire URL, even though these functions only work
on domain names. This commit fixes the issue by using the WinRT `Url`
class and its `AbsoluteUri` and `AbsoluteCanonicalUri` getters.
The algorithm still works the same way though.
Closes #16017
* ``"`e]8;;https://www.xn--fcbook-3nf5b.com/`e\test`e]8;;`e\"``
still shows as two URLs in the popup ✅
* Shows the given URI if it's canonical and not an IDN ✅
* Works with >100 char long file:// URIs ✅

Fix URL sanitizer for long URLs

---

build/pipelines/templates-v2/job-build-project.yml
build/scripts/New-UnpackagedTerminalDistribution.ps1

I also added support to the unpackaged distribution script to produce portable mode packages. It is off by default for AppX->ZIP builds and **on** by default for Layout->ZIP builds.
This constitutes a change in behavior.

Build unpackaged Canary distributions in portable mode

---

build/pipelines/nightly.yml
build/pipelines/templates-v2/job-deploy-to-azure-storage.yml
src/cascadia/CascadiaPackage/Package-Can.appxmanifest

Unfortunately, the appLicensing restricted capability we used to make Canary installable without the store only works on Windows 11. Because of that, we have to restrict the app package to Windows 11 and above.
I'd rather not leave Windows 10 users out in the cold, so this pull request also publishes Canary builds to the public storage bucket with the name `Microsoft.WindowsTerminalCanary_latest_x64.zip` (etc.)
The version number will be kept inside the archive. It remains to be seen whether that is a good idea!
When combined with #16048, Canary builds from Azure will automatically run in portable mode!

nightly: upload unpackaged to Az as well; force canary to 11+

---

src/common.build.pre.props

Control Flow Guard requires both linker and compiler flags.
It turns out that the MSVC build rules determine whether to _link_ with CFG based on whether it compiled anything with CFG.
It also turns out that when you don't compile anything (such as in our DLL projects that only consume a static library!), the build rules can't guess whether to link with CFG.
Whoops.
We need to force it.

Fix CFG on our static-lib-only DLL projects

---

build/pipelines/templates-v2/job-build-package-wpf.yml
build/pipelines/templates-v2/job-build-project.yml
build/pipelines/templates-v2/job-merge-msix-into-bundle.yml
build/pipelines/templates-v2/job-package-conpty.yml

The version we were using requires .NET 2.1 (wow) which is way out of support.
Task version 3 supports much newer versions.

build: switch the EsrpCodeSigning task to version 3

---

build/config/release.gdnbaselines
build/config/tsa.json
build/pipelines/ob-nightly.yml
build/pipelines/ob-release.yml
build/pipelines/templates-v2/job-build-project.yml
build/pipelines/templates-v2/job-merge-msix-into-bundle.yml
build/pipelines/templates-v2/job-publish-symbols.yml
build/pipelines/templates-v2/pipeline-full-release-build.yml
build/pipelines/templates-v2/pipeline-onebranch-full-release-build.yml
build/pipelines/templates-v2/variables-nuget-package-version.yml
build/pipelines/templates-v2/variables-onebranch-config.yml

This pipeline does everything the existing release pipeline does, except it does it using the OneBranch official templates.
Most of our existing build infrastructure has been reused, with the following changes:
- We are no longer using `job-submit-windows-vpack`, as OneBranch does this for us.
- `job-merge-msix-into-bundle` now supports afterBuildSteps, which we use to stage the msixbundle into the right place for the vpack
- `job-build-project` supports deleting all non-signed files (which the OneBranch post-build validation requires)
- `job-build-project` now deletes `console.dll`, which is unused in any of our builds, because XFGCheck blows up on it for some reason on x86
- `job-publish-symbols` now supports two different types of PAT ingestion
- I have pulled out the NuGet filename …

build: add a OneBranch Official release pipeline

---

src/cascadia/TerminalApp/TerminalWindow.cpp

Wow our preview population must just _not use `startupActions`. This obviously never worked in 1.18 Preview.
Closes #16050

Fix tearout with `startupActions` set.

---

src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h
src/cascadia/WindowsTerminal/WindowThread.cpp
src/cascadia/WindowsTerminal/WindowThread.h

See MSFT:46763065. Looks like we're in the middle of being `Refrigerate`d, we're pumping messages, and as we pump messages, we get to a `co_await` in `AppHost::_WindowInitializedHandler`. When we resume, we just try to use `this` like everything's fine but OH NO, IT'S NOT.
To fix this, I'm
* Adding `enable_shared_from_this` to `AppHost`
* Holding the `AppHost` in a shared_ptr in WindowThread
- though, this is a singular owning `shared_ptr`. This is probably ripe for other footguns, but there's little we can do about this.
* whenever we `co_await` in `AppHost`, make sure we grab a weak ref first, and check it on the other side.
This is another "squint and yep that's a bug" fix, that I haven't been able to verify locally. This is
[allegedly](https://media.tenor.com/VQi3bktwLdIAAAAC/allegedly …

Use `weak_ptr`s for `AppHost` for coroutines

---

src/cascadia/TerminalSettingsModel/ActionArgs.cpp

Fixes MSFT:46725264
don't explode trying to parse a URL, if the string wasn't one.

Fix a crash in the GenerateName for `SearchForTextArgs`

---

src/cascadia/TerminalApp/TerminalPage.cpp

Updated the function `TerminalPage::CloseWindow`  to include logic for closing context and flyout menus so that they are dismissed before the warning is displayed.

Dismiss flyouts before opening warning dialog when exiting app

---

src/cascadia/TerminalApp/Pane.cpp

Well, Pane doesn't _only_ care if the connection isn't entering a terminal state. It does need to update its own state first.
Regressed in #15335
Closes #16068

Fix `closeOnExit: always`

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.cpp

`GetAt` can throw if the index is out of range. We don't check that in some places. This fixes some of those.
I don't think this will take care of #15689, but it might help?

Bounds check some tab GetAt()s

---

src/cascadia/TerminalApp/TerminalWindow.cpp

Have added a conditional check in `TerminalWindow::UpdateSettings` method

Dismiss "Failed to reload settings" modals when settings.json is valid

---

build/pipelines/ob-nightly.yml
build/pipelines/ob-release.yml
build/pipelines/templates-v2/pipeline-full-release-build.yml
build/pipelines/templates-v2/variables-nuget-package-version.yml

This fixes a cosmetic issue with the version number in the unpackaged builds and NuGet packages.
They were showing up as `-preview`, even when they were stable, because the variable template didn't know about the branding.

build: pass branding into the nuget variable template

---

doc/cascadia/profiles.schema.json

This addresses the following issues:
* The JSON Schema spec doesn't actually define whether objects with
a "properties" key still require `"type": "object"` or not.
VS Code for instance largely pretends as if it's implied, but when it
encounters them inside a `oneOf` tree, then it behaves as if it isn't.
In other words, we need to always set `"type": "object"`.
* Declaring an `oneOf` containing a `"type": "string"` and an `enum`
doesn't work, because if one of the `enum` cases is given, it results
in both variants to match, since any `enum` is also a `string`.
We have to use `anyOf` instead.
* `SuggestionSource` used `"BuiltinSuggestionSource"` inside a `type`
key which doesn't work. We have to use `$ref` for that.
Closes #13387
* VS Code stops complaining ✅
* …

Fix issues and warnings caused by profiles.schema.json

---

src/tools/vtapp/Program.cs

No need to check for if a bit is set before manually clearing or setting them when xor will do the trick.

Flip bits instead of checking for them

---

src/cascadia/TerminalConnection/ConptyConnection.cpp
src/inc/til/env.h
src/til/ut_til/EnvTests.cpp

eb871bf fails to properly handle REG_SZ strings, which are documented as
being null-terminated _and_ length restricted.
`wcsnlen` is the perfect fit for handling this situation as it returns
the position of the first \0, or the given length parameter.
As a drive by improvement, this also drops some redundant code:
* `to_environment_strings_w` which is the same as `to_string`
* Retrieving `USERNAME`/`USERDOMAIN` via `LookupAccountSidW` and
`COMPUTERNAME` via `GetComputerNameW` is not necessary as the
variables are "volatile" and I believe there's generally no
expectation that they change unless you log in again.
Closes #16051
* Run this in PowerShell to insert a env value with \0:
```pwsh
$hklm = [Microsoft.Win32.RegistryKey]::OpenBaseKey(
[Microsoft.Win32.RegistryHive]::LocalMachine,
0
) …
```

env: properly handle nulls in REG_SZ strings

---

.github/actions/spelling/expect/expect.txt
src/host/ft_host/API_BufferTests.cpp
src/host/readDataCooked.cpp

This restores the original code from before 821ae3a where
the `.GetMainBuffer()` call was accidentally removed.
Closes #16158
* Run this Python script:
```py
import sys
while True:
sys.stdout.write("\033[?1049h")
sys.stdout.flush()
sys.stdin.readline()
sys.stdout.write("\033[?1049l")
```
* Press enter repeatedly

COOKED_READ: Fix reference counting woes

---

src/interactivity/win32/Clipboard.cpp

cd6b083 had 2 issues:
* Improper testing with Ctrl+M instead of Edit > Mark.
* Wrong SelectionState function being used. When the selection is
initiated without keyboard or mouse, `IsKeyboardMarkSelection`
returns false. The proper function to use is `IsLineSelection`.
Closes #15153
* Run Far
* Start selection via Edit>Mark
* Hold Alt while dragging to make a rectangular selection
* Right click
* Clipboard contains a rectangular copy ✅

Fix rectangular clipboard copying initiated from the app menu

---

src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/IslandWindow.h

As in the title. Also fixes a crash for refrigeration with the rainbow border. Closes #16211
Tested by manually forcing us into Windows 10 mode (to refrigerate the window). That immediately repros the bug, which was simple enough to fix.

Clear the system menu when we refrigerate a window

---

src/cascadia/TerminalControl/TermControl.cpp

Wrap single quotes to drag and dropped paths in WSL
#15646  , #8109 
First time contributor, from what I understand from reading #15646 and #8109 , issue is asking for single quotes added to a drag and dropped path always, regardless of whitespace and special characters, in WSL.
Tested drag and drop changes in WSL and non WSL sources.
Closes #15646

add single quotes to WSL drag and drop

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.r.cpp
src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/common.h

This commit fixes 4 minor bugs:
* Forgot to set the maximum swap chain latency. Without it, it defaults
to up to 3 frames of latency. We don't need this, because our renderer
is simple and fast and is expected to draw frames within <1ms.
* ClearType treats the alpha channel as ignored, whereas custom shaders
can manipulate the alpha channel freely. This meant that using both
simultaneously would produce weird effects, like text having black
background. We now force grayscale AA instead.
* The builtin retro shader should not be effected by the previous point.
* When the cbuffer is entirely unused in a custom shader, it has so far
resulted in constant redraws. This happened because the D3D reflection
`GetDesc` call will then return `E_FAIL` in this situation.
The new code on the other hand …

AtlasEngine: Minor bug fixes

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/common.h
src/renderer/dx/DxFontInfo.cpp

I still don't know how to reproduce it properly, but I'm slowly
wrapping my head around how and why it happens. The issue isn't that
`FindFamilyName` fails with `exists=FALSE`, but rather that any of the
followup calls like `GetDesignGlyphMetrics` fails, which results in an
exception and subsequently in an orderly fallback to Consolas.
I've always thought that the issue is that even with the nearby font
collection we get an `exists=FALSE`... I'm not sure why I thought that.
This changeset also drops the fallback iteration for Lucida Console and
Courier New, because I felt like the code looks neater that way and I
think it's a reasonable expectation that Consolas is always installed.
Closes #16058

Fix the fix for the fix of nearby font loading

---

src/cascadia/WindowsTerminal/AppHost.cpp

For history: 
> This is MSFT:46763065 internally. Dumps show this repros on 1.19 too. 
> 
> This was previously #16061 which had a theoretical fix in #16065. Looks like you're on Terminal Stable v1.18.2822.0, and https://github.com/microsoft/terminal/releases/tag/v1.18.2822.0 is supposed to have had that fix in it. Dang. 
> well this is embarrassing ... I never actually checked if we _still had a `_window`_. We're alive, yay! But we're still in the middle of refrigerating. So, there's no HWND anymore 
Attempt to fix this by actually ensuring there's a `_window` in `AppHost::_WindowInitializedHandler`
Closes #16235

Another theoretical fix for a crash

---

src/cascadia/CascadiaPackage/Package-Can.appxmanifest
src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest

Adds
```xml
<uap17:UpdateWhileInUse>defer</uap17:UpdateWhileInUse>
```
To our `Package.Properties` for all our packages. This was added in the September 2023 OS release of Windows 11.
Apparently, this just works now? I did update VS, but I don't _think_ that updated the SDK. I have no idea how it updated the manifest definitions.
Closes #3915
Closes #6726

Defer package updates while the Terminal is running

---

tools/Get-OSSConhostLog.ps1
tools/ReleaseEngineering/New-TerminalStackedChangelog.ps1
tools/ReleaseEngineering/ServicingPipeline.ps1

It makes the output less cluttered and more correct (for example: ServicingPipeline no longer tries to service two copies of each commit if there's a merge in the history...)

releng: add --first-parent to the scripts that use git log

---

src/cascadia/TerminalSettingsEditor/CommonResources.xaml

This changes the appearance of the disclaimer text that is used on some of the settings pages. The italic text style is replaced with a neutral style that fits better with the rest of the UI.
Before:
After:
Addresses #16264.
I also tried out these alternative styles but overall preferred the default TextBlock style (BodyTextBlockStyle).
BaseTextBlockStyle:
CaptionTextBlockStyle:
SecondaryTextBlockStyle:
Manually verified the appearance of the new text style on all pages where it is used, in light and dark mode.

Change DisclaimerStyle to be non-italic

---

src/cascadia/CascadiaPackage/Package-Can.appxmanifest

Canary still advertised the Dev CLSIDs, so it didn't work as DefTerm.
Closes #16316

canary: include the correct handoff CLSIDs

---

src/cascadia/CascadiaPackage/Package-Can.appxmanifest
src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest

I find it somewhat silly that (1) this isn't documented anywhere and (2) installing the "desktop experience" packages for Server doesn't automatically add support for the `Windows.Desktop` platform...
Oh well.
I'm going to roll this one out via Preview first, because if the store blows up on it I would rather it not be during Stable roll-out.

Add a magic incantation to tell the Store we support Server

---

src/renderer/dx/DxFontInfo.cpp

The nearby font loading has to be outside of the try/catch of the
`_FindFontFace` call, because it'll throw for broken font files.
But in my previous PR I had overlooked that the font variant loop
modifies the only copy of the face name that we got and was in the
same try/catch. That's bad, because once we get to the nearby search
code, the face name will be invalid. This commit fixes the issue by
wrapping each individual `_FindFontFace` call in a try/catch block.
Closes #16322
* Remove every single copy of Windows Terminal from your system
* Manually clean up Cascadia .ttf files because they aren't gone
* Destroy your registry by manually removing appx references (fun!)
* Put the 4 Cascadia .ttf files into the Dev app AppX directory
* Launch
* No warning ✅

Fix nearby fonts for DxEngine again

---

src/common.build.pre.props

Our CI seems to have had an update recently to around VS 17.7.
That version contains a faulty implementation for C26478 and C26494.
The issue has been fixed in VS 17.8 and later.

Hotfix recent AuditMode failures on CI

---

.github/workflows/similarIssues.yml

Just like in https://github.com/microsoft/WSL/pull/10745
We're working with the WSL team to figure out if we can use a LLM to help us triage. This _should_ just comment on issues, if it finds something similar on the backlog. 
@craigloewen-msft as an FYI. If this explodes or doesn't work, well, we'll figure it out soon enough 😝

test: Add an LLM-powered bot to detect dupes

---

src/host/VtInputThread.cpp
src/host/VtInputThread.hpp
src/host/VtIo.cpp

Under normal circumstances this bug should be rare as far as I can
observe it on my system. However, it does occur randomly.
In short, WSL doesn't pass us anonymous pipes, but rather WSA sockets
and those signal their graceful shutdown first before being closed
later by returning a `lpNumberOfBytesRead` of 0 in the meantime.
Additionally, `VtIo` synchronously pumps the input pipe to get the
initial cursor position, but fails to check `_exitRequested`.
And so even with the pipe handling fixed, `VtIo` will also deadlock,
because it will never realize that `VtInputThread` is done reading.
* Build commit 376737e with this change and replace conhost with it
Coincidentally it contains a bug (of as of yet unknown origin)
due to which the initial cursor position loop in `VtIo` never
completes. …

ConPTY: Fix a shutdown deadlock with WSL

---

src/host/VtIo.cpp
src/renderer/vt/state.cpp

This changeset fixes an issue caused by #15991 where "chunked" escape
sequences would get corrupted. The fix is to simply not flush eagerly
anymore. I tried my best to keep the input lag reduction from #15991,
but unfortunately this isn't possible for console APIs.
Closes #16079
* `type ascii.com` produces soft font ASCII characters ✅

Fix chunked soft fonts not working

---

src/common.build.pre.props
src/host/inputBuffer.cpp

This fixes an issue where character-wise reading of an input like "abc"
would return "a" to the caller, store "b" as a partial translation
(= wrong) and return "c" for the caller to store it for the next call.
Closes #16223
Closes #16299
* `ReadFile` with a buffer size of 1 returns inputs character by
character without dropping any inputs ✅

Fix input buffering for A APIs

---

src/propsheet/misc.cpp

After exiting the main loop in this function the invariant
`nFont <= NumberOfFonts` still holds true. Additionally,
preceding this removed code is this (paraphrased):
```cpp
if (nFont < NumberOfFonts) {
RtlMoveMemory(...);
}
```
It ensures that the given slot `nFont` is always unoccupied by moving
it and all following items upwards if needed. As such, the call to
`DeleteObject` is always incorrect, as the slot is always "empty",
but may contain a copy of the previous occupant due to the `memmove`.
This regressed in 154ac2b.
Closes #16297
* All fonts have a unique look in the preview panel ✅

Fix font preview for conhost

---

src/host/inputBuffer.cpp

Converts null byte to specific input event, so that it's properly delivered to the program running in the terminal.
Closes #15939

Fix Control+Space not sent to program running in terminal

---

src/renderer/base/renderer.cpp

81b7e54 caused a regression in `SetConsoleWindowInfo` and any other
function that used the `WriteToScreen` helper. This is because it
assumes that it can place the viewport anywhere randomly and it was
written at a time where `TriggerScroll` didn't exist yet (there was
no need for that (also not today, but that's being worked on)). 
Caching the viewport meant that `WriteToScreen`'s call to
`TriggerRedraw` would pick up the viewport from the last rendered
frame, which would cause the intersection of both to be potentially
empty and nothing to be drawn on the screen.
This commit reverts 81b7e54 as I found that it has no or negligible
impact on performance at this point, likely due to the overall
vastly better performance of conhost nowadays.
Closes #15932
* Scroll the viewport by entire …

Fix scrolling with SetConsoleWindowInfo

---

CONTRIBUTING.md
README.md
SUPPORT.md
doc/roadmap-2022.md
doc/roadmap-2023.md
doc/specs/#1571 - New Tab Menu Customization/#1571 - New Tab Menu Customization.md
doc/specs/#1595 - Suggestions UI/Suggestions-UI.md
doc/specs/#2046 - Unified keybindings and commands, and synthesized action names.md
doc/specs/#5000 - Process Model 2.0/#1032 - Elevation Quality of Life Improvements.md
doc/specs/#5000 - Process Model 2.0/#4472 - Windows Terminal Session Management.md
doc/specs/#653 - Quake Mode/#653 - Quake Mode.md
doc/specs/#6899 - Action IDs/#6899 - Action IDs.md
doc/terminal-v2-roadmap.md

Update paths to use relative linking instead of static GitHub link. Also fixes some dead links
Closes #16338

Update paths to use linking within repo instead of github URL

---

src/cascadia/TerminalConnection/AzureConnection.cpp

Cloud shell connection calls out to Azure to do a device code login. When the polling interval is exceeded or the tab is closed, the method doing the connection polling returns `nullptr`, and `AzureConnection` immediately tries to `GetNamedString` from it, causing a crash. This doesn't repro on Terminal Stable or Preview, suggesting it's pretty recent related to the update of this azureconnection.
This is just a proposed fix, not sure if you want to do more extensive changes to the affected class or not, so marking this as a draft.
* N/A - encountered this while using the terminal myself
Tested out a local dev build:

Fixed crash when cloud shell provider timed out or was closed waiting for login

---

src/terminal/parser/InputStateMachineEngine.cpp

Since all VT parameters are treated to be at least 1 (and 1 if they're
absent or 0), `modifierParam > 0` was always true. This meant that
`ENHANCED_KEY` was always being set. It's unclear why `ENHANCED_KEY`
was used there, but it's likely not needed in general.
Closes #16266
* Can't test this unless we fix the win32 input mode issue #16343 ❌

Fix dwControlKeyState always including ENHANCED_KEY

---

src/cascadia/TerminalApp/TerminalTab.cpp

tl;dr: A coroutine lambda does not hold onto captured variables.
This causes an AV crash when closing tabs. I randomly noticed this
in a Debug build as the memory contents got replaced with 0xCD.
In a Release build this bug is probably fairly subtle and not common.

Fix a coroutine AV crash

---

src/host/inputBuffer.cpp
src/host/inputBuffer.hpp
src/host/outputStream.cpp

This changeset avoids re-encoding output from `AdaptDispatch`
via the win32-input-mode mechanism when VT input is enabled.
That is, an `AdaptDispatch` output like `\x1b[C` would otherwise
result in dozens of characters of input.
Related to #16343
* Replace conhost with this
* Launch a Win32 application inside WSL
* ASCII keyboard inputs are represented as single `INPUT_RECORD`s ✅

Avoid encoding VT via win32 input mode

---

src/host/outputStream.cpp

The final parameter, `updateBottom`, controls not just whether the
`_virtualBottom` is updated, but also whether the position is clamped
to be within the existing `_virtualBottom`. Setting this to `false`
thus broke scroll-forward as the `_virtualBottom` was now a constant.
* Disable scroll-foward
* Press and hold Ctrl+C
* It scrolls past the viewport bottom ✅

Fix scroll-forward-disable setting

---

src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
src/renderer/vt/VtSequences.cpp
src/renderer/vt/invalidate.cpp
src/renderer/vt/state.cpp
src/renderer/vt/vtrenderer.hpp
src/terminal/adapter/adaptDispatch.cpp

When ConPTY exits it should attempt to restore the state as it was
before it started. This is particularly important for the win32
input mode sequences, as Linux shells don't know what to do with it.
Related to #16343
* Replace conhost with this
* Launch a Win32 application inside WSL
* Exit that application
* Shell prompt doesn't get filled with win32 input mode sequences ✅

Disable win32 input mode on exit

---

doc/AddASetting.md

Added some Punctuation Marks as Required.
None.
There were some missing Punctuation Marks(Ex: Colon(:) and Full Stop(.)), so I have added them.

Minor grammar fixes for the vintage AddASetting.md doc

---

README.md

Changes any references of `> **Note**\` with `> [!NOTE]` to match the
new syntax for markdown files in GitHub.
Fixes the 14 November 2023 update to the alerts syntax in markdown
files:
> ## Update - 14 November 2023
> * The initial syntax using e.g. **Note** isn't supported any longer.
> 
> https://github.com/orgs/community/discussions/16925

Fix markdown alerts syntax in README

---

src/host/VtIo.cpp

This prevents an issue in conhost where older versions of Windows Terminal (including the ones currently inbox in Windows, as well as stable and preview) will *still* cause WSL interop to hang on startup.
Since VT input is erroneously re-encoded as Win32 input events on those versions, we need to make sure we request the cursor position *before* enabling Win32 input mode. That way, the CPR we get back is properly encoded.

conpty: request DSR-CPR before Win32 input mode

---

src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/BackendD3D.h
src/renderer/gdi/paint.cpp
src/renderer/gdi/state.cpp

Fixes Curlyline being drawn as single underline in some cases
**Detailed Description**
- Curlyline is drawn at all font sizes.
- We might render a curlyline that is clipped in cases where we don't have enough space to draw a full curlyline. This is to give users a consistent view of Curlylines. Previously in those cases, it was drawn as a single underline.
- Removed minimum threshold `minCurlyLinePeakHeight` for Curlyline drawing.
- GDIRender changes:
- Underline offset now points to the (vertical) mid position of the underline. Removes redundant `underlineMidY` calculation inside the draw call.
Closes #16288
**Validation Steps Performed**
- underlines are drawn properly in WT and Conhost
**PR Checklist**

Fix curlyline rendering in `AtlasEngine` and `GDIRenderer`

---

src/host/VtInputThread.cpp
src/host/VtInputThread.hpp

This makes 3 improvements:
* 16x larger input buffer size improves behavior when pasting
clipboard contents while the win32-input-mode is enabled,
as each input character is roughly 15-20x longer after encoding.
* Translate UTF8 to UTF16 outside of the console lock.
* Preserve the UTF16 buffer between reads for less mallocs.

Increase VtInputThread buffer size

---

.github/actions/spelling/expect/expect.txt
src/renderer/gdi/gdirenderer.hpp
src/renderer/gdi/paint.cpp
src/renderer/gdi/state.cpp
src/tools/RenderingTests/main.cpp

While #16444 left wavy lines in an amazing state already, there were
a few more things that could be done to make GDI look more consistent
with other well known Windows applications.
But before that, a couple unrelated, but helpful changes were made:
* `GdiEngine::UpdateFont` was heavily modified to do all calculations
in floats. All modern CPUs have fast FPUs and even the fairly slow
`lroundf` function is so fast (relatively) nowadays that in a cold
path like this, we can liberally call it to convert back to `int`s.
This makes intermediate calculation more accurate and consistent.
* `GdiEngine::PaintBufferGridLines` was exception-unsafe due to its
use of a `std::vector` with catch clause and this PR fixes that.
Additionally, the vector was swapped out with a `til::small_vector`
to reduce …

Put the final touches on GDI's underlines

---

src/host/exe/exemain.cpp
src/host/telemetry.cpp
src/host/tracing.cpp
src/terminal/parser/tracing.cpp

17cc109 and e9de646 both made the same mistake: When cleaning up our
telemetry code they also removed the calls to `TraceLoggingRegister`
which also broke regular tracing. Windows Defender in particular uses
the "CookedRead" event to monitor for malicious shell commands.
This doesn't fix it the "right way", because destructors of statics
aren't executed when DLLs are unloaded. But I felt like that this is
fine because we have way more statics than that in conhost land,
all of which have the same kind of issue.

Add missing TraceLoggingRegister calls

---

src/host/readDataCooked.cpp
src/host/readDataCooked.hpp

This is just a minor, unimportant cleanup to remove code duplication
in `_flushBuffer`, which called `SetCursorPosition` twice each time
the cursor position changed.

COOKED_READ: A minor cleanup

---

src/terminal/parser/IStateMachineEngine.hpp
src/terminal/parser/InputStateMachineEngine.cpp
src/terminal/parser/InputStateMachineEngine.hpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp
src/terminal/parser/stateMachine.cpp
src/terminal/parser/ut_parser/StateMachineTest.cpp

Even with the previous fixes we still randomly encounter win32-
input-mode sequences that are broken up in exactly such a way that
e.g. lone escape keys are encounters. Those for instance clear the
current prompt. The remaining parts of the sequence are then visible.
This changeset fixes the issue by skipping the entire force-to-ground
code whenever we saw at least 1 win32-input-mode sequence.
Related to #16343
* Host a ConPTY inside ConPTY (= double the trouble) with cmd.exe
* Paste random amounts of text
* In the old code spurious `[..._` strings are seen
* In the new code they're consistently gone ✅

Fix parsing of chunked win32-input-mode sequences

---

.github/workflows/similarIssues.yml

The tolerance value for a similar issue was changed from 0.8 to 0.75.
This is because I changed the backend service for this to use pinecone instead of Azure AI search (see here https://github.com/craigloewen-msft/GitGudIssues/commit/f72fa59e23c0b7501b613daea95371cb13831d42 ) and the metric changed as a result of that. They are slightly lower than they were before, so this should offset that.
Small PR so only one change of a value.
Validated with the same calls to the Azure AI search and then to the new database to determine that minusing 0.05 would be sufficient.

Update similarIssues.yml to have a lower tolerance

---

.github/actions/spelling/expect/expect.txt
src/host/res.rc
src/host/resource.h
src/host/sources.inc
src/inc/conint.h
src/interactivity/win32/Clipboard.cpp
src/interactivity/win32/resource.h
src/interactivity/win32/ut_interactivity_win32/sources
src/internal/stubs.cpp
src/propsheet/sources
src/terminal/adapter/ut_adapter/sources
src/terminal/parser/ut_parser/sources

This pull request started out very differently. I was going to move all the EDP code from the internal `conint` project into the public, because EDP is [fully documented]!
Well, it doesn't have any headers in the SDK.
Or import libraries.
And it's got a deprecation notice:
> [!NOTE]
> Starting in July 2022, Microsoft is deprecating Windows Information
> Protection (WIP) and the APIs that support WIP. Microsoft will continue
> to support WIP on supported versions of Windows. New versions of Windows
> won't include new capabilities for WIP, and it won't be supported in
> future versions of Windows.
So I'm blasting it out the airlock instead.
[fully documented]: https://learn.microsoft.com/en-us/windows/win32/devnotes/windows-information-protection-api

Remove EDP auditing completely

---

src/terminal/input/mouseInput.cpp
src/terminal/input/terminalInput.cpp
src/terminal/input/terminalInput.hpp

This PR enables alternate scroll mode by default, and also fixes the
precedence so if there is any other mouse tracking mode enabled, that
will take priority.
I've manually tested by viewing a file with `less`, and confirmed that
it can now scroll using the mouse wheel by default. Also tested mouse
mouse in vim and confirmed that still works.

Enable alternate scroll mode by default

---

src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.cpp
src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.h
src/cascadia/TerminalSettingsEditor/ColorSchemeViewModel.idl
src/cascadia/TerminalSettingsEditor/EditColorScheme.xaml

In the Settings UI's Color Scheme page (where you edit the color scheme itself), update the color chip buttons to include the RGB value in the tooltip and screen reader announcements.
Closes #15985
Closes #15983
Tooltip and screen reader announcement is updated on launch and when a new value is selected.

Update SUI Color Scheme colors' AutoProp.Name and ToolTip

---

src/terminal/parser/OutputStateMachineEngine.cpp

Up to now we've using `U+2E2E` (reverse question mark) to represent the
`SUB` control glyph. This PR changes the glyph to `U+2426` (substitute
form two), which is also rendered as a reverse question mark, but is
more semantically correct.
The original `SUB` control rendering was implemented in PR #15075.
I've manually confirmed that `printf "\x1A"` is now shown as a reverse
question mark in OpenConsole when using the Cascadia Code font. That
would not previously have worked, because `U+2E2E` is not supported by
Cascadia Code.

Change the SUB control glyph to U+2426

---

src/cascadia/LocalTests_TerminalApp/pch.h
src/cascadia/TerminalApp/ColorHelper.cpp
src/cascadia/TerminalApp/ColorHelper.h
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h
src/cascadia/TerminalApp/Toast.h
src/cascadia/TerminalApp/pch.h
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/pch.h
src/cascadia/WinRTUtils/WinRTUtils.vcxproj
src/cascadia/WinRTUtils/WinRTUtils.vcxproj.filters
src/cascadia/WinRTUtils/inc/SafeDispatcherTimer.h
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h
src/cascadia/WindowsTerminal/pch.h
src/cascadia/ut_app/precomp.h

At the time of writing, closing the last tab of a window inexplicably
doesn't lead to the destruction of the remaining TermControl instance.
On top of that, on Win10 we don't destroy window threads due to bugs in
DesktopWindowXamlSource. In other words, we leak TermControl instances.
Additionally, the XAML timer class is "self-referential".
Releasing all references to an instance will not stop the timer.
Only calling Stop() explicitly will achieve that.
The result is that the message loop of a frozen window thread has so
far received 1-2 messages per second due to the blink timer not being
stopped. This may have filled the message queue and lead to bugs as
described in #16332 where keyboard input stopped working.

Avoid timer ticks on frozen windows

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/IControlSettings.idl
src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.h
src/cascadia/inc/ControlProperties.h

Avoid generating extra formatted copies when action's `copyFormatting` is not present and globally set `copyFormatting` is used.
Previously, when the action's `copyFormatting` wasn't set we deferred the decision of which formats needed to be copied to the `TerminalPage::CopyToClipboard` handler. This meant we needed to copy the text in all the available formats and pass it to the handler to copy the required formats after querying the global `copyFormatting`.
To avoid making extra copies, we'll store the global `copyFormatting` in TerminalSettings and pass it down to `TermControl`. If `ControlCore::CopySelectionToClipboard()` doesn't receive action specific `copyFormatting`, it will fall back to the global one _before generating the texts_.
- no `copyFormatting` set for the copy action: …

Avoid generating extra formatted copies when no action specific `copyFormatting` is set

---

src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/ut_adapter/adapterTest.cpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp

This PR adds support for more Device Status Report (`DSR`) queries,
specifically:
* Printer Status (`DSR ?15`)
* User Defined Keys (`DSR ?25`)
* Keyboard Status (`DSR ?26`)
* Locator Status (`DSR ?55`)
* Locator Identity (`DSR ?56`)
* Data Integrity (`DSR ?75`)
* Multiple Session Status (`DSR ?85`)
For most of these, we just need to return a `DSR` sequence indicating
that the functionality isn't supported.
* `DSR ?13` indicates that a printer isn't connected.
* `DSR ?23` indicates the UDK extension isn't supported.
* `DSR ?53` indicates that a locator device isn't connected
* `DSR ?57;0` indicates the locator type is unknown or not connected.
* `DSR ?83` indicates that multiple sessions aren't supported.
For the keyboard, we report `DSR ?27;0;0;5`, indicating a PC keyboard
(the `5` …

Add support for more DSR queries.

---

src/cascadia/TerminalSettingsEditor/Profiles_Advanced.xaml
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.xaml
src/cascadia/TerminalSettingsEditor/Profiles_Base.xaml

Fix overlapping disclaimer text in Profiles' Defaults section
[While removing ScrollViewer](https://github.com/microsoft/terminal/pull/16261) from the subpages in the settings UI, the main Grid child element order was not preserved and as a result, the disclaimer text overlapped with the main content on the page.
To fix that we now apply (the lost) `Grid.Row` property on the parent StackPanel of the main content.
- Disclaimer text does not overlap.

Fix overlapping disclaimer text in Profiles' Defaults section

---

src/cascadia/WindowsTerminal/WindowEmperor.cpp
src/cascadia/WindowsTerminal/WindowEmperor.h
src/cascadia/WindowsTerminal/main.cpp

This simplifies the function in two ways:
* Passing `nCmdShow` from `wWinMain` alleviates the need to interpret
the return value of `GetStartupInfoW`.
* `til::env::from_current_environment()` calls `GetEnvironmentStringsW`
to get the environment variables, while `to_string()` turns it back.
Calling the latter directly alleviates the need for this round-trip.

Simplify WindowEmperor::HandleCommandlineArgs

---

src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/host/ut_host/ScreenBufferTests.cpp
src/terminal/adapter/adaptDispatch.cpp

#15541 changed `AdaptDispatch::_FillRect` which caused it to not affect
the `ROW::_wrapForced` flag anymore. This change in behavior was not
noticeable as `TextBuffer::GetLastNonSpaceCharacter` had a bug where
rows of only whitespace text would always be treated as empty.
This would then affect `AdaptDispatch::_EraseAll` to accidentally
correctly guess the last row with text despite the `_FillRect` change.
#15701 then fixed `GetLastNonSpaceCharacter` indirectly by fixing
`ROW::MeasureRight` which now made the previous change apparent.
`_EraseAll` would now guess the last row of text incorrectly,
because it would find the rows that `_FillRect` cleared but still
had `_wrapForced` set to `true`.
This PR fixes the issue by replacing the `_FillRect` usage to clear
rows with direct calls to …

Reset _wrapForced when erasing scrollback

---

src/interactivity/win32/Clipboard.cpp
src/interactivity/win32/clipboard.hpp

conhost has 2 bugs related to clipboard handling:
* Missing retry on `OpenClipboard`: When copying to the clipboard
explorer.exe is very eager to open the clipboard and peek into it.
I'm not sure why it happens, but I can see `CFSDropTarget` in the
call stack. It uses COM RPC and so this takes ~20ms every time.
That breaks conhost's clipboard randomly during `ConsoleBench`.
During non-benchmarks I expect this to break during RDP.
* Missing null-terminator check during paste: `CF_UNICODETEXT` is
documented to be a null-terminated string, which conhost v2
failed to handle as it relied entirely on `GlobalSize`.
Additionally, this changeset simplifies the `HGLOBAL` code slightly
by adding `_copyToClipboard` to abstract it away.
* `ConsoleBench` (#16453) doesn't fail randomly anymore ✅
(cherry …

Fix conhost clipboard handling bugs

---

build/pipelines/templates-v2/pipeline-onebranch-full-release-build.yml

Due to things outside our control, sometimes the Package phase fails when VPack publication is enabled. Because of this, symbols won't be published. We still want these builds to be considered "golden" and we are still shipping them, so we *must* publish symbols.

build: remove symbols' dependency on the Package phase

---

dep/nuget/packages.config
src/common.nugetversions.targets
src/renderer/atlas/BackendD3D.cpp

This includes a fix for the hang on shutdown due to the folder change reader.
WIL now validates format strings in `LOG...` macros (yay!) and so we needed to fix
some of our `LOG` macros.
Closes #16456

Upgrade Microsoft.Windows.ImplementationLibrary to 1.0.240122.1

---

src/cascadia/WindowsTerminal/WindowEmperor.cpp

#16592 passes the return value of `GetEnvironmentStringsW` directly
to the `hstring` constructor even though the former returns a
double-null terminated string and the latter expects a regular one.
This PR fixes the issue by using a basic strlen() loop to compute
the length ourselves. It's still theoretically beneficial over
the previous code, but now it's rather bitter since the code isn't
particularly short anymore and so the biggest benefit is gone.
Closes #16623
* Validated the `env` string in a debugger ✅
It's 1 character shorter than the old `til::env` string.
That's fine however, since any `HSTRING` is always null-terminated
anyways and so we get an extra null-terminator for free.
* `wt powershell` works ✅

Fix a bug caused by #16592

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/interactivity/win32/Clipboard.cpp
src/interactivity/win32/clipboard.hpp
src/interactivity/win32/windowproc.cpp

TIL: You could Ctrl+V files into Windows Terminal and here I am,
always opening the context menu and selecting "Copy as path"... smh
This restores the support by adding a very rudimentary HDROP handler.
The flip side of the regression is that I learned about this and so
conhost also gets this now, because why not!
Closes #16627
* Single files can be pasted in WT and conhost ✅

Restore support for pasting files

---

src/interactivity/win32/Clipboard.cpp

#16618 contained a bug which was fixed inbox. This ports the
changes to the OSS repo manually since the two slightly diverged.

Port clipboard improvements from inbox to oss

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/DebugTapConnection.cpp
src/cascadia/TerminalApp/DebugTapConnection.h
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalConnection/AzureConnection.cpp
src/cascadia/TerminalConnection/AzureConnection.h
src/cascadia/TerminalConnection/BaseTerminalConnection.h
src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/ConptyConnection.h
src/cascadia/TerminalConnection/ConptyConnection.idl
src/cascadia/TerminalConnection/EchoConnection.h
src/cascadia/TerminalConnection/ITerminalConnection.idl
src/cascadia/TerminalConnection/TerminalConnection.vcxproj
src/cascadia/TerminalConnection/TerminalConnection.vcxproj.filters
src/cascadia/TerminalSettingsEditor/PreviewConnection.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
src/cascadia/TerminalSettingsModel/ApplicationState.cpp
src/cascadia/TerminalSettingsModel/ApplicationState.h
src/cascadia/TerminalSettingsModel/ApplicationState.idl
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/GlobalAppSettings.h
src/cascadia/UnitTests_Control/MockConnection.h
src/cascadia/WindowsTerminal/WindowEmperor.cpp
src/cascadia/WindowsTerminal/WindowEmperor.h
src/types/inc/utils.hpp
src/types/ut_types/UtilsTests.cpp
src/types/utils.cpp

This contains all the parts of #16598 that aren't specific to session
restore, but are required for the code in #16598:
* Adds new GUID<>String functions that remove the `{}` brackets.
* Adds `SessionId` to the `ITerminalConnection` interface.
* Flush the `ApplicationState` before we terminate the process.
* Not monitoring `state.json` for changes is important as it prevents
disturbing the session state while session persistence is ongoing.
That's because when `ApplicationState` flushes to disk, the FS
monitor will be triggered and reload the `ApplicationState` again.

General improvements in preparation for #16598

---

src/terminal/input/terminalInput.cpp

This fixes two issues where the `Space` key wasn't being handled
correctly:
* Keyboards with an `AltGr`+`Space` mapping were not generating the
expected character.
* Pressing a dead key followed by `Space` is supposed to generate the
accent character associated with that key, but it wasn't doing so.
These were both regressions from the keyboard refactor in PR #16511.
The problem was that we were treating `VK_SPACE` as a "functional" key,
which means it gets hardcoded VT mappings which take precedence over
whatever is in the keyboard layout. This was deemed necessary to deal
with the fact that many keyboards incorrectly map `Ctrl`+`Space` as a
`SP` character, when it's expected to be `NUL`.
I've now dropped `VK_SPACE` from the functional mapping table and allow
it be handled by the default …

Improve handling of Space key combinations

---

src/features.xml
src/terminal/input/terminalInput.cpp

DECKPAM originally tracked in #16506.
Support was added in #16511.
But turns out people didn't expect the Terminal to actually be like, compliant: #16654
This closes #16654 while we think over in #16672 how we want to solve this

Disable DECKPAM mode behind velocity

---

src/cascadia/TerminalCore/TerminalSelection.cpp

Hi,  I realized I had a bug in my pull request for search selections where when the highlight is wrapped it causes the selection to select back to start of the current line instead of wrapping to the next line.
PR where I introduced this bug.
https://github.com/microsoft/terminal/pull/16227

Fix for search selections highlight going backward when the selection wraps to next line

---

doc/cascadia/profiles.schema.json

Add experimental.repositionCursorWithMouse to profiles.schema.json.  So when editing settings.json with vscode, it autocompletes and don't complain.
Not really relevant, but how I found out this was missing: It was `experimental.moveCursorWithMouse` early in the feature implementation PR. I was in my personal list to check out the feature, finally I tried to test it today, couldn't make it work cause I was trying with `moveCursorWithMouse`. VScode also wasn't much help as `experimental.` autocomplete didn't contain this value. After looking over the PR thoroughly and the relevant docs PR I realized my mistake.
I set **$schema** to my patched one's url and vscode no longer complains about `experimental.repositionCursorWithMouse`. Autocompletes and also shows description on hover.
- If …

schema: add experimental.repositionCursorWithMouse

---

src/cascadia/QueryExtension/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Add the `experimental` tag to various locations where we refer to Terminal Chat
Settings UI navigation view:
Terminal Chat UI itself:
Dropdown:

Add experimental tags to Terminal Chat labels

---

src/host/readDataCooked.cpp

Write "<command that doesn't exist> foo" in cmd.exe, move yours cursor
past the <command> and press tab. The "foo" will still be there but
will be inaccessible. This commit fixes the issue. As far as I can
tell, this never worked in any conhost version ever.
Closes #16704

COOKED_READ: Fix tab not erasing the prompt

---

src/inc/til/bitmap.h

There's an apparent miscompilation of `dynamic_bitset` on x86 with
MSVC 19.38, where the following code:
```cpp
dynamic_bitset<uint64_t> bits(80 * 24, 0);
bits.set(0, 3 * 80, true);
```
is expected to set the first 3.75 blocks to 1 which should produce
the following blocks:
```
0xffffffffffffffff
0xffffffffffffffff
0xffffffffffffffff
0x0000ffffffffffff
```
but it actually produces:
```
0xffffffffffffffff
0x00000000ffffffff
0xffffffffffffffff
0x0000ffffffffffff
```
The weird thing here is that this only happens if `til::bitmap`
uses a `dynamic_bitset<uint64_t>`. As soon as it uses `<uint32_t>`
any other instantiation of `<uint64_t>` is magically fixed.
Conclusion: Use `size_t` until we know what's going on.
Last known good CL version: 14.37.32822
Current broken CL version: 14.38.33130
The …

Fix an apparent x86 miscompilation on MSVC 19.38

---

src/cascadia/QueryExtension/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Updating the resource strings to be in line with the mocks (capitalizing the "e", removing the unnecessary experimental tag in the dropdown)

Capitalize the 'e' in "experimental"

---

src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/BackendD3D.h
src/renderer/atlas/shader_ps.hlsl

This changeset makes 3 improvements:
* Dotted lines now use a 2:1 ratio between gaps and dots (from 1:1).
This makes the dots a lot easier to spot at small font sizes.
* Dashed lines use a 1:2 ratio and a cells-size independent stride.
By being cell-size independent it works more consistently with a
wider variety of fonts with weird cell aspect ratios.
* Curly lines are now cell-size independent as well and have a
height that equals the double-underline size.
This ensures that the curve isn't cut off anymore and just like
with dashed lines, that it works under weird aspect ratios.
Closes #16712
This was tested using RenderingTests using Cascadia Mono, Consolas,
Courier New, Lucida Console and MS Gothic.

AtlasEngine: Improve dotted, dashed and curly underlines

---

src/cascadia/LocalTests_SettingsModel/DeserializationTests.cpp
src/cascadia/LocalTests_SettingsModel/SerializationTests.cpp
src/cascadia/TerminalSettingsModel/ActionMap.h
src/cascadia/TerminalSettingsModel/ActionMapSerialization.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/Command.cpp
src/cascadia/TerminalSettingsModel/Command.h
src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp
src/cascadia/TerminalSettingsModel/GlobalAppSettings.h

Surprisingly easier than I thought this would be. ActionMap already supports layering (from defaults.json), so this basically re-uses a lot of that for fun and profit. 
The trickiest bits:
* In `SettingsLoader::_parseFragment`, I'm constructing a fake, empty JSON object, and taking _only_ the actions out from the fragment, and stuffing them into this temp json. Then, I parse that as a globals object, and set _that_ as the parent to the user settings file. That results in _only_ the actions from the fragment being parsed before the user's actions. 
* In that same method, I'm also explicitly preventing the ActionMap (et al.) from parsing `keys` from these actions. We don't want fragments to be able to say "ctrl+f is clear buffer" or something like that. This required a bit of annoying …

Add support for actions in fragments

---

src/buffer/out/Row.cpp

URL detection was broken again in #15858. When the regex matched, we calculate the column(cell) by its offset, we use forward or backward iteration of the column to find the correct column that displays the glyphs of `_chars[offset]`.
https://github.com/microsoft/terminal/blob/abf5d9423a23b13e9af4c19ca35858f9aaf0a63f/src/buffer/out/Row.cpp#L95-L104
However, when calculating the `currentOffset` we forget that MSB of `_charOffsets[col]` could be `1`, or col is pointing to another glyph in preceding column.
https://github.com/microsoft/terminal/blob/abf5d9423a23b13e9af4c19ca35858f9aaf0a63f/src/buffer/out/Row.hpp#L223-L226

Fix the hyperlink detection when there are leading wide glyph in the row

---

src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalSettingsEditor/Appearances.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/KeyChordSerialization.cpp
src/inc/til/env.h
src/inc/til/string.h
src/til/ut_til/string.cpp

`wstring_case_insensitive_compare` is not a great name for what it
does as it's incorrect to use for regular (human readable) strings.
This PR thus renames it to `env_key_sorter`.
`compare_string_ordinal` was renamed to `compare_ordinal_insensitive`
to make sure callers know that the comparison is insensitive
(this may otherwise be incorrect in certain contexts after all).
The return value was changed to match `memcmp` so that the API
is detached from its underlying implementation (= NLS).
`compare_linguistic_insensitive` and `contains_linguistic_insensitive`
were added to sort and filter human-readable strings respectively.
`prefix_split` was extended to allow for needles that are just a
single character. This significantly improves the generated assembly
and is also usually what someone …

Add new and extend existing til::string helpers

---

src/cascadia/TerminalSettingsEditor/Appearances.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp

This is just a minor cleanup I did as a drive-by while working on
customized font fallback. The benefit of this change is that it's
a tiny bit less expensive, but also that it's a lot easier to read.
The split into "get index" and "get string by index" helps us to
more easily handle both, missing locales and locale fallback.
The code that ties everything together then ends up being just 7 lines.

A minor cleanup of ProfileViewModel

---

src/buffer/out/Row.cpp
src/buffer/out/Row.hpp
src/buffer/out/ut_textbuffer/TextBuffer.Unit.Tests.vcxproj
src/buffer/out/ut_textbuffer/UTextAdapterTests.cpp
src/buffer/out/ut_textbuffer/sources
src/inc/til/point.h

Aside from overall simplifying `CharToColumnMapper` this fixes 2 bugs:
* The backward search loop may have iterated 1 column too far,
because it didn't stop at `*current <= *target`, but rather at
`*(current - 1) <= *target`. This issue was only apparent when
surrogate pairs were being used in a row.
* When the target offset is that of a trailing surrogate pair
the forward search loop may have iterated 1 column too far.
It's somewhat unlikely for this to happen since this code is
only used through ICU, but you never know.
This is a continuation of PR #16775.

Fix bugs in CharToColumnMapper

---

src/cascadia/TerminalSettingsEditor/Appearances.xaml

Make sure the delete button's `Tag` updates when the selected axis/feature changes, so that the correct key value gets propagated when the delete button is clicked.
Refs #16678 #16104 
1. Add a new feature/axis
2. Change the key
3. Click the delete button
4. Delete button works

Fix being unable to delete a changed Font Axis or Font Feature

---

build/rules/GenerateFeatureFlags.proj

Welp, would you look at that? We never actually supported "canary" feature settings. Canary's been defaulting to the "Dev" config since inception. 
There's a couple things that are supposed to only be on in Dev and not Canary. They clearly haven't mattered but better safe than sorry

Fix the velocity script to actually support canary

---

src/renderer/vt/paint.cpp

When using the legacy console APIs, it's possible to write arbitrary
codepoints into the buffer. If any of those codepoints are in the C0 or
C1 range, and the buffer contents are forwarded over conpty, they can
end up mistakenly interpreted as controls by the connected terminal.
This PR fixes that issue by converting any C0 and C1 codepoints in the
buffer into printable glyphs before forwarding them over conpty. I've
used the C0 glyphs from the DOS 437 codepage and just a `?` for the C1
codepoints, since that's what you would typically have seen in the v1
console with a raster font.
Although this doesn't address the main problem in #16410, it should at
least fix the rendering issues they're seeing when running their app in
Windows Terminal.
I've confirmed that the test case in #4363 now …

Fix conpty rendering of control characters in the buffer

---

src/cascadia/TerminalApp/CommandPalette.cpp

As mentioned in the issue [#11146](https://github.com/microsoft/terminal/issues/11146), when the "Next/Prev"  command is executed from the command line with a string in the search bar, this is setting always the first tab.
#11146 
When using the command "Next/Previous Tab" from the command line, we are creating another tab (as if we are using the keyboard shortcut), and this triggers the `_filterTextChanged` that resets the index to the first item in because the current mode that it has.
This could be cause because, It seems that it detects as if we are deleting the entered letter or creating an empty string, causing the execution of the mentioned method and resetting its index to 0.
To avoid this, we are making sure that when this action is triggerd and we are in the `TabSwitchMode`, we …

Update CommandPalette.cpp to ignore _filterTextChanged on TabSwitchMode

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/IControlSettings.idl
src/cascadia/TerminalSettingsEditor/Appearances.h
src/cascadia/TerminalSettingsEditor/Appearances.idl
src/cascadia/TerminalSettingsEditor/Appearances.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/FontConfig.idl
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.h
src/cascadia/inc/ControlProperties.h
src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/BackendD2D.cpp
src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/common.h
src/renderer/base/FontInfoDesired.cpp
src/renderer/inc/FontInfoDesired.hpp

This pull request introduces support for disabling full-color emoji (and technically other COLR-related font features!)
Full-color emoji don't respond to SGR colors, intensity, faint or blink. Some users also just prefer the line art ones.
Related to #15979
Refs #1790
Closes #956

Add support for turning off full-color Emoji

---

src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml

This commit adds some styles to SettingContainer that can be used to display informational messages. They don't have reset buttons or content and they can't be interacted with.
I did this because the InfoBars didn't scale properly when the window was wide. Also they had an [X] button that hid the warning but didn't persist that they had been hidden or anything.

Add SettingContainer Warning/Error styles to replace InfoBar

---

src/cascadia/TerminalSettingsEditor/Appearances.idl
src/cascadia/TerminalSettingsEditor/Appearances.xaml
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.idl
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.xaml
src/cascadia/UIHelpers/Converters.cpp
src/cascadia/UIHelpers/Converters.h
src/cascadia/UIHelpers/Converters.idl

I thought the Converters.idl file had a really neat ordering,
and I felt like the .cpp implementation fell short of this.
This PR reorders the functions in the implementation to match the IDL.
It also gets rid of some unnecessary math (int vs. float, clamping)
and removes another use of `std::stringstream` (= bad STL class).

Clean up the Converters implementation

---

.github/actions/spelling/expect/expect.txt
src/host/ft_host/CJK_DbcsTests.cpp
src/host/output.cpp

The `nLength` parameter of `ReadConsoleOutputCharacterW` indicates
the number of columns that should be read. For single-column (narrow)
surrogate pairs this previously clipped a trailing character of the
returned string. In the major Unicode support update in #13626
surrogate pairs truly got stored as atomic units for the first time.
This now meant that a 120 column read with such codepoints resulted
in 121 characters. Other parts of conhost still assume UCS2 however,
and so this results in the entire read failing.
This fixes the issue by turning surrogate pairs into U+FFFD
which makes it UCS2 compatible.
Closes #16892
* Write U+F15C0 and read it back with `ReadConsoleOutputCharacterW`
* Read succeeds with a single U+FFFD ✅

Fix a ReadConsoleOutputCharacter regression

---

build/pipelines/templates-v2/variables-onebranch-config.yml

The 14.39 compiler seems pretty busted.
Refs #16794

build: roll back to a build container with the 14.38 compiler

---

src/cascadia/TerminalSettingsModel/Command.cpp
src/cascadia/TerminalSettingsModel/KeyChordSerialization.cpp
src/inc/til.h
src/inc/til/bytes.h
src/inc/til/replace.h
src/inc/til/type_traits.h
src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/BackendD3D.h
src/til/ut_til/ReplaceTests.cpp
src/types/colorTable.cpp

When no soft fonts are set up but we're asked to draw a U+EF20, etc.,
character we'll currently read out-of-bounds, because we don't check
whether the soft fonts array is non-empty. This PR fixes the issue by
first getting a slice of the data and then checking if it's ok to use.
This changeset additionally fixes a couple constinit vs. constexpr
cases. I changed them to constinit at some point because I thought
that it's more constexpr than constexpr by guaranteeing initialization
at compile time. But nope, constinit is actually weaker in a way,
because while it does guarantee that, it doesn't actually make the
data constant. In other words, constinit is not `.rdata`.

AtlasEngine: Fix a OOB read when rendering PUA chars

---

src/common.build.pre.props

This makes the build a tiny bit faster (less time spent linking)
and makes everything run roughly 50% faster.

Enable /Ob1 in Debug builds

---

build/pipelines/daily-loc-submission.yml
build/scripts/Generate-PseudoLocalizations.ps1
scratch/ScratchIslandApp/Package/Resources/qps-ploc/Resources.resw
scratch/ScratchIslandApp/Package/Resources/qps-ploca/Resources.resw
scratch/ScratchIslandApp/Package/Resources/qps-plocm/Resources.resw
src/cascadia/CascadiaPackage/Resources/qps-ploc/Resources.resw
src/cascadia/CascadiaPackage/Resources/qps-ploca/Resources.resw
src/cascadia/CascadiaPackage/Resources/qps-plocm/Resources.resw
src/cascadia/TerminalApp/Resources/qps-ploc/ContextMenu.resw
src/cascadia/TerminalApp/Resources/qps-ploc/Resources.resw
src/cascadia/TerminalApp/Resources/qps-ploca/ContextMenu.resw
src/cascadia/TerminalApp/Resources/qps-ploca/Resources.resw
src/cascadia/TerminalApp/Resources/qps-plocm/ContextMenu.resw
src/cascadia/TerminalApp/Resources/qps-plocm/Resources.resw
src/cascadia/TerminalConnection/Resources/qps-ploc/Resources.resw
src/cascadia/TerminalConnection/Resources/qps-ploca/Resources.resw
src/cascadia/TerminalConnection/Resources/qps-plocm/Resources.resw
src/cascadia/TerminalControl/Resources/qps-ploc/Resources.resw
src/cascadia/TerminalControl/Resources/qps-ploca/Resources.resw
src/cascadia/TerminalControl/Resources/qps-plocm/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/qps-ploc/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/qps-ploca/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/qps-plocm/Resources.resw
src/cascadia/TerminalSettingsModel/Resources/qps-ploc/Resources.resw
src/cascadia/TerminalSettingsModel/Resources/qps-ploca/Resources.resw
src/cascadia/TerminalSettingsModel/Resources/qps-plocm/Resources.resw
tools/ConvertTo-PseudoLocalization.ps1

It appears as if our official ploc translations use a per-file hash
as the seed for generating random pseudo-localization characters.
This works poorly for us since we have these translations hooked up
to our CI to submit PRs with the latest changes. We do want to get
the latest proper translations but merging 1000s of lines of ploc
changes every time is unneccessary.
This PR replicates LocStudio's pseudo-localizations in PowerShell
but it uses a per-key seed for the RNG.

Make ploc translations predictable

---

src/features.xml

One of the DSB requirements for Terminal AI was the check for a jailbreak filter. The code for this merged a while back and was put behind a velocity flag, this PR turns it on.

Enable the check for the jailbreak filter

---

build/pipelines/templates-v2/job-deploy-to-azure-storage.yml

This is required for us to move off Entra ID Application identity.

Move to AzureFileCopy@6 for Managed Identity support

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Fixes "Align 'Run this profile as Administrator' Settings Description with Microsoft Style Guidelines" #16946 
Expanded the contraction "it'll" to "it will" on line 993 of `src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw`
N/A
- No tests were added
- No documentation was updated
- No schema was updated

Replace 'it'll' with 'it will' to adhere to Microsoft Style Guidelines

---

src/buffer/out/TextColor.cpp
src/buffer/out/textBuffer.cpp
src/host/directio.cpp
src/host/inputBuffer.cpp
src/inc/consoletaeftemplates.hpp
src/inc/til/bit.h

The former was introduced when we were still using C++17.
We're using C++20 now so it's not needed anymore.

Replace til::bit_cast with std::bit_cast

---

src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/WindowsTerminal/WindowEmperor.cpp

Basically, title. 
It'd be a neat idea for portable installs of the Terminal to reference files that are right there in the portable install.
This PR adds a `WT_SETTINGS_DIR` var to Terminal's own env block. This allows us to resolve profiles relative to our own settings folder. 
Closes #16295

Add a WT_SETTINGS_DIR env variable that portable profiles can use

---

src/renderer/vt/invalidate.cpp
src/renderer/vt/paint.cpp
src/renderer/vt/state.cpp
src/renderer/vt/vtrenderer.hpp

I've found that #16079 was never properly addressed (it still randomly
occurred after even after PR #16349), which later led to the issues
described in #16769 (nushell flickering due to too many flushes).
The crux of the fix is that this brings back the `_noFlushOnEnd` flag
that was removed in PR #15991. This is then combined with a change to
the cork API: An `uncork` on `VtEngine` now only flushes if `_Flush`
got called while it was corked in the first place.
`_noFlushOnEnd` prevents us from flushing in between two "unknown"
VT sequences (like soft fonts or FTCS) which prevents them from being
corrupted. The corking prevents the remaining cases of flushing too
often. Long-term, a proper fix would be to pass through VT unmodified.
Closes #16769

Properly fix ConPTY buffer corking

---

src/cascadia/TerminalSettingsEditor/Appearances.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.h

* Since `FindFontWithLocalizedName` is broken (intentionally and
temporarily until #16943 is fixed) we have to be extra be careful
not to return a nullptr `Font`.
* Portable builds may not have a broken font cache, but also not have
the given font (Cascadia Mono for instance) installed. This requires
us to load the nearby fonts even if there aren't any exceptions.
* Open `src/cascadia/CascadiaResources.build.items`
and remove the `Condition` for .ttf files
* Deploy on a clean Windows 10 VM
* Cascadia Mono loads without issues ✅
* Open the `Settings > Defaults > Appearance`,
enter a non-existing font and hit Save

Fix bugs introduced in #16821 (custom font fallback)

---

src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp
src/cascadia/UnitTests_SettingsModel/DeserializationTests.cpp

This clamps the initial rows and columns settings in two areas:
- When reading the JSON file
- In the settings dialogue
For consistency, I've also added a minimum value to the NumberBoxes even
though the default Minimum is 1. The Maximum and Minimum are taken from
the JSON Schema file (Min 1, Max 999).
Closes #11957

Add clamping of initial rows and columns settings

---

src/buffer/out/textBuffer.cpp

Closes #16782
- Double-clicking on a Double-Width row selects the word (identified by delimiters) under the cursor.
- Tripple-clicking on a Double-Width row selects the whole line under the cursor.
- The same works for Double-Height rows also.
- The same works for Single-Width rows also.

Fix selection expansion for Double-Width and Double-Height rows

---

src/buffer/out/textBuffer.cpp

I forgot to `buffer.clear()` after a write. Whoops.
This includes 2 additional, smaller improvements that I just happened
to notice: The `GenRTF` code calls `to_string` despite using `fmt`.

Buffer Restore: Fix serializing >32KiB

---

src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/TerminalSettingsModel/Profile.cpp
src/features.xml

* Switches the marks feature to being stable. 
* Renames the settings, to remove "experimental."
Stacked on top of #16937, so that we actually finish reflow before merging this. 
Closes #15057

Make marks a stable feature

---

src/cascadia/UnitTests_SettingsModel/ProfileTests.cpp

Adding more profile GUID tests
Closes #2119 
Currently, there are formats that simply break GUID parsing (the commented out test cases). Should we catch that and treat it like a "null" GUID or should we generate a new GUID for those profiles?

Add more profile GUID tests

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/EventArgs.cpp
src/cascadia/TerminalControl/EventArgs.h
src/cascadia/TerminalControl/EventArgs.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/host/outputStream.cpp
src/host/outputStream.hpp
src/terminal/adapter/ITermDispatch.hpp
src/terminal/adapter/ITerminalApi.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/termDispatch.hpp
src/terminal/adapter/ut_adapter/adapterTest.cpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp

In the spirit of #15360 this implements the copy part.
The problem is that we have an issue accessing the clipboard while
other applications continue to work just fine. The major difference
between us and the others is that we use the WinRT clipboard APIs.
So, the idea is that we just use the Win32 APIs instead.
The feel-good side-effect is that this is (no joke) 200-1000x faster,
but I suspect no one will notice the -3ms difference down to <0.01ms.
The objective effect however is that it just works.
This may resolve #16982.
* Cycle through Text/HTML/RTF-only in the Interaction settings
* Paste the contents into Word each time
* Text is plain and HTML/RTF are colored ✅

Replace WinRT clipboard API with Win32 for copying

---

src/cascadia/TerminalApp/MinMaxCloseControl.cpp

Closes: #13961
This PR changes the window styling we use under the minimized state. We now retain the active window styling so the content's height doesn't change when switching between minimized and maximized states.
- Open Terminal and go into Maximized mode.
- Click on the Minimize button.
- No `SizeChanged` event in `ControlCore`.
- Click on the WT icon in the taskbar to restore it.
- No `SizeChanged` event in `ControlCore`.

Fix window style under minimized state

---

src/cascadia/TerminalApp/TabManagement.cpp

Closes: #17032
We were wrongly calling the Ctor of CommandPalette which led to the creation of an uninitialized winrt command palette object, and then OnCreateAutomationPeer() was called on that. This seems to be the cause of #17032.
- Open WT.
- Try to tear off a tab out of the tab headers view.
- WT doesn't crash.

Fix wrong CommandPallete access

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.idl
src/cascadia/TerminalApp/TerminalWindow.h
src/cascadia/TerminalApp/TerminalWindow.idl
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h

This got lost in #16598. `TerminalPage` needs to ask the window where the it actually is, so it can persist it. More details in https://github.com/microsoft/terminal/pull/16598#discussion_r1511519304
Closes #17010

Also remember to persist window positions

---

src/host/_output.cpp
src/host/misc.cpp
src/host/tracing.hpp
src/propsheet/console.h
src/server/ApiDispatchers.cpp

More TraceLogging = More better?
I made this change as I noticed that most calls are not being logged.
Even after this change some crucial information won't be logged
(for instance arrays of `INPUT_RECORD`), because I couldn't come up
with a clever way to do so, but I think this is better than nothing.

Add more TraceLogging to ApiDispatchers

---

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
src/cascadia/WindowsTerminal/NonClientIslandWindow.h

Because this holds onto the root element, `TerminalPage` gets "leaked"
on Windows 10 when a window is closed until another is opened.
* Set a breakpoint in `Renderer::~Renderer`
* Open and close a window
* Breakpoint used to not get hit and now it does ✅

Fix TerminalPage not being released on window close

---

src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/BackendD3D.h
src/renderer/atlas/common.h

Since floats are imprecise we need to constrain the time value into a
range that can be accurately represented. Assuming a monitor refresh
rate of 1000 Hz, we can still easily represent 1000 seconds accurately
(roughly 16 minutes). So to solve this, we'll simply treat the shader
time modulo 1000s. This may lead to some unexpected jank every 16min
but it keeps any ongoing animation smooth otherwise.

AtlasEngine: Fix custom shader time imprecision

---

src/buffer/out/search.cpp
src/buffer/out/search.h
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalSelection.cpp
src/cascadia/TerminalCore/terminalrenderdata.cpp
src/cascadia/UnitTests_TerminalCore/ScrollTest.cpp
src/host/renderData.cpp
src/host/renderData.hpp
src/host/ut_host/VtIoTests.cpp
src/interactivity/onecore/BgfxEngine.cpp
src/interactivity/onecore/BgfxEngine.hpp
src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/base/renderer.cpp
src/renderer/base/renderer.hpp
src/renderer/dx/DxRenderer.cpp
src/renderer/dx/DxRenderer.hpp
src/renderer/gdi/gdirenderer.hpp
src/renderer/gdi/paint.cpp
src/renderer/inc/IRenderData.hpp
src/renderer/inc/IRenderEngine.hpp
src/renderer/uia/UiaRenderer.cpp
src/renderer/uia/UiaRenderer.hpp
src/renderer/vt/paint.cpp
src/renderer/vt/vtrenderer.hpp
src/renderer/wddmcon/WddmConRenderer.cpp
src/renderer/wddmcon/WddmConRenderer.hpp

This wasn't guarded under velocity, and some of the fixes are coming in too hot to be serviced into 1.20.
Reverts PR #16227 and #16691

[1.20] Revert search result highlighting from stable

---

src/cascadia/TerminalApp/TerminalPage.cpp

I forgot to check here if the `INewContentArgs` were null or not. Pretty dumb mistake honestly.
Closes #17075
Closes #17076

Don't explode when duplicating a pane

---

src/buffer/out/search.cpp
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/EventArgs.cpp
src/cascadia/TerminalControl/EventArgs.h
src/cascadia/TerminalControl/EventArgs.idl
src/cascadia/TerminalControl/SearchBoxControl.cpp
src/cascadia/TerminalControl/SearchBoxControl.h
src/cascadia/TerminalControl/SearchBoxControl.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/host/outputStream.cpp
src/host/outputStream.hpp
src/inc/til/throttled_func.h
src/interactivity/win32/find.cpp
src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/base/RenderEngineBase.cpp
src/renderer/base/renderer.cpp
src/renderer/inc/IRenderEngine.hpp
src/renderer/inc/RenderEngineBase.hpp
src/terminal/adapter/ITerminalApi.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/ut_adapter/adapterTest.cpp

This PR extends `til::throttled_func` to also support debouncing:
* throttling: "At most 1 call every N seconds"
* debouncing: "Exactly 1 call after N seconds of inactivity"
Based on the latter the following series of changes were made:
* An `OutputIdle` event was added to `ControlCore` which is
raised once there hasn't been any incoming data in 100ms.
This also triggers an update of our regex patterns (URL detection).
* The event is then caught by `TermControl` which calls `Search()`.
* `Search()` in turn was modified to return its results by-value
as a struct, which avoids the need for a search-update event
and simplifies how we update the UI.
This architectural change, most importantly the removal of the
`TextLayoutUpdated` event, fixes a DoS bug in Windows Terminal:
As the event leads …

Fix search highlights during reflow

---

src/cascadia/TerminalConnection/AzureConnection.cpp

Updates the `api-version` to `2023-02-01-preview` when requesting for CloudShell settings and shell
Can still use Azure Cloud Shell through Windows Terminal

Update Azure Cloud Shell API to the newer version

---

build/pipelines/templates-v2/job-deploy-to-azure-storage.yml

This is required for us to move off Entra ID Application identity.
(cherry picked from commit 2e7c3fa3132fa3bff23255480c593cbd3432eee5)
This was approved in #16957, so I will merge with one signoff.

[REPLAY] Move to AzureFileCopy@6 for Managed Identity support

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/Resources/en-US/Resources.resw
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

This adds a system message which displays the time at which the
buffer snapshot was written to disk.
Additionally, this PR moves the snapshot loading into a background
thread, so that the UI thread is unblocked and that multiple
tabs/panes can load simultaneously.
Closes #17031
Closes #17074
Repeatedly closing and opening WT adds more and more messages.
Currently, the messages get somewhat corrupted due to a bug
in our line-wrap handling, or some similar part.

Add a system message to session restore

---

src/cascadia/TerminalApp/TerminalWindow.cpp

While I was fixing the initial position thing, I figured I'd fix this too. We were mistakenly accounting for the size of the titlebar when we should launch into focus mode (without one)
Closes #10730

Fix persisting the size of a focus mode window

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h

This shouldn't have ever worked...? This looks like it was a typo and should have been `mark.end`. 
Thanks @joadoumie for asking about the moving the cursor in the prompt, that convo lead to me finding this.

Fix repositioning with the cursor, again

---

src/renderer/vt/XtermEngine.cpp
src/renderer/vt/state.cpp
src/renderer/vt/vtrenderer.hpp

When the conpty renderer determines that it needs to hide the cursor,
it does so by inserting a `DECTCEM` reset sequence at the start of the
output buffer, assuming that is the start of the frame. But when the
`_noFlushOnEnd` flag is set, you can have multiple frames pending in the
buffer, and the `DECTCEM` sequence will then end up in the wrong place.
This PR fixes the issue by saving the buffer size at the start of the
frame, and using that saved offset as the insert position for the
`DECTCEM` sequence.
I have a game that was frequently affected by this issue (the cursor
would be visible when it was meant to be hidden). With this PR applied,
it now works perfectly.

Fix the DECTCEM reset position in the conpty stream

---

src/buffer/out/UTextAdapter.cpp
src/buffer/out/UTextAdapter.h
src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/cascadia/TerminalCore/Terminal.cpp

This PR achieves two things:
* When encountering rows with newlines (`WasForceWrapped` = `false`)
we'll now copy the contents out of the row and append a `\n`.
To make `utext_clone` cheap, it adds a reference counted buffer.
* Text extraction in `Terminal::GetHyperlinkAtBufferPosition`
was fixed by using a higher level `TextBuffer::GetPlainText`
instead of iterating through each cell.
Closes #16676
Closes #17065
* In pwsh execute the following:
``"`e[999C`e[22Dhttps://example.com/foo`nbar"``
* Hovering over the URL only underlines `.../foo` and not `bar` ✅
* The tooltip ends in `.../foo` and not `.../fo` ✅

Make UTextFromTextBuffer newline aware

---

build/pipelines/templates-v2/job-build-project.yml
build/scripts/Set-LatestVCToolsVersion.ps1
src/interactivity/onecore/SystemConfigurationProvider.cpp

build: force the latest VCToolsVersion; see DD-1541167 for more

---

src/buffer/out/search.cpp
src/buffer/out/search.h
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/TermControl.cpp
src/host/ut_host/SearchTests.cpp
src/interactivity/win32/find.cpp
src/types/UiaTextRangeBase.cpp

This addresses a review comment left by tusharsnx in #17092 which I
forgot to fix before merging the PR. The fix itself is somewhat simple:
`Terminal::SetSearchHighlightFocused` triggers a scroll if the target
is outside of the current (scrolled) viewport and avoiding the call
unless necessary fixes it. To do it properly though, I've split up
`Search::ResetIfStale` into `IsStale` and `Reset`. Now we can properly
detect staleness in advance and branch out the search reset cleanly.
Additionally, I've taken the liberty to replace the `IVector` in
`SearchResultRows` with a direct `const std::vector&` into `Searcher`.
This removes a bunch of code and makes it faster to boot.
* Print lots of text
* Search a common letter
* Scroll up
* Doesn't scroll back down ✅
* Hold enter to search more …

Fix search constantly triggering a scroll

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlSettings.h
src/cascadia/TerminalControl/IControlSettings.idl
src/cascadia/TerminalSettingsEditor/Appearances.cpp
src/cascadia/TerminalSettingsEditor/Appearances.h
src/cascadia/TerminalSettingsEditor/Appearances.idl
src/cascadia/TerminalSettingsEditor/Appearances.xaml
src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/FontConfig.cpp
src/cascadia/TerminalSettingsModel/FontConfig.h
src/cascadia/TerminalSettingsModel/FontConfig.idl
src/cascadia/TerminalSettingsModel/JsonUtils.h
src/cascadia/TerminalSettingsModel/TerminalSettings.h
src/cascadia/UnitTests_Control/MockControlSettings.h
src/cascadia/UnitTests_SettingsModel/SerializationTests.cpp
src/cascadia/ut_app/JsonUtilsTests.cpp
src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.h

Due to #16821 everything about #16104 broke. This PR rights the wrongs
by rewriting all the `Font`-based code to not use `Font` at all.
Instead we split the font spec once into font families, do a lot of
complex logic to split font axes/features into used and unused ones
and construct all the UI elements. So. much. boilerplate. code.
Closes #16943
There are more edge cases than I can list here... Some ideas:
* Edit the settings.json with invalid axis/feature keys ✅
* ...out of range values ✅
* Settings UI reloads when the settings.json changes ✅
* Adding axes/features works ✅
* Removing axes/features works ✅
* Resetting axes/features works ✅
* Axes/features apply in the renderer when saving ✅

Fix font axes/features settings UI

---

.github/actions/spelling/allow/microsoft.txt
build/pipelines/ob-nightly.yml
build/pipelines/ob-release.yml
build/pipelines/templates-v2/job-build-package-wpf.yml
build/pipelines/templates-v2/job-build-project.yml
build/pipelines/templates-v2/job-merge-msix-into-bundle.yml
build/pipelines/templates-v2/job-package-conpty.yml
build/pipelines/templates-v2/pipeline-full-release-build.yml
build/pipelines/templates-v2/pipeline-onebranch-full-release-build.yml

This required me to push a bunch more parameters through the build pipeline, but it gave me the opportunity to define them as variables that can be set at queue time.

build: switch to ESRP v5, which supports managed identities

---

src/cascadia/TerminalApp/TerminalTab.cpp

Re-add some machinery to special case settings tabs. When we're going to persist a tab that only has a single settings pane in it, we'll now promote that to the first-class "openSettings" action. This will allow our other code in TerminalPage to route multiple settings tabs all to the same tab. 
This of course doesn't stop you from opening multiple settings tabs with `{ "command": {"action": "newTab", "type": "settings"} }` actions. If we did that, then that would prevent someone from having a settings pane in the first pane, and a terminal to the right. 
Closes #17070

Prevent multiple settings tabs from being persisted

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalSettingsEditor/Appearances.cpp
src/cascadia/TerminalSettingsEditor/Appearances.h
src/cascadia/TerminalSettingsEditor/Appearances.xaml
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.cpp
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.h

Something something code changes, fixes issue. Events need throwing,
some events don't need throwing, some events need throttling to
not overwhelm the flurble function within the gumbies component.
This is all boilerplate and it works now.
Closes #17171
Closes #17172
* Resetting the font axis/feature expander keeps
the add new button flyout sorted ✅
* Changing a font axis/feature value updates the preview ✅
* After changing the font, features/axes can still be edited ✅

Fix font axis/feature SUI issues

---

.github/actions/spelling/allow/allow.txt
src/buffer/out/textBuffer.cpp
src/host/ut_host/TextBufferTests.cpp

Take wrapping into account when expanding wordwise selections

---

doc/cascadia/profiles.schema.json

Noticed all these while prepping for Build:
* Promotes the stabilized features out of `experimental.`
* fixes a bug where a nested command with a `name` would match to a `renameWindow` action, instead of a command. 
* Adds the tab theme icon style
* fixes a bug where `ScrollToMarkAction` wasn't in the list of possible args, so they would incorrectly get flagged as `moveTab` 
* outright adds `experimental.rightClickContextMenu` which was missing (?)

Some schema updates for 1.21

---

src/host/alias.cpp
src/host/alias.h
src/host/ut_host/AliasTests.cpp
src/inc/til.h
src/renderer/atlas/BackendD3D.cpp

Initially the PR restored the original v1 conhost code for
`MatchAndCopyAlias` which fixed the linked issue.
Afterwards, I've taken the liberty to rewrite the code to use modern
constructs again, primarily `string_view`. Additionally, the v1 code
first counted the number of arguments and then iterated through it
again to assemble them. This new code does both things at once.
Closes #15736
The unit tests have been extended to cover multiple consecutive
spaces. All tests pass.

Fix doskey macros for inputs with >1 consecutive whitespace

---

src/buffer/out/textBuffer.cpp

It may be more accurate to say: "Fix _known_ remaining buffer
serialization bugs", but I'll try to be positive about my code.
Initially, the buffer is initialized with the default attributes,
but once it begins to scroll, newly scrolled in rows are initialized
with the current attributes. This means we need to set the current
attributes to those of the upcoming row before the row comes up.
This is related to #17074.
* Persist and restore a buffer 10 times
* All previous "Restore" status messages look correct ✅
* The escape sequences in the buffer file look correct ✅

Fix remaining buffer serialization bugs

---

src/renderer/base/renderer.cpp
src/renderer/base/renderer.hpp
src/renderer/inc/CursorOptions.h

There were multiple bugs:
* GDI engine only paints whatever has been invalidated.
This means we need to not just invalidate the old cursor rect
but also the new one, or else movements may not be visible.
* The composition should be drawn at the cursor position even if
the cursor is invisible, but inside the renderer viewport.
* Conceptually, scrolling the viewport moves the relative cursor
position even if the cursor is invisible.
* An invisible cursor is not the same as one that's outside the
viewport. It's more like a cursor that's not turned on.
To resolve the first issue we simply need to call `InvalidateCursor`
again. To do so, it was abstracted into `_invalidateCurrentCursor()`.
The next 2 issues are resolved by un-`optional`-izing `CursorOptions`.
After all, even an invisible or an …

Fix multiple cursor invalidation issues

---

src/cascadia/TerminalControl/TermControl.cpp
src/renderer/atlas/AtlasEngine.r.cpp
src/renderer/atlas/BackendD2D.cpp
src/renderer/atlas/BackendD2D.h

This fixes:
* `HRESULT`s not being shown as unsigned hex
* `D2DERR_RECREATE_TARGET` not being handled
* 4 calls not checking their `HRESULT` return
Out of the 4 only `CreateCompatibleRenderTarget` will throw in
practice, however it throws `D2DERR_RECREATE_TARGET` which is common.
Without this error handling, AtlasEngine may crash.
* Set Graphics API to Direct2D
* Use `DXGIAdapterRemovalSupportTest.exe` to trigger
`D2DERR_RECREATE_TARGET`
* No error message is shown ✅
* If the `D2DERR_RECREATE_TARGET` handling is removed, the application
never crashes due to `cursorRenderTarget` being `nullptr` ✅

AtlasEngine: Fix several error handling bugs

---

src/renderer/vt/XtermEngine.cpp
src/renderer/vt/XtermEngine.hpp
src/renderer/vt/vtrenderer.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/parser/IStateMachineEngine.hpp
src/terminal/parser/InputStateMachineEngine.cpp
src/terminal/parser/InputStateMachineEngine.hpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp
src/terminal/parser/ut_parser/StateMachineTest.cpp

When the `DCS` passthrough code was first implemented, it relied on the
`ActionPassThroughString` method flushing the given string immediately.
However, that has since stopped being the case, so `DCS` operations end
up being delayed until the entire sequence has been parsed.
This PR fixes the issue by introducing a `flush` parameter to force an
immediate flush on the `ActionPassThroughString` method, as well as the
`XtermEngine::WriteTerminalW` method that it calls.
I've confirmed that the test case in issue #17111 now updates the color
table as soon as each color entry is parsed, instead of delaying the
updates until the end of the sequence.
Closes #17111

Make sure DCS strings are flushed to conpty without delay

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/TermControl.cpp

We use `if (auto self = weakSelf.get())` in a lot of places.
That assigns the value to `self` and then checks if it's truthy.
Sometimes we need to add a "is (app) closing" check because XAML,
so we wrote something akin to `if (self = ...; !closing)`.
But that's wrong because the correct `if (foo)` is the same as
`if (void; foo)` and not `if (foo; void)` and that meant that
we didn't check for `self`'s truthiness anymore.
This issue became apparent now, because we added a new kind of
delayed callback invocation (which is a lot cheaper).
This made the lack of a `nullptr` check finally obvious.

Add nullptr checks to shared_ptr conversions

---

src/cascadia/TerminalApp/TerminalWindow.cpp
src/cascadia/TerminalApp/TerminalWindow.h
src/cascadia/TerminalApp/TerminalWindow.idl
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/WindowEmperor.cpp
src/cascadia/WindowsTerminal/WindowEmperor.h

This fixes 2 bugs:
* `PersistState` being called when the window is closed
(as opposed to closing the tab). The settings check was missing.
* Session cleanup running depending on whether the feature is
currently enabled as opposed to whether it was enabled on launch.
Closes #17206
Closes #17207
* Create a bunch of leftover buffer_*.txt files by running
the current Dev version off of main
* Build this branch, then open and close a window
* All buffer_*.txt are gone and state.json is cleaned up ✅

Fix session being persisted even when disabled

---

src/tsf/Implementation.cpp

On Windows 10 Emojis don't finish composition until the Emoji picker
panel is closed. Each emoji is thus its own composition range.
`firstRange` thus caused only the first emoji to finish composition.
The end result was that all remaining emojis would stay around
forever, with the user entirely unable to clear them.
* Windows 10 VM
* Open Emoji picker (Win+.)
* Press and hold Enter on any Emoji
* Press Esc to finish the composition
* All of the Emoji can be backspaced / deleted

Fix typing multiple emojis on Windows 10

---

src/cascadia/TerminalSettingsModel/Command.cpp

Fix Terminal crashing when experimental PowerShell menu completion is very quickly invoked multiple times.
`Command::ParsePowerShellMenuComplete` can be called from multiple threads, but it uses a `static` `Json::CharReader`, which cannot safely parse data from multiple threads at the same time. Removing `static` fixes the problem, since every function call gets its own `reader`.
Validation: Pressed Ctrl+Space quickly a few times with hardcoded huge JSON as the completion payload. Also shown at the end of the second video in #17220.
Closes #17220

PowerShell menu completion parser thread-safety fix

---

src/renderer/vt/invalidate.cpp
src/renderer/vt/vtrenderer.hpp

When the VT render engine checks whether the cursor has moved in the
`InvalidateCursor` method, it does so by comparing the origin of the
given cursor region with the last text output coordinates. But these two
values are actually from different coordinate systems, and when on a
double-width line, the x text coordinate is half of the corresponding
screen coordinate. As a result, the movement detection is sometimes
incorrect.
This PR fixes the issue by adding another field to track the last cursor
origin in screen coordinates, so we have a meaningful value to compare
against.
The previous cursor movement detection was added in PR #17194 to fix
issue #17117.
I've confirmed that the test case from issue #17232 is now fixed, and
the test case from issue #17117 is still working as expected.

Fix conpty cursor movement detection on double-width lines

---

src/renderer/base/renderer.cpp

When the renderer calculates the invalidate region for the cursor, it
needs to take the line rendition into account. But it was using a
relative coordinate rather than absolute coordinate when looking up the
line rendition for the row, so the calculated region could easily be
incorrect.
With this PR we now use the line rendition that was already being cached
in the `CursorOptions` structure, so we avoid needing to look it up
anyway. Similarly I've replaced the `IsCursorDoubleWidth` lookup with
the value that was already cached in the `CursorOptions` structure.
I've confirmed that the test case in issue #17226 is now working as
expected.

Fix cursor invalidation when line renditions are used

---

build/pipelines/templates-v2/job-build-package-wpf.yml
build/pipelines/templates-v2/job-build-project.yml
build/pipelines/templates-v2/job-merge-msix-into-bundle.yml
build/pipelines/templates-v2/job-package-conpty.yml
build/pipelines/templates-v2/steps-esrp-signing.yml

This centralized all our ESRP calls in one file, which will make it easier in the future when we are invariable required to change how we call it again.

build: move ESRP to a parameterized subtask which takes signingId

---

src/cascadia/TerminalControl/TermControl.cpp

- Opened multi-tab terminal window with Narrator. Narrator can read characters from the tabs.
- Started a drag and drop (tear-off) of a tab, and it didn't crash. This was repeated multiple times.

Fix single-tab window tear-off crash

---

src/cascadia/TerminalApp/SuggestionsControl.cpp
src/cascadia/TerminalApp/SuggestionsControl.xaml

gotta go fast, and these animations are not fast
noted in #15845

Remove the animations from the suggestions UI

---

src/types/UiaTextRangeBase.cpp

We need to lock the buffer when getting the viewport/cursor position.
This caused the UIA overlay to randomly fail to update.
* Open a cmd tab and hold any key immediately
* Repeat until you're somewhat confident it's gone ✅

Fix race conditions in UiaTextRangeBase

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/UnitTests_Control/ControlCoreTests.cpp

This is fallout from #16937. 
* Typing a command then backspacing the chars then asking for suggestions would think the current commandline ended with spaces, making filtering very hard. 
* The currently typed command would _also_ appear in the command history, which isn't useful. 
I actually did TDD for this and wrote the test first, then confirmed again running through the build script, I wasn't hitting any of the earlier issues. 
Closes #17241
Closes #17243

Clean up command history context passed to suggestions UI

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

A few minor changes to better guide people along new features in 1.21.
The font face box gets a sub-text that explains how to add multiple
fonts and the builtin glyph toggle now explains its dependence to D3D.

Improve font related help text

---

tools/ReleaseEngineering/ServicingPipeline.ps1

This prevents me from making dumb mistakes, really.

ServicingPipeline: Warn when local release-XX branch is not uptodate

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/BackendD2D.cpp
src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/BackendD3D.h
src/renderer/atlas/common.h

This clamps the font sizes between 1 and 100. Additionally, it fixes
a warning that I randomly noticed when reproducing the issue: D2D
complained that `EndDraw` must be called before releasing resources.
Finally, this fixes a crash when the terminal size is exactly (1,1)
cells, which happened because the initial (invalid) size was (1,1) too.
This doesn't fully fix all font-size related issues, but that's
currently difficult to achieve, as for instance the swap chain size
isn't actually based on the window size, nay, it's based on the cell
size multiplied by the cell count. So if the cell size is egregiously
large then we get a swap chain size that's larger than the display and
potentially larger than what the GPU supports which results in errors.
Closes #17227

AtlasEngine: Improve robustness against weird font sizes

---

src/cascadia/TerminalCore/TerminalApi.cpp

As reported here:
https://github.com/microsoft/terminal/pull/16224#discussion_r1594849244
The underlying `WriteFile` call may block indefinitely and
we shouldn't hold the terminal lock during that period.

Fix lock warning during ReturnResponse

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/ConptyConnection.h

As it turns out, for handoff'd connections `Initialize` isn't called
and this meant the `_sessionId` was always null.
After this PR we still don't have a `_profileGuid` but that's probably
not a critical issue, since that's an inherent flaw with handoff.
It can only be solved in a robust manner if WT gets launched before the
console app is launched, but it's unlikely for that to ever happen.
* Launch
* Register that version of WT as the default
* Close all tabs (Ctrl+Shift+W)
* `persistedWindowLayouts` is empty ✅
* Launch cmd/pwsh via handoff
* You get 1 window ✅
* Close the window (= press the X button)
* Launch
* You get 2 windows ✅

Fix persistence of handoff'd tabs

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalWindow.cpp
src/cascadia/TerminalApp/TerminalWindow.h
src/cascadia/TerminalApp/TerminalWindow.idl
src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/ConptyConnection.h
src/cascadia/WindowsTerminal/AppHost.cpp

As the title says, this backports the changes in #17211 and #17268:
* `PersistState` being called when the window is closed
(as opposed to closing the tab). The settings check was missing.
* Avoid persisting windows with 0 tabs (= last tab gets closed).

Backport session persistence fixes in #17211 and #17268

---

src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/atlas/AtlasEngine.r.cpp
src/renderer/atlas/BackendD2D.cpp
src/renderer/atlas/BackendD2D.h
src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/BuiltinGlyphs.cpp
src/renderer/atlas/BuiltinGlyphs.h
src/tools/RenderingTests/main.cpp

This implements builtin glyphs for our Direct2D renderer, as well as
dashed and curly underlines. With this in place the only two features
it doesn't support are inverted cursors and VT soft fonts.
This allows us to remove the `_hack*` members introduced in a6a0e44.
The implementation of dashed underlines is trivial, while curly
underlines use quadratic bezier curves. Caching the curve as a sprite
is possible, however I feel like that can be done in the future.
Builtin glyphs on the other hand require a cache, because otherwise
filling the entire viewport with shaded glyphs would result in poor
performance. This is why it's built on top of `ID2D1SpriteBatch`.
Unfortunately the API causes an eager flush of other pending graphics
instructions, which is why there's still a decent perf hit. …

AtlasEngine: Implement remaining underlines and builtin glyphs for D2D

---

src/cascadia/CascadiaPackage/Package-Can.appxmanifest

The 2024.04D servicing update to Windows 10 added support for `appLicensing`.

Revert Canary to supporting 10.0.19041 (Windows 10 Vb+)

---

src/renderer/vt/XtermEngine.cpp

The dirty view calculation in the `XtermEngine::StartPaint` method was
originally used to detect a full frame paint that would require a clear
screen, but that code was removed as part of PR #4741, making this
calculation obsolete.
The `performedSoftWrap` variable in the `XtermEngine::_MoveCursor`
method was assumedly a remanent of some WIP code that was mistakenly
committed in PR #5181. The variable was never actually used.
All the unit tests still pass and nothing seems obviously broken in
manual testing.

Remove some unused/obsolete XtermEngine code

---

.github/workflows/similarIssues.yml

I was talking with @plante-msft this week at Build and we agreed that .75 is just a bit too chatty. .8 seems like it's a better threshold - sure, it'll miss a few of the harder edge cases, but it'll chime in less frequently when it's just wrong.

Raise the dupe bot's threshold to .8

---

src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/UnitTests_TerminalCore/TerminalBufferTests.cpp

Closes: #17323 
- Run `echo Hello ^(https://github.com/microsoft/terminal^)` in cmd.
- Ctrl+click on the URL opens `https://github.com/microsoft/terminal` in the browser.
- Hovering over the url in the terminal shows `https://github.com/microsoft/terminal` in the hover UI.

Fix hyperlinks using an extra character at the end

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalControl/ControlCore.cpp

First, this makes use of `PSEUDOCONSOLE_INHERIT_CURSOR` to stop ConPTY from emitting a CSI 2 J on startup. Then, it uses `Terminal::SetViewportPosition` to fake-scroll the viewport down so that only 3 lines of scrollback are visible. It avoids printing actual newlines because if we later change the text buffer to actually track the written contents, we don't want those newlines to end up in the next buffer snapshot.
Closes #17274
* Restore cmd multiple times
* There's always exactly 3 lines visible ✅

Show parts of the scrollback on restore

---

src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/Pane.h
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalTab.cpp

Calling Close() from within WalkPanes is not safe. Simply using _FindPane is enough to fix this.
This PR also fixes another potential source of infinite recursion, and fixes panes being passed by-value into the callbacks.
Closes #17305
* Split panes vertically 3 times
* `exit` the middle, the bottom and final one, in that order

Fix a crash when closing panes

---

src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

I noticed this while working on #17330. We're constructing a whole lambda just to do this wacky weak_ref logic, and that feels... gross. We should just make this a bound method and a typed event, so we can just use the one event handler regardless

Replace `tab.ActivePaneChanged` handler with a method

---

src/host/ut_host/ScreenBufferTests.cpp
src/terminal/adapter/PageManager.cpp
src/terminal/adapter/PageManager.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp

When we receive a stream of output at the bottom of the page that wraps
over more than two lines, that is expected to pan the viewport down by
multiple rows to accommodate all of the output. However, when the output
is received in a single write, that did not work correctly.
The problem was that we were reusing a `Page` instance across multiple
`_DoLineFeed` calls, and the viewport cached in that `Page` wasn't valid
after the first call. This PR fixes the issue by adjusting the cached
viewport when we determine it has been moved by `_DoLineFeed`.
The bug was introduced in PR #16615 when paging support was added.
I've verified that the test case in #17351 is now working correctly, and
have added a unit test covering this scenario.

Account for viewport movement when wrapping over multiple rows

---

src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/Pane.h
src/cascadia/TerminalApp/ScratchpadContent.cpp
src/cascadia/TerminalApp/SettingsPaneContent.cpp
src/cascadia/TerminalApp/TerminalPaneContent.cpp
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h
src/cascadia/TerminalConnection/ConptyConnection.cpp

#17333 introduced a regression: While it fixes a recursion *into*
`Pane::Close()` that doesn't fix the recursion outside of it.
In this case, `Close()` raises the `Closed` event which results
in another tab being closed because it's bound to `_RemoveTab`.
The recursion is now obvious, because I made the entire process
synchronous. Previously, it would (hopefully) just be scheduled
after the pane and its content are already gone.
The issue can be fixed by moving the recursion check from
`Pane::Close()` to `TerminalTab::Shutdown()` but I felt like
it would better to fix the issue a bit more thoroughly.
`IPaneContent` can raise a `CloseRequested` event to indicate it wants
to be closed. However, that also contained recursion, because the
content would call its own `Close()` to raise the …

Fix two panes being closed when just one is

---

src/buffer/out/UTextAdapter.cpp
src/cascadia/TerminalCore/Terminal.cpp

`utextAccess` apparently doesn't actually need to clamp the
`chunkOffset` to be in range of the current chunk. Also, I missed to
implement the part of the spec that says to leave the iterator on the
first/last chunk of the `UText` in case of an out-of-bounds index.
This PR fixes the issue by simply not returning early, doing a more
liberal clamp of the offset, and then checking whether it was in range.
As an aside, this also fixes a one-off bug when hovering URLs that
end on the very last cell of the viewport (or are cut off).
Closes #17343
* Write an URL that wraps across the last 2 lines in the buffer
* Scroll 1 line up
* No assert ✅
* Hovering the URL shows the full, still visible parts of the URL ✅

Support valid out-of-bounds access in utextAccess

---

src/buffer/out/textBuffer.cpp

I think I forgot to complete that section of the code...
The parentheses were missing and `beg` was repeated twice. The last
line in the comment above this explains what I intended it to be.
Closes #17365
* In a new PowerShell tab
* Run ``"`e[999C`e[2D`e[42mfoo`e[m"``
* Newline until it scrolls
* Run it again
* Close and reopen
* The green "foo" is still green ✅

Fix spurious clear-to-end sequence in buffer dumps

---

src/cascadia/TerminalControl/Resources/en-US/Resources.resw
src/cascadia/TerminalControl/TermControl.cpp
src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/BackendD3D.h
src/renderer/atlas/common.h

This adds a check for whether MacType is injected and whether it's
a known bad version (pre-2023). In that case we avoid calling the
known faulty `ID2D1Device4` interface. We could avoid it in general to
fix the issue without a warning (it's only a very mild optimization),
but on the other hand, the bug that MacType has is a very serious one
and it's probably better overall to suggest users to update.
See: https://github.com/snowie2000/mactype/pull/938
* MacType 2021.1-RC1 results in a warning and no crash ✅
* MacType 2023.5.31 results in no warning ✅

Warn when using old MacType versions

---

build/pipelines/ci-caching.yml

This is a place for @dfederm to work, but I couldn't create the pipeline definition without first creating the yml file _in main_. Thanks SFI.

build: add a caching copy of the CI pipeline

---

src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp

CI is complaining about this on all new builds, in audit mode. But I don't think anything changed here recently. Maybe just new audit rules rolled out?

Mark the AdaptDispatch ctor as noexcept

---

src/cascadia/Remoting/WindowManager.cpp

Sometimes subsequent WT windows open in the background behind other applications. This PR tries to fix it.
Refs #15895
Refs #15479
Mysterious bug (and annoying). There are even some discussions about happening to the first startup, not just subsequent ones. Sometimes the window may show up without animation too. So I don't think this is the final solution, but it did get solved on my computer, for now.
0. Quit all WT windows if some.
1. Open File Explorer, click "Open in Terminal" in context menu.
2. Move the newly opened window and minimize it.
3. Back to step 1 and repeat several times.
4. All the windows should open in the foreground correctly (yet possibly without animation).

Make subsequent windows open in the foreground

---

src/cascadia/TerminalApp/ActionPreviewHandlers.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/Resources/en-US/Resources.resw
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/renderer/base/renderer.cpp
src/renderer/inc/IRenderData.hpp
src/tsf/Implementation.cpp

This adds support for previewing snippets, again. This time, with the new TSF implementation. Leonard pointed me in the right direction with this - he's the one who suggested to have a second `Composition` just for previews like this. 
Then we do some tricky magic to make it work when we're using commandlines from shell integration, or you've got the ghost text from powershell, etc. Then we visualize the control codes, just so they aren't just U+FFFE diamonds. 
Closes #12861

Re-implement previewing, with the new TSF

---

src/cascadia/TerminalApp/SuggestionsControl.cpp
src/cascadia/TerminalApp/SuggestionsControl.h
src/cascadia/TerminalApp/SuggestionsControl.xaml
src/cascadia/TerminalSettingsModel/Command.cpp
src/cascadia/TerminalSettingsModel/Command.h
src/cascadia/TerminalSettingsModel/Command.idl
src/types/UiaTextRangeBase.cpp

This adds a `"description"` property to actions. Notably, the shell completion protocol (#3121) will now also populate that. 
The suggestions UI can then use those descriptions to display an additional tooltip with that information. 
TeachingTip was kinda an abject disaster last time I tried this, so this _isn't_ a TeachingTip. It's literally a text block. 
xlinks:
* #13000
* #15845 
* #14939 - the last abandoned attempt at this

Add descriptions to commands (namely, snippets)

---

src/cascadia/TerminalControl/SearchBoxControl.cpp
src/cascadia/TerminalControl/SearchBoxControl.h
src/cascadia/TerminalControl/TermControl.cpp

Fixes:
- Snapping the current match to the current selection doesn't work.
- Fast closing and re-opening SearchBox would leave search highlights in an inconsistent state. The highlights would be active even when SB is not on the screen, and results are not updated as more text is added to the buffer.
- Search highlights scroll marks are not cleared when the search box is closed.

Fix some search highlights scenarios

---

build/pipelines/ci-caching.yml
build/pipelines/ci.yml
build/pipelines/fuzz.yml
build/pipelines/pgo.yml
build/pipelines/templates-v2/job-run-pgo-tests.yml
build/pipelines/templates-v2/job-test-project.yml

We are no longer exclusively using one organization named "ms" and one organization not named "ms".
This change flips the sense of the organization comparison so the `OSS` agents can be used for every collection _except_ very specifically the Microsoft one. I also switched to using its ID.

build: make the agent pool selection more robust

---

src/cascadia/TerminalApp/Pane.cpp

#17358 introduced a bug where if you open/close panes very rapidly Terminal will crash. This was because `_content` was being set to `null` and then a `Close` event was being emitted, but several functions attempt to access the pane's `_content` as part of the close routine. For example, `TerminalTab` tries to update the `TaskbarProgress` every time a pane is closed and as part of that update sequence it queries the pane - which has `null` content now - for the taskbar progress, resulting in a crash. This PR fixes that crash.
Refs #17358

Fix crash when closing panes very quickly

---

.github/actions/spelling/expect/expect.txt
.gitignore
Directory.Build.props
Directory.Build.targets
build/pipelines/ci-caching.yml
build/pipelines/templates-v2/job-build-project.yml
dep/nuget/packages.config

Add Microsoft.MSBuildCache
This change adds a new pipeline which enables caching in the build. This is added as a separate pipeline for now with the eventual goal of enabling for PR and/or CI builds.
Documentation for Microsoft.MSBuildCache can be found in the GitHub repo: https://github.com/microsoft/MSBuildCache
Preliminary numbers below.
* [Baseline](https://dev.azure.com/ms/terminal/_build/results?buildId=579399&view=results): 12 min
* [0% Cache hits](https://dev.azure.com/ms/terminal/_build/results?buildId=579419&view=results): 16 mins
* [100% cache hits](https://dev.azure.com/ms/terminal/_build/results?buildId=579427&view=results): 3 mins

Add Microsoft.MSBuildCache

---

src/tools/ConsoleBench/ConsoleBench.exe.manifest
src/tools/ConsoleBench/ConsoleBench.vcxproj
src/tools/ConsoleBench/ConsoleBench.vcxproj.filters
src/tools/ConsoleBench/arena.cpp
src/tools/ConsoleBench/arena.h
src/tools/ConsoleBench/conhost.cpp
src/tools/ConsoleBench/conhost.h
src/tools/ConsoleBench/main.cpp
src/tools/ConsoleBench/utils.h

This now covers all major Console APIs.
In the future we could add tests that cover VT sequences as well.

Add more ConsoleBench tests

---

src/renderer/atlas/BackendD2D.cpp

The initial contents of a texture are undefined. That's not good.
Now they are. That's good.

Fix builtin glyph corruption in the D2D renderer

---

src/terminal/adapter/SixelParser.hpp

Assuming we do have a bug somewhere, initializing these members
will allow us to consistently reproduce the bug, whereas without
the initialization the member values will all be random and so
they may result in random behavior which would make finding the
root cause more difficult (or at least less consistent).

Initialize all SixelParser members

---

.github/actions/spelling/excludes.txt
build/StoreSubmission/.gitignore
build/StoreSubmission/Preview/PDPs/en-US/PDP.xml
build/StoreSubmission/Preview/SBConfig.json
build/StoreSubmission/README.md
build/StoreSubmission/Stable/PDPs/en-US/PDP.xml
build/StoreSubmission/Stable/SBConfig.json
build/pipelines/daily-loc-submission.yml

This also updates the localization pipeline to check in translations for the PDPs.
Right now, the primary source for PDPs is the Terminal.Internal repository. They are submitted from there, and pulled back in as though they were destined for the internal repo. We rename them on disk prior to loc check-in to pretend they live in this repo.
Once I submit a change request to the Touchdown team to update the paths in their backend, I will follow up with another pull request that updates the remaining build steps to account for that.

Check the PDPs and StoreBroker configs into the repo

---

src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/shader_ps.hlsl

We'd previously subtract one underline-height from the curly line
offset, even though we already had subtracted its complete height.
Additionally, the pixel shader received some fine tuning:
* Shrink the stroke width so that the anti-aliasing can be seen
all the way up to the horizontal edges of the bounding box.
* Add a phase shift to break apart the symmetry of the curve.
Closes #17482
Co-authored-by: Carlos Zamora <carlos.zamora@microsoft.com>

AtlasEngine: Improve appearance of curly underlines

---

src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/PageManager.cpp
src/terminal/adapter/PageManager.hpp
src/terminal/adapter/SixelParser.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/ut_adapter/adapterTest.cpp

This PR add supports for two query sequences that are used to determine
the pixel size of a character cell:
* `CSI 16 t` reports the pixel size of a character cell directly.
* `CSI 14 t` reports the pixel size of the text area, and when divided
by the character size of the text area, you can get the character cell
size indirectly (this method predates the introduction of `CSI 16 t`).
These queries are used by Sixel applications that want to fit an image
within specific text boundaries, so need to know how many cells would be
covered by a particular pixel size, or vice versa. Our implementation of
Sixel uses a virtual cell size that is always 10x20 (in order to emulate
the VT340 more accurately), so these queries shouldn't really be needed,
but some applications will fail to work without …

Add support for querying the character cell size

---

build/pipelines/daily-loc-submission.yml

This allows us to remove the dependency on the `Terminal.Internal` repository.
I have also added some parameters to the build pipeline to ease testing.

build: update the loc pipeline with the final locations of the PDPs

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalSettingsModel/userDefaults.json

- Remove the `deprecated` flag for the `keybindings` array now that we have re-added that
- Update `userDefaults` to use the correct ID for the `Copy` command

Fix schema and user defaults from Action ID change

---

build/pipelines/templates-v2/pipeline-onebranch-full-release-build.yml
build/pipelines/templates-v2/variables-onebranch-config.yml

We have to run in an older OneBranch Windows container image due to compiler bugs.
This change prevents us from having to wait for the container image to download for build legs that _aren't_ using the compiler.

onebranch: allow publish/package to run in :latest container

---

build/scripts/Generate-PseudoLocalizations.ps1
tools/ConvertTo-PseudoLocalization.ps1

* Modified `Generate-PseudoLocalizations.ps1` to find the .xml files.
(As opposed to .resw for the other translations.)
* Added support for the new format by adding new XPath expressions,
and stripping comments/attributes as needed.
* Fixed `PreserveWhitespace` during XML loading.
* Fixed compliance with PowerShell's strict mode.
Ran it locally and compared the results. ✅

Fix qps-ploc generation for store translations

---

build/scripts/Copy-ContextMenuResourcesToCascadiaPackage.ps1
build/scripts/Generate-PseudoLocalizations.ps1
tools/ConvertTo-PseudoLocalization.ps1

This fixes some more issues not properly covered by #17526:
* Fixed `_locComment_text` comments being effectively ignored.
* Fixed line splitting of comments (CRLF vs LF).
* Fixed BOM suppression.
* Fixed support for having multiple `{Locked=...}` comments.

Fix more PDP ploc related issues

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/SnippetsPaneContent.cpp
src/cascadia/TerminalApp/SnippetsPaneContent.h
src/cascadia/TerminalApp/SnippetsPaneContent.xaml
src/cascadia/TerminalApp/TerminalPage.cpp

As discussed in the bug bash. It should be closable with a button. 
This also changes the tab color to match the Settings tabs.
This also fixes a crash where dragging just a snippets pane out to it's own window would crash.

Add a close button to the Snippets pane

---

src/cascadia/TerminalApp/ActionPreviewHandlers.cpp

This became much more obvious with the sendInput previewing. We would only dismiss previews if the following action was also previewable.
related: #15845

Dismiss a action preview when the next action isn't previewable

---

src/renderer/atlas/BackendD3D.cpp

The strided `memcpy` between buffers failed to account for situations
where the destination stride is smaller than the source stride.
The solution is to only copy as many bytes as are in each row.
Even with AppVerifier the issue could not be reproduced.
Adding an `assert(srcStride <= mapped.RowPitch)`, however, did trap
the bug when WARP is used while BackendD3D is force-enabled.

AtlasEngine: Fix a buffer overrun

---

src/cascadia/TerminalApp/AppCommandlineArgs.cpp
src/cascadia/TerminalApp/ShortcutActionDispatch.cpp
src/cascadia/TerminalApp/ShortcutActionDispatch.h
src/cascadia/TerminalApp/ShortcutActionDispatch.idl
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
src/cascadia/TerminalSettingsModel/ActionMap.cpp
src/cascadia/TerminalSettingsModel/AllShortcutActions.h
src/cascadia/TerminalSettingsModel/Command.idl

In the spec review, we agreed these didn't really need to be saved to the user's own settings file. This removes parsing and saving for the `experimental.saveSnippet` action, but we still have the action _internally_. This is powered by a new x-macro for "INTERNAL_" actions.
Follow-up from #16513.

Stop parsing `saveSnippets` actions in json

---

src/renderer/base/renderer.cpp

`InvalidateCursor` wants a viewport-relative coordinate.
Thankfully, this bug hasn't shipped anywhere yet.
* Enable horizontal scrolling in conhost
* Horizontally scroll
* Cursor blinks ✅

Fix cursor invalidation with horizontal scrolling

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalControl/TermControl.xaml

Turns out, when the branding disables the feature, we try to get `QuickFixMenu` when it's not loaded, causing a crash [here](https://github.com/microsoft/terminal/blob/dabc70ee21247fa8fa0bde976b456b124fb4b82a/src/cascadia/TerminalApp/TerminalPage.cpp#L1763-L1769). 
Since we end up loading the quick fix menu when we scroll or apply UI settings, we're actually loading the quick fix menu pretty early on. So might as well remove the `x:Load="False"`. If we feel strongly about keeping the lazy loading functionality, we can do that later (and probably apply the same heuristic to the other XAML we're registering in TerminalApp).
This also adds a feature flag check when registering the menu in TerminalApp.
Closes #17548

Revert lazy loading Quick Fix UI

---

src/buffer/out/Row.cpp
src/buffer/out/lib/bufferout.vcxproj

STL iterators have a significant overhead. This improves performance
of `GetLastNonSpaceColumn` by >100x (it's too large to measure),
and reflow by ~15x in debug builds. This makes text reflow in debug
builds today ~10x faster than it used to be in release builds before
the large rewrites in #15701 and #13626.

15x faster reflow in debug builds

---

src/interactivity/win32/Clipboard.cpp

Well, this one is rather simple. :)
tl;dr: We shouldn't call `StringPaste` twice for the same paste.
Closes MSFT:51822029

Fix double paste when CF_UNICODETEXT & CF_HDROP are present

---

src/buffer/out/textBuffer.cpp
src/host/readDataCooked.cpp
src/host/readDataCooked.hpp

* Wide glyphs that don't fit into the last column got treated
as narrow glyphs which broke line layout.
* Wide glyphs that don't fit into the last column got manually
padded with whitespace which broke Ctrl+A + Ctrl+C in conhost.
* Sudden increases/decreases in the pager height would leave
parts of the viewport with leftover text and not clear it away.
* Deleting an entire word at the start of a line would only delete
its first two characters.
Closes #17554

Fix various cooked read issues

---

src/cascadia/TerminalApp/BasicPaneEvents.h
src/cascadia/TerminalApp/ScratchpadContent.h
src/cascadia/TerminalApp/SettingsPaneContent.h
src/cascadia/TerminalApp/SnippetsPaneContent.h
src/cascadia/TerminalApp/TerminalPaneContent.h

These events are kinda just boilerplate that now keeps getting copy-pasta'd every time I make new pane types. 
This instead moves them all to a singular base class, so the definitions stay in sync.

Create a base class for all pane content events

---

src/cascadia/UnitTests_SettingsModel/TerminalSettingsTests.cpp
src/inc/til/rand.h
src/terminal/parser/ut_parser/Base64Test.cpp

This simply adds the missing `noexcept` attributes.
It also removes the unnecessary `pcg_random` import.

Make til/rand noexcept-correct

---

src/buffer/out/OutputCellIterator.hpp
src/buffer/out/OutputCellView.hpp
src/host/ApiRoutines.h
src/host/_output.cpp
src/server/ApiDispatchers.cpp
src/server/IApiRoutines.h

This abstraction will help #17510 inject its ConPTY-specific behavior
into all 6 relevant console API functions simultaneously. This avoids
having to repeat the same prologue and epilogue 4 times.
Ideally, we'd use composition here, but I found it to be a bad fit.

Abstract Write/FillOutput APIs with FillConsoleImpl

---

.github/actions/spelling/expect/expect.txt
src/types/inc/utils.hpp
src/types/utils.cpp

Split off from #17510:
* `HandleWantsOverlappedIo` can be used to check if a handle requires
overlapped IO. This is important, as `ReadFile` and `WriteFile` are
documented to not work correctly if an overlapped handle is used
without overlapped IO and vice versa.
In my tests with pipes, this appears to be true.
* `CreatePipe` creates a synchronous, unidirectional pipe.
* `CreateOverlappedPipe` does what it says on the tin, while allowing
you to specify the direction of the pipe (in, out, duplex).
* `GetOverlappedResultSameThread` is largely the same as
`GetOverlappedResult`, but adds back a neat optimization from
the time before Windows 7. I thought it was neat.

Add helper functions for pipes

---

src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
src/host/ut_host/ApiRoutinesTests.cpp
src/host/ut_host/ClipboardTests.cpp
src/host/ut_host/ConptyOutputTests.cpp
src/host/ut_host/ObjectTests.cpp
src/host/ut_host/ScreenBufferTests.cpp
src/host/ut_host/SearchTests.cpp
src/host/ut_host/SelectionTests.cpp
src/host/ut_host/TextBufferIteratorTests.cpp
src/host/ut_host/TextBufferTests.cpp
src/host/ut_host/UtilsTests.cpp
src/inc/test/CommonState.hpp
src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp

By always setting up the font, it simplifies the upcoming VtIo tests
for #17510 which don't need a font, but implicitly rely on it anyway.

Remove CleanupGlobalFont from tests

---

src/terminal/parser/stateMachine.cpp
src/types/inc/utils.hpp
src/types/utils.cpp

This will allow us to use `FindActionableControlCharacter` in code
outside of our VT parser. #17510 uses it to sanitize inputs.

Move FindActionableControlCharacter to Types

---

src/host/VtInputThread.cpp
src/host/VtInputThread.hpp
src/host/VtIo.cpp
src/terminal/parser/InputStateMachineEngine.cpp
src/terminal/parser/InputStateMachineEngine.hpp

This implements a 3s timeout for cursor inheritance which prevents
ConPTY from being deadlocked at startup, if the terminal misbehaves.
It serves another purpose, however, in that it prepares the code for
the introduction of overlapped IO in #17510.
Closes #11213

Implement a timeout for PSEUDOCONSOLE_INHERIT_CURSOR

---

src/cascadia/CascadiaPackage/Package-Can.appxmanifest
src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest
src/cascadia/TerminalConnection/CTerminalHandoff.cpp
src/cascadia/TerminalConnection/CTerminalHandoff.h
src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/ConptyConnection.h
src/cascadia/UnitTests_Remoting/RemotingTests.cpp
src/host/proxy/IConsoleHandoff.idl
src/host/proxy/ITerminalHandoff.idl
src/host/srvinit.cpp
src/inc/til/u8u16convert.h

Without a renderer in #17510 we cannot skip "frames" anymore.
As such, using overlapped IO becomes crucial to avoid a regression
in performance. ITerminalHandoff3 fixes this by allowing the terminal
to pick the pipes it wants, which mirrors CreatePseudoConsole
where the caller can also pick its own pipes.
* Do a handoff with the dev build
* Input/Output works ✅

Add ITerminalHandoff3 in preparation for overlapped pipes

---

src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
src/cascadia/TerminalSettingsModel/AllShortcutActions.h
src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/defaults.json

Adds a keybinding to open the quick fix menu, if one is available. When the action is used, we also open up the button (if it was collapsed) because that looks nice.
The `showSuggestions` action is bound to `ctrl+shift+period` by default to align with VS' "quick actions" feature and VS Code's "quick fix" feature. This was chosen over binding to `quickFix` because it's more helpful. The quick fix button is a route for users that prefer to use the mouse. If users want to add a keybinding to activate the `quickFix` button, they can do that now.
This PR also performs a bit of miscellaneous polish from the bug bash. This includes:
- the suggestions UI now presents quick fixes first
- scrolling may result in the button being drawn in the wrong place
- The bug was tracked down this line: …

Add action for Quick Fix and key binding for Suggestions

---

src/host/directio.cpp
src/host/directio.h
src/host/ft_host/API_OutputTests.cpp
src/host/ut_host/ViewportTests.cpp
src/types/viewport.cpp
tools/OpenConsole.psm1

Split off from #17510:
* `Viewport::Clamp` used `std::clamp` to calculate the intersection
between two rectangles. That works for exclusive rectangles,
because `.left == .right` indicates an empty rectangle.
But `Viewport` is an inclusive one, and so `.left == .right` is
non-empty. For instance, if the to-be-clamped rect is fully
outside the bounding rect, the result is a 1x1 viewport.
In effect this meant that `Viewport::Clamp` never clamped so far.
* The `targetArea < targetBuffer.size()` check is the wrong way around.
It should be `targetArea > targetBuffer.size()`.
* The `sourceSize` and `targetSize` checks are incorrect, because the
rectangles may be non-empty but outside the valid bounding rect.
* If these sizes were empty, we'd return the requested rectangle which
is a regression …

Fix various Read/WriteConsoleOutput bugs

---

src/renderer/atlas/atlas.vcxproj

I wish I could use these in PIX, but I can't figure out why it won't
load the PDBs. Well, better than not having them in the first place!

AtlasEngine: Generate shader PDBs in Release builds

---

.github/actions/spelling/allow/allow.txt
src/cascadia/TerminalSettingsEditor/AISettings.cpp
src/cascadia/TerminalSettingsEditor/AISettings.xaml

Instead of a TextBox for the input of the AzureOpenAI key, we use a PasswordBox now which hides the input.

Use a PasswordBox instead of a TextBox for the AzureOpenAI key

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/atlas/common.h

This regressed in #15707. By having the `viewportOffset` on the
`Settings` object we accidentally invalidate the entire viewport
every time it scrolls. That doesn't break anything of course,
but it's better to prevent this.
This PR additionally contains a fix for clamping the y coordinates
coming from `Renderer`: Since `viewportCellCount.y` is a count and
thus exclusive, but clamp's max is inclusive, we must subtract 1.

AtlasEngine: Fix dirty rects during scrolling

---

Directory.Build.props

MSBuildCache: Allow duplicate outputs under `obj\*\vcpkg\**`

MSBuildCache: Allow duplicate outputs under "obj\*\vcpkg\**"

---

dep/nuget/packages.config

Update MSBuildCache to 0.1.283-preview
Notable change is this one, which should avoid under-builds when the build tooling updates: https://github.com/microsoft/MSBuildCache/pull/77
Full release notes: [0.1.283-preview](https://github.com/microsoft/MSBuildCache/releases/tag/v0.1.283-preview)

Update MSBuildCache to 0.1.283-preview

---

src/renderer/base/renderer.cpp

Regressed in #15500, incorrectly fixed in #17332, exposed by #17583.
My ineptitude on full display. If this isn't the last cursor
invalidation bug I'm going to cry.
Closes #17615
* cmd.exe
* a directory with 6 files
* 80x24 viewport
* run `cls`
* run `dir` twice

Fix cursor invalidation, again

---

.github/actions/spelling/expect/expect.txt
doc/specs/#13000 - In-process ConPTY.md

👉 Preview: https://github.com/microsoft/terminal/blob/dev/lhecker/13000-spec/doc/specs/%2313000%20-%20In-process%20ConPTY.md
The spec has a tl;dr! The tl;dr^2 for the commit message:
* Less bugs
* Less code
* More perf

Add a spec for an In-process ConPTY

---

build/pipelines/templates-v2/pipeline-onebranch-full-release-build.yml

Thanks to a string of compiler bugs, we had to use an older container image that shipped with VS 17.9.
Unfortunately, that container image is falling further and further out of date. The build agents don't cache it any longer, so they spend 30-45 minutes of every build pulling it from the registry.
With the changes to ConPTY in #17510 removing the need for til::bitmap, we no longer need to work around the compiler bugs it exposed.
Furthermore, 17.10.6+ has a much more robust and presumably "working" compiler.

build: switch back to the "latest" OneBranch build image

---

src/interactivity/base/EventSynthesis.cpp

This fixes a regression caused by 5b44476 which accidentally moved
the two pushes into the if condition.
Closes MSFT:52463679
* Enable `Feature_UseNumpadEventsForClipboardInput`
* `cmd`
* `chcp 54936`
* Paste narrow Unicode characters like ①
* It works ✅

Fix alt-numpad events

---

src/renderer/atlas/BackendD2D.cpp

Fix sixels in BackendD2D

---

src/cascadia/TerminalSettingsEditor/Utils.cpp

We aren't sure what exactly it is, but on the latest toolchain
this code miscompiles. The fmt call throws an exception because
it supposedly has too few arguments supplied for the format string.
Debugging the issue shows that the `next_arg_id_` internal to `fmt`
is 10000, even though it's parsing the first argument. At that point
it's supposed to be 0. This code hasn't been changed in years.
My hope is that this slight shuffling of the code causes
the issue to go away.

Potential hotfix for a MSVC 14.40.33807 miscompilation

---

src/cascadia/TerminalSettingsEditor/Utils.cpp

`towupper` return `wint_t` which is `int`. 🤦
Open the settings menu. 🤦✅

wint_t is not wchar_t

---

src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/ut_adapter/adapterTest.cpp

This PR adds support for querying the cursor style - technically the
state of the `DECSCUSR` setting - using a `DECRQSS` escape sequence.
The initial `DECRQSS` support was added in PR #11152, but it wasn't
practical to report the cursor style until conpty passthrough was added
in PR #17510.
If the user has chosen a cursor style that isn't one of the shapes
supported by the `DECSCUSR` control, we report those as 0 (i.e. the
default style). That way, if an application later tries to restore the
cursor using the returned value, it should still be reset to its
original state.
I also took the opportunity in this PR to do some refactoring of the
other `DECRQSS` reports, since several of them were using unnecessary
appending that could be simplified to a single `fmt::format` call, or
even just …

Add support for querying the DECSCUSR setting

---

src/renderer/atlas/BackendD2D.cpp
src/renderer/atlas/BackendD2D.h

BackendD2D will now draw one extra cell on all sides when rendering the background, filled with the expected background color, starting at (-1, -1) to ensure that cell backgrounds do not bleed over the edges of the viewport where the is swapchain but no content.
Fixes #17672

atlas,d2d: overdraw the background bitmap by one cell on all sides

---

src/inc/til/rect.h
src/renderer/atlas/AtlasEngine.cpp

This pulls one of the inlines in AtlasEngine out as a helper so we can use it elsewhere.

til: add til::point_span_subspan_within_rect

---

src/cascadia/TerminalSettingsModel/ActionMap.cpp
src/cascadia/TerminalSettingsModel/ApplicationState.cpp
src/cascadia/TerminalSettingsModel/ApplicationState.h
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/inc/til/io.h

* Every single place that called `read_file_as_utf8_string_if_exists`
would immediately do a `.value_or(std::string{})`.
As such, the function now returns a string directly.
* There was just one caller to `read_file_as_utf8_string`
and it only cared about files that are non-empty.
As such, the specialization got removed.
Both of these make sense to me, as in practice there's seldom
a difference between an empty file and a non-existent one.
* Compiles ✅
* Starts ✅
* Deleting the `settings.json` contents triggers a reload ✅

Return strings directly from read_file_as_utf8_string_if_exists

---

src/inc/til/small_vector.h

As explained in the updated code comment, we can actually safely
allow more types to enjoy the fast-pass in `til::small_vector`.

Be less strict about trivialities

---

src/host/VtIo.cpp
src/host/VtIo.hpp
src/host/_output.cpp
src/host/_stream.cpp
src/host/consoleInformation.cpp
src/host/getset.cpp
src/host/ut_host/VtIoTests.cpp
src/interactivity/base/InteractivityFactory.cpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/parser/stateMachine.hpp

* Added/changed comments as mentioned.
* Improved the ugly `resize_and_overwrite` hack into the STL.
* Add `Write` functions for xterm's window API.
* The only reason we needed a move operator for `VtIo::Writer`
is because we used it in a ternary in `CONSOLE_INFORMATION`.
Ternaries are like if branches with hidden move assignments.
Instead, we simply construct each `Writer` in place.
No ternary = No move = No problems in life.
The best benefit of this is that this makes calling `GetVtWriter`
a hundred times cheaper.
Otherwise, I still need to extend a few tests in `VtIoTests`,
but I'm planning to do that later.

Address feedback from #17510

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp

Adds a scroll offset to avoid hiding the current search highlight with
the search box.
- Offset is based on the number of rows that the search box takes up. (I am not totally sure I am calculating this right)
- This won't help when the current highlight is in the first couple rows of the buffer.
Fixes: #4407

Avoid covering current search highlight with search box

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

This adds an indirection for `_KeyHandler` so that `OnDirectKeyEvent`
can call `_KeyHandler`. This allows us to consistently handle
Alt-key-up events. Then I added custom handling for Alt+ddd (OEM),
Alt+0ddd (ANSI), and Alt+'+'+xxxx (Unicode) sequences, due to the
absence of Alt-key events with xaml islands and our TSF control.
Closes #17327
* Tested it according to https://conemu.github.io/en/AltNumpad.html
* Unbind Alt+Space
* Run `showkey -a`
* Alt+Space generates `^[ `
* F7 generates `^[[18~`

Implement Alt-Numpad handling

---

src/host/readDataCooked.cpp
src/host/readDataCooked.hpp

This delays the CSI J until we know the new origin of the prompt.
That way it's at the right (reflowed) position.
* conhost
* Print a ton of text
* Write a prompt of a hundred chars
* Resize the window very narrow / wide
* Works ✅
* Windows Terminal
* Write a prompt of a hundred chars
* Resize the window very narrow / wide
* Works ✅

Fix cooked read reflow under ConPTY

---

src/renderer/atlas/shader_ps.hlsl

This fixes several scaling issues with double width/height rows.
* Run `RenderTests` ✅

AtlasEngine: Fix curly line rendering on rows with line renditions

---

.github/actions/spelling/expect/expect.txt
dep/Console/winconp.h
doc/cascadia/profiles.schema.json
src/cascadia/TerminalCore/ICoreSettings.idl
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/TerminalSettingsModel/Profile.idl
src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.h
src/cascadia/inc/ControlProperties.h
src/host/outputStream.cpp
src/host/outputStream.hpp
src/host/settings.cpp
src/host/settings.hpp
src/propslib/RegistrySerialization.cpp
src/terminal/adapter/ITermDispatch.hpp
src/terminal/adapter/ITerminalApi.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/termDispatch.hpp
src/terminal/adapter/ut_adapter/adapterTest.cpp
src/terminal/parser/OutputStateMachineEngine.cpp

The answerback feature allows for the user to define a message that the
terminal will transmit to the host whenever an `ENQ` (enquiry) control
character is received.
In Windows Terminal, the message can be configured at the profile level
of the settings file, as a string property named `AnswerbackMessage`.
In ConHost, the message can be configured in the registry, again as a
string value with the name `AnswerbackMessage`.
I've confirmed that the control is working as intended in both Windows
Terminal and ConHost using Vttest.
Closes #11946

Add support for the VT answerback capability

---

src/cascadia/WindowsTerminal/WindowThread.cpp
src/cascadia/WindowsTerminal/WindowThread.h

This sends a telemetry event if a session is interacted with. Specifically, key events are essential to have an interactive session in Windows Terminal, so we're tracking sessions that have had a key down event.

Log number of interactive sessions

---

src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/host/outputStream.cpp
src/host/outputStream.hpp
src/terminal/adapter/ITerminalApi.hpp
src/terminal/adapter/PageManager.cpp
src/terminal/adapter/PageManager.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatchGraphics.cpp
src/terminal/adapter/ut_adapter/adapterTest.cpp

The only reason we had the `SetTextAttributes` method in `ITerminalApi`
was to allow for conhost to remap the default color attributes when the
VT PowerShell quirk was active. Since that quirk has now been removed,
there's no need for this API anymore.
The PowerShell quirk was removed in PR #17666.
I've had to update all the attribute tests in adapterTest to manually
check the expected attributes, since those checks were previously being
handled in a `SetTextAttributes` mock which no longer exists.
I've also performed some manual tests of the VT attribute operations to
double check that they're still working as expected.

Remove SetTextAttributes from the ITerminalApi interface

---

src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/cascadia/TerminalCore/TerminalSelection.cpp
src/host/selection.cpp
src/host/selection.hpp
src/host/selectionInput.cpp
src/host/selectionState.cpp
src/host/ut_host/SelectionTests.cpp

In #17638, I am moving selection to an earlier phase of rendering (so
that further phases can take it into account). Since I am drafting off
the design of search highlights, one of the required changes is moving
to passing `span`s of `point_span`s around to make selection effectively
zero-copy.
We can't easily have zero-copy selection propagation without caching,
and we can't have caching without mandatory cache invalidation.
This pull request moves both conhost and Terminal to use
`til::generational` for all selection members that impact the ranges
that would be produced from `GetSelectionRects`.
This required a move from `std::optional<>` to a boolean to determine
whether a selection was active in Terminal.
We will no longer regenerate the selection rects from the selection
anchors plus …

Port selection in conhost and Terminal to use til::generational

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalCore/TerminalApi.cpp

This removes the `Terminal::SetViewportPosition` call from session
restoration which was responsible for putting the viewport below
the buffer height and caused the renderer to fail.
In order to prevent such issues in the future, `SetViewportPosition`
now protects itself against out of bounds requests.
Closes #17639
* Enable persistence
* Print `big.txt`
* Restart
* Looks good ✅

Fix session restoration of full buffers

---

src/terminal/adapter/ITermDispatch.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/termDispatch.hpp
src/terminal/adapter/ut_adapter/adapterTest.cpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp
src/types/inc/utils.hpp
src/types/utils.cpp

This PR introduces the framework for the `DECRQTSR` sequence which is
used to query terminal state reports. But for now I've just implemented
the `DECCTR` color table report, which provides a way for applications
to query the terminal's color scheme.
This is the counterpart to the the `DECRSTS` sequence, which is used to
restore a color table report. That was implemented in PR #13139, but it
only became practical to report the color table once conpty passthrough
was added in PR #17510.
This sequence has the option of reporting the colors as either HLS or
RGB, but in both cases the resolution is lower than 24 bits, so the
colors won't necessarily round-trip exactly when saving and restoring.
The HLS model in particular can accumulate rounding errors over time.
I've added a basic unit test …

Add support for querying the DECCTR color table report

---

src/cascadia/TerminalApp/DebugTapConnection.cpp
src/cascadia/TerminalApp/DebugTapConnection.h
src/cascadia/TerminalAzBridge/main.cpp
src/cascadia/TerminalConnection/AzureConnection.cpp
src/cascadia/TerminalConnection/AzureConnection.h
src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/ConptyConnection.h
src/cascadia/TerminalConnection/EchoConnection.cpp
src/cascadia/TerminalConnection/EchoConnection.h
src/cascadia/TerminalConnection/ITerminalConnection.idl
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalSettingsEditor/PreviewConnection.cpp
src/cascadia/TerminalSettingsEditor/PreviewConnection.h
src/cascadia/UnitTests_Control/ControlCoreTests.cpp
src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp
src/cascadia/UnitTests_Control/MockConnection.h
src/cascadia/inc/cppwinrt_utils.h

`HSTRING` does not permit strings that aren't null-terminated.
As such we'll simply use a plain char array which compiles down to
a `UINT32` and `wchar_t*` pointer pair. Unfortunately, cppwinrt uses
`char16_t` in place of `wchar_t`, and also offers no trivial conversion
between `winrt::array_view` and `std::wstring_view` either.
As such, most of this PR is about explicit type casting.
Closes #17697
* Patch the `DeviceAttributes` implementation in `adaptDispatch.cpp`
to respond like this:
```cpp
_api.ReturnResponse({L"ABCD", 3});
```
* Open a WSL shell and execute this:
```sh
printf "\e[c"; read
```

Use a plain char array to pass connection input

---

src/cascadia/TerminalConnection/ConptyConnection.cpp
src/inc/conpty-static.h
src/winconpty/dll/winconpty.def
src/winconpty/ft_pty/ConPtyTests.cpp
src/winconpty/winconpty.cpp
src/winconpty/winconpty.h

This removes `ClosePseudoConsoleTimeout` as waiting for conhost
to exit is prone to deadlocks due to incorrect API usage.
Additionally, this publicly exposes `ReleasePseudoConsole`.

Align the OSS ConPTY API with Windows 11 24H2

---

doc/cascadia/profiles.schema.json

Updates the schema to include `reloadEnvironmentVariables` for New Terminal Args.
Other properties that aren't included:
- `__content`: we're explicitly not including this in the schema since it's only used internally. In fact, we even throw an error if it is defined (sample code)!
- `sessionId`: there isn't really a legit use for this one, so we'll leave it undocumented and as an implementation detail.
Closes #17469 
[sample code]: https://github.com/microsoft/terminal/blame/0199ca33ddb4a02ca3549627d772ce6b330ed1ce/src/cascadia/TerminalSettingsModel/ActionArgs.h

schema: add reloadEnvironmentVariables to newTerminalArgs

---

src/buffer/out/OutputCell.cpp
src/buffer/out/OutputCellIterator.cpp
src/buffer/out/OutputCellView.cpp
src/buffer/out/textBuffer.cpp

Fix a misdiagnosis in MSVC 17.11

---

src/buffer/out/ImageSlice.cpp
src/renderer/gdi/paint.cpp

When we have a series of image slices of differing widths, which also
don't align with the cell boundaries, we can get rounding errors in the
scaling which makes the different slices appear misaligned.
This PR fixes the issue by removing the 4 pixel width alignment that was
enforced in the `ImageSlice` class, since that's not actually necessary
when the pixels themselves are already 4 bytes in size. And without
that, the widths should be correctly aligned with the cell boundaries.
The initial Sixel implementation was added in PR #17421.
I've confirmed that this fixes the rendering glitches reported in
#17711, and all my existing Sixel tests still work as expected.

Fix misalignment of Sixel image slices

---

src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalSelection.cpp
src/cascadia/TerminalCore/terminalrenderdata.cpp
src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp
src/cascadia/UnitTests_TerminalCore/ScrollTest.cpp
src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp
src/host/renderData.cpp
src/host/renderData.hpp
src/host/selection.cpp
src/host/selection.hpp
src/host/selectionInput.cpp
src/host/ut_host/SelectionTests.cpp
src/interactivity/onecore/BgfxEngine.cpp
src/interactivity/onecore/BgfxEngine.hpp
src/interactivity/win32/Clipboard.cpp
src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/base/RenderEngineBase.cpp
src/renderer/base/renderer.cpp
src/renderer/base/renderer.hpp
src/renderer/gdi/gdirenderer.hpp
src/renderer/gdi/invalidate.cpp
src/renderer/inc/IRenderData.hpp
src/renderer/inc/IRenderEngine.hpp
src/renderer/inc/RenderEngineBase.hpp
src/renderer/uia/UiaRenderer.cpp
src/renderer/uia/UiaRenderer.hpp
src/renderer/wddmcon/WddmConRenderer.cpp
src/renderer/wddmcon/WddmConRenderer.hpp

Right now, selections are stored as a set of points (start, end, pivot)
and converted into rectangles based on the contents of the screen buffer
**every single render pass**.
They are also painted fairly late in the rendering cycle.
This pull request makes a few changes to how selections happen.
Selections are now requested earlier in the rendering pass, during the
creation of the `RenderInfo`, and stored as a `span<point_span>`. To
make that `span` work, the selection data must be durably stored
somewhere.
Therefore, Terminal and conhost now take advantage of their new
generational selection data (#17676) to create and cache arrays of
`point_span`s covering their selections.
Unlike selection rects, linear (non-box) selections take only a single
entry in the span set. Also unlike …

Introduce the concept of "selection spans" instead of "rects"

---

build/StoreSubmission/Preview/PDPs/en-US/PDP.xml
build/StoreSubmission/Stable/PDPs/en-US/PDP.xml

Now that the store displays changelogs, it seems unfair for us to not put something in here.
These are intended to give a rough idea, not to be perfect, as they are not the product of my hours of changelog writing (since I am lazy and put that off until the day of release 🫣)

pdp: add quick release notes to the store pages

---

src/cascadia/TerminalControl/HwndTerminal.cpp
src/cascadia/TerminalControl/HwndTerminal.hpp
src/cascadia/WpfTerminalControl/TerminalTheme.cs
src/cascadia/WpfTerminalTestNetCore/MainWindow.xaml.cs
src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/atlas/BackendD2D.cpp
src/renderer/atlas/BackendD3D.cpp
src/renderer/atlas/BackendD3D.h
src/renderer/atlas/common.h
src/renderer/atlas/shader_common.hlsl

With the merge of #17638, selections are now accumulated early in the
rendering process. This allows Atlas, which currently makes decisions
about cell foreground/background at the time of text rendering,
awareness of the selection ranges *before* text rendering begins.
As a result, we can now paint the selection into the background and
foreground bitmaps. We no longer need to overlay a rectangle, or series
of rectangles, on top of the rendering surface and alpha blend the
selection color onto the final image.
As a reminder, "alpha selection" was always a stopgap because we didn't
have durable per-cell foreground and background customization in the
original DxEngine.
Selection foregrounds are not customizable, and will be chosen using the
same color distancing algorithm as the cursor. We …

atlas: draw selection colors as background/foreground instead of alpha overlay

---

src/terminal/parser/stateMachine.cpp

When conhost receives input from a conpty connection, and that input
arrives in a block larger than our 4K buffer, we can end up with a VT
sequence that's split at the buffer boundary. Previously that could
result in the start of the sequence being dropped, and the remaining
characters being interpreted as individual key presses.
This PR attempts to fix the issue by caching the unprocessed characters
from the start of the sequence, and then combining them with the second
half of the sequence when it's later received.
I've confirmed that pasting into vim now works correctly with the sample
data from issue #16655. I've also tested with a `DECCTR` report larger
than 4K which would previously have been corrupted, and which now works
as expected.

Fix input sequences split across the buffer boundary

---

src/cascadia/Remoting/Monarch.cpp
src/cascadia/Remoting/Monarch.h
src/cascadia/Remoting/Monarch.idl
src/cascadia/Remoting/Peasant.cpp
src/cascadia/Remoting/Peasant.h
src/cascadia/Remoting/Peasant.idl
src/cascadia/Remoting/WindowManager.cpp
src/cascadia/Remoting/WindowManager.h
src/cascadia/Remoting/WindowManager.idl
src/cascadia/UnitTests_Remoting/RemotingTests.cpp
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h

Once all applications that have received a `WM_ENDSESSION` message
have returned from processing said message, windows will terminate
all processes. This forces us to process the message synchronously.
This meant that this issue was timing dependent. If Windows Terminal
was quick at persisting buffers and you had some other application that
was slow to shut down (e.g. Steam), you would never see this issue.
Closes #17179
Closes #17250
* Set up a lean Hyper-V VM for fast reboots
* `Set-VMComPort <vm> 1 \\.pipe\\<pipe>`
* Hook up WIL to write to COM1
* Add a ton of debug prints all over the place
* Read COM output with Putty for hours
* RTFM, and notice that the `WM_ENDSESSION` documentation states
"the session can end any time after all applications
have returned from processing this …

Fix session persistence when the session ends

---

src/cascadia/WindowsTerminal/main.cpp

Log when `WindowsTerminal.exe` starts

---

src/cascadia/TerminalApp/TerminalWindow.cpp

* Adds a check whether the thread dispatcher is already null.
(See code comments.)
* Moves the `_settings` to only happen on the UI thread.
Anything else wouldn't be thread safe.
Closes #17620
Not reproducible. 🚫

Fix a crash during settings update

---

build/pipelines/ob-nightly.yml

Disable PGO for nightly builds

---

src/host/_stream.cpp

`ProcessString` may delete the ASB and cause a dangling screen info
pointer. As such, we must avoid using the pointer after the call.
Closes #17709
I couldn't repro the issue.

Fix a crash when disabling the ASB

---

src/interactivity/win32/uiaTextRange.cpp
src/interactivity/win32/uiaTextRange.hpp
src/types/TermControlUiaTextRange.cpp
src/types/TermControlUiaTextRange.hpp
src/types/UiaTextRangeBase.cpp
src/types/UiaTextRangeBase.hpp

Fixes the `RangeFromPoint` API such that we're now properly locking when we attempt to retrieve the viewport data. This also corrects the conversion from `UiaPoint` (screen position) to buffer coordinates (buffer cell).
Closes #17579 
- `UiaTextRangeBase::Initialize(UiaPoint)`:
- reordered logic to clamp to client area first, then begin conversion to buffer coordinates
- properly lock when retrieving the viewport data
- updated `_TranslatePointToScreen` and `_TranslatePointFromScreen` to use `&` instead of `*`
- we weren't properly updating the parameter before
- `TermControlUiaTextRange::_TranslatePointFromScreen()`
- `includeOffsets` was basically copied over from `_TranslatePointToScreen`. The math itself was straight up wrong since we had to do it backwards.
✅ Moved WT to top-left of …

Fix UIA RangeFromPoint API

---

src/cascadia/TerminalApp/Pane.cpp

I don't know what has changed between #17450 and now, but that fix
doesn't seem necessary anymore. If you add this action:
```json
{
"keys": "ctrl+a",
"command":
{
"action": "splitPane",
"commandline": "cmd /c exit"
}
}
```
and repeatedly spam Ctrl-A it used to lead to crashes. That doesn't
happen anymore, because some other PR must've fixed that.
Reverting #17450 fixes the issue found in #17578: Because the content
pointer didn't get reset to null anymore it meant that the root
pane retained the pointer after a split. After closing the split off
pane, it would assign the remaining one back to the root, which would
cause the still existing content pointer to be closed. That pointer
is potentially the same as the remaining pane and so no close events
would get received anymore.
Closes …

Fix pane event handlers being unbound

---

tools/ReleaseEngineering/ServicingPipeline.ps1

GraphQL was a steep learning curve, but I think I get it now. I've written the queries to go deep into objects to find the exact merge commit (for a PR) or the PR->merge commit chain (for an issue). This means that ServicingPipeline now supports *issues* in project boards rather than just pull requests!
One of the big benefits of doing it this way is that we no longer have to search all git commits for ones that match our pull request title format! Instead, we can just get the commit object ID directly from the graph and ask git to sort them in the right order.
I am sure that it is going to break.

Port ServicingPipeline.ps1 to ProjectsV2

---

src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.cpp
src/types/ColorFix.cpp
src/types/inc/ColorFix.hpp

Just for now. We can figure out better color grading for selections as we go.

Force selection FG to black or white depending on BG luminance

---

src/host/_stream.cpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/parser/stateMachine.hpp

Does what it says on the tin.
Part of #17737
* In WSL run
`printf "\e[?9001h"; sleep 1; printf "\e[?9001l"; read`
* Wait 1s and press Enter
* Run `showkey -a`
* Esc works ✅

ConPTY: Inject W32IM sequences

---

src/cascadia/TerminalApp/AppCommandlineArgs.cpp
src/cascadia/TerminalApp/AppLogic.cpp

By manually setting the `_windowTarget` to `0`, we can make sure to toss `x-save` commandlines at the current terminal window (so long as there is one).
Edge cases:
* You passed other subcommands with `x-save`: Well, we'll do whatever we would have normally done for multiple subcommands. We won't `x-save` in the current window, we'll obey your settings. That seems to make sense
* You ran `wt x-save` without an open Terminal window: We'll open a terminal window during the process of handling it. That seems sensible.
Closes #17366

`x-save` the commandline in the current window

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalSettingsModel/MTSMSettings.h

As we discussed in bug bash.
There's really no downside to us enabling it by default (and leaving showMarksOnScrollbar: false). It'll mark lines as "prompts" when the user hits enter. This will have a couple good side effects:
* When folks have right-aligned prompts (like, from oh-my-posh), the `enter` will terminate where shell integration thinks the command is, so that the right-prompt doesn't end up in the commandline history
* the scrollToMark actions will Just Work without any other shell integration
Closes #17632

Set the default for `autoMarkPrompts` to `true`

---

src/cascadia/TerminalSettingsEditor/ActionsViewModel.cpp

Fixes a regression from the actions MVVM change in #14292 - attempting to overwrite a keybinding was displaying a warning but propagating the change before the user acknowledged it.
The overwrite key binding warning in the SUI works like before

Fix overwrite key binding warning in the SUI

---

build/pipelines/ob-release.yml

Same justification as #17749.
We will revert this when either OneBranch Custom Pools become fit-for-purpose or they upgrade to VS 17.11. Or the heat death of the universe.

Disable PGO for Release builds

---

src/cascadia/TerminalApp/ShortcutActionDispatch.cpp
src/cascadia/TerminalSettingsModel/Command.idl

Some simple logic to report whenever an action has successfully occurred (and what ShortcutAction was used).
Note, there will be some false positives here from startup. I noticed we get a `newTab` on launch. This is probably a result of restoring the window layout of the previous session since we're using ActionAndArgs for that.

Log action dispatch occurrence

---

src/cascadia/TerminalControl/TermControl.cpp

When you close a window, it naturally loses focus.
We were trying to use members of the control to update its appearance on focus loss after it got torn down.
Closes #17520

Guard Control UpdateAppearance/Settings against UAF

---

src/buffer/out/TextColor.h
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/HwndTerminal.cpp
src/cascadia/TerminalControl/IControlAppearance.idl
src/cascadia/TerminalCore/ICoreAppearance.idl
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/inc/ControlProperties.h
src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/AtlasEngine.cpp
src/renderer/atlas/AtlasEngine.h
src/renderer/base/RenderSettings.cpp
src/renderer/base/renderer.cpp
src/renderer/inc/IRenderEngine.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp

This pull request adds support for setting and querying the selection
color with `OSC 17`.
To make this possible, I had to move selection color down into the color
table where it always belonged. This lets us get rid of the special
`SetSelectionColor` method from the surface of AtlasEngine, and reunites
selection colors with the rest of the special colors.

Allow OSC 17 to set the selection background color

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

We were erroneously eating Alt followed by VK_ADD. This change makes sure we cache key presses and releases that happen once a numpad composition is active so that we can send them when you release Alt.
Right now, we only send them when you release Alt after composing Alt and VK_ADD (entering hex mode) and only if you haven't inserted an actual hex numpad code. This does mean that `Alt VK_ADD 0 0 H I` will result in an input of "+hi". That... seems like a small price to pay for Alt VK_ADD working again.
Closes #17762

During Alt+Numpad composition, stash keys in case we bail out

---

src/cascadia/TerminalControl/ControlInteractivity.cpp
src/cascadia/TerminalControl/ControlInteractivity.h
src/cascadia/TerminalControl/ControlInteractivity.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/UnitTests_Control/ControlInteractivityTests.cpp

PR #10642 and #11290 introduced an adjustment for the cursor position used to generate VT mouse mode events.
One of the decisions made in those PRs was to only send coordinates where Y was >= 0, so if you were off the top of the screen you wouldn't get any events. However, terminal emulators are expected to send _clamped_ events when the mouse is off the screen. This decision broke clamping Y to 0 when the mouse was above the screen.
The other decision was to only adjust the Y coordinate if the core's `ScrollOffset` was greater than 0. It turns out that `ScrollOffset` _is 0_ when you are scrolled all the way back in teh buffer. With this check, we would clamp coordinates properly _until the top line of the scrollback was visible_, at which point we would send those coordinates over …

Restore off-the-top behavior for VT mouse mode

---

src/cascadia/TerminalApp/SuggestionsControl.cpp

Pretty obvious in retrospect. If there's no results, then we need to preview
_nothing_ to make sure that we clear out any old previews.
Closes #17773
Additionally, while I was here:
I realized why it seems like the selected item is so wacky when you first open the sxnui: 
* on launch we're not scrolling to the bottom item (which makes it awkward in bottom up mode)
* when we filter the list, we're maintaining the selection _index_, not the selection _item_.
Alas, that second part is... shockingly bodgy. 
(you can review this as two separate commits for sanity's sake)

Dismiss the snippet preview when there is no suggestions

---

src/host/ut_host/ScreenBufferTests.cpp

I used this very bad regex to try and find all the `\x1b`'s in ScreenBufferTests that weren't in a ProcessString call:
```
(?<!ProcessString.*)\x1b\[
```
And these looked like the ones that were the only violations. 
Closes #17736

Don't emit raw escape sequences in the test log output

---

src/cascadia/TerminalCore/Terminal.cpp

I guess I didn't realize that `SendCharEvent` could get called before `Create`. In that scenario, `enter` would hit the automark codepath (due to #17761), then crash because there was no text buffer.
Pretty easy to prevent.
Closes #17776

Prevent a crash when holding enter when creating a tab

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalCore/TerminalApi.cpp

* Repurposes `_sendInputToConnection` to send output to the connection
no matter whether the terminal is read-only or not.
Now `SendInput` is the function responsible for the UI handling.
* Buffers responses in a VT string into a single string
before sending it as a response all at once.
This reduces the chances for the UI thread to insert cursor positions
and similar into the input pipe, because we're not constantly unlocking
the terminal lock anymore for every response. The only way now that
unrelated inputs are inserted into the input pipe is because the VT
requests (e.g. DA1, DSR, etc.) are broken up across >1 reads.
This also fixes VT responses in read-only panes.
Closes #17775
* Repeatedly run `echo ^[[c` in cmd.
DA1 responses don't stack & always stay the same ✅
* Run nvim in WSL. …

Improve reliability of VT responses

---

.wt.json
src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/UnitTests_Control/ControlCoreTests.cpp
src/host/ut_host/ScreenBufferTests.cpp

This is particularly relevant to pwsh with the "ghost text" enabled. In that scenario, pwsh writes out the predicted command to the right of the cursor. With `showSuggestions(useCommandline=true)`, we'd auto-include that text in the filter, and that was effectively useless.
This instead defaults us to not use anything to the right of the cursor (inclusive) for what we consider "the current commandline"
closes #17772

Clip the "current commandline" at the cursor position

---

.github/actions/spelling/allow/allow.txt
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/pch.h
src/cascadia/TerminalSettingsModel/ActionMap.cpp
src/cascadia/TerminalSettingsModel/ActionMap.h
src/cascadia/TerminalSettingsModel/ActionMapSerialization.cpp
src/cascadia/TerminalSettingsModel/AppearanceConfig.cpp
src/cascadia/TerminalSettingsModel/AppearanceConfig.h
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettings.idl
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/Command.cpp
src/cascadia/TerminalSettingsModel/Command.h
src/cascadia/TerminalSettingsModel/FontConfig.cpp
src/cascadia/TerminalSettingsModel/FontConfig.h
src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp
src/cascadia/TerminalSettingsModel/GlobalAppSettings.h
src/cascadia/TerminalSettingsModel/IInheritable.h
src/cascadia/TerminalSettingsModel/Profile.cpp
src/cascadia/TerminalSettingsModel/Profile.h
src/cascadia/TerminalSettingsModel/Theme.cpp
src/cascadia/TerminalSettingsModel/Theme.h

Adds functionality throughout the settings model to keep track of which settings have been set.
There are two entry points:
- AppLogic.cpp: this is where we perform a settings reload by loading the JSON
- MainPage.cpp: this is where the Save button is clicked in the settings UI
Both of these entry points call into `CascadiaSettings::LogSettingChanges()` where we aggregate the list of changes (specifically, _which_ settings changed, not _what_ their value is).
Just about all of the settings model objects now have a `LogSettingChanges(std::set& changes, std::string_view context)` on them.
- `changes` is where we aggregate all of the changes to. In it being a set, we don't need to worry about duplicates and can do things like iterate across all of the profiles.
- `context` prepends a string …

Track and log changes to settings

---

.github/actions/spelling/expect/expect.txt
src/host/VtInputThread.cpp
src/host/VtInputThread.hpp
src/host/VtIo.cpp
src/host/VtIo.hpp
src/host/getset.cpp
src/host/ut_host/VtIoTests.cpp
src/inc/til/enumset.h
src/terminal/parser/InputStateMachineEngine.cpp
src/terminal/parser/InputStateMachineEngine.hpp
src/types/viewport.cpp
src/winconpty/ft_pty/ConPtyTests.cpp
tools/OpenConsole.psm1
tools/tests.xml

This adds logic to get the DA1 report from the hosting terminal on
startup. We then use the information to figure out if it supports
rectangular area operations. If so, we can use DECCRA/DECFRA to
implement ScrollConsoleScreenBuffer.
This additionally changes `ScrollConsoleScreenBuffer` to always
forbid control characters as the fill character, even in conhost
(via `VtIo::SanitizeUCS2`). My hope is that this makes the API
more consistent and robust as it avoids another source for
invisible control characters in the text buffer.
Part of #17643
* New tests ✅

Use DECCRA/DECFRA for ScrollConsoleScreenBuffer

---

src/cascadia/TerminalCore/TerminalApi.cpp

When a VT title sequence sets the title to a blank string, that is meant
to trigger a reset to the default starting value. This used to work in
the past because the blank value was dealt with by conhost, so Windows
Terminal never received a blank title, but that's no longer the case
with the new VT passthrough. This PR fixes the issue by getting Windows
Terminal to handle the blank title strings itself. 
VT passthrough was introduced in PR #17510.
I've manually verified that the `OSC 0`, `OSC 2`, and `DECSWT` sequences
now correctly reset the title when passed a blank title string.

Make sure a blank title string resets the title

---

src/cascadia/TerminalSettingsModel/Command.cpp

There's an unnecessary `fmt::format` here caught in the code review: https://github.com/microsoft/terminal/pull/17678#discussion_r1729426705
This simply removes it.

Remove unnecessary FMT

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.idl
src/cascadia/TerminalApp/TerminalWindow.cpp
src/cascadia/TerminalApp/TerminalWindow.h
src/cascadia/TerminalApp/TerminalWindow.idl
src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/ConptyConnection.h
src/cascadia/TerminalConnection/ConptyConnection.idl
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/EventArgs.cpp
src/cascadia/TerminalControl/EventArgs.h
src/cascadia/TerminalControl/EventArgs.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h
src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp

`ResizeWindow` event in `TerminalApi` is handled and bubbled to `TerminalApi->ControlCore->TermControl->TerminalPage->AppHost`. Resizing is accepted only if the window is not in fullscreen or quake mode, and has 1 tab and pane.
Relevant issues: #5094

Handle window resize event (CSI t, resize)

---

src/cascadia/TerminalSettingsModel/enableColorSelection.json

Add action IDs to the default commands for color selection
Color selection commands now show up in the command palette

Add action IDs to the color selection commands

---

src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
src/interactivity/base/InteractivityFactory.cpp

Worked with @ekoschik on this one. 
> The auth prompt in pwsh.exe is disabling the terminal window while its opened and re-enabling it when the window closes. BUT it is enabling Terminal after dismissing itself, instead of before, which means terminal is disabled when activated.
> 
> Terminal wants focus on the ISLAND window (a grandchild; island is parented to bridge, which is parented to terminal’s TLW). When it is activated, it gets a `WM_SETFOCUS` (in response to DefWindowProc `WM_ACTIVATE`). From `WM_SETFOCUS` it calls `SetFocus` on the bridge window, and similarly the bridge calls `SetFocus` on the island.
> 
> If the TLW is disabled, these `SetFocus` calls fail (see [this check](#internal-link-redacted) in `SetFocus`). In the case above, this leaves Terminal’s TLW as focus, and it …

Fix two ConPTY HWND focus issues

---

src/terminal/parser/InputStateMachineEngine.cpp
src/terminal/parser/InputStateMachineEngine.hpp

When an app makes a VT request that returns a `DCS` response, and it
hasn't also enabled VT input mode, the new passthrough implementation
loses that response. All the app receives is an `Alt`+`\` key press
triggered by the `ST` terminator. This PR fixes that issue.
This is one of the unresolved issues tracked in #17643.
The way `DCS` sequences are handled in the input state machine engine is
by returning a nullptr from `ActionDcsDispatch`, which tells the state
machine to ignore that content. But the sequence is still buffered, and
when the `ST` terminator is eventually received, that buffer is flushed,
which passes the whole thing through to the app.
Originally this only worked when VT input mode was enabled, otherwise
the `ST` sequence is converted into a key press, and the buffered …

Pass through DCS responses when VT input mode is disabled

---

src/terminal/adapter/IInteractDispatch.hpp
src/terminal/adapter/InteractDispatch.cpp
src/terminal/adapter/InteractDispatch.hpp
src/terminal/parser/InputStateMachineEngine.cpp
src/terminal/parser/ut_parser/InputEngineTest.cpp
src/tools/vtpipeterm/main.cpp

`GetChar` checks if the vkey is VK_ESCAPE. `CharToKeyEvents` however
tries really hard to figure out the vkeys of all characters.
To avoid these issues all we need to do is to simply use the existing
`WriteString` function we already use for all other VT responses.
If it's good for conhost responses, it's good for ConPTY responses.
Additionally, this removes another `IsVtInputEnabled` which was
redundant with `WriteString` which worked exactly the same internally.
Closes #17813
Closes #17851
Probably also related to #17823
* Wrote a small app to send and receive a DA1 request. It works ✅
* WSL already worked to begin with (and still works now) ✅
* No double-encoding of mouse input events ✅

Avoid dropping Esc characters from VT responses

---

src/host/getset.cpp

By translating the clip rectangle into a source-relative coordinate
space we can calculate the intersection that must be copied
much much more easily. I should've done that from the start.
Closes #17801
* Test code provided in #17801

Fix ScrollRect to DECCRA translation

---

src/host/VtIo.cpp
src/host/VtIo.hpp
src/host/getset.cpp
src/server/ObjectHandle.cpp

This moves the `SetConsoleActiveScreenBufferImpl` into `VtIo` which
allows us to use the code when the screen info handle is closed.
Closes #17817
* Calling `CreateConsoleScreenBuffer` + `SetConsoleActiveScreenBuffer`
+ `CloseHandle` results in no obvious screen changes ✅

Restore contents when a screen info is closed

---

src/cascadia/WindowsTerminal/AppHost.cpp

No dispatcher? Check dispatcher!
Closes #17847 (hopefully)

Fix crash in AppHost::_QuitRequested

---

src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.h

This commit fixes the middle mouse button handler. The `PointerReleased` callback is registered, but it is not operational because, on the Release event, the mouse button is no longer pressed. We need to track its state and act accordingly.
Issue was introduced by commit 05e7ea1423ede8ee67c3462fb04538fae5c9f9b2, which changed the event handler from `PointerPressed` to `PointerReleased`, rendering it inoperative. Instead, the default handler is used. The main issue is that when the close button is hidden with the `showCloseButton` option, the default handler no longer closes the tab on middle mouse clicks.
Also made it consistent with the Settings tab, which was never converted to `PointerReleased` and is still handled with a custom handler.
Related commit …

Allow closing tabs with middle mouse button when close button is hidden

---

build/pipelines/templates-v2/job-build-package-wpf.yml
build/pipelines/templates-v2/job-merge-msix-into-bundle.yml
build/pipelines/templates-v2/job-package-conpty.yml
build/pipelines/templates-v2/job-publish-symbols-using-symbolrequestprod-api.yml
build/pipelines/templates-v2/job-publish-symbols.yml
build/pipelines/templates-v2/job-submit-windows-vpack.yml
build/pipelines/templates-v2/pipeline-full-release-build.yml
build/pipelines/templates-v2/pipeline-onebranch-full-release-build.yml
build/pipelines/templates-v2/steps-setup-versioning.yml

PackageES is deprecated by known scourge-on-earth OneBranch, and is now the cause of some non-compliance.
I got permission from them to open-source it, so that's coming next.
For now, we can just depend on a package based on our code based on theirs.
Tested and working for C++ (DLL, EXE), C#, NuGet and MSIX.

Remove PackageES in favor of our own versioning package

---

src/cascadia/TerminalApp/Pane.cpp

The underlying issue is that the "Pane" is used both as a model and as
a UI element and so a pane loses its content as soon as it is closed,
but the tree only gets reordered after the animation has finished.
This PR is truly just a hotfix, because it doesn't solve this issue,
it only adds checks to the function that crashes.
Closes #17869
Closes #17871
* `Split pane` a few times
* Run the "Close all other panes" action

Fix a crash on pane close

---

src/cascadia/TerminalSettingsEditor/Actions.xaml
src/cascadia/TerminalSettingsEditor/ActionsViewModel.cpp
src/cascadia/TerminalSettingsEditor/CommonResources.xaml
src/cascadia/TerminalSettingsEditor/EditColorScheme.xaml

Fixes some issues with truncated text in the settings UI when 200% text scaling is applied.
For #17897, a minimum height was applied instead of a plain "height". This ensures that the desired height is applied in general, but under 200% text scaling, we are allowed to grow past that, thus preventing the truncation of the text.
For #17898, flyouts have a scroll viewer inside them by default. We actually don't want the scroll viewer because that means the text will appear "truncated" when in reality, the user is expected to notice the small scrollbar and scroll horizontally (why that's the default, I will never know). This PR introduces a new style that can be applied to these flyouts to cause text wrapping instead of horizontal scrolling. Looked through the app for any instances where this …

Fix text scaling issues in settings UI

---

src/cascadia/TerminalControl/TermControl.cpp

This just adds a quick registry check for `EnableHexNumpad`.
Depends on #17774
Closes #17762 (again)
* Alt + NumpadAdd + 221E doesn't do anything ✅
* Set the `EnableHexNumpad` registry key
* Restart
* Alt + NumpadAdd + 221E inserts ∞ ✅

Check EnableHexNumpad before enabling it

---

src/terminal/adapter/SixelParser.cpp

The sixel parser has an internal buffer that holds the indexed-color
representation of the image, prior to it being translated to RGB. This
buffer only retains the section of the image that is within the visible
viewport, so we're continually erasing segments from the top of it when
the image is large enough to trigger a scroll.
But there is a problem that arises if the window or font is resized so
that the buffer needs to reflow, because that can result in the image
being pushed entirely offscreen. At that point the segment we're trying
to erase is actually larger than the buffer itself, which can end up
causing the terminal to crash
To fix this, we just need to check for an oversized erase attempt and
simply clear the buffer instead.
I could easily reproduce this crash in Windows …

Fix a sixel crash when the buffer is reflowed

---

src/buffer/out/textBuffer.cpp
src/host/readDataCooked.cpp

Because `_layoutLine` would never return `column == columnLimit` for
control character visualizers, we'd get a deadlock in `_redisplay`,
as it tries to fill the line until it's full, but never achieve it.
Closes #17893
* Press Ctrl-A to insert "^A"
* Press Home to get to the start of the prompt
* Press and hold "A" until the line wraps
* The line wraps and there's no deadlock ✅

Fix a cooked read deadlock

---

src/buffer/out/search.cpp
src/buffer/out/search.h
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/interactivity/win32/find.cpp

* Don't reset the position entirely when changing the needle
* Don't change the scroll position when output arrives
* Don't interfere with the search when output arrives constantly
Closes #17301
* In pwsh, run `10000..20000 | % { sleep 0.25; $_ }`
* You can search for e.g. `1004` and it'll find 10 results. ✅
* You can scroll up and down past it and it won't snap back
when new output arrives. ✅
* `while ($true) { Write-Host -NoNewline "`e[Ha"; sleep 0.0001; }`
* You can cycle between the hits effortlessly. ✅ (This tests that
the constantly reset `OutputIdle` event won't interfere.)
* On input change, the focused result is near the previous one. ✅

Stop scrolling on output when search is open

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/UnitTests_Control/ControlCoreTests.cpp
src/host/PtySignalInputThread.cpp
src/host/screenInfo.cpp
src/host/screenInfo.hpp

Without a VT "renderer" there's no implicit output anymore when
calling `ClearPseudoConsole`. The fix is trivial, but it works
slightly different from before: Previously, we would preserve
the line the cursor is on, while this PR doesn't do that.
I felt like there's not much merit in preserving the line,
because it may be a multi-line prompt which won't work with that.
Closes #17867
Bind 3 different actions to the 3 variants of "Clear buffer"
and test them. They work. ✅

Fix clear buffer command

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalControl/EventArgs.idl
src/cascadia/TerminalControl/IControlSettings.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
src/cascadia/TerminalSettingsEditor/GlobalAppearanceViewModel.cpp
src/cascadia/TerminalSettingsEditor/GlobalAppearanceViewModel.h
src/cascadia/TerminalSettingsEditor/GlobalAppearanceViewModel.idl
src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
src/cascadia/TerminalSettingsEditor/LaunchViewModel.h
src/cascadia/TerminalSettingsEditor/LaunchViewModel.idl
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/EnumMappings.cpp
src/cascadia/TerminalSettingsModel/EnumMappings.h
src/cascadia/TerminalSettingsModel/EnumMappings.idl
src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp
src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.h
src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h
src/cascadia/inc/ControlProperties.h
src/tsf/Handle.cpp
src/tsf/Handle.h
src/tsf/Implementation.cpp
src/tsf/Implementation.h
src/tsf/precomp.h

This adds a "defaultInputScope" setting, hooks it up to our TSF,
and exposes it as a setting in the UI under the startup page.
In order to stay close with the other language setting, I moved that
one from the appearance to the startup page as well.
20 out of the 26 files in this PR are boilerplate unfortunately.
Closes #17816
* Install and use the Chinese IME
* Launch WT
* Chinese input ✅
* Change setting to `alphanumericHalfWidth`
* Restart WT
* English input ✅

Add input scope startup setting

---

src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml

Adds a theme resource for the color of the reset button in the settings UI.
Closes #17902

Improve color contrast of reset button in SUI

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalSettingsEditor/Interaction.xaml
src/cascadia/TerminalSettingsEditor/InteractionViewModel.h
src/cascadia/TerminalSettingsEditor/InteractionViewModel.idl
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp
src/cascadia/TerminalSettingsModel/GlobalAppSettings.h
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/UnitTests_SettingsModel/SerializationTests.cpp

Adds the following settings to the Interaction page under a Warnings subsection:
- ConfirmCloseAllTabs
- InputServiceWarning
- WarnAboutLargePaste
- WarnAboutMultiLinePaste
This also changes the JSON keys of those settings to be in the `warning` namespace as a QOL change for JSON users. We still handle the legacy keys, don't worry 😉.
#10000

Add Warnings to Settings UI

---

src/cascadia/WinRTUtils/inc/WtExeUtils.h

It bothered me. :)
* Launch packaged WT. `IsPackaged() == true` ✅
* Launch unpackaged WT. `IsPackaged() == false` ✅

Fix an exception on startup

---

src/cascadia/TerminalSettingsEditor/Appearances.cpp
src/cascadia/TerminalSettingsEditor/Appearances.h
src/cascadia/TerminalSettingsEditor/Appearances.xaml

`AutoSuggestBox` has a `SuggestionChosen` event and any reasonable
person would assume that this means one of the items was chosen.
But with WinUI it's raised whenever a suggestion is merely highlighted.
`QuerySubmitted` is the right event instead. Clearly that naming is
a lot better than `SuggestionChosen`, since the property to get the
chosen item is called `ChosenSuggestion`.
WinUI, like the unrelenting wilderness of a world indifferent to human
suffering, stands as a testament to the futility of human aspiration.
Closes #17916
* Type "Casc"
* Move up/down with the arrow keys
* Neither the filtered list nor the text updates ✅
* Press Enter on an item
* Text updates ✅

Stop updating AutoSuggestBox on selection

---

src/cascadia/QueryExtension/ExtensionPalette.cpp
src/cascadia/QueryExtension/ExtensionPalette.xaml

You can now press shift+enter in the Terminal Chat query box to enter newlines
Closes #17940

Allow shift+enter in Terminal Chat's text box

---

src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/host/getset.cpp
src/host/getset.h
src/host/output.cpp
src/host/outputStream.cpp
src/host/outputStream.hpp
src/host/server.h
src/terminal/adapter/ITermDispatch.hpp
src/terminal/adapter/ITerminalApi.hpp
src/terminal/adapter/InteractDispatch.cpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/termDispatch.hpp
src/terminal/adapter/ut_adapter/adapterTest.cpp
src/terminal/adapter/ut_adapter/inputTest.cpp
src/terminal/input/terminalInput.cpp
src/terminal/input/terminalInput.hpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp
src/terminal/parser/stateMachine.cpp

This PR adds support for the `S8C1T` and `S7C1T` commands, which enable
an application to choose whether the terminal should use C1 controls
when sending key sequences and query responses.
This also updates the `DOCS` command to set both the input and output
code pages. So when switched to ISO2022 mode, the C1 controls will be
transmitted as 8-bit, which is what legacy systems would be expecting.
While adding the input code page support, I also reworked the way we
handle the code page reset in `RIS`. In the original implementation we
saved the active code page when the `DOCS` sequence was first used, and
that would become the default value for a reset.
With this PR I'm now saving the code pages whenever `SetConsoleCP` or
`SetConsoleOutputCP` is called, so those APIs now control what the …

Add support for the S8C1T/S7C1T escape sequences

---

.github/actions/spelling/allow/apis.txt
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/UnitTests_TerminalCore/UnitTests.vcxproj
src/host/PtySignalInputThread.cpp
src/host/PtySignalInputThread.hpp
src/host/exe/Host.EXE.vcxproj
src/host/ft_fuzzer/Host.FuzzWrapper.vcxproj
src/host/outputStream.cpp
src/host/sources.inc
src/host/ut_host/Host.UnitTests.vcxproj
src/interactivity/base/InteractivityFactory.cpp
src/interactivity/base/InteractivityFactory.hpp
src/interactivity/base/ServiceLocator.cpp
src/interactivity/inc/IInteractivityFactory.hpp
src/interactivity/inc/ServiceLocator.hpp
src/interactivity/win32/ut_interactivity_win32/Interactivity.Win32.UnitTests.vcxproj
src/interactivity/win32/ut_interactivity_win32/sources
src/terminal/adapter/InteractDispatch.cpp
src/terminal/adapter/ut_adapter/sources
src/terminal/parser/ut_parser/sources

This fixes a lot of subtle issues:
* Avoid emitting another de-/iconify VT sequence when
we encounter a (de)iconify VT sequence during parsing.
* Avoid emitting a de-/iconify VT sequence when
a focus event is received on the signal pipe.
* Avoid emitting such sequences on startup.
* Avoid emitting multiple such sequences
when rapidly un-/focusing the window.
It's also a minor cleanup, because the `GA_ROOTOWNER` is not security
relevant. It was added because there was concern that someone can just
spawn a ConPTY session, tell it that it's focused, and spawn a child
which is now focused. But why would someone do that, when the console
IOCTLs to do so are not just publicly available but also documented?
I also disabled the IME window.
* First:
```cpp
int main() {
for (bool show = false;; …
```

Avoid focus loops in ConPTY

---

src/cascadia/TerminalSettingsEditor/Appearances.cpp
src/cascadia/TerminalSettingsEditor/Appearances.h
src/cascadia/TerminalSettingsEditor/Appearances.idl
src/cascadia/TerminalSettingsEditor/Appearances.xaml
src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
src/cascadia/TerminalSettingsEditor/GlobalAppearanceViewModel.h
src/cascadia/TerminalSettingsEditor/GlobalAppearanceViewModel.idl
src/cascadia/TerminalSettingsEditor/Interaction.xaml
src/cascadia/TerminalSettingsEditor/InteractionViewModel.h
src/cascadia/TerminalSettingsEditor/InteractionViewModel.idl
src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl
src/cascadia/TerminalSettingsEditor/Profiles_Advanced.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/TerminalSettingsModel/Profile.cpp

Adds the following settings to the settings UI:
- $profile.RainbowSuggestions
- $profile.CellWidth
- $global.SearchWebDefaultQueryUrl
- $global.EnableColorSelection
- $global.ShowAdminShield
- $global.EnableUnfocusedAcrylic
Additionally, the following settings have graduated from experimental 🎓:
- $profile.rightClickContextMenu
- $profile.RainbowSuggestions
Part of #10000

Add miscellaneous simple settings to the settings UI

---

src/cascadia/TerminalApp/TabManagement.cpp

Changed newSelectedIndex on tab close to tabIndex instead of tabIndex - 1.

Changed new tab index on tab close to next tab

---

src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp

The settings UI and settings model allow you to set the icon to "none" to hide the icon (you can actually see this effect in the settings UI when changing the value of the profile icon). However, during settings validation, "none" is considered a file path, which is then failed to be parsed, resulting in the icon being marked as invalid and immediately clearing the value.
This PR fixes this issue by considering "none" to be an accepted value during validation.
Related to #15843
Closes #17943
When an icon is set to "none", ...
✅ no more warning
✅ the icon is hidden

Fix hiding the icon when it's set to "none"

---

tools/OpenConsole.psm1

Added a check in OpenConsole.psm1 to throw an error if the Powershell version is <7.
Confirmed that attempting to `Import-Module .\tools\OpenConsole.psm1` throws an error on Powershell 5.

OpenConsole.psm1 PSVersion check

---

build/pipelines/templates-v2/job-check-code-format.yml

We started requiring PowerShell 7+ in #18021
We did not update the code formatting task.

ci: fix the code formatting job

---

.github/actions/spelling/expect/04cdb9b77d6827c0202f51acd4205b017015bfff.txt
.github/actions/spelling/expect/expect.txt
policies/WindowsTerminal.admx
policies/en-US/WindowsTerminal.adml
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/inc/til/winrt.h

This adds a basic policy check for DisabledProfileSources, so that
organizations can easily disable certain profiles like the Azure one.
Closes #17964
* Add a policy to disable Azure under HKCU. Disabled ✅
* Add a policy to disable nothing under HKLM. Enabled ✅
(...because it overrides the HKCU setting.)

Add a policy for profile sources

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalSettingsEditor/Appearances.cpp
src/cascadia/TerminalSettingsEditor/Appearances.h
src/cascadia/TerminalSettingsEditor/Appearances.xaml

I wrote a big comment next to the changes I made.
This is a redo of #17961 which had various issues.
Closes #17916
Closes #18070 
* Pressing Enter within the input line doesn't crash ✅
* Type "Cour" and pick Courier New, press Save = Saved ✅
* Pick any other font from the dropdown, press Save = Saved ✅
* Picking an option dismisses focus but not to the tab row ✅
* The first time after launching the SUI, when the setting is still
unmodified, when you focus the box and pick an option,
it'll unfocus the box ✅
* When the setting is unmodified, and you pick the default
(Cascadia Mono), it'll still unfocus the box ✅

Stop updating AutoSuggestBox on selection redux

---

src/cascadia/QueryExtension/ExtensionPalette.cpp

When a multiline code block is clicked in Terminal chat, the first command gets run before the user presses 'Enter'. This commit fixes that by separating the code lines by the delimiter appropriate to the shell (`&` for cmd, `;` for everything else).
Newlines get replaced with the appropriate delimiter

Don't send newlines to the shell from Terminal Chat

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalSettingsModel/ActionEntry.cpp
src/cascadia/TerminalSettingsModel/ActionEntry.h
src/cascadia/TerminalSettingsModel/NewTabMenuEntry.idl
src/cascadia/TerminalSettingsModel/ProfileEntry.cpp
src/cascadia/TerminalSettingsModel/ProfileEntry.h

This PR is to allow users to set a custom icon for entries in the new tab menu for "action" and "profile" type entries.
This PR is in response to #18103 
It is now possible to specify an optional "icon" setting for any "action" or "profile" type entry in the "newTabMenu" JSON settings. When specified, this icon will be used as the menu icon for that action/profile in the new tab menu. If not specified, the action/profile definition's default icon will be used instead (if present).
The Cascadia settings schema ("doc/cascadia/profiles.schema.json") has been updated to reflect this.
Manually tested with multiple combinations of icon settings:
- ActionEntry:
- valid path in action definition and new tab entry (renders new tab entry icon)
- valid path in action definition but no path in new …

Add icon override setting for newTabMenu entries

---

src/cascadia/TerminalApp/Jumplist.cpp
src/cascadia/TerminalSettingsModel/KeyChordSerialization.cpp
src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h
src/cascadia/UIHelpers/Converters.cpp
src/cascadia/UIHelpers/Converters.h
src/cascadia/UIHelpers/IconPathConverter.cpp
src/common.build.pre.props
src/inc/til/string.h
src/terminal/parser/OutputStateMachineEngine.cpp
src/til/ut_til/string.cpp

Reading through our existing patterns for integer parsing, I noticed
that we'd be better off returning them as optionals.
This also allowed me to improve the implementation to support integers
all the way up to their absolute maximum/minimum.
Furthermore, I noticed that `prefix_split` was unsound:
If the last needle character was the last character in the remaining
text, the remaining text would be updated to an empty string view.
The caller would then have no idea if there's 1 more token left
or if the string is truly empty.
To solve this, this PR introduces an iterator class. This will allow
it to be used in our VT parser code.

New tokenization & integer parsing helpers

---

src/cascadia/TerminalApp/CommandPalette.xaml

Turns out that having the styles for the KeyChordText and ParsedCommandLineText be empty for high contrast mode caused the issue. Since we're already using theme resources for the colors, we automatically adjust properly to whatever the high contrast theme is (Thanks XAML!).
Bonus points:
- we didn't need the theme dictionaries anymore, so I just moved them to the ResourceDictionary directly
- ParsedCommandLineTextBlockStyle isn't used. So I removed it altogether.
Validated command palette with multiple high contrast themes. See PR thread for demo.
Closes #17914

Fix High Contrast mode in Command Palette

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/MainPage.xaml
src/cascadia/TerminalSettingsEditor/pch.h

"HighContrast" is not a possible requested theme. So `_UpdateBackgroundForMica()` would force the settings UI to be light or dark. To fix this, we just check if we're in high contrast mode and, if so, we don't bother setting the requested theme.

Fix High Contrast mode in Settings UI

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TabBase.cpp
src/cascadia/TerminalApp/TabBase.h
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

Adds a "Move tab" submenu to the tab's context menu. This submenu includes "move tab to new window", "move left", and "move right".
The new "move left/right" items are disabled if the tab can't be moved in a certain direction.'
Closes #17900

Add 'Move Tab' submenu to tab context menu

---

src/cascadia/TerminalApp/TabBase.cpp

Originally, the XAML resources were being applied on the TabView's ResourceDictionary directly. However, high contrast mode has a few weird scenarios as it basically reduces the color palette to just a few colors to ensure high contrast. This PR now stores the resources onto the ThemeDictionaries so that we have more control over the colors used.
Closes #17913
Closes #13067 (fixed by 5be0056)
Compared the following scenarios to WinUI 2 gallery's TabView when in High Contrast mode:
✅ (Un)selected tab
✅ hover over x of (un)selected tab
✅ hover over unselected tab

Fix tab contrast colors when in high contrast

---

src/cascadia/QueryExtension/GithubCopilotLLMProvider.cpp

We were setting an error type for non-error responses, this commit fixes that

Set the error status correctly for Github Copilot responses

---

tools/razzle.cmd

This PR aims to fix issue #1111.
* https://github.com/microsoft/terminal/issues/1111
This PR makes it so the path to nuget in this repo is prepended. This will make it so the local `nuget.exe` is prioritised before looking for nuget in `PATH`.
Run `razzle.cmd`, the local instance of nuget is utilised. 
Delete `nuget.exe`, `razzle.cmd` uses `nuget.exe` specificed in the `PATH`.

Prepend path to nuget in repo

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl
src/cascadia/TerminalSettingsEditor/Profiles_Base_Orphaned.cpp
src/cascadia/TerminalSettingsEditor/Profiles_Base_Orphaned.h
src/cascadia/TerminalSettingsEditor/Profiles_Base_Orphaned.idl
src/cascadia/TerminalSettingsEditor/Profiles_Base_Orphaned.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/Profile.cpp
src/cascadia/TerminalSettingsModel/Profile.h
src/cascadia/TerminalSettingsModel/Profile.idl

The original intent with dynamic profiles was that they could be uninstalled but that Terminal would remember your settings in case they ever came back.
After we implemented dynamic profile _deletion_, however, we accidentally made it so that saving your settings after a dynamic profile disappeared scoured it from the planet _forever_ (since we remembered that we generated it, but now it was no longer in the settings file).
This pull request implements:
- Tracking for orphaned dynamic profiles
- A new settings page for the profile that explains what happened
- Badging on the Navigation Menu indicating which profiles are orphaned and which are hidden
Closes #14061
Closes #11510 
Refs #13916 
Refs #9997
It looks like this:
If you disable all profile sources, it looks barren indeed:

Retain (and indicate) orphaned dynamic profiles

---

src/cascadia/TerminalControl/ControlInteractivity.cpp

In #18195, we introduced a real `pathTranslationStyle` setting.
I'm not backporting that whole thing.

[<= 1.22] Do path translation for multiple types of WSL

---

src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/Profile.cpp
src/cascadia/TerminalSettingsModel/Profile.h
src/cascadia/TerminalSettingsModel/Profile.idl

The original intent with dynamic profiles was that they could be uninstalled but that Terminal would remember your settings in case they ever came back.
After we implemented dynamic profile _deletion_, however, we accidentally made it so that saving your settings after a dynamic profile disappeared scoured it from the planet _forever_ (since we remembered that we generated it, but now it was no longer in the settings file).
This pull request implements:
- Tracking for orphaned dynamic profiles
Closes #14061
Closes #11510
Refs #13916
Refs #9997
Modified for 1.22. I am not including any of the UI affordances.
(cherry picked from commit 90866c7c93c4743926d481b07d66a3e3e4eb1da8)
Service-Card-Id: PVTI_lADOAF3p4s4AmhmQzgU1-p4
Service-Version: 1.22

[<= 1.22] Retain (BUT DON'T INDICATE) orphaned dynamic profiles

---

doc/cascadia/profiles.schema.json
src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlInteractivity.cpp
src/cascadia/TerminalControl/ControlInteractivity.h
src/cascadia/TerminalControl/ControlInteractivity.idl
src/cascadia/TerminalControl/HwndTerminal.cpp
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalSelection.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.h
src/cascadia/TerminalSettingsModel/ActionArgs.idl

This extends the copy command to be able to include control sequences, for use in tools that subsequently know how to parse and display that.
https://github.com/microsoft/terminal/issues/15703
At a high level, this:
- Expands the `CopyTextArgs` to have a `withControlSequences` bool.
- Plumbs that bool down through many layers to where we actuall get data out of the text buffer.
- Modifies the existing `TextBuffer::Serialize` to be more generic and renames it to `TextBuffer::ChunkedSerialize`.
- Uses the new `ChunkedSerialize` to generate the data for the copy request.
To test this I've manually:
- Generated some styled terminal contents, copied it with the control sequences, pasted it into a file, `cat`ed the file and seen that it looks the same.
- Set `"firstWindowPreference": …

Allow copying with ANSI escape code control sequences

---

src/common.build.pre.props

microsoft/vcpkg-tool#1474 now validates that the target triplet is valid. Unfortunately, `ARM64` is not valid... despite VS defaulting to it.
VS 17.12 moved to the newer version of the vcpkg tool.
Given that we still want to build on VS 17.12, this commit adds a local workaround.
See DD-2302065 for the internal tracking bug.
 
See microsoft/vcpkg#42182 for the upstream fix.

build: fix arm64 vcpkg triplet selection error

---

src/cascadia/TerminalControl/TermControl.cpp

When file/folder is dropped to the terminal, its path is translated and quoted with a pair of single quotes if necessary.
However, the terminal control does not escape single quotes (allowed in the Win32 subsystem) that need escapes when translated.
On the translation styles other than `"none"` (note: all other translation styles are currently intended for the POSIX shell), it causes incorrect path to be pasted when the path contains one or more single quotes (see #18006 for an example).
With this commit, the terminal control escapes a single quote with a valid escape sequence `'\''` (finish quote, print a single quote then begin quote again) when the path translation is required.
* Changed escape sequence from `'"'"'` to much shorter `'\''`.
* Reflected comments by the reviewer.
* …

Escape single quotes while translating dropped Win32 paths

---

src/host/settings.cpp
src/propsheet/registry.cpp

This reverts commit 5fdfd51209fc681e66657d6697ce031bc4319619,
because 3 people complained about this change VS 1 person
requesting the change to be made in the first place.
Closes #18138
Reopens #17797 for discussion

Revert "Dedup command history by default (#17852)"

---

doc/cascadia/Unittesting-CppWinRT-Xaml.md
scratch/ScratchIslandApp/Package/Package.appxmanifest
src/cascadia/CascadiaPackage/Package-Can.appxmanifest
src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest
src/cascadia/WindowsTerminal/WindowsTerminal.manifest

As it turns out, you cannot use `<uap17:UpdateWhileInUse>`
(or any other newer namespace) unless you declare a corresponding
`MaxVersionTested` in your package manifest.
It does not appear that there's a reason for this, it just is.
`MaxVersionTested` is not to be confused with the `maxversiontested`,
which is something else entirely, but I updated it for safe measure.
Since `maxversiontested` is not a "max", but rather a list
of tested versions, it gets appended to the end of the list.
Closes #18119

Add 10.0.26100.0 to MaxVersionTested

---

doc/cascadia/profiles.schema.json

It seems I forgot to add this in #16916.

Update settings schema for compatibility.textMeasurement

---

src/inc/til/string.h
src/til/ut_til/string.cpp

* Fixed parsing of octal numbers
* Fixed missing check for the value range
* Fixed overflow check
* Added support for anything up to base 36
* Added support for the 0b prefix
* New unit tests
* Fuzzing

Fix til string to integer routines

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlCore.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl
src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
src/cascadia/TerminalSettingsModel/AllShortcutActions.h
src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/defaults.json

Added open current directory action.
Need to set this: https://learn.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory
- Ensure shell has been configured
- Run "Open current working directory" action in command palette
- File explorer opens the correct directory

Open current working directory action.

---

README.md

Closes #18055 - Updated README with Table Of Contents

---

src/server/ApiMessage.cpp

This increases the console IO buffer size to retain at least 128KiB as this matches the default buffer size of `cat`. This avoids allocator churn due to constantly freeing and reallocating buffers. In the future this should ideally use a better suited, cheap allocator.
Closes #18286

Reduce malloc churn for console calls <=128KiB

---

src/cascadia/TerminalApp/TabBase.cpp

If we colored a tab, then switched to another tab, there's a bug that the unselected tab loses its color. This was introduced in PR #18109. This PR fixes that by actually applying the selected color to the tab (whoops). Additionally, I removed setting the "TabViewItemHeaderCloseButtonBackground" resource because it looked weird (see comment in PR).
Closes #18226

Fix colored tab losing color when unselected

---

src/propsheet/fontdlg.cpp

CodeQL is raising errors when building Visual Studio since we have a dependency on Windows Terminal for our integrated terminal. The issue raised is not applicable to this case and therefore requires a suppression comment to ignore the raised error.
CodeQL error: https://liquid.microsoft.com/codeql/issues/794ce24e-f563-420c-b611-351ab9a2b700?copilot_promptid=E91B0CE9-0C1B-4AC2-8A46-33F49B67E058
Adds a CodeQL suppression comment to specifically ignore the error raised by CodeQL.

Added CodeQL supression comment

---

src/cascadia/WindowsTerminal/WindowEmperor.cpp

Forgetti di spaghetti in #18215.
Closes #18324
* Launch through the start menu
* Explicitly minimize
* Then...
* Launch through the start menu again ✅
* Launch via wtd.exe in Win+R ✅
* Launch via wtd.exe in another Terminal ✅
* Launch via handoff ✅

Pass foreground rights to the emperor

---

src/winconpty/package/native/Microsoft.Windows.Console.ConPTY.targets
src/winconpty/package/winconpty.nuspec

win10-* is no longer a valid rid
https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/rid-graph
This package would fail to install the dependencies to the correct location in .net 8 and later by default.  win-x64 is a valid runtime id in prior .net versions so I think this should be back compat.   
Without this the package fails to do its job on newer builds unless `  <UseRidGraph>true</UseRidGraph>` and the user sets `win10-x64` as their RID in their project file.

Fix Microsoft.Windows.Console.ConPTY package runtime identifiers

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/WindowEmperor.cpp
src/cascadia/WindowsTerminal/WindowEmperor.h

Fixes
* Cursor vanishing, because
```cpp
CoreWindow::GetForCurrentThread().PointerCursor()
```
returned a non-null, but still invisible cursor.
* Alt/F7 not dispatching to newly created windows, because the
`WM_ACTIVATE` message now arrives before the `AppHost` is initialized.
This caused the messages to be delivered to old windows.
* Windows Terminal blocking expedited shutdown,
because we return `FALSE` on non-`ENDSESSION_CLOSEAPP` messages.
Closes #18331
Closes #18335
* Cursor still doesn't really vanish for me in the first place ✅
* Alt/F7 work in new windows without triggering old ones ✅

Fix multiple regressions since #18215

---

src/host/VtIo.cpp
src/inc/LibraryIncludes.h
src/renderer/atlas/AtlasEngine.api.cpp
src/renderer/atlas/pch.h
src/renderer/gdi/gdirenderer.hpp
src/renderer/gdi/paint.cpp
src/server/WaitBlock.h
src/terminal/adapter/SixelParser.hpp
src/types/colorTable.cpp
src/types/inc/colorTable.hpp

and fix non-standard compliant code
Fix some potential issues that may be exposed after upgrading the compiler and dependencies. For detailed explanations, see the comments.

Remove dependencies on unstable MSVC/STL extensions,

---

src/cascadia/QueryExtension/ExtensionPalette.cpp

Keeps any text in the input box around if Terminal Chat is dismissed. The original behaviour was consistent with the way the command palette works but it does not quite make sense for the chat. 
Input is not lost when the chat pane is closed

No longer clear the input box when Terminal chat is dismissed

---

src/cascadia/ut_app/TerminalApp.Unit.Tests.manifest
src/interactivity/win32/window.cpp
src/interactivity/win32/window.hpp
src/interactivity/win32/windowproc.cpp

The conhost window uses the window message WM_GETDPISCALEDSIZE to scale its client rect non-linearly. This is done to keep the rows and columns from changing when the window changes (font sizes scale non-linearly). If you size the window such that the text perfectly fits the width (and cursor is on the first row of the next line), dragging the window between monitors with different DPIs should NOT change how much of the text fits on each line.
https://learn.microsoft.com/en-us/windows/win32/hidpi/wm-getdpiscaledsize
The current code is assuming that the size that should be scaled is the current window size. This is sometimes the case, for example when dragging a window between monitors, but it is not always the case. This message can sometimes contain a size that is different from the …

[conhost] Fix WM_GETDPISCALEDSIZE handler, use provided size instead of current window size

---

src/cascadia/WindowsTerminal/WindowEmperor.cpp

Adds a description and keyword for the `SessionBecameInteractive` event
Follow-up from #17682

Fix tag for SessionBecameInteractive event

---

README.md

After #15855, this repo no longer uses submodules. Removing instruction about needing to initialize them. 
#15855
N/A
Read the revised README and was able to F5 without running the submodule command.
N/A
N/A
- If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here
Repo docs, not real docs
N/A

Update README to remove reference to submodules

---

src/cascadia/WindowsTerminal/WindowEmperor.cpp
src/cascadia/WindowsTerminal/WindowEmperor.h

This fixes the bit check for key down and adds a few comments.
Closes #18331
Printing the resulting INPUT_RECORDs shows both key down and up events when pressing F7. Alt-Space now also works again.

Fix dispatching of system keys

---

src/cascadia/TerminalSettingsEditor/Appearances.cpp
src/cascadia/TerminalSettingsEditor/Appearances.h
src/cascadia/TerminalSettingsEditor/Appearances.idl
src/cascadia/TerminalSettingsEditor/Appearances.xaml
src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
src/cascadia/TerminalSettingsEditor/LaunchViewModel.h
src/cascadia/TerminalSettingsEditor/LaunchViewModel.idl
src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl
src/cascadia/TerminalSettingsEditor/Profiles_Base.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsEditor/SettingContainer.cpp
src/cascadia/TerminalSettingsEditor/SettingContainer.h
src/cascadia/TerminalSettingsEditor/SettingContainer.idl
src/cascadia/TerminalSettingsEditor/SettingContainerStyle.xaml

Fixes a few accessibility bugs in the SettingContainer previews. Main changes include:
- `SettingContainer` was considered a separate UIA element from the inner expander. It's been marked as `AccessibilityView=Raw` to "remove" it from the UIA tree.
- Added a `CurrentValueAccessibleName` property to the `SettingContainer` to expose the current value to the screen reader for `SettingContainer`s that have expanders. Non-expander `SetttingContainer`s already worked fine.
- Applied `CurrentValueAccessibleName` to various settings throughout the settings UI for full coverage. Added a `CurrentValue` for the ones that were missing it.
- Removed a redundant/hidden tab stop in `Icon`
`Padding` was not updated since #18300 is handling that. This'll just automatically make it accessible.
Font axes …

Make SUI previews readable by screen readers

---

src/cascadia/TerminalSettingsEditor/NewTabMenu.xaml

There's an existing WinUI bug where a nested Grid has it's star-sizing ignored on Windows 10. This resulted in the New Tab Menu page looking weird on Windows 10. This PR fixes the layout issue by applying a max width to the first column, which will be clipped as necessary to make space for the second column.
Part of #18281
Validated the page looks good on Windows 10 and Windows 11, even after resizing the window.

[Windows 10] Fix layout in New Tab Menu page

---

src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.idl
src/cascadia/TerminalApp/TerminalWindow.h
src/cascadia/TerminalApp/TerminalWindow.idl
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h

Reroutes the `closeWindow` action to use the `CloseWindow()` method like the window's X button does. This includes logic to display the confirmation dialog.
Also removes `CloseRequested` as it was only used by this action handler. We already have `CloseWindowRequested` so we're just using that instead.
✅ `closeWindow` action while multiple tabs opened brings up the confirmation dialog
Closes #17613

Fix 'closeWindow' ignoring confirmation

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalCore/ICoreSettings.idl
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl
src/cascadia/TerminalSettingsEditor/Profiles_Terminal.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/TerminalSettingsModel/Profile.idl
src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.h
src/cascadia/inc/ControlProperties.h

This pull request introduces a new profile setting, `compatibility.allowOSC52`, which defaults to `true`. When disabled, it will not allow applications to write to the clipboard.
Security-minded folks may choose to disable it.

Let folks disable OSC 52

---

src/host/readDataCooked.cpp
src/host/readDataCooked.hpp
src/host/selectionInput.cpp

As explained in the comment on `_getViewportCursorPosition`, printing
to stdout after initiating a cooked stdin reads is a race condition
between the application and the terminal. But we can significantly
reduce the likelihood of this being obvious with this change.
Related to #18265
Possibly related to #18081
Execute the following Go code and start typing:
```go
package main
import (
"fmt"
"time"
)
func main() {
go func() {
time.Sleep(50 * time.Millisecond)
fmt.Printf("Here is a prompt! >")
}()
var text string
fmt.Scanln(&text)
}
```
Without this change the prompt will disappear,
and with this change in place, it'll work as expected. ✅

Reduce likelihood of races between stdout and cooked stdin reads

---

build/scripts/Set-LatestVCToolsVersion.ps1

Apparently, we were using the package containing the CRT _source code_ to determine the version of the tools.
Also apparently, VS does not guarantee that that package has the same version as the tools package.
We should use the version of the tools package instead.

build: change how we find  the latest VC tools version

---

doc/cascadia/profiles.schema.json

Fixes typo in `experimental.rightClickContextMenu` property description. Description should say right-click **pastes**, rather than **copies**.

Fix schema description

---

src/cascadia/TerminalSettingsEditor/Appearances.cpp

ConvergedAlignment stores vertical alignment to 0xF0 and horizontal alignment to 0x0F. These were accidentally backwards!
Closes #18479

Fix SUI crash when image alignment not centered

---

src/cascadia/TerminalControl/ControlInteractivity.cpp

Fixes a bug where VT mouse mode would round to the nearest cell when clicking the mouse button. 
The fix is to round to the nearest cell only when we're selecting text. The other scenarios affected are:
- clicking on a hyperlink
- vt mouse mode
- where the context menu is anchored
Really the most notable ones were the first two. So now, we use the position of the cell we clicked on. We only round for selection.
Follow-up to #18106
Opened Midnight Commander in Ubuntu and clicked between the two panes.
- Before: threshold was too early to switch between panes
- After: threshold is clearly separated between the outline of the two panes

Bugfix: only round to the nearest cell for selection

---

.github/actions/spelling/expect/expect.txt
src/renderer/gdi/state.cpp

When Sixel images are rendered, they're automatically scaled to match
the 10x20 cell size of the original hardware terminals. If this requires
the image to be scaled down, the default GDI stretching mode can produce
ugly visual artefacts, particularly for color images. This PR changes
the stretching mode to `COLORONCOLOR`, which looks considerably better,
but without impacting performance.
The initial Sixel implementation was added in PR #17421.
I've tested with a number of different images using a small font size to
trigger the downscaling, and I think the results are generally better,
although simple black on white images are still better with the default
mode (i.e. `BLACKONWHITE`), which is understandable.
I've also checked the performance with a variation of the [sixel-bench]
test, …

Improve quality of GDI image scaling

---

src/cascadia/TerminalSettingsModel/defaults.json

Campbell has been the default color scheme for a long time now,
but it has quite some issues with hue and chroma.
This PR introduces a new scheme which was created using the Oklab
color space to find colors with maximal distance to each other
and well distributed and consistent hue and chroma.
Because of this, I've named the scheme after the creator of Oklab.
 
Closes #17818

Add Oklab based color scheme "Ottosson"

---

src/winconpty/winconpty.cpp

Since the argument no longer exists.
Removes argument documentation of "wait" which no longer exists.

Remove outdated arg comment for `_ClosePseudoConsoleMembers`

---

.github/actions/spelling/allow/allow.txt
src/cascadia/TerminalSettingsModel/defaults.json

Okay, here is a challenge for the default color scheme.
This PR adds [Dimidium](https://github.com/dofuuz/dimidium) terminal color scheme.
#17818
#18502
I adjusted colors using [CAM16](https://en.wikipedia.org/wiki/Color_appearance_model#CAM16). I prioritized lightness so that all colors(especially blue) has appropriate contrast with the background.
[Brief information about the Dimidium color scheme](https://github.com/dofuuz/dimidium/blob/main/README.md)
[Detailed explanation on crafting the color scheme with CAM16](https://dofuuz.github.io/color/2024/03/17/dimidium-terminal-color-scheme.html)
🔍 [More preview](https://htmlpreview.github.io/?https://github.com/dofuuz/dimidium/blob/main/preview/tty-preview-nobold.html)

Add CAM16 based color scheme "Dimidium"

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Updates the resource strings for the GitHub Copilot description now that GitHub Copilot Free is a thing

Update GitHub Copilot description to include GitHub Copilot Free

---

src/host/VtIo.cpp
src/host/VtIo.hpp
src/host/srvinit.cpp

During startup we relinquish ownership of the console lock to wait for the DA1 response of the hosting terminal. The problem occurs if the hosting terminal disconnects during that time. The broken pipe will cause `VtIo` to send out `CTRL_CLOSE_EVENT` messages, but those won't achieve anything, because the first and only client hasn't even finished connecting yet. What we need to do instead is to return an error code.
In order to not use a bunch of booleans to control this behavior, I gave `VtIo` a state enum. This however required restructuring the calling code in order to not have a dozen states.
* Launch cmd.exe with ConPTY
* ...but leave the stdin pipe unbound (which will hang the DA1 request)
* Immediately kill the ConPTY session
* cmd.exe exits after clicking away the error message ✅

ConPTY: Fix shutdown if killed during startup

---

src/cascadia/WindowsTerminal/IslandWindow.cpp

Found this one completely randomly.
* Open 2 windows with 1 tab each
* Click the X button on the tab in the 1st window
* OpenConsole/etc. is cleaned up ✅

Fix leaking the contents of the first tab in the first window

---

src/cascadia/TerminalApp/TerminalPage.cpp

This is a theoretical fix for #18584 as I cannot reproduce the issue
anymore. It did happen briefly on one of my devices though, and at the
time I observed that it would persist a window with no startup actions.

Fix persistence of empty windows

---

src/cascadia/TerminalApp/TabBase.cpp
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalTab.cpp

WinUI asynchronously updates its tab view items, so it may happen that
we're given a `TabViewItem` that still contains a `TabBase` which has
actually already been removed. Regressed in #15924.
Closes #18581
* Close tabs rapidly with middle click
* No crash ✅

Fix a crash when closing tabs

---

src/cascadia/TerminalCore/TerminalSelection.cpp

There's already logic to tab to a hyperlink when we're in mark mode. We do this by looking at the automatically detected hyperlinks and finding the next one of interest. This adds an extra step afterwards to find any embedded hyperlinks and tab to them too.
Since embedded hyperlinks are stored as text attributes, we need to iterate through the buffer to find the hyperlink and it's buffer boundaries. This PR tries to reduce the workload of that by first finding the automatically detected hyperlinks (since that's a fairly quick process), then using the reduced search area to find the embedded hyperlink (if one exists).
In PowerShell, add an embedded hyperlink as such:
```powershell
${ESC}=[char]27
Write-Host "${ESC}]8;;https://github.com/microsoft/terminal${ESC}\This is a …
```

Add support for tabbing to embedded hyperlinks

---

src/host/srvinit.cpp
src/server/ApiMessage.cpp
src/server/ApiMessage.h
src/server/ConDrvDeviceComm.cpp
src/server/WaitBlock.cpp

When the server handle gets closed on conhost (= terminal is gone),
and e.g. PowerShell is used, we would previously log 6 error messages.
This PR reduces it to zero, by removing the 3 biggest offenders.

Reduce log spam on conhost exit

---

src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/TabPaletteItem.cpp
src/cascadia/TerminalApp/TerminalPage.cpp

* `_ApplyLanguageSettingChange` calls `PrimaryLanguageOverride`
(the WinRT API function) and we would call it every time a new
window is created. Now it's only called on settings load.
* `_RegisterTabEvents` would listen for "Content" changes which can
be null. `IVector::Append` throws if a null object is given.
In our case, it's null if the content got erased with nothing.
Additionally, this fixes a bug where we wouldn't call
`_ProcessLazySettingsChanges` on startup. This is important if the
settings file was changed while Windows Terminal wasn't running.
Lastly, there's a lifetime fix in this PR, which is a one-line change
and I didn't want to make a separate PR for that.

Fix two sources of runtime exceptions

---

src/cascadia/TerminalControl/ControlInteractivity.cpp

Missed a few `_getTerminalPosition()` on the first run. Disabled rounding for pointer movements and mouse wheel events (which are used for hyperlink hover detection and vt mouse mode). The only time we round now is...
- `SetEndSelectionPoint()` --> because we're updating a selection
- `ControlCore->LeftClickOnTerminal()` --> where all paths are used for selection*
*the only path that doesn't is `RepositionCursorWithMouse` being enabled, which also makes sense based on clicking around Notepad with a large font size.
Follow-up for #18486 
Closes #18595 
In large font size, play around with midnight commander and hover over hyperlink edges.

Bugfix: don't round to nearest cell for mouse movements and VT mouse mode

---

src/cascadia/LocalTests_TerminalApp/TabTests.cpp
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalWindow.cpp

I don't actually know why this is happening, because it doesn't
happen with startup actions specified in the settings file.
In any case, it's fixed with more delays.
Closes #18572
* Create a tab with 2 panes
* Tear it off into a new window
* New window has 1 tab with 2 panes ✅

Fix panes being dropped when tearing off tabs

---

src/cascadia/WindowsTerminal/WindowEmperor.cpp
src/cascadia/WindowsTerminal/WindowEmperor.h

Does what it says on the tin.
Closes #18525
* Enable persistence
* Close the last window
* Persisted ✅

Fix persistence of the last closed window

---

src/cascadia/TerminalApp/TerminalWindow.cpp
src/cascadia/TerminalApp/TerminalWindow.h

This can be considered "part 1" of fixing #18599: It prevents crashes (due to unhandled exceptions) by ensuring we only create 1 content dialog across all windows at a time. Sounds bad, but I tried it and it's not actually _that_ bad in practice (it's still really gross though).
The bad news is that I don't have a "part 2", because I can't figure out what's going on:
* Create 2 windows
* Open the About dialog in window 1
and right click the text
* Close the About dialog
* Open the About dialog in window 2
and right click the text
* WinUI will simply toss the focus to window 1
It appears as if context menus are permanently associated with the first window that uses them. It has nothing to do with whether a ContentDialog instance is reused (I tested that).
* Open 2 windows with 2 tabs each …

Fix dialogs not working across multiple windows

---

src/renderer/gdi/paint.cpp

CodeQL for paint.cpp
Some CodeQL for converting BOOL to HRESULT.
PolyBezier returns a BOOL instead of an HRESULT, so just refactoring how the pertaining function returns.
Built, ran all tests.

CodeQL: Prevent cast of BOOL to HRESULT

---

src/cascadia/TerminalConnection/CTerminalHandoff.cpp
src/cascadia/TerminalConnection/CTerminalHandoff.h
src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/ConptyConnection.h
src/cascadia/TerminalConnection/ConptyConnection.idl

I've received a dump from an affected user, and it showed that the layout event in TerminalPage was raised synchronously. This meant that during page initialization, the handoff listener was started while still being stuck inside the handoff listener. This resulted in a deadlock.
This PR fixes the issue by not holding the lock across handoff callback calls.
Closes #18634
* Can't repro ❌

Fix a handoff deadlock if layout completes synchronously

---

src/terminal/parser/InputStateMachineEngine.cpp
src/terminal/parser/InputStateMachineEngine.hpp

Since `WaitForDA1` would wait until `_deviceAttributes` is non-zero,
we must ensure it's actually non-zero at the end of this handler,
even if there are no parameters.
* Mod the Terminal DA1 to be `\x1b[?6c`. No hang ✅
* Mod the Terminal DA1 to be `\x1b[?61c`. No hang ✅

Fix a ConPTY startup hang with 0-param DA1 responses

---

src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/pch.h
src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsEditor/LaunchViewModel.cpp
src/cascadia/TerminalSettingsEditor/LaunchViewModel.h
src/cascadia/TerminalSettingsEditor/LaunchViewModel.idl

It turns out that we *can* support language overrides--fairly easily, in fact!--by simply changing the default Language qualifier.
I elected not to change how packaged language override works until we are certain this works properly everywhere. Consider it a healthy distrust of the Windows App Platform.
Closes #18419
Closes #18336
Closes #17619

Add support for language override to unpackaged/portable builds

---

src/cascadia/TerminalControl/dll/TerminalControl.vcxproj
src/host/exe/Host.EXE.vcxproj

Originally, I intended to switch to icuuc/icuin.dll to make it work on Windows 1703 as well... but it turns out that the 22621 or 26100 SDKs redirect those back to icu.dll. That's a poor decision on their part, as it means that developers can't use the old compatibility names.
VS supports Windows <=1903, so we need to be able to load. Fortunately, the aren't using any of the features that need ICU (search and URL detection). Therefore, we don't need to guard our ICU calls... yet.
ConPTY doesn't use them at all.
When we add support for URL detection and search to HwndTerminal, we'll need to revisit.

Delay-load icu so that we don't fail to start up on Windows <1903

---

.config/configuration.vsEnterprise.winget
.config/configuration.vsProfessional.winget
.config/configuration.winget
.github/actions/spelling/expect/expect.txt
README.md

PR adds a WinGet configuration file to install the necessary dependencies in order to build terminal locally. The configuration file enables developer mode, installs PowerShell 7, Visual Studio 2022 & all the required workloads from the project's [.vsconfig](https://github.com/microsoft/terminal/blob/main/.vsconfig) file (in accordance with the [dependencies listed](https://github.com/microsoft/terminal?tab=readme-ov-file#prerequisites) in the project's README).
Tested the configuration file by spinning up a clean Win11 Pro VM in azure and then doing the following:
1. Install latest WinGet on the VM using [WinGet sandbox script](https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget-on-windows-sandbox). Install git and clone the repo
2. Run `winget configure …

Add WinGet configuration file for building terminal

---

dep/vcpkg-overlay-ports/fmt/fix-write-batch.patch
dep/vcpkg-overlay-ports/fmt/portfile.cmake
dep/vcpkg-overlay-ports/fmt/usage
dep/vcpkg-overlay-ports/fmt/vcpkg.json
vcpkg.json

This pull request brings us up to fmt 11.1.4 and enables `FMT_PEDANTIC`.
`FMT_PEDANTIC` turns on `/W3`, which is required by our local feudal lords who will automatically file bugs on us if we don't build with enough warnings enabled.

vcpkg: add an overlay port for fmt 11.1.4; enable /W3

---

.github/actions/spelling/expect/expect.txt
build/pipelines/ob-nightly.yml
build/pipelines/templates-v2/job-deploy-to-azure-storage.yml
build/pipelines/templates-v2/job-publish-symbols-using-symbolrequestprod-api.yml
build/pipelines/templates-v2/pipeline-onebranch-full-release-build.yml
build/pipelines/templates-v2/steps-ensure-nuget-version.yml

This required removing connections during the build to `nuget.org` and `powershellgallery.com`.
The NuGet Tool task was downloading nuget from `nuget.org` unconditionally.
The `AzureFileCopy` task was downloading `Az.Accounts` from `powershellgallery.com` unconditionally.
Both of these tasks have better options nowadays.
Tested and passed in OneBranch on 2025-04-01.

build: run official builds with the R1 network isolation policy

---

src/renderer/base/RenderSettings.cpp
src/renderer/inc/RenderSettings.hpp
src/terminal/adapter/ITermDispatch.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/termDispatch.hpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp

This pull request adds support for resetting the various color table entries and xterm resource values back to their defaults.
Building on the default color table James introduced in #17879, it was relatively straightforward to add support for resetting specific entries.
This implementation cleaves tightly to observed behavior in xterm(379) rather than observed behavior in libvte(0.70.6). They differ in the following ways:
- xterm rejects any OSC [110..119] with any number of parameters; libvte accepts it but only resets the first color.
- When passed a list of color indices to reset in 104, xterm resets any colors up until the first one which fails to parse as an integer and does _not_ reset the rest; libvte resets all parseable color indices.
I was unable to verify how these reset …

Add support for OSC 104, 110, 111, 112 and 117 (resets)

---

src/cascadia/TerminalControl/ControlCore.cpp

* Added logic to convert file time to local time before printing.
* Used FileTimeToLocalFileTime() to convert file time to local time.
* The result is converted to system time again to ensure minimal impact on the method RestoreFromPath().
* Tested with different time zones.

Display local time instead of UTC while restoring previous session

---

src/cascadia/TerminalApp/SuggestionsControl.xaml

* Added a right margin to _descriptionComment  TextBlock of SuggestionsControl.xaml.
* This ensures that the vertical scrollbar will not cover the description text.
* Without margin
* With margin

Added right margin to description textblock of action suggestion

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalControl/IControlSettings.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalSettingsEditor/Resources/de-DE/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/es-ES/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/fr-FR/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/it-IT/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/ja-JP/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/pt-BR/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/qps-ploc/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/qps-ploca/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/qps-plocm/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/ru-RU/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/zh-CN/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/zh-TW/Resources.resw
src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h

Support drag-n-drop path translation in the style used by MinGW programs.  In particular for usage with shells like `ash` from busybox (https://frippery.org/busybox/).
Provides a new option "mingw" for "pathTranslationStyle".
Shown as "MinGW" with translation documented as `(C:\ -> C:/)` in the UI.
As per the other modes, this translates `\` to `/` but stops there.  There is no prefix/drive translation.
Run using `busybox ash` shell.  Dragged directories and files from both local disks and network shares onto terminal.  All were appropriately single quoted and had their backslashes replaced with forward slashes.  They were directly usable by the `ash` shell.
Language files containing the other options have been updated to include the new one.
- [Docs PR …

TerminalControl: Support MinGW path translation style (C:\ -> C:/)

---

src/host/_output.cpp
src/host/ut_host/VtIoTests.cpp

When we overwrite the attributes during the fill,
we must retain the lead/trail byte attributes.
Closes #18746
* Added a unit test ✅

Fix wide char support for WriteConsoleOutputAttribute

---

.github/actions/spelling/allow/allow.txt
src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/Resources/en-US/Resources.resw

Add additional information to 2 error scenarios when launching a different profile in the `ConptyConnection.cpp` file.
- Requires Elevation
- File Not Found
Created a profile that required elevation and verified the error message. Created profile that passed a made up command and verified the error message. Unable to test CTRL+C case, but included due to issue conversation. 
Closes #7186

Add 2 additional error messages

---

src/host/readDataCooked.cpp

Use DECSC/DECRC and XTPUSHSGR/XTPOPSGR while redrawing
popups, since they're drawn using the current popup colors.
I wish we could just use the reverse video rendition...
Closes #18742
* Run `color 3f` and then press F7
* Works fine in conhost (VtPipeTerm) ✅
* Works as expected (black background) in VS Code ✅

Backup and restore attributes during cooked reads

---

src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalCore/Terminal.cpp

Fixes a bug where the color selection actions would color one more character than they needed to.
Also fixes a bug where if mark mode was used to create the selection, a dangling y-beam would be left over after executing the action.
 
Regressed in #18106
- `TextBuffer::SpanLength` was only used once (in `Terminal::ColorSelection`). All it really did was call `Viewport::CompareInBounds`. So I deduplicated it.
- Funny enough, the +1 added there was no longer correct because the incoming coordinates were switched from an inclusive range to an exclusive range.
- To fix the dangling y-beam, I added a call to `_updateSelectionUI` in `ControlCore::ColorSelection`. This heuristic is used throughout the file for other selection-related functions.
✅ color selection action highlights reference(s) to …

Fix color selection off-by-one error and dangling Y-beam

---

src/cascadia/TerminalApp/Remoting.cpp
src/cascadia/TerminalApp/Remoting.h
src/cascadia/TerminalApp/TerminalPage.cpp

This fixes two issues:
* An unused `_cwd` property that should've been `CurrentDirectory`
* A cwd override that was applied even if there wasn't an override
Closes #18637
* Launch WT, then run `wtd -d ..`
* Launches in the expected relative path ✅

Fix cwd not applying on launch

---

policies/WindowsTerminal.admx
policies/en-US/WindowsTerminal.adml

This PR implements a policy definition for setting/enforcing the default terminal application.
GitHub (issues):
- https://github.com/microsoft/terminal/issues/18302
- https://github.com/microsoft/terminal/discussions/18303
Docs:
- https://support.microsoft.com/en-us/windows/command-prompt-and-windows-powershell-for-windows-11-6453ce98-da91-476f-8651-5c14d5777c20
- https://github.com/microsoft/terminal/discussions/13153#discussioncomment-6064759
This PR adds a new policy definition to the ADMX templates for settings the default Terminal application in Windows.
> [!Note]
> This PR does not change any code of Windows, Console Host or WIndows Terminal. It only adds the definiton for a new policy to the templates.
I got the registry values form the documentation and by testing the values.
The …

[Enterprise, GPO] Add "Default Terminal app" policy to definition template

---

src/renderer/base/renderer.cpp
src/renderer/base/renderer.hpp
src/renderer/base/thread.cpp
src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/adaptDispatch.cpp

Now that we have passthrough mode (#17510), as well as the render thread
rewrite (#18632), adding support for DECSET 2026 is a piece of cake.
Closes #8331
* Run `btop` via ssh in a huge window
* Open the Options menu
* No flicker ✅
* Run the following in PowerShell 7+:
```pwsh
1..10000 | % { Write-Host -NoNewline ("`e[?2026h" + "foobar`r`e[K$_" * 10000 + "`e[?2026l") }
```
* "foobar" is not visible ❌
* The number count goes up smoothly ❌

Implement DECSET 2026 - Synchronized Output

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/MainPage.h
src/cascadia/TerminalSettingsEditor/MainPage.xaml

The "open JSON" button in the settings UI wasn't working when invoked via accessibility tools (specifically Narrator in scan mode and Voice Access). For some reason, in those scenarios, neither the `Tapped` or `KeyDown` event were hit!
This PR adds the logic to open the json file via the `ItemInvoked` event instead. The `Tapped` and `KeyDown` handlers were removed to prevent a redundant `OpenJson` event being raised.
Additionally, `SelectsOnInvoked` was set to `False` on the "open JSON" nav item. This prevents the selection pill from moving to the nav item, which feels more correct.
The following scenarios are confirmed to open the JSON
✅ Mouse click
✅ Keyboard (Spacebar and Enter)
✅ Voice Access
✅ Narrator in scan mode
For all of these (except Voice Access), I've confirmed that holding …

[SUI] Improve accessibility to open json

---

.github/policies/resourceManagement.yml

Wanted to learn how the bot works, so I went ahead cleaned up the bot rules a bit. List of changes:
- added a description for each rule (and move it to the top of the rule)
- added all the "Area-" labels and sorted
If there's any new rules you'd like added, let me know. 🎁

Add descriptions and new labels to the bot rules

---

src/cascadia/TerminalControl/ControlCore.cpp
src/renderer/base/RenderSettings.cpp
src/renderer/base/renderer.cpp
src/renderer/base/renderer.hpp
src/renderer/inc/RenderSettings.hpp
src/terminal/adapter/adaptDispatch.cpp

`RenderSettings` already stores `DECSCNM` (reversed screen),
so it only makes sense to also store DECSET 2026 there.
* Same as in #18826 ✅

Use RenderSettings for DECSET 2026 - Synchronized Output

---

tools/ReleaseEngineering/ServicingPipeline.ps1

We used to cherry-pick every commit that had even one card in "To Cherry Pick", even if it was also referenced by a card in "Rejected" or even "To Consider".
Now we will warn and skip those commits.
I took this opportunity to add a bit of an object model for servicing cards as well as prettify the output.
That allowed us to add a list of cards that were ignored due to having no commits, and display little icons for each type of card.

ServicingPipeline: make a bunch of quality of life improvements

---

build/pipelines/templates-v2/job-merge-msix-into-bundle.yml
tools/ReleaseEngineering/Draft-TerminalReleases.ps1

I've been doing this manually. It is time for me to do it not-manually.

release-engineering: package (during build) and upload GPO templates

---

src/buffer/out/ImageSlice.cpp
src/buffer/out/ImageSlice.hpp

This PR fixes two cases where image content wasn't correctly erased when
overwritten.
1. When legacy console APIs fill an area of the buffer using a starting
coordinate and a length, the affected area could potentially wrap over
multiple rows, but we were only erasing the overwritten image content on
the first affected row.
2. When copying an area of the buffer with text content over another
area that contained image content, the image in the target area would
sometimes not be erased, because we ignored the `_eraseCells` return
value which indicated that the image slice needed to be removed.
The original code was from the Sixel implementation in PR #17421.
I've manually verified that these two cases are now working as expected.

Fix two image erasure bugs

---

src/terminal/adapter/ut_adapter/MouseInputTest.cpp
src/terminal/input/mouseInput.cpp
src/terminal/input/terminalInput.hpp

According to the documentation, the final character of an SGR mouse
report is meant to be `M` for a button press and `m` for a button
release. However it isn't clear what the final character should be for
motion events, and we were using an `m` if there weren't any buttons
held down at the time, while all other terminals used an `M`, regardless
of the button state.
This PR updates our implementation to match what everyone else is doing,
since our interpretation of the spec was causing problems for some apps.
I've manually tested the new behavior in Vttest, and confirmed that our
mouse reports now match Xterm more closely, and I've tested with v0.42.0
of Zellij, which was previous glitching badly in Windows Terminal, but
now works correctly.
I've also updated our unit tests for the SGR …

Fix SGR mouse movement reports

---

src/cascadia/TerminalControl/HwndTerminal.cpp
src/cascadia/TerminalControl/HwndTerminal.hpp

This fixes two issues in the WPF terminal control:
- The emoji picker and other IME candidate windows didn't show up in the right place
- Submitting an emoji via the emoji picker would result in two win32 input mode events with a VK of 65535 and the surrogate pair halves.
I am not sure I did the right thing with the thread TSF handle...

wpf: use the new TSF implementation

---

src/cascadia/WindowsTerminal/AppHost.cpp

Fixes a bug where `Monarch::_peasants` would not be updated when the last window was closed and `compatibility.allowHeadless` was enabled.
The bug was originally caused by `Monarch::_peasants` still holding on to a reference to itself in the list. Normally, a `Peasant` was removed from the list via the `WindowManager::SignalClose()` (aka `Monarch::SignalClose()`) function. However, `AppHost::_CloseRequested()` would omit that call when the last window was closing.
Normally, that makes sense. It's the last window, so let's call `AppHost::_quit()` --> `WindowManager::QuitAll()` --> `Monarch::QuitAll()`, where we just call `Peasant::Quit()` on all the peasants and the monarch and we call it a day. Everything should be cleaned up and if we need a new session, we'll create a new `Monarch` …

[1.22] Fix teardown when 'allowHeadless' is enabled

---

src/cascadia/TerminalCore/TerminalSelection.cpp
src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp

This fixes #18877, This iteratively checks to see if a line is wrapped and moves up or down accordingly.
**Current behavior:** When a user triple-clicks on a line that’s visually wrapped by the terminal, only the single physical row that was clicked gets selected.
**Expected behavior:** A triple-click like in xterm, should select the entire logical line including all of its wrapped segments, from the true start through its true end, regardless of where the wrap occurred.
**Why it matters:** Logical line selection is what users expect when they’re trying to grab one command or output block in full. Limiting the selection to just the current physical row can lead to copy/paste mistakes and a confusing experience whenever a long line wraps.
I ran the existing tests using …

FIX#18877 Triple-click to select logical line

---

.config/configuration.vsEnterprise.winget
.config/configuration.vsProfessional.winget
.config/configuration.winget

Using the [Microsoft.Windows.Settings](https://www.powershellgallery.com/packages/Microsoft.Windows.Settings/) module is the now the recommended way of configuring Windows Settings, including developer mode.
Verified that setting developer mode with the new resource works as intended

Use Microsoft.Windows.Settings module for enabling developer mode

---

src/buffer/out/TextAttribute.cpp
src/buffer/out/TextAttribute.hpp
src/buffer/out/textBuffer.cpp
src/renderer/atlas/AtlasEngine.cpp

The `SGR 1` VT attribute can either be interpreted as a brighter color,
or as a bolder font, depending on the _Intense text style_ setting.
However, the concept of brightness only applies to the eight standard
ANSI colors, so when `SGR 1` is configured as _bright_, it has no effect
on the ITU T.416 colors (RGB and the 256 index colors).
To address that, we now interpret `SGR 1` as a bolder font when applied
to ITU colors, regardless of whether the _Intense text style_ option is
set to bold or not.
Note that this only applies to the Atlas render engine, since the GDI
engine doesn't support bold fonts.
I've manually tested `SGR 1` applied to different color formats with the
_Intense text style_ option set to _None_, and confirmed that the text
is now rendered with a bold font for ITU …

Render SGR 1 as bold when used with ITU colors

---

src/cascadia/TerminalSettingsEditor/Appearances.cpp
src/cascadia/TerminalSettingsEditor/Appearances.h
src/cascadia/TerminalSettingsEditor/Appearances.idl
src/cascadia/TerminalSettingsEditor/Appearances.xaml
src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl
src/cascadia/TerminalSettingsEditor/Profiles_Advanced.xaml
src/cascadia/TerminalSettingsEditor/Profiles_Base.xaml
src/cascadia/TerminalSettingsEditor/Profiles_Terminal.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Went through the settings UI and checked which other setting containers were missing a preview. Here's the list:
- starting directory
- tab title
- background image
- answerback message
- bell style
Adding them was fairly straightforward. Tried to reuse existing resources when possible. The general pattern was to add a "Current<Setting>" or "<Setting>Preview" getter that just created the human-readable format of the setting.
✅ value is shown (including special values!)
✅ each of these work with a screen reader
Closes #18576

Fix remaining settings container previews in SUI

---

.github/actions/spelling/allow/apis.txt
src/cascadia/TerminalControl/HwndTerminal.cpp
src/cascadia/TerminalControl/HwndTerminal.hpp

We never hooked up this callback!
This allows a CLI application to emit text directly to the clipboard.

wpf: allow OSC 52 to write the clipboard

---

src/terminal/adapter/adaptDispatch.cpp

Possibly closes #8976? Let's let the CI decide which of our tests it breaks.

Speculative: remove overeager line wrapping in AdaptDispatch

---

src/cascadia/WindowsTerminal/WindowEmperor.cpp

I finally realized the missing piece.
We need to clear the state array unconditionally, as otherwise it won't get cleared. Duh.
Closes #18584
* Craft a state.json with a layout
* Launch Terminal while the feature is disabled
* state.json is cleaned up on exit ✅

Clean up persisted windows after the feature is disabled

---

src/cascadia/TerminalSettingsModel/ActionMap.cpp
src/cascadia/TerminalSettingsModel/ActionMap.h

Adds logic such that local snippets from .wt.json files are imported not only at the current directory, but also in the parent directories.
Spec: https://github.com/microsoft/terminal/blob/main/doc/specs/%231595%20-%20Suggestions%20UI/Snippets.md
`D:\test\.wt.json`: contains `Hello --> hello (parent)`
`D:\test\inner_dir\.wt.json`: contains `Hello --> hello`
- In `D:\test\`...
- ✅ `Hello` command outputs `hello (parent)`
- ✅ commands from `inner_dir` not shown
- In `D:\test\inner_dir\`...
- ✅ `Hello` command outputs `hello`
- ✅ commands from `D:\test` are shown
Closes #17805

Load .wt.json snippets from parent directories

---

src/cascadia/TerminalSettingsEditor/Compatibility.cpp
src/cascadia/TerminalSettingsEditor/Compatibility.h
src/cascadia/TerminalSettingsEditor/Compatibility.idl
src/cascadia/TerminalSettingsEditor/Compatibility.xaml
src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettings.idl
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

Adds the ability to reset the settings.json file and application state via the Settings UI. Since these are destructive operations, the destructive styling is applied, as well as a confirmation prompt notifying the user that this occurs immediately.
✅ "reset settings" results in the correct contents for settings.json and state.json
✅ "reset cache" results in the correct contents for state.json
Closes #947

Add reset cache and settings buttons to SUI

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalApp/AboutDialog.xaml
src/cascadia/TerminalApp/CommandPalette.xaml
src/cascadia/TerminalApp/MarkdownPaneContent.cpp
src/cascadia/TerminalApp/MarkdownPaneContent.xaml
src/cascadia/TerminalApp/ScratchpadContent.cpp
src/cascadia/TerminalApp/SnippetsPaneContent.xaml
src/cascadia/TerminalApp/SuggestionsControl.xaml
src/cascadia/TerminalApp/TabHeaderControl.xaml
src/cascadia/TerminalApp/TabRowControl.xaml
src/cascadia/TerminalApp/TerminalPage.xaml
src/cascadia/TerminalApp/TerminalWindow.cpp
src/cascadia/TerminalControl/SearchBoxControl.xaml
src/cascadia/TerminalControl/TermControl.xaml
src/cascadia/TerminalSettingsEditor/CommonResources.xaml
src/cascadia/UIHelpers/Resources/en-US/Resources.resw
src/cascadia/UIHelpers/TextMenuFlyout.cpp
src/cascadia/UIHelpers/TextMenuFlyout.h
src/cascadia/UIHelpers/TextMenuFlyout.idl
src/cascadia/UIHelpers/UIHelpers.vcxproj
src/cascadia/UIHelpers/UIHelpers.vcxproj.filters
src/cascadia/UIHelpers/init.cpp
src/cascadia/UIHelpers/pch.h
src/cascadia/UIMarkdown/CodeBlock.xaml
src/cascadia/UIMarkdown/MarkdownToXaml.cpp
src/cascadia/UIMarkdown/UIMarkdown.vcxproj
src/cascadia/UIMarkdown/UIMarkdown.vcxproj.filters
src/cascadia/UIMarkdown/pch.h

This works around a bug in WinUI where it creates a single context menu/flyout for text elements per thread, not per `XamlRoot`, similar to many other areas. Since the `XamlRoot` cannot change after creation, this means that once you've opened the flyout, you're locked into that window (= XAML root) forever. You can't open the flyout in another window and once you've closed that window, you can't open it anywhere at all.
Closes #18599
* Flies out right click in the
* About dialog ✅
* Search dialog ✅
* Word delimiters setting ✅
* Launch size setting ✅
* Across two windows ✅

Implement custom text context menus to fix crashes

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/MatchProfilesEntry.cpp
src/cascadia/TerminalSettingsModel/MatchProfilesEntry.h

Applies some localization fixes for the regex strings and Settings_ResetApplicationState.HelpText.
Also renames the `_validateX()` functions to `_validateAndPopulateXRegex()` for clarity.

Apply localization and documentation fixes for regex code

---

src/host/consoleInformation.cpp
src/host/outputStream.cpp
src/host/server.h
src/interactivity/win32/Clipboard.cpp
src/interactivity/win32/CustomWindowMessages.h
src/interactivity/win32/clipboard.hpp
src/interactivity/win32/windowproc.cpp

This adds support for copying to the clipboard in conhost using the OSC
52 escape sequence, extending the original implementation which was for
Windows Terminal only.
The Windows Terminal implementation was added in PR #5823.
Because the clipboard can't be accessed from a background thread, this
works by saving the content in a global variable, and then posting a
custom message to the main GUI thread, which takes care of the actual
copy operation.
I've manually confirmed that tmux copy mode is now able to copy to the
system clipboard.

Add support for OSC 52 clipboard copy in conhost

---

src/terminal/adapter/SixelParser.cpp
src/terminal/adapter/SixelParser.hpp

This is an attempt to improve the correctness of the background fill
that the Sixel parser performs when an image is scrolled because it
doesn't fit on the screen.
This new behavior may not be exactly correct, but does at least match
the VT330 and VT340 hardware more closely than it did before.
The initial Sixel parser implementation was in PR #17421.
When a Sixel image has the background select parameter set to 0 or 2, it
fills the background up to the active raster attribute dimensions prior
to writing out any actual pixel data. But this fill operation is clamped
at the boundaries of the screen, so if the image doesn't fit, and needs
to scroll, we have to perform an additional fill at that point to cover
the background of the newly revealed rows (this is something we weren't
doing …

Improve correctness of Sixel background fill

---

.github/workflows/winget.yml

With the latest winget-create release, the preferred method for providing the GitHub token in CI/CD environment is via the environment variable `WINGET_CREATE_GITHUB_TOKEN`. Removed use of `--token` and switched to environment variable. See https://aka.ms/winget-create-token for details.

Update WinGet publish script to use env var instead of --token

---

src/cascadia/TerminalApp/Pane.cpp

Fixes a bug where the swap panes action would result in no content being focused!
The root cause of this bug was that in `Pane::SwapPanes()`, we would do the following:
```
if (const auto focus = first->GetActivePane())
focus->_Focus();
```
However, `_Focus` would exit early if the pane was `_lastActive`, which was always the case because `GetActivePane()` would retrieve the `_lastActive` pane!
To fix this, we just manually focus the pane and its content.
Closes #18184
1. Split pane (type content in them to more easily differentiate them)
2. Swap panes
3. ✅ Focus is on the same pane content as before (which should now be in a different position)

Manually focus panes after swapping them

---

src/renderer/atlas/README.md

Replace newline literal in AtlasEngine Readme with `<br>` tag so the newline is actually rendered rather than a `\n` literal. 
None.
If the intention of the \n in the was not a newline please disregard this pull request :)

Replace newline literal in AtlasEngine Readme with <br> tag.

---

src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp

Right now, image validation accepts web-sourced icons (boo) and rejects images whose paths begin with `\\?\`. In addition, it will warn the user for things out of their control like images set by fragments.
This pull request adds a filesystem path validator (which accepts images with fully-qualified paths and UNC paths), makes the URI validator reject any web-origin URIs (only `file` and `ms-*` are allowable), and suppresses warnings for any images that were not _directly_ set by the user.
Since we want to avoid using fragment images that fail validation, we no longer `Clear` each image property but rather set it to the blank or fallback value.
This does **not** actually add support for images at absolute paths beginning with `\\?\`. Such images are still rejected by `Image` and the other …

Gently rework icon and background image validation

---

build/pipelines/templates-v2/job-publish-symbols-using-symbolrequestprod-api.yml

They made secure strings the default. Doing it this way maintains compatibility with the version before and after the default changed.

build: adjust for changes in the Az.Accounts module

---

src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/terminal/adapter/ITermDispatch.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/termDispatch.hpp
src/terminal/adapter/ut_adapter/adapterTest.cpp

Some applications that make use of the `OSC 52` clipboard sequence will
only do so if they can be certain that the terminal actually has that
functionality. Indicating our support for `OSC 52` in the `DA1` report
will give them an easy way to detect that.
`OSC 52` support was added to Windows Terminal in issue #5823, and to
ConHost in issue #18949.
Support for writing to the clipboard is indicated in the primary device
attributes report by the extension parameter `52`. This is obviously not
a standard DEC extension, but it's one that's been agreed upon by a
number of modern terminals. The extension is only reported when writing
to the clipboard is actually permitted (Windows Terminal has an option
to disable that).
I've updated the Device Attributes unit test to check that we're
reporting …

Indicate support for OSC 52 in the DA1 report

---

doc/cascadia/profiles.schema.json

WSL now generates profiles with the source named `Microsoft.WSL`, this PR adds the value to the profile schema.
https://github.com/microsoft/terminal/issues/18231

Add Microsoft.WSL profile source to schema

---

tools/OpenConsole.psm1

Enable build support for ARM64 in the build script
NONE
ARM64 is becoming more prevalent, and terminal should be the first tool we reach for on that platform as well. This pull request lights up build support on ARM64 in the build script. 
it built successfully following the documentation on my Snapdragon Surface Laptop :)

Add arm64 build support using the build script

---

src/cascadia/TerminalApp/Pane.cpp

Fixes a crash when multiple panes were closed simultaneously (i.e. using broadcast input).
The root cause of this crash was that we would get a null pointer exception when trying to access a member/function off of a null `_content`. This is because `Pane::_CloseChild()` would always pass over the content from the non-closed pane and attempt to hook everything up to it.
The fix was to operate similarly to `Pane::Close()` and raise a `Closed` event and return early. Since there's no alternative content to attach to, might as well just close the entire pane. This propagates up the stack of listeners to update the UI appropriately and close the parent pane and eventually the entire tab, if necessary.
 
Closes #18071
Closes #17432
1. Open 2 panes
2. Use broadcast input to send "exit" to both …

Fix crash when closing multiple panes simultaneously

---

src/cascadia/WindowsTerminal/WindowEmperor.cpp
src/cascadia/WindowsTerminal/WindowEmperor.h

The crash occurs because WinRT `abort()`s when it encounters
a `std::wstring_view` without null-terminator.
Closes #19093
* Set `wtd` as the default terminal
* Launch `cmd`
* Launch `wtd`
* 2 windows ✅

Fix a crash during commandline handoff

---

src/cascadia/WindowsTerminal/WindowEmperor.cpp

Right now, we do not use a sufficiently unique name to disambiguate Terminal instances running on the same desktop.
Mutexes (mutants) are named objects that live in the user's session, under `Sessions\1\BaseNamedObjects` (for the local desktop session). When multiple users are logged into the same session--such as with "Run as different user"--they share a local BaseNamedObjects namespace. Ugh.
We cannot use [`CreatePrivateNamespace`] as it requires a boundary descriptor, and the only boundary descriptors supported by the current API are based on package identity. I also fear that `CreatePrivateNamespace` is subject to a race condition with `OpenPrivateNamespace`; Create will not Open an existing one, so we would need to back off and retry either opening or creating. Yuck.
After this …

Include the hash of the SID in the Window Class and Mutant

---

custom.props
src/cascadia/ElevateShim/elevate-shim.vcxproj
src/cascadia/ShellExtension/WindowsTerminalShellExt.vcxproj
src/cascadia/TerminalApp/dll/TerminalApp.vcxproj
src/cascadia/TerminalAzBridge/TerminalAzBridge.vcxproj
src/cascadia/TerminalConnection/TerminalConnection.vcxproj
src/cascadia/TerminalControl/dll/TerminalControl.vcxproj
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
src/cascadia/TerminalSettingsModel/dll/Microsoft.Terminal.Settings.Model.vcxproj
src/cascadia/UIHelpers/UIHelpers.vcxproj
src/cascadia/UIMarkdown/UIMarkdown.vcxproj
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/cascadia/wt/wt.vcxproj
src/host/exe/Host.EXE.vcxproj
src/propsheet/propsheet.vcxproj
src/winconpty/dll/winconptydll.vcxproj

version: fix the LCID in our VERSIONINFO, add descriptions to each file

---

src/tsf/Implementation.cpp

If an IME provider sets both `crText` and `crBk` we should respect this,
but the previous logic would incorrectly assert for `crLine != TF_CT_NONE`.
❌ I'm not aware which TSF even sets these colors in a
way that's compatible with us in the first place...

Improve TSF color filtering logic (re: QQPinyin)

---

src/cascadia/WinRTUtils/LibraryResources.cpp
src/cascadia/WinRTUtils/ScopedResourceLoader.cpp
src/cascadia/WinRTUtils/inc/LibraryResources.h
src/cascadia/WinRTUtils/inc/ScopedResourceLoader.h

This pull request elevates ScopedResourceLoader to the API surface of LibraryResources, which will allow any library resource consumer to directly interact with its resource loader.
One of those new interactions is to make a sub-context with a specific narrowed-down qualifier. Like this:
```c++
auto englishOnlyLoader = GetLibraryResourceLoader().WithQualifier(L"language", L"en-us");
/* auto foo = */ englishOnlyLoader.GetLocalizedString(USES_RESOURCE(L"AppName"));
```

Expose a library's Resource Loader, allow a user to "subset" it

---

.github/workflows/spelling2.yml

The logic currently present occasionally fails to enable reporting for some PRs.

ci: turn on SARIF reporting unconditionally for check-spelling

---

src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/features.xml

Disables a controversial part of #19044.
Refs #19075

Re-enable web-source icons in Stable and Preview builds

---

src/cascadia/TerminalApp/FilteredCommand.cpp
src/cascadia/TerminalApp/FilteredCommand.h

PR #17330 changed FilteredCommand so that FilteredTask could derive from it. It also **did not** implement FilteredTask as a derived class.
We've been carrying around the debt of a decision we un-decided for like a year.

Undo the damage done to FilteredCommand in #17330

---

src/cascadia/TerminalApp/BasePaletteItem.h

In #19132, we introduced caching for BasePaletteItem::ResolvedIcon as a late optimization.
We actually can't cache those, because they're UI elements, with parents and relationships and all. When you filter a list with icons and the list elements change physical position, they're assigned new templates-- and new parents.
Fixes e7939bb4e

Remove IconElement caching from PaletteItem

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalControl/ControlInteractivity.cpp
src/cascadia/TerminalControl/IControlSettings.idl
src/cascadia/TerminalSettingsEditor/Interaction.xaml
src/cascadia/TerminalSettingsEditor/InteractionViewModel.h
src/cascadia/TerminalSettingsEditor/InteractionViewModel.idl
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
src/cascadia/TerminalSettingsModel/MTSMSettings.h
src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.h
src/cascadia/inc/ControlProperties.h

This PR introduces an experimental setting that allows to toggle opacity changes with scrolling.
#3793
By default, holding Ctrl + Shift while scrolling changes the terminal's opacity. This PR adds an option to disable that behavior.
I built the project locally and verified that the new feature works as intended.
- If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: https://github.com/MicrosoftDocs/terminal/pull/873

feat: add option to adjust opacity with Ctrl+Shift+scroll

---

src/cascadia/TerminalApp/TerminalPage.cpp

Adds new telemetry events to track traffic through the new tab menu. Specifically, the following events are added:
- `NewTabMenuDefaultButtonClicked`: Event emitted when the default button from the new tab split button is invoked
- `NewTabMenuOpened`: Event emitted when the new tab menu is opened
- `NewTabMenuClosed`: Event emitted when the new tab menu is closed
- `NewTabMenuItemClicked`: Event emitted when an item from the new tab menu is invoked
- Has an `ItemType` parameter that can be set to `Settings`, `CommandPalette`, `About, `Profile`, `Action`
- Has a `TabCount` parameter that keeps tracked of the number of tabs in the window before changing the state
- `NewTabMenuCreatedNewTerminalSession`: Event emitted when a new terminal was created via the new tab menu
- Has a `SessionType` …

Add telemetry for new tab menu traffic

---

src/cascadia/TerminalSettingsEditor/Actions.xaml

Reverts most of the styling changes done in #19001 to the key chords displayed in the SUI's Actions page. The `CornerRadius` was kept at the updated value of `ControlCornerRadius` for consistency.
The only other changes in #19001 that were kept for this page include:
- `EditButtonIconSize`: 15 --> 14
- `AccentEditButtonStyle` > `Padding`: 3 --> 4
- Command name's `FontWeight` reduced to `Normal`
- `AddNewButton` > `Margin` added (set to `0,12,0,0` to provide spacing between breadcrumb header and button)

Update key chord styling in actions page

---

src/cascadia/TerminalSettingsModel/Command.cpp
src/cascadia/TerminalSettingsModel/Command.h

Right now, when a Command's name is `{"key": "ResourceName"}` we resolve the resource immediately at load time. That prevents us from looking it up later in another language if we need to.
This pull request introduces an intermediate representation for command names which is be resolved during `Command::Name`.
Refs #7039

Command: realize resource-key names when they are requested, not at load

---

src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/MinMaxCloseControl.cpp
src/cascadia/TerminalApp/MinMaxCloseControl.h
src/cascadia/TerminalApp/Tab.cpp
src/cascadia/TerminalApp/Tab.h
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.cpp
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.h
src/cascadia/TerminalSettingsModel/ApplicationState.cpp
src/cascadia/TerminalSettingsModel/ApplicationState.h
src/cascadia/WinRTUtils/inc/ThrottledFunc.h
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h
src/inc/til/throttled_func.h
src/til/ut_til/throttled_func.cpp

You can now create throttled functions which trigger both on the leading
and trailing edge. This was then also ported to `ThrottledFunc` for
`DispatcherQueue`s and used for title/taskbar updates.
Closes #19188
* In CMD run:
```batch
FOR /L %N IN () DO @echo %time%
```
* Doesn't hang the UI ✅

Extend lead/trail edge support for throttled_func

---

src/cascadia/TerminalControl/ControlCore.cpp

https://github.com/microsoft/terminal/issues/19181
- Modify the cursor repositioning logic to check if a selection is in progress
- Only reposition the cursor when the mouse is used for positioning, not during selection operations

fix(ControlCore): prevent cursor repositioning during mouse selection

---

src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.idl
src/cascadia/TerminalApp/TerminalWindow.h
src/cascadia/TerminalApp/TerminalWindow.idl
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h

We already have the logic to fall back when the setting is disabled, we just _also_ had a terrible eventing architecture and never used the `Title` getter that was smart enough to figure it out.
This pull request somewhat disentangles the mess that is title handling. For example, TerminalPage had a facility to get its current title! It was never used. Once we started using it, it wouldn't work for the Settings page... because it only read the title out of the active control.
Closes #12871
Closes #19139 (superseded)

Fix title being stuck after toggling "showTerminalTitleInTitlebar"

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

As explained in the diff itself.
Closes #13136
* In conhost, with `wtd` not running, execute:
```pwsh
1..10 | % { wt -w 1 nt --title=$_ pwsh -NoExit -Command "Get-Date -Format HH:mm:ss.ffff" }
```
* Every tab is up and running immediately ✅

Throttle incoming handoffs so WinUI can layout them

---

dep/nuget/packages.config
src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/dll/TerminalApp.vcxproj
src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/ConptyConnection.h
src/cascadia/TerminalConnection/ConptyConnection.idl
src/common.nugetversions.targets
src/host/srvinit.cpp

Windows 11 uses some additional signals to determine what the user cares
about and give it a bit of a QoS boost. One of those signals is whether
it is associated with a window that is in the foreground or which has
input focus.
Association today takes two forms:
- Process has a window which is in the foreground or which has input
focus
- Process has a *parent* that meets the above criterion.
Console applications that are spawned "inside" terminal by handoff do
not fall into either bucket. They don't have a window. Their parent is
`dllhost` or `explorer`, who is definitely not in focus.
We are piloting a new API that allows us to associate those processes
with Terminal's window.
When Terminal is in focus, it will attach every process from the active
tab to its QoS group. This means that …

Use a new API to propagate foreground state to child processes

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalSettingsModel/ApplicationState.h
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

Automatically generates an "SSH" folder in the new tab menu that contains all profiles generated by the SSH profile generator. This folder is created if the SSH generator created some profiles and the folder hasn't been created before. Detecting if the folder was generated is done via the new `bool ApplicationState::SSHFolderGenerated`. The logic is similar to `SettingsLoader::DisableDeletedProfiles()`.
Found a bug on new tab menu's folder inlining feature where we were counting the number of raw entries to determine whether to inline or not. Since the folder only contained the match profiles entry, this bug made it so that the profile entries would always be inlined. The fix was very simple: count the number of _resolved_ entries instead of the raw entries. This can be pulled into its …

Add SSH folder to NTM for dynamic profiles

---

src/host/screenInfo.cpp

`IsOn` is the blinker on/off state, which `IsVisible`
is the actual cursor visibility on/off state.
* Run bash/zsh in WSL
* (Repeatedly) Quickly scroll right and press A-Z
* Scrolls to the left ✅

Fix SnapOnOutput not always snapping

---

src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

Fixes a few issues with some telemetry events:
- The macro is organized as such: `TraceLoggingX(value, argName, [argDescription])`. A few args had a description set on the spot where the name should be. I added a name for a few of these.
- `TraceLoggingBool` --> `TraceLoggingInt32` for `themeChoice` (we shouldn't be casting the evaluated int as a bool; it loses some of the data we care about)
- improves the description for `themeChoice` to include information about the legacy values
Checked through all our telemetry events and all of the args have a proper name set. We tend to use `TraceLoggingValue` too which automatically figures out the type that's being used, so that's also handled.

Fix names and types of a few telemetry events

---

src/host/selection.cpp
src/host/selection.hpp
src/host/selectionInput.cpp
src/host/selectionState.cpp

Fixes a bug where copying and coloring selected text would be off by one. This was introduced in #18106 when selection was updated to be stored as an exclusive range. `Selection::_RegenerateSelectionSpans()` was updated then, but copying text and coloring selection didn't rely on selection spans.
Copying text relies on `GetSelectionAnchors()`. This function has now been updated to increment the bottom-right point of the selection. This way, `GetTextSpans()` operates on the expected _exclusive_ range.
Coloring selection relies on `TextBuffer::SearchText()`, `TextBuffer::GetTextRects` and `GetSelectionSpans()`. Both `Selection::ColorSelection()` were updated to use `rect` over `inclusive_rect` to emphasize that they are exclusive ranges. Converting between the two improves clarity and fixes …

[Conhost] Fix off-by-1 error when copying and coloring selections

---

src/cascadia/TerminalSettingsEditor/Appearances.xaml
src/cascadia/TerminalSettingsEditor/CommonResources.xaml
src/cascadia/TerminalSettingsEditor/Profiles_Appearance.xaml

The unfocused appearance section in the settings UI looks a little off. Specifically, the header was too large (larger than the breadcrumbs!) and the button was weirdly aligned.
This PR reduces the size of the header and creates a style in CommonResources that manages it. This is the only place it's used, for now. A vertical alignment was added to the "create appearance" and "delete appearance" buttons to make them look better. The top margin of the "Text" header was also removed so that there isn't an awkward gap in the unfocused appearance section (the 32 that was there was moved to the bottom of the control preview so that that area remains unaffected.)
Follow-up from #19001

Fix unfocused appearance UI in settings

---

src/inc/til/env.h

It fails inside app containers (!) such as the one used by LocalTests.

env: don't explode when GetShortPathNameW fails

---

src/cascadia/WindowsTerminal/WindowEmperor.cpp
src/cascadia/WindowsTerminal/WindowEmperor.h

tl;dr: ~Apphost() may pump the message loop.
That's no bueno. See comments in the diff.
Additionally, this PR enables `_assertIsMainThread` in
release to trace down mysterious crashes in those builds.

Avoid reentrancy issues when dropping AppHost

---

src/cascadia/TerminalSettingsModel/defaults.json

- Add Selection BG color
- Make Bright white brighter
Final tune for Dimidium color scheme before its release.
#18563
I made little change to Dimidium color scheme.
- Adjusted "Bright white" slightly brighter, hoping it can be distinguished better from "White".
- Defined "Selection Background" color.
This will be the final tune for Dimidum color scheme.

Adjust "Dimidium" color scheme

---

src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalSettingsCache.cpp
src/cascadia/TerminalApp/TerminalSettingsCache.h
src/cascadia/TerminalApp/TerminalWindow.cpp
src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/ControlInteractivity.cpp
src/cascadia/TerminalControl/ControlInteractivity.h
src/cascadia/TerminalControl/ControlInteractivity.idl
src/cascadia/TerminalControl/IControlSettings.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl
src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.h
src/cascadia/TerminalSettingsModel/TerminalSettings.idl
src/cascadia/UnitTests_SettingsModel/TerminalSettingsTests.cpp
src/cascadia/inc/ControlProperties.h

For some reason, we went real hard on an architecture where the settings object contained the key bindings handler for the terminal. To make this work, we had to wind it through tons of layers: `TermControl`, `ControlInteractivity`, `ControlCore` (which saved it on `ControlSettings`), `ControlSettings`. Of course, because we have no clear delineation of concerns at the App layer this required us to put the bindings into the Settings Cache[^1].
Well, `TermControl` used `ControlCore` to get the Settings, to get the Bindings, to dispatch keys.
Yes, `TermControl` stored `IKeyBindings` down three layers _only to fish it back out and use it itself._
There is one place in the application where `TermControl`s are hooked up to their owners. Instead of passing the key bindings dispatcher in through …

Stop using Settings to shuttle IKeyBindings around

---

src/host/screenInfo.cpp
src/host/screenInfo.hpp

Fixes the crash and also makes `SnapOnOutput` a bit nicer.
Closes #19325
* Launch vim in WSL
* Exit
* No crash ✅

Fix a crash in _makeCursorVisible

---

src/cascadia/TerminalApp/Remoting.cpp
src/cascadia/TerminalApp/TerminalWindow.cpp

Closes #18815
* `wt -w 0 sp` splits the current tab ✅

Fix behavior of split-plane for existing windows

---

src/renderer/gdi/state.cpp

Fixed broken MSDN link in src/renderer/gdi/state.cpp line 611(was in line 591 at the time).
- Old link: `https://msdn.microsoft.com/en-us/library/ms969909.aspx` (404 error)
- New link: `https://learn.microsoft.com/en-us/windows/win32/gdi/character-widths`
- The original article was about GetCharABCWidths() and calculating text extents
- Microsoft has migrated this content to their new Learn platform
Closes #16439

 Fix broken MSDN link in gdi/state.cpp

---

build/pipelines/daily-loc-submission.yml

This is required as part of offboarding our non-user service account.

build: switch Touchdown to Federated Identity

---

src/cascadia/TerminalApp/Tab.cpp

If the progress state hasn't been set for more than 200ms, we shouldn't even bother flickering the old state.
This prevents applications from making the tab (and the taskbar icon) flicker.
We were reviewing #19394 and decided that the _original_ behavior before Leonard's throttling fix was somewhat unfortunate as well. An application that sets an indeterminate state for 10ms and then clears it shouldn't be able to make any part of the application flicker, fast _or_ slow.
Removing the leading fire time from the throttled function ensures that it will only fire once every 200ms, and only with the state most recently set. It will not debounce (so setting the progress every 150ms will not prevent it from updating.)
Closes #19394

Remove the leading fire from the taskbar progress handler

---

doc/cascadia/profiles.schema.json

Fixes a couple of minor issues in the settings schema which can result in erroneous settings validation failures.
None
- `answerbackMessage`  
Permit `null` type (corresponds to the default value).
- `compatibility.input.forceVT`  
Add missing setting (previously was `experimental.input.forceVT`).
- `rendering.graphicsAPI`  
Add missing `automatic` enumeration value.
- Mark several settings as deprecated using the same format and direct the user to the updated settings to use.
Tested updated schema against configuration with above settings present.

Minor fixes to the settings schema
