microsoft/terminal

tools/ColorTool/ColorTool/Program.cs, tools/ColorTool/ColorTool/Resources.resx, tools/ColorTool/README.md
This adds an option `-c, --current` which outputs the colour table without specifying/applying a new scheme
=> Add an option to print the colour table for the current scheme

tools/ColorTool/ColorTool/XmlSchemeParser.cs
iTerm2 color schemes could not be parsed when using a non-english locale. This fixes the issue.
=> Use invariant culture for parsing double values

tools/ColorTool/build.bat
If msbuild is already on PATH, use that one instead of searching through known install locations. This way, if a user or contributor has already added msbuild to PATH (e.g. by running from a "Developer Command Prompt" for VS 2015 or 2017), the build uses the expected version of the tools.
=> Default to msbuild.exe on PATH if found

tools/ColorTool/ColorTool/Program.cs
Small change to fix typo in variable name.
=> Fix variable name (from quite to quiet).

README.md
This adds a badge for the master branch line CI of colortool.
=> Add build badge for color tool master.

tools/ColorTool/all.bat
all.bat doesn't work if you use build.bat to build the program, as all.bat looks for ct.exe rather than colortool.exe. Fortunately, fixing the batch file is almost as easy as working around its bug manually.
=> ColorTool: Fix the included all.bat batch file

tools/ColorTool/ColorTool/Program.cs
Unfortunately, when you run `.\colortool.exe --current`, you might notice that the color of the prompt printed after the program finishes is slightly different from what it was before you ran the program.
This changelist fixes the issue by restoring the old console colors after the program finishes printing the color table.
Testing: manual
=> ColorTool: Restore old console colors after printing the color table

tools/ColorTool/ColorTool/Resources.resx, tools/ColorTool/README.md
This just fixes a few minor typos in the README file and usage text for colortool.
=> Fix typos in colortool help message and README

tools/ColorTool/build.bat
The build file should check for Visual Studio Professional when trying to locate msbuild.exe.
=> Check for VS 2017 Professional in build.bat

tools/ColorTool/ColorTool/IniSchemeParser.cs, tools/ColorTool/ColorTool/Program.cs, tools/ColorTool/ColorTool/Resources.Designer.cs, tools/ColorTool/ColorTool/Resources.resx
As suggested by #6. `colortool -o <filename>` will write the current properties to `<filename>`, in ini file format.
=> Add a switch for exporting settings

tools/ColorTool/ColorTool/ConsoleAPI.cs, tools/ColorTool/ColorTool/Program.cs, tools/ColorTool/ColorTool/Resources.resx, tools/ColorTool/README.md
Right now there is no way to view the available color schemes that the user can use. This commit adds an option to do so.
=> Add option to view available color schemes

tools/ColorTool/ColorTool/ColorScheme.cs, tools/ColorTool/ColorTool/ColorTool.csproj, tools/ColorTool/ColorTool/ConsoleAPI.cs, tools/ColorTool/ColorTool/ISchemeParser.cs, tools/ColorTool/ColorTool/IniSchemeParser.cs, tools/ColorTool/ColorTool/Program.cs, tools/ColorTool/ColorTool/XmlSchemeParser.cs
This is an attempt to partially fix https://github.com/Microsoft/console/issues/23.
To wrap it up:
1. uint[] colorTable -> class ColorScheme.
2. XML scheme parser now reads foreground/background colors.
3. fg/bg color slots are actually designated with wAttributes field in the console info structure.
4. fg/bg color indices are selected based on color similarity -- WIP
=> colortool: add support for fg/bg color slot designation, and color approximation

tools/ColorTool/ColorTool/Program.cs
For use cases where ColorTool has been added to and invoked from PATH, for instance, using a relative path from the working directory to print schemes will result in an empty list. Instead, use the path of the ColorTool.exe to find installed schemes.
=> Change listing of available schemes to use directory of executable

tools/ColorTool/ColorTool/IniSchemeParser.cs, tools/ColorTool/ColorTool/Scheme.cs, tools/ColorTool/ColorTool/XmlSchemeParser.cs
This PR addresses the following to-do comment in the code by introducing `Scheme.GetSearchPaths` method that is then used from `IniSchemeParser` and `XmlSchemeParser`:
https://github.com/Microsoft/console/blob/f334ba68c94e974d8326f2f39ad89ab739761bd5/tools/ColorTool/ColorTool/IniSchemeParser.cs#L73-L75
=> Consolidate schemes path search code

tools/ColorTool/ColorTool/JsonParser.cs
concfg (https://github.com/lukesampson/concfg) is a tool that can import and export console settings. It includes a set of settings presets that includes color settings. This PR updates colortool to understand that format, so these presets can be used by colortool to change the colors of the current console session w/o affecting the defaults. 
Should close #62
=> Add support for parsing concfg presets

tools/ColorTool/ColorTool/Program.cs
Fixes UIntToColor to use the same BGR color ordering that the ColorScheme uses, so the -s --schemes output makes sense.
=> Fix UIntTocolor

tools/ColorTool/ColorTool/Program.cs
@adiviness tried writing on a non-writeable network share and got a nice stack exception dump off the top. 
As such, I'll wrap this with a try/catch and print the error message when the StreamWriter fails. He got an access denied, but I can think of a good dozen reasons this would fail. A catch all should be fine for now.
Also the string should be pre-localized.
=> Wrap file system export write in try/catch.

tools/ColorTool/ColorTool/Program.cs
Adjust version lookup to use file version info stamp which is automatically incremented/generated by engineering system.
=> Correct version lookup for ES autoincremented value

samples/ConPTY/MiniTerm/MiniTerm.sln, samples/ConPTY/MiniTerm/MiniTerm/App.config, samples/ConPTY/MiniTerm/MiniTerm/MiniTerm.csproj, samples/ConPTY/MiniTerm/MiniTerm/Native/ConsoleApi.cs, samples/ConPTY/MiniTerm/MiniTerm/Native/ProcessApi.cs, samples/ConPTY/MiniTerm/MiniTerm/Native/PseudoConsoleApi.cs, samples/ConPTY/MiniTerm/MiniTerm/Process.cs, samples/ConPTY/MiniTerm/MiniTerm/Processes/Process.cs, samples/ConPTY/MiniTerm/MiniTerm/Processes/ProcessFactory.cs, samples/ConPTY/MiniTerm/MiniTerm/Program.cs, samples/ConPTY/MiniTerm/MiniTerm/Properties/AssemblyInfo.cs, samples/ConPTY/MiniTerm/MiniTerm/PseudoConsole.cs, samples/ConPTY/MiniTerm/MiniTerm/PseudoConsolePipe.cs, samples/ConPTY/MiniTerm/MiniTerm/Terminal.cs, samples/ConPTY/MiniTerm/README.md
As I mentioned in https://github.com/Microsoft/console/issues/251, I've been working on a basic C# terminal that uses the new PseudoConsole APIs. It's at a point where I've fixed all the known bugs, and I think it could be a useful sample in this repo.
The demo is similar to the existing EchoCon example in that it uses the virtual terminal processing feature, starts up a pseudoconsole, and runs a command. It also handles ctrl-c and window exit.
I'd appreciate some advice on ways to improve it as I'm fairly inexperienced when it comes to writing terminals and pinvoking Windows APIs. The following areas might need some attention:
I've split this PR into three commits, the final commit will be the most interesting to review.
I've tested this with the following versions:
- OS: Windows 10 Pro …
=> Add csharp conpty sample

tools/ColorTool/signing/CopySignFiles.cmd, tools/ColorTool/signing/SignConfig.xml
We need the signing configuration for color tool when it runs through the build system to come from the Git repository instead of from another ancillary, non-source-controlled place.
=> Add signing configuration information to repository.

tools/ColorTool/ColorTool/ISchemeParser.cs, tools/ColorTool/ColorTool/IniSchemeParser.cs, tools/ColorTool/ColorTool/JsonParser.cs, tools/ColorTool/ColorTool/Program.cs, tools/ColorTool/ColorTool/Resources.resx, tools/ColorTool/ColorTool/XmlSchemeParser.cs
ColorTool now has three different color scheme parsers (.ini files, [concfg](https://github.com/lukesampson/concfg/tree/master/presets) JSON files and [itermcolors](https://iterm2colorschemes.com/) XML files). Because each scheme parser is tried in turn until one succeeds, any scheme parser that fails dumps useless error information to the console.
This change flips the `reportErrors` parameter of `ISchemeParser.ParseScheme` from true to false so these failed parse error messages are not printed by default. This PR also adds a new `--errors` or `-e` command line argument to enable error reporting for usage scenarios that need it.
=> Don't report scheme parse errors by default

tools/ColorTool/ColorTool/ColorScheme.cs, tools/ColorTool/ColorTool/ConsoleAttributes.cs, tools/ColorTool/ColorTool/IniSchemeParser.cs, tools/ColorTool/ColorTool/JsonParser.cs, tools/ColorTool/ColorTool/Program.cs, tools/ColorTool/ColorTool/XmlSchemeParser.cs
This is an proposal to store background and foreground color index.
I've added two section `screen` and `popup`. Both sections contain two keys `FORGROUND` and `BACKGROUND`. The assignable values are keys of the `table` section.
**sample**
```ini
[table]
DARK_BLACK = 12,12,12
DARK_BLUE = 0,55,218
DARK_GREEN = 19,161,14
DARK_CYAN = 58,150,221
DARK_RED = 197,15,31
DARK_MAGENTA = 1,36,86
DARK_YELLOW = 238,237,240
DARK_WHITE = 204,204,204
BRIGHT_BLACK = 118,118,118
BRIGHT_BLUE = 59,120,255
BRIGHT_GREEN = 22,198,12
BRIGHT_CYAN = 97,214,214
BRIGHT_RED = 231,72,86
BRIGHT_MAGENTA = 180,0,158
BRIGHT_YELLOW = 249,241,165
BRIGHT_WHITE = 242,242,242
[screen]
FOREGROUND = DARK_YELLOW
BACKGROUND = DARK_MAGENTA
[popup]
FOREGROUND = DARK_CYAN
BACKGROUND = BRIGHT_WHITE
[info]
name = powershell-default
```
=> Back and forground index export

tools/ReadConsoleInputStream/ConcurrentBoundedQueue.cs, tools/ReadConsoleInputStream/ConcurrentCircularQueue.cs, tools/ReadConsoleInputStream/NativeMethods.cs, tools/ReadConsoleInputStream/Program.cs, tools/ReadConsoleInputStream/ReadConsoleInputStream.cs, tools/ReadConsoleInputStream/ReadConsoleInputStreamDemo.csproj, tools/ReadConsoleInputStream/ReadConsoleInputStreamDemo.sln
This is a demo that shows how we can have a stream-oriented view of characters from the console
while also listening to console events like mouse, menu, focus, buffer/viewport(1) resize events.
This has always been tricky to do because ReadConsoleW/A doesn't allow retrieving events.
Only ReadConsoleInputW/A returns events, but isn't stream-oriented. Using both doesn't work because
ReadConsoleW/A flushes the input queue, meaning calls to ReadConsoleInputW/A will wait forever.
I do this by deriving a new Stream class which wraps ReadConsoleInputW and accepts a provider/consumer implementation of BlockingCollection<Kernel32.INPUT_RECORD>. This allows asynchronous monitoring of console events while simultaneously streaming the character input. I also use Mark Gravell's great …
=> ReadConsoleInputStream demo

tools/razzle.cmd
* Add few more possible locations of MSBuild, including VS2019 and VS2017 Professional
Confirmed working on VS2019 Community. Hopefully it does on others as well 😀 
Alternatively, write scripts in C# and use [Microsoft.Build.Locator package](https://docs.microsoft.com/en-gb/visualstudio/msbuild/updating-an-existing-application?view=vs-2019#use-microsoftbuildlocator)?
=> Add a few more possible locations of MSBuild to the razzle.cmd script

src/tools/ColorTool/schemes/deuteranopia.itermcolors
http://colororacle.cartography.ch/ moved to https://colororacle.org/
The old link is no longer accessible and this screenshot of the old link [(source)](https://sur.ly/i/colororacle.cartography.ch/) shows that this seems to be the new location:
Only comments are affected by this change.
=> fix: replaced outdated url

src/inc/LibraryIncludes.h
Without this, building in VS2019 results in multiple function is not a member of std errors. This fixes that. 😃 
EDIT: Important to mention I'm using VS2019 16.0.3 and build tools v. 142.
=> Fix build errors in VS2019 and Build Tools v142

NuGet.Config
Projects are looking for the packages under the path './packages', so we need to specify the path in Project config, in case it is restored by the User/Computer config.
=> Specify the NuGet packages folder

doc/cascadia/Keybindings-spec.md
Should use "its" rather than "it's".
=> Typos: Incorrect use of the possessive of "it".

src/cascadia/TerminalApp/Profile.cpp, src/cascadia/TerminalSettings/TerminalSettings.cpp
This should take care of the easy part of #460.
=> make closeOnExit: true the default

.gitmodules
The `Microsoft` org has been renamed to `microsoft`. While casing isn't an issue with GitHub, just correcting it in case some implementations are case-sensitive.
=> Lowercase GH org name in .gitmodules

.nuget/packages.config, README.md, tools/README.md, tools/bcz.cmd, tools/razzle.cmd
Instead of listing out all the locations for MSBuild, use the vswhere tool to find the location and add that directory to that path.
=> Update razzle to use vswhere (#13)

src/terminal/parser/ft_fuzzwrapper/main.cpp
Check null pointer before fclose because fclose(NULL) will lead to undefined behavior (CWE-476: NULL Pointer Dereference)
=> Check null pointer before fclose

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalCore/Terminal.cpp
Text selection is now removed when ESC is passed as input. Still unclear as to why selection did get cleared in CMD but not in any of the other options. The line `_terminal->ClearSelection()` was still called but, for whatever reason, the renderer didn't update. @miniksa Any thoughts on that? Just curious.
=> Bugfix: ESC didn't clear selection (except CMD)

build/pipelines/release.yml, build/pipelines/templates/build-console-int.yml, src/cascadia/CascadiaPackage/CascadiaPackage.wapproj, src/cascadia/CascadiaPackage/Package-Dev.appxmanifest, src/cascadia/CascadiaPackage/Resources/en-US/Resources.resw
To produce a package named `Microsoft.WindowsTerminal`, you must build with
`/p:WindowsTerminalReleaseBuild=true`.
Fixes #556.
=> Add a dev manifest, which will be used by default

src/cascadia/TerminalApp/App.cpp
Also add a few of the TODOs for similar areas. This change will do for now until we decide on a better story for closing the last tab.
=> Bugfix: don't allow closing last tab with middle click

.gitignore
The paths in this section of the .gitignore are not done the way I'd write them, but this one is clearly just wrong, right?
=> Fix the .gitignore for /Generated Files/

src/cascadia/TerminalControl/TermControl.cpp
I deleted the duplicate line in TermControl mentioned in #732
=> Fixed duplicate line in TermControl (#732)

src/interactivity/base/ApiDetector.cpp
It looks like the code at some point was trying to use RtlGetLastNtStatus, and this was changed to GetLastError but it's comparing against an NTSTATUS rather than the mapped Win32 error value.  This causes the program to AV on launch downlevel.
=> Fix downlevel support for traditional console

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalCore/terminalrenderdata.cpp
Resolves #665. Behaviour was discussed a bit there:
- When the window is not in focus, the cursor is not shown.
- When the user is typing, the cursor is constantly shown.
- Otherwise, the cursor blinks.
=> Blink the cursor

consolegit2gitfilters.json
This will remove Windows Terminal sources from any replications driven by git2git.
=> Exclude Windows Terminal sources and some other files from git2git

README.md
due to #558, app that is built from source will be named "Windows Terminal (Dev Build)” instead of "Windows Terminal (Preview)”
=> Reflect new AppNameDev in readme

src/cascadia/TerminalApp/CascadiaSettings.cpp
This is close I think but what I see in the One Half Light theme as described [here](https://packagecontrol.io/packages/One%20Half%20Color%20Schemes) duplicates the dark colors for the light colors.  On Windows w/colortool, I see that duplication for One Half Dark but not One Half Light.  Should I emulate what colortool is using for the schemes?  Also there are some "off-by-one" issues with the colortool scheme RGB values - at least as compared to the link above.  Not sure which I should follow.
=> Add one half color schemes

doc/WIL.md
- "Windows Internal Library" got named "Windows Implementation Library" for its GH release
- Fixed the links to point to the files in the WIL GH instead of the local copies.
- Left the rest of this as general guidance to how we use it.
=> Fix WIL doc summary

src/cascadia/TerminalApp/App.cpp
Fixes #787.
Considering we're just duping all feedback hub issues to github, lets cut out
the middleman and take them straight here.
=> Change the Feedback link to take you to github

src/cppwinrt.build.post.props
Added quotes to the commands that caused issues on my machine - Managed to build it and deploy with no issues.
=> Fixed a bug where terminal won't build when local user folder has spaces

README.md
The console-docs repository is very related to this one. I feel it should be linked somewhere prominently in this one.
=> Add link to related console-docs GH repository

src/buffer/out/textBuffer.cpp
I believe there are bunches of unnecessary copies in the codebase that can be converted into moves.  Is there any idea how we can find and fix them?
=> Convert copy to move

.gitignore, src/cascadia/TerminalApp/ColorScheme.cpp
microsoft/Terminal#711
Refactoring the terminal `color` array to a list of typed values to remove confusion as to what the values represent.
=> Amend Color array to typed values

tools/razzle.cmd
It will help to build project via scripts in case when only prerelease version of MSVS is installed.
=> tools: search for MSBuild in prerelease versions of MSVS

build/.nuget/packages.config, build/config/NuGet.config, build/pipelines/templates/build-console-steps.yml
This requires an additional service connection on the Azure Devops instance running our builds. That has been done.
**OPEN DISCUSSION**: We may want to mark this task optional so it doesn't fail the build when external folks set up their own AzDO instances?
Fixes #775.
=> ci: Restore Taef.TestAdapter before build to run tests in CI

src/cppwinrt.build.post.props
echo ( f | xcopy ) will not work, can get around with putting an '*' at the end, xcopy will treat then as file. This solutions builds 
fine on DE German machine.
=> fixed on build error xcopy on localized machines

src/cascadia/TerminalConnection/ConhostConnection.cpp, src/cascadia/TerminalConnection/ConhostConnection.h, src/cascadia/TerminalConnection/ConptyConnection.cpp, src/cascadia/TerminalConnection/ConptyConnection.h, src/host/CursorBlinker.cpp, src/host/PtySignalInputThread.cpp, src/host/PtySignalInputThread.hpp, src/host/VtInputThread.cpp, src/host/VtInputThread.hpp, src/host/srvinit.cpp, src/interactivity/onecore/ConsoleInputThread.cpp, src/interactivity/win32/ConsoleInputThread.cpp, src/interactivity/win32/find.cpp, src/interactivity/win32/windowio.cpp, src/interactivity/win32/windowio.hpp, src/propsheet/ColorControl.cpp, src/propsheet/ColorControl.h, src/propsheet/ColorsPage.cpp, src/propsheet/ColorsPage.h, src/propsheet/console.cpp, src/propsheet/console.h, src/propsheet/fontdlg.cpp, src/propsheet/misc.cpp, src/propsheet/preview.cpp, src/tools/echokey/main.cpp, src/tools/fontlist/main.cpp, src/tools/vtpipeterm/VtConsole.cpp, src/tools/vtpipeterm/VtConsole.hpp, src/tools/vtpipeterm/main.cpp
This PR fixes a bunch of callback function signatures so that they align with the signatures expected by Windows API. Most changes are from `__cdecl` to `__stdcall`, which matters on x86, but not on x64 or ARM64.
I find it hard to believe that conhost.exe as shipped in Windows would use callback functions with incorrect calling convention. Perhaps the version that ships with Windows is compiled with `/Gz` (`__stdcall`-by-default)? But OpenConsole.sln isn't.
All of these functions were found manually, so it's likely that there are more issues like this that I didn't find. It would be great if MSVC had a warning similar to GCC's `-Wcast-function-type`.
The only one signature incompatibility I found that wasn't eliminated was with `FONTENUMPROC` (I only fixed the calling convention, which is …
=> Fix signatures of some callback functions

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
This fix prevents text from being selected when the user clicks within the active terminal to re-focus the window. This brings the new terminal's behavior inline with the original powershell and cmd terminals. 
Fixes #670 
I tested this fix's behavior manually, but did ensure all unit tests are passing. 
The proposed changes may be a naive way of fixing the issue. I simply added a bool called _focused to the TermControl class which is set and unset during the respective GotFocus and LostFocus events. That bool is then checked whenever a new MouseClick event is encountered. If _focused is false during the MouseClick event, the MouseClick event handler immediately returns instead of handling the event normally. 
I did try to fix this issue using the GettingFocus event, but I could not find …
=> Fix #670: Terminal selects a char when bringing window to foreground

README.md, src/cascadia/WindowsTerminal/BaseWindow.h, src/cascadia/WindowsTerminal/IslandWindow.cpp, src/cascadia/WindowsTerminal/IslandWindow.h, src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
This change simplify the code that deals with sizing of the main xaml content.
Win32 API like SetWindowPos are always in physical coordinates (a.k.a screen coordinates)
while Xaml/UWP apis are always in logical coordinates (a.k.a client coordinates divided vi monitor DPI)
=> Simplify DPI logic

src/cascadia/TerminalApp/CascadiaSettings.cpp, src/cascadia/TerminalApp/GlobalAppSettings.cpp, src/cascadia/TerminalApp/GlobalAppSettings.h
Added the possibility to change the theme (dark/light/default) from the terminal settings
=> Added requestedTheme option into terminal settings

README.md
Update README.md to describe that opening the solution in VS2019 will prompt to automatically install missing development components.
=> Add behavior of .vsconfig to README

src/buffer/out/TextAttribute.cpp, src/buffer/out/UnicodeStorage.cpp, src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp, src/cascadia/TerminalApp/GlobalAppSettings.cpp, src/cascadia/TerminalApp/Profile.cpp, src/cascadia/TerminalApp/Tab.cpp, src/cascadia/TerminalConnection/ConhostConnection.cpp, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/WindowsTerminal/IslandWindow.cpp, src/cppwinrt.build.post.props, src/host/ConsoleArguments.cpp, src/host/VtIo.cpp, src/host/screenInfo.cpp, src/host/settings.cpp, src/host/srvinit.cpp, src/interactivity/win32/windowio.cpp, src/renderer/base/renderer.cpp, src/renderer/dx/DxRenderer.cpp, src/renderer/inc/RenderEngineBase.hpp, src/renderer/vt/XtermEngine.cpp, src/terminal/adapter/MouseInput.cpp, src/terminal/adapter/adaptDispatch.cpp, src/terminal/adapter/ut_adapter/adapterTest.cpp, src/terminal/parser/InputStateMachineEngine.cpp, src/terminal/parser/OutputStateMachineEngine.cpp, src/tools/vtpipeterm/VtConsole.cpp
Fix common typo `it's` ("it is") versus `its` in the code comments.
=> Fix `it's` versus `its` typo.

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
Related to #875, #745
This is a fix for one allocation site from the bug #875, but it may be related to the #745
Just use `std::unique_ptr<>` to hold a `Terminal` object.
=> Fix memory leak, use unique_ptr for Core::Terminal object, #875

README.md
Fix readme to show correct path of build tools
Fix `README.md` documentation in Build the Code section 
It might be fixed also by adding path to `bcz` in `razzle` command.
=> Update README.md - Build the Code section 

src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp, src/cascadia/TerminalApp/ColorScheme.cpp, src/cascadia/TerminalApp/GlobalAppSettings.cpp, src/cascadia/TerminalApp/GlobalAppSettings.h, src/cascadia/TerminalApp/Profile.cpp, src/cascadia/TerminalApp/Profile.h, src/host/ConsoleArguments.cpp, src/host/ConsoleArguments.hpp, src/host/ut_host/CodepointWidthDetectorTests.cpp
Instead of creating const static wstring objects which call malloc in the constructor, use wstring_view instead which just wraps the constant.
Simple code refactoring.
=> Use wstring_view for constants instead of wstring

README.md
Removed Windows Insider warning about 1903.
=> doc: remove statement about 1903 being available only on Insider

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalCore/Terminal.cpp
Padding used to offset selection. 
Created `_GetTerminalPosition()` to encompass some of this logic and prevent this kind of stuff from happening again. Also, just nice to wrap everything up into a function call. 
To the team: this was already somewhat reviewed back before we went on GitHub. So if you have a deja vu feeling, that's why.
=> Bugfix: padding offsets selection

src/cascadia/TerminalConnection/ConhostConnection.cpp, src/cascadia/TerminalConnection/ConhostConnection.h, src/cascadia/TerminalConnection/ConhostConnection.idl, src/cascadia/TerminalConnection/TerminalConnection.vcxproj, src/cascadia/TerminalConnection/pch.h, src/cascadia/TerminalControl/TermControl.cpp, src/inc/conpty-universal.h
Set a WT_SESSION environment variable to a unique guid on every new connection to allow shell consumers to detect Windows Terminal and uniquely identify the session.
Unknown.
Set a new 'WT_SESSION' environment variable when creating new terminal connections to allow shells to detect a unique Windows Terminal session.  The value of the variable is a stringified GUID as returned by
CoCreateGuid.
How verified:
- "razzle" & vs debug build
- runut
- opencon
- testcon
- manual inspection
Uncertain about what tests to add and where; all of the existing ones passed.
I did some basic research to try to ensure that "WT_SESSION" is a "unique", non-conflicting environment variable and so shouldn't cause any problems with any existing programs.  I'm certainly open to suggestions about the name though.
=> set identifying environment variable for new connections

src/host/utf8ToWideCharParser.cpp
std::unique_ptr.release() releases ownership and does not destroy an object.
Fix this issue by using reset(nullptr)
_Reset() is used only in the two places:
- in case of `_currentState == _State::Error` 
- when some exception has occured during parsing or converting
=> Utf8ToWideCharParser: Fix memory leak in case of error

src/cascadia/Microsoft.UI.Xaml.Markup/XamlApplication.cpp, src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/AppKeyBindings.cpp, src/cascadia/TerminalConnection/ConhostConnection.cpp, src/cascadia/TerminalConnection/EchoConnection.cpp, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalSettings/KeyChord.cpp, src/cascadia/TerminalSettings/TerminalSettings.cpp, src/cppwinrt.build.pre.props
Doing this speeds up local builds and makes module.g.cpp a lot simpler.
There's also some goodness around instantiating components that are local to your DLL not going through RoGetActivationFactory.
=> Enable C++/WinRT Optimizations for local component builds

src/propsheet/OptionsPage.cpp, src/propsheet/TerminalPage.cpp
found by cppcheck
[src/propsheet/OptionsPage.cpp:216] -> [src/propsheet/OptionsPage.cpp:242]: (warning) Either the condition 'lParam' is redundant or there is possible null pointer dereference: pshn.
[src/propsheet/TerminalPage.cpp:352] -> [src/propsheet/TerminalPage.cpp:378]: (warning) Either the condition 'lParam' is redundant or there is possible null pointer dereference: pshn.
=> fix couple of null pointer dereferences

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalCore/ITerminalApi.hpp, src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalCore/TerminalApi.cpp, src/cascadia/TerminalCore/TerminalDispatch.cpp, src/cascadia/TerminalCore/TerminalDispatch.hpp
Fixes #601
Added support for changing the cursor style via the [DECSCUSR](https://vt100.net/docs/vt510-rm/DECSCUSR.html) sequences. Higher values (e.g. `\x1b[\x37 q`) fall back to the legacy cursor.
Tested manually by invoking `wsl` and using `echo` commands (e.g. `echo -e -n "\x1b[\x32 q"`). 
Implemented the `SetCursorStyle()` method for `TerminalDispatch` and `TerminalApi`. Also, had to implement logic in `TermControl.cpp` to stop cursor blink when `cursor->IsBlinkingAllowed()` is `false`.
=> Added support for DECSCUSR sequences

src/cascadia/TerminalControl/TermControl.cpp
Fix #744, by making sure the TermControl always handles Tab keypresses. This will break keyboard navigation with tab, but considering that the shell almost _always_ wants tab as a character, this makes more sense. We should probably introduce another keybinding to manually get the focus out of the control, but that can be a follow-up.
=> Eat all tab keypresses no matter what.

src/cascadia/WindowsTerminal/IslandWindow.cpp, src/cascadia/WindowsTerminal/WindowsTerminal.manifest
While messing around with building with VS2019/14.2/etc, I noticed that the version we're using in the compatibility manifest doesn't match guidance for XAML Islands. This puts the version information from the public guidance into the manifest and leaves a link back to the page where I got this idea from.
I also found an unreferenced paramter thing that I'm fixing up qucik.
=> Update manifest to correct 1903 version, unref param fix

src/cascadia/TerminalControl/TermControl.cpp, src/renderer/base/thread.cpp
This PR makes a couple of small changes:
- In src\cascadia\TerminalControl\TermControl.cpp, the `TermControl::_InitializeTerminal()` method now initializes the `RenderThread` it creates before making any calls into the `Renderer` it also creates, as the Renderer has been given the RenderThread and expects it to be fully initialized.
- In src\renderer\base\thread.cpp, the RenderThread's members of type `HANDLE` are now initialized to NULL instead of INVALID_HANDLE_VALUE. The latter is not appropriate for these HANDLEs because they are returned from CreateThread() or CreateEvent(), which both return NULL on failure.
Using manual testing, I verified that either of these changes alone will resolve one or both of the 2 AppVerifier stops cited in the bug report. …
=> Fix #936: misuse of uninitialized objects causes AppVerifier breaks on Windows Terminal startup

src/cascadia/TerminalControl/TermControl.cpp
It's happening probably because the terminal gain focus before setting up timer, therefore starting the timer in the initialize phase should solve this problem.
=> Fix cursor not blinking in new tab

tools/razzle.cmd
This PR fixes issue #1045, in which if you had NuGet 5 on your PATH prior to running `tools\razzle.cmd`, then `tools\razzle.cmd & nuget restore` would fail with an "Illegal characters on path" error in NuGet.
Since version 5.0.2, NuGet has used the PATH environment variable to find MSBuild.exe before looking in other file paths. See NuGet change https://github.com/NuGet/NuGet.Client/commit/21f2b07f2c2e84afd6602c6743d356dae8880c0c (https://github.com/NuGet/NuGet.Client/pull/2687 ).
Unfortunately, in PR https://github.com/microsoft/terminal/pull/606 , `tools\razzle.cmd` was changed to add the MSBuild.exe folder path in _quotes_ to the PATH environment variable. Windows itself is fine with this (you can type `msbuild` and MSBuild runs), but some tools are not, including NuGet itself, so you …
=> Fix #1045 - Allow `tools\razzle & nuget restore` to work with NuGet 5 and later

src/renderer/dx/CustomTextLayout.cpp
Every screen update was causing memory usage to grow, seemingly unbounded. This appears to be due to a failure to decrement the reference count on a COM object.
The main allocation stack was:
|Commit   Stack | Size (MB)|
|-- | --|
[Root] | 3.609
ntdll.dll!RtlUserThreadStart | 3.609
kernel32.dll!BaseThreadInitThunk | 3.609
TerminalControl.dll!Microsoft::Console::Render::RenderThread::s_ThreadProc | 3.609
TerminalControl.dll!Microsoft::Console::Render::Renderer::PaintFrame | 3.609
TerminalControl.dll!Microsoft::Console::Render::Renderer::_PaintFrameForEngine | 3.609
TerminalControl.dll!Microsoft::Console::Render::Renderer::_PaintBufferOutput | 3.609
TerminalControl.dll!Microsoft::Console::Render::Renderer::_PaintBufferOutputHelper | 3.609 …
=> Use a ComPtr to avoid leaking font.

src/cascadia/WindowsTerminal/BaseWindow.h, src/cascadia/WindowsTerminal/IslandWindow.cpp, src/cascadia/WindowsTerminal/IslandWindow.h, src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp, src/cascadia/WindowsTerminal/NonClientIslandWindow.h, src/host/ConsoleArguments.hpp, src/host/VtIo.cpp, src/host/VtIo.hpp, src/host/cmdline.h, src/host/popup.cpp, src/host/popup.h, src/inc/test/CommonState.hpp, src/interactivity/inc/IConsoleControl.hpp, src/interactivity/win32/window.cpp, src/interactivity/win32/window.hpp, src/interactivity/win32/windowproc.cpp, src/propsheet/ColorControl.cpp, src/propsheet/ColorControl.h, src/propsheet/ColorsPage.cpp, src/propsheet/ColorsPage.h, src/propsheet/console.cpp, src/propsheet/console.h, src/propsheet/dbcs.cpp, src/propsheet/font.h, src/propsheet/fontdlg.cpp, src/propsheet/misc.cpp, src/propsheet/preview.cpp, src/propsheet/util.cpp, src/server/IoDispatchers.cpp, src/terminal/parser/ft_fuzzer/fuzzing_directed.h
Functions returning status codes should use [[nodiscard]] as [mentioned recently](https://github.com/microsoft/terminal/pull/897#discussion_r286205725) by @adiviness.
They should also use noexcept, but that's a much more invasive change, so this issue is just about [[nodiscard]].
#897 
- applied [[nodiscard]] for all HRESULT, LRESULT, and NTSTATUS functions
- fixed IntelliSense declaration complaints leading to function not
implemented warnings
- deleted declared but never implemented functions
- fixed unused parameter warnings
Please note I only checked for functions that had a declaration in a header file of some kind, so there might still be some functions only defined and used within .cpp files that don't have [[nodiscard]] applied.
How verified:
- bcz dbg
- opencon
- testcon
- VS2019 …
=> Apply [[nodiscard]] to functions returning error codes

src/terminal/input/terminalInput.cpp, src/terminal/input/terminalInput.hpp
Modernization and light cleanup of `TerminalInput.cpp` and `.hpp`.
Addresses Issue #685
=> Improvements to TerminalInput

src/cascadia/TerminalApp/Profile.cpp, src/tools/ColorTool/ColorTool/ColorScheme.cs, src/tools/ColorTool/ColorTool/ColorTable.cs, src/tools/ColorTool/ColorTool/ConsoleAttributes.cs, src/tools/ColorTool/ColorTool/Program.cs
Change the profile key to `colorScheme` (from `colorscheme`), to be consistent with other configuration options.
Update some comments in ColorTool to match.
This will likely break some existing profiles that use the old key.
=> "Color scheme" is two words

src/interactivity/onecore/ConsoleInputThread.cpp, src/renderer/wddmcon/WddmConRenderer.cpp
Synchronize the font between the WDDMCon Renderer and the SCREEN_INFORMATION when the OneCore Interactivity library starts up. #21717424
Retrieved from rs_onecore_dep_acioss ccca0315e7db34c09f5fcd9dfabae666ede1687b
Fixes #958.
=> inbox: Synchronize the font between WDDMCon and the SCREEN_INFORMATION

src/cascadia/TerminalApp/App.cpp
Use tabview.SelectedIndex for setting focus tab
=> Provide workaround for _GetFocusedTabIndex

src/cascadia/TerminalControl/TermControl.cpp
Fixes #1082 -- #853's fix of the acrylic background's flash/fade on _any_ settings change managed to cause a flash/fade on new tab creation.  This change removed both flash/fades.
#853 split background brush initialization from background color changes; due to the brush being constructed with a default color and then the color being initialized later, new tabs were getting the flash/fade that accompanies a re-focused fluent-style acrylic background.  This PR initializes the acrylic color at brush initialization to avoid the problem.
=> Fix acrylic brush flash/fade on new tab creation.

.github/PULL_REQUEST_TEMPLATE.md
While filling out PR templates, I've realized that I am making a strong effort to list my validation steps at the bottom in the "details and other comments" block. I feel like it would be good to make it explicit that we would like to see justification of how changes have been validated for functionality.
=> Add explicit "validation steps" to PR template

src/host/ft_host/API_InputTests.cpp
Flushes the input queue on `RawReadUnpacksCoalescedInputRecords` test to ensure that other tests cannot cause failure by leaving extraneous input records behind after they run.
This only failed in the core operating system gate tests. This is because those tests run a subset of the complete test suite (subtracting the ones that do not make sense in a core environment). Apparently one of the tests that was skipped that normally runs prior to the `UnpacksCoalesced` test ensured that the input queue was clean enough for this test to succeed. But in the core environment, the test that ran prior left stuff behind.
To resolve this, I'm making the `Coalesced` test more resilient by cleaning out the queue prior to performing its operations.
(Also, bonus, I'm fixing the typo in the name …
=> Flush input queue before running test. #1137

src/interactivity/base/VtApiRedirection.cpp, src/interactivity/onecore/BgfxEngine.cpp, src/interactivity/onecore/ConIoSrvComm.cpp, src/interactivity/onecore/ConsoleInputThread.cpp
These were introduced by:
- build warning with using wrong type in wil macro: #1105 
- namespace issues: #955 
These showed up in the official Windows build. I fixed them on that side to restore the build and now I'm bringing them back out.
=> Fix build warnings and namespace issues introduced by GitHub merge

src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/WindowsTerminal/AppHost.cpp, src/types/inc/utils.hpp, src/types/ut_types/Types.Unit.Tests.vcxproj, src/types/ut_types/UtilsTests.cpp, src/types/ut_types/sources, src/types/utils.cpp
Currently, the program crashes with a window width or height greater than 32767 (accounting for window decorations). This can be caused when the `initialRows` and `initialColumns` settings are set too high (also depends on the font width and height). This fixes the issue by not allowing the window to expand beyond 32767x32767.
#843 - relocated the ClampToShortMax helper for reuse elsewhere
I didn't add tests because there doesn't seem to be a test framework for the `WindowsTerminal` project yet.
=> Fix crash when window width and height are too high

src/cascadia/TerminalApp/CascadiaSettings.cpp, src/cascadia/TerminalApp/CascadiaSettings.h, src/cascadia/TerminalApp/TerminalApp.vcxproj, src/inc/LibraryIncludes.h
This code generates a list of WSL Distributions to be added to the drop down list.  It was tested manually with a setup holding a single WSL distribution.
While implementing the stream I was getting stuck in a loop inside of the `wfstream `functions when I ran past the end of the output.  None of the `wfstream`'s health functions seemed to be working properly (`::rdstate()`, `::eof()`, etc) so I used `peeknamedpipe `to get the length and stopped reading from the pipe before this became an issue.  I'd like to find a more clean method
=> Code to add WSLProfiles.

src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp
Related to #825, #1000.
The actual keybinding serialization for splitting new panes got lost in a bad merge. This adds it back.
=> Add the keybinding for panes back

src/terminal/parser/stateMachine.cpp, src/terminal/parser/ut_parser/OutputEngineTest.cpp
Adds support for any number of leading zeros in the parameter values of VT escape sequences. Tested manually, with [Vttest](https://invisible-island.net/vttest/), and with unit tests.
In the `StateMachine::_ActionParam` and `StateMachine::_ActionOscParam` methods, the parser would treat any parameter number with more than 5 digits as being the maximum value. This PR add checks which prevent leading zeros from contributing to that count, so the 5 digit limit now only applies to _significant_ digits.
* I've tested in the WSL bash shell with escape sequences containing many leading zeros, e.g.: 
`printf "\033[0000000032mGREEN?\033[m\n"`.
* I've confirmed that the leading zeros test in [Vttest](https://invisible-island.net/vttest/) now works (the last screen in the _Test of cursor …
=> Support any number of leading zeros in VT parameter values

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
This commit introduces a few automatic event revokers and implements staged Close for TermControl's constituent components. It also fixes an issue in reading the title from a tab with no focused control.
Fixes #1198, #1188.
I've opened and closed a number of tabs at a number of speeds, I can neither get it to crash _nor_ get it to leak console hosts and shells and a bunch of memory.
=> Properly manage teardown state in TermControl

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
Accounting padding when calculating the initial window size
Set `"padding": "100"` and observe the window becomes larger
Set `"padding": "100, 200"` and observe the window becomes larger
Set `"padding": "50, 100, 150, 200"` and observe the window becomes larger
=> Accounting padding when calculating the initial window size

tools/OpenConsole.psm1
take advantage of the switch parameter on the Cmdlet Get-VSSetupInstance from the vssetup module.
Get-VSSetupInstance  -All -Prerelease
=> add support for the -Prerelease VS locations

src/cascadia/TerminalConnection/ConhostConnection.cpp, src/tools/vtpipeterm/VtConsole.cpp
I try to fix what looked as a "FIXME" to me (under question), and a crash when using the test-app VtPipeTerm.
I would like to have feedback on this commit:
```
Cascadia/TerminalConnection: Close the output thread on exit.
It seems that TerminateThread() is available in the code...
```
The following one concerns VtPipeTerm:
```
VtPipeTerm: Don't crash when closing the app.
- Gracefully handle ReadFile returning false (usually because of ERROR_BROKEN_PIPE on exit).
- Minor whitespace formatting.
```
Manual tests only, by starting, interacting with, and closing the programs.
=> Minor fixes

src/cascadia/CascadiaPackage/Package-Dev.appxmanifest, src/cascadia/CascadiaPackage/Package.appxmanifest, src/cascadia/CascadiaPackage/Resources/en-US/Resources.resw
Note that the word "Windows Terminal" is way too long for a medium size tile, and thus will be truncated by Windows. I choose "Terminal" as the short name for tiles, but I can revert that if you prefer to leave the app name as it is.
Example of a truncated tile:
Current implementation
=> Show name on startmenu tile

src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/UnitTests_TerminalCore/InputTest.cpp, src/cascadia/UnitTests_TerminalCore/UnitTests.vcxproj
MapVirtualKey will give us the capitalized version of the char.
However, if shift isn't pressed, we want to send the lowercase version.
I added a test for this case.
=> Don't always send an uppercase letter for Alt+key

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
- capturing the SwapChainPanel and ScrollBar separately:
- it used to be that the root would take pointer events. So both the scroll bar AND the terminal would respond to a mouse drag on the scroll bar. Yuck!
- Renamed MouseClickHandler and MouseMovedHandler to more generic names (since they handle touch events too).
So, this fixes #950, but also doesn't. The reason #950 crashes is because the copy is waaaaaay too big. This will make it so that you can't make the selection that unreasonably big anymore. That said, there's still other ways to make massive copy selections so I think there's two relevant issues here:
- #1246 Copy large selection --> crash
- #1247 While selecting, dragging mouse over top/bottom border scrolls.
=> Captured pointer for SwapChainPanel and ScrollBar separately

src/cascadia/TerminalCore/Terminal.cpp
The selection anchors would become outside of the new size. They didn't matter for rendering the selection, but they would crash on the copy because we would actually try to read the buffer in a non-existent space.
Solution: clamp the anchors at RENDER TIME
That way, if we have the window resize again AND the anchors are valid, draw them appropriately.
I think this is better than just clearing a selection after a resize event, BUT if you disagree, I guess we can add that in pretty easily.
#1165 specifically mentions resizing so I'll close that one. Just be aware that there is a chance #1246  could be what's happening too.
- clamp when you're extracting data from buffer
- also moved the `_buffer->GetSize().RightInclusive()` out of the for loop so I guess it's more performant? 
1. Maximize …
=> Bugfix: crash on copying resized selection

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/CascadiaSettings.h, src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp, src/cascadia/TerminalApp/pch.h
This commit drops all of the special packaged app code in
CascadiaSettingsSerialization. It can all be replaced with passing
KF_FLAG_FORCE_APP_DATA_REDIRECTION to SHGetKnownFolderPath, which will
automatically handle the different paths used in packaged context.
We'll still store profiles.json under %APPDATA%\Microsoft\Windows
Terminal in an unpackaged context.
I've also taken the liberty of fixing a settings reload crash. Using the
Application storage APIs would cause us to throw an exception when
profiles.json was deleted, which it absolutely was for certain editors
that do an atomic replace.
Because we're not using W.S.A any more, this cuts down our load time
significantly and fixes all of our known STA/MTA-on-startup issues.
Fixes #1102, #1292.
=> Switch away from Windows.Storage.ApplicationData

src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
We need `FILE_SHARE_READ | FILE_SHARE_WRITE` on _both_ calls to `CreateFile`, so that we can properly watch the file for reloads.
Without these, when the file reloaded, we'd fail to open the file, think that it's because the file doesn't exist, create the default settings, and then we'd blow away the user's settings.
Fixes #1325
=> CreateFile with the right flags

src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalCore/TerminalSelection.cpp
This was a side effect of #905. But applies the same logic #1254. We were trying to get buffer data at a location that doesn't exist for the buffer. Removed the `noexcept`s from the expand selection functions.
The fix is simple enough. Just clamp the Y value of the selection to be between 0 and the mutable viewport's height. I tried using the Viewport's Clamp method but we're doing some weird transforms so I found that it's just easiest to do it manually (and slightly differently).
As an extra benefit, now if you're all the way at the top of the buffer and you try making a selection past the top, the x-value still updates as you move. The same thing applies to the bottom when you're at the bottom of the buffer.
- create a selection expanding past the top of the window
- do same selection …
=> Bugfix: vertical selection out of bounds

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/App.h
This commit introduces a 50ms debounce so that we stop flapping around while text editors are making directory changes.
Fixes #1329.
* Write from VSCode (hold down <kbd>Ctrl+S</kbd>, go mad with power)
* Write from vim
* Write invalid settings
* Run multiple terminals simultaneously and do the above.
=> Allow file modifications to quiet down before reloading settings

src/cascadia/TerminalApp/App.cpp
Make about dialog content copyable
Wrap aboutText with a selectable text block.
=> Make about dialog content copyable

src/renderer/dx/DxRenderer.cpp, src/renderer/dx/DxRenderer.hpp
This PR enables a software rendering fallback for the DX renderer in the case that hardware acceleration fails. This is primarily useful for Hyper-V environments where hardware acceleration is not guaranteed to exist.
This will be useful for future work to enable the DX renderer to run on windows 7 since win7 virtual machines do not/cannot have hardware acceleration unlike windows 10 machines
The PR does two things:
- Fallback to `D3D_DRIVER_TYPE_WARP` if `D3D_DRIVER_TYPE_HARDWARE` fails.
- pass `NULL` as the adapter instead of creating the default adapter ourselves.
I ran this as part of a larger codechange to enable win7 support. The software fallback worked correctly on win7.
=> fallback to software rendering

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/App.h, src/cascadia/TerminalApp/App.idl, src/cascadia/TerminalApp/pch.h, src/cascadia/WindowsTerminal/AppHost.cpp, src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj, src/cascadia/WindowsTerminal/pch.h
Fix issue [1380](https://github.com/microsoft/terminal/issues/1380)
[1380](https://github.com/microsoft/terminal/issues/1380)
The order of destruction is incorrect:
Construction: 1. XamlApp, 2. XamlIsland
Destruction: 1. XamlApp, 2. XamlIsland, it should be 1. Xamlsland, 2. XamlApp
Manually debugged that the Xaml core is de-initialized correctly.
=> Fix a bug where Terminal may crash or hang at shutdown

src/cppwinrt.build.pre.props
Having the AppContainer bit enabled makes us fail the Windows App
Certification Kit test required to submit to the store.
Manual, local WACK.
=> Disable the AppContainer bit on our C++/WinRT binaries

doc/bot.md
Added new labeling rule for issues in PR and for adding the resolution tag when a fix is committed.
=> Update bot doc for In-PR label rule

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalCore/ITerminalInput.hpp, src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/UnitTests_TerminalCore/InputTest.cpp, src/terminal/adapter/ut_adapter/inputTest.cpp
Let's start fixing #521 and the currently broken state of AltGr combinations, as it heavily affects many non-US users of this project.
I'm about 100% sure that this PR is not going to fix #521 by itself, but it's a start. 🙂
If others wan't to contribute to this PR, please feel free to do so. I'll gladly grant push permissions to my fork.
If you want to view the diff here on GitHub I recommend enabling "Hide whitespace changes" in the diff viewer.
This PR fixes all immediate/obvious issues in regards to AltGr for me in all types of shells I know.
I think it's fairly easy to see why it works, since I simply delegate the handling to `WM_CHAR` instead.
=> Fixed #521 - AltGr combinations not working

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/App.h, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalControl/TermControl.idl
We want TermControl to be agnostic to the type of connection, so the connection initialization has been moved to TerminalApp. 
The TermControl constructor has been modified to take in a connection, thus TermControl does not need to initialize a connection anymore. Instead, TerminalApp initializes the connection and passes it into the TermControl constructor. Thus once we start allowing different types of connections (an Azure connection for example), the detection of the type of connection only needs to happen in TerminalApp.
=> App now initializes the connection instead of term control.

src/cascadia/TerminalApp/Pane.cpp
Fixes revoking of old close event handlers after a pane is closed (issue #1278).
Currently, when a pane with non-leaf sibling is closed, various close event handlers are incorrectly revoked leading to dangling references. These are dereferenced next time another close event occurs (i.e. closing a 2nd pane) and causes Terminal to crash.
Additionally it revokes event handlers on old panes and controls (as occurs when a leaf pane is closed).
Tested manually. If I understand correctly, an automated test could be written after the framework in #1164 lands.
=> Revoke old event handlers correctly on pane close

src/cascadia/TerminalApp/CascadiaSettings.cpp
Changed the foreground color from #F2F2F2 to #CCCCCC.
I changed where foreground is set in CascadiaSettings.cpp, from #F2F2F2 : RGB(242, 242, 242) to #CCCCCC : RGB(204, 204, 204).
As detailed in the bug, this slightly reduces the brightness of the default/foreground color of the Campbell color scheme from BrightWhite to White. This then allows the use of ESC sequence codes to add an intensity bit to make White display as BrightWhite. Without this change, using ESC[1m would keep the display color the same.
This was tested by manipulating the profiles.json to find the correct values to use. The code change was not tested outside this commit because it is a direct replacement of hard coded data, so there are no behavioral changes which should need to be evaluated separately.
=> #1363 - Campbell color scheme should change the foreground color from #F2F2F2 to #CCCCCC

src/cascadia/TerminalApp/MinMaxCloseControl.cpp, src/cascadia/TerminalApp/MinMaxCloseControl.xaml
This pull request contains a bunch of XAML that makes our caption buttons look like this:
|state|image|
|-|-|
|normal|![image](https://user-images.githubusercontent.com/14316954/60141892-55027f80-976c-11e9-8074-c8b77ca4a1d8.png)|
|hovered|![image](https://user-images.githubusercontent.com/14316954/60141895-58960680-976c-11e9-89d2-08dbd664625f.png)|
|clicked|![image](https://user-images.githubusercontent.com/14316954/60141898-5c298d80-976c-11e9-9a53-c9f394c3ca88.png)|
|maximized|![image](https://user-images.githubusercontent.com/14316954/60141918-795e5c00-976c-11e9-83d4-fc0fe80acb57.png)|
instead of like the characters `_`, `-` and `X` from Segoe UI.
Part of #1625.
=> Replace caption buttons with ones that look close to correct

src/host/ut_host/ScreenBufferTests.cpp, src/terminal/adapter/DispatchTypes.hpp, src/terminal/adapter/ITermDispatch.hpp, src/terminal/adapter/adaptDispatch.cpp, src/terminal/adapter/adaptDispatch.hpp, src/terminal/adapter/termDispatch.hpp, src/terminal/parser/ut_parser/OutputEngineTest.cpp
While the [DECCOLM](https://vt100.net/docs/vt100-ug/chapter3.html#DECCOLM) escape sequence is technically implemented, it's disabled by a flag that is not user-accessible. This PR adds support for an escape sequence (XTerm's private mode 40) which essentially enables that flag, so users can turn on DECCOLM support in an XTerm-compatible way. Tested manually, with [Vttest](https://invisible-island.net/vttest/), and with unit tests.
My initial plan was to build this on top of the existing `_fIsSetColumnsEnabled` flag, but after further investigation that proved not to be practical. In order to be compatible with XTerm, the flag needs to be checked in the `_DoDECCOLMHelper` method rather than in `SetColumns`, since it needs to prevent all facets of the DECCOLM operation taking effect - not …
=> Enable DECCOLM support via a private mode escape sequence

src/cascadia/TerminalApp/CascadiaSettings.cpp
Some of the colors from the Solarized schemes that ship with Windows Terminal are not aligned with the [reference Solarized palette](https://github.com/altercation/solarized#the-values).
Also requires #293 for [correct rendering](https://github.com/microsoft/terminal/issues/293#issuecomment-506065103) of background/foreground colors.
Implements the changes discussed in https://github.com/microsoft/terminal/issues/1509#issuecomment-505236830.
No behavioral changes.
=> Fix inaccurate Solarized palette

src/renderer/dx/DxRenderer.cpp
Adjusts the logic inside the DX renderer's resize operations to not leave some device resources null and not others when a resize operation fails.
You can see the verbose diagnostics that led to this conclusion in https://github.com/microsoft/terminal/issues/1572#issuecomment-507469309
This should resolve the crash, though it might not resolve the underlying issue of why the resizing is failing. But we should have more diagnostic information available when running under the debugger with the wil macros applied.
- Ran the build with the patched and snapped it all over the place on my multiple monitors at varying speeds. 
- Turned on the 4k monitor and snapped to/from that one as well to see if a DPI transition gave it a problem.
=> Stop crash on window snap by preventing torn device resources state 

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/CascadiaSettings.cpp, src/cascadia/TerminalApp/Pane.cpp, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalCore/ITerminalInput.hpp, src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/UnitTests_TerminalCore/InputTest.cpp, src/cppwinrt.build.pre.props, src/renderer/dx/DxRenderer.cpp, src/renderer/dx/DxRenderer.hpp, src/terminal/adapter/ut_adapter/inputTest.cpp
* 508edf3 Stop crash on window snap by preventing torn device resources state  (#1768)
* 9faf206 Fix inaccurate Solarized palette (#1720)
* 51ffc31 Change Campbell's default foreground color (#1629)
* 4559bdd Revoke old event handlers correctly on pane close (#1279)
* 03d730f Fixed #521 - AltGr combinations not working (#1436)
* 3e8c845 Disable the AppContainer bit on our C++/WinRT binaries (#1653)
* 8a826d1 Add a fallback to software rendering (#1263)
* 08e8f37 Make the about dialog's contents selectable (#1452)
=> Cherry-pick a number of fixes for a v0.2 servicing release

src/cascadia/TerminalControl/TermControl.cpp
Make padding applied as swap chain panel's margin
I know that this PR is trying to do the same thing as #1672. However since that one is unlikely to be merged in a short time and the issue will cause background image to be padded once #1107 is merged, I present my slightly more straight forward solution which is just set margins to swap chain panel. Hope this one gets merge sooner but we can switch to #1672's solution later if it is preferred.
Note that this PR does NOT fixx  #1367 as #1672 does.
Set padding and observe that the scroll bar stay in the same place
=> Make padding applied as swap chain panel's margin

doc/cascadia/SettingsSchema.md
Added default values for global and profiles within SettingsSchema.md
#1712
=> Updated SettingsSchema.md with default values for global and profiles

src/cascadia/TerminalApp/App.cpp
This fixes two issues.
* Opens the assigned default application regardless of its configuration.
Gvim for example only reacts to the "edit" verb so when selected as default application won't open.
Using nullptr results in using the first specified application.
This fixes #1789
* If no application is assigned for json files fall back to notepad
See https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutea for more details
especially why the result code checking is so horrific.
* Set a default application and make sure it opens
* Remove the default application and make sure that notepad gets opened
=> Make opening the settings file more robust

doc/user-docs/index.md
Added Terminal tip about changing the font size and acrylic opacity using keyboard shortcuts.
`Ctrl`+mouse scroll to change font size
`Ctrl+Shift` + mouse scroll to change acrylic opacity  given `useAcrylic` is set to `true` in profiles.json.
=> Added fontSize and acrylicOpacity changing tip

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/App.h, src/cascadia/TerminalApp/App.idl, src/cascadia/TerminalApp/MinMaxCloseControl.cpp, src/cascadia/TerminalApp/MinMaxCloseControl.h, src/cascadia/TerminalApp/MinMaxCloseControl.idl, src/cascadia/TerminalApp/TerminalApp.vcxproj, src/cascadia/TerminalApp/TerminalPage.cpp, src/cascadia/TerminalApp/TerminalPage.h, src/cascadia/TerminalApp/TerminalPage.idl, src/cascadia/TerminalApp/TerminalPage.xaml, src/cascadia/TerminalApp/pch.h
This pull request migrates a lot of the manual Xaml construction from `TerminalApp::App` into a .xaml file. The benefits in doing this are myriad:
* We can now use the live xaml designer to edit Terminal's layout!
* It performs way better because we don't need a WinRT call for every object's every property
* It is the groundwork for supporting multiple windows
* It can be themed with theme resources without jumping through terrible, terrible hoops
* The Xaml compiler produces all of the members for all of the named xaml objects all on its own!
It is, however, incomplete. I have _only moved the xaml_, I have not moved any of the logic. This is groundwork, and necessary for @cinnamon-msft to keep working on the UI. Followup issue #1878.
Mentioned in #929.
* Manual run with custom themes, …
=> Move most of TerminalApp's runtime Xaml to a .xaml file and class

src/cascadia/TerminalApp/CascadiaSettings.cpp
This change adds the "Classic" color scheme to the ones in [the default `profiles.json` settings file](https://github.com/microsoft/terminal/blob/122f0de382542de14d79babad92699d916057783/doc/user-docs/UsingJsonSettings.md), with the colors suggested by @ocalvo in issue #1781. I named it "Vintage" per @DHowett-MSFT's suggestion.
All manual tests. I didn't feel it was necessary to add any automated tests because the only ones that would make sense would be ones to check that other default color schemes aren't regressed, and we don't have any tests for default settings today (presumably because they change too often!).
- Deleted `profiles.json`, started Terminal.
- Verified that the output "Vintage" color scheme existed in the newly created `profiles.json` file.
- Verified that "Vintage" …
=> Add Vintage color scheme to defaults; fixes #1781

src/cascadia/TerminalCore/TerminalSelection.cpp
I was accidentally looking at the mutable viewport instead of the buffer.
1. Added wide glyph.
2. `dir`
3. scroll up
4. select wide glyph
=> Bugfix: selection on wide glyph in scrollback buffer

src/host/getset.cpp, src/host/screenInfo.cpp, src/host/screenInfo.hpp, src/host/ut_host/ScreenBufferTests.cpp
When executing an escape sequence that might cause the viewport to scroll, a check is made to see whether the cursor position is in the bounds of the scroll margins, otherwise the scroll operation shouldn't happen. In a couple of cases (in the RI, DL, and IL escape sequence), these boundary tests were incorrect, so the scroll operation would sometimes not occur when it should have. This PR fixes those boundary tests.
Tested manually, and with the _joe_ editor which was previously failing, and with some additional screen buffer unit tests.
The one problem was the use of `Viewport::IsInBounds` method to check whether the cursor was inside the margins. That method only works on the first column of the screen, because the horizontal margins are always set to 0. So that needed to be replaced …
=> Fix margin boundary tests in the RI, DL, and IL escape sequences.

src/renderer/dx/CustomTextLayout.cpp
This is a partial fix of #538 . This does *not* change the Console RTL behavior, it does however fix an issue in the rendering. Basically, DirectX expects the origin to be on the right if it is going to draw RTL text. This PR is a simple fix for that. Rather than draw with the left point and then move the origin rightwards, we check if it's RTL, if so, we move the origin rightwards immediately, and then draw. LTR rendering is unchanged.
This doesn't fix underlying questions of RTL handling in the console. It's just a render bugfix. However, this render bugfix should still be a big help and solve the low-hanging issues.
Behavior was tested. No changes were made to underlying console.
Three sample cases:
1. RTL text input
Before:
After:
2. Hebrew Output
Before (the Hebrew text is all being …
=> Fixed DirectX RTL text issue where it'd be over other text / offscreen

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
Implement acrylic over background image. Also make backgroundImageOpacity works with respect to the profile's background color
Introduce a new root Element that holds the original container and a background image. The root element's background sits behind `_bgImageLayer` and is responsible for acrylic and solid background.
=> Implement background image over acrylic or solid color

src/cascadia/TerminalApp/Profile.cpp, src/cascadia/TerminalApp/Profile.h, src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalSettings/ICoreSettings.idl, src/cascadia/TerminalSettings/TerminalSettings.cpp, src/cascadia/TerminalSettings/terminalsettings.h, src/inc/DefaultSettings.h
Delimiters for double click can now be set in settings. This is on a **per profile** basis (shoutout to all the WSL users out there). 
The first of a few additions to Multi-Click Selection (#1197).
Contributes to #988 
- TerminalSettings:
- add property to winrt TerminalSettings
- Terminal App:
- read/write JSON for this new property
- default set to " /\\"
- TerminalCore:
- import/use delimiters from ICoreSettings
- modified profiles.json. Then performed double click in an instance of that profile
=> Multi-Click Selection: Double-Click Settings

src/terminal/adapter/adaptDispatch.cpp, src/terminal/adapter/ut_adapter/adapterTest.cpp
When setting the scroll margins with the [DECSTBM](https://vt100.net/docs/vt510-rm/DECSTBM.html) escape sequence, some of the edge cases are interpreted incorrectly. If the top margin is equal to the bottom margin, or the bottom margin is greater than the screen height, the command should be ignored, but at the moment it isn't. This PR fixes those cases.
Tested manually and with additional adapter unit tests.
This is a slight rewrite of the `AdaptDispatch::_DoSetTopBottomScrollingMargins` method which I think should be a little easier to follow.
* Step 1: Translate the default (zero) values - default top is 1, and default bottom is the screen height.
* Step 2: Check whether the values are valid, i.e. top is less than bottom, and bottom is less than or equal to the screen height.
* Step …
=> Fix interpretation of DECSTBM margin parameters

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
Fixes the calculation of the margins when the non client island window is maximized on non primary monitors
#1055 
The overhang of a maximized window is currently calculated with this:
```cpp
auto offset = 0;
if (rcMaximum.left == 0)
{
offset = windowPos->x;
}
else if (rcMaximum.top == 0)
{
offset = windowPos->y;
}
```
This always works on the primary monitor but on a non primary monitor, it isn't always the case that `left` or `top` can be 0. Examples are when you offset a monitor. In those cases, `offset` will be 0 and the window will be cut off.
Instead I've changed the calculation to calculate the width of the windows frame which is how much it would overhang. Admittedly, the old calculation could be kept and take into consideration the current monitor.
Also I see a lot of work on the …
=> Fix wrong maximized window offset on non primary monitors

src/common.build.pre.props, src/host/ut_host/ClipboardTests.cpp, src/host/ut_host/UnicodeLiteral.hpp
There were a few issues when we first opened the project related to building in other locales because we weren't using UTF-8.
#458 
#549
I will close those because this supersedes them.
I set the /utf-8 flag globally in the pre props file per the commentary in #458. I also converted the one complaining file `UnicodeLiterals.hpp` to UTF-8 without a BOM to get it to stop complaining.
I have a personal vendetta against BOMs so I'm wholesale rejecting the idea of #549. Microsoft was wrong to BOM. If I had a time machine, I would go egg the person on the .NET team at Microsoft who decided to BOM everything a long time ago and keep going back in time to egg them repeatedly until I felt satisfaction for the pain they've caused me in my life because Microsoft UTF-8 stuff is BOM'd.
- I built it …
=> Set utf-8 for the entire project

src/cascadia/CascadiaPackage/Resources/en-US/Resources.resw, src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/pch.h
Added links to "[Getting Started](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingJsonSettings.md)", "[Documentation](https://github.com/microsoft/terminal/blob/master/doc/user-docs/index.md)", and "[Release Notes](https://github.com/microsoft/terminal/releases)" in the About section.
#1576 
Clicked the links and they all work.
The hover color is too dark to read when using dark theme.
=> Added links to user docs inside About popup

src/renderer/dx/CustomTextLayout.cpp, src/renderer/dx/CustomTextLayout.h, src/renderer/dx/CustomTextRenderer.cpp, src/renderer/dx/CustomTextRenderer.h, src/renderer/dx/DxRenderer.cpp, src/renderer/dx/DxRenderer.hpp
This PR allows the DirectX rendering engine to run on windows 7.
Certain DirectX features are unavailable on windows 7. The important ones as they are used in the DX renderer are color font rendering and fallback font support. Color fonts did not exist at all on windows 7 so running basic glyphrun rendering should work just fine.
Fallback font support was not exposed to the user in windows 7, making dealing with them difficult. Rather than try to get some workarounds to properly enable it I have opted to just conditionally disable the support on windows 7.
I ran these patches both on windows 10 and windows 7 with an in-progress WPF control. The relevant features turned themselves on and off correctly based on the version of the operating system being run on.
=> allow DX rendering engine to run on windows 7

src/host/ConsoleArguments.cpp, src/host/ut_host/ConsoleArgumentsTests.cpp
This PR is used to fix conhost when the process is started, and the command line is not properly escaped causing an error. For details, please see Issues: #1090
=> Fix The conhost command line is not properly escaped

src/cascadia/WindowsTerminal/BaseWindow.h, src/cascadia/WindowsTerminal/IslandWindow.cpp, src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp, src/cascadia/WindowsTerminal/NonClientIslandWindow.h
Fixes the round corners and lack of shadow on the window introduced in #929.
This introduces the problem discussed in #1897
* If we handle `WM_NCPAINT`, we _don't_ get shadows. We also get the legacy rounded top window corners, because of some kernel insanity. The whole point of `DwmExtendFrameIntoClientArea` is that we can just `PAINT` the entire window, instead of trying to do `NC_PAINT` tricks. So, we need to move the entire NCPAINT we had into PAINT.
* We also need to remove the margins we were setting. If we leave a top margin, the system caption buttons will try and draw into that area. Since we don't want those, we need to make sure the top margin is 0, so they have no space to draw into. 
* I also split out the DragSizeChanged handler from OnSize. I don't know why, but having it …
=> Don't NCPAINT our window, PAINT our window

src/host/exemain.cpp
Fixes #1838.
This pull request ensures that conhost, when started in conpty mode (that is: with a signal pipe, an inPipe or an outPipe (the latter two of which are no longer supported)), launches in modern v2 mode and doesn't delegate to ConhostV1.dll.
I chose to move the check into `ShouldUseLegacyConhost`, but it could equally well belong in `ShouldUseConhostV2`. Right now, "ShouldUse...V2" is dedicated to checking the registry. It's simple to change it, but this seemed like the most scoped change.
The narrow scope of the change is intentional: perhaps we can try to service this because it represents a complete scenario breakage.
Manually replaced conhost on my machine and attempted to launch a pseudoconsole with pwincon while legacy mode was engaged.
=> Force the use of v2 (non-legacy) conhost when in ConPTY mode

src/cascadia/CascadiaPackage/CascadiaPackage.wapproj, src/cascadia/TerminalApp/MinMaxCloseControl.cpp, src/cascadia/TerminalApp/TerminalApp.vcxproj, src/cascadia/TerminalApp/TerminalPage.cpp, src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
This commits fixes the centennial package by:
* Forcing XBF (XAML binary format) files to be embedded in project
PRI files.
* Moving package content generation to before PRI generation
* Collecting all of the package's PRI files to merge into resources.pri
* Fixing the hardcoded resource paths to reflect the new reality.
It also includes a magic value that fixes the bug where the project is
autodetected as a Mixed (CLR + Native) project.
Fixes #1816.
=> Fix the WAP packaging project

NuGet.Config, dep/packages/README.md
We think its gross to keep giant binary blobs in our dependencies folder for nuget packages that aren't hosted properly yet.
So we get an Azure Blob Storage account and put it there using [Sleet](https://github.com/emgarten/Sleet).
This removes the package in the repo and makes NuGet get it off of our feed instead.
=> Host our own NuGet feed for packages that we need that aren't elsewhere yet

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalCore/ControlKeyStates.hpp, src/cascadia/TerminalCore/ITerminalInput.hpp, src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalCore/terminalcore-common.vcxproj, src/cascadia/UnitTests_TerminalCore/InputTest.cpp
As a continuation to #1436 this PR adds a `Microsoft::Terminal::Core::ControlKeyStates` class which will act as a safe wrapper for the ControlKeyState enum, found in the NT console subsystem (`<um/wincon.h>`) and used throughout the older parts of this project.
Feel free to reject, modify, adopt or otherwise use this code in any way or form.
If you have comments I'll try my best of integrating them.
The `ControlKeyStates` class I wrote is as good as I was able to think of one for now which is compatible to the rest of the code base.
I think it should replace the `KeyModifiers` enum, but I'm a total C# noob and was afraid of doing so (my total C# experience is about 10h or so and I haven't even touched IDLs yet lol).
As with #1436 I tested all possible Alt/Ctrl/Shift/AltGr combinations on …
=> Add a ControlKeyStates wrapper class

src/cascadia/TerminalApp/TerminalApp.vcxproj, src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
This may be a targeted fix that obviates the need for #2002 without going all the way to #1995.
=> Roll up WindowsTerminal's subprojects into packaging outputs

src/cascadia/TerminalConnection/ConhostConnection.cpp, src/types/UTF8OutPipeReader.cpp, src/types/inc/UTF8OutPipeReader.hpp, src/types/ut_types/UTF8OutPipeReaderTests.cpp
=> Don't let the UTF8OutPipeReader be static

tools/OpenConsole.psm1, tools/razzle.cmd
As above. Previously, these helper commands to run various test cases would fail with "path not found" errors without running any tests. Now, they work again.
The problem occurred because in commit 0905140955f5d431753739312982c1d6a42d9538 (PR #1164), we updated the version of the Taef.Redist.Wlk NuGet package for the TAEF test harness and framework. However, the helper commands hard-code the path to the TAEF executable, which because of NuGet's design includes the TAEF NuGet package version. The commands weren't updated to reflect the new TAEF version and so have been broken since then.
=> Fix test runner commands - runut.cmd and friends; PowerShell Invoke-OpenConsoleTests

build/pipelines/templates/build-console-steps.yml, build/scripts/Test-WindowsTerminalPackage.ps1, src/cascadia/CascadiaPackage/CascadiaPackage.wapproj, src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
This pull request removes some of our manual cross-project reference hacks. CascadiaPackage no longer needs to import `Microsoft.UI.Xaml` directly to roll up its content, and it can get a bunch of stuff from TerminalApp (DLL only!) for free.
I've unpacked the package and verified that `resources.pri` contains TerminalApp's resources _and_ that the AppX manifest contains all of the activatable classes.
=> Roll up dependencies through TerminalApp so the package is right

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/App.h, src/cascadia/TerminalApp/AppKeyBindings.cpp, src/cascadia/TerminalApp/AppKeyBindings.h, src/cascadia/TerminalApp/AppKeyBindings.idl, src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp, src/cascadia/TerminalApp/CascadiaSettings.cpp, src/cascadia/TerminalApp/Pane.cpp, src/cascadia/TerminalApp/Pane.h, src/cascadia/TerminalApp/Tab.cpp, src/cascadia/TerminalApp/Tab.h
Closes #993
When the last pane in a tab is closed, the tab will close.
Bound to Ctrl+Shift+W by default. 
See #1417 for discussion on the default keybindings. The Ctrl+W->CloseTab keybinding is being removed in favor ClosePane.
* [N/A] Requires documentation to be updated
=> Add a keybinding for ClosePane

src/tools/ColorTool/README.md
Since ColorTool shares the same Release page as Windows Terminal, it is more difficult to navigate to it. So whenever ColorTool is updated with a new release, we will update the link to the latest release. The link I changed to is the latest available from April 2019. @zadjii-msft and @miniksa please review. This also came up in https://github.com/microsoft/terminal/issues/2025.
N/A
Link works in updated README
=> Changes link to go to latest ColorTool release

src/host/exe/Host.EXE.vcxproj, src/host/exe/conhost.exe.manifest, src/host/exe/openconsole.exe.manifest
This PR is mainly to fix the conhost.exe not using the application manifest correctly and the operating system version cannot be detected correctly. Related documents can be viewed #2053. 
This update also brings support for longPath to conhost.exe.
When DirectWrite rendering is turned on with `UseDx`, this application cannot display emoji on Windows 10 before applying this PR. After applying this PR, it can be displayed normally.
=> Fix conhost.exe detect os version

src/cascadia/TerminalApp/CascadiaSettings.cpp
Closes #1417.
Changes New Tab to Ctrl+Shift+t (from Ctrl+t)
Changes SwitchToTabN to Ctrl+Alt+&lt;number> (from Alt+&lt;number>)
This is from discussion in #1417
#2012 Changes "Close Window" by removing it by default, and adding ClosePane on Ctrl+Shift+W
* [N/A] Requires documentation to be updated
=> Change some default keybindings

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/AppKeyBindings.cpp, src/cascadia/TerminalApp/AppKeyBindings.h, src/cascadia/TerminalApp/KeyChordSerialization.cpp
This commit introduces support for key bindings containing keys
traditionally classified as "OEM" keys. It uses VkKeyScanW and
MapVirtualKeyW, and translates the modifiers that come out of
VkKeyScanW to key chord modifiers.
The net result of this is that you can use bindings like "ctrl+|" in
your settings. That one in particular will be reserialized (and
displayed in any menus) as "ctrl+shift+\". Admittedly, this is not
clear, but it _is_ the truest representation of the key.
This commit also moves the Xaml key chord name override generator into
App as a static function, *AND* it forces its use for all modifier
names. This will present a localization issue, which will be helped in
part by #1972. This is required to work around
microsoft/microsoft-ui-xaml#708. I've kept the original code …
=> Allow the mapping of OEM keys ({}|\<>/_-=+) in key bindings

README.md
The Readme doesn't mention the store link until HALFWAY DOWN. The CTA here is to get the terminal.
=> TAKE ME TO THE DOWNLOADS

.vsconfig, src/renderer/dx/CustomTextLayout.cpp, src/renderer/dx/DxRenderer.cpp
DX rendering only needs to detect the operating system version when EXTERNAL_BUILD is turned on. For Windows building, the target Windows is almost considered to be the latest.
=> Switch away from OS version detection for DirectWrite things

doc/cascadia/SettingsSchema.md, doc/user-docs/UsingJsonSettings.md, src/cascadia/TerminalApp/Profile.cpp, src/cascadia/TerminalApp/Profile.h, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalSettings/IControlSettings.idl, src/cascadia/TerminalSettings/TerminalSettings.cpp, src/cascadia/TerminalSettings/terminalsettings.h
Implement #1949: `profiles.json` has been given a setting for background images labeled as shown below, with the following valid values. This allows background images to be anchored to different corners/sides of the console to fit that background image's intended use-case and focus.
```json
"backgroundImageAlignment": "center" | "left" | "top" | "right" | "bottom"
| "topLeft" | "topRight" | "bottomLeft" | "bottomRight"
```
When `left`, `top`, `right`, or `bottom` is specified, the other axis is implied to be centered, as that is the default behavior. I went in favor of labeling the default value as `center` instead of `none` as "none" does not clearly list the alignment behavior.
The branch [dev/trigger/background-image-align-two-settings](https://github.com/trigger-segfault/terminal/tree/ …
=> Implement #1949 Background Image Align (as one setting)

src/terminal/adapter/terminalOutput.cpp
Corrects the 0x5f code point in the DEC Special Graphics character set, which is meant to map to a blank glyph rather than an underscore. and updates the 0x60 code point to map to a "black diamond suite" glyph, rather than the "black diamond" glyph, since the latter currently renders as a double width character.
The was mostly a matter of updating the `s_rgDECSpecialGraphicsTranslations` table in the `TerminalOutput` class, but also required a change in the `TranslateKey` method, to make sure the 0x5f code point was included in the range of translatable characters.
I've also made a few cosmetic changes to the source, fixing the comments on the translation table to match the DEC documentation (a couple of them were not quite right), and tidying up the case of the hex values in the table, …
=> Fix a couple of the DEC Special Graphics characters

build/pipelines/ci.yml
@DHowett-MSFT has a thread with the relevant people trying to sort this whole thing out.
But in the meantime, the static analysis builds are low value and are blocking actual work from happening.
So I commented them out for now.
=> Remove static analysis builds because they're running out of disk space.

doc/bot.md
Fixes #2090.
There was a small typo in `bot.md`.
=> Fixes #2090

src/cascadia/TerminalApp/App.cpp
Fixes #1913.
_AplyTheme raises an event for the IslandWindow to handle and actually apply
the theme, so we don't _really_ need to worry about it, but we do need to
worry for ContentDialogs.
=> Make sure to apply the theme on load of the application

src/cascadia/TerminalApp/CascadiaSettings.cpp
Set Starting Directory for WSL profile
Currently, WSL Starting Directory is /mnt/c/WINDOWS/system32, it's better to be in /mnt/c/Users/UserName directory. 
This only take effects if no existing profile.
=> Set Starting Directory for WSL profile

src/cascadia/TerminalApp/Profile.cpp, src/cascadia/ut_app/JsonTests.cpp
If a profile did not have a GUID, generate one.
**_I ran the tests_**
=> If a profile did not have a GUID, generate one

src/cascadia/TerminalApp/TitlebarControl.cpp
Only set the MaxWidth of the TitlebarControl's Content when the value is
positive. Any smaller will crash the app.
Opened the terminal with this fix and just went wild on the resize
=> Prevent a crash on resizing too small caused by the Titlebar

.github/ISSUE_TEMPLATE/Feature_Request.md
When I'm scrolling through emails, Outlook usually clips the preview of the message after the first few words. Both the PR template and the Feature Request template start with the words "Summary of the ", so both look basically the same in my inbox. PRs are way more interesting to read, so I'd love a way to be able to tell the difference immediately.
=> Change "Summary"->"Description" in the Feature Request Template

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/App.h, src/cascadia/TerminalApp/Profile.cpp, src/cascadia/TerminalApp/TerminalApp.vcxproj, src/cascadia/TerminalApp/init.cpp, src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj, src/cascadia/TerminalApp/lib/pch.h, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TerminalControl.vcxproj, src/cascadia/TerminalControl/init.cpp, src/cascadia/TerminalControl/pch.h
This pull request adds some logging around profile and tab creation. We'd like to learn what default settings people are using so that we can inform discussions like #1417.
Looked at the generated ETL.
=> Add some ETL around profile, control and connection creation

doc/cascadia/SettingsSchema.md, src/renderer/dx/DxRenderer.cpp, src/renderer/dx/DxRenderer.hpp
Adds fallback routine for when a font name is missing instead of crashing due to uncaught exception thrown when font cannot be found.
For GDI and for DirectX using the stock Layouts and Formats, if your chosen font face name isn't found... something else is just picked on your behalf. When I wrote our custom DX code, I instead threw an exception when I couldn't find the chosen font face. That exception was uncaught and led to a crash.
I decided to just make the custom code act more like the stock code and attempt to choose a fallback if we cannot find what you've requested. I also improved a bit of the passing around of the chosen font name and added locale name information while I was at it.
- Opened settings
- Set font name to "arse"
- Watched as nothing changed from previous Consolas …
=> Fixes crash when specifying invalid font

src/host/PtySignalInputThread.cpp, src/host/VtIo.cpp, src/host/VtIo.hpp, src/host/screenInfo.cpp, src/renderer/vt/invalidate.cpp, src/renderer/vt/state.cpp, src/renderer/vt/vtrenderer.hpp, src/terminal/adapter/InteractDispatch.cpp
Fixes a crash that occur when changing the buffer height. During the resize, conpty would immediately request a repaint, which would throw an exception that would cause the resize to fail halfway through, and that would make the subsequent render fail.
This change prevents the VT Renderer from immediately requesting a paint during the resize. 
Might also be related to #1095. I can't seem to get that to repro anymore with this change.
Might be related to #1856. We should verify.
This does however make another issue more apparent. When you restore down with a COOKED_READ input line (read:cmd.exe), the terminal can crash. I have a fix for that in d34a3be, which I wasn't sure if I should include in this PR or not, because I wasn't confident that was the right fix. I'm fairly certain there's …
=> Fix a crash on restore down

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
When we snap across a DPI boundary, we'll get the DPI changed message _after_ the resize message. So when we try to calculate the new terminal position, we'll use the _old_ DPI to calculate the size. When snapping to a lower DPI, this means the terminal will be smaller, with "padding" all around the actual app. 
Instead, when we get a new DPI, force us to update out UI layout for the new DPI.
Snapped the terminal a bunch back and forth on my monitors.
Checked this works fine for `showTabsInTitlebar: false`.
Tried snapping into corners from high to low back to high DPI
=> Fix the terminal snapping across DPI boundaries strangely.

src/buffer/out/textBuffer.cpp, src/buffer/out/textBuffer.hpp, src/cascadia/TerminalCore/ITerminalApi.hpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalCore/TerminalApi.cpp, src/cascadia/TerminalCore/TerminalDispatch.cpp, src/cascadia/TerminalCore/TerminalDispatch.hpp
Implemented the following VT sequences:
- EraseInLine
- EraseInDisplay
- DeleteCharacter
- InsertCharacter
(Minor: implemented CursorUp and CursorBackward in TerminalDispatch with existing APIs)
Related to #1883 
Without these VT sequences, non-Conhost connections behave strangely (since they do not go through conpty for VT parsing). 
Compared behaviour with putty/other terminals and imitated them
=> VT sequence support for EraseInLine, EraseInDisplay, DeleteCharacter and InsertCharacter

src/cascadia/TerminalCore/TerminalApi.cpp
EraseScrollback no longer hangs
=> Use ROW.Reset in EraseInDisplay instead of printing millions of spaces per line

src/cascadia/TerminalConnection/ConhostConnection.cpp
Removes the `ConhostConnection` work that set up a job object and created everything suspended. I don't believe this is or should be necessary as the ConPTY'd conhost should realize that the server end of the connection is gone and gracefully shut down (and tell its clients to shut down).
I believe that using a job here is just covering up an underlying problem with outstanding handles, bad eventing, or other message communication failures. The job is a big hammer solution to just terminate everything when the terminal goes down, which I believe is responsible for some of the `pwsh.exe` post-mortem debugger sessions I'm seeing (as the conhost goes down and then pwsh throws an unhandled exception).
Overall, if there's an issue in this area, I think we can debug and diagnose it individually …
=> Remove job object and startup suspended behavior

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/CascadiaSettings.cpp, src/cascadia/TerminalConnection/AzureConnection-ARM64.cpp, src/cascadia/TerminalConnection/AzureConnection-ARM64.h, src/cascadia/TerminalConnection/AzureConnection.cpp, src/cascadia/TerminalConnection/AzureConnection.h, src/cascadia/TerminalConnection/AzureConnection.idl, src/cascadia/TerminalConnection/TerminalConnection.vcxproj, src/cascadia/TerminalCore/TerminalApi.cpp
The Azure connection profile will not show up as an option anymore if the user is on an ARM64 build or if they're on a local build (and so they do not have the required clientID).
=> Azure connector only shows up if available

.github/ISSUE_TEMPLATE/Bug_Report.md
I learned that it is easier to find crash analysis data from a Feedback Hub link than anything else. Updates the bug template to ask users with application crashes to please make a feedback hub item so we can find diagnostic data more easily.
=> Update bug template with crash instructions

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalCore/Terminal.cpp
This moves the detection of AltGr keypresses in front of the shortcut handling.
This allows one to have Ctrl+Alt shortcuts, while simultaneously being able to use the AltGr key for special characters.
This fixes a regression in v0.3.2142.0, which automatically creates `Ctrl+Alt+[0-9]` shortcuts for switching between tabs. These conflicted with the detection of the AltGr key. in `SendKeyEvent()`.
Refixes #521.
This PR has the flaw that it doesn't allow one to define AltGr shortcuts anymore.
Considering that it's probably more important to get a fix out of the door quickly I personally see this as a minor flaw though. VS Code has the same "flaw" for instance and doesn't allow AltGr combinations either.
We could fix it more correctly later on, by modifying the `IKeyBindings` interface and …
=> Fixed Ctrl+Alt shortcuts conflicting with AltGr

src/common.build.post.props
This cleans up PCHs on CI machines only as builds continue to attempt to mitigate the 10GB maximum scratch space limitation.
=> Attempt to clean up PCHs as we build to leave more Hosted Agent disk space

build/pipelines/ci.yml
Changing docs is still causing a full 30 minute PR build. This should stop it by copying the exclusion pattern for directories down from the rolling build to the PR build too.
=> add exclusion directories to PR builds, not just rolling builds.

src/host/directio.cpp
The `_DoGetConsoleInput` method is documented as returning `STATUS_SUCCESS` if data was found, and `CONSOLE_STATUS_WAIT` if there wasn't enough data or it needed to block. While the latter is an expected response, the fact that its high bit is set means it is treated as an error, generating many unwanted logs in the debug output window. This PR makes sure that the `CONSOLE_STATUS_WAIT` response is never logged as an error.
The `_DoGetConsoleInput` is called from four places in the `ApiRoutines` class. In each case, the `NTSTATUS` response is returned via the `RETURN_NTSTATUS` macro, which is what currently generates the debug logs. This PR simply adds a check before the `RETURN_NTSTATUS` call to handle the `CONSOLE_STATUS_WAIT` as a special case, and return it directly (using …
=> Prevent unwanted debug logs when calling _DoGetConsoleInput

src/buffer/out/textBuffer.cpp, src/buffer/out/textBuffer.hpp, src/cascadia/TerminalControl/TermControl.cpp, src/interactivity/win32/Clipboard.cpp
Modernizes style of code in `TextBuffer::GenHTML` and significantly simplifies structure of produced HTML. There is sill scope for improvement (customization in particular) but that's another story.
- Changed `string` to `ostringstream` for string building.
- Changed 'sprintf_s` to c++ stream formatting.
- Changed `\r\n` to `<BR>` in produced HTML.
- Used already implemented function for UTF16->UTF8 conversion.
- Now there is flat and minimalised list of `<span>`s with fg and bg color.
Previous structure was.. weird. Each row was child span of previous row and there were empty spans with black color attributes in place of `\r\n` at end of the row. And all of this seemed unintended.
- HTML text was unescaped, and it still is, becouse Word doesn't work with HTML entities, like `&lt;`. But …
=> Refactor TextBuffer::GenHTML

src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp
These tests are specifically only failing in CI. They don't fail when I run the tests locally though. Temporarilly disabling them.
Created Issue #2261 for tracking
=> Skip a few failing tests for x86

src/cascadia/TerminalApp/CascadiaSettings.h, src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
We'll no longer use RoamingState as our app data folder. Instead we'll use the LocalState folder. This will prevent settings from automatically roaming. 
We'll also `MoveFile` existing settings from RoamingState to LocalState, if we find it in RoamingState, but not LocalState.
* [?] Requires documentation to be updated
* No profiles.json -> generates a new one in LocalState
* Profile in LocalState, not Roaming -> Nothing happens, loads normally.
* Profile in RoamingState, not Local -> File moves to Local, loads normally.
* profile in _both_ -> File in Roaming is ignored, only uses Local, loads normally.
=> Stop Roaming settings

src/cascadia/TerminalApp/FixVisualStudioBug.targets, src/cascadia/TerminalApp/TerminalApp.vcxproj, src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj
Move the hack from TerminalApp.vcxproj to a .targets file to be used by the  ut_app project too.
This might need to go into #2294
=> Fix the ut_app build for VS 16.2, 16.3

.github/ISSUE_TEMPLATE/Bug_Report.md
As `ver` doesn't work in default shell.
GitHub issues currently have instructions to run `ver` which doesn't work in Windows default shell. This PR adds Powershell instructions and keeps the cmd instructions too.
No issues. Could create one if you want.
Follow instructions. Note they work now in the default shell now rather than producing an error.
=> Add Powershell command to get OS version

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/Profile.cpp, src/cascadia/TerminalApp/Profile.h, src/cascadia/TerminalApp/Tab.cpp, src/cascadia/TerminalApp/Tab.h, src/cascadia/TerminalApp/Utils.cpp, src/cascadia/TerminalApp/Utils.h
Only update the icon of a tab it the icon actually _changed_. The way we have it, we'll try and update the icon everytime focus changes, causing the tab icon to blink for a second, even when switching between two panes with the same profile.
While I was here, I also fixed #2329, I think accidentally. But that's cool!
=> Only update the icon of a tab it the icon actually _changed_

src/host/ut_host/CodepointWidthDetectorTests.cpp, src/types/CodepointWidthDetector.cpp, src/types/inc/CodepointWidthDetector.hpp
This commit replaces CodepointWidthDetector's
dynamically-generated map with a static constexpr one that's compiled
into the binary.
It also almost totally removes the notion of an `Invalid` width. We
definitely had gaps in our character coverage where we'd report a
character as invalid, but we'd then flatten that down to `Narrow` when
asked. By combining the not-present state and the narrow state, we get
to save a significant chunk of data.
I've tested this by feeding it all 0x10FFFF codepoints (and then some)
and making sure they 100% match the old code's outputs.
| Metric                       | Then          | Now            |
|------------------------------|---------------|----------------|
| disk space                   | 56k (`.text`) | 3k (`.rdata`)  |
| runtime memory …
=> Replace CodepointWidthDetector's runtime table with a static one

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/App.h, src/cascadia/TerminalApp/App.idl, src/cascadia/WindowsTerminal/AppHost.cpp, src/cascadia/WindowsTerminal/IslandWindow.cpp, src/cascadia/WindowsTerminal/IslandWindow.h, src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp, src/cascadia/WindowsTerminal/NonClientIslandWindow.h, src/cascadia/inc/cppwinrt_utils.h
* Add a method to `App` to indicate to the app that the titlebar has been clicked. We'll use this method to `Hide` the flyout.
* In `NonClientIslandWindow`, treat the titlebar as `HTNOWHERE`, so we get clicks in that area.
* In `NonClientIslandWindow`, raise an event when the titlebar area is clicked. Also do the normal `HTCAPTION` thing we were doing before.
* In `AppHost`, when it handles the event from `NonClientIslandWindow`, it'll call the method on `App` to close the flyout.
=> When the titlebar is clicked, dismiss the new tab flyout

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalControl/TermControlAutomationPeer.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalCore/terminalrenderdata.cpp, src/host/renderData.cpp, src/host/renderData.hpp, src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp, src/interactivity/win32/windowUiaProvider.cpp, src/renderer/inc/IRenderData.hpp, src/types/IBaseData.h, src/types/IUiaData.h, src/types/ScreenInfoUiaProvider.cpp, src/types/ScreenInfoUiaProvider.h, src/types/UiaTextRange.cpp, src/types/UiaTextRange.hpp, src/types/lib/types.vcxproj, src/types/lib/types.vcxproj.filters
Created the following inheritance tree:
`IBaseData`
├─ `IRenderData`
└─ `IUiaData`
This cleans up what is exposed to UiaProviders. If more things are needed in `IUiaData` that are already in `IRenderData`, just move them to `IBaseData`.
Anything specifically used for the UIA Providers is now passed through IUiaData. I added a few `pragma region`s to make the code look pretty. No functionality should actually be changed here.
New files:
- `IBaseData`
- `IUiaData`
Used inspect.exe to see if the UIA Tree still appears in ConHost and WindowsTerminal. I was able to still interact with the UIA Tree so nothing broke.
=> Accessibility: Refactor IRenderData with IUiaData

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/Pane.cpp, src/cascadia/TerminalApp/Pane.h, src/cascadia/TerminalApp/Tab.cpp, src/cascadia/TerminalApp/Tab.h
Fixes a crash that can occur when splitting pane that was so small that the target panes would have a width/height of 0, causing DxRenderer to fail when creating the device resources.
This PR prevents both the call to `App::AddHorizontal/VerticalSplit` and the creation of the `TermControl` if the split would fail.
`App::_SplitPane` calls `focusedTab->CanAddHorizontalSplit/CanAddHorizontalSplit` before it initializes the `TermControl` to avoid having to deal with the cleanup. If a split cannot occur, it will simply return. 
**Question: Should we beep or something here?**
It then follows the same naming/flow style as the split operation, so: `Tab::CanAddHorizontalSplit -> Pane::CanSplitHorizontal ->Pane::_CanSplit`. The public pane methods will handle leaf/child the same as the current …
=> Prevent splitting panes into 0 width/height #2401

src/cascadia/TerminalApp/App.cpp
Turns out, you need to call `Clipboard::Flush()`. This is apparently a very common issue with the UWP Clipboard ([link](https://stackoverflow.com/questions/31781019/clipboard-content-of-closed-windows-universal-app)).
N/A
Manual test of repro defined in bug report.
=> Bugfix: Copy data should persist after Windows Terminal Closes

src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/App.h, src/cascadia/TerminalApp/CascadiaSettings.h, src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
This is more trouble than it's worth. We had code before to re-serialize settings when they changed, to try and gracefully migrate settings from old schemas to new ones. This is good in theory, but with #754 coming soon, this is going to become a minefield. In the future we'll just always be providing a base schema that's reasonable, so this won't matter so much. Keys that users have that aren't understood will just be ignored, and that's _fine_.
* #2389 
* #754
I tried changing `"acrylicOpacity"` to `0.9`. When re-serialized, `0.9` becomes `0.8999grabage`. This would have caused a re-format before, but no longer does :)
=> Just never save the settings

src/renderer/dx/DxRenderer.cpp, src/renderer/dx/DxRenderer.hpp
Since we're rendering with antialiasing enabled, we need to make sure
we're stroking actual pixels; to do that, we need to adjust all of our
coordinates by the StrokeWidth / 2. We're always using a stroke width of
1, so that means 0.5.
While I was here, I took the opportunity to fix the color of the grid
lines. Fixes #543.
I wrote a quick tool that uses all the gridlines.
=> dx: Render all gridlines (and, bonus: the box cursor) properly

doc/user-docs/UsingJsonSettings.md
Docs show example config with with a background image
That image is listed as being .SVG
SVG currently doesn't work
Let's have the docs use .jpg instead
Since the JPG won't stretch nicely we're also going to put it in the top-right corner without any scaling
We can go back to an SVG file after #2441 gets fixed
No additional comments
I looked at it in the 'Preview' panel
=> SVG currently doesn't work; using .jpg instead

doc/user-docs/UsingJsonSettings.md
Finally this time maybe? I think I got it right.
=> startingDirectory formatting note

doc/user-docs/UsingJsonSettings.md
Just a simple change to the documentation, in order to eliminate path confusion (using '\\\\' over '/')
=> More clear path instructions

src/cascadia/TerminalConnection/AzureConnection.cpp, src/cascadia/TerminalConnection/AzureConnectionStrings.h
When we change the client ID, we're going to need to force people to log
in again.
We can do that either by:
1. Trying to log in and refresh the user's token and failing (displaying
a cryptic message like "you aren't on the internet, please get on the
internet"), **OR** by...
2. Getting out ahead of it, detecting when we would have failed for client
ID (and other) reasons, and _not trying at all._
This is option 2.
=> AZ: Introduce a "credential version" to force old credentials to be deleted

src/cascadia/TerminalConnection/AzureConnection.cpp, src/cascadia/TerminalConnection/AzureConnectionStrings.h
On occasion, in certain delegated access scenarios, we'll fail to read
the name of one or more of the user's Azure tenants. We would summarily
explode (because we're being strict about our incoming JSON, and we
didn't know that this was possible.)
Now we'll substitute in an alternate name and present the ID.
Fixes #2249.
=> az: Don't fail when a tenant doesn't have a knowable name

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalCore/Terminal.cpp
Checking if a windows key is pressed and prevent handling at all.
1. Run commands until the scroll bar appears
2. Scroll up
3. Press the windows key
The terminal should not reset the scroll location
This is my very first pull request on GitHub. Please be kind :smiley:
=> Fix win key resets scroll location

doc/user-docs/index.md
=> Fixed typo in user-docs

src/tools/ColorTool/ColorTool/Resources.resx
In the ColorTool usage section, changed "an file" to "a file" under the -o option.
In the ColorTool usage section, changed "an file" to "a file" under the -o option. I tested it by manually building and confirming that the typo is fixed when running the application from the command line.
I didn't see any issues or existing PRs related to this typo.
I think the description above is as detailed as necessary. I didn't see anything in any issues or pull requests about this typo, but I figured it couldn't hurt to try to fix it. Please tell me if this is not the right way to address this problem (i.e., if I should I have opened an issue first/instead).
=> Fix typo in ColorTool documentation

src/cascadia/TerminalApp/App.cpp
Unfortunately, we can't necessarily guarantee that you can open the clipboard. It just happens -.-. So, let's catch this error and not crash the Terminal.
=> Catch failure to open clipboard

src/cascadia/ut_app/JsonTests.cpp, src/types/utils.cpp
This adds a few lines to support shorthand color hex codes like `#ABC`. They are treated as equivalent of `#AABBCC`
N/A
The PR is only a few lines of code so should be self-explanatory.
I've changed `src/cascadia/ut_app/JsonTests.cpp` thanks to the fact that Cascadia actually has a white color that can be expressed this way. The new test passes on my machine.
I thought that change might be a better idea than adding a new test to https://github.com/microsoft/terminal/blob/master/src/types/ut_types/UtilsTests.cpp as discussed originally, if only for the reason of simplicity. I'll be happy to write an explicit test if that seems like a better idea to maintainers.
=> Add support for short hex color codes like #CCC (#2639)

src/host/screenInfo.cpp, src/host/ut_host/ScreenBufferTests.cpp
When a user had "Disable Scroll Forward" enabled and switched to the alt buffer and maximized the console, then restored down, we'd crash. Now we don't.
The problem is that we'd previously try to "anchor" the viewport to the virtual bottom when resizing like this. This would also cause us to move the top of the viewport down, into the buffer. However, if the alt buffer is getting smaller, we don't want to do this - if we anchor to the old _virtualBottom, the bottom of the viewport will actually be outside the current buffer.
This could theoretically happen with the main buffer too, but it's much easier to repro with the alt buffer.
Added tests. 
Tried the original repro. Really went wild on the resizing.
=> Don't crash when restor-down'ing the alt buffer

doc/bot.md
We were using a tag to trigger the bot for the verbose feedback hub response.
But...
1. We have run into several instances of the bot aggressively replying multiple times before the tag is removed.
2. We asked for a "comment contains" function in the bot and the Fabric Bot team obliged.
So I've changed it to `/duplicate` from the tag trigger and will remove the tag.
=> Changed feedback hub request rule

doc/user-docs/index.md
Amends docs procedure for `Running a Different Shell`:
* Adds an overview sentence.
* Adds some light rephrasing.
* Proposes using the countersink arrow `⌵` to depict the `down` GUI element.
=> Amends user-docs procedure

src/propsheet/OptionsPage.cpp, src/propsheet/OptionsPage.h, src/propsheet/TerminalPage.cpp, src/propsheet/console.rc, src/propsheet/dialogs.h, src/propsheet/globals.cpp, src/propsheet/globals.h, tools/bx.ps1
Whenever you'd open the "options" propsheet, we'd always revert the "cursor shape" to "legacy". This is obviously bad. This PR will make is so the cursor shape will persist, and only selecting a size manually will set the shape to "legacy".
We actually need to add a hidden radio button to the "size" radio buttons on the options page, which acts as a placeholder for "non-legacy". Whenever we set the shape to not-legacy, we'll check that hidden radio button. Otherwise, whenever the Options page is activated, the selected radio button from each group gets a `BN_CLICKED` notification, and if there's no button selected, the _first_ will still get that notification.
I've opened the propsheet and really mucked with it a …
=> Prevent "Options" propsheet from reverting cursor shape settings

src/cascadia/TerminalControl/TermControl.cpp
You can now use the stylus to create a selection on your device. 
Just added the device type to where we handle a mouse.
@cinnamon-msft: I dragged the stylus over text inside the Terminal and it selected cell-by-cell
=> Add Stylus Selection Support

SECURITY.md
Open Source program office guidelines encourage us to add this information to our repository. So I'm doing it.
Sourced from https://github.com/microsoft/microsoft.github.io/blob/master/SECURITY.MD
=> Add SECURITY.md to repo

doc/user-docs/UsingJsonSettings.md
The ctrl+c issue was fixed in [#2446](https://github.com/microsoft/terminal/pull/2446)
Release: `Windows Terminal Preview v0.4.2382.0`
=> Fix json settings documentation

doc/user-docs/index.md
* Converts into a procedure.
* Uses `⌵` character to replace the `down` UI element.
=> Edits doc section `Configuring Windows Terminal`

src/host/getset.cpp, src/host/ut_host/ScreenBufferTests.cpp
CLS calls two functions: 
- `SetConsoleCursorPositionImpl()`
- `ScrollConsoleScreenBufferWImpl()`
Both of these were not checking which buffer to apply to (main vs active buffer).
Now we get the active buffer and apply the changes to that one.
Also, we forgot to switch out of the alt buffer in the previous test. Added that in.
manually performed what is described in the attached bug report.
Also ran automated test.
=> Bugfix: CLS should clear current active buffer

src/buffer/out/textBuffer.cpp, src/buffer/out/textBuffer.hpp, src/cascadia/TerminalControl/TermControl.cpp, src/interactivity/win32/Clipboard.cpp
It just takes background color from terminal (or console) configured in settings, instead first copied 
character. Somewhat easier than I thought it would be.
=> Set actual background color in HTML copy

src/types/ut_types/UtilsTests.cpp, src/types/utils.cpp
This off-by-one (regression: #2607) resulted in the following profile and environment corruption:
```
vvvvvv
"guid" : "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}\u0000",
"icon" : "ms-appx:///ProfileIcons/{0caa0dad-35be-5f56-a8ff-afceeeaa6101}\u0000.png",
^^^^^^
```
=> utils: prevent the corruption of GUID strings

src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp, src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp, src/cascadia/TerminalApp/Profile.cpp, src/cascadia/TerminalApp/Profile.h
When the user adds a name-only profile, we shouldn't re-add that to their list of profiles each time they launch the terminal.
Introduced in #2515 or #2603 
=> Don't explode name-only profiles

src/renderer/dx/CustomTextRenderer.cpp, src/renderer/dx/CustomTextRenderer.h
Removes the null check introduced for static analysis purposes as the parameter is truly optional.
Changed the null check. Ran it with some emoji.
=> Remove null check from glyph run drawing

src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalCore/TerminalSelection.cpp, src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp
Just some housekeeping work on our selection. Added a few more tests and refactored some of the functionality to improve code clarity. 
Reenabled x86 tests. They work on my machine. I hope they work on CI?
Added support for double clicking delimiter runs.
Double Click Delimiter runs now operate as follows. Characters are separated into 3 classes:
- class 0: spaces and control characters
- class 1: delimiters imported from settings
- class 2: all other characters
If you double click a cell, the selection will expand until the class of the next cell differs from the preceding one.
This is slightly different than before in that the following example will only highlight the ">" char instead of the ">" and all the surrounding spaces:
```
C:\Terminal>
^
double click here
```
N/A
Added some …
=> Selection Code Cleanup and Double Click Delimiter Runs

src/buffer/out/textBuffer.cpp
Since MS Word apparently just got support for HTML entities, we can now properly escape them.
I omitted this in #2038 since Word didn't support them
=> Escape HTML entities

src/cascadia/TerminalApp/CascadiaSettings.h, src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp, src/cascadia/TerminalApp/userDefaults.json
This pull request both adds a schema to the default JSON file written out for the user and adds code to patch a `$schema` into existing user settings.
#2704 
We have to re-parse the settings string after every patch, because there's a chance the object offsets have moved around on us. Alternatively, we could always patch from the bottom up. That approach seems more fragile, even if it's technically faster.
The tests probably fail, but I tried it locally against my settings file :P
=> Add a schema reference to the userDefaults and patch one into user data

src/tools/ColorTool/signing/SignConfig.xml
We've been requested to move to SHA2 certificates where possible. This replaces the friendly name that internally converts to a variant containing a non-zero amount of SHA1 stuff into one that is fully SHA2.
This literally just replaces the friendly name for the old certificate with the one for the new certificate so the signing tool knows which cert to pick up out of the certificate store. It has to dovetail with the authorization which I've already submitted for review.
As I mentioned above, I can't validate it until it's in and the authorization is approved. I'll manually launch a signed build and check it out (and maybe even release it) once we're all authorized and updated.
=> Update SignConfig to use SHA2 variant per governance request.

src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp, src/cascadia/TerminalApp/App.cpp, src/cascadia/TerminalApp/CascadiaSettings.cpp, src/cascadia/TerminalApp/Resources/en-US/Resources.resw, src/cascadia/TerminalApp/TerminalWarnings.h
Prevent the Terminal from toasting it's marshmallows when the user hides all their profiles. In that case, we'll just revert to the defaults.
* ran tests
* validated manually
=> Add validation for hiding all the profiles

src/host/screenInfo.cpp, src/host/ut_host/ScreenBufferTests.cpp, src/host/ut_host/SelectionTests.cpp
If a user has `VirtualTerminalLevel` set, then `SetConsoleMode(ENABLE_VIRTUAL_TERMINAL_PROCESSING)` won't set our tab stops, because we're never going from vt off -> on.
So, if VT mode is enabled, construct the VT tab stops when the buffer is created.
Big shout-out to @j4james for basically doing all the work on what I thought was an impossible bug. Thanks!
=> Initialize the VT tab stops when a buffer is created in VT mode

src/host/_stream.cpp
=> Fix display of the "low ASCII" glyphs in PC code pages

src/interactivity/win32/find.cpp
Remember the last searched-for string in the Find dialog
#2844 
Manually verified the dialog retains the last used string for the lifetime of the process
=> Remember last-used string in the Find dialog in conhost

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/WindowsTerminal/BaseWindow.h, src/cascadia/WindowsTerminal/IslandWindow.cpp, src/cascadia/WindowsTerminal/IslandWindow.h
Remove WindowUiaProvider entry points
Make TerminalAutomationPeer not crash the app if creation failed.
WindowUiaProvider was something I thought we needed. We still need it for signaling (maybe). But it sometimes can crash because it's not hooked up properly at all. For now, I removed all entry points. After the signaling model gets added for #2447, I'll decide if we actually need to remove it.
Also surrounded the TerminalControlAutomationPeer with a try/catch. If we don't have everything we need to create the AutomationPeer yet, we'll just catch it and move forward.
=> Improve Accessibility Reliability

doc/user-docs/UsingJsonSettings.md, doc/user-docs/index.md
The `profiles.json` file was moved from RoamingState to LocalState in PR #2298. This PR updates the documentation to reflect this change.
PR #2298
I searched through the documentation for references to RoamingState in relation to `profiles.json` and changed RoamingState to LocalState for such instances. The configuration example for adding a custom background could technically continue to reference the roaming path, but I felt it was best to change it to the local path since it referenced this path as the "same directory as your `profiles.json` file."
Documentation update only, so no validation was performed.
=> Update path to profiles.json in documentation

src/renderer/base/renderer.cpp, src/renderer/dx/DxRenderer.cpp
If _PaintFrameForEngine returns E_PENDING, we'll give it another two
tries to get itself straight. If it continues to fail, we'll take down
the application.
We observed that the DX renderer was failing to present the swap chain
and failfast'ing when it did so; however, there are some errors from
which DXGI guidance suggests we try to recover. We'll now return
E_PENDING (and destroy our device resources) when we hit those errors.
Fixes #2265.
I TDR'd the heck out of my machine. While Visual Studio and Outlook were busy assuming ambient temperature and taking a dirt nap respectively, Terminal continued chugging along.
=> Add some retry support to Renderer::PaintFrame

src/host/srvinit.cpp
This change enables VT processing by default for _all_ conpty clients. See #1965 for a discussion on why we believe this is a righteous change.
Also mentioned in the issue was the idea of only checking the `VirtualTerminalLevel` reg key in the conpty startup. I don't think this would be a more difficult change, looks like all we'd need is a simple `reg.LoadGlobalsFromRegistry();` call instead of this change.
Manually launched a scratch app in both the terminal and the console. The console launch's output mode was 0x3, and the terminal's was 0x7. 0x4 is the ` ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag, which the client now had by default in the Terminal.
=> Enable VT processing by default for conpty

src/host/_stream.cpp, src/host/getset.cpp, src/host/output.cpp, src/host/ut_host/ApiRoutinesTests.cpp, src/host/ut_host/ScreenBufferTests.cpp, src/terminal/adapter/adaptDispatch.cpp
The [`DECSTBM`](https://vt100.net/docs/vt510-rm/DECSTBM.html) margins are meant to define the range of lines within which certain vertical scrolling operations take place. However, we were applying these margin restrictions in the `ScrollRegion` function, which is also used in a number of places that shouldn't be affected by `DECSTBM`.
This includes the [`ICH`](https://vt100.net/docs/vt510-rm/ICH.html) and [`DCH`](https://vt100.net/docs/vt510-rm/DCH.html) escape sequences (which are only affected by the horizontal margins, which we don't yet support), the [`ScrollConsoleScreenBuffer`](https://docs.microsoft.com/en-us/windows/console/scrollconsolescreenbuffer) API (which is public Console API, not meant to be affected by the VT terminal emulation), and the `CSI 3 J` erase scrollback …
=> Remove unwanted DECSTBM clipping

src/host/settings.cpp
We've seen a number of cases where the user's settings can get corrupted
and their default foreground/background and cursor color get set to all
black (black on black). This results in a fairly unhappy user and
probably a great number of support incidents.
Let's declare that an invalid state.
Related to #2651.
=> conhost: if we start with invalid terminal colors, reset them to sanity

src/cascadia/TerminalCore/TerminalApi.cpp
Making Terminal use EraseInLine when clearing exposed an off-by-one error.
None.
Forced to use EraseInLine() and checked output.
=> Fix EraseInLine off-by-one error

src/cascadia/TerminalCore/lib/terminalcore-lib.vcxproj, src/tools/vtpipeterm/VtPipeTerm.vcxproj
Retarget VtPipeTerm & terminalcore-lib to 18362. I'm not sure if we should also change the min SDK version. Let me know if it's needed.
Besides, the OpenConsolePackage appx target is still using lower SDK version
```xml
<TargetPlatformVersion>10.0.17763.0</TargetPlatformVersion>
<TargetPlatformMinVersion>10.0.17134.0</TargetPlatformMinVersion>
```
I wonder if it's intended so I left it intact.
=> Retarget VtPipeTerm & terminalcore-lib to 18362

build/pipelines/templates/build-console-steps.yml, build/scripts/Index-Pdbs.ps1, src/cascadia/TerminalApp/TerminalApp.vcxproj, src/cascadia/TerminalApp/packages.config, src/cascadia/TerminalConnection/TerminalConnection.vcxproj, src/cascadia/TerminalConnection/TerminalConnection.vcxproj.filters, src/cascadia/TerminalConnection/packages.config, src/cascadia/TerminalControl/TerminalControl.vcxproj, src/cascadia/TerminalControl/TerminalControl.vcxproj.filters, src/cascadia/TerminalControl/packages.config, src/cascadia/TerminalSettings/TerminalSettings.vcxproj, src/cascadia/TerminalSettings/packages.config, src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj, src/host/exe/Host.EXE.vcxproj, src/host/exe/Host.EXE.vcxproj.filters, src/host/exe/packages.config, src/propsheet/packages.config, src/propsheet/propsheet.vcxproj, src/propsheet/propsheet.vcxproj.filters, src/winconpty/packages.config, src/winconpty/winconpty.vcxproj
I've been having trouble debugging some crashes because the source information is difficult to come by in Visual Studio and WinDBG. This adds SourceLink to link it up for Visual Studio and a script that @jevansaks created for [MUX](https://github.com/Microsoft/Microsoft-UI-XAML) to create the srcsrv linkage for WinDBG.
- I checked the release build I generated with this and it worked in WinDBG and Visual Studio
=> Add source linking information during the build

src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalCore/terminalrenderdata.cpp
Fix double width cursor for CJK characters
#2713 
The code was copied from https://github.com/microsoft/terminal/blob/master/src/host/renderData.cpp#L266
=> Fix double width cursor for CJK characters

src/terminal/parser/OutputStateMachineEngine.cpp
Passthrough the 🔔 in conpty mode
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🔔
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🔔🔔🔔🔔🔔
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🔔🔔🔔🔔🔔🔔🔔
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🔔🔔🔔🔔🔔🔔🔔
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🔔🔔🔔🔔🔔🔔🔔
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🔔🔔🔔🔔🔔🔔🔔
&nbsp;&nbsp;🔔🔔🔔🔔🔔🔔🔔🔔🔔
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;🔔
=> Passthrough BEL in conpty

src/cascadia/TerminalApp/lib/pch.h, src/cascadia/TerminalConnection/pch.h, src/cascadia/TerminalControl/pch.h, src/cascadia/TerminalSettings/pch.h, src/cascadia/WindowsTerminal/pch.h
It turns out that if you CATCH_LOG without including this file, and you
end up catching a C++/WinRT hresult_exception, IT TURNS IT INTO A
FAILFAST.
Fixes #2591
Fixes #2881
Fixes #2807
Really went ham on the clipboard. Like, wow.
=> teach wil about c++/winrt exceptions by including cppwinrt.h

src/buffer/out/Row.cpp, src/buffer/out/Row.hpp, src/buffer/out/textBuffer.cpp, src/buffer/out/textBuffer.hpp, src/host/_output.cpp, src/host/ft_host/API_FillOutputTests.cpp, src/host/screenInfo.cpp, src/host/screenInfo.hpp, src/host/ut_host/TextBufferTests.cpp
EraseInLine calls `FillConsoleOutputCharacterW()`. In filling the row with chars, we were setting the wrap flag. We need to specifically not do this on ANY _FILL_ operation. Now a fill operation UNSETS the wrap flag if we fill to the end of the line.
Originally, we had a boolean `setWrap` that would mean...
- **true**: if writing to the end of the row, SET the wrap value to true
- **false**: if writing to the end of the row, DON'T CHANGE the wrap value
Now we're making this bool a std::optional to allow for a ternary state. This allows for us to handle the following cases completely. Refer to the table below:
| current wrap value | are we filling the last cell in the row? | new wrap value | COMMENTS |
|-- |-- |-- |-- |
| 0 | 0 | 0 | |
| ~0~ | ~0~ | ~1~ | IMPOSSIBLE |
| 0 | 1 | 0 | |
| 0 | …
=> make filling chars (and, thus, erase line/char) unset wrap

src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/UnitTests_TerminalCore/TerminalApiTests.cpp, src/cascadia/UnitTests_TerminalCore/UnitTests.vcxproj
Writing can enter an infinite loop with full-width characters being inserted into the last column of the buffer.
#780
This is because the "WriteCharsLegacy2ElectricBoogaloo" implementation in the Terminal (`Terminal::_WriteBuffer`) is a hacky thing that we put together knowing full well that we'd have to do #780 but we had to get this working enough for now. Turns out, it's not super complete and fragile. Surprise.
- Manual run of @treit's sample against the Terminal.
- Attempting to author automated test with @treit's sample
- I need to run it against conhost and make sure it's not failing too (and fix it there too if it is)
=> Patch fix for #1360 until WriteStream (#780) can be implemented.

src/host/getset.cpp, src/host/ut_host/ScreenBufferTests.cpp
Literally the same thing as #2668, but with RI as well.
#2668, #2505, #832
=> When reverse indexing, preserve RGB/256 attributes

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalCore/ITerminalInput.hpp, src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/UnitTests_TerminalCore/InputTest.cpp
This PR mostly fixes the mapping of <kbd>Alt</kbd> combinations to unicode characters.
The case of <kbd>AltGr</kbd> was originally hotfixed by returning early in `TerminalControl`.
But this didn't fix e.g. <kbd>Alt</kbd><kbd>Shift</kbd> combinations. See #2771 for instance.
This PR now fixes this particular remaining issue.
Cases where a single keypress generates more than a single UTF-16 code point (e.g. when diacritics come into play) are not fixed though, due to a limitation in the design of the low level `KeyEvent` class.
* #2771
* #1819
* #1694 (Not sure about that one - I don't understand the issue description)
* I changed the `ITerminalInput` interface
This removes the special handling of AltGr in `TerminalControl`, so that `terminalInput` may now handle it by itself.
I believe …
=> Partially fix mapping of virtual keys to characters

src/host/getset.cpp, src/host/ut_host/ScreenBufferTests.cpp
If we're moving the cursor up, its vertical movement should be stopped at the top margin. It should not magically jump up to the bottom margin. Similarly, this applies to moving down and the bottom margin. Furthermore, this constraint should always apply, not just when the start position is within BOTH margins
#170
Shout-out to @j4james as always, for keeping the VT implementation honest 😋
=> CUU and CUD should not move "across" margins.

src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
Fixes a build error about `wil/cppwinrt.h` being included in the wrong order vis-a-vis `result_macros.h`
=> Remove a stray inclusion of an old Windows.ImplementationLibrary package

src/cascadia/TerminalApp/defaults.json
As per prior agreement with WinUI team, disabling acrylic for Cmd (and Windows PowerShell, already complete) by default. 
PowerShell Core/7 and WSL distros allowed to have Acrylic enabled by default.
=> Update cmd's default profile to disable acrylic

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp, src/cascadia/WindowsTerminal/NonClientIslandWindow.h
It turns out that our WM_LBUTTONDOWN handler wasn't even necessary, as
our NCHITTEST tells win32 that all of the titlebar is actually
non-client area. This brings the code in line with
NonNonClientIslandWindow.
Fixes #2513
Went wild with the clicking and dragging.
=> Simplify non-client hit testing in NCIslandWindow to fix doubleclick

src/cascadia/TerminalApp/MinMaxCloseControl.cpp, src/cascadia/TerminalApp/MinMaxCloseControl.h, src/cascadia/TerminalApp/MinMaxCloseControl.idl, src/cascadia/TerminalApp/TitlebarControl.cpp, src/cascadia/TerminalApp/TitlebarControl.h, src/cascadia/TerminalApp/TitlebarControl.idl, src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
This also sets us up for a bit more robustness down the line.
Really went ham on ways to minmax the window.
=> Propagate window style changes to the titlebar and minmax

src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp, src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
Layer the `globals` globals on top of the root globals.
We added the ability for the root to be used as the globals object in #2515. However, if you have a globals object, then the settings in the root will get ignored. That's bad. We should layer them.
=> Layer the globals globals on top of the root globals

doc/user-docs/UsingJsonSettings.md
This path is consistently `WindowsTerminal_8wekyb3d8bbwe`, rather than a randomized string.
=> Updates path to profiles.json

src/cascadia/TerminalConnection/AzureConnection.cpp, src/cascadia/TerminalConnection/AzureConnection.h, src/cascadia/WindowsTerminal/main.cpp, src/types/utils.cpp
This is a general code health PR. I was reading about WIL, and found out that they've got these helpers already.
I ran the UUIDgen tests and used the azure cloud shell connector, and launched WT on the wrong architecture.
=> health: get rid of our hand-rolled sprintf->wstring helpers, prefer WIL

src/terminal/parser/stateMachine.cpp, src/terminal/parser/stateMachine.hpp, src/terminal/parser/ut_parser/Parser.UnitTests.vcxproj, src/terminal/parser/ut_parser/Parser.UnitTests.vcxproj.filters, src/terminal/parser/ut_parser/StateMachineTest.cpp, src/terminal/parser/ut_parser/sources
It was bad before, but now it is not.
=> Move the VT parser's parse state into instanced storage

src/buffer/out/textBuffer.cpp, src/buffer/out/textBuffer.hpp, src/host/getset.cpp, src/host/output.cpp, src/host/renderFontDefaults.cpp, src/host/renderFontDefaults.hpp, src/host/selection.cpp, src/host/selection.hpp, src/host/settings.cpp, src/host/settings.hpp, src/host/srvinit.cpp, src/host/telemetry.cpp, src/interactivity/onecore/SystemConfigurationProvider.cpp, src/interactivity/onecore/SystemConfigurationProvider.hpp, src/interactivity/win32/menu.cpp, src/renderer/base/FontInfoBase.cpp, src/renderer/base/FontInfoDesired.cpp, src/renderer/base/fontinfo.cpp, src/renderer/dx/DxRenderer.cpp, src/renderer/gdi/state.cpp, src/renderer/inc/FontInfo.hpp, src/renderer/inc/FontInfoBase.hpp, src/renderer/inc/FontInfoDesired.hpp, src/renderer/inc/IFontDefaultList.hpp
We now truncate the font name as it goes out to GDI APIs, in console API
servicing, and in the propsheet.
I attempted to defer truncating the font to as far up the stack as possible, so as to make FontInfo usable for the broadest set of cases.
There are a couple things I have questions about, actually. I know that `Settings` gets memset (memsat?) by the registry deserializer, and perhaps that's another place for us to tackle. Right now, this pull request enables fonts whose names are >= 32 characters _in Windows Terminal only_, but the underpinnings are there for conhost as well. We'd need to explicitly break at the API, or perhaps return a failure or log something to telemetry.
* Should we log truncation at the API boundary to telemetry?
* Should the "launch face name" get the same …
=> Allow FontInfo{,Base,Desired} to store a font name > 32 wch

src/cascadia/TerminalCore/Terminal.cpp
Defer cursor redrawing when reading buffer
#2932 
My previous PR #2932 introduces an overhead when writing a lot of text on screen. I found that this could be optimized by delaying cursor redraw
=> Defer cursor redrawing when writing buffer

src/host/ft_host/API_FontTests.cpp, src/host/ft_host/CanaryTests.cpp, src/host/ft_host/Common.cpp, src/host/ft_host/Common.hpp, src/server/Entrypoints.cpp
=> Replace ExpandEnvironmentStrings double calling with wil helper

src/cascadia/TerminalControl/TermControl.cpp
From Egmont Koblinger:
> In terminal emulation, apps have to be able to print something and
keep track of the cursor, whereas they by design have no idea of the
font being used. In many terminals the font can also be changed runtime
and it's absolutely not feasible to then rearrange the cells. In some
other cases there is no font at all (e.g. the libvterm headless terminal
emulation library, or a detached screen/tmux), or there are multiple
fonts at once (a screen/tmux attached from multiple graphical
emulators).
> The only way to do that is via some external agreement on the number
of cells, which is typically the Unicode EastAsianWidth, often accessed
via wcwidth(). It's not perfect (changes through Unicode versions, has
ambiguous characters, etc.) but is still the best we have.
> …
=> TermControl: force all ambiguous glyphs to be narrow

src/cascadia/WpfTerminalControl/TerminalContainer.cs
Visual studio terminal was patched to make sure connection messages got through
=> correctly inform wpf pty connection of resize events

src/renderer/dx/CustomTextLayout.cpp
It takes many CPU cycles to calculate text layout & font fallback even it's not really necessary. This may seem a little aggresive but it indeed dramatically boost performance.
#806 
With the help of #2937 and this PR, vim performance is way more smooth than before.
=> Reduce text layout CPU usage when DWrite analysis is not needed

src/host/ut_host/ClipboardTests.cpp, src/types/convert.cpp
It was wrong. It is now not wrong.
Some badly-behaved applications prefer to reconstitute a keyboard key out of a scancode and a modifier set.
I tested `less` from the original bug!
=> Always use a VK in MapVirtualKeyW(..., MAPVK_VK_TO_VSC)

src/cascadia/TerminalCore/TerminalApi.cpp
Fixes issue with console text copied to the clipboard not having correct line endings.
It appears the primary cause of the problem was the text erase code was using the default setting of the wrapped-text flag -- that is, when it erased lines (or the whole screen), it cleared cells up until the end of the line, and without end-of-line wrapping explicitly disabled, the rows with erased text all thought there was a wrapped line because the last cell in each row was written to...
1) Open up a Terminal window (for this example, a WSL instance)
2) Hit enter a couple of times to generate some duplicates of the prompt to copy/paste
3) Select multiple lines, copy, paste to Notepad
4) Note that the lines include line breaks as expected
5) Clear the terminal by the clear command
6) Hit enter a …
=> Fix issue where text copied to clipboard doesn't have line endings

src/cascadia/TerminalCore/Terminal.cpp
Fixes crash introduced by #2932 
See #2932
=> Fix potential cursor redrawing crash

src/buffer/out/AttrRow.cpp
Reduces CPU usage in `ATTR_ROW::InsertAttrRuns`.
#806 
I myself have experienced the slow cursor movement described in #806 . I found one hotspot is in `ATTR_ROW::InsertAttrRuns`. It is called many times during screen redrawing. All those vector initializing and copying consumes lots of CPU cycles. 
The idea is simple: exit as quickly as possible. The original author has already done this optimization when `_list.size()` is 1 or 2. I took a little further and aggresive way.
I added quick exit on these following condition
* Insert single color that is the same as the left color:
```plaintext
AAAAABBBBBBBCCC
^
AAAAAABBBBBBCCC
```
* Insert single color that is the same as surrouding ones
```plaintext
AAAAABBBBBBBCCC
^
AAAAABBBBBBBCCC
```
I didn't change the documentation cuz I wanna hear …
=> Reduce InsertAttrRuns CPU usage

src/renderer/dx/DxRenderer.cpp
Fixes off-by-one bug when copying font name, which resulted in null character being inside the string. The code assumed that `std::string::resize()` includes null, but it does not.
It resulted in HTML string including null character (from font name) which was no good (#3252).
=> html copy: fix null character in font face name

src/cascadia/CascadiaPackage/CascadiaPackage.wapproj, src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj, src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj, src/cascadia/TerminalApp/packages.config, src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj, src/cascadia/WindowsTerminal/packages.config, src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj
Due to a platform issue, elevated application packages occasionally fail
to find all of their dependencies. The real fix for this is going to
take a lot of time and probably a new build of Windows.
The fix we have here switches us to a non-"release" build of
Microsoft.UI.Xaml. The critical thing about their non-release builds is
that they prefer to embed their DLLs into the hosting package instead of
expressing a platform dependency.
This build of Microsoft.UI.Xaml was produced from the same commit as
the original and official build; the only difference is that it will
embed into our package.
Fixes #3275.
=> Switch to a non-release build of MUXc to fix elevated launch

src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalCore/terminalrenderdata.cpp
Revert "Fix cursor redrawing crash (#2965)"
This reverts commit 926a2e3d800a18a23139f8c6e9f97f3ccf63650c.
Revert "Fix double width cursor for CJK characters (#2932)"
This reverts commit eafa884fc40e566c4df4a4521850b14130a7ff24.
Fixes #3277.
Fully reverts #2965, #2932.
Chatted with @skyline75489 about the appropriate fix for #3277, and we decided that it'd be best to revert these two PRs until we can get them in better shape.
A whole bunch of bisecting.
=> Revert two cursor changes that cause crashing and rendering artifacts

src/host/ut_host/VtRendererTests.cpp, src/renderer/vt/Xterm256Engine.cpp
We should be clearing the bits when they're different, not just always
setting them.
Fixes #3281.
The tests should have caught this. I'll send in more tests.
Replaced conhost on my system, tried vim's terminal which does support those SGRs.
=> Manipulate Xterm256Engine's extended attr state properly

src/cascadia/PublicTerminalCore/HwndTerminal.cpp
The WPF control was sending the tab character to the pty twice because in Win32-land tab comes in as both a WM_CHAR and WM_KEYDOWN event. This is contrary to UWP which only gets a key event for tab.
VS terminal was patched to verify that the terminal no longer double tabs.
=> prevent double handling of tab in wpf control

src/cascadia/WpfTerminalControl/TerminalContainer.cs, src/cascadia/WpfTerminalControl/TerminalControl.xaml.cs
The WPF control incorrectly assumed that it would receive DPI changed events when launched on a screen with a non-default DPI. This turned out not to be the case so instead we manually get the current DPI when sending size information to the native control.
Patched the VS terminal and verified that on 125% DPI the control was sized correctly.
=> fix latent DPI issues with the WPF control

src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp, src/cascadia/TerminalApp/ColorScheme.cpp, src/cascadia/TerminalApp/ColorScheme.h
The `_FindMatchingColorScheme` function currently iterates through all pairs in
the map to find the matching color scheme for a given JSON.
Improved this by using the name from the JSON to lookup the color scheme
in the map.
Closes #3200 
Verified that UTs are passing (especially `ColorSchemeTests`)
=> CascadiaSettings: Use map to find matching color scheme

src/terminal/parser/OutputStateMachineEngine.cpp, src/terminal/parser/OutputStateMachineEngine.hpp, src/terminal/parser/ut_parser/OutputEngineTest.cpp
[`HPA`](https://vt100.net/docs/vt510-rm/HPA.html) (horizontal position absolute) is just an alias for the existing [`CHA`](https://vt100.net/docs/vt510-rm/CHA.html) (cursor horizontal absolute) escape sequence, which moves the cursor position to the specified column on the current line. This is needed in order to pass the `HPA` test in [Vttest](https://invisible-island.net/vttest/).
As discussed in issue #3348, the general consensus is that this can be considered an alias for the `CHA` escape sequence. So I've just added a new entry in the `VTActionCodes` enum for the `HPA` final character, and then updated the switch statements in `OutputStateMachineEngine::ActionCsiDispatch` to share the same code path as the existing `CHA` action.
I haven't bothered with giving it a unique telemetry …
=> Add support for the HPA escape sequence

src/host/popup.cpp, src/host/screenInfo.cpp, src/host/screenInfo.hpp
The `LineChar` array was used to hold a set of the Unicode characters required to draw the borders of a box. The array was never updated with different values, so there was no need for that level of indirection. This PR gets rid of the `LineChar` array and just uses the appropriate Unicode constants directly.
The only place the `LineChar` values were used was in the [`_DrawBorder`](https://github.com/microsoft/terminal/blob/9b92986b49bed8cc41fde4d6ef080921c41e6d9e/src/host/popup.cpp#L87) method of the `Popup` class, so I've just replaced all of those references with the appropriate Unicode constants, then removed the `LineChar` array, and it's initialization code, from the `SCREEN_INFORMATION` class.
I've checked that the borders still render correctly by viewing the command history …
=> Get rid of the SCREEN_INFORMATION::LineChar array

src/host/ut_host/Utf8ToWideCharParserTests.cpp, src/host/utf8ToWideCharParser.cpp
- Permits substitution of Unicode Replacement for non-minimal codepoint encodings in UTF-8.
- We do a lot of work to figure out whether or not we have some invalid UTF-8 inside our own internal parser. We're correctly identifying in the first full-conversion pass that something is amiss with the stream of text we were given. And inside the second pass for involved parsing, we are identifying and removing obviously wrong sequences like those that have a lead byte without the correct number of continuations, continuations that come from nowhere, and so on. But there's one big gap:
- We're not correctly identifying non-minimal forms of characters. Specifically, what is causing the crash, is non-minimal representations of the null character U+0000. The minimal form of this character in UTF-8 …
=> Compensate for non-minimal UTF-8 encodings

src/cascadia/TerminalControl/TermControl.cpp
This resolves (possibly not all) crashes when quickly opening and closing a tab that stem from accessing UI elements after control has closed. This looks strange to me that xaml sill runs dispatches after closing, but this seems to happen here (but it really shouldn't right?). If so, this might also explain some other crashes.
Other investigations:
- There is definitely some use after free going on, mostly at xaml level. It also looks like terminal is invalidated even before `TermControl::Close()` has a chance to run.
- The code seems to be not completely thread safe (e.g. removing `TerminalOutput` event handler on `ConhostConnection` is not synchronized). Although this could explain some occasional crashes like #2655, I rather doubt so; if these are only some single fields then x86, …
=> Fix scrollbar update after terminal close

src/buffer/out/cursor.h, src/host/_stream.cpp, src/host/_stream.h, src/host/cmdline.cpp, src/host/directio.cpp, src/host/popup.h, src/host/screenInfo.cpp, src/host/settings.cpp, src/host/settings.hpp, src/terminal/adapter/adaptDispatch.hpp
Replace some macros with modern constexpr.
#2941 
Macros are just very 1980s and should be used less.
I'm not sure which one is preferred, `auto` or concrete type.
Not needed.
=> Replace some macros with constexpr

src/host/cmdline.cpp, src/host/history.h, src/host/input.h, src/host/settings.cpp, src/host/ut_host/HistoryTests.cpp, src/host/ut_host/PopupTestHelper.hpp, src/inc/conime.h, src/tsf/TfConvArea.cpp
A follow-up of #3362.
Replace some macros with modern constexpr
#2941
=> Replace macros with constexpr part 2

src/buffer/out/AttrRow.cpp
=> Break if an early exit can not be found in InsertAttrRuns

src/cascadia/PublicTerminalCore/HwndTerminal.cpp, src/cascadia/PublicTerminalCore/HwndTerminal.hpp, src/cascadia/WpfTerminalControl/NativeMethods.cs, src/cascadia/WpfTerminalControl/TerminalContainer.cs
Adds a blinking cursor to the WPF terminal control
VS terminal was patched with new bits to verify cursor only blinked when it had keyboard focus.
=> wpf: make the cursor blink

src/host/outputStream.cpp, src/host/outputStream.hpp, src/host/ut_host/ScreenBufferTests.cpp, src/terminal/adapter/ITermDispatch.hpp, src/terminal/adapter/adaptDispatch.cpp, src/terminal/adapter/adaptDispatch.hpp, src/terminal/adapter/conGetSet.hpp, src/terminal/adapter/termDispatch.hpp, src/terminal/adapter/ut_adapter/adapterTest.cpp, src/terminal/parser/OutputStateMachineEngine.cpp, src/terminal/parser/ut_parser/OutputEngineTest.cpp
The current [DECSC](https://www.vt100.net/docs/vt510-rm/DECSC.html) implementation only saves the cursor position and origin mode. This PR improves that functionality with additional support for saving the SGR attributes, as well as the active character set.
It also fixes the way the saved state interacts with the alt buffer (private mode 1049), triggering a save when switching to the alt buffer, and a restore when switching back, and tracking the alt buffer state independently from the main state.
In order to properly save and restore the SGR attributes, we first needed to add a pair of APIs in the `ConGetSet` interface which could round-trip the attributes with full 32-bit colors (the existing methods only work with legacy attributes).
I then added a struct in the `AdaptDispatch` …
=> Improve the DECSC/DECRC implementation

src/host/ft_host/API_BufferTests.cpp, src/host/ft_host/Common.cpp, src/host/ft_host/Common.hpp, src/host/ft_host/InitTests.cpp, src/host/ut_host/Host.UnitTests.vcxproj, src/host/ut_host/Host.UnitTests.vcxproj.filters, src/host/ut_host/ObjectTests.cpp, src/host/ut_host/sources, src/server/ObjectHandle.cpp, src/server/ObjectHandle.h, src/server/ObjectHeader.cpp, src/server/ObjectHeader.h
Stops a crash that occurs when Cooked Read fails to acquire the screen buffer handle and accidentally cleans up the entire buffer on failure.
When I refactored the object management and server layer in the console host, I divided each segment into objects with their own role and tried to ensure that things cleaned themselves up appropriately when errors occurred. 
Turns out, one of those things got a little bit too aggressive.
`ObjectHandle` is given out for each client process or activity touching either the input or output objects (the input buffer and output buffers, respectively.) They also track their own permission state because each access can have different permission to the same object.
However, the objects themselves in the `ObjectHeader` have to keep track of their open count, …
=> Prevent cleanup of object given to handle that failed access check

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
#1091 
#1094 
#2390 
#3314
Combination of the PRs #1094, #2390, and #3314, especially as discussed in #3314.
In short, this changes line endings from Windows-space \r\n to the more universal \r.
Copied and pasted text into the terminal without the patch, line endings were doubled.
With the patch, line endings weren't doubled.
=> Replacing \r\n line endings with \r line endings

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp, src/cascadia/WindowsTerminal/NonClientIslandWindow.h
It's apparently perfectly possible that DWM will just crash or close, and when it does, `DwmExtendFrameIntoClientArea` will return a failure. If we THROW_IF_FAILED that call, then we'll also crash when DWM does.
This converts that THROW_IF_FAILED to a LOG_IF_FAILED. When DWM comes back, we'll hit this codepath again, and all will be right again in the world.
`taskkill /f /im dwm.exe` used to crash us too, now it onlt takes down DWM.
=> Prevents DWM crashing from also crashing us

doc/user-docs/ThirdPartyToolProfiles.md
Maybe it would be helpful to have a comprehensive guide on adding some common third-party tools as profiles.
Other ideas:
I figured this would be something the community would mostly maintain.
Related to #2283
=> Create a doc for adding common third-party tools

src/cascadia/TerminalApp/TabRowControl.xaml, src/cascadia/TerminalApp/TerminalPage.cpp, src/cascadia/TerminalApp/TerminalPage.h
Add support for rearranging open tabs via drag and drop
=> Add support for tab drag and drop

src/renderer/dx/CustomTextRenderer.cpp
A tiny little perf fix.
I don't really get it, though. Isn't Windows Terminal only available on Windows 10+?
=> dx: don't check the OS version multiple times

src/cascadia/WpfTerminalControl/WpfTerminalControl.csproj
Add .NET Core target to WPF control.
Developer side requirement update: forces Visual Studio version to support .NET Core SDK 3.0. The supported minimal version is 16.3.
- Use `Microsoft.NET.Sdk.WindowsDesktop`
The SDK is designed for WPF and/or WinForms. It handles all item definitions and references for WPF, and also hides difference of desktop WPF and netcore WPF.
- Add .NET Core target to WPF control
WPF in .NET Core is getting feature parity, and it's the future. As simple as an addition in `TargetFrameworks`.
No actual code changed.
Requires to test if the WPF control works in .NET Core. But I can't find .NET Framework test to compare.
=> wpf: Add .NET Core target to WPF control

src/cascadia/TerminalConnection/ConptyConnection.cpp
I misunderstood the docs for HSTRING and thought the empty string was represented as `nullptr`. It isn't.
Self-tested.
=> Don't ever try to pass "" as a starting directory, no way

doc/cascadia/profiles.schema.json
Added a line to the schema to allow for null in the background property.
=> doc: allow null for foreground/background in schema

src/cascadia/TerminalApp/App.xaml
Reset the padding to default around the tabs.
=> Increase left padding around tabs

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalCore/ITerminalInput.hpp, src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp
We forgot to snapOnInput when text is pasted. This corrects that, by making sure that pasted output attempts to snap the Terminal as well.
=> SnapOnInput on Paste

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
Another tiny performance fix.
Correct me if I'm wrong, It doesn't really make sense to update scroll status faster than frame rate limit.
=> Throttle scroll position update

src/cascadia/TerminalCore/Terminal.cpp
This PR potentially fixes #3101.
This PR fixes #3101 by setting flag 0 in `ToUnicodeEx()` even though the documentation says "If bit 0 is set, a menu is active.". I'm not 100% sure why it works, but it definitely does in this case.
I thought that bit 2, which claims that "keyboard state is not changed" would be sufficient to prevent this from happening, but it seems that's not the case.
I believe this PR should be verified by a developer at Microsoft who's familiar with the internal workings of `ToUnicodeEx()`.
We need this function (or something similar) to translate Alt+Key combinations to proper unicode.
But at the same time it should not send us any additional IBM-style Alt Codes to our character handler if that translation fails (and `ToUnicodeEx()` returns 0).
See #3101 for more …
=> Fixed #3101: Alt+Arrow-Keys print extra characters

src/buffer/out/textBuffer.cpp, src/buffer/out/textBuffer.hpp, src/cascadia/TerminalApp/TerminalPage.cpp, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalControl/TermControl.idl
RTF data is now copied to the clipboard. Tested by copy pasting text from terminal to WordPad.
Mostly similar to PR #1224. Added a new static method `GenRTF` in `TextBuffer` that is responsible
for generating the RTF representation of a given text. The generated RTF is added to the `DataPackage` that is ultimately passed to the clipboard.
Validated by copy pasting text from the terminal to WordPad. Validated with different colors to make sure that is working. (MS Word seems to prefer HTML data from the clipboard instead of RTF.)
=> Copy RTF data to the clipboard

src/cascadia/TerminalConnection/ConptyConnection.cpp, src/cascadia/TerminalConnection/ConptyConnection.h, src/inc/conpty-static.h, src/winconpty/dll/winconpty.def, src/winconpty/winconpty.cpp, src/winconpty/winconpty.h
Fixes #3553.
There's ample description in the header as to why this was the only method. ☹️
=> Force the use of the static pseudoconsole functions in TConn

src/cascadia/LocalTests_TerminalApp/KeyBindingsTests.cpp, src/cascadia/TerminalApp/ActionArgs.h, src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp
Fixes #3604 where Increase/Decrease font size bindings were not working.
Increase and decrease font size works once again!
=> Fixing increase + decrease font size

doc/cascadia/profiles.schema.json
A simple one-liner addition to `profiles.schema.json`.
Enables VSCode to recognize Color-type entries in `profiles.json` and show a color decorator in the editor.
`"format" : "color"` is a nonstandard, VSCode-specific extension to the schema format, but it shouldn't hurt validation for this case.
=> Add "format : color" to Profiles Schema color items

doc/specs/#2563 - closeOnExit and TerminalConnection evolution.md
This pull request introduces a specification for the next generation of `closeOnExit`.
#1364 #1770
Look at the spec.
It is a spec.
=> spec: propose an evolution of closeOnExit

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
Reverts microsoft/terminal#3531
This caused #3622. Since we're about to ship v0.7, I'd rather be safe.
/cc @greg904 @skyline75489
Chester, happy to have you bring this back once we get #3622 cleared up.
=> Revert "Throttle scroll position update"

src/cascadia/WinRTUtils/inc/Utils.h
It worked in debug because uninitialized memory.
Fixes #3664.
=> Make sure to set an alpha channel during ColorRefToColor

doc/cascadia/SettingsSchema.md, doc/cascadia/profiles.schema.json, src/cascadia/TerminalApp/AppActionHandlers.cpp, src/cascadia/TerminalApp/AppKeyBindings.cpp, src/cascadia/TerminalApp/AppKeyBindings.h, src/cascadia/TerminalApp/AppKeyBindings.idl, src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp, src/cascadia/TerminalApp/TerminalPage.cpp, src/cascadia/TerminalApp/TerminalPage.h, src/cascadia/TerminalApp/defaults.json, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalControl/TermControl.idl
This PR implements resetFontSize keybindings, with default keybindings `ctrl+0`.
=> Reset font size key bindings

custom.props, src/cascadia/CascadiaPackage/CascadiaPackage.wapproj, src/cascadia/WpfTerminalControl/WpfTerminalControl.csproj
This location and name is practically mandated by PackageES. Sorry ☹️.
This will ensure that all artifacts that we produce are versioned properly:
|thing|version (example)|
|-|-|
|exe, dll, .net assembly|`0.7.1911.22009`|
|nupkg|`0.7.191122009`|
|appx|`0.7.3269.0`|
For reference, here's the version format:
```
0.7.1911.22009
^ ^  ^ ^  ^  ^
| |  | |  |  `-Build # on that date
| |  | |  `-Day
| |  | `-Month
| |  `-Year
| `-Minor
`-Major
```
```
0.7.191122009
^ ^  ^ ^ ^  ^
| |  | | |  `-Build # on that date
| |  | | `-Day
| |  | `-Month
| |  `-Year
| `-Minor
`-Major
```
```
0.7.03269.0
^ ^ ^  ^^ ^
| | |  || `-Contractually always zero (a waste)
| | |  |`-Build # on that date
| | |  `-Number of days in [base year]
| | `-Number of years since [base year]
| `-Minor
`-Major
[base year] = …
```
=> consolidate PackageES versioning in /custom.props

src/cascadia/TerminalApp/TerminalPage.cpp
I regressed being able to set the window title with `title foo` in #3540. This restores that bit.
=> Restore ability to set window title from commandline

src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp, src/cascadia/TerminalApp/CascadiaSettings.cpp, src/cascadia/TerminalApp/CascadiaSettings.h
Adds a simple helper function to look up the GUID associated with a profile name.
Very simple function, for-each through profiles checking for a match. Returns the associated GUID if found, else returns the null GUID.
This function is marked as `noexcept` to comply with assumption made by other `CascadiaSettings` functions that [`Profiles::GetGuid`](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/Profile.cpp#L141) does not throw, despite it throwing.
The new function is simple and can be visually validated, but added tests regardless. A new test group was added in `SettingsTests` called `TestHelperFunctions` to validate the new function `FindGuid` and older function `FindProfile`. This test group could be used to validate more helper functions in …
=> FindGuid helper function

src/cascadia/WinRTUtils/inc/Utils.h
Replaced a `gsl::narrow` call to `gsl::narrow_cast` call. The `gsl::narrow` call used to throw when the user had custom display scaling due to a bad comparison between floating point values.
Possible other [startup crashes](https://github.com/microsoft/terminal/issues/3749#issuecomment-559900267). I'll update this as they're found.
It's a one line fix. If you want more context, here's the [full description](https://github.com/microsoft/terminal/issues/3749#issuecomment-559911062) of the problem.
Set my machine to a custom scaling  and opened a fixed build of the WT. My WT started up without crashing and continued to operate without issues (including maximizing, minimizing, and fullscreen toggle).
=> Fixed throwing floating point cast

src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp, src/cascadia/TerminalApp/CascadiaSettings.cpp, src/cascadia/TerminalApp/Profile.cpp, src/cascadia/TerminalApp/Profile.h
Fixed the noexcept specifier on `GetGuid`, and corrected `FindProfile` and `FindGuid` so they don't throw. Also, adjusted `SettingsTests` to reflect these changes.
The `noexcept` specifier on `GetGuid` was not removed when `Profile` was [updated](https://github.com/microsoft/terminal/issues/3763#issuecomment-559497094) to `std::optional<GUID>`. This PR fixes that and modifies two helper functions `FindProfile` and `FindGuid` in `CascadiaSettings` to work correctly if `GetGuid` does throw. 
Updated the `TestHelperFunctions` test group in `SettingsTests` and made sure the tests pass.
=> GetGuid noexcept Fix

src/cascadia/LocalTests_TerminalApp/ColorSchemeTests.cpp, src/cascadia/LocalTests_TerminalApp/KeyBindingsTests.cpp, src/cascadia/LocalTests_TerminalApp/ProfileTests.cpp, src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp, src/cascadia/LocalTests_TerminalApp/TabTests.cpp, src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.AppxManifest.prototype.xml
Fixes the LocalTests that should work. This does _not_ fix the TabTests.
In a previous PR, we broke unpackaged activation. This had the unintended side-effect of breaking these tests. The solution here is to run these unittests _packaged_.
This also makes things a little bit better for the TabTests, but doesn't fix them (inexplicably). A mail thread internally is tracking the progress of fixing those tests.
=> Fix LocalTests that were working before

src/tools/ColorTool/ColorTool/Program.cs, src/tools/ColorTool/ColorTool/Resources.resx, src/tools/ColorTool/README.md, src/tools/ColorTool/build.bat
1. ColorTool: Proofread and improve the help text supplied to the user
2. ColorTool: Update `build.bat` for Visual Studio 2019 and newer versions of MSBuild
None
Hi.
This PR is exclusively related to the **`ColorTool.exe`**.
This is my first PR to the source code of a computer program, so I'm a little afraid I've done something wrong. Visual Studio surreptitiously made a large number of "noise" changes to the source code. I tried to upload only the relevant changes, so as to reduce the diff cross-section. I hope I didn't break anything in the process.
First, my changes to `build.bat`:
1. `Build.bat` now looks for Visual Studio 2019 too.
2. `Build.bat` now ensures that the linker places ColorTool.exe into `\debug` or `\release` folders, not `\debug\net471` or `\release\net471`.
3. …
=> ColorTool: Proofread the helper text, update Build.bat

doc/cascadia/profiles.schema.json, src/cascadia/LocalTests_TerminalApp/KeyBindingsTests.cpp, src/cascadia/TerminalApp/ActionArgs.h, src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp
Correct behavior for `copyTextWithoutNewlines`. Updated schema for clarity.
Abandoned #3811
=> Correct Copy Keybinding Arg Default Behavior

doc/cascadia/SettingsSchema.md
It took me some trial and error to figure out how to bind "ctrl+pgdn".  This patch adds a small amount of documentation for that key combination and a couple others (both of which I tested).
Since I was here anyway, I suspect the use of the word "keybinding" was unintentional, as the thing it refers to is later referred to as a "command".  So, I tidied that up.
Tested by visual inspection.
None
* [N/A] Closes #xxx
* [CHECK] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [N/A] Requires documentation to be updated
* [READY] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where …
=> doc: Disambiguate "Keybindings" reference; add example keys

src/host/_stream.cpp, src/host/getset.cpp, src/host/screenInfo.cpp, src/host/ut_host/ScreenBufferTests.cpp
When a horizontal tab ('\t') is output on the last column of the screen, the current implementation moves the cursor position to the start of the next line. However, the _DEC STD 070_ manual specifies that a horizontal tab shouldn't move past the last column of the active line (or the right margin, if we supported horizontal margins). This PR updates the forward tab implementation, to prevent it wrapping onto a new line when it reaches the end of a line.
Originally the `SCREEN_INFORMATION::GetForwardTab` method had a condition which handled a tab at the end of the line as a special case, moving the cursor to the start of the next line. I've simply removed that condition, so an end-of-line tab is handled the same way as any other position (in this case it will just leaves the cursor where …
=> Prevent the horizontal tab character wrapping at the end of a line

src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/TerminalApi.cpp
Fixed bug where suppressApplicationTitle didn't suppress initial title from application
=> suppressApplicationTitle will suppress initial application title

src/interactivity/win32/Clipboard.cpp, src/interactivity/win32/clipboard.hpp, src/interactivity/win32/windowio.cpp
RTF data is now copied to the clipboard. The clipboard format name
used for RTF data is `Rich Text Format`.
Refactored some code in `Clipboard.cpp` so that the code for setting
data to the clipboard is re-used. Also, renamed parameter
`fAlsoCopyHtml` to `fAlsoCopyFormatting` to make it more generic.
Tested by copying text from console to WordPad. Also verified that
HTML copy is not regressed by copying to Word.
Closes #3560.
=> Conhost: copy RTF to clipboard

src/buffer/out/textBuffer.cpp, src/buffer/out/textBuffer.hpp, src/cascadia/TerminalControl/TermControlUiaProvider.cpp, src/cascadia/TerminalControl/TermControlUiaProvider.hpp, src/cascadia/TerminalControl/UiaTextRange.cpp, src/cascadia/TerminalControl/UiaTextRange.hpp, src/interactivity/win32/screenInfoUiaProvider.cpp, src/interactivity/win32/screenInfoUiaProvider.hpp, src/interactivity/win32/uiaTextRange.cpp, src/interactivity/win32/uiaTextRange.hpp, src/types/ScreenInfoUiaProviderBase.cpp, src/types/ScreenInfoUiaProviderBase.h, src/types/UiaTextRangeBase.cpp, src/types/UiaTextRangeBase.hpp
This allows the developer to define word delimiters for our accessibility model via multiple avenues.
1. import a word delimiter into the constructor of the `ScreenInfoUiaProvider` (SIUP)
- this defines a word delimiter for _all_ the `UiaTextRange`s (UTR) created by in this context
2. import a word delimiter into the UTR directly
- this provides more control over what a "word" is
- this can be useful if you have an idea of what text a particular UTR will encounter and you want to customize the word navigation for it (i.e consider adding `/` or `\\` for file paths)
The default param of `" "` is scattered throughout because this is the word delimiter used in the English language.
#3659 
#3161
=> UIA Word Navigation: Import Custom Word Delimiters

src/buffer/out/AttrRowIterator.cpp, src/buffer/out/AttrRowIterator.hpp, src/cascadia/TerminalCore/TerminalSelection.cpp, src/host/ut_host/AttrRowTests.cpp, tools/ConsoleTypes.natvis
The `count -= _currentAttributeIndex` caused `_run` to go out of bounds. Removing the minor optimization fixes this potential crash.
#3409 
@miniksa knows much more about this. He's the real MVP.
1. Open ubuntu shell
2. double click the : or ~ in cazamor@PC-cazamor:~$
This used to crash. Not anymore!
=> Fix Reverse Walking in AttrRowIterator

src/cascadia/TerminalApp/TerminalPage.cpp, src/cascadia/TerminalApp/TerminalPage.h
I accidentally did the wrong check here to see if the value exists. For an `IReference`, you need to do `variable != nullptr`. I did `variable.Value()`. 
Introduced in #3825
This includes a maybe unrelated fix to make `TerminalPage`'s `ShortcutActionDispatch` a `com_ptr`. While I was messing with the tests for this, I caught that we're not supposed to direct allocate winrt types like that. Ofc, the `TerminalAppLib` project doesn't catch this.
Ran the terminal manually, instead of just running the tests
=> Fix a crash when opening a new tab with args

src/cascadia/TerminalApp/ActionArgs.h, src/cascadia/TerminalApp/ActionArgs.idl
On this month's episode of "Mike accidentally breaks this": 
Mike forgets that `==` is defined on a pair of winrt objects as "do these point to the _SAME_ object", not "do they have the same values". 
This just slipped right through code review.
Broken in #3825
Manually checked that these are still there
=> Re-add the keychords to the new tab flyout

doc/specs/#2325 - Default Profile Settings.md
Refer to the original issue: **Default Profile for Common Profile Settings** #2325
So this is my summary of everything we discussed regarding "default profile settings". The original PR was #3369, but we were _not_ in agreement on the UX, so this PR is for discussion about that. 
I put forth 4 proposals that were mentioned in the discussion.
We'll iterate on this in the comments below, and if we can come to a consensus, I'll update the spec accordingly.
=> Spec for Default Profile Settings

build/pipelines/templates/build-console-steps.yml, src/common.build.post.props
I've received word that the standard build agents have been bumped to a version of Visual Studio 2019 with the servicing fix we needed.
=> ci: return to the original oneshot build config

src/host/_stream.cpp, src/host/ut_host/ScreenBufferTests.cpp
When the `DECSTBM` margins are set, scrolling should only allowed within
those margins. So if the cursor is below the bottom margin, it should
just be clamped when it tries to move down from the bottom line of the
viewport, instead of scrolling the screen up. This PR implements that
restriction, i.e. it prevents scrolling taking place outside the
`DECSTBM` margins, which was previously allowed.
This simply adds a condition in the `AdjustCursorPosition` function to
check if the cursor is moving below the bottom of the viewport when the
margins are set. If so, it clamps the y coordinate to the bottom line of
the viewport.
The only time it's acceptable for scrolling to happen when margins are
set, is if the scrolling is taking place within those margins. But those
cases would already have …
=> Don't allow a linefeed to scroll when outside DECSTBM margins

doc/cascadia/SettingsSchema.md, doc/cascadia/profiles.schema.json, src/cascadia/TerminalControl/TermControl.cpp, src/renderer/dx/DxRenderer.cpp, src/renderer/dx/ScreenPixelShader.h
The original PR had a few TODOs in it without issue numbers. IMO, this wasn't important enough to block the PR over. _Also I'm impatient and wanted that setting_. 
After I merged the PR I created the issues and added the numbers myself.
=> Add some issue numbers for TODOs from #3468

custom.props
Since we're producing servicing releases from the release-0.7 branch,
this will let us produce preview releases that are on a separate version train.
=> Update the version in master to 0.8

src/winconpty/winconpty.cpp
Change function to verify that `COORD` X,Y values are positive.
Visual verification, it's a basic `if` statement.
=> Fix ResizePseudoConsole accepting negative values

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
An asynchronous event handler capturing raw `this` in `TermControl` was causing an exception to be thrown when a scroll update event occurred after closing the active tab. This PR replaces all non-auto_revoke lambda captures in `TermControl` to capture (and validate) a `winrt::weak_ref` instead of using raw `this`.
`TermControl` is already a WinRT type so no changes were required to enable the `winrt::weak_ref` functionality. There was only one strange change I had to make. In the destructor's helper function `Close`, I had to remove two calls to [`Stop`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.dispatchertimer.stop#Windows_UI_Xaml_DispatcherTimer_Stop) which were throwing under [some circumstances](https://github.com/microsoft/terminal/issues/2947#issuecomment-562914135). …
=> Fixed self capture in TermControl

src/cascadia/TerminalCore/TerminalApi.cpp, src/cascadia/UnitTests_TerminalCore/TerminalApiTest.cpp, src/cascadia/UnitTests_TerminalCore/UnitTests.vcxproj
Uses the verification in `at` to ensure the index is correct (as @j4james suggests). If `at` throws, then returns false.
Can no longer repro the issue after the fix.
=> Fix SetColorTableEntry off-by-one error

src/cascadia/TerminalApp/Pane.cpp
This PR fixes the ability to move between already-split panes
=> Fix move focus between grouped panes (#3045)

src/host/ut_host/ScreenBufferTests.cpp, src/terminal/adapter/ITermDispatch.hpp, src/terminal/adapter/adaptDispatch.cpp, src/terminal/adapter/adaptDispatch.hpp, src/terminal/adapter/termDispatch.hpp, src/terminal/parser/OutputStateMachineEngine.cpp, src/terminal/parser/OutputStateMachineEngine.hpp, src/terminal/parser/telemetry.cpp, src/terminal/parser/telemetry.hpp
This adds support for the [`DECALN`](https://vt100.net/docs/vt510-rm/DECALN.html) escape sequence, which produces a kind of test pattern, originally used on VT terminals to adjust the screen alignment. It's needed to pass several of the tests in the [Vttest](https://invisible-island.net/vttest/) suite.
To start with, the `ActionEscDispatch` method in the `OutputStateMachineEngine` needed to be extended to check for a new intermediate type (`#`). Then when that intermediate is followed by an `8`, it dispatches to a new `ScreenAlignmentPattern` method in the `ITermDispatch` interface.
The implementation of the `ScreenAlignmentPattern` itself is fairly simple. It uses the recently added `PrivateFillRegion` API to fill the screen with the character `E` using default attributes. Then in …
=> Add support for the DECALN escape sequence

doc/user-docs/UsingJsonSettings.md
This change fixed a typo with the grammatical construct in the sentence.
Fixes a typo
=> doc: fix a typo in the default settings discussion

doc/cascadia/SettingsSchema.md
- The `Description` for `selectionBackground` in the Profiles section was in the `Default` column, add an empty default column to fix this.
Editing in GitHub normalized the newlines in the file to CRLF so the diff is not very nice unless you switch to rendered Markdown or use the `?w=1` query parameter.
I looked at the rendered Markdown and it put the description in the right column!
=> Fix columns in SettingsSchema.md Profiles section

src/cascadia/LocalTests_TerminalApp/KeyBindingsTests.cpp, src/cascadia/TerminalApp/ActionArgs.h, src/cascadia/TerminalApp/ActionArgs.idl, src/cascadia/TerminalApp/Pane.cpp, src/cascadia/TerminalApp/Pane.h
Adds support for `auto` as a potential value for a `splitPane` keybinding's `split` argument. For example:
```json
{ "keys": [ "ctrl+shift+z" ], "command": { "action": "splitPane", "profile": "matrix", "commandline": "cmd.exe", "split":"auto" } },
```
When set to `auto`, Panes will decide which direction to split based on the available space within the terminal. If the pane is wider than it is tall, the pane will introduce a new vertical split (and vice-versa).
Ran tests, played with it.
=> Add support for "Automatic" splits

src/cascadia/TerminalControl/Resources/en-US/Resources.resw, src/cascadia/TerminalControl/SearchBoxControl.cpp, src/cascadia/TerminalControl/SearchBoxControl.h, src/cascadia/TerminalControl/SearchBoxControl.idl, src/cascadia/TerminalControl/SearchBoxControl.xaml, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalControl/TerminalControl.vcxproj, src/cascadia/TerminalControl/init.cpp
This PR includes the non-blocking follow-ups of Search, which are addressed in this issue: https://github.com/microsoft/terminal/issues/3942
At current, the following two issues have been resolved: 
1. The place holder text in the TextBox ("Find...") needs to be localizable.
2. Search event should have a delegate with more args. This is illustrated below in Issue
The third issue, which is related to KeyDown events handling, is still under investigation. KeyDown events are now first sent to root TermControl, I need to figure out a way to make sure SearchBoxControl receives and handles the events first.
=> Fix Search non-blocking follow-ups

src/terminal/parser/OutputStateMachineEngine.cpp, src/terminal/parser/ut_parser/OutputEngineTest.cpp
This removes support for the the VT52 cursor movement operations, in preparation for PR #3271, since the cursor back operation conflicts with the VT100 [`IND`](https://vt100.net/docs/vt510-rm/IND.html) sequence, which we're planning to add. Eventually these ops will be brought back as part of a proper VT52 implementation, when appropriately activated by the [`DECANM`](https://vt100.net/docs/vt510-rm/DECANM.html) mode.
#976 #3271
The operations were removed from the `OutputStateMachineEngine`, and their associated test cases were removed from `StateMachineExternalTest`. There is no real loss of functionality here, since these sequences were never valid as implemented.
I've just tested manually to confirm that the sequences no longer work.
=> Remove the VT52 cursor movement operations

doc/cascadia/profiles.schema.json
Adds proper `type` for `ProfilesObject` definition to avoid warnings about matches of multiple schemas.
Original issue: #3909
Related PR: #3892
Relates VSCode issue: https://github.com/microsoft/vscode/issues/86738
1. Download `doc/cascadia/profiles.schema.json` locally
1. Open `profiles.json` from WT in VSCode
1. Replace `$schema` value with path to local copy (verified that all errors are still in place and validations works as before)
1. Update it with `type` on `ProfilesObject`
1. Check that `Matches multiple schemas when only one must validate` warning is fixed
=> Fix matches of multiple schemas on "profiles"

src/cascadia/TerminalControl/TermControl.cpp
Before, when a terminal window was focused, the blinking cursor would initially be hidden. This PR will immediately show the cursor when the window is focused, making it easier to keep track of the cursor.
#3761
I guess I'm the cursor guy now
* Switched rapidly between different panes, different tabs and focused and unfocused the main window repeatedly.
=> Immediately show the cursor on terminal focus

README.md
>  it's worth noting this for the benefit of people who are looking at this as an introduction to UWP.
=> Add notes concerning running WT directly from VS

src/host/getset.cpp
Fixes the bug @DHowett-MSFT found in conpty. Before conpty, this check was all one statement. With the addition of conpty, that statement was moved into a "am I not headless" check, to not restrict the conpty size based on the window size. However, the "is the user trying to resize the buffer smaller than the viewport" should have been done outside the headless check. This just splits that statement up.
Ran the tiny repro program Dustin provided - we no longer crash.
=> Fix a crash when calling SetConsoleScreenBufferSize in conpty

src/interactivity/win32/windowproc.cpp
When dragging _DEBUG_ conhost across a DPI boundary, we'd crash. This doesn't repro for some reason on Release builds. Maybe @miniksa can share some light why that is.
Dragged it across the boundary again, doesn't crash anymore 🙏
=> Fix a crash when dragging a debug conhost across a DPI boundary

src/cascadia/TerminalCore/TerminalDispatch.cpp
=> Fix flipped sense in TerminalDispatch::CursorPosition

src/host/PtySignalInputThread.cpp, src/host/screenInfo.cpp, src/interactivity/win32/Clipboard.cpp, src/renderer/base/renderer.cpp, src/renderer/dx/DxRenderer.cpp, src/terminal/adapter/InteractDispatch.cpp, src/terminal/adapter/adaptDispatch.cpp, src/terminal/parser/InputStateMachineEngine.cpp, src/terminal/parser/OutputStateMachineEngine.cpp, src/tools/vtpipeterm/VtConsole.cpp
FIx incorrect usage of THROW_IF_NULL_ALLOC which will throw E_OUTOFMEMORY unintentionally.
Build and run it.
=> Correct improper usage of THROW_IF_NULL_ALLOC

src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
Fix a test that regressed during #3575. It wasn't caught, because the LocalTests don't run in CI unfortunately.
Ran the local tests
=> Fix a test that regressed during #3575

src/cascadia/TerminalControl/TSFInputControl.cpp
The first argument to `NotifyTextChanged` incorrectly was `[0,0]`
instead of the length of the text to be removed from the
`CoreTextEditContext`.
Best source of documentation for `NotifyTextChanged`:
https://docs.microsoft.com/en-us/windows/uwp/design/input/custom-text-input#overriding-text-updates
FYI @DHowett-MSFT (just in case): C++/WinRT uses `winrt::param::hstring`
for string parameters which intelligently borrows strings. As such you
can simply pass a `std::wstring` to most WinRT methods without the need
of having to allocate an intermediate `hstring`. 🙂
I followed the reproduction instructions of #3706 and #3745 and ensured
the issue doesn't happen anymore.
Closes #3645
Closes #3706
Closes #3745
=> Fix IME/CoreTextEditContext not being reset properly

doc/cascadia/SettingsSchema.md, doc/cascadia/profiles.schema.json, src/cascadia/TerminalApp/GlobalAppSettings.cpp, src/cascadia/TerminalApp/GlobalAppSettings.h, src/cascadia/TerminalApp/TerminalPage.cpp, src/cascadia/TerminalApp/defaults.json
Adds a setting `snapToGridOnResize` to disable snapping the window on resize, and defaults it to `false`.
Introduced by pr #3181
=> Add a setting to disable pane snapping

src/cascadia/TerminalApp/WslDistroGenerator.cpp
We were eating an exception on exit in debug mode because we were using
wil to clean up half of a named pipe we'd already handed ownership of
over to the CRT. The CRT likes to tie up all its loose ends when it gets
unloaded, so it was coming along at exit and closing the handle again.
Big no-no.
=> wsl: actually close the pipe handle for wsl.exe, but only once

src/cascadia/TerminalConnection/ConptyConnection.cpp
This makes sure that things running inside WSL can see `WT_SESSION`.
Closes #3948.
=> Add WT_SESSION to WSLENV so it propagates into WSL

src/cascadia/TerminalApp/WslDistroGenerator.cpp
These utility distributions are used by Docker for Windows' WSL2
integration. They are not intended for user consumption.
There is a minimal chance that a user _has_ a distribution named `docker-desktop` or some superstring thereof, but this is taken as an acceptable level of risk.
=> Don't generate WSL distributions for docker-desktop*

doc/Debugging.md
Provide notes on how to use Postmortem debugging to get into a specific context in both WinDBG and Visual Studio
- I wrote something like this as a comment in #4150
=> doc: Add debugging notes on DebugBreak

src/host/ft_host/API_BufferTests.cpp, src/host/ft_host/API_DimensionsTests.cpp, src/host/ft_host/API_OutputTests.cpp, src/host/ft_host/API_TitleTests.cpp, src/host/ft_host/CJK_DbcsTests.cpp, src/host/ft_host/precomp.h, src/propsheet/console.cpp, src/propsheet/fontdlg.cpp, src/propsheet/precomp.h, src/propsheet/preview.cpp
It's 2020 now. It's *about* time that we move on from 1990's macros.
Remove global namespaced min/max and replace it with STL min/max.
Run it.
=> Remove global namespaced min/max and replace it with STL min/max

src/terminal/parser/stateMachine.cpp
Perform checking on `std::basic_string_view<T>.substr()` calls to
prevent running out of bounds and sporadic Privileged Instruction throws
during x86 tests.
apparent reason
It appears that not all `std::basic_string_view<T>.substr()` calls are
created equally. I rooted around for other versions of the code in our
source tree and found several versions that were less careful about
checking the start position and the size than the one that appears when
building locally on dev machines. 
My theory is that one of these older versions is deployed somewhere in
the CI. Instead of clamping down the size parameter appropriately or
throwing correctly when the position is out of bounds, I believe that
it's just creating a substring with a bad range over an
invalid/uninitialized memory region. Then …
=> Guard the substring calls in StateMachine parser to avoid bounds issues

src/host/_stream.cpp
This PR reverses the behaviour of the `IS_GLYPH_CHAR` macro, so it now actually returns true if the given char is a glyph, and false if it isn't. Previously it returned the opposite of that, which meant it had to be called as `!IS_GLYPH_CHAR` to get the correct result.
The original implementation returned true if the given character was a C0 control, or a DEL:
#define IS_GLYPH_CHAR(wch) (((wch) < L' ') || ((wch) == 0x007F))
It's now the exact opposite, so returns true for characters that are _not_ C0 controls, and are not the DEL character either: 
#define IS_GLYPH_CHAR(wch) (((wch) >= L' ') && ((wch) != 0x007F))
The macro was only used in one place, where is was being called as `!IS_GLYPH_CHAR` when the intent was actually to test whether the char _was_ a glyph. That code could now be …
=> Correct the behaviour of the IS_GLYPH_CHAR macro

src/buffer/out/textBuffer.cpp
When `GenHTML` or `GenRTF` encountered an empty line, they assumed that `CR` is the last character of the row and wrote it, even though in general `CR` and `LF` just break the line and instead of them either `<BR>` in HTML or `\line` in RTF is written. Don't know how I missed that in #2038.
Another question is whether the `TextAndColor` structure which these methods receive and which is generated by `TextBuffer::GetTextForClipboard` should really contain `\r\n` at the end of each row. I think it'd be cleaner if it didn't esp. that afaik these last 2 characters don't have associated valid color information.
Copied various terminal states and verified the generated HTML.
=> Fix redundant CR in formatted text copy

doc/cascadia/profiles.schema.json
Add `find` as a `ShortcutActionName`, so that it is recognized as a command for keybindings in profiles.json settings.
This seems to have been missed by #3590.
* [N/A] Requires documentation to be updated
* [N/A] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx
See #4218 
The command is recognized when using the updated schema:
=> Add find action to keybinding commands in Settings Profile Schema

src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/UnitTests_TerminalCore/TerminalApiTest.cpp
See [my code comment](https://github.com/microsoft/terminal/pull/4150#discussion_r364392640) below for technical details of the issue that caused #4145.
TBH I kinda hope this project could migrate to an internal use of UTF-8 in the future. 😶
Followed the "Steps to reproduce" in #4145 and ensured the "Expected behavior" happens.
=> Fixed a deadlock when printing surrogate pairs

src/cascadia/TerminalCore/TerminalDispatch.cpp, src/cascadia/TerminalCore/TerminalDispatch.hpp, src/host/getset.cpp, src/host/getset.h, src/host/outputStream.cpp, src/host/outputStream.hpp, src/host/ut_host/ScreenBufferTests.cpp, src/terminal/adapter/DispatchTypes.hpp, src/terminal/adapter/ITermDispatch.hpp, src/terminal/adapter/adaptDispatch.cpp, src/terminal/adapter/adaptDispatch.hpp, src/terminal/adapter/conGetSet.hpp, src/terminal/adapter/termDispatch.hpp, src/terminal/adapter/ut_adapter/adapterTest.cpp, src/terminal/parser/OutputStateMachineEngine.cpp, src/terminal/parser/OutputStateMachineEngine.hpp, src/terminal/parser/telemetry.cpp, src/terminal/parser/telemetry.hpp, src/terminal/parser/ut_parser/OutputEngineTest.cpp
This adds support for the `FF` (form feed) and `VT` (vertical tab) [control characters](https://vt100.net/docs/vt510-rm/chapter4.html#T4-1), as well as the [`NEL` (Next Line)](https://vt100.net/docs/vt510-rm/NEL.html) and [`IND` (Index)](https://vt100.net/docs/vt510-rm/IND.html) escape sequences.
#976 discusses the conflict between VT100 Index sequence and the VT52 cursor back sequence.
I've added a `LineFeed` method to the `ITermDispatch` interface, with an enum parameter specifying the required line feed type (i.e. with carriage return, without carriage return, or dependent on the [`LNM` mode](https://vt100.net/docs/vt510-rm/LNM.html)). The output state machine can then call that method to handle the various line feed control characters (parsed in the `ActionExecute` method), as well …
=> Add support for all the line feed control sequences

doc/cascadia/profiles.schema.json
`profiles.schema.json` did not have `auto` as a valid value for the `split` attribute. This PR adds the support and makes a minor update to the details associated with the `split` attribute.
Potentially the [`default`](https://github.com/microsoft/terminal/blob/master/doc/cascadia/profiles.schema.json#L217) value for `SplitPaneAction` should be set to `auto` as well. Let me know your thoughts.
Changed the `$schema` attribute in my local `profiles.json` to the updated `profiles.schema.json` and ensured that `auto` did not have a squiggly line like in #4245.
=> schema: add support for "auto" split value

doc/user-docs/ThirdPartyToolProfiles.md
New 3rd part tool "Far Manager" configuration.
=> doc: include FAR in ThirdPartyToolProfiles.md

src/host/getset.cpp, src/host/getset.h, src/host/outputStream.cpp, src/host/outputStream.hpp, src/host/ut_host/ScreenBufferTests.cpp, src/terminal/adapter/adaptDispatch.cpp, src/terminal/adapter/adaptDispatch.hpp, src/terminal/adapter/conGetSet.hpp, src/terminal/adapter/ut_adapter/adapterTest.cpp
Originally there were 3 different methods for implementing VT cursor movement, and between them they still couldn't handle some of the operations correctly. This PR unifies those operations into a single method that can handle every type of cursor movement, and which fixes some of the issues with the existing implementations. In particular it fixes the `CNL` and `CPL` operations, so they're now correctly constrained by the `DECSTBM` margins.
If this PR is accepted, the method added here should make it trivial to implement the `VPR` and `HPR` commands in issue #3428.
The new [`AdaptDispatch::_CursorMovePosition`](https://github.com/microsoft/terminal/blob/d6c4f35cf60a239cb1b8b7b7cc5796b06f78a884/src/terminal/adapter/adaptDispatch.cpp#L169) method is based on the proposal I made in issue …
=> Improve the VT cursor movement implementation

src/inc/til.h, src/inc/til/at.h, src/inc/til/some.h, src/types/inc/viewport.hpp, src/types/viewport.cpp
Let's give it a test drive.
Build and run it.
=> Use til::some<T,N> to replace the SomeViewports class

src/renderer/dx/CustomTextLayout.cpp
This change tries to fix column size calculation when shaping return glyphs that represents multiple characters (e.g. ligature).
This should fix #696.
Currently, it seems like CustomTextLayout::_CorrectGlyphRun generally assumes that glyphs and characters have a 1:1 mapping relationship - which holds true for most trivial scenarios with basic western scripts, and also many, but unfortunately not all, monospace "programming" fonts with programming ligatures.
This change makes terminal correctly processes glyphs that represents multiple characters, by properly accumulating the column counts of all these characters together (which I believe is more close to what this code originally intended to do).
There are still many issues existing in both CustomTextLayout as well as the TextBuffer, and …
=> Fix column count issues with certain ligature.

src/host/ut_host/ScreenBufferTests.cpp, src/terminal/adapter/ITermDispatch.hpp, src/terminal/adapter/adaptDispatch.cpp, src/terminal/adapter/adaptDispatch.hpp, src/terminal/adapter/termDispatch.hpp, src/terminal/parser/OutputStateMachineEngine.cpp, src/terminal/parser/OutputStateMachineEngine.hpp, src/terminal/parser/telemetry.cpp, src/terminal/parser/telemetry.hpp, src/terminal/parser/ut_parser/OutputEngineTest.cpp
This PR adds support for the `HPR` and `VPR`  escape sequences from the VT510 terminal. `HPR` moves the cursor position forward by a given number of columns, and `VPR` moves the cursor position downward by a given number of rows. They're similar in function to the `CUF` and `CUD` escape sequences, except that they're not constrained by the scrolling margins.
#3628 provided the new `_CursorMovePosition` method that made these operations possible
Most of the implementation is in the new `_CursorMovePosition` method that was created in PR #3628, so all we're really doing here is hooking up the escape sequences to call that method with the appropriate parameters.
I've extended the existing state machine tests for CSI cursor movement to confirm that the `HPR` and `VPR` sequences are dispatched …
=> Add support for the HPR and VPR escape sequences

OpenConsole.sln, src/cascadia/UnitTests_TerminalCore/UnitTests.vcxproj
In #4213 I added a dependency to the `UnitTests_TerminalCore` project on basically all of conhost. This _worked on my machine_, but it's consistently not working on other machines. This should fix those issues.
Made a fresh clone and built it.
=> Fix the `UnitTests_TerminalCore`'s dependency on `RendererGdi`

src/host/getset.cpp, src/host/getset.h, src/host/outputStream.cpp, src/host/outputStream.hpp, src/host/settings.cpp, src/host/settings.hpp, src/host/ut_host/ScreenBufferTests.cpp, src/terminal/adapter/DispatchTypes.hpp, src/terminal/adapter/ITermDispatch.hpp, src/terminal/adapter/adaptDispatch.cpp, src/terminal/adapter/adaptDispatch.hpp, src/terminal/adapter/conGetSet.hpp, src/terminal/adapter/termDispatch.hpp, src/terminal/adapter/ut_adapter/adapterTest.cpp, src/terminal/parser/ut_parser/OutputEngineTest.cpp
This adds support for the [`DECSCNM`](https://vt100.net/docs/vt510-rm/DECSCNM.html) private mode escape sequence, which toggles the display between normal and reverse screen modes. When reversed, the background and foreground colors are switched. Tested manually, with [Vttest](https://invisible-island.net/vttest/), and with some new unit tests.
This also fixes issue #72 for the most part, although if you toggle the mode too fast, there is no discernible flash.
I've implemented this as a new flag in the `Settings` class, along with updates to the `LookupForegroundColor` and `LookupBackgroundColor` methods, to switch the returned foreground and background colors when that flag is set. 
It also required a new private API in the `ConGetSet` interface to toggle the setting. And that API is …
=> Add support for the DECSCNM screen mode

src/cascadia/TerminalApp/Pane.cpp, src/cascadia/TerminalApp/Pane.h, src/cascadia/TerminalApp/Tab.cpp, src/cascadia/TerminalApp/Tab.h, src/cascadia/TerminalApp/TerminalPage.cpp, src/cascadia/TerminalControl/TSFInputControl.cpp, src/cascadia/TerminalControl/TSFInputControl.h, src/cascadia/TerminalControl/TSFInputControl.idl, src/cascadia/TerminalControl/TermControl.cpp
This commit introduces a new recursive pane shutdown that will give all
controls under a tab a chance to clean up their state before beign
detached from the UI. It also reorders the call to LastTabClosed() so
that the application does not exit before the final connections are
terminated.
It also teaches TSFInputControl how to shut down to avoid a dramatic
platform bug.
Fixes #4159.
Fixes #4336.
Validated through manual terminal teardown within and without the debugger, given a crazy number of panes and tabs.
=> Shut down all controls under a tab before we remove it from the list

doc/cascadia/profiles.schema.json
In https://github.com/microsoft/terminal/pull/3575, Terminal added support for the `rowsToScroll` field – which accepts integers or `"system"`. However, the settings schema only allows integers:
https://github.com/microsoft/terminal/blob/e675de3a881dfc70bd018e2593ad6e3043d2d13c/doc/cascadia/profiles.schema.json#L289-L295
which means writing `rowsToScroll: "system"` produces the following warning:
This PR fixes the issue.
1. Opened settings and replaced the `$schema` field with the updated schema from my fork (https://raw.githubusercontent.com/iamakulov/terminal/b5d4c9337d3f323613dd5209bb68decb86cce667/doc/cascadia/profiles.schema.json).
2. Validated that the `"system"` value doesn’t produce the warning anymore
3. Validated that the value of `false` (i.e., a boolean – a type that’s not …
=> Allow string values (like "system") in the `rowsToScroll` schema

src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp, src/cascadia/UnitTests_TerminalCore/TerminalBufferTests.cpp, src/cascadia/UnitTests_TerminalCore/TestUtils.h, src/cascadia/UnitTests_TerminalCore/UnitTests.vcxproj, src/host/ConsoleArguments.cpp, src/host/ConsoleArguments.hpp, src/host/VtIo.cpp, src/host/VtIo.hpp, src/host/globals.cpp, src/host/globals.h, src/host/screenInfo.hpp, src/host/ut_host/ConptyOutputTests.cpp, src/inc/test/CommonState.hpp, src/renderer/vt/vtrenderer.hpp
#4354 is a pretty complicated PR. It's got a bunch of conpty changes, but what it also has was some critical improvements to the roundtrip test suite. I'm working on some other bugfixes in the same area currently, and need these tests enhancements in those branches _now_. The rest of #4354 is complex enough that I don't trust it will get merged soon (if ever). However, these fixes _should_ be in regardless.
This is four main changes:
* Enable conpty to be fully enabled in unittests. Just setting up a VT renderer isn't enough to trick the host into being in conpty mode - it also needs to have some other flags set.
* Some minor changes to `CommonState` to better configure the common test state for conpty
* Move some of the verify helpers from …
=> Add just the test infrastructure bits from #4354

src/cascadia/TerminalCore/ITerminalApi.hpp, src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalCore/TerminalApi.cpp, src/cascadia/TerminalCore/TerminalDispatch.cpp, src/host/_stream.cpp, src/host/cmdline.h, src/host/outputStream.cpp, src/host/screenInfo.cpp, src/host/screenInfo.hpp
This PR removes all of the VT-specific functionality from the `WriteCharsLegacy` function that dealt with control characters, since those controls are now handled in the state machine when in VT mode. It also removes most of the control character handling from the `Terminal::_WriteBuffer` method for the same reason.
This is a followup to PR #4171
There are four changes to the `WriteCharsLegacy` implementation:
1. The `TAB` character had special case handling in VT mode which is now no longer required. This fixes a bug in the Python REPL editor (when run from a cmd shell in Windows Terminal), which would prevent you tabbing past the end of the line. It also fixes #3971.
2. Following on from point 1, the `WC_NONDESTRUCTIVE_TAB` flag could also now be removed. It only ever applied in VT …
=> Remove unneeded VT-specific control character handling

doc/user-docs/UsingCommandlineArguments.md, src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp, src/cascadia/TerminalApp/AppCommandlineArgs.cpp, src/cascadia/TerminalApp/AppCommandlineArgs.h
This commit fixes an issue where "wt -d C: wsl -d Alpine" would be
parsed as "wt -d C: -d Alpine wsl" and rejected as invalid due to the
repeated -d. It also fixes support for the option parsing terminator,
--, in all command lines.
Fixes #4277.
https://github.com/CLIUtils/CLI11/issues/417
Tests, manual wailing.
=> Configure CLI11 to stuff all unknown positionals into the cmdline

src/host/getset.cpp, src/host/output.cpp, src/host/ut_host/ScreenBufferTests.cpp
This is a pair of related fixes to conpty. For both of these bugs, the root cause was that the cursor was getting set to Off in conpty. Without the `CursorBlinkerTimer`, the cursor would remain off, and frames that only had cursor movements would not update the cursor position in the terminal.
Recall that there's a bunch of cursor state that's hard to parse without looking up:
* `Visibility` This controls whether the cursor is visible _at all_, regardless if it's been blinked on or off
* `Blinking` controls whether the blinker timer should do something, or leave the cursor alone.
* `IsOn`: When the cursor is blinking, this alternates between true and false. 
The trick here is that we only `TriggerCursorMoved` when the cursor is `On`, and there …
=> A pair of fixes related to cursor movement in conpty

src/cascadia/TerminalControl/SearchBoxControl.xaml
We were overriding the button foreground and the placeholder foreground using our
own custom resource names. They didn't exist in HC.
Instead of making them exist in HC, I made us use and override the real resource
names. Those ones have HC colors defined by the platform!
Fixes #4393.
=> Fix the search box in High Contrast by using the right theme resources

src/cascadia/TerminalApp/App.xaml, src/cascadia/TerminalApp/AppLogic.cpp, src/cascadia/TerminalApp/TerminalPage.cpp
Added styling to the buttons on the Close All Tabs dialog box.
=> Round and style buttons on close all tabs dialog

src/cascadia/TerminalApp/AppCommandlineArgs.cpp, src/cascadia/TerminalApp/Resources/en-US/Resources.resw, src/cascadia/TerminalApp/lib/pch.h, src/cascadia/WinRTUtils/inc/LibraryResources.h
Fixes #4155.
```
Summary: Total=23, Passed=22, Failed=1, Blocked=0, Not Run=0, Skipped=0
```
The failing test is the same one as before. It is not germane to this pull request.
=> Kill NEEDS_LOC and move cmdline descriptions into resources

src/cascadia/TerminalControl/TermControl.cpp
This PR addresses the following two issues:
#4203: If a selection is active, a <kbd>shift</kbd>-LeftClick will set the SelectionEnd to where the pointer is.  
#3911: Currently, any keypress will clear selection, and will pass through to the terminal. This PR will make it so that if a selection is active, _any_ keypress will clear the selection and then any keypress _except_ <kbd>esc</kbd> will pass through to the terminal.
Played around a whole bunch with shift-clicking selections and regular clicking selections.
Also played around with selections and dismissing with all sorts of keypresses and keychords.
Tests all pass still!
=> selection: Shift-Click to set endpoint, clear & discard keypress on ESC

src/types/UiaTextRangeBase.cpp
`GetBoundingRect()` has inclusive endpoints. I previously assumed end was exclusive so I drew the bounding rect wrong.
This also means that we should allow start and end to be the same. Which means that FailFastIf would get hit...
=> Adjust GetBoundingRect() for Inclusive end

src/host/VtInputThread.cpp, src/host/VtInputThread.hpp, src/host/_stream.cpp, src/host/_stream.h
Replace  `utf8Parser` with `til::u8u16` in order to have the same conversion algorithms used in terminal and conhost.
This PR is a follow up of #4093 
This PR addresses item 2 in this list:
1. ✉ Implement `til::u8u16` and `til::u16u8` (done in PR #4093)
2. ✔ **Unify UTF-8 handling using `til::u8u16` (this PR)**
2.1. ✔ **Update VtInputThread::_HandleRunInput()**
2.2. ✔ **Update ApiRoutines::WriteConsoleAImpl()**
2.3. ❌ (optional / ask the core team) Remove Utf8ToWideCharParser from the code base to avoid further use
3. ❌ Enable BOM discarding (follow up)
3.1. ❌ extend `til::u8u16` and `til::u16u8` with a 3rd parameter to enable discarding the BOM
3.2. ❌ Make use of the 3rd parameter to discard the BOM in all current function callers, or (optional / ask the core team) make it the default …
=> Unify UTF-8 handling using til::u8u16 & revise WriteConsoleAImpl

doc/cascadia/profiles.schema.json
Added `#000000` as default for `background` and `#FFFFFF` as default for `foreground` in JSON schema.
=> schema: add default colors for foreground and background

src/cascadia/WindowsTerminal/main.cpp
This fixes a crash caused by Narrator starting *before* terminal.
Fixes #2907.
For context,
```
// We must initialize the main thread as a single-threaded apartment before
// constructing any Xaml objects. Failing to do so will cause some issues
// in accessibility somewhere down the line when a UIAutomation object will
// be queried on the wrong thread at the wrong time.
// We used to initialize as STA only _after_ initializing the application
// host, which loaded the settings. The settings needed to be loaded in MTA
// because we were using the Windows.Storage APIs. Since we're no longer
// doing that, we can safely init as STA before any WinRT dispatches.
```
=> Initialize Windows Terminal in STA

src/cascadia/PublicTerminalCore/PublicTerminalCore.vcxproj
In debug builds that haven't been LTO'd or had unused refs removed,
there will still be a spurious reference to api-ms-win-winrt-core (or
something similar.)
In release builds, that reference is gone.
Fixes #4519.
=> Force the use of named forwarders in PublicTermCore for Win7

src/types/UiaTextRangeBase.cpp, src/types/UiaTextRangeBase.hpp
In UIA Providers, update the concept of the size of the text buffer to just go down to the virtual bottom. This significantly increases performance to the point that it can even be used in the Debug build.
We already actually have this concept exposed to us via the IUiaData. So we're just leveraging that and putting it in a helper function `_getBufferSize()`.
Tested word nav on Narrator (previously hung). Now it works on the Debug build. Previously, using the release build was necessary to be able to test this feature.
=> Limit Concept of TextBuffer's Size in UIA

src/cascadia/TerminalControl/TermControlUiaProvider.cpp, src/cascadia/TerminalControl/TermControlUiaProvider.hpp, src/cascadia/TerminalControl/UiaTextRange.cpp, src/interactivity/win32/screenInfoUiaProvider.hpp, src/types/ScreenInfoUiaProviderBase.h
The UIA Provider now scrolls the viewport when necessary. This just fills in the missing virtual function in Terminal to have the same behavior as what it does in ConHost.
`ChangeViewport` is now a virtual function at the `ScreenInfoUiaProvider` layer to have access to the TermControl.
In ConHost, we pass this call up to the WindowUiaProvider layer. In Terminal, we don't need to do that because the concept of updating the viewport is handled at the TermControl layer. So we just call that function and _voila_!
Verified using Accessibility Insights and Narrator.
=> uia: add support for scrolling the viewport

README.md
New Link https://github.com/microsoft/terminal/blob/master/CONTRIBUTING.md
Just updating a link.
Link for Contributors Guide change from https://github.com/microsoft/terminal/blob/master/contributing.md to https://github.com/microsoft/terminal/blob/master/CONTRIBUTING.md
Well, the link is working.
=> doc: fix link to Contributor's Guide in README.md

src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
This will attempt to match the style of the user's JSON.
Caveats:
1. If the user has no profiles, it'll explode. This isn't new.
2. If the user's indentation style if `{profile}, {profile}, {profile}` (that is: no indentation), you'll get this:
```
{profile}, {profile}, {profile},
{
new profile content
}
```
There may be something better we can do by copying their newline (or lack thereof) and using it in our generator or detecting the indentation of their members as well.
That's an exercise for later.
Ref #2805
=> When patching profiles in, copy the user's indentation

src/cascadia/TerminalControl/TermControl.cpp
The issue seems to be how `SwapChainScaleChanged` gets fired and attempts to tell the renderer
to `UpdateDPI` when the renderer is gone. So, as a quick bandaid, we'll put a quick check to only do the thing if the renderer is alive.
Held my new tab button for about thirty seconds then held the close tab button until all tabs closed without a crash.
=> Fix crash when closing a ton of tabs at once

src/renderer/vt/state.cpp, src/renderer/vt/tracing.cpp
- If no one is listening to the ETW provider for the VT Renderer for diagnostic purposes, do not spend time allocating/deleting/formatting strings for presentation in TraceLogging messages.
WPR/WPA
Before: 321/3016 samples on hot path (10.64%)
After: 0/1266 samples on the same path (0%)
=> Avoid processing VT Render Trace strings when no one is listening

src/renderer/base/thread.cpp, src/renderer/base/thread.hpp
This is an attempt to reduce unnecessary `SetEvent` CPU overhead.
Redrawing is triggered intensively when terminal is under load. The code here indicates that the redraw call will be throttled:
https://github.com/microsoft/terminal/blob/94fc40ed31c0de050304248644458b21d0cce2e9/src/renderer/base/renderer.cpp#L154
Still, the `SetEvent` call itself stands out a 7% usage of CPU in Release build. Those `SetEvent` calls are mostly useless because most of them are invoked while the rendering thread is sleeping (for `s_FrameLimitMilliseconds` long). 
I've tried to guard all the useless calls with `_fPainting` flag, as in this PR. It works great for the CPU. But the rendering became noticeably sluggish. 
I've figured that the rendering thread design is flawed in the perspective of this certain …
=> Throttle SetEvent call in render thread

README.md
I noticed we are missing the install from Store link.  Here is my suggested text
=> readme: reintroduce the Store install link

doc/user-docs/ThirdPartyToolProfiles.md
On **Adding profiles for third-party tools** documentation, `cmder` and `Anaconda` profiles are incorrect due to double quotes escape missing on the `commandline` JSON property.
This PR fixes the sample by adding `\"` on the file path of each tool that uses `cmd.exe` to run.
=> fix: escape double quotes on cmder and Anaconda profiles

build/pipelines/templates/check-formatting.yml, tools/OpenConsole.psm1
This will make `Invoke-CodeFormat` less bad.
=> Batch up to 64 files per clang-format to speed it up

OpenConsole.sln, src/winconpty/ft_pty/ConPtyTests.cpp, src/winconpty/ft_pty/precomp.cpp, src/winconpty/ft_pty/precomp.h, src/winconpty/ft_pty/winconpty.FeatureTests.vcxproj
This will allow us to run the ConPTY tests in CI.
I've run the tests.
Please note: this code is unchanged (apart from `wil::ScopeExit` -> `wil::scope_exit`) from Windows. Now is not the time to comment on their perfectness.
=> Migrate the ConPTY functional tests out of Windows

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
Currently, clicking on an unfocused terminal with a selection active will trigger `copyOnSelect`. This is because the check for `copyOnSelect` and copying to the clipboard is bound to when the Pointer is released. This works fine for when a user performs a click-drag selection, but it inadvertently also triggers when the user performs a single click on an unfocused terminal. We expect `copyOnSelect` to trigger only on the first time a selection is completed. 
This PR will allow the user to single click on an unfocused terminal that has a selection active without triggering a copyOnSelect. It also ensures that any click-drag selection, whether it's on an unfocused or focused terminal, will trigger copyOnSelect.
Performed manual testing involving permutations of multiple panes, tabs, in …
=> Fix duplicate copyOnSelect when clicking on an unfocused terminal

src/renderer/dx/DxRenderer.cpp, src/renderer/dx/DxRenderer.hpp
Adds an ETW provider for tracing out operations inside the DirectX Renderer.
This supports #2191 and #778 and other rendering issues.
This declares and defines the provider with the a GUID appropriate for the namespace and adds an initial invalidation rectangle method for figuring out what is being drawn mostly to understand what could be differential.
Implemented provider.
Opened real-time ETW tracing tool
Ran the Terminal and watched invalidation events appear live
=> Add DxEngine drawing ETW tracing for debugging and diagnostics purposes

src/inc/til/u8u16convert.h, src/til/ut_til/u8u16convertTests.cpp
Fixes a flaw that happened if `til::u8u16` received a single lead byte.
The loop for caching partials didn't run and thus, the lead byte was
converted to U+FFFD. That's because the loop starts with `sequenceLen`
initialized with 1. And if the string has a length of 1 the initial
condition is `1<1` which is evaluated to `false` and the body of the
loop was never executed.
1) updated the code of the state class and tested manually that `printf
"\xE2"; printf "\x98\xBA\n"` prints a U+263A character
2) updated the unit tests to make sure that still up to 3 partials are
cached
3) updated the unit tests to make sure caching also works if the string
consists of a lead byte only
4) tested manually that #4086 is still resolved
=> Ensure til::u8u16 still works if the string consists of just a lead byte

src/cascadia/PublicTerminalCore/HwndTerminal.cpp, src/cascadia/PublicTerminalCore/HwndTerminal.hpp, src/cascadia/PublicTerminalCore/pch.h, src/cascadia/TerminalControl/TermControlAutomationPeer.cpp, src/cascadia/TerminalControl/TermControlAutomationPeer.h, src/cascadia/TerminalControl/TerminalControl.vcxproj, src/cascadia/TerminalControl/XamlUiaTextRange.cpp, src/cascadia/TerminalControl/XamlUiaTextRange.h, src/cascadia/WpfTerminalControl/NativeMethods.cs, src/cascadia/WpfTerminalControl/TerminalContainer.cs, src/cascadia/WpfTerminalControl/TerminalControl.xaml.cs, src/interactivity/win32/uiaTextRange.cpp, src/interactivity/win32/uiaTextRange.hpp, src/types/IControlAccessibilityInfo.h, src/types/ScreenInfoUiaProviderBase.h, src/types/TermControlUiaProvider.cpp, src/types/TermControlUiaProvider.hpp, src/types/TermControlUiaTextRange.cpp, src/types/TermControlUiaTextRange.hpp, src/types/UiaTextRangeBase.hpp, src/types/lib/types.vcxproj, src/types/lib/types.vcxproj.filters, src/types/sources.inc
This PR hooks up the existing UIA implementation to the WPF control. Some existing code that was specific to the UWP terminal control could be shared so that has been refactored to a common location as well.
WPF control was brought up in UISpy and the UIA tree was verified. NVDA was then used to check that screen readers were operating properly.
=> Move Terminal UIA provider into Types & hook it up to the WPF control

src/cascadia/CascadiaPackage/CascadiaPackage.wapproj, src/terminal/adapter/adaptDefaults.hpp, src/terminal/adapter/conGetSet.hpp
This commit introduces two fixes for C5205 (delete of an abtract class
without a virtual dtor) and one fix for a very hopeful VS version gating
that didn't pan out.
=> Fix the build on VS 2019 Update 5

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControlAutomationPeer.cpp
(I believe that this) fixes #4623, which looks like it was caused by
floats being truncated when stuffed into LONGs for UIA purposes.
=> TermControl: don't use narrow when narrow_cast will do

src/cascadia/TerminalControl/TSFInputControl.cpp, src/cascadia/TerminalControl/TSFInputControl.h, src/cascadia/WinRTUtils/inc/Utils.h
Currently, while in IME mode, selections with the Emoji/Kaomoji/Symbol Picker (which is brought up with <kbd>win+.</kbd>) are not displayed until the user starts a new composition. This is due to the fact that we hide the TextBlock when we receive a CompositionCompleted event, and we only show the TextBlock when we receive a CompositionStarted event. Input from the picker does not count as a composition, so we were never showing the text box, even if the symbols were thrown into the inputBuffer. In addition, we weren't receiving CompositionStarted events when we expected to.
We should be showing the TextBlock when we receive _any_ text, so we should make the TextBlock visible inside of `TextUpdatingHandler`. Furthermore, some really helpful discussion in #3745 around wrapping the …
=> Display Emojis, Kaomojis, and symbols while in IME mode

src/cascadia/TerminalControl/TermControl.cpp
Currently, when the user attempts to type using IME while the Search Box is focused, the input goes to the terminal instead. This is due to the fact that the `TSFInputControl` assumes it's in control whenever TermControl gets focus. So, it'll intercept IME input before the Search Box receives it. We simply need to modify `TermControl::GotFocus` to check if the SearchBox has focus. If it does, `TSFInputControl::NotifyFocusEnter` shouldn't be called.
As a small side fix, I've also disabled the terminal cursor blinking when the Search Box has focus.
Thinking a little further, if we have more features in the future that behave like search box (i.e. advanced tab switcher, or any other XAML controls that pop up) and require text input, we might need to create a sort of …
=> Allow IME input in Search Box

src/renderer/dx/CustomTextLayout.cpp
- Surrogate pairs are being split in half with the run splitting check.
- Related to #4708 but not going to fix it.
- The adjustment of the run heights in the correction function reports back a text index and a scaling factor. However, I didn't remember at the time that the text is being stored as UTF-16. So the index given can be pointing to the high surrogate of a pair. Thus adding 1 to split "after" the text character, then backing up by 1 isn't valid in if the index given was for a high surrogate.
The quick fix is to advance by two if it's a high surrogate and one otherwise.
- Used the sample code from #4704 to print the house emoji in various situations into the buffer.
=> Avoid splitting surrogate pairs when breaking runs for scaling

src/cascadia/PublicTerminalCore/PublicTerminalCore.vcxproj
The new UIA code in `PublicTerminalCore` broke windows 7 support by referring to API set dlls for UIA. This PR changes the link line to link to UIAutomationcore.dll directly.
Terminal run on a windows 7 VM to ensure correct behavior.
=> Fix PublicTerminalCore APIset usage on Windows 7

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalControl/TermControl.xaml, src/cascadia/TerminalControl/TerminalControl.vcxproj
This commit removes all of the custom UI initialization code in
TermControl and replaces it with a xaml file. Some dead or reundant code
was removed as part of this refactoring.
It also fixes two (quasi-related) issues:
* The search box, on first launch, was offset by the scrollbar even if
the scrollbar was invisible.
* The scrollbar state wasn't hot-reloadable.
Launched, opened, closed, searched and TSF-inputted-into controls.
=> Convert TermControl to .xaml

src/renderer/base/thread.cpp, src/renderer/base/thread.hpp
Fix a bug where the `Renderer::PaintFrame` method:
1. is not called until the next `RenderThread::NotifyThread` call but needs to be called because there the terminal was updated (theoretical bug)
2. is called twice but needs to be called only once (verified bug)
The bug was introduced by #3511.
In the original code, `_fNextFrameRequested` is set to `true` in render thread because `std::atomic_flag::test_and_set` is called.
This is wrong because it means that the render thread will render the terminal again even if there is no change after the last render.
I think the the goal was to load the boolean value for `_fNextFrameRequested` to check whether the thread should sleep or not.
The problem is that there is no method on `std::atomic_flag` to load its boolean value. I guess what happened …
=> Fix RenderThread's notify mechanism

src/cascadia/PublicTerminalCore/HwndTerminal.cpp, src/cascadia/PublicTerminalCore/HwndTerminal.hpp, src/cascadia/WpfTerminalControl/TerminalContainer.cs
PR #4548 inadvertantly broke mouse button input in the WPF control. This happened due to the extra layer of HWND indirection. The fix is to move the mouse button handling down into the native control where the window messages are now being sent.
VS was patched with new bits to ensure correct behavior.
=> fix mouse events in the wpf control

doc/user-docs/index.md
Tip to open Windows Terminal in current directory
Open Windows Terminal in current directory by typing `wt -d .` in the address bar.
=> doc: add a tip about opening terminal in current directory

src/cascadia/TerminalControl/TermControl.cpp
Match conhost behavior and clear selection on viewport/font resize.
Retried attached bug repro steps
=> Clear Selection on Viewport/Font Resize

src/renderer/dx/CustomTextLayout.cpp
Adjusts column padding code in `CustomTextLayout` to only pad out for surrogate pairs, not anything that reports two columns.
- See also #4747
For surrogate pairs like high Unicode emoji, we receive two wchar_ts but only one column count (which is usually 2 because emoji are usually inscribed in the full-width squares.) To compensate for this, I added in a little padding function at the top of the `CustomTextLayout` construction that adds a column of 0 aligned with the second half of a surrogate pair so the text-to-glyph mapping lines up correctly.
Unfortunately, I made a mistake while either responding to PR feedback in #4747 or in the first place and I made it pad out extra 0 columns based on the FIRST column count, not based on whether or not there is a trailing surrogate pair. The …
=> Stop padding text columns for fullwidth characters

doc/user-docs/UsingJsonSettings.md
Corrected issues documented in #4783
Updated documentation that when used causes JSON syntax errors
Validated based on syntax error checking in VSCode and based on a new profiles.json created using most recent version of Windows Terminal.
=> Fix JSON syntax errors in UsingJsonSettings.md

src/cascadia/TerminalConnection/AzureConnection.cpp, src/cascadia/TerminalConnection/AzureConnection.h, src/cascadia/TerminalConnection/Resources/Resources.language-en.resw
This pull request comprises four commits that improve the Azure connection.
This commit replaces the AzureConnection's input handler with one that
acts more like "getline()". Instead of the Read thread setting a state
and WriteInput filling in the right member variable, the reader blocks
on the user's input and receives it in an optional<string>.
This moves the input number parsing and error case handling closer to
the point where those inputs are used, as opposed to where they're
collected.
It also switches our input to be "line-based", which is a huge boon for
typing tenant numbers >9. This fixes #3233. A simple line editor
(supporting only backspace and CR) is included.
It also enables echo on user input, and prints it in a nice pretty green
color.
It also enables input queueing: if …
=> AzCon: improve input, usability, reliability (4 commits)

src/buffer/out/CharRow.cpp, src/buffer/out/CharRow.hpp, src/buffer/out/textBuffer.cpp, src/buffer/out/textBuffer.hpp, src/types/ScreenInfoUiaProviderBase.cpp, src/types/UiaTextRangeBase.cpp, src/types/UiaTracing.cpp, src/types/UiaTracing.h
1) Improves the performance of word-recognition operations such as word
navigation in UIA and selection.
2) Fixes a bug where attempting to find the next word in UIA, when none
exists, would hang
3) TraceLogging code only runs when somebody is listening
- The concept of a delimiter class got moved to the CharRow.
- The buffer iterator used to save a lot more information than we needed
- I missed updating a tracing function after making GetSelection return
one text range. That is fixed now.
Performed Word Navigation under Narrator and NVDA.
NOTE: The release build should be used when testing to optimize
performance
Closes #4703
=> Improve Word Navigation/Selection Performance

src/cascadia/TerminalApp/AppLogic.cpp, src/cascadia/TerminalApp/AppLogic.h, src/cascadia/TerminalApp/AppLogic.idl, src/cascadia/TerminalApp/IF7Listener.idl, src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalControl/TermControl.idl, src/cascadia/WindowsTerminal/AppHost.cpp, src/cascadia/WindowsTerminal/AppHost.h, src/cascadia/WindowsTerminal/main.cpp
The Xaml input stack doesn't allow an application to suppress the "caret
browsing" dialog experience triggered when you press F7.
The official recommendation from the Xaml team is to catch F7 before we
hand it off.
This commit introduces a special F7 handler and an ad-hoc implementation of event bubbling.
Runtime classes implementing a custom IF7Listener interface are
considered during a modified focus parent walk to determine who can
handle F7 specifically.
If the recipient control handles F7, we suppress the message completely.
This event bubbler has some minor issues -- the search box will not be
able to receive F7 because its parent control implements the handler.
Since search is already mostly a text box, it doesn't _need_ special
caret browsing functionality as far as I can tell. …
=> Tunnel F7 keypresses directly into special handlers in TermControl

src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp, src/cascadia/TerminalApp/ActionArgs.h, src/cascadia/TerminalApp/AppKeyBindings.h, src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp, src/cascadia/TerminalApp/AppLogic.cpp, src/cascadia/TerminalApp/CascadiaSettings.cpp, src/cascadia/TerminalApp/CascadiaSettings.h, src/cascadia/TerminalApp/GlobalAppSettings.cpp, src/cascadia/TerminalApp/GlobalAppSettings.h, src/cascadia/TerminalApp/Resources/Resources.language-en.resw, src/cascadia/TerminalApp/TerminalWarnings.h
Adds warning messages for a pair of keybindings-related scenarios. This covers the following two bugs:
* #4239 - If the user has supplied more than one key chord in their `"keys"` array.
* #3522 - If a keybinding has a _required_ argument, then we'll display a message to the user
- currently, the only required parameter is the `direction` parameter for both `resizePane` and `moveFocus`
When we get to #1334, we'll want to remove the `TooManyKeysForChord` warning.
Tested manually, added tests.
=> Add warning messages for bad keybindings

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp, src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj, src/cascadia/WindowsTerminal/packages.config
This solution was vetted by the DWM team.
Fixes #3425.
=> Apply dark window borders to NonClientIslandWindow using ThemeHelpers

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
Pretty straightforward. When we get a `WM_DISPLAYCHANGE`, that means the display's DPI changed. When that happens, resize the drag bar, so that it'll reflect the new scaling.
I'm doing this to unblock #4778 
Man I've changed the DPI of my displays so many times in the last 30 minutes. I draged the window across a bunch of DPI boundaries too.
=> Resize the drag bar on `WM_DISPLAYCHANGE`

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
We're deref'ing a null `_terminal`. Don't do that. This is a _okay_ fix, mostly to stem the bleeding. @DHowett-MSFT's got a mind for a real fix to #4166, but this isn't it.
=> Fix a rampant crash in `TSFInputControl` when opening new tabs

src/tools/U8U16Test/U8U16Test.vcxproj
Translate automatically generated message text from German into English.
#4799
@miniksa mentioned in https://github.com/microsoft/terminal/pull/4799#discussion_r389166916
> Actually..... we would consider that block to be wrong. It should have had the English error text there. [...] It's just our practice to have everything be in English as that's our company's working language. [...]
The translation is based on the message text found in the official docs: https://docs.microsoft.com/en-us/nuget/Consume-Packages/Package-restore-troubleshooting
=> translate German message into English

src/cascadia/TerminalControl/TSFInputControl.cpp
Emoji composition was only being shown one letter at a time. This is because of the way I expected `CoreTextTextUpdatingEventArgs.Range` to be provided to TSFInputControl during composition (for Chinese/Japanese IME). Emoji IME composition gives the `StartCaretPosition` as the same as `EndCaretPosition`, unlike how for Chinese/Japanese IME, `StartCaretPosition` is usually the start of the composition and `EndCaretPosition` is the latest character in the composition. The solution is to change the `_inputBuffer.substr()` call to simply grab all of the buffer starting from `_activeTextStart`. This way I can ensure that I grab all of the "active text", instead of trusting the given `args.Range` to tell me the active text.
Chinese, Japanese, Korean, Emoji composition performed. Emoji selection …
=> Allow Emoji composition to be seen in the TSF TextBlock

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
Add a `SizeChanged` handler to the titlebar content UI element. It's possible that this element's size will change after the dragbar's. When that happens, the drag bar won't send another `SizeChanged` event, because the dragbar's _size_ didn't change, only it's position.
We originally duped this issue to #4166, but after #4829 fixed that issue, this one persisted. They're all related, and _look_ like dupes, but they weren't.
I had a solid 100% repro that doesn't repro anymore.
I've maximized, restored, resized, and generally played with the window a bunch.
=> Update the dragbar when the titlebar content size changes

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
Right clicking on a focused tab while Copy On Select is active currently copies any active selection. This is because `PointerReleasedHandler` doesn't check for the mouse button that was released. 
During a mouse button release, only the left mouse button release should be doing anything.
These are the scenarios I've tested. They're a combination of in focus/out of focus, Copy On Select on/off, left/right click pressed and their move and release variants.
From Out of Focus:
- Left Click = Focus
- Left Click Move = Focus + Selection
- Left Click Release
- CoS on = Copy
- CoS off = Nothing
- Shift Left Click = Focus
- Right Click 
- Focus 
- CoS on = Paste
- CoS off = Copy if Active Selection, Paste if not.
- Right Click Move = Nothing
- Right Click Release = Nothing
From In Focus
- Left …
=> Ignore right-click copy when copy on select is enabled

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
When we are maximized or fullscreened, check for the presence of the taskbar in auto-hide mode. If the Terminal finds the taskbar on any side of the monitor, adjust our window rect by just a little bit, so that the taskbar can still be revealed by the user mousing over that edge.
Note to future code archeologists:
This doesn't seem to work for fullscreen on the primary display. However, testing a bunch of other apps with fullscreen modes and an auto-hiding taskbar has shown that _none_ of them reveal the taskbar from fullscreen mode. This includes Edge, Firefox, Chrome, Sublime Text, Powerpoint - none seemed to support this. 
This does however work fine for maximized.
I'm maximized and fullscreened the Terminal a lot in the last two days.
=> Reveal the taskbar when the user has the Terminal maximized or fullscreen

src/cascadia/TerminalControl/TSFInputControl.cpp, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/pch.h
I originally thought that setting `TSFInputControl::_editContext.InputPaneDisplayPolicy` to be Automatic would allow the InputPanel to show and hide automatically when `TSFInputControl` gains and loses focus. It doesn't seem to behave that way, so we'll show the InputPanel manually. 
I'll show the panel during `PointerPressedHandler` and during `GotFocusHandler`. A user will have the on-screen keyboard pop up when getting focus, but if they close the keyboard, they can simply re-tap on the terminal to bring it back up.
Played on my surfaces book with the on screen keyboard by closing/tapping on the terminal and using the search box.
=> Show InputPanel on focus and pointer press

src/renderer/dx/CustomTextLayout.cpp
With certain font faces at certain sizes, the advances seem to be
slightly more than the pixel grid; Cascadia Code at 13pt (though, 200%
scale) had an advance of 10.000001.
This commit makes it so that anything sub-1/100 of a cell won't make us
break up runs, because doing so results in suboptimal rendering.
Fixes #4806.
---
I wrote a renderer hack that colors text runs by their origin x (blue+) and y (red+).
This shows that at font size 12, we were only doing one run per line.
This shows that at font size _13_, we were doing one run _per cell_.
=> Suppress run breaking for abs. differences < 0.001 in advance

src/interactivity/onecore/BgfxEngine.cpp, src/interactivity/onecore/BgfxEngine.hpp, src/renderer/base/renderer.cpp, src/renderer/dx/DxRenderer.cpp, src/renderer/dx/DxRenderer.hpp, src/renderer/gdi/gdirenderer.hpp, src/renderer/gdi/math.cpp, src/renderer/inc/IRenderEngine.hpp, src/renderer/uia/UiaRenderer.cpp, src/renderer/uia/UiaRenderer.hpp, src/renderer/vt/XtermEngine.cpp, src/renderer/vt/math.cpp, src/renderer/vt/vtrenderer.hpp, src/renderer/wddmcon/WddmConRenderer.cpp, src/renderer/wddmcon/WddmConRenderer.hpp
- Changes the `IRenderEngine` interface to return a vector of values instead of just a single one. Engines that want to report one still can. Engines that want to report multiple smaller ones will be able to do so going forward.
- Some of my ideas for the `DxEngine` require the ability to specify multiple smaller rectangles instead of one giant one, specifically to mitigate the case where someone refreshes just one cell in two opposite corners of the display (which currently coalesces into refreshing the entire display.)
- This is pulled out into an individual PR to make it easier to review that concept changing.
- Ran the Terminal
=> Move dirty interface to N rectangles, not just one

src/cascadia/TerminalConnection/ConptyConnection.cpp
I noticed a crash in debug builds when a connected application terminates; we get its exit code, then we destruct, and the u16state is used after it's destructed by the process's last words.
=> Don't let ConptyConnection be UAF

src/host/VtInputThread.cpp, src/host/outputStream.cpp, src/host/outputStream.hpp, src/terminal/adapter/IInteractDispatch.hpp, src/terminal/adapter/InteractDispatch.cpp, src/terminal/adapter/InteractDispatch.hpp, src/terminal/adapter/adaptDispatch.cpp, src/terminal/adapter/conGetSet.hpp, src/terminal/adapter/ut_adapter/adapterTest.cpp, src/terminal/parser/InputStateMachineEngine.cpp, src/terminal/parser/InputStateMachineEngine.hpp, src/terminal/parser/ut_parser/InputEngineTest.cpp
This commit enables passthrough mode for VT Input Mode in ConPty. This
will be used to pass VT Input from Mouse Mode directly to the app on the
other side.
#545 - VT Mouse Mode (Terminal)
#376 - VT Mouse Mode (ConPty)
- Set the callback for the InputEngine.
- Retrieve `IsInVirtualTerminalInputMode` from the InputBuffer
Retrieve `VTInputMode` setting from ConHost
- Add a callback to passthrough unknown input sequences directly to the
input queue.
- If we're in VTInputMode, use the callback
Tests should still pass.
=> Enable Passthrough for VT Input Mode in ConPty

src/cascadia/TerminalApp/AppLogic.cpp, src/cascadia/TerminalApp/AppLogic.h, src/cascadia/TerminalApp/AppLogic.idl, src/cascadia/TerminalApp/TerminalPage.cpp
There's a platform limitation that causes us to crash when we rearrange
tabs. Xaml tries to send a drag visual (to wit: a screenshot) to the
drag hosting process, but that process is running at a different IL than
us.
For now, we're disabling elevated drag.
Fixes #3581
=> Prevent tab reordering while elevated

doc/user-docs/index.md, src/cascadia/TerminalControl/TermControl.cpp
If UseAcrylic is disabled, CTRL+SHIFT+SCROLL would enable it, without having to change the setting in profile.json manually.
#661
If UseAcrylic is disabled, CTRL+SHIFT+Scroll would enable it and acrylic background brush is initialized.
1. Set "useAcrylic" to false for the any profile in profile.json
2. Open terminal window for that profile.
3. CTRL+SHIFT+MouseScroll
Acrylic background opacity should change according to mouse scroll
=> Make ctrl+shift+scroll toggle acrylic on/off at extrema

doc/user-docs/UsingCommandlineArguments.md
=> doc: remove unimplemented `-t` arg from `split-pane`

src/host/ut_host/VtRendererTests.cpp, src/renderer/vt/VtSequences.cpp, src/renderer/vt/state.cpp, src/renderer/vt/vtrenderer.hpp
Allows VT engine methods that print formatted strings (cursor movements, color changes, etc.) to provide a guess at the max buffer size required eliminating the double-call for formatting in the common case.
- The most common case for VT rendering is formatting a few numbers into a sequence. For the most part, we can already tell the maximum length that the string could be based on the number of substitutions and the size of the parameters.
- The existing formatting method would always double-call. It would first call for how long the string was going to be post-formatting, allocate that memory, then call again and fill it up. This cost two full times of running through the string to find a length we probably already knew for the most part.
- Now if a size is provided, we allocate that …
=> Use estimated formatted lengths to optimize performance of VT rendering

src/terminal/parser/stateMachine.cpp, src/terminal/parser/stateMachine.hpp, src/terminal/parser/ut_parser/StateMachineTest.cpp
When we had to flush unknown sequences to the terminal, we were only
taking the _most recent run_ with us; therefore, if we received `\e[?12`
and `34h` in separate packets we would _only_ send out `34h`.
This change fixes that issue by ensuring that we cache partial bits of
sequences we haven't yet completed, just in case we need to flush them.
Fixes #3080.
Fixes #3081.
Ran new tests!
=> vt: make sure to Flush the entire parsed sequence

src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp, src/renderer/vt/WinTelnetEngine.cpp, src/renderer/vt/XtermEngine.cpp, src/terminal/adapter/adaptDispatch.cpp
When ConPTY encounters a string we don't understand, immediately flush the frame.
This PR supersedes #2665. This solution is much simpler than what was proposed in that PR. 
As mentioned in #2665: "This might have some long-term consequences for #1173."
=> When Conpty encounters an unknown string, flush immediately

src/inc/til.h, src/inc/til/point.h, src/til/ut_til/PointTests.cpp, src/til/ut_til/til.unit.tests.vcxproj, src/til/ut_til/til.unit.tests.vcxproj.filters, tools/ConsoleTypes.natvis
Introduces convenience type `til::point` which automatically implements our best practices for point-related types and provides automatic conversions in/out of the relevant types.
- Automatically converts in from anything with a X/Y (console `COORD`) or x/y (Win32 `POINT`)
- Automatically converts out to `COORD`, `POINT`, or `D2D1_POINT_2F`.
- Constructs from bare integers written into source file
- Default constructs to empty
- Uses Chromium Math for all basic math operations (+, -, *, /)
- Provides equality tests
- Accessors for x/y
- Type converting accessors (that use safe conversions and throw) for x/y
- TAEF/WEX Output and Comparators so they will print very nicely with `VERIFY` and `Log` macros in our testing suite.
- A natvis
- See automated tests of functionality.
=> til::point

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalCore/ITerminalApi.hpp, src/cascadia/TerminalCore/ITerminalInput.hpp, src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalCore/TerminalApi.cpp, src/cascadia/TerminalCore/TerminalDispatch.cpp, src/cascadia/TerminalCore/TerminalDispatch.hpp, src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp, src/terminal/input/mouseInput.cpp, src/terminal/input/terminalInput.hpp
Make TerminalControl synthesize mouse events and Terminal send them to
the TerminalInput's MouseInput module.
The implementation here takes significant inspiration from how we handle
KeyEvents.
Closes #545 - VT Mouse Mode (Terminal)
References #376 - VT Mouse Mode (ConPty)
- `_TrySendMouseEvent` attempts to send a mouse event via TermInput.
Similar to `_TrySendKeyEvent`
- Use the above function to try and send the mouse event _before_
deciding to modify the selection
- Hookup (re)setting the various modes to handle VT Input
- Terminal is _always_ in VT Input mode (important for #4856)
- Hookup (re)setting the various modes to handle VT Input
- Convert the mouse input position from viewport position to buffer
position
- Then send it over to the MouseInput in TerminalInput to actually do it …
=> Synthesize VT mouse events and add mouse support to Terminal

src/buffer/out/TextAttribute.cpp, src/buffer/out/TextAttribute.hpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalCore/terminalrenderdata.cpp, src/host/renderData.cpp, src/host/renderData.hpp, src/renderer/base/renderer.cpp, src/renderer/inc/IRenderData.hpp
cmatrix is somewhat of a pathological case for our infrastructure: it
prints out a bunch of green and white characters and then updates them a
million times a second.
It also maintains a column of space between every green character. When
it prints this column, it prints it in "default" or "white". This ends
up making runs of text that look like this:
`(def: G=green B=bright white W=white *=matrix char  =space)`
```
G W G W G W G W G W G W G W G W
G W G W G W G W G W G W G W G W
G W G W G W G W G W G W G W G W
G W G W G W G W G W G W G W G W
G W G W G W G W G W G W G W G W
G W G W G W G W G W G W G W G W
G W G W G W G W G W G W G W G W
G W G W G W G W G W G W G W G W
```
As characters trickle in:
```
G*W G*W G*W G*W G*W G*W G*W B*W
G*W G*W G*W G*W G*W G*W G*W G W
G*W G*W G*W B*W G*W G*W …
```
=> Optimize rendering runs of spaces when there is no visual change

src/renderer/base/renderer.cpp
This changes the renederer to make sure to not draw the cursor when it is placed outside the viewport. When the window height isn't an exact multiple of a row's height, then there's a little bit of space below the last line we're actually drawing. If cursor is on the line below the viewport, then it can actually get drawn into this space. Since we're not drawing the text for that line, this is a little odd. 
This PR fixes the issue by simply ensuring the cursor is in the veiwport before we draw it. 
Checked with the GDI renderer as well as the DX renderer in conhost to make sure this is fixed for both of them, as well as the Terminal
=> Don't draw the cursor if it's outside the viewport

src/cascadia/PublicTerminalCore/HwndTerminal.cpp, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalCore/ITerminalApi.hpp, src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalCore/TerminalApi.cpp, src/cascadia/TerminalCore/TerminalDispatch.cpp, src/cascadia/TerminalCore/TerminalDispatch.hpp, src/cascadia/UnitTests_TerminalCore/TerminalApiTest.cpp
Adds support for setting the cursor visibility in Terminal. Visibility
is a property entirely independent from whether the cursor is "on" or
not. The cursor blinker _should_ change the "IsOn" property. It was
actually changing the "Visible" property, which was incorrect. This PR
additionally corrects the naming of the method used by the cursor
blinker, and makes it do the right thing.
I added a pair of tests, one taken straight from conhost. In
copy-pasting that test, I took it a step further and implemented
`^[[?12h`, `^[[?12l`, which enables/disables cursor blinking, for the
`TerminalCore`. THIS DOES NOT ADD SUPPORT FOR DISABLING BLINKING IN THE
APP. Conpty doesn't emit the blinking on/off sequences quite yet, but
when it _does_, the Terminal will be ready.
* I'd bet this conflicts with …
=> Add support for setting the cursor visibility in Terminal

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
When the auto-hide taskbar setting is enabled, then we don't
always get another window message to trigger us to remove the drag bar.
So, make sure to update the size of the drag region here, so that it
_definitely_ goes away.
Manually tested it
=> Always remove the drag bar when entering fullscreen

src/host/outputStream.cpp, src/host/outputStream.hpp, src/terminal/adapter/adaptDispatch.cpp, src/terminal/adapter/conGetSet.hpp, src/terminal/adapter/ut_adapter/adapterTest.cpp
This is a hack to fix #4911. I cannot stress enough that I haven't tested this, but it's 5pm on a Friday here in Wisconsin, and I'm hoping that the rest of the team will validate this 😝
=> Only passthrough input changes if the client's in VT input mode

src/inc/til.h, src/inc/til/point.h, src/inc/til/rectangle.h, src/inc/til/size.h, src/inc/til/some.h, src/til/ut_til/RectangleTests.cpp, src/til/ut_til/SomeTests.cpp, src/til/ut_til/til.unit.tests.vcxproj, src/til/ut_til/til.unit.tests.vcxproj.filters, tools/ConsoleTypes.natvis
Introduces convenience type `til::rectangle` which automatically implements our best practices for rectangle-related types and provides automatic conversions in/out of the relevant types.
- Automatically converts in from anything with a Left/Top/Right/Bottom or left/top/right/bottom (Win32 `RECT`)
- Automatically converts Console type `SMALL_RECT` and shifts it from **inclusive** to **exclusive** on instantiation
- Automatically converts out to `SMALL_RECT` (converting back to **inclusive**), `RECT`, or `D2D1_RECT_F`.
- Constructs from bare integers written into source file
- Constructs from a single `til::point` as a 1x1 size rectangle with top-left corner (origin) at that point
- Constructs from a single `til::size` as a WxH size rectangle with top-left corner (origin) at 0,0
- …
=> til::rectangle

src/buffer/out/textBuffer.cpp, src/buffer/out/textBuffer.hpp, src/cascadia/TerminalCore/Terminal.cpp, src/host/screenInfo.cpp
Currently, when the user resizes the Terminal, we'll snap the visible viewport back to the bottom of the buffer. This PR changes the visible viewport of the Terminal to instead remain in the same relative location it was before the resize.  
Made possible by our sponsors at #4741, and listeners like you. 
We already hated the `std::optional<short>&` thing I yeet'd into #4741 right at the end to replace a `short*`. So I was already going to change that to a `std::optional<std::reference_wrapper<short>>`, which is more idomatic. But then I was looking through the list of bugs and #3494 caught my eye. I realized it would be trivial to not only track the top of the `mutableViewport` during a resize, but we could use the same code path to track the …
=> Maintain scrollbar position during a resize operation

src/cascadia/TerminalCore/TerminalDispatch.cpp, src/cascadia/TerminalCore/TerminalDispatch.hpp, src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp, src/terminal/adapter/adaptDispatch.cpp, src/terminal/parser/OutputStateMachineEngine.cpp
This _actually_ implements `\033c`
([RIS](https://vt100.net/docs/vt220-rm/chapter4.html)) for the Windows Terminal.
I thought I had done this in #4433, but that PR actually only passthrough'd
`\x1b[3J`. I didn't realize at the time that #2715 was mostly about hard reset,
not erase scrollback.
Not only should conpty pass through RIS, but the Terminal should also be
prepared to actually handle that sequence. So this PR adds that support as well.
* #4433: original PR I thought fixed this.
Actually tested `printf \033c` in the Terminal this time
=> Implement Hard Reset for Terminal

src/renderer/dx/DxRenderer.cpp
Always use the system's locale to render text to ensure the correct font variants are used.
`_ResolveFontFaceWithFallback()` overrides the last argument with the locale name of the font, but users normally configure fonts with latin alphabet only and use font linking to display non-latin characters, which causes the the locale names of the latin fonts are used to render the non-latin fonts. https://github.com/microsoft/terminal/issues/4508#issuecomment-598552472
On a zh-hans system, simplified Chinese hans are used after this patch (above), versus Japanese hans before (below).
=> Always use the system's locale to render text

doc/cascadia/SettingsSchema.md
Minor thing I noticed as I was reading the docs. Bothered me so I fixed it.
=> Make commands in doc appear as code

src/terminal/parser/stateMachine.cpp, src/terminal/parser/ut_parser/InputEngineTest.cpp
This PR ensures that Conpty properly treats `^[^Z` and `^[^X` as
<kbd>Ctrl+Alt+z</kbd> and <kbd>Ctrl+Alt+x</kbd>, instead of <kbd>Ctrl+z</kbd>
and <kbd>Ctrl+x</kbd>.
`^Z` and `^X` are special control characters, SUB and CAN. For the output state
machine, these characters are supposed to be executed from _any_ state. However,
we shouldn't do this for the input engine. With the current behavior, these
characters are immediately executed regardless of what state we're in. That
means we end up synthesizing <kbd>Ctrl+z/x</kbd> for these characters. However,
for the InputStateMachine engine, when these characters are preceeded by `^[`
(ESC), we want to treat them as <kbd>Ctrl+Alt+z/x</kbd>.
This just adds a check in `StateMachine` to see if we should …
=> Fix C-M-z, C-M-x in Conpty

src/cascadia/TerminalApp/WslDistroGenerator.cpp
When WSL.exe would hang for users, WslDistroGenerator would also hang
while waiting for its `wsl.exe --list` call to return. The timeout was
`INFINITE` in the `WaitForSingleObject` call, but we should slap a
timeout on it instead (here we choose 2 seconds). In addition, if it
times out, we should also just return profiles and let the Terminal
continue to start up without the WSL distro profiles loaded.
Made a sleep 30 executable as the command instead, made sure it hit the
`WAIT_TIMEOUT` and continued to start up without loading my Ubuntu
profile.
Closes #3987
=> Force WslDistroGenerator to timeout after 10s and return Profiles

src/terminal/adapter/ITermDispatch.hpp, src/terminal/adapter/adaptDispatch.hpp, src/terminal/adapter/termDispatch.hpp
Most of the methods in the `ITermDispatch` interface have a comment following them that indicates the VT function that they implement. These comments are then used by the script in PR #1884 to generate a table of supported VT functions. This PR updates some of those comments, to more accurately reflect the functions that are actually supported.
PR #1884 
In some cases there are methods that implement multiple VT functions which are essentially aliases. Originally the comments listed only one of the functions, so I've now updated them to list both. This includes `HPA` as an alias of `CHA`, and `HVP` as an alias of `CUP`.
Similarly, some control characters are implemented in terms of another VT function, but only the main function was listed in the comment. Again I've now updated the …
=> Update comments to better indicate the supported VT functions

src/cascadia/TerminalApp/Pane.cpp
Dustin and Mike had a discussion on star sizing. Mcpiroman connected the dots. I just swooped in and implemented it.
https://github.com/microsoft/terminal/issues/3996#issuecomment-566676111
https://github.com/microsoft/terminal/issues/3744#issuecomment-568926636
Star sizing allows us to keep things proportional. Since a 1::1 proportion is the same as a 100::100 proportion, I just went in and added star sizing. In the words of a some dude with a big metal fist, everything is perfectly balanced now.
Verified for vertical, horizontal, and uneven splits.
=> Make panes use XAML star sizing

src/types/IInputEvent.cpp
In IInputEvent, there are two for loops. One is a range based loop operating on "records", and the other is a classic for-loop doing the same. For consistency, the for-loop was changed into the more modern variation via a compiler refactoring, which has the exact same behavior as the other for-loop in the main function.
Yes, of course this was tested manually and with the unit tests.
Unit testing passed. In addition, for the manual validation tests, I compared the output for sample values between the two loops ensuring the same results.
=> Make loop in IInputEvent more consistent and modern

src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp
We (the royal "we") broke key unbinding in #4746. We didn't run the local tests after this, which actually would have caught this. The comment even suggests what we should have done here. We need to make sure that when we bail, it's because there's a parsing function that returned nothing. `null`, `"unbound"`, etc actually don't even have a parsing function at all, so they should just keep on keepin' on.
Source of this regression: #4746
This is a great example of why your unittests should run in CI always
* **ran the tests**
* tested the following unbindings:
```json
{ "command": null, "keys": [ "ctrl+shift+t" ] },
{ "command": "unbound", "keys": [ "ctrl+shift+t" ] },
{ "command": "null", "keys": [ "ctrl+shift+t" ] },
```
and they each …
=> Fix unbinding keys in v0.10

src/cascadia/TerminalControl/TermControl.cpp
Alt-Numpad# input would be escaping each numkey before sending it through. This would result in some weird behavior, for example, in powershell, where the first alt-numpad# would start digit argument and once the user releases alt, a character is sent through and digit argument would repeat that character X times. To resolve this, we simply need to ignore KeyDowns where Alt is held and a Numpad# is pressed. 
Once Alt is released, we'll receive a character through `TSFInputControl`, not `TermControl::CharacterHandler`. It seems that the `CoreTextEditContext` in `TSFInputControl` intercepts the character before it gets to `TermControl`. TSF will then send the received character through as normal.
Testing various combinations of Alt-Numpad# consistently sends through only one instance of the …
=> Ignore KeyDown events during Alt-Numpad Input

src/cascadia/TerminalControl/TermControlAutomationPeer.cpp, src/renderer/uia/UiaRenderer.cpp, src/renderer/uia/UiaRenderer.hpp, src/types/UiaTracing.cpp, src/types/UiaTracing.h
This notifies automation clients (i.e.: NVDA, narrator, etc...) of new output being rendered to the screen.
Close #2447 - Signaling for new output and cursor
Close #3791 - fixed by signaling cursor changes
- Added tracing for UiaRenderer. This makes it easier to debug issues with notifying an automation client.
- Fire TextChanged automation events when new content is output to the screen.
Verified with NVDA [1]
Narrator works _better_, but is unable to detect new output consistently. There is no harm for narrator when this change goes in.
[1] https://github.com/microsoft/terminal/issues/2447#issuecomment-595879890
=> Fire UIA Events for Output and Cursor Movement

src/host/ut_host/ConptyOutputTests.cpp, src/renderer/vt/paint.cpp
When we painted spaces up until the character right before the right
edge of the screen, we would erroneously use Erase in Line instead of
Erase Character due to an off-by-one.
This commit also fixes how we'd crash during a verify failure on the
render thread.
Fixes #4727.
Unit tests and manual verification.
=> Fix an off-by-one that made us use EL instead of ECH

src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalCore/TerminalSelection.cpp, src/host/renderData.cpp, src/host/renderData.hpp, src/interactivity/win32/screenInfoUiaProvider.cpp, src/interactivity/win32/uiaTextRange.cpp, src/interactivity/win32/uiaTextRange.hpp, src/types/IUiaData.h, src/types/TermControlUiaProvider.cpp, src/types/TermControlUiaTextRange.cpp, src/types/TermControlUiaTextRange.hpp, src/types/UiaTextRangeBase.cpp, src/types/UiaTextRangeBase.hpp
Block selections were always read and displayed as line selections in UIA. This fixes that.
1. Expose `IsBlockSelection()` via IUiaData
2. Update the constructor to be able to take in a block selection parameter
3. Make ScreenInfoUiaProviders pass step 1 output into step 2 constructor
4. Update all instances of `UiaTextRange::GetTextRects()` to include this new flag
Manually tested.
Additional tests would be redundant as GetTextRects() is tested in the text buffer.
=> Properly represent block selections in UIA

src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/UnitTests_TerminalCore/ScreenSizeLimitsTest.cpp
This is 100% on me. Even after mucking around in this function for the last 3
months, I missed that there was a single addition where we weren't doing a
clamped addition. This would lead to us creating a buffer with negative height,
and all sorts of badness.
Clamping this addition was enough to fix the bug.
* ran tests
* Created a profile with `"historySize" : 32728`, then filled the viewport with
text, then maximized, and saw that the viewport indeed did resize to the new
size of the window.
=> Clamp the terminal buffer to `SHRT_MAX` on resize

src/renderer/dx/DxRenderer.cpp, src/terminal/adapter/ut_adapter/inputTest.cpp, src/terminal/input/terminalInput.cpp
Ctrl+/ and Ctrl-? are complicated in VT input.
* C-/ is supposed to be `^_` (the C0 character US)
* C-? is supposed to be `DEL`
* C-M-/ is supposed to be `^[^_` (ESC US)
* C-M-? is supposed to be `^[^?` (ESC DEL)
The astute reader will note that these characters also share the same key on a
standard en-us keyboard layout, which makes the problem even more complicated.
This PR does a better job of handling these weird cases.
* #3079 - At first, I thought this PR would close this issue, but as I've learned below, this won't solve that one. This bug was merely found during that investigation.
* ran tests
* checked `showkey -a` in gnome-terminal, which gives you the wrong results for C-M-/, C-M-?
* checked `showkey -a` in xterm, which gives you the …
=> Fix VT sequences for Ctrl+Alt+? input

src/cascadia/CascadiaPackage/Package.appxmanifest
There's an issue in the UAC consent dialog where it cannot read an
application's name if it's stored in a resource. When it fails, it deems
us an "Unknown Program" and that looks pretty silly.
Fixes #2289.
=> Pin the DisplayName to Windows Terminal to fix the UAC prompt

src/buffer/out/RowCellIterator.hpp, src/buffer/out/cursor.h, src/cascadia/inc/cppwinrt_utils.h, src/types/ScreenInfoUiaProviderBase.h, src/types/UiaTextRangeBase.hpp, src/types/WindowUiaProviderBase.hpp
For some functions, the overriding implementation is set to default, but
the deletion is not explicitly set at all. For those functions, I
changed default to delete.
- Manual Checking including testing the base and the subclasses.
- Compiler Refactorings
- Unit tests passed.
=> hygiene: change default specifiers of some functions to delete

src/inc/til/point.h, src/inc/til/rectangle.h, src/inc/til/size.h, src/til/ut_til/PointTests.cpp, src/til/ut_til/SizeTests.cpp
Found a bug where the following won't work:
```c++
COORD inclusiveEnd{ _end };
```
where `_end` is a `til::point`.
The only fix for this is to replace these instances with this:
```c++
COORD inclusiveEnd = _end;
```
What was happening in the first notation is the implicit conversion of `til::point` to `bool` to `SHORT`. The constructor for COORD only sees one SHORT so it thinks the value should be the definition for X, and Y should stay as 0. So we end up getting `1, 0`.
By adding the explicit keyword to the bool operators, we prevent the accident above from occurring.
=> Add explicit to bool operators of Point and Rect

src/cascadia/TerminalControl/TSFInputControl.cpp, src/cascadia/TerminalControl/TSFInputControl.xaml
This PR turns on TextWrapping on `TSFInputControl::TextBlock`. Once the TextBlock hits the end of the Terminal window, it will wrap downwards, but the TextBlock will have as much width as it had when composition started. Unfortunately, this means if composition starts right at the end of the Terminal with enough width for just one character, there will be a vertical line of characters down the right side of the Terminal 😅. It's definitely not ideal, and I imagine this won't be the last time we visit this issue, but for now users can see what they're typing.
Played around with IME towards the edge of the Terminal window.
=> Allow IME Text Wrapping

src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj, src/cascadia/TerminalControl/TerminalControl.vcxproj
These projects load Xaml components that have Uids, but those Uids just
weren't working because Xaml components are, by default, loaded in
"Application" scope. Application scope is great if the resource producer
is the EXE project.
Application scope means that resources are looked up at the resource
root, but DLLs with resources don't produce resources at the root. They
produce resources at a root named after the DLL.
Setting the Xaml component resource location to Nested makes sure the
Xaml resource loader loads resources from the right places.
=> Set the ComponentResourceLocation for our DLL projects

src/terminal/adapter/ut_adapter/MouseInputTest.cpp, src/terminal/input/mouseInput.cpp
If the _Alternate Scroll Mode_ is enabled, the terminal generates up/down keystrokes when the mouse wheel is scrolled. However, the expected escape sequences for those keys are dependent on the state of the _Cursor Keys Mode_ ( `DECCKM`), but we haven't taken that into account. This PR updates the alternate scroll implementation to make sure the appropriate sequences are sent for both `DECCKM` modes.
#3321
I've simply added a condition in the `TerminalInput::_SendAlternateScroll` method to send a different pair of sequences dependent on the state of `_cursorApplicationMode`  flag.
Manually tested in VIM (although that required me enabling the _Alternate Scroll Mode_ myself first). Also added a new unit test in `MouseInputTest` to confirm the correct sequences were generated for both …
=> Fix the Alternate Scroll Mode when DECCKM enabled

src/host/ut_host/CommandListPopupTests.cpp, src/host/ut_host/CopyToCharPopupTests.cpp
When I did my last PR that was merged, the PR #4960, there were two more cases I forgot to include, so I included them here, for the sake of consistency and completion
PR #4690
Replacing pointer casts to 0 with nullptr in two tests.
Manual Testing
Automated Testing
=> Replace casting 0 to a pointer with nullptr.

src/cascadia/TerminalControl/TermControl.cpp
=> Make sure to account for the size the padding _will be_ scaled to

src/buffer/out/textBuffer.cpp, src/buffer/out/textBuffer.hpp, src/host/ut_host/TextBufferTests.cpp, src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp, src/types/ScreenInfoUiaProviderBase.cpp, src/types/UiaTextRangeBase.cpp, src/types/UiaTextRangeBase.hpp, src/types/UiaTracing.cpp
- Added better wide glyph support for UIA. We used to move one _cell_ at a time, so wide glyphs would be read twice.
- Converted a few things to use til::point since I'm already here.
- fixed telemetry for UIA
The text buffer has a concept of word boundaries, so it makes sense to have a concept of glyph boundaries too.
_start and _end in UiaTextRange are now til::point
Verified using Narrator
=> Improve wide glyph support in UIA

src/terminal/parser/InputStateMachineEngine.cpp, src/terminal/parser/InputStateMachineEngine.hpp, src/terminal/parser/ut_parser/InputEngineTest.cpp
ConPty did not set the ENHANCED_KEY flag when generating new input. This change helps detect when it's supposed to do so, and sends it.
[Enhanced Key Documentation](https://docs.microsoft.com/en-us/windows/console/key-event-record-str)
| KEY_EVENT_RECORD modifiers | VT encodable? | Detectable on the way out? |
|----------------------------|---------------|----------------------------|
| CAPSLOCK_ON                | No            | No                         |
| ENHANCED_KEY               | No            | Yes**                      |
| LEFT_ALT_PRESSED           | Yes*          | Yes*                       |
| LEFT_CTRL_PRESSED          | Yes*          | Yes*                       |
| NUMLOCK_ON                 | No            | No                         |
| RIGHT_ALT_PRESSED          | …
=> Add enhanced key support for ConPty

doc/user-docs/ThirdPartyToolProfiles.md
I think not much detail needed since this only an update to a doc and not the main application.
I tried it locally and worked without any adjustments to the cmder folder. Just making sure (as already stated) the `%CMDER_ROOT%` is set correctly.
=> doc: add cmder icon to ThirdPartyToolProfiles

doc/cascadia/profiles.schema.json
The pattern regex in [profiles.schema.json](https://raw.githubusercontent.com/davidwin/terminal/keychords_schema/doc/cascadia/profiles.schema.json) now correctly disallows keybindings consisting of only modifiers, modifiers not separated by `+`, and unknown key names. Certain `shift+numpad` combinations are also not allowed.
The description lists allowed key names in tabular format (assuming the client renders `\t` correctly):
The problem with the current keybinding schema is primarily that it accepts invalid key combinations.
Also, there is no accessible documentation of valid keys and modifiers. Now the regular expression 
should be much closer to what the parser in [KeyChordSerialization.cpp](https://github.com/microsoft/terminal/blob/master/src/cascadia/TerminalApp/KeyChordSerializatio …
=> Improve keybinding JSON schema

src/cascadia/TerminalControl/TSFInputControl.cpp
This PR fixes an out of bounds access when deleting composition during Chinese IME. What's happening is that we're receiving a CompositionCompleted before receiving the TextUpdate to tell us to delete the last character in the composition. This creates two problems for us:
1. The final character gets sent to the Terminal when it should have been deleted.
2. `_activeTextStart` gets set to `_inputBuffer.length()` when sending the character to the terminal, so when the `TextUpdate` comes right after the `CompositionCompleted` event, `_activeTextStart` is out of sync.
This PR fixes the second issue, by updating `_activeTextStart` during a `TextUpdate` in case we run into this issue. 
The first issue is trickier to resolve since we assume that if the text server api tells us a composition is …
=> Fix broken Chinese IME when deleting composition

NOTICE.md, dep/dynamic_bitset/LICENSE, dep/dynamic_bitset/MAINTAINER_README.md, dep/dynamic_bitset/cgmanifest.json, dep/dynamic_bitset/dynamic_bitset.hpp, dep/libpopcnt/LICENSE, dep/libpopcnt/MAINTAINER_README.md, dep/libpopcnt/cgmanifest.json, dep/libpopcnt/libpopcnt.h, src/cascadia/WindowsTerminalUniversal/WindowsTerminalUniversal.vcxproj, src/common.build.pre.props, src/inc/LibraryIncludes.h, src/inc/til/bitmap.h, src/til/ut_til/BitmapTests.cpp
This commit replaces `std::vector<bool>` with `dynamic_bitset<>` by
@pinam45 (https://github.com/pinam45/dynamic_bitset) and with
`libpopcnt` for high-performance bit counting by @kimwalisch
(https://github.com/kimwalisch/libpopcnt).
"not speed enough" as well as my sanity relative to
`std::vector<bool>`
cleared the licensing checks before pulling this in.
incapable of a great many things. Many of the methods you come to expect
off of `std::vector<T>` that are dutifully presented through the `bool`
variant will spontaneously fail at some future date because it decides
you allocated, resized, or manipulated the `vector<bool>` specialization
in an unsupported manner. Half of the methods will straight up not work
for filling/resizing in bulk. And you will tear your hair out as it will …
=> Update til::bitmap to use dynamic_bitset<> + libpopcnt

src/common.build.pre.props
This commit may help with the compiler and linker running out of memory.
=> Switch to the x64 hosted tools when building on x64

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalCore/TerminalSelection.cpp, src/cascadia/TerminalSettings/IControlSettings.idl, src/cascadia/TerminalSettings/ICoreSettings.idl, src/cascadia/UnitTests_TerminalCore/SelectionTest.cpp
This commit rewrites selection handling at the TermControl layer.
Previously, we were keeping track of a number of redundant variables
that were easy to get out of sync.
The new selection model is as follows:
* A single left click will always begin a _pending_ selection operation
* A single left click will always clear a selection (#4477)
* A double left click will always begin a word selection
* A triple left click will always begin a line selection
* A selection will only truly start when the cursor moves a quarter of
the smallest dimension of a cell (usually its width) in any direction
_This eliminates the selection of a single cell on one click._
(#4282, #5082)
* We now keep track of whether the selection has been "copied", or
"updated" since it was last copied. If an endpoint moves, …
=> Rework and simplify selection in TermControl

.github/actions/spell-check/dictionary/math.txt, .github/actions/spell-check/dictionary/microsoft.txt, .github/actions/spell-check/dictionary/names.txt, .github/actions/spell-check/whitelist/whitelist.txt
This is just some minor whitelisting/additions to dictionaries to catch up between when the spell checker PR was written and when it was finally merged.
This is basically taking the output from https://github.com/microsoft/terminal/commit/499f24a29e6f321d6c4da8eb22c2ef0d30f13770#commitcomment-38053489 and putting it into files.
The choice of files is arbitrary. I'm adding a `math.txt` dictionary because it's a reasonable example.
The goal here is to get master to a green check mark
When I pushed this commit to my fork, the spell check action ran and gave me a check mark:
https://github.com/jsoref/terminal/runs/534783276
=> ci: update spelling allowlists/dictionaries

.github/workflows/spelling.yml
This repository tends to use `/`s in branch names.
Unfortunately, `branch: "*"` at present only matches a single
level, which means it would match a branch named `foo` but not `bar/foo`.
Given that I don't think this repository is actively using tags,
and given that the general cost for the spell checker isn't particularly
high, it's better to remove the filtering so that all branches get
checked.
Worst case, a branch that is also tagged and has spelling errors
will get two comments complaining about those spelling errors.
Testing by @DHowett-MSFT 
* https://github.com/microsoft/terminal/commit/4357854560d5e5b2ef0a29fd893381918ee0a342 -- null commit on DTI no slash branch
* https://github.com/microsoft/terminal/commit/30556187aee9ef7289055d8d70f28393582b7b71 -- null commit on DTI with …
=> ci: spelling: remove branch / tag filtering

doc/user-docs/UsingJsonSettings.md
=> Add a note about binding multiple keys

src/cascadia/TerminalApp/Resources/en-US/Resources.resw, src/cascadia/TerminalApp/TerminalPage.cpp, src/cascadia/TerminalApp/TerminalPage.h, src/cascadia/TerminalApp/TerminalPage.idl, src/cascadia/TerminalApp/TerminalPage.xaml
This pull request replaces about a hundred lines of manual xaml DOM code with a few lines of actual xaml, and wires up bound properties and event handlers in the good and correct way.
As part of this change, I've replaced the giant TextBlock in the about dialog with StackPanels, and replaced the Hyperlinks with HyperlinkButtons. This is in line with other platform applications.
URLs are _not_ localizable resources, so I moved them into the about dialog's xaml. Per #5138, we'll likely change them so that they get localization for "free" (dispatching based on the browser's language, without having to localize the URL in the application).
=> Convert the About and Close All Tabs dialogs to xaml

.github/actions/spell-check/dictionary/math.txt, .github/actions/spell-check/whitelist/whitelist.txt, src/inc/til.h, src/inc/til/math.h, src/inc/til/point.h, src/inc/til/size.h, src/til/ut_til/MathTests.cpp, src/til/ut_til/PointTests.cpp, src/til/ut_til/SizeTests.cpp, src/til/ut_til/sources, src/til/ut_til/til.unit.tests.vcxproj
This pull request introduces the `til::math` namespace, which provides some casting functions to be used in support of `til::point` and `til::size`. When point/size want to ingest a floating-point structure, they _must_ be instructed on how to convert those floating-point values into integers.
This enables:
```
Windows::Foundation::Point wfPoint = /* ... */;
til::point tp{ til::math::rounding, wfPoint };
```
Future thoughts: should the TilMath types be stackable? Right now, you cannot get "checked + rounding" behavior (where it throws if it doesn't fit) so everything is saturating.
=> add til::math, use it for float conversions to point, size

doc/user-docs/ThirdPartyToolProfiles.md
Added Git Bash (WOW64) profile.
The `mingw32` part is a catch.
=> doc: add Git Bash(WOW64) to ThirdPartyToolProfiles

src/renderer/dx/CustomTextRenderer.cpp, src/renderer/dx/DxRenderer.cpp
There are two antialias modes that can be set on the ID2D1RenderTarget:
- one for text/glyph drawing [1]
- one for everything else [2]
We had to configure that in the RenderTarget.
Additionally, when clipping the background color rect, we need to make
sure that's aliased too. [3]
[1] ID2D1RenderTarget::SetTextAntialiasMode
https://docs.microsoft.com/en-us/windows/win32/api/d2d1/nf-d2d1-id2d1rendertarget-settextantialiasmode
[2] ID2D1RenderTarget::SetAntialiasMode
https://docs.microsoft.com/en-us/windows/win32/api/d2d1/nf-d2d1-id2d1rendertarget-setantialiasmode)
[3] ID2D1CommandSink::PushAxisAlignedClip
https://docs.microsoft.com/en-us/windows/win32/api/d2d1_1/nf-d2d1_1-id2d1commandsink-pushaxisalignedclip)
Open and interact with midnight commander with the display scaling set
to...
- 100% …
=> Set DxRenderer non-text alias mode

src/tools/echokey/main.cpp
This PR updates our internal tool `conechokey` to use `ReadConsoleInputW` by default. It also adds a flag `-a` to force it to use `ReadConsoleInputA`.
I discovered this while digging around for #1503, but figured I'd get this checked in now while I'm still investigating.
Since this is just a helper tool, I spent as little effort writing this change - yea the whole tool could benefit from cleaner code but _ain't nobody got time for that_.
=> Make `conechokey` use ReadConsoleInputW by default

doc/cascadia/SettingsSchema.md, doc/cascadia/profiles.schema.json, doc/user-docs/UsingJsonSettings.md, src/cascadia/LocalTests_TerminalApp/KeyBindingsTests.cpp, src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp, src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp, src/cascadia/TerminalApp/CascadiaSettings.cpp, src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp, src/cascadia/TerminalApp/ColorScheme.cpp, src/cascadia/TerminalApp/Profile.cpp, src/cascadia/TerminalApp/Profile.h, src/cascadia/TerminalApp/ShortcutActionDispatch.cpp, src/cascadia/TerminalApp/ShortcutActionDispatch.idl, src/cascadia/TerminalApp/TerminalPage.cpp, src/cascadia/TerminalApp/defaults.json
This pull request removes support for:
* legacy keybindings of all types
* `colorScheme.colors`, as an array
* A `globals` object in the root of the settings file
* `profile.colorTable` and `profile.colorscheme` (the rare v0.1 all-lowercase variety)
Fixes #4091.
Fixes #1069.
=> Remove a heap of legacy settings deserialization

src/terminal/parser/stateMachine.cpp, src/terminal/parser/stateMachine.hpp, src/terminal/parser/ut_parser/OutputEngineTest.cpp
This PR clamps the parameter values in the VT `StateMachine` parser to 32767, which was the initial limit prior to PR #3956. This fixes a number of overflow bugs (some of which could cause the app to crash), since much of the code is not prepared to handle values outside the range of a `short`.
#3956 - the PR where the cap was changed to the range of `size_t`
#4254 - one example of a crash caused by the higher range
The DEC STD 070 reference recommends supporting up to at least 16384 for parameter values, so 32767 should be more than enough for any standard VT sequence. It might be nice to increase the limit to 65535 at some point, since that is the cap used by both XTerm and VTE. However, that is not essential, since there are very few situations where you'd even notice the difference. …
=> Clamp VT parameter values to 32767

src/cascadia/TerminalControl/TermControl.cpp, src/renderer/uia/UiaRenderer.cpp, src/renderer/uia/UiaRenderer.hpp
Reduce the number of times we dispatch a cursor changed event. We were firing it every time the renderer had to do anything related to the cursor. Unfortunately, blinking the cursor triggered this behavior. Now we just check if the position has changed.
Verified using Narrator
Also verified #3791 still works right
=> Reduce CursorChanged Events for Accessibility

doc/user-docs/UsingJsonSettings.md
In the spec for this feature I was using `Microsoft.Terminal.*` for dynamic profile generators, but in the PR this changed to `Windows.Terminal.*`. Noticed this in the morning.
=> Fix a typo in this doc

.github/actions/spell-check/whitelist/whitelist.txt
_Technically_, "wether" is a word but I'd be shocked if there's a scenario for us to use it properly in this repo, so I'm pulling it from the dictionary.
Also, in #5200, we added "VTE", which is totally a valid acronym, to the codebase, but not the whitelist. I'm not sure why the bot let me merge it anyways, but I'm fixing it now.
=> Remove "wether" from dictionary, add "VTE"

.github/actions/spell-check/advice.txt, .github/workflows/spelling.yml, doc/specs/#607 - Commandline Arguments for the Windows Terminal.md
This updates the spell checker.
Scheduled checks should now function, this means that if someone has a fork and isn't allowing actions to run in their fork, this repository should be able to run a spell check against the PR similar to the way checks would be run otherwise.
This is designed to be merged after #5207
Note: due to a bug in a previous version, `i'th` was treated as an acceptable term. This update fixes that bug which makes the checking stricter. `nth` is in the dictionary, and thus I've used it instead.
You can see how advice works because I'm conveniently building on top of an unhappy commit. If @DHowett-MSFT / @miniksa / @zadjii-msft have input about how the advice should be worded, we can certainly adjust that here (or you're welcome to tune it later).
I pushed this commit …
=> ci: spelling: update and include advice

doc/cascadia/SettingsSchema.md, doc/cascadia/profiles.schema.json, src/cascadia/LocalTests_TerminalApp/KeyBindingsTests.cpp, src/cascadia/TerminalApp/ActionArgs.h, src/cascadia/TerminalApp/ActionArgs.idl, src/cascadia/TerminalApp/AppActionHandlers.cpp, src/cascadia/TerminalApp/TerminalPage.cpp, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalCore/TerminalSelection.cpp
`TrimWhitespace` is misleading. So it is now renamed as 'singleLine'. If true, it comes out as a single line! That makes more sense!
Attempted the keybinding with both settings (and none set).
Attempted mouse copy with and without shift.
=> Rename copy keybinding arg

src/cascadia/TerminalApp/AppLogic.cpp
Because we cannot set RequestedTheme at the application level, we
occasionally run into issues where parts of our UI end up themed
incorrectly.  Dialogs, for example, live under a different Xaml root
element than the rest of our application. This makes our popup menus and
buttons "disappear" when the user wants Terminal to be in a different
theme than the rest of the system.  This hack---and it _is_ a
hack--walks up a dialog's ancestry and forces the theme on each element
up to the root. We're relying a bit on Xaml's implementation details
here, but it does have the desired effect.
It's not enough to set the theme on the dialog alone.
Fixes #3654.
Fixes #5195.
=> Force all our dialogs into the application theme, forcibly

src/cascadia/TerminalControl/TermControlAutomationPeer.h, src/types/IUiaTraceable.h, src/types/ScreenInfoUiaProviderBase.cpp, src/types/ScreenInfoUiaProviderBase.h, src/types/UiaTextRangeBase.cpp, src/types/UiaTextRangeBase.hpp, src/types/UiaTracing.cpp, src/types/UiaTracing.h, src/types/lib/types.vcxproj, src/types/lib/types.vcxproj.filters
In preparation for getting more accessibility-related issues, I added an ID to the `ScreenInfoUiaProvider` (SIUP) and abstracted the one from `UiaTextRange`. Using this, I noticed that we are creating SIUPs when a new tab/pane is created. This is _good_. This means that we need to somehow notify a UIA Client that out structure has changed, and we need to use the new SIUP because the old one has been removed.
I'll be investigating that more after this PR lands.
=> Add more object ID tracing for Accessibility

doc/cascadia/profiles.schema.json
Minor cleanup on the schema. Globals isn't accepted anymore, so the schema should not help you autocomplete anymore.
Imported the new schema. You do _not_ get a warning when globals is in. But, the schema won't suggest things when inside globals. It's just treated as an unknown item.
However, "defaultProfile" is still required (more of a sanity test)
=> doc: remove "globals" from schema

src/host/screenInfo.cpp
A side effect of the `SetConsoleCursorInfo` API is that it resets the
cursor type to _Legacy_. This makes it impossible to change the cursor
visibility via the console APIs without also resetting the user's
preferred cursor type. This PR attempts to fix that limitation, by only
resetting the cursor type if the size has also been changed.
I suspect the reason for the original behaviour was because the
`SetConsoleCursorInfo` API sets both the visibility and the size, and if
you're setting the size, it's assumed you'd want the _Legacy_ cursor
type, because that's the only style for which the size is applicable.
So my solution was to only reset the cursor type if the requested cursor
size was actually different from the current size. That should be
reasonably backwards compatible with most …
=> Prevent the cursor type being reset when changing the visibility

src/host/ut_host/ScreenBufferTests.cpp, src/terminal/adapter/adaptDispatch.cpp
If we receive a _Reset to Initial State_ (`RIS`) sequence while in the alternate screen buffer, we should be switching back to the main buffer. This PR fixes that behavior.
I've added a condition at the start of the `AdaptDispatch::HardReset` method to check whether we're using the alt buffer, and if so, call the `ConGetSet::PrivateUseMainScreenBuffer` API to switch back to the main buffer.
Calling `AdaptDispatch::UseMainScreenBuffer` would probably be neater for this, but it would also attempt to restore the cursor state, which seems pointless when we're in the process of resetting everything anyway.
I've added a screen buffer test to confirm that the `RIS` sequence does actually switch back to the main buffer. I've also manually confirmed that the test case in issue #3685 does now …
=> Make RIS switch back to the main buffer

src/cascadia/TerminalControl/TermControl.cpp
The terminal lock is really only for the terminal; since the renderer is
fully owned by the control, not the Terminal, and we'll only be
receiving swap chain events after we register them during
initialization, we don't need to lock before _or_ after firing off the
coroutine.
Manual validation.
=> Relax locking around the swapchain

doc/cascadia/SettingsSchema.md, doc/cascadia/profiles.schema.json, src/cascadia/TerminalApp/AppLogic.cpp, src/cascadia/TerminalApp/GlobalAppSettings.cpp, src/cascadia/TerminalApp/GlobalAppSettings.h, src/cascadia/TerminalApp/defaults-universal.json, src/cascadia/TerminalApp/defaults.json
Renames the `requestedTheme` global setting to `theme`. Propagates updates to...
- schema
- doc
- defaults.json
- universal-defaults.json
| `theme` | Success? |
|--|--|
| `system` | ✔ |
| `light` | ✔ |
| `dark` | ✔ |
But we really know that `dark` is the one we care about here 😉
=> Rename 'requestedTheme' to 'theme'

.github/actions/spell-check/whitelist/whitelist.txt, .github/workflows/spelling.yml
https://github.com/check-spelling/check-spelling/releases/tag/0.0.14-alpha
* https://github.com/jsoref/terminal/commit/d9d2bdeacb46507979222c0866daf10b41610248
* https://github.com/jsoref/terminal/runs/567983452#step:4:32
* https://github.com/jsoref/terminal/commit/ab6520c2f1a9c41640c3b9098be7c35a50268407
Probably the main noticeable change is that for passing runs where whitelist entries are no longer necessary, you can now see that output in the logs, as seen here:
https://github.com/jsoref/terminal/runs/567983452#step:4:32
The output was always constructed (and is available to people who add `VERBOSE: 1` their branch's `.github/workflows/spelling.yml` in the `env:` section), but I had decided not to spam commits w/ such comments (it seemed too distracting/frustrating).
⚠️  The tool's …
=> ci: spelling: update to 0.0.14a

src/cascadia/TerminalApp/CascadiaSettings.cpp, src/cascadia/TerminalApp/Resources/en-US/Resources.resw, src/cascadia/TerminalApp/defaults.json, src/cascadia/TerminalApp/userDefaults.json
This commit introduces another template replacement for the user's
default settings, COMMAND_PROMPT_LOCALIZED_NAME, which will be replaced
with the contents of the CommandPromptDisplayName resource.
By default, that will be "Command Prompt." This name change will apply
only for new users, and only on first launch. Changes in the system
locale after first launch will not impact the name of the profile.
If the user _removes_ the name from their command prompt profile, its
name will revert irrecoverably to "Command Prompt". They will not be
given a chance to regenerate a localized name.
Fixes #4476.
Possibly rejected proposal for dynamic localized json strings: #5280 
Deleted my profiles.
=> Localize the profile name for cmd, change it to Command Prompt

src/cascadia/TerminalControl/TermControl.cpp
When the connection printed text immediately, synchronously, as part of
Start() it would cause terminal to deadlock. We should start the
connection outside of lock.
The ConptyConnection would do this when it failed to launch something
(trivial repro: `wt -- xyz`).
The TelnetConnection would do this all the time, because local loopback
telnet is fast and easy.
Attempted to run the failing scenario.
=> Control: Start the connection outside of lock

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
This stops us from dispatching back-to-back terminal cursor position
updates to the TSF control before it has a chance to get back to us.
Fixes #5288 
This was tested live with the 6MB repro file from "Terminal Not Speed Enough".
=> Muffle updates to the cursor position to 1/~100ms

src/cascadia/TerminalControl/TermControl.cpp
This fixes a silly regression introduced by 1299a839b. We would crash
when the connection updated the cursor as it was being torn down.
It would have been good for me to test this better. Sorry.
=> Control: make sure we actually have a dispatcher in 100ms

src/terminal/adapter/DispatchTypes.hpp, src/terminal/adapter/ITermDispatch.hpp, src/terminal/adapter/adaptDispatch.cpp, src/terminal/adapter/adaptDispatch.hpp, src/terminal/adapter/termDispatch.hpp, src/terminal/adapter/ut_adapter/adapterTest.cpp, src/terminal/parser/OutputStateMachineEngine.cpp, src/terminal/parser/ut_parser/OutputEngineTest.cpp
This adds support for the VT escape sequence that requests the terminal's operating status. There is no attempt to actually verify the status of the app, though. We always return a response indicating a good operating condition (the same as most terminal emulators).
This required an update to the `OutputStateMachineEngine` to accept the `DSR-OS` type, since it only dispatches types that it recognises (I think that's unnecessary, but that's an issue for another day).
The actual processing of the request is handled in the `AdaptDispatch` class, where it simply responds with a hard coded sequence (`CSI 0 n`), indicating a good operating condition.
I've added unit tests to confirm that the request is dispatched correctly, and the appropriate response is returned. I've also manually confirmed …
=> Add support for the DSR-OS operating status report

.github/actions/spell-check/dictionary/apis.txt, src/cascadia/TerminalApp/AppLogic.cpp
This pull request makes sure we still get a usable (for troubleshooting purposes) version number in the about dialog and settings file when the user is running unpackaged.
I've had this laying around since I reworked the about dialog.
The code looks hairy, and we could pull it out into a helper. It's straightforward except for the magic LCID constant.
The story behind that constant: by default, Package ES emits version resource information that says we're localized to ... language zero.
It also emits a language-coded version block for 0x0409 (en-US).
These two things cannot both be true.
=> Fall back to TerminalApp.dll's version when we're unpackaged

.github/actions/spell-check/whitelist/whitelist.txt, doc/specs/drafts/#2046 - Command Palette.md
Hey, did you know that the `doc` folder spellchecked too? 
Sorry about breaking the build 🙄
=> doc: Fix the typos I introduced in #2193

.github/actions/spell-check/whitelist/whitelist.txt, src/til/ut_til/ColorTests.cpp
Spell check passed on my fork :-)
I saw this when I was looking at someone else's PR and realized that it's just a typo.
=> spelling: COLOREREF -> COLORREF

src/cascadia/TerminalControl/Resources/en-US/Resources.resw, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h, src/cascadia/TerminalControl/TermControl.xaml, src/renderer/base/renderer.cpp, src/renderer/base/renderer.hpp, src/renderer/base/thread.cpp, src/renderer/base/thread.hpp, src/renderer/inc/IRenderThread.hpp
Renderer: Add support for backoff and auto-disable on failed retry
This commit introduces a backoff (150ms * number of tries) to the
renderer's retry logic (introduced in #2830). It also changes the
FAIL_FAST to a less globally-harmful render thread disable, so that we
stop blowing up any application hosting a terminal when the graphics
driver goes away.
In addition, it adds a callback that a Renderer consumer can use to
determine when the renderer _has_ failed, and a public method to kick it
back into life.
Fixes #5340.
This PR also wires up TermControl so that it shows some UI when the renderer tastes clay.
I tested this by dropping the number of retries to 1 and forcing a TDR while doing `wsl cmatrix -u0`. It picked up exactly where it left off.
As a bonus, you can actually still type …
=> Add support for renderer backoff, don't FAIL_FAST on 3x failures, add UI

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
This fixes an issue where a shift+click selection with `copyOnSelect` enabled would result in copying the content as a single line.
I've been thinking a lot about this issue and how it relates to the copy/paste discussions we've been having over the past few weeks. Considering that the majority of users want regular copy, it makes sense to default to that in this case too.
If a user wants to perform a special form of copy, it makes sense that they should use their custom keybinding to accomplish that. This kind of behavior aligns with that kind of philosophy.
The following scenarios were tested with `copyOnSelect` enabled.
| scenario | behavior |
|--|--|
| Perform a shift+click selection | content copied w/ newlines |
| right-click | clipboard paste |
| copy keybinding (`singleLine` …
=> Remove singleLine copy from Shift+Click, CopyOnSelect 

src/host/screenInfo.cpp, src/host/ut_host/ScreenBufferTests.cpp
If an application writes to the screen while not in VT mode, and the user has scrolled forward in the screen buffer, the _virtual bottom_ location is not updated to take that new content into account. As a result, the viewport can later jump back to the previous _virtual bottom_, making the content disappear off screen. This PR attempts to fix that issue by updating the _virtual bottom_ location whenever the cursor moves below that point.
This simply adds a condition in the `SCREEN_INFORMATION::SetCursorPosition` to check if the new _Y_ coordinate is below the current _virtual bottom_, and if so, updates the _virtual bottom_ to that new value.
I considered trying to make it only update when something is actually written to the screen, but this seemed like a cleaner solution, and is less …
=> Update the virtual bottom location if the cursor moves below it

src/cascadia/TerminalApp/AppLogic.cpp, src/cascadia/TerminalApp/Resources/en-US/Resources.resw, src/cascadia/TerminalConnection/AzureConnection.cpp, src/cascadia/TerminalConnection/ConptyConnection.cpp, src/cascadia/TerminalConnection/Resources/en-US/Resources.resw, src/cascadia/TerminalControl/Resources/en-US/Resources.resw
Loc issues are given to us through the internal bug tracker.
* Lock some strings, or parts of strings, that should not be localized.
* Switch to positional format parameters
* Remove the forced newlines in the warning resources; insert them at
runtime
Fixes MSFT:25936156.
=> Fix localizability issues in Windows Terminal

src/cascadia/TerminalConnection/AzureClient.h, src/cascadia/TerminalConnection/AzureConnection.cpp, src/cascadia/TerminalConnection/AzureConnection.h, src/cascadia/TerminalConnection/Resources/en-US/Resources.resw
Instead of passing around four loose variables, create a Tenant class
and use that for packing/unpacking into/out of json (and the windows
credential store, where we "cleverly" used json for the tenant info
there too).
When displaying a tenant, use its display name if there is one, the
unknown resource string if there isn't, and the default domain if there
is one and the ID if there isn't.
Fixes #5325.
Switch to 2020 tenant API; use defaultDomain; put defaultDomain into the
display name.
Consider: not showing the tenant GUID at all?
* _RequestHelper no longer eats exceptions.
* Delete the "no internet" error message.
* Wrap exceptions coming out of Azure API in a well-known type.
* Catch by type.
* Extract error codes for known failures (keep polling, invalid grant).
* When we get an …
=> Rework error handling and state flow in the Azure connection

src/cascadia/WpfTerminalControl/TerminalContainer.cs
This pull request fixes a crash on scrolling down (overflow exception cramming the signed short upper WORD of the wParam into an actual signed short on x64) and a crash on key input caused by improper use of `Marshal.ReadByte` on an integer (instead of a memory address).
Manually did those things on x64.
=> wpf: fix two crashes and some fallout from the new key event handler

src/cascadia/PublicTerminalCore/HwndTerminal.cpp, src/cascadia/PublicTerminalCore/HwndTerminal.hpp, src/cascadia/TerminalCore/Terminal.cpp
This pull request ports #5096 to WpfTerminalControl, bringing it in line with the selection mechanics in Terminal. It also introduces double- and triple-click selection and makes sure we clear the selection when we resize.
Please read #5096 for more details.
This code is, largely, copy-and-pasted from TermControl with some updates to use `std::chrono` and `til::point`. I love `til::point`. A lot.
Lots of manual selection.
=> wpf: port selection changes from TermControl, add multi-click selection

src/cascadia/PublicTerminalCore/HwndTerminal.cpp, src/cascadia/PublicTerminalCore/HwndTerminal.hpp, src/cascadia/WpfTerminalControl/NativeMethods.cs, src/cascadia/WpfTerminalControl/TerminalContainer.cs
This pull request ports the VT mouse code from TermControl to WpfTerminalControl. Our WPF control is a lot closer to Win32 than to Xaml, so our mouse event handler looks _nothing_ like the one that we got from Xaml. We can pass events through almost directly, because the window message handling in the mouse input code actually came from _conhost_. It's awesome.
Neither TermControl nor conhost pass hover events through when the control isn't focused, so I wired up focus events to make sure we acted the same.
Just like Terminal and conhost, mouse events are suppressed when <kbd>Shift</kbd> is held.
Tested with MC, and tested by manually engaging SGR events in an Echo terminal.
=> wpf: add support for VT mouse mode

src/terminal/adapter/adaptDispatch.cpp, src/terminal/parser/InputStateMachineEngine.cpp, src/terminal/parser/InputStateMachineEngine.hpp, src/terminal/parser/ut_parser/InputEngineTest.cpp
Adds SS3 cursor encoding for cursor keys and home/end button. Reverts a portion of #4913 that checks for VT Input Mode.
1. Open pwsh
2. run `wsl`
3. execute `printf "\e[?1h"`
4. verify keys work
5. exit back to pwsh
6. verify keys work still (didn't previously)
Also verified that those keys work in vim when connected to my Raspberry Pi over SSH.
=> Add SS3 cursor key encoding to ConPty

src/types/UiaTextRangeBase.cpp
The scroll locking rework that landed with the DxRenderer's partial
invalidation change introduced a deadlock. UIA locks the buffer for
reading before asking it to scroll (which now requires a write lock.)
Scrolling is probably _okay_ to have a little bit of torn state that
might arise from us unlocking the read lock early before triggering the
write lock down the line.
While investigating this, I also noticed that our bounding rects stopped
being viewport-relative (and were instead buffer-relative.) That
regressed with the switch to `GetTextRects` in #4991  
Manual pass with inspect.exe
=> Fix a deadlock and a bounding rects issue in UIA

src/cascadia/PublicTerminalCore/HwndTerminal.cpp, src/cascadia/PublicTerminalCore/HwndTerminal.hpp, src/cascadia/WpfTerminalControl/TerminalContainer.cs
Selection would act up when you were using shift to ignore VT mouse
mode: we would get hundreds of WM_KEYDOWN for VK_SHIFT and dismiss the
selection every time.
I took the opportunity to move the actual responsibility for key event
dispatch into HwndTerminal. In the future, I'd like to make more of the
TerminalXxx calls just call impl methods on HwndTerminal.
Selection now works in VT mouse mode.
=> wpf: only dismiss selection for real chars, not modifiers

src/common.build.pre.props
Add a specific error message to the build that tells people to restore git submodules if they forgot to read the README.
#5416 was the straw that broke the camels back
=> Add a git submodules sanity check step to the build

src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp, src/renderer/vt/paint.cpp
The logic here, regarding deleting the spaces and just instantly adding
them bad, is incredibly suspect. Given that we're close to 0.11, I don't
think I can change it.
I've added a TODO with an issue number to figure out the right logic
here.
Fixes #5386.
Tests, manual validation of the scenario in 5386 and a repro program.
=> Don't duplicate spaces from potentially-wrapped EOL-deferred lines

src/types/UiaTextRangeBase.cpp
This is a quick-and-easy solution to #5309. If the ITextRangeProvider API allows us to take in two UiaTextRanges, we need to verify that they are both valid.
With this PR, we make sure they both fit in the current TextBuffer. If not, we return `E_FAIL`. Though this doesn't prove that both UiaTextRanges are from the same TextBuffer, at the very least we don't crash and in cases where we can't make a valid comparison, we return an HRESULT failure.
#5406 - This should be the proper solution to this problem. Each UiaTextRange needs to be aware of which TextBuffer it came from.
1. generate enough output to cause the terminal to scroll
2. execute `nano` to make us go into the alternate buffer
This previously crashed, now NVDA seems to detect that there was an error and keeps moving along.
=> UIA: Prevent crash from invalid UTR endpoint comparison

src/cascadia/TerminalApp/defaults.json
The "Campbell Powershell" color scheme does not have a high enough color contrast ratio. Campbell does, so we're changing it there.
=> Change Windows Powershell default scheme to Campbell

doc/user-docs/UsingCommandlineArguments.md
Yea, this doc should probably mention that `wt` will _always_ create a new window. Also links to #4472.
- it does
=> doc: add a note about running `wt` in the current instance

doc/user-docs/UsingCommandlineArguments.md
This PR adds some notes from #4570 to the [UsingCommandlineArguments.md](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md) doc. Hopefully, this should add clarity on how to use sub-commands in the `wt` commandline from within Powershell.
=> doc: Add note about using `;` as a separator in PowerShell

src/renderer/vt/VtSequences.cpp
`_Write` accepts `std::string_view`, so don't create `std::string` for const string.
=> Use string_view where possible

src/terminal/adapter/InteractDispatch.cpp, src/terminal/parser/ut_parser/InputEngineTest.cpp
Users were not able to intercept Ctrl-C input using `$Host.UI.RawUI.ReadKey("IncludeKeyUp")`, because we weren't sending a Ctrl-C KeyUp event. This PR simply adds a KeyUp event alongside the existing KeyDown.
The repro script in #1894 now works, both options for `ReadKey`: `IncludeKeyUp` and `IncludeKeyDown` work fine.
=> Send a Ctrl-C KeyUp event

src/common.build.pre.props
Fixes #5452.
This will make security go brrrrrrr
=> Enable Control Flow Guard in the common build props

src/cascadia/WindowsTerminal/main.cpp
If Terminal is spawned by a shortcut that requests that it run in a new process group
while attached to a console session, that request is nonsense. That request will, however,
cause WT to start with Ctrl-C disabled. This wouldn't matter, because it's a Windows-subsystem
application. Unfortunately, that state is heritable. In short, if you start WT using cmd in
a weird way, ^C stops working _inside_ the terminal. Mad.
Fixes #5460.
=> Re-enable Ctrl-C if the application that spawned us disabled it

src/cascadia/TerminalCore/terminalrenderdata.cpp
In order to support a transparent background for the acrylic effect, the renderer sets the alpha value to zero for the default background color. However, when the _reversed video_ attribute is set, the background is actually filled with the foreground color, and will not be displayed correctly if it is made transparent. This PR addresses that issue by making sure the rendered background color is opaque if the reversed video attribute is set.
* This is not a major issue at the moment, since the _reverse video_ attribute is not typically forwarded though conpty, but that will change once #2661 is fixed.
This simply adds an additional check in `Terminal::GetBackgroundColor` to make sure the returned color is opaque if the _reverse video_ attribute is set. At some point in the future this …
=> Make sure background color is opaque when attrs are reversed

doc/cascadia/SettingsSchema.md
This PR aligns documentation with actual implementation.
The modifiers, `ctrl+`, `shift+` and `alt+` were capitalized but *terminal* does **not** accept capitalized modifiers, e.g. `Ctrl+` is an **invalid** modifier.
=> Lower case modifiers in doc

doc/cascadia/profiles.schema.json
These were already in the `SettingsSchema.md`, so I just updated the `profiles.schema.json` to have the descriptions as well.
=> Add descriptions for `backgroundImageAlignment`, `backgroundImageOpacity`

doc/cascadia/SettingsSchema.md, doc/user-docs/UsingJsonSettings.md, src/cascadia/TerminalApp/AppLogic.cpp, src/cascadia/TerminalApp/Profile.cpp, src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj, src/tools/ColorTool/ColorTool/ConsoleTargets/TerminalSchemeConsoleTarget.cs
Literally just <kbd>ctrl+f</kbd> find-and-replace all the old `profiles.json` that are sitting around in the repo with `settings.json`. I didn't touch the specs, since it seemed better to leave them in the state that they were originally authored in.
=> Remove last lingering references to profiles.json

src/cascadia/TerminalControl/TermControl.cpp
Takes the lock inside two routines in `TermControl` that were changing the selection endpoint while a rendering frame was still drawing, resulting in several variants of graphical glitches from double-struck selection boxes to duplicated line text.
- Introduced with #5185
The renderer base and specific renderer engine do a lot of work to remember the previous selection and compensate for scrolling regions and deltas between frames. However, all that work doesn't quite match up when the endpoints are changed out from under it. Unfortunately, `TermControl` doesn't have a robust history of locking correctly in step with the renderer nor does the renderer's `IRenderData` currently provide any way of 'snapping' state at the beginning of a frame so it could work without a full lock. So the …
=> Lock when changing selection endpoint on wheel/auto-scroll

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
This is one of the downsides of not running the x86 build in CI.
=> Remove a stray __stdcall that was breaking the x86 build

src/cascadia/TerminalApp/TerminalPage.cpp
This is, perhaps, silly.
Fixes #5564.
=> Actually check the elevation status when disabling tab rearrange

src/cascadia/TerminalApp/defaults.json, src/tools/ColorTool/schemes/tango_dark.itermcolors, src/tools/ColorTool/schemes/tango_light.itermcolors
Followup on ea61aa3b.
The default foreground in the iTerm2 defaults for the Tango Dark color
scheme is too bright, use the value for ANSI 7 (white) instead.
Signed-off-by: Rafael Kitover <rkitover@gmail.com>
#5305
* [x ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
Sorry, I should have really done this in the original PR.
=> Improve default foregrounds for Tango schemes

src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp, src/cascadia/TerminalApp/AppLogic.cpp, src/cascadia/TerminalApp/CascadiaSettings.cpp, src/cascadia/TerminalApp/CascadiaSettings.h, src/cascadia/TerminalApp/Resources/en-US/Resources.resw, src/cascadia/TerminalApp/TerminalWarnings.h
This property was deprecated in 0.11. We probably should have also added a warning
message to help the community figure out that this property is gone and won't work
anymore.
This PR adds that warning.
* I'm not going to list the enormous number of duped threads _wait yes I am_
* #5581
* #5547
* #5555
* #5557
* #5573 
* #5532
* #5527
* #5535 
* #5510
* #5511
* #5512
* #5513
* #5516
* #5515
* #5521 
* This literally isn't even all of them
=> Add a warning about using the `globals` property

src/renderer/base/renderer.cpp
A tiny performance fix in `renderer.cpp`.
The cluster construction code is intensively called during rendering. Even though a single `back()` is fast, but accumulated `back()`s still take a noticiable amount of CPU cycles.
Before:
After:
Manually validated.
=> Improve cluster construction performance

src/cascadia/TerminalControl/TSFInputControl.cpp, src/cascadia/TerminalControl/TSFInputControl.h
This PR fixes a couple of issues with TSFInputControl alignment:
1. The emoji picker IME in particular would show up overlapping the
current buffer row because I stupidly didn't realize that
`TextBlock.ActualHeight` is 0 right after initialization and before
it has any text. So, the emoji picker will show up on the bottom of
the 0 height TextBlock, which overlaps the current buffer row. This
isn't a problem with CJK because inputting text _causes_ the IME to
show up, so by the time the IME shows up, the TextBlock has text and
accordingly has a height.
2. It turns out the emoji picker IME doesn't follow the `TextBlock`
bottom, unlike Chinese and Japanese IME, so if a user were to compose
near the edge of the screen and let the `TextBlock` start line
wrapping, the emoji IME doesn't follow …
=> Adjust TSFInputControl alignment

src/terminal/adapter/ut_adapter/inputTest.cpp, src/terminal/input/terminalInput.cpp
This PR fixes #5525 by re-adding range checks that where erroneously removed in a9c9714.
* Enabled a German keyboard layout
* Entered `<`, `+`, `7`, `8`, `9`, `0` while holding either Alt+Ctrl or AltGr and...
* Ensuring that both produce `|`, `~`, `{`, `[`, `]`, `}`
=> Fix Ctrl+Alt not being treated as a substitute for AltGr anymore

src/cascadia/WindowsTerminal/IslandWindow.cpp, src/cascadia/WindowsTerminal/IslandWindow.h
Enforces a minimum width of 460 wide. This allows tabs to always be seen (albeit partially).
NOTE: A minimum height was originally added to allow the About menu to be seen. This minimum height was removed from this PR because we don't foresee a circumstance where your Terminal is in that state, and you can't just resize it to make the content fit properly.
#4990 may be fixed/affected by this?
Here's some images of what the terminal looks like when it's at its minimum size:
=> Add and enforce minimum width

src/cascadia/TerminalControl/TermControl.cpp
Before this, if the Search Box was open, new selections would not notify automation clients. This was because the UiaEngine (responsible for notifying automation clients) would remain disabled. Now we're enabling it before the early exit in TermControl's FocusHandler
Verified using NVDA.
Narrator's behavior is not impacted, for some reason.
=> Notify UIA when Search finds something

src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/UnitTests_TerminalCore/TerminalAndRendererTests.cpp, src/cascadia/UnitTests_TerminalCore/TerminalBufferTests.cpp, src/cascadia/UnitTests_TerminalCore/UnitTests.vcxproj
This PR clamp the "new rows" scrolling value to a positive number. We can't create a negative number of new rows. It also adds a test.
The origin of this bug is that as newlines are emitted, we'll accumulate an enormous scroll delta into a selection region, to the point of overflowing a `SHORT`. When the overflow occurs, the `Terminal` would fail to send a `NotifyScroll()` to the `TermControl` hosting it.
For this bug to repro, we need to:
- Have a sufficiently large buffer, because each newline we'll accumulate a delta of (0, ~bufferHeight), so (bufferHeight^2 + bufferHeight) > SHRT_MAX
- Have a selection
* Dustin verified this actually
* Created a new insane test case
=> Clamp the new rows scrolling value to a positive number

src/buffer/out/textBuffer.cpp, src/buffer/out/textBuffer.hpp, src/cascadia/PublicTerminalCore/HwndTerminal.cpp, src/cascadia/TerminalControl/TermControl.cpp, src/interactivity/win32/Clipboard.cpp
Web apps apparently will paste the \<title\> as plaintext before the actual HTML content from the clipboard. Since this seems to be widespread behavior across web apps, this isn't just a bug in _some app_, this is a bug on us. We shouldn't emit the title. 
This PR removes the title tag from the generated HTML.
Above is composing an email with copied text from 0.11.
Below is using the same webmail client to compose an email with this patch
=> Remove the title tag from the generated HTML

src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp, src/host/getset.cpp, src/inc/test/CommonState.hpp
Hide any commandline (cooked read) we have before we begin a resize, and
show it again after the resize. 
* I found #5618 while I was working on this.
Basically, during a resize, we try to restore the viewport position
correctly, and part of that checks where the current commandline ends.
However, when we do that, the commandline's _current_ state still
reflects the _old_ buffer size, so resizing to be smaller can cause us
to throw an exception, when we find that the commandline doesn't fit in
the new viewport cleanly.
By hiding it, then redrawing it, we avoid this problem entirely. We
don't need to perform the check on the old commandline contents (since
they'll be empty), and we'll redraw it just fine for the new buffer size
* ran tests
* …
=> Hide the commandline on a resize to prevent a crash when snapping the window

src/cascadia/TerminalApp/ActionArgs.h, src/cascadia/TerminalApp/CascadiaSettings.h, src/cascadia/TerminalApp/DebugTapConnection.h, src/cascadia/TerminalApp/Pane.h, src/cascadia/TerminalApp/Profile.h, src/cascadia/TerminalApp/TerminalWarnings.h, src/cascadia/TerminalAzBridge/ConsoleInputReader.h, src/host/CommandNumberPopup.hpp, src/host/CopyFromCharPopup.hpp, src/host/conareainfo.h, src/host/conattrs.cpp
If a class has a constructor which can be called with a single argument, then this constructor becomes conversion constructor because such a constructor allows conversion of the single argument to the class being constructed. To ensure these constructors are passed the argument of its type, I labeled them explicit.
In some header files, there were constructors that took a value that could involve implicit conversions, so I added explicit to ensure that does not happen.
Unit testing
=> Add explicit identifier to some constructors

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalControl/TermControl.h
Based on the discussion in #5479, it seems that the crash is caused by a race condition due to not obtaining the write lock before calling `TriggerFontChange`.
I'm not totally sure if my approach is the right one, but I've taken the lock out of `_RefreshSize` since it seems like all calls of `_RefreshSize` come after a `TriggerFontChange`/`UpdateFont`. Then I just 
made sure all calls of `TriggerFontChange`/`UpdateFont` are preceded with a `LockForWriting`.
Scrolling to change my font size does not kill the Terminal anymore! 🙌
=> Grab the write lock before updating the font

src/cascadia/WindowsTerminal/AppHost.cpp
We've got a weird crash that happens terribly inconsistently, but pretty
readily on migrie's laptop, only in Debug mode. Apparently, there's some
weird ref-counting magic that goes on during teardown, and our
Application doesn't get closed quite right, which can cause us to crash
into the debugger. This of course, only happens on exit, and happens
somewhere in the `...XamlHost.dll` code.
Crazily, if we _manually leak the `Application`_ here, then the crash
doesn't happen. This doesn't matter, because we really want the
Application to live for _the entire lifetime of the process_, so the only
time when this object would actually need to get cleaned up is _during
exit_. So we can safely leak this `Application` object, and have it just
get cleaned up normally when our process exits.
=> Intentionally leak our Application, so that we DON'T crash on exit

src/renderer/dx/CustomTextRenderer.cpp
This fixes the RTL regression caused in #4747. We create the rectangle taking the direction (through the BiDi Level) into account, and then the rendering works again. The GlyphRun shaping could still probably use some work to be a polished thingy, and there are still issues with RTL getting chopped up a lot when there's font fallback going on, but this fixes the regression, and it's now functional again.
#4779 #4747 
The baseline is actually direction dependent. So when it was being initialized, the unconditional baseline as left broke it, setting the box off to right of the text. We just check if the `GlyphRun->bidiLevel` is set, and if so, we adjust it so that the baseline lines up with the right, not with the left.
=> Fix RTL regression (fixes #4779)

src/cascadia/TerminalApp/AppCommandlineArgs.cpp, src/cascadia/TerminalApp/AppCommandlineArgs.h, src/cascadia/TerminalApp/AppLogic.cpp, src/cascadia/TerminalApp/AppLogic.h, src/cascadia/TerminalApp/AppLogic.idl, src/cascadia/TerminalApp/Resources/en-US/Resources.resw, src/cascadia/TerminalApp/TerminalPage.cpp, src/cascadia/TerminalApp/TerminalPage.h, src/cascadia/TerminalApp/TerminalPage.idl, src/cascadia/WindowsTerminal/AppHost.cpp
=> Add support for displaying the version with `wt --version`

src/cascadia/TerminalApp/TerminalPage.cpp
This was an oversight.
Fixes #5738
It looks like this happens when you close a tab _while that tab is being closed_. I tried that hella.
=> Make sure we don't try to remove tabs when they don't exist

src/cascadia/TerminalApp/TerminalPage.cpp
This is actually related to another issue we have, #3917. I think if the system is set to "Dark" theme, but the app is set to light theme, then the brush lookup in `_ClearNewTabButtonColor` still returns to us the dark theme brushes.
Fortunately, since we're not actually setting the color of the new tab button anymore, we can just remove the call to that method now, and loop back on it later.
* regressed in #3789 
* related to #3917
=> Don't set the new tab button colors for now

build/pipelines/release.yml, src/cascadia/CascadiaPackage/CascadiaPackage.wapproj, src/cascadia/CascadiaPackage/Package-Pre.appxmanifest, src/cascadia/CascadiaPackage/Resources/Resources.resw, src/cascadia/CascadiaResources.build.items, src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj, src/cascadia/WindowsTerminalUniversal/WindowsTerminalUniversal.vcxproj
This adds a new appxmanifest for 'Windows Terminal (Preview)' and links the resources.
Code-wise, split up `WindowsTerminalReleaseBuild` into...
- WindowsTerminalOfficialBuild: [true, false]
- WindowsTerminalBranding: [Dev, Preview, Release]
Added a comment about that in release.yml
used msbuild to build...
then checked the msix for the correct name/icon.
=> Add a new appxmanifest for preview

src/cascadia/TerminalApp/TerminalPage.cpp
If we're fullscreen, the TabView isn't `Visible`. If it's not `Visible`, it's _not_ going to raise a `SelectionChanged` event, which is what we usually use to focus another tab. Instead, we'll have to do it manually here.
So, what we're going to try to do is move the focus to the tab to the left, within the bounds of how many tabs we have.
EX: we have 4 tabs: [A, B, C, D]. If we close:
* A (`tabIndex=0`): We'll want to focus tab B (now in index 0)
* B (`tabIndex=1`): We'll want to focus tab A (now in index 0)
* C (`tabIndex=2`): We'll want to focus tab B (now in index 1)
* D (`tabIndex=3`): We'll want to focus tab C (now in index 2)
`_UpdatedSelectedTab` will do the work of setting up the new tab as the focused one, and unfocusing all the others.
Also, we need to _manually_ set the …
=> Manually select a new tab when we're in fullscreen mode

build/config/SignConfig.WindowsTerminal.xml
This allows me to make the build pipeline, instead of the release
engineer, put the version number in the package name.
It also lets us sign _multiple packages_ (if we ever produce more than
one.)
=> build: merge the signing steps and wildcard them

src/cascadia/TerminalCore/terminalrenderdata.cpp
We accidentally missed switching one `TriggerRedrawAll` to `TriggerScroll`. This does that.
#5185 - applies logic from this PR
Followed bug repro steps.
=> Trigger scroll on scrolled selection

src/renderer/dx/CustomTextLayout.h
One of the downsides of not having x86 in CI.
=> dx: fix a missing stdcall that was blowing up the x86 build

src/renderer/dx/DxRenderer.cpp
There is no guarantee that the HWND's backing color matches our expected
backing color.
This repairs the gutter in the WPF terminal.
=> dx: when filling an HWND target, use the actual background color

doc/cascadia/SettingsSchema.md, doc/cascadia/profiles.schema.json, src/cascadia/TerminalApp/GlobalAppSettings.cpp, src/cascadia/TerminalApp/GlobalAppSettings.h, src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalSettings/IControlSettings.idl, src/cascadia/TerminalSettings/TerminalSettings.cpp, src/cascadia/TerminalSettings/terminalsettings.h, src/renderer/dx/DxRenderer.cpp, src/renderer/dx/DxRenderer.hpp
Adds user settings to adjust rendering behavior to mitigate blurry text on some devices.
- #778 introduced this, almost certainly.
When we switched from full-screen repaints to incremental rendering, it seems like we exposed a situation where some display drivers and hardware combinations do not handle scroll and/or dirty regions (from `IDXGISwapChain::Present1`) without blurring the data from the previous frame. As we're really close to ship, I'm offering two options to let people in this situation escape it on their own. We hope in the future to figure out what's actually going on here and mitigate it further in software, but until then, these escape hatches are available.
1. `experimental.rendering.forceFullRepaint` - This one restores the pre-778 behavior to the Terminal. On every …
=> Add renderer settings to mitigate blurry text for some graphics devices

src/interactivity/win32/lib/win32.LIB.vcxproj
#5743 introduced a dependency from _any consumer of the DX header_ to a header generated from an IDL file.
I hope this fixes #5819. I'm going to run builds to find out.
=> InteractivityWin32: Add a dependency on Dx

src/cascadia/TerminalControl/TermControl.cpp, src/cascadia/TerminalCore/TerminalSelection.cpp
Apparently, this accounts for somewhere between 7% and 14% of our
crashes on 1.0RC1.
It turns out that we weren't really adequately guarding calls to SetSelectionEnd and friends.
I decided that it would be prudent to add a WIL log.
First, I figured out how the heck to repro this. Snap the window, begin a selection, then use <kbd>Win+Up</kbd> to resize it. Then, I fixed it and tried the repro again.
=> Stop trying to set selection endpoints when there's no selection

src/cascadia/TerminalApp/TerminalPage.cpp
Terminal should try not to join the choir invisible when the clipboard
API straight up horks it.
This accounts for ~3% of the crashes seen in 1.0RC1 and ~1% of the crashes
seen all-up in the last 14 days.
Fixes #4906.
Found out a surefire way to repro it!
`"copyOnSelect": true`
Copy something small.
Hold down <kbd>Ctrl+Shift+V</kbd>
Double-click like your life depends on it. Double-click like you're
playing cookie clicker again. 2013 called, it wants its cookies back.
=> Teach TerminalPage to handle exceptions that happen during paste

.github/actions/spell-check/whitelist/whitelist.txt, src/types/CodepointWidthDetector.cpp
A couple of codepoints, namely the card suites, male and female signs,
and white and black smiling faces were changed to have a two-column
width as part of #5795 since they were specified as emoji in Unicode's
emoji list v13.0[1]. 
These particular glyphs also show up in some of the most fundamental
code pages, such as CP437[2] and WGL4[3]. We should
not be touching the width of the glyphs in these codepages, as suddenly
changing a long-time-running narrow glyph to use two-columns all of a
sudden will surely break (and has already broken) things.
[1] https://www.unicode.org/Public/13.0.0/ucd/emoji/emoji-data.txt
[2] https://en.wikipedia.org/wiki/Code_page_437
[3] https://en.wikipedia.org/wiki/Windows_Glyph_List_4
Closes #5822
=> Revert some emoji back to narrow width

src/cascadia/TerminalControl/Resources/en-US/Resources.resw, src/cascadia/TerminalControl/TermControl.cpp
Implements drag-dropping text onto a `TermControl`, in addition to the already supported drag-drop of files.
* [StandardDataFormats](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.standarddataformats?view=winrt-18362)
* [StandardDataFormats::Text](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.standarddataformats.text?view=winrt-18362#Windows_ApplicationModel_DataTransfer_StandardDataFormats_Text)
* [GetTextAsync](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.datapackageview.gettextasync?view=winrt-18362)
Oh I also changed "Copy path to file" to "Paste path to file". I thought that actually made more sense here
* Tested manually that text and files …
=> Implement drag-drop paste for text

src/cascadia/TerminalApp/TerminalPage.cpp
When we're dragging the tab around, if you execute a `ClosePane`/`CloseTab`, then we should make sure to actually activate a new tab, so that focus doesn't just fall into the void.
* This is almost exactly #5799, but with rearranging tabs
We suppress `_OnTabItemsChanged` events during a rearrange, so if a tab is closed while we're rearranging tabs, the we don't fire the `SelectionChanged` event that we usually do during a close that would select the new tab.
* Tested manually
- Confirmed that tragging a tab out, closing it, then dragging it back in does nothing.
=> Manually close tabs when they're closed while dragging them

src/types/CodepointWidthDetector.cpp
This seems to be in line with the emoji-sequences table in the latest
version of the Unicode standard: those glyphs require U+FE0F to activate
their emoji presentation. Since we don't support composing U+FE0F, we
should not present them as emoji by default.
Fixes #5910.
Yes, I hate this.
=> CodepointWidthDetector: reclassify U+25FB, U+25FC as Narrow

tools/bcz.cmd
The `bcz.cmd` script calls a powershell helper script (bx.ps1), but (previous to this change) did not pass `-NoProfile`, which means that powershell.exe would load and run one's personal profile script, which can only slow things down, and worse, can change default behaviors (such as turning on strict mode by default, which will cause scripts that don't run cleanly with strict mode to generate lots of errors--such as bx.ps1).
This change amends the powershell.exe command line to pass -NoProfile, as well as to set the execution policy and ensure that interactive prompts can't inadvertently show up (normal best practices for use of powershell in build scripts).
This change will speed things up (probably negligibly, but still) and (more importantly) prevent non-determinism and errors that …
=> Make bcz not run personal PowerShell profile script (-NoProfile)

.github/actions/spell-check/patterns/patterns.txt
This addresses a string introduced by #5930
Stop `adb` from being flagged in PRs.
https://github.com/jsoref/terminal/commit/76ac9858143501ba83dab0eb3e5c95623aff5050 shows a ✔️ .
And thankfully this is a pattern file, so it won't conflict w/ the 0.0.16 update.
=> ci: Update spelling patterns to cover cascadia commit ID

CONTRIBUTING.md
Issue: On clicking "the Help-Wanted label" hyperlink, a page with filters is:open label:Help-Wanted is opened which shows "No results matched your search".
Fix: hyperlink to "the Help-Wanted label" is changed and tested.
=> doc: correct Help Wanted link in CONTRIBUTING.md

.github/actions/spell-check/whitelist/whitelist.txt
'carlos' 'zamora' exists. I swear. This was caught on a number of PRs...
=> Add Carlos Zamora to spell checker

README.md
included a link to the repo, but live docs is a better reading experience
Recommend pointing to the docs.microsoft.com/windows/terminal live documentation in this ReadMe so users get a good reading experience. I left the link to the docs source code in case folks want to contribute.
* [ x] Closes #xxx
* [ x] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ na] Tests added/passed
* [ na] Requires documentation to be updated
=> Update to point to live docs

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
This is an enormously trivial nit - when we launch maximized, we don't draw the maximize button in the "restore" state.
This PR changes the terminal to manually update the Maximize button on launch, once the titlebar is added to the UI tree.
=> Make sure to update the maximize button's visual state on launch

src/host/conimeinfo.cpp, src/host/conimeinfo.h, src/host/convarea.cpp
When using an _Input Method Editor_ in conhost for East Asian languages, the text cursor is temporarily hidden while the characters are being composed. When the composition is complete, the cursor visibility is meant to be restored, but that doesn't always happen if the IME composition is cancelled. This PR makes sure the cursor visibility is always restored, regardless of how the IME is closed.
The original implementation hid the cursor whenever `ConsoleImeInfo::WriteCompMessage` was called (which could be multiple times in the course of a composition), and then only restored the visibility when `ConsoleImeInfo::WriteResultMessage` was called. If a composition is cancelled, though, `WriteResultMessage` would never be called, so the cursor visibility wouldn't be restored.
I've now made …
=> Make sure cursor visibility is restored after using an IME

src/cascadia/TerminalApp/TerminalPage.cpp
Fixes #6079 by implementing support for IStorageItem clipboard contents. Manually tested, seems to work for both types of address-copying from Explorer (as well as normal text).
* Not sure what tests would be useful here, it's mostly to do with what Explorer's doing
Not enormously familiar with C++ or this codebase, so happy to make changes as requested.
Ran the terminal, pasted from several different sources (explorer's various copy functions + plaintext)
=> Fix #6079, allow pasting from Explorer's 'Copy Address'

src/tools/U8U16Test/U8U16Test.hpp
Adds implicit stdexcept header include to u8u16test tool.
In VS 16.5, the <stdexcept> header was pulled in by `<string>` or  `<string_view>` or `<array>` or `<algorithm>` implicitly. In VS 16.6, that's gone. No one wrote it in the header because it was just automatically there in the past. Now I wrote it in the header.
=> Add stdexcept header explicitly to u8u16test tool

src/cascadia/ShellExtension/OpenTerminalHere.h
These methods need to be declared `STDMETHODIMP` so the x86 build will pass.
=> Make the Shell Extension methods STDMETHODIMP

src/cascadia/CascadiaPackage/Package-Pre.appxmanifest, src/cascadia/CascadiaPackage/Package.appxmanifest
These manifests were missing some namespaces in #6100
=> Add missing namespaces to the Preview, Release manifests

doc/cascadia/profiles.schema.json
Fix some simple syntax errors in font weight options.
Existing syntax errors in file [profiles.schema.json](https://github.com/microsoft/terminal/blob/master/doc/cascadia/profiles.schema.json):
1. Line 537: indentation error
2. Line 559: "]" for closing "one of" is mising; "," after "}" is mising
1. Open the settings file for Windows Terminal, `$schema` will display as "unable to parse content".
2. Modify `$schema` to new file.
```json
"$schema": "https://raw.githubusercontent.com/alexzshl/terminal/patch-2/doc/cascadia/profiles.schema.json",
```
=> Fix syntax errors in font weight options

src/interactivity/win32/SystemConfigurationProvider.cpp, src/propsheet/PropSheetHandler.cpp, src/propslib/ShortcutSerialization.cpp, src/propslib/ShortcutSerialization.hpp
Implements what I was suggesting in #6266 where if a shortcut doesn't
specify an icon, the shortcut target full path is used before searching
for a matching executable in the path.
Found due to not getting the right icon in conhost from the Yori
installer.  It's fixed in the installer from
https://github.com/malxau/yori/commit/5af366b6a5ea4c92dce3940abb8616ab5bd300a6
for all current users of conhost though, so this PR is just trying to
minimize surprises for the next guy.
I know conhost and shortcut settings aren't really the team's focus
which is why I'm doing this.  I understand though if there's a better
way or there are factors that I hadn't considered.  Note that the path
searching code is used when programs are launched without using a
shortcut, and it will match if the working …
=> Find icon from shortcut target if shortcut doesn't specify it

src/cascadia/TerminalApp/TerminalPage.cpp
Users can now open an auto split pane with the mouse.
When opening the dropdown, alt+invoke the profile of choice and it should open in an auto sized pane.
#5025 - further discussion there as to whether this actually closes it.
Had to do a special check for debugTap because that's triggered by holding both alts.
alt+click/enter on a new profile. Looks great!
=> Adds Alt+Click to auto split pane

src/host/outputStream.cpp, src/host/outputStream.hpp, src/terminal/adapter/DispatchTypes.hpp, src/terminal/adapter/ITermDispatch.hpp, src/terminal/adapter/adaptDispatch.cpp, src/terminal/adapter/adaptDispatch.hpp, src/terminal/adapter/conGetSet.hpp, src/terminal/adapter/termDispatch.hpp, src/terminal/adapter/ut_adapter/adapterTest.cpp, src/terminal/input/terminalInput.cpp, src/terminal/input/terminalInput.hpp, src/terminal/parser/IStateMachineEngine.hpp, src/terminal/parser/InputStateMachineEngine.cpp, src/terminal/parser/InputStateMachineEngine.hpp, src/terminal/parser/OutputStateMachineEngine.cpp, src/terminal/parser/OutputStateMachineEngine.hpp, src/terminal/parser/ft_fuzzer/VTCommandFuzzer.cpp, src/terminal/parser/stateMachine.cpp, src/terminal/parser/stateMachine.hpp, src/terminal/parser/ut_parser/OutputEngineTest.cpp, src/terminal/parser/ut_parser/StateMachineTest.cpp
This PR adds support for the core VT52 commands, and implements the `DECANM` private mode sequence, which switches the terminal between ANSI mode and VT52-compatible mode.
PR #2017 defined the initial specification for VT52 support.
PR #4044 removed the original VT52 cursor ops that conflicted with VT100 sequences.
Most of the work involves updates to the parsing state machine, which behaves differently in VT52 mode. `CSI`, `OSC`, and `SS3` sequences are not applicable, and there is one special-case escape sequence (_Direct Cursor Address_), which requires an additional state to handle parameters that come _after_ the final character.
Once the parsing is handled though, it's mostly just a matter of dispatching the commands to existing methods in the `ITermDispatch` interface. Only one new …
=> Add support for VT52 emulation

.github/actions/spell-check/dictionary/apis.txt, src/buffer/out/CharRow.cpp, src/buffer/out/CharRow.hpp, src/cascadia/PublicTerminalCore/HwndTerminal.cpp, src/cascadia/TerminalConnection/ConptyConnection.cpp, src/renderer/dx/DxRenderer.cpp
When resizing the window title, a GDI object would be leaked. This has to do with our island message handler using `wil` to track these objects and `wil` having a bug.
microsoft/wil#100
=> Update wil. Fixes GDI handle leak

src/cascadia/TerminalApp/MinMaxCloseControl.xaml
As discussed in #6293 , this PR adds a fade animation to button background when pointer hover ends
Added storyboarded coloranimations to the visualstategroup of captionbuttons
Tested manually
=> Animate Hover state change of CaptionButtons

src/cascadia/TerminalApp/AppCommandlineArgs.cpp, src/cascadia/TerminalApp/AppCommandlineArgs.h, src/cascadia/TerminalApp/Resources/en-US/Resources.resw
Adds support for setting the terminal `title` with the commandline argument `--title <title>`.
* I wasn't sure how we felt about `-t` being the short version of this argument, so I left it out. If we're cool with that, adding it wouldn't be hard.
=> Add support for `--title` to the `wt.exe` commandline args

src/cascadia/TerminalApp/AppLogic.cpp
I was debugging the terminal unpackaged, and noticed that this method crashes immediately. I'm gonna bet that this functionality only works when the app is installed as a package. Wrapping this whole method up in one big ol' `try/catch` seems to fix the immediate crash.
* Introduced in #4908 
We _could_ display a warning if the user has this property set and is running the terminal unpackaged, to clue them in that it won't work? I'm willing to file a follow-up for that, but I think we should fix the crash _now_.
* Ran the terminal successfully unpackaged.
=> Fix a crash with this method when running unpackaged

src/cascadia/TerminalApp/GlobalAppSettings.cpp, src/cascadia/TerminalApp/GlobalAppSettings.h, src/cascadia/TerminalApp/Profile.cpp, src/cascadia/TerminalApp/Profile.h
Every time somebody sees these they think they have to write new ones for their new things.
=> Remove more serializers missed in 6394e5d70

.github/actions/spell-check/dictionary/apis.txt, src/host/conimeinfo.cpp, src/renderer/base/renderer.cpp
Restores proper line drawing during IME operations in `conhost`
- Changed `ConsoleImeInfo::s_ConvertToCells` to be less confusing. It's doing about the same thing, but it's way easier to read now and the compiler/linker/optimizer should just be the same.
- Edited `Renderer::_PaintBufferOutputHelper` to check each attribute for line drawing characters as the right half of a two-col character might have different line drawing characters than the left-half.
=> Fix line drawing during IME operations.

tools/bcz.cmd
Running `nuget restore` on every build is pretty unnecessary - usually, you _know_ when you need to run it. For the inner dev loop, this is a few seconds on every `bx` build. 
This adds a environment variable you can set to skip the `nuget restore` part of a `bcz` build.
Add the following to your `.razzlerc.cmd`:
```cmd
set _SKIP_NUGET_RESTORE=1
```
and `bcz` (and the other helpers) _won't_ perform a nuget restore on every build.
=> Add a helper to skip nuget restore during local builds

src/host/ut_host/VtRendererTests.cpp, src/interactivity/onecore/BgfxEngine.cpp, src/renderer/base/RenderEngineBase.cpp, src/renderer/base/renderer.cpp, src/renderer/base/renderer.hpp, src/renderer/dx/CustomTextRenderer.cpp, src/renderer/dx/CustomTextRenderer.h, src/renderer/dx/DxRenderer.cpp, src/renderer/dx/DxRenderer.hpp, src/renderer/gdi/paint.cpp, src/renderer/inc/CursorOptions.h, src/renderer/inc/IRenderEngine.hpp, src/renderer/inc/RenderEngineBase.hpp, src/renderer/uia/UiaRenderer.cpp, src/renderer/vt/XtermEngine.cpp, src/renderer/vt/paint.cpp, src/renderer/wddmcon/WddmConRenderer.cpp
This is the plan that @miniksa suggested to me. Instead of trying to do lots of work in all the renderers to do backgrounds as one pass, and foregrounds as another, we can localize this change to basically just the DX renderer. 
1. First, we give the DX engine a "heads up" on where the cursor is going to be drawn during the frame, in `PrepareRenderInfo`.
- This function is left unimplemented in the other render engines.
2. While printing runs of text, the DX renderer will try to paint the cursor in `CustomTextRenderer::DrawGlyphRun` INSTEAD of `DxEngine::PaintCursor`. This lets us weave the cursor background between the text background and the text. 
* #6151 was a spec in this general area. I should probably go back and update it, and we should probably approve that first.
* #6193 is also …
=> Draw the cursor underneath text, and above the background

doc/cascadia/SettingsSchema.md, doc/cascadia/profiles.schema.json, src/cascadia/TerminalApp/Profile.cpp, src/cascadia/TerminalApp/Profile.h, src/cascadia/TerminalApp/defaults-universal.json, src/cascadia/TerminalApp/defaults.json, src/cascadia/TerminalCore/Terminal.cpp, src/cascadia/TerminalCore/Terminal.hpp, src/cascadia/TerminalSettings/ICoreSettings.idl, src/cascadia/TerminalSettings/terminalsettings.h, src/cascadia/UnitTests_TerminalCore/MockTermSettings.h
Some people wish to use Ctrl+Alt combinations without Windows treating those as an alias for AltGr combinations. This PR adds a new `altGrAliasing` setting allowing one to control this behavior.
* Choose a German keyboard layout
* Using `showkey -a` ensured that both `Ctrl+Alt+Q/E` and `AltGr+Q/E` produce `@/€`
* Added `"altGrAliasing": false` to the WSL profile
* Using `showkey -a` ensured `Ctrl+Alt+Q/E` now produces `^[^Q/E` while `AltGr+Q/E` continues to produce `@/€`
=> Allow Ctrl+Alt <> AltGr aliasing to be disabled

src/buffer/out/TextAttribute.hpp, src/host/conareainfo.cpp, src/host/getset.cpp, src/host/popup.cpp, src/host/ut_host/AttrRowTests.cpp, src/host/ut_host/OutputCellIteratorTests.cpp, src/host/ut_host/ScreenBufferTests.cpp, src/interactivity/win32/menu.cpp, src/terminal/adapter/ut_adapter/adapterTest.cpp
In Windows, we build with /Zc:wchar_t- (which makes wchar_t an unsigned
short typedef.) This causes build breaks when we compare two wchar_t
values (or a wchar_t and an enum class that's of type wchar_t) and the
compiler decides that it might want to _promote them to TextAttribute_
before doing the comparison.
=> Make the conversion from WORD to TextAttribute explicit

.github/actions/spell-check/expect/expect.txt, src/buffer/out/TextAttribute.cpp, src/buffer/out/TextAttribute.hpp, src/buffer/out/TextColor.cpp, src/buffer/out/TextColor.h, src/host/cmdline.cpp, src/host/cmdline.h, src/host/conareainfo.cpp, src/host/conareainfo.h, src/host/conimeinfo.cpp, src/host/ft_host/API_RgbColorTests.cpp, src/host/output.cpp, src/host/popup.cpp, src/host/popup.h, src/host/screenInfo.cpp, src/host/screenInfo.hpp, src/host/selectionInput.cpp, src/host/settings.cpp, src/host/ut_host/ObjectTests.cpp
This PR provides a faster algorithm for converting 8-bit and 24-bit
colors into the 4-bit legacy values that are required by the Win32
console APIs. It also fixes areas of the code that were incorrectly
using a simple 16-color conversion that didn't handle 8-bit and 24-bit
values.
The faster conversion algorithm should be an improvement for issues #783
and #3950.
One of the main points of this PR was to fix the
`ReadConsoleOutputAttribute` API, which was using a simplified legacy
color conversion (the original `TextAttribute:GetLegacyAttributes`
method), which could only handle values from the 16-color table. RGB
values, and colors from the 256-color table, would be mapped to
completely nonsensical values. This API has now been updated to use the
more correct …
=> Improve the legacy color conversions

src/cascadia/CascadiaPackage/Package-Dev.appxmanifest, src/cascadia/CascadiaPackage/Package-Pre.appxmanifest, src/cascadia/CascadiaPackage/Package.appxmanifest
We're removing this because of MSFT:24623699, which prevents us from being able to do the right thing when we're called on the background of a directory for a range of OS builds. 
#6414 will track re-adding this to the Terminal when the original issue is closed.
* I work here
=> Remove the shell extension from directory backgrounds
