microsoft/terminal

src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest
src/cascadia/CascadiaPackage/Resources/Resources.resw

Remove parentheses from the Preview and Dev build. Now they're called Windows Terminal Preview and Windows Terminal Dev Build respectively.
Also removed them from other identifiers of Terminal for consistency.

Remove parentheses from Preview and Dev build

---

src/cascadia/TerminalApp/Tab.cpp
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/cascadia/TerminalCore/terminalrenderdata.cpp

When opening a new tab, it takes a few milliseconds before title to
appears. This PR makes it instantaneous.
* Updated the Terminal so that it can load the title from the settings
before it is initialized.
* Load terminal settings in TermControl constructor before the terminal
is initialized (see above).
* Update Tab so that it sets the TabViewItem's title in the constructor
(in Tab::_MakeTabViewItem) instead of waiting for the VT sequence to
set the title (from what I understand).
NOTE 1: there is a similar problem with the tabview icon which is not
fixed by this PR.
NOTE 2: This is only a problem with animations disabled because
otherwise the title fades in so there is enough time for it to be set
when it becomes visible.
I ran the terminal and opened a new tab. The title appears …

Set tab title as early as possible

---

.github/actions/spell-check/dictionary/apis.txt
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalCore/Terminal.cpp
src/types/inc/IInputEvent.hpp

Does what it says on the label. Pure modifier keys weren't making it
this far at all prior to #6309. This PR changes these methods to make
sure that we only dismiss a selection or snap on input when the key
pressed isn't a modifier key.
* regressed in #6309
* Tried to repro this in the Terminal, couldn't anymore.

Don't snap on input nor dismiss selection for just a modifier key

---

src/cascadia/TerminalControl/TermControl.cpp

When someone asked "Do we need to send a F7 keyup too" in #6309, the right answer was actually _no_. Turns out that while XAML will eat the F7 key**down**, it _won't_ eat the F7 key**up**. 
* regressed in #6309
* Checked this with the debug tap

Don't send a manual F7 keyup

---

doc/specs/#2557 - Settings Keybinding.md

As I was looking at #2557, I realized that the addition of a Settings UI could make things a little weird. I decided to add a mini spec to discuss what to do.
The implementation of this feature shouldn't be too difficult. I more just want to openly discuss what we think the right approach should be.
#2557 - open defaults keybinding

Add Mini-Spec for openSettings

---

src/cascadia/WpfTerminalControl/TerminalContainer.cs
src/cascadia/WpfTerminalTestNetCore/WpfTerminalTestNetCore/MainWindow.xaml.cs
src/renderer/dx/CustomTextRenderer.cpp
src/renderer/dx/CustomTextRenderer.h

* [wpf] WM_KEYUP crashes on x64 #6444
- Turns out that doing the `(uint)lParam` cast worked fine for the
keydowns, because the value of lParam usually didn't have super
high-order bits set. That's not the case for keyups, where the 30th
bit is _always_ set. This is fixed by explicitly getting the byte
with the scancode in it.
* [wpf] WM_KEYUP generates wrong value in Win32 input mode #6445
- This was fixed by basically the same thing as the above.
* [wpf] WPF control crashes on startup trying to render cursor #6446
- This was a regression from #6337. I forgot to initialize the brush
used to paint the cursor, because the UWP version always uses color
(but the WPF one relies on the text foreground color).
* Also adds a minor change to the WPF test app, so that the user can
actually exit …

Fix 3 different bugs in the WPF control

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/ActionArgs.cpp
src/cascadia/TerminalApp/ActionArgs.h
src/cascadia/TerminalApp/ActionArgs.idl
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/defaults.json

Adds the `target` keybinding arg to `openSettings`. Possible values include: `defaultsFile`, `settingsFile`, and `allFiles`.
#5915 - mini-spec
Implemented as discussed in the attached spec. A new enum will be added for the SettingsUI when it becomes available.
Added the following to my settings.json:
```json
{ "command": "openSettings", "keys":... },
{ "command": { "action": "openSettings" }, "keys":... },
{ "command": { "action": "openSettings", "target": "settingsFile" }, "keys":... },
{ "command": { "action": "openSettings", "target": "defaultsFile" }, "keys":... },
{ "command": { "action": "openSettings", "target": "allFiles" }, "keys":... }
```

Add keybinding arg to openSettings

---

src/inc/til/bitmap.h

Add a fast path to `til::bitmap::translate`: use bit shifts when the delta is vertical.
Performance while printing the content of a big file, with the patch from #6492 which hasn't been merged yet, in Release mode:
Before:
After:

Add fast path to til::bitmap::translate using bitshifts

---

src/inc/til/bitmap.h

While re-reading the code, I found out that I forgot to do clear cached runs after translate_y in my previous PR.

Clear cached runs after translate_y

---

src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp

This commit reverts the removal of the "SSH hack" in #5383. It was
originally added as a solution to #4911, when we realized that SSH would
request the SS3 cursor key encoding but we weren't equipped to handle
it.
A number of folks have filed issues that, in summary, say "when I use
SSH, I can't select/copy/paste text". It turns out that SSH will _also_
pass through requests for mouse input. Terminal dutifully responds to
those requests, of course, by disabling mouse selection/copy/paste. SSH
is **NOT** actually in VT_INPUT_MODE, so it will never receive the mouse
messages.
It's important to note that even with #376 fixed, we are still required
to keep this check. With the closure of #376, we'll be able to convert
VT mouse input back into Win32 mouse input for Win32 applications . . .
but …

Reintroduce the check for VT_INPUT_MODE in AdaptDispatch

---

src/cascadia/TerminalControl/TermControl.cpp

Make sure to set the scancode for the manual alt-up's we're sending. If you don't, then terminalInput in the conpty is going to treat that keypress as an actual NUL, and send that to the connected client.
* regressed in #6421 
Tested `showkeys -a`

Fix sending a NUL on alt key up

---

src/cascadia/TerminalCore/Terminal.cpp

Prior to #6309, we'd only snap on input for non-modifier key_down_ events. #6423 fixed this for modifier keys, but didn't fix this for keyups.
* #6423 was an incomplete fix to this problem, which caused this regression

Only snap on key _downs_

---

src/cascadia/TerminalApp/defaults.json

Fixes a misspelling in defaults.json that made the new openSettings keybinding not actually work.
#6299 - original PR
pressed <kbd>ctrl+alt+,</kbd>

Fix openSettings misspelling in defaults

---

src/cascadia/TerminalCore/Terminal.cpp

Fixes #6377. `TerminalCore` does not initialize `_altGrAliasing`. The impact is minimized in WT because it defaults to `true` in higher layers. It's not initialized when WPF is driving.

Fixed #6377: TerminalCore::_altGrAliasing is undefined by default

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

This PR changes `TermControl::_KeyHandler` to use early returns, which you can think of as "guard clauses".
This has the benefit of a reduced nesting level, easier to understand control flow and opens op the way to more complex conditions.
Everything still works as expected.

Use early returns in TermControl::_KeyHandler

---

src/buffer/out/AttrRow.cpp

Improve `ATTR_ROW::ReplaceAttrs` performance by only reserving the necessary capacity instead of resizing the new run.
That way `TextAttributeRun`s are only instantiated once instead of twice.
Performance could be further improved by directly moving `TextAttributeRun`s into the new vector, but I considered this out of scope for this PR.
CPU usage when running `cacafire` is slightly reduced.

Improved ATTR_ROW::ReplaceAttrs performance

---

src/cascadia/TerminalControl/TermControl.cpp
src/renderer/dx/DxRenderer.cpp
src/renderer/dx/DxRenderer.hpp

- I found four settings that weren't hot reloadable with the 3927 comment above them:
1. Experimental retro terminal effect
2. Experimental software rendering
3. Experimental full repaint rendering
4. Antialiasing settings for text
I made them all hot reloadable by telling the `TermControl` to propagate them on settings change to the `DxEngine`.
Then I set up the `DxEngine` inside the setters to only set them if they changed. And if they do change, to trigger a full repaint and/or a complete drop and recreate of the entire DX device chain (as would happen if it were lost for another reason like a user-mode graphics failure, disconnected display, etc.)
I made the boolean an atomic because the settings can be coming in off of another thread (the XAML eventing one) and the renderer is …

Enable hot reload of renderer settings that aren't already hot reload capable

---

src/inc/LibraryIncludes.h
src/inc/til/bitmap.h

`bitmap::_calculateArea` performance can be improved by leveraging the
optimized `find_first`/`find_next` methods instead of iterating through
the bitmap manually.

Improve bitmap::_calculateArea performance

---

src/renderer/dx/DxRenderer.cpp
src/renderer/dx/DxRenderer.hpp

I was told that the DeviceContext version supercedes the RenderTarget
one. This moves us to it so we can gain access to a higher level of
control over the various pieces in our pipeline as we continue to evolve
the renderer.
The underlying motivation here is to potentially use a
`ID2D1CommandList` to batch our commands and run them all later outside
the lock. That can only really be done with this more granular level of
control over the pipeline. So this moves to that in a single step that
is easily findable in history should we have problems
I discussed this with @NiklasBorson of the Direct2D/DirectWrite team as
well as with @DHowett before doing it.
Platform Update
Closes #6525

Use D2DDeviceContext and friends over D2DRenderTarget

---

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
src/cascadia/WindowsTerminal/NonClientIslandWindow.h

The `TerminalTrySetDarkTheme` function is a hack to make the window
borders dark. We do this to make the Windows Terminal look like other
UWP apps. If we do not do this, then the borders stay light, like other
Win32 apps that customize their title bar such as `explorer.exe` and
`regedit.exe`.
Previously, we only did it when the theme set was the dark theme. Now,
we always do it: the window border is always dark, like other UWP apps.

Always use the dark window borders

---

src/cascadia/TerminalApp/Tab.cpp

When the user double clicks on a tab, show the tab rename box
as if they right clicked on the tab and clicked on "Rename".
I added a handler for the `DoubleTapped` event on the tab view item
when we are constructing it for the tab (in `Tab::_MakeTabViewItem`).
The code for that handler was copied the "rename tab menu item" click
handler.
I did not extract the code into a member function because it is very
short (only 2 lines of code) and only used twice so it is not worth
it IMO.

Double-click a tab to rename it

---

doc/specs/#2046 - Command Palette.md
doc/specs/#2046 - Unified keybindings and commands, and synthesized action names.md

This is another iteration on the Command Palette spec, from #5674. These were some ideas that were tossed around by @DHowett, @cinnamon-msft and myself, formalized here. I proposed this as an addendum to the original spec, since I think the first made sense atomically, and this only makes sense as a set of changes to the original. I didn't want to go hacking up the original doc to add this set of changes. 
**There are two proposals in this spec - they should be viewed as two atomic units. They can be accepted or rejected independently. I'm suggesting we approve both. They work _together_. I'm realizing now that this is worded confusingly, and it's on me to fix that.**
> ## Abstract
> 
> This document is intended to serve as an addition to the [Command Palette Spec].
> While that spec is …

Spec for unified keybindings and commands, and synthesized action names

---

samples/ReadConsoleInputStream/ReadConsoleInputStream.cs
src/cascadia/TerminalApp/WslDistroGenerator.cpp
src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
src/host/CursorBlinker.cpp
src/interactivity/onecore/ConIoSrvComm.cpp
src/tools/U8U16Test/U8U16Test.cpp
src/tools/U8U16Test/main.cpp
src/tools/pixels/main.cpp

Many places in this codebase has an equality comparison to the boolean FALSE. This adds unneeded complexity as C and C++ has a NOT operand for use of these in if statements. This makes the code more readable in those areas.
One boolean being compared to FALSE was only used once, with the boolean name being "b", so it is better off not existing at all.
Unit Testing passed, compiler refactoring

Optimize booleans

---

src/buffer/out/UnicodeStorage.cpp
src/buffer/out/UnicodeStorage.hpp
src/buffer/out/textBuffer.cpp
src/cascadia/WpfTerminalControl/NativeMethods.cs
src/cascadia/WpfTerminalControl/TerminalContainer.cs
src/interactivity/win32/windowUiaProvider.hpp
src/types/ScreenInfoUiaProviderBase.h
src/types/inc/CodepointWidthDetector.hpp

Replace std::map with std::unordered_map when the order doesn't matter
and hash functions are provided. Simple optimizations, but I expect the
performance should be strictly better, especially for
CodepointWidthDetector.hpp.

Replace std::map with std::unordered_map

---

src/renderer/dx/CustomTextLayout.cpp
src/renderer/dx/CustomTextLayout.h

This reverts commit 94eab6e391a099814ce8f9a08c8cccf9f588b7d1.
We'll reintroduce this again after making sure it plays nicely with
recycling and box drawing glyphs.
Fixes #6488
Fixes #6664

Revert "Skip ... analysis when the ... text is simple (6206)"

---

src/cascadia/TerminalApp/TerminalPage.cpp

This workaround was suggested by @chingucoding in
microsoft/microsoft-ui-xaml#2711
Fixes #6570
microsoft/microsoft-ui-xaml#2711
#6570

When we add a new tab in compact mode, re-enforce Compact mode

---

src/cascadia/TerminalApp/defaults.json

Occasionally, we get users with corrupt PATH environment variables: they
can't lauch PowerShell, because for some reason it's dropped off their
PATH. We also get users who have stray applications named
`powershell.exe` just lying around in random system directories.
We can combat both of these issues by simply hardcoding where we expect
PowerShell and CMD to live. %SystemRoot% was chosen over %WINDIR%
because apparently (according to Stack Overflow), SystemPath is
read-only and WINDIR isn't.
Refs #6039, #4390, #4228 (powershell was not found)
Refs #4682, Fixes #6082 (stray powershell.exe)

Hardcode the paths to Windows PowerShell and CMD

---

src/renderer/dx/CustomTextLayout.cpp
src/renderer/dx/CustomTextLayout.h

Restores the simple text run analysis and skipping of most of the
shaping/layout steps. Corrects one of the fast-path steps to ensure that
offsets and clusters are assigned.
- Bug #6488 
- Bug #6664
- Simple run PR #6206 
- Simple run revert PR #6665
- Recycle glyph runs PR #6483
The "correction" functions, by which box drawing analysis is one of
them, is dependent on the steps coming before it properly assigning the
four main vectors of the text layout glyphs: indices, advances, offsets,
and clusters. When the fast path is identified by the code from #6206,
only two of those are fully updated: indices and advances. The offsets
doesn't tend to cause a problem because offsets are rarely used so
they're pretty much always 0 already (but this PR enforces that they're
zero for the simple/fast …

Restore simple text runs, correct for crashes

---

src/buffer/out/TextAttribute.cpp
src/buffer/out/TextAttribute.hpp
src/buffer/out/ut_textbuffer/TextAttributeTests.cpp
src/host/consoleInformation.cpp
src/host/getset.cpp
src/host/output.cpp
src/host/screenInfo.cpp
src/host/settings.cpp
src/host/settings.hpp
src/host/ut_host/ScreenBufferTests.cpp
src/inc/test/CommonState.hpp
src/interactivity/win32/menu.cpp

Essentially what this does is map the default legacy foreground and
background attributes (typically white on black) to the `IsDefault`
color type in the `TextColor` class. As a result, we can now initialize
the buffer for "legacy" shells (like PowerShell and cmd.exe) with
default colors, instead of white on black. This fixes the startup
rendering in conpty clients, which expect an initial default background
color. It also makes these colors update appropriately when the default
palette values change.
One complication in getting this to work, is that the console permits
users to change which color indices are designated as defaults, so we
can't assume they'll always be white on black. This means that the
legacy-to-`TextAttribute` conversion will need access to those default
values. …

Improve conpty rendering of default colors in legacy apps

---

src/tools/ColorTool/ColorTool/SchemeManager.cs
src/tools/ColorTool/ColorTool/SchemeParsers/ISchemeParser.cs
src/tools/ColorTool/ColorTool/SchemeParsers/IniSchemeParser.cs
src/tools/ColorTool/ColorTool/SchemeParsers/JsonParser.cs
src/tools/ColorTool/ColorTool/SchemeParsers/SchemeParserBase.cs
src/tools/ColorTool/ColorTool/SchemeParsers/XmlSchemeParser.cs

This PR fixes the scheme resolution bug outlined in #5326
The approach is as follows:
* In [SchemeManager.cs], find the first scheme parser that actually
successfully parses the scheme, as opposed to the existing code, which
finds the first scheme parser which _says it can parse the scheme_, as
that logic spuriously returns `true` currently. 
* In [XmlSchemeParser.cs] and [JsonParser.cs], ensure that the contents
of the file are read and the contents passed to XmlDocument.LoadXXX,
as this fails with an UriException on WSL otherwise.
* Remove `CanParse` as it is superfluous. The check for a valid scheme
parser should not just check an extension but also if the file exists
- this is best done by the `ParseScheme` function as it already
returns null on failure.
* Add `FileExtension` to the …

fix scheme name resolution, and schema load on WSL

---

src/cascadia/TerminalCore/TerminalDispatch.cpp
src/terminal/adapter/adaptDispatch.cpp

The VT reset operations `RIS` and `DECSTR` are implemented as a series
of steps, each of which could potentially fail. Currently these
operations abort as soon as an error is detected, which is particularly
problematic in conpty mode, where some steps deliberately "fail" to
indicate that they need to be "passed through" to the conpty client. As
a result, the reset won't be fully executed. This PR changes that
behaviour, so the error state is recorded for any failures, but the
subsequent steps are still run.
Originally the structure of these operations was of the form:
bool success = DoSomething();
if (success)
{
success = DoSomethingElse();
}
But I've now changed the code so it looks more like this:
bool success = DoSomething();
success = DoSomethingElse() && success;
This means that …

Don't abort early in VT reset operations if one of the steps fails

---

src/buffer/out/TextAttribute.cpp
src/buffer/out/TextAttribute.hpp
src/cascadia/TerminalCore/TerminalDispatchGraphics.cpp
src/host/ut_host/VtRendererTests.cpp
src/renderer/vt/VtSequences.cpp
src/renderer/vt/Xterm256Engine.cpp
src/renderer/vt/vtrenderer.hpp
src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/adaptDispatchGraphics.cpp
src/terminal/adapter/ut_adapter/adapterTest.cpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp

This PR adds support for the `SGR 53` and `SGR 55` escapes sequences,
which enable and disable the ANSI _overline_ graphic rendition
attribute, the equivalent of the console character attribute
`COMMON_LVB_GRID_HORIZONTAL`. When a character is output with this
attribute set, a horizontal line is rendered at the top of the character
cell.
To start with, I added `SetOverline` and `IsOverlined` methods to the
`TextAttribute` class, to set and get the legacy
`COMMON_LVB_GRID_HORIZONTAL` attribute. Technically there was already an
`IsTopHorizontalDisplayed` method, but I thought it more readable to add
a separate `IsOverlined` as an alias for that.
Then it was just a matter of adding calls to set and reset the attribute
in response to the `SGR 53` and `SGR 55` sequences in the …

Add support for the "overline" graphic rendition attribute

---

src/cascadia/TerminalApp/TabRowControl.xaml

The MUX TabView control has a uniquely-shaped [+] button.  TerminalApp
doesn't use it: instead, it has a SplitView button that is styled to
look like MUX's official button.  However, it doesn't get the button's
shape right.  This PR updates TerminalApp's custom button to look more
like MUX's.
The difference is that MUX only rounds the top two corners, and it uses
a bigger radius.  Without matching MUX's radius, the upper-left corner
of the button makes an awkward asymmetric divot with the abutting tab.
There's also a spot in the lower-left corner that just looks like
someone accidentally spilled a few pixels on the floor.
Current appearance before this PR:
New appearance with this PR:
Most important deltas highlighted with red circles:
Note that this PR does *not* attempt to fix the …

Update the shape of our custom NewTab button to match MUX's TabView button

---

src/cascadia/TerminalApp/TabRowControl.xaml

Update colors of our custom NewTab button to match MUX's TabView button
MUX has a NewTab button, but Terminal uses a homemade lookalike.  The
version in Terminal doesn't use the same brush color resources as MUX's
button, so it looks very slightly different.  This PR updates Terminal's
button to use the exact same colors that MUX uses.  I literally copied
these brush names out of MUX source code.
This is the color version of the layout fix #6766 
This is a prerequisite for fixing #5360
The real reason that this matters is that once you flip on
`ApplicationHighContrastAdjustment::None`, the existing colors will not
work at all.  The existing brushes are themed to black foreground on a
black background when High Contrast (HC) Black theme is enabled.  The
only thing that's saving you is …

Update colors of our custom NewTab button to match MUX's TabView

---

.github/actions/spell-check/expect/expect.txt
doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/ActionAndArgs.cpp
src/cascadia/TerminalApp/CommandKeyChordVisibilityConverter.cpp
src/cascadia/TerminalApp/CommandKeyChordVisibilityConverter.h
src/cascadia/TerminalApp/CommandKeyChordVisibilityConverter.idl
src/cascadia/TerminalApp/CommandPalette.xaml
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/defaults.json
src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj

In the wake of #6635, a couple things got missed in merges:
* `toggleRetroEffect` didn't get into the schema, nor did `renameTab` or
`commandPalette`.
* `toggleRetroEffect` also didn't get a name
Furthermore, I thought it might be a good idea to start sticking
commands into `bindings` even without `keys`. So I tried doing that for
`opentabColorPicker` and `toggleRetroEffect`, and found immediately that
the labels for the key chord still appear even when the text is empty.
So I added some XAML magic to hide those when the text is empty.
* #6762 
* #6691
* #6557 
* #6635 
* See also: https://docs.microsoft.com/en-us/windows/uwp/data-binding/data-binding-quickstart#formatting-or-converting-data-values-for-display
- make sure to switch to C++/WinRT …

Add actions missing in schema, descriptions for `toggleRetroEffect`

---

doc/building.md
src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
src/cascadia/TerminalApp/TerminalApp.vcxproj
src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/packages.config
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/cascadia/WindowsTerminal/packages.config
src/cascadia/WindowsTerminalUniversal/WindowsTerminalUniversal.vcxproj
src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj

See: https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.5.0-prerelease.200609001
> ### Notable Changes:
> 
>     Resize tab view items only once the pointer has left the TabViewItem strip (microsoft/microsoft-ui-xaml#2569)
>     Align TabView visuals with Edge (microsoft/microsoft-ui-xaml#2201)
>     Fix background of MenuFlyout in white high contrast (microsoft/microsoft-ui-xaml#2446)
>     TabView: Make TabViewItem consume the TabViewItemHeaderForeground theme resource (microsoft/microsoft-ui-xaml#2348)
>     TabView: Add tooltips to its scrolling buttons. (microsoft/microsoft-ui-xaml#2369)

Update MUX to 2.5.0-prerelease.200609001

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/CommandPalette.h

Pretty straightforward. Logs three scenarios:
* The user opened the command palette (and which mode it was opened in)
* The user ran a command from the palette
* The user dismissed the palette without running an action.
We discussed this in team sync yesterday.

Add some logging regarding command palette usage

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.xaml

WinUI's `Margin` and `Padding` work very similarly. `Margin` distances
ourselves from our parent. Whereas `Padding` distances our children from
ourselves.
Terminal's `padding` setting is actually implemented by defining
`Margin` on the SwapChainPanel. This means that the "padding" that is
created is actually belongs to SwapChainPanel's parent: Grid (not to be
confused with its parent, "RootGrid").
When a user clicks on the padded area, input goes to Grid. But there's a
twist: you can't actually hit Grid. To be able to hit Grid, you can't
just set IsHitTestVisible. You need to set it's Visibility to Visible,
and it's Background to Transparent (not null) [2].
- The SearchBox gets first dibs on the hit test so none gets through
to the SwapChainPanel
[1] …

Allow starting selections from padding area

---

.github/actions/spell-check/dictionary/microsoft.txt
src/cascadia/TerminalApp/App.cpp
src/cascadia/TerminalControl/SearchBoxControl.xaml

This PR enables `ApplicationHighContrastAdjustment::None`.  Doing this disables a set of mitigations in XAML designed to band-aid apps that were never explicitly designed for High Contrast (HC) modes.  Terminal now has full control of and responsibility for its appearance in HC mode.  This allows Terminal to look a lot better.
On paper, we should be able to set `HighContrastAdjustment="None"` on the `<Application>` element.  But that doesn't have any effect.  I don't know if this is a bug in `<Toolkit:XamlApplication>` or somewhere else.  So instead I set the property in codebehind, which is not as ideal, but does at least work.  I'd love to a way to move this into App.xaml.
The Find box had a couple stray styles to override the ToggleButton's foreground color.  With backplating removed, …

Make Terminal look great in High Contrast

---

src/renderer/vt/tracing.cpp
src/renderer/vt/tracing.hpp

Passes the bitmap by ref into the tracing function instead of making a copy on the way in. It's only read anyway for tracing (if enabled) so the copy was a pointless oversight.
- Observed WPR trace before and after with `time cat big.txt` in WSL.

Avoid copying the bitmap on the way into the tracing function

---

src/renderer/vt/paint.cpp
src/renderer/vt/state.cpp
src/renderer/vt/vtrenderer.hpp

A lot of time was spent between each individual line in the VT paint engine in allocating some scratch space to assemble the clusters then deallocating it only to have the next line do that again. Now we just hold onto that memory space since it should be approximately the size of a single line wide and will be used over and over and over as painting continues.
- Run `time cat big.txt` under WPR. Checked before and after perf metrics.

Cache VT buffer line string to avoid (de)alloc on every paint

---

src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
src/cascadia/TerminalAzBridge/TerminalAzBridge.vcxproj
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/cascadia/WindowsTerminalUniversal/WindowsTerminalUniversal.vcxproj
src/cppwinrt.build.pre.props

The main change in 16.7 is the separation of `AppContainerApplication`
into `WindowsStoreApp` and `WindowsAppContainer`. There's been a bit of
interest in splitting packaging away from containment, and this is the
first step in that direction.
We're a somewhat unique application, but as WinUI3 becomes more
prevalent we will become _less_ unique.
Some of these things, I've looked at and wondered how they ever worked.
Built locally and in CI. Tested the generated package with the package tester. Built on 16.6 and seen that it still seems to work.

Fix the build in VS 2019 16.7

---

src/buffer/out/search.cpp
src/buffer/out/search.h
src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/types/ScreenInfoUiaProviderBase.cpp
src/types/ScreenInfoUiaProviderBase.h

Looking up the size of the viewport from the underlying dimensions of
the structures seemed like a good idea at the time (so it would only be
in one place), but it turns out to be more of a perf cost than we
expected. Not necessarily on any one hot path, but if we sort by
functions in WPR, it was the top consumer on the Terminal side. This
instead saves the size as a member of the `TextBuffer` and serves that
out. It only changes when it is constructed or resized traditionally, so
it's easy to update/keep track of. It impacted conhost/conpty to a
lesser degree but was still noticeable.
- Run `time cat big.txt` under WPR. Checked before and after perf
metrics.

Cache the size viewport structure inside TextBuffer

---

src/cascadia/TerminalCore/ITerminalApi.hpp
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/cascadia/TerminalCore/TerminalDispatch.cpp
src/cascadia/TerminalCore/TerminalDispatch.hpp
src/cascadia/TerminalCore/terminalrenderdata.cpp
src/terminal/adapter/adaptDispatch.cpp

This PR adds full support for the `DECSCNM` reverse screen mode in the Windows Terminal to align with the implementation in conhost.
* The conhost implementation of `DECSCNM` was in PR #3817.
* WT originally inherited that functionality via the colors being passed through, but that behaviour was lost in PR #6506.
The `AdaptDispatch::SetScreenMode` now checks if it's in conpty mode and simply returns false to force a pass-through of the mode change. And the `TerminalDispatch` now has its own `SetScreenMode` implementation that tracks any changes to the reversed state, and triggers a redraw in the renderer.
To make the renderer work, we just needed to update the `GetForegroundColor` and `GetBackgroundColor` methods of the terminal's `IRenderData` implementation to check the reversed state, …

Add support for DECSCNM in Windows Terminal

---

src/interactivity/win32/windowio.cpp
src/terminal/adapter/ut_adapter/MouseInputTest.cpp
src/terminal/input/mouseInput.cpp
src/terminal/input/terminalInput.hpp
src/types/inc/utils.hpp

By storing up the accumulated delta in the mouse input handler, we can
enlighten both conhost and terminal about wheel events that are less
than one line in size. Previously, we had a workaround in conhost that
clamped small scroll deltas to a whole line, which made trackpad
scrolling unimaginably fast. Terminal didn't make this mistake, but it
also didn't handle delta accumulation . . . which resulted in the same
behavior.
MouseInput will now wait until it's received WHEEL_DELTA (well-known
constant, value 120) worth of scrolling delta before it dispatches a
single scroll event.
Future considerations may include sending multiple wheel button events
for every *multiple* of WHEEL_DELTA, but that would be a slightly larger
refactoring that I'm not yet ready to undertake.
There's a chance …

Account for WHEEL_DELTA when dispatching VT mouse wheel events

---

src/buffer/out/TextAttribute.cpp
src/buffer/out/TextAttribute.hpp
src/host/ApiRoutines.h
src/host/_stream.cpp
src/host/_stream.h
src/host/screenInfo.cpp
src/host/screenInfo.hpp
src/host/ut_host/ApiRoutinesTests.cpp
src/host/ut_host/ScreenBufferTests.cpp
src/host/ut_host/TextBufferTests.cpp
src/host/writeData.cpp
src/host/writeData.hpp
src/renderer/vt/paint.cpp
src/server/ApiDispatchers.cpp
src/server/ConsoleShimPolicy.cpp
src/server/ConsoleShimPolicy.h
src/server/IApiRoutines.h

There is going to be a very long tail of applications that will
explicitly request VT SGR 40/37 when what they really want is to
SetConsoleTextAttribute() with a black background/white foreground.
Instead of making those applications look bad (and therefore making us
look bad, because we're releasing this as an update to something that
"looks good" already), we're introducing this compatibility quirk.
Before the color reckoning in #6698 + #6506, *every* color was subject
to being spontaneously and erroneously turned into the default color.
Now, only the 16-color palette value that matches the active console
background/foreground color will be destroyed, and only when received
from specific applications.
Removal will be tracked by #6807.
Michael and I discussed what layer this quirk really …

Reintroduce a color compatibility hack, but only for PowerShells

---

src/buffer/out/TextAttribute.cpp
src/buffer/out/TextAttribute.hpp
src/buffer/out/TextColor.h
src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/buffer/out/ut_textbuffer/TextAttributeTests.cpp
src/cascadia/PublicTerminalCore/HwndTerminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalSelection.cpp
src/cascadia/TerminalCore/terminalrenderdata.cpp
src/host/renderData.cpp
src/host/renderData.hpp
src/host/settings.cpp
src/host/settings.hpp
src/host/ut_host/ScreenBufferTests.cpp
src/host/ut_host/TextBufferTests.cpp
src/interactivity/win32/Clipboard.cpp
src/renderer/base/renderer.cpp
src/renderer/dx/DxRenderer.cpp
src/renderer/gdi/paint.cpp
src/renderer/gdi/state.cpp
src/renderer/inc/IRenderData.hpp

This is a refactoring of the renderer color calculations to simplify the
implementation, and to make it easier to support additional
color-altering rendition attributes in the future (e.g. _faint_ and
_conceal_).
* This is a followup to PRs #3817 and #6809, which introduced additional
complexity in the color calculations, and which suggested the need for
refactoring. 
When we added support for `DECSCNM`, that required the foreground and
background color lookup methods to be able to return the opposite of
what was requested when the reversed mode was set. That made those
methods unnecessarily complicated, and I thought we could simplify them
considerably just by combining the calculations into a single method
that derived both colors at the same time.
And since both conhost and Windows …

Refactor the renderer color calculations

---

src/terminal/adapter/ITermDispatch.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/termDispatch.hpp
src/terminal/adapter/ut_adapter/adapterTest.cpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp
src/terminal/parser/telemetry.cpp
src/terminal/parser/telemetry.hpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp

This PR adds support for the `DA2` (Secondary Device Attributes) and
`DA3` (Tertiary Device Attributes) escape sequences, which are standard
VT queries reporting basic information about the terminal.
The _Secondary Device Attributes_ response is made up of a number of
parameters:
1. An identification code, for which I've used 0 to indicate that we
have the capabilities of a VT100 (using code 0 for this is an XTerm
convention, since technically DA2 would not have been supported by a
VT100).
2. A firmware revision level, which some terminal emulators use to
report their actual version number, but I thought it best we just
hardcode a value of 10 (the DEC convention for 1.0).
3. Additional hardware options, which tend to be device specific, but
I've followed the convention of the later DEC …

Add support for DA2 and DA3 device attributes reports

---

src/cascadia/TerminalApp/JsonUtilsNew.h

This commit updates JsonUtilsNew to support winrt
`Windows::Foundation::IReference<T>` as an option type, and cleans up the
optional support code by removing the optional overload on
`GetValue(...)`. Instead of using an overload with a partial
specialization, we're using a constexpr if with a type trait to
determine option-type-ness.
In addition, Carlos reported an issue with deriving from `FlagMapper`
(itself templated) and referring to the base type's members without
fully qualifying them. To make derivation easier, `EnumMapper` and
`FlagMapper` now provide `BaseEnumMapper` and `BaseFlagMapper` type
aliases.
I've taken the opportunity to add a `winrt::hstring` conversion
trait.
Lastly, in casual use, I found out that I'd written the til::color
converter wrong: it supports color strings …

Update JsonNew for IReference+cleaner optionals, and better Mappers

---

src/buffer/out/TextAttribute.cpp
src/buffer/out/TextAttribute.hpp
src/buffer/out/ut_textbuffer/TextAttributeTests.cpp
src/cascadia/TerminalCore/TerminalDispatchGraphics.cpp
src/host/ut_host/ScreenBufferTests.cpp
src/host/ut_host/VtRendererTests.cpp
src/inc/conattrs.hpp
src/renderer/vt/VtSequences.cpp
src/renderer/vt/Xterm256Engine.cpp
src/renderer/vt/vtrenderer.hpp
src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/adaptDispatchGraphics.cpp
src/terminal/adapter/ut_adapter/adapterTest.cpp

This PR adds support for the `SGR 2` escape sequence, which enables the
ANSI _faint_ graphic rendition attribute. When a character is output
with this attribute set, it uses a dimmer version of the active
foreground color.
There was already an `ExtendedAttributes::Faint` flag in the
`TextAttribute` class, but I needed to add `SetFaint` and `IsFaint`
methods to access that flag, and update the `SetGraphicsRendition`
methods of the two dispatchers to set the attribute on receipt of the
`SGR 2` sequence. I also had to update the existing `SGR 22` handler to
reset _Faint_ in addition to _Bold_, since they share the same reset
sequence. For that reason, I thought it a good idea to change the name
of the `SGR 22` enum to `NotBoldOrFaint`.
For the purpose of rendering, I've updated the …

Add support for the "faint" graphic rendition attribute

---

.github/actions/spell-check/dictionary/apis.txt
doc/cascadia/SettingsSchema.md
doc/cascadia/profiles.schema.json
src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
src/cascadia/TerminalApp/GlobalAppSettings.cpp
src/cascadia/TerminalApp/GlobalAppSettings.h
src/cascadia/TerminalApp/defaults-universal.json
src/cascadia/TerminalApp/defaults.json
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalSettings/ICoreSettings.idl
src/cascadia/TerminalSettings/TerminalSettings.cpp
src/cascadia/TerminalSettings/terminalsettings.h
src/cascadia/UnitTests_TerminalCore/MockTermSettings.h
src/inc/DefaultSettings.h

This parameter was added as a workaround for our fast trackpad
scrolling. Since that was fixed before 1.0 shipped, in #4554, it has
been largely vestigial. There is no reason for us to keep it around any
longer.
It was also the only "logic" in TerminalSettings, which is otherwise a
library that only transits data between two other libraries.
I have not removed it from the schema, as I do not want to mark folks'
settings files invalid to a strict schema parser.
While I was in the area, I added support for "scroll one screen at a
time" (which is represented by the API returning WHEEL_PAGESCROLL),
fixing #5610. We were also storing it in an int (whoops) instead of a
uint.
Fixes #5610

Remove the rowsToScroll setting and just always use the system setting

---

src/buffer/out/TextAttribute.cpp
src/buffer/out/ut_textbuffer/TextAttributeTests.cpp
src/terminal/adapter/ut_adapter/adapterTest.cpp

This PR adds support for the `SGR 8` and `SGR 28` escape sequences,
which enable and disable the _concealed/invisible_ graphic rendition
attribute. When a character is output with this attribute set, it is
rendered with the same foreground and background colors, so the text is
essentially invisible.
where discussion took place: #6876
Most of the framework for this attribute was already implemented, so it
was just a matter of updating the `TextAttribute::CalculateRgbColors`
method to make the foreground the same as the background when the
_Invisible_ flag was set. Note that this has to happen after the
_Reverse Video_ attribute is applied, so if you have white-on-black text
that is reversed and invisible, it should be all white, rather than all
black.
There were already existing SGR unit …

Add support for the "concealed" graphic rendition attribute

---

src/cascadia/TerminalApp/CommandPalette.xaml

Update the Palette to be readable under High Contrast mode
Regressed in #6833
I pulled the styling of the KeyChord text into a Style, so we can give it a different style under High Contrast.  Under HC, I just left all the colors at their default, so ListView can do its thing.  (IMHO, the HC style now looks better than the non-HC mode, but maybe I'm biased ;) )
| | Old | New |
|---|:---:|:---:|
| Light | ![light](https://user-images.githubusercontent.com/10259764/87398203-6b8f9a80-c56a-11ea-99d0-2eeefcfea269.png) | ![newlight](https://user-images.githubusercontent.com/10259764/87399212-e3aa9000-c56b-11ea-9e94-c8fae8825cd1.png) |
| Dark | ![dark](https://user-images.githubusercontent.com/10259764/87398269-819d5b00-c56a-11ea-9180-5c6ec1071b95.png) | …

Tweak the Palette's KeyChord for High Contrast mode

---

src/host/ut_host/VtIoTests.cpp
src/renderer/base/renderer.cpp
src/renderer/base/renderer.hpp

In `Renderer::TriggerRedraw`, the act of fetching the viewport from the
`pData` over and over is wasted time. We already have a cached variable
of the viewport that is updated on every scroll check (on
`TriggerScroll` and on `PaintFrame`.) Scrolling wouldn't be working
correctly if the clients weren't already notifying us that the viewport
has changed for scroll purposes, so we can just keep using that cached
value for the invalidation restriction to speed things up over fetching
it again.
- Run `time cat big.txt`. Checked average time before/after, WPR traces
before/after.

Cache the viewport to make invalidation faster

---

tools/bcz.cmd

Without this fix, you'd end up with an empty target variable, and so
msbuild would complain and tell you to give it a target.

Fix 'bcz exclusive' typo

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/CommandPalette.h

The command palette is a ListView of commands.  As you type into the
search box, commands are added or removed from the ListView.  Currently,
each update is done by completely clearing the backing list, then adding
back any items that should be displayed.  However, this defeats the
ListView's built-in animations: upon every keystroke, ListView displays
its list-clearing animation, then animates the insertion of every item
that wasn't deleted.  This results in noticeable flickering.
This PR changes the update logic so that it updates the list using
(roughly) the minimum number of Insert and Remove calls, so the ListView
makes smoother transitions as you type.
I implemented it by keeping the existing code that builds the filtered
list, but I changed it to build into a scratch list.  Then I …

Smooth animation of command palette filtering

---

NuGet.Config

After we stood up our own NuGet feed in Azure blob storage, Azure DevOps
came out with a public artifact feed feature. I've migrated all our
packages over, and the only thing left to do is switch our project's
NuGet config to use it.
Fixes #6952

Move to the TerminalDependencies NuGet feed

---

src/buffer/out/TextAttribute.cpp
src/buffer/out/TextAttribute.hpp
src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/cascadia/TerminalCore/TerminalDispatchGraphics.cpp
src/host/ut_host/ScreenBufferTests.cpp
src/host/ut_host/VtRendererTests.cpp
src/renderer/vt/VtSequences.cpp
src/renderer/vt/Xterm256Engine.cpp
src/renderer/vt/XtermEngine.cpp
src/renderer/vt/vtrenderer.hpp
src/terminal/adapter/adaptDispatchGraphics.cpp
src/terminal/adapter/ut_adapter/adapterTest.cpp

Text can have various attributes, such as "bold", "italic", "underlined", etc.  The TextAttribute class embodies this. It has methods to set/query these attributes.
This change tweaks a few of the method names to make them match. I.e. for an imaginary text property "Foo", we should have methods along the lines of:
```
IsFoo
SetFoo(bool isFoo)
```
And variations should match: we should have "Foo" and "OverFoo", not "Fooey" and "OverFoo".
I chose to standardize on the adjective form, since that's what we are closest to already. The attributes I attacked here are:
SetItalic**s** --> SetItalic
SetUnderline --> SetUnderline**d**
SetOverline --> SetOverline**d**
("italic" is an adjective; "italics" is a plural noun, representing letters or words in an italic typeface)
And I also added methods …

Tweaks: normalize TextAttribute method names (adjective form)

---

.github/actions/spell-check/patterns/patterns.txt
src/cascadia/TerminalControl/ThrottledFunc.cpp
src/renderer/base/thread.cpp

By default, the memory order on atomics is `seq_cst`. This is a relatively expensive ordering and it shows in situations where we're rapidly signaling a consumer to pick up something from a producer. I've instead attempted to switch these to `release` (producer) and `acquire` (consumer) to improve the performance of these signals. 
- Run `time cat big.txt` and `time cat ls.txt` under VS Performance Profiler.

Set memory order on slow atomics

---

src/cascadia/TerminalApp/CommandPalette.xaml

The command palette has some content that can overlap with its
scrollbar.  This PR adds a 16px gutter for the scrollbar, as recommended
[here](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/scroll-controls#:~:text=leave%2016px%20of%20padding%20on%20the%20edge%20of%20the%20viewport).
You can repro the overlap in the default configuration by grabbing the
scrollbar with the mouse pointer.  But there's an accessibility option
that makes this more obvious: Settings > Display > Automatically hide
scroll bars.  With that option enabled, the text is _always_
overlapping.
The gutter does look slightly larger than it needs to be when the
scrollbar is thin or completely hidden.  Dynamic reflow may help, but
unfortunately, I don't know enough XAML to wire that up.  MUX has …

Add gutter to Command Palette to avoid overlapping with scrollbar

---

src/types/UiaTextRangeBase.cpp

In UiaTextRange, `_getBufferSize` returns an optimized version of the
size of the buffer to be the origin and the last character in the
buffer. This is to improve performance on search or checking if you are
currently on the last word/line.
When setting the endpoint and drawing the bounding rectangles, we should
be retrieving the true buffer size. This is because it is still possible
to create UiaTextRanges that are outside of this optimized size. The
main source of this is `ExpandToEnclosingUnit()` when the unit is
`Document`. The end _should_ be the last visible character, but it isn't
because that would break our tests.
This is an incomplete solution. #6986 is a follow up to completely test
and implement the solution.
The crash in #6402 was caused by getting the document range (a range …

UIA: use full buffer comparison in rects and endpoint setter

---

src/cascadia/PublicTerminalCore/HwndTerminal.cpp
src/cascadia/PublicTerminalCore/HwndTerminal.hpp
src/cascadia/WpfTerminalControl/NativeMethods.cs
src/cascadia/WpfTerminalControl/TerminalContainer.cs

* send alt/F10 through the control
We were not listening for WM_SYSKEY{UP,DOWN}
* extract the actual scancode during WM_CHAR, not the bitfield
We were accidentally sending some of the additional keypress data in with
the character event in Win32 Input Mode
* set default fg/bg to campbell
The WPF control starts up in PowerShell blue even though it's not typically used
in PowerShell blue.
* don't rely on the font to determine wideness
This is a cross-port of #2928 to the WPF control
* deterministic shutdown
In testing, I saw a handful of crashes on teardown because we were not shutting
down the render thread properly.
* don't pass 10 for the font weight ...
When Cascadia Code is set, it just looks silly.
* trigger render when selection is cleared, do it under lock
Fixes #6966.

wpf: fix a handful of issues with the wpf control

---

src/cascadia/TerminalApp/TerminalPage.cpp

The outer window title was not updating correctly with tab renames, this change fixes that
Previously, upon changing tabs we would send up the title of the focused control, this change makes it so we send up the title of the focused tab instead.
Cannot reproduce the bug after this change.

Fixed window title not updating with tab rename

---

src/cascadia/TerminalCore/ITerminalApi.hpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/cascadia/TerminalCore/TerminalDispatch.cpp
src/cascadia/TerminalCore/TerminalDispatch.hpp

This was never hooked up to the TerminalCore implementation.
Closes #7102

Implement SetCursorColor in Terminal

---

src/cascadia/TerminalApp/TerminalPage.cpp

Allows splitting pane (with default settings) by holding down ALT and pressing the new tab button ('+')
Pretty much exactly the code added in #5928 (all credit to @carlos-zamora), but put at the new tab button event binding
Seems to work - holding ALT while pressing '+' opens a pane instead of a tab. Holding ALT while starting up terminal for the first time does not seem to affect the behaviour.

Implement split pane with new tab button

---

src/cascadia/PublicTerminalCore/HwndTerminal.cpp
src/cascadia/PublicTerminalCore/HwndTerminal.hpp
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/WpfTerminalControl/NativeMethods.cs
src/cascadia/WpfTerminalControl/TerminalContainer.cs

When we added support for win32 input mode, we neglected to pass
`ENHANCED_KEY` through the two surfaces that would generate events. This
broke arrow keys in much the same way was #2397, but in a different
layer.
While I was working on the WPF control, I took a moment to refactor the
message cracking out into a helper. It's a lot easier on the eyes than
four lines of bit shifting repeated three times.
Fixes #7074

Send ENHANCED_KEY in Win32 input mode in the wpf/uwp controls

---

src/renderer/base/renderer.cpp
src/terminal/adapter/ut_adapter/adapterTest.cpp

This PR adds support for the ANSI _crossed-out_ graphic rendition
attribute, which is enabled by the `SGR 9` escape sequence.
* Support for the escape sequences and storage of the attribute was
originally added in #2917.
* Support for drawing the strikethrough effect in the grid line renderer
was added in #7107.
Since the majority of the code required for this attribute had already
been implemented, it was just a matter of activating the
`GridLines::Strikethrough` style in the `Renderer::s_GetGridlines`
method when the `CrossedOut` attribute was set.
VALIDATION
There were already some unit tests in place in `VtRendererTest` and the
`ScreenBufferTests`, but I've also now extended the SGR tests in
`AdapterTest` to cover this attribute.
I've manually confirmed the first test case from #6205 …

Add support for the "crossed-out" graphic rendition attribute

---

src/buffer/out/TextAttribute.cpp
src/host/ft_uia/VirtualTerminalTests.cs
src/host/ut_host/TextBufferTests.cpp
src/inc/conattrs.hpp
src/renderer/base/renderer.cpp
src/terminal/adapter/ut_adapter/adapterTest.cpp
src/tools/vtapp/Program.cs

This PR updates the rendering of the _underlined_ graphic rendition
attribute, using the style specified in the active font, instead of just
reusing the grid line at the bottom of the character cell.
* Support for drawing the correct underline effect in the grid line
renderer was added in #7107.
There was already an `ExtendedAttributes` flag defined for the
underlined state, but I needed to update the `SetUnderlined` and
`IsUnderlined` methods in the `TextAttribute`  class to use that flag
now in place of the legacy `LVB_UNDERSCORE` attribute. This enables
underlines set via a VT sequence to be tracked separately from
`LVB_UNDERSCORE` grid lines set via the console API.
I then needed to update the `Renderer::s_GetGridlines` method to
activate the `GridLines::Underline` style when the …

Render the SGR "underlined" attribute in the style of the font

---

src/cascadia/TerminalApp/CommandPalette.cpp

Add some user research to determine what the average number of characters a user types before executing a cmdpal action.
This might need to be modified when it merges with #6732

Research how many characters users are typing before dismissing the cmdpal

---

src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
src/cascadia/LocalTests_TerminalApp/TabTests.cpp
src/cascadia/TerminalApp/CascadiaSettings.h
src/cascadia/TerminalApp/ColorScheme.cpp
src/cascadia/TerminalApp/ColorScheme.h
src/cascadia/TerminalApp/GlobalAppSettings.h
src/cascadia/TerminalApp/Pane.h
src/cascadia/TerminalApp/Profile.cpp
src/cascadia/TerminalApp/Profile.h
src/cascadia/TerminalApp/Tab.h
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalSettings.cpp
src/cascadia/TerminalApp/TerminalSettings.h
src/cascadia/TerminalApp/TerminalSettings.idl
src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj.filters
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl
src/cascadia/TerminalSettings/TerminalSettings.vcxproj

Move TerminalSettings object from TerminalSettings project
(Microsoft.Terminal.Settings) to TerminalApp project. `TerminalSettings`
specifically operates as a bridge that exposes any necessary information
to a TerminalControl.
Closes #7139 
Related Epic: #885
Related Spec: #6904
Deployed Windows Terminal and opened a few new tabs.

Move TerminalSettings object to TermApp Project

---

src/cascadia/PublicTerminalCore/HwndTerminal.cpp
src/cascadia/TerminalCore/Terminal.cpp
src/interactivity/win32/windowio.cpp

This pull request fixes capture and event generation in VT mouse mode
for both conhost and terminal.
Fixes #6401.
[1/3] Terminal: clamp mouse events to the viewport, don't throw them away
gnome-terminal (at least) sends mouse events whose x/y are at the
extreme ends of the buffer when a drag starts inside the terminal and
then exits it.
We would previously discard any mouse events that exited the borders of
the viewport. Now we will keep emitting events where X/Y=0/w/h.
[2/3] conhost: clamp VT mouse to viewport, capture pointer
This is the same as (1), but for conhost. conhost wasn't already
capturing the pointer when VT mouse mode was in use. By capturing, we
ensure that events that happen outside the screen still result in events
sent to an application (like a release after a drag) …

Fix VT mouse capture issues in Terminal and conhost

---

src/cascadia/PublicTerminalCore/HwndTerminal.cpp

I found this while crawling through conhost's WindowIo. Mouse wheel
events come in in screen coordinates, unlike literally every other mouse
event.
The WPF control was doing it wrong.

wpf: fixup mouse wheel events from screen coords

---

src/cppwinrt.build.pre.props

This fixes the build the rest of the way in VS 16.7. Something about the
way we were using the Store/Container flags caused some of our projects
to end up linking kernel32.lib only (MinimalCoreWin==KernelOnly).
The best way to solve it once and for all is to make sure MinimalCoreWin
is always set.
References 313568d0e5c.

Disable MinimalCoreWin when OpenConsoleUniversalApp is false

---

.github/actions/spell-check/expect/af1ff90dc512c83c902762b02f284c1c61603b4a.txt
.github/actions/spell-check/expect/expect.txt
src/renderer/dx/CustomTextLayout.cpp
src/renderer/dx/CustomTextLayout.h

Consecutive RTL GlyphRuns are drawn from the last to the first.
#538, #7149 , all those issues asking for RTL closed as dupes.
As @miniksa suggested in a comment on #7149 -- handle the thingy on the render side.
If we have GlyphRuns abcdEFGh, where EFG are RTL, we draw them now in order abcdGFEh.
This has ransom-noting, because I didn't touch the font scaling at all. This should fix the majority of RTL issues, except it *doesn't* fix issues with colors, because those get split in the TextBuffer phase in the renderer I think, so they show up separately by the GlyphRun phase.

Batch RTL runs to ensure proper draw order

---

src/buffer/out/TextAttribute.cpp
src/buffer/out/TextAttribute.hpp
src/cascadia/TerminalCore/TerminalDispatchGraphics.cpp
src/host/ut_host/ScreenBufferTests.cpp
src/host/ut_host/VtRendererTests.cpp
src/inc/conattrs.hpp
src/renderer/base/renderer.cpp
src/renderer/dx/DxRenderer.cpp
src/renderer/dx/DxRenderer.hpp
src/renderer/gdi/gdirenderer.hpp
src/renderer/gdi/paint.cpp
src/renderer/gdi/state.cpp
src/renderer/inc/IRenderEngine.hpp
src/renderer/vt/VtSequences.cpp
src/renderer/vt/Xterm256Engine.cpp
src/renderer/vt/vtrenderer.hpp
src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/adaptDispatchGraphics.cpp
src/terminal/adapter/ut_adapter/adapterTest.cpp

This PR adds support for the ANSI _doubly underlined_ graphic rendition
attribute, which is enabled by the `SGR 21` escape sequence.
There was already an `ExtendedAttributes::DoublyUnderlined` flag in the
`TextAttribute` class, but I needed to add `SetDoublyUnderlined` and
`IsDoublyUnderlined` methods to access that flag, and update the
`SetGraphicsRendition` methods of the two dispatchers to set the
attribute on receipt of the `SGR 21` sequence. I also had to update the
existing `SGR 24` handler to reset _DoublyUnderlined_ in addition to
_Underlined_, since they share the same reset sequence.
For the rendering, I've added a new grid line type, which essentially
just draws an additional line with the same thickness as the regular
underline, but slightly below it - I found a gap of around …

Add support for the "doubly underlined" graphic rendition attribute

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/JsonUtils.h
src/cascadia/TerminalApp/Profile.cpp

We're expecting that people have treated `padding` as an integer, and the type-based converter is too strict for that. This PR widens its scope and explicitly allows for it in the schema.

Allow profile.padding to be an int (or any other type :|)

---

src/cascadia/TerminalApp/CascadiaSettings.cpp
src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalApp/GlobalAppSettings.cpp
src/cascadia/TerminalApp/GlobalAppSettings.h

The "default profile as name" feature in 1.1 broke the loading of
default settings, as we would never get to the validation phase where
the default profile string was transformed into a guid.
I moved knowledge of the "unparsed default profile" optional to the
consumer so that we could make sure we only attempted to deserialize it
once (and only if it was present.)
Fixes #7236.

Resolve the default profile during defaults load, don't crash on launch

---

src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/CascadiaSettings.h
src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalApp/JsonUtils.h
src/cascadia/TerminalApp/TerminalSettingsSerializationHelpers.h
src/cascadia/ut_app/JsonUtilsTests.cpp

This pull request completes (and somewhat rewrites) the JsonUtils error
handling arc. Deserialization errors, no longer represented by trees of
exceptions that must be rethrown and caught, are now transformed at
catch time into a message explaining what we expected and where we
expected it.
Instead of exception trees, a deserialization failure will result in a
single type of exception with the originating JSON object from which we
can determine the contents and location of the failure.
Because most of the error message actually comes from the JSON schema
or the actual supported types, and the other jsoncpp errors are not
localized I've made the decision to **not** localize these messages.

Display meaningful errors when JSON types don't match

---

src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/UnitTests_TerminalCore/TerminalBufferTests.cpp

If you scroll up to view the scrollback, then we want the viewport to
"stay in place", as new output comes in (see #6062). This works fine up
until the buffer circles. In this case, the mutable viewport isn't
actually moving, so we never set `updatedViewport` to true. 
This regressed in #6062
Closes #7222

Fix viewport moving when we've scrolled up and circled the buffer

---

.github/actions/spell-check/expect/expect.txt
tools/Get-OSSConhostLog.ps1

This script takes a range of commits and generates a commit log with the
git2git-excluded file changes filtered out.
It also replaces GitHub issue numbers with GH-XXX so as to not confuse
Git2Git or Azure DevOps.  Community contributions are tagged with CC- so
they can be detected later.
The output looks like this:
```
Carlos Zamora (2)
* Pass mouse button state into HandleMouse instead of asking win32 (GH-6765)
Dustin L. Howett (6)
* Disable MinimalCoreWin when OpenConsoleUniversalApp is false (GH-7203)
James Holderness (1)
* Add support for the "doubly underlined" graphic rendition attribute (CC-7223)
```
Yes, the numbers are wrong. No, it doesn't really matter.

tools: add Get-OSSConhostLog

---

src/cascadia/TerminalCore/lib/terminalcore-lib.vcxproj

This regressed around the #7163 timeframe.
We're discussing this on chat currently. It might break the intellisense
on the `#include <winrt/Microsoft.Terminal.TerminalControl.h>` line in
VS 16.7, but we're not _really_ sure? Intellisense has been notoriously
flaky for us.
I'm running 16.6.5, and it works for me. @lhecker is running 16.7 and
confirmed it worked there. If the CI build passes, then this definitely
will work for 16.7.

Enable partial rebuilds of the TerminalControl project again

---

.github/actions/spell-check/dictionary/apis.txt
src/cascadia/TerminalConnection/ConptyConnection.cpp
src/types/Environment.cpp
src/types/inc/Environment.hpp
src/types/precomp.h

This commit ensures that we always furnish a new process with the
cleanest, most up-to-date environment variables we can. There is a minor
cost here in that WT will no longer pass environment variables that it
itself inherited to its child processes.
This could be considered a reasonable sacrifice. It will also remove
somebody else's TERM, TERM_PROGRAM and TERM_PROGRAM_VERSION from the
environment, which could be considered a win.
I validated  that GetCurrentProcessToken returns a token we're
_technically able_ to use with this API; it is roughly equivalent to
OpenProcessToken(GetCurrentProcess) in that it returns the current
active _access token_ (which is what CreateEnvironmentBlock wants.)
There's been discussion about doing a 3-way merge between WT's
environment and the new one. This …

Always create a new environment block before we spawn a process

---

src/cascadia/TerminalApp/CommandPalette.cpp

Whoops, members are zero initialized in Debug builds but most likely not
in Release builds So, this PR adds a couple of default values to
`_currentMode` and its associated XAML strings to make cmdpal/ats work
deterministically on first use.  I also added a default value to
`_anchorKey` just to be safe.
Closes #7254

Default initialize a CmdPal mode

---

src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/Tab.cpp
src/cascadia/TerminalApp/Tab.h

This is a minor fix from #6989. If there's only one pane in the
Terminal, then we'd still "zoom" it and give it a border, but all the
borders would be black. 
A single pane is already "zoomed", so it doesn't really make sense to
try and zoom if there's only one.

Don't zoom when there's only one pane

---

src/cascadia/TerminalApp/CommandPalette.cpp

Removes the if-statement in `UpdateTabIndices` that blocks all scenarios where you delete the second to last tab. This fixes the issue where the ATS gets confused about which item in the ListView is associated with which tab.
Closes #7278

Remove unnecessary check when updating ATS indices

---

src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/IDirectKeyListener.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h
src/cascadia/WindowsTerminal/main.cpp

#7145 introduced a check so that we wouldn't dispatch keys unless they
actually had a scancode. Our synthetic events actually _didn't_ have
scancodes. Not because they couldn't--just because they didn't.
Fixes #7297

Pass the scancode in our tunneled DirectKey event

---

src/cascadia/LocalTests_TerminalApp/ColorSchemeTests.cpp
src/cascadia/TerminalApp/CascadiaSettings.cpp
src/cascadia/TerminalApp/CascadiaSettings.h
src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalApp/ColorScheme.cpp
src/cascadia/TerminalApp/ColorScheme.h
src/cascadia/TerminalApp/ColorScheme.idl
src/cascadia/TerminalApp/GlobalAppSettings.cpp
src/cascadia/TerminalApp/GlobalAppSettings.h
src/cascadia/TerminalApp/Profile.h
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj.filters
src/cascadia/ut_app/JsonTests.cpp
src/cascadia/ut_app/precomp.h

ColorScheme is now a WinRT object in the TerminalApp project.
#7141 - ColorScheme is a settings object
#885 - this new settings object will be moved to a new TerminalSettingsModel project
All of the JSON stuff can't be exposed via the idl. So the plan here is that we'll have the TerminalSettingsModel project handle all of the serialization when it's moved over. These functions will be exposed off of the `implementation` namespace, not projected namespace.

Make ColorScheme a WinRT object

---

build/pipelines/templates/build-console-steps.yml
src/common.build.post.props

The build now builds every project multiple times, so I figure, why not
try to fix it.

Disable parallel build (again) and keep TerminalApp PCHs

---

src/cascadia/TerminalApp/ColorPickupFlyout.xaml

Deployed locally and verified that the colour picker's button has round edges.
Closes #7142

Update colour picker buttons with round edges.

---

src/buffer/out/UnicodeStorage.cpp
src/buffer/out/UnicodeStorage.hpp
src/cascadia/PublicTerminalCore/HwndTerminal.cpp
src/cascadia/TerminalConnection/init.cpp
src/inc/til/bitmap.h
src/renderer/dx/DxRenderer.cpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/terminalOutput.cpp
src/terminal/input/mouseInput.cpp
src/terminal/input/terminalInput.cpp
src/terminal/parser/InputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/base64.cpp

New warnings were added in VS 16.7 and `std::map::erase` is now `noexcept`.
Update our code to be compatible with the new enforcement.

Compensate for new warnings and STL changes in VS 16.7

---

src/inc/til/static_map.h
src/til/ut_til/StaticMapTests.cpp
src/til/ut_til/til.unit.tests.vcxproj
src/til/ut_til/til.unit.tests.vcxproj.filters

This is based on (cribbed almost directly from) code written by the
inimitable @StephanTLavavej on one of our mailing lists.
This is a nice generic version of the approach used in
JsonUtils::EnumMapper and CodepointWidthDetector: a static array of
key-value pairs that we binary-search at runtime (or at compile time, as
the case may be.)
Keys are not required to be sorted, as we're taking advantage of
constexpr std::sort (VS 16.6+) to get the compiler to do it for us. How
cool is that?
static_map presents an operator[] or at much like
std::map/std::unordered_map does.
I've added some tests, but they're practically fully-solveable at compile
time so they pretty much act like `VERIFY_IS_TRUE(true)`.

Add til::static_map, a constexpr key-value store

---

README.md

This adds an (unofficial) installation method for Scoop package manager users. Many developers using Windows (me included) use and love Scoop, so this would be a nifty addition to the Readme.
Made changes to README.md file.

Add Scoop (unofficial) installation method

---

.github/actions/spell-check/expect/expect.txt
src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/ITermDispatch.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/termDispatch.hpp
src/terminal/adapter/terminalOutput.cpp
src/terminal/adapter/terminalOutput.hpp
src/terminal/parser/IStateMachineEngine.hpp
src/terminal/parser/InputStateMachineEngine.cpp
src/terminal/parser/InputStateMachineEngine.hpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp
src/terminal/parser/stateMachine.cpp
src/terminal/parser/stateMachine.hpp
src/terminal/parser/ut_parser/InputEngineTest.cpp
src/terminal/parser/ut_parser/StateMachineTest.cpp

This PR changes the way VT control sequences are identified and
dispatched, to be more efficient and easier to extend. Instead of
parsing the intermediate characters into a vector, and then having to
identify a sequence using both that vector and the final char, we now
use just a single `uint64_t` value as the identifier.
The way the identifier is constructed is by taking the private parameter
prefix, each of the intermediate characters, and then the final
character, and shifting them into a 64-bit integer one byte at a time,
in reverse order. For example, the `DECTLTC` control has a private
parameter prefix of `?`, one intermediate of `'`, and a final character
of `s`. The ASCII values of those characters are `0x3F`, `0x27`, and
`0x73` respectively, and reversing them gets you 0x73273F, …

Refactor VT control sequence identification

---

src/cascadia/PublicTerminalCore/HwndTerminal.cpp
src/cascadia/PublicTerminalCore/HwndTerminal.hpp
src/cascadia/WpfTerminalControl/TerminalTheme.cs
src/renderer/dx/DxRenderer.cpp
src/renderer/dx/DxRenderer.hpp

Adds the ability to set the selection background opacity when setting the selection background. This also exposes the selection background and alpha through the terminal WPF container.
Patched VS and ran the terminal tool window with multiple selection background colors and alphas.

Expose selection background and alpha through the WPF control

---

src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
src/cascadia/TerminalApp/Command.cpp
src/cascadia/TerminalApp/Command.h
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/SettingsTypes.h
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalSettingsSerializationHelpers.h
src/cascadia/TerminalApp/defaults.json

Allows for creating commands that iterate over the user's color schemes. Also adds a top-level nested command to `defaults.json` that allows the user to select a color scheme (pictured above). I'm not sure there are really any other use cases that make sense, but it _really_ makes sense for this one.
* #5400 - cmdpal megathread
* made possible by #6856, _and support from viewers like you._
* All this is being done in pursuit of #6689 
Most of the hard work for this was already done in #6856. This is just another thing to iterate over.
* Played with this default command. It works great.
* Added tests.

Add support for commands iterable on color schemes

---

build/pipelines/templates/build-console-ci.yml
build/pipelines/templates/helix-processtestresults-job.yml

Activating a template doesn't actually process conditions. Only jobs, stages, and tasks can process a condition. So specify the full condition in the parent template call as a parameter and ask the child job (who can actually evaluate the condition) to use that parameter to determine if it should run.

Set ProcessTestResults job to use conditions specified in parent

---

src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
src/cascadia/TerminalApp/GlobalAppSettings.cpp
src/cascadia/TerminalApp/defaults-universal.json
src/cascadia/TerminalApp/defaults.json

In #6532, we thought it would be a good idea to add "bindings" as an
overload for "keybindings", as we were no longer going to use the
keybindings array for just keybindings. We were going to add commands.
So we started secretly treating `"bindings"` the same as
`"keybindings"`.
Then, in #7175, we discussed using "actions" as the key for the list of
commands/keybindings/global actions, instead of using "bindings". We're
going to be using this array as the global list of all actions, so it
makes sense to just call it `"actions"`. 
This PR renames "bindings" to "actions". Fortunately, we never
documented the "bindings" overload in the first place, so we can get
away with this safely, and preferably before we ship "bindings" for too
long.
References #6899

Replace "bindings" with "actions"

---

src/cascadia/TerminalApp/TerminalPage.cpp

Update profile shortcut based on profiles defined.
1. Removed hard-coded value (9).
Added more profiles and able to create new tab.
Note: This binding doesn't work tho ```{ "command": { "action": "newTab", "index": 10 }, "keys": "ctrl+shift+0" }```

Make sure we check to profile shortcuts with an index >9

---

src/buffer/out/UnicodeStorage.cpp
src/buffer/out/UnicodeStorage.hpp

This is just the `noexcept` part of #7319, because the CI apparently got updated overnight.

Compensate for VS 16.7, part 2

---

src/cascadia/TerminalApp/defaults-universal.json
src/cascadia/TerminalApp/defaults.json

Bind the command palette to <kbd>Ctrl+Shift+P</kbd> by default, to enable it for all users in v1.3

Bind the command palette by default

---

src/cascadia/TerminalControl/TermControl.cpp

Most applications with scrollable content seem to define the "large
jump" distance as about a screenful of content. You can see this in long
pages in Settings and documents in Notepad.
We just weren't configuring ScrollBar here.
Fixes #7367

TermControl: set the scrollbar jump distance to one screenful

---

src/types/convert.cpp

When the console functional tests are running on OneCoreUAP, the
newly-introduced (65bd4e327, #4309) FillOutputCharacterA tests will
actually fail because of radio interference on the return value of GLE.
Fixes MSFT-28163465

Clear the last error before calling Mb2Wc in ConvertToW

---

src/cascadia/TerminalCore/Terminal.cpp

Previously, if `altGrAliasing` was disabled, all `Ctrl+Alt` combinations were considered to be aliases of `AltGr` including `AltGr` itself and thus considered as key and not character events. But `AltGr` should not be treated as an alias of itself of course, as that prevents one from entering `AltGr` combinations entirely.
* Activate a German keyboard layout
* Run `showkey -a` in WSL
* **Ensure** that `AltGr+Q` produces `@`
* **Ensure** that `Ctrl+Alt+Q` produces `@`
* Disable `altGrAliasing`
* **Ensure** that `AltGr+Q` produces `@`
* **Ensure** that `Ctrl+Alt+Q` produces `^[^Q`

Fixed #7372: Setting "altGrAliasing" to "false" disables AltGr

---

src/types/Environment.cpp

This fixes a regression in environment variable loading introduced as part
of the new environment block creation that prevents some system-defined,
volatile environment variables from being defined.
https://github.com/microsoft/terminal/pull/7243#discussion_r476603599
Manually verified locally.
Closes #7399

Fix environment block creation

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/ActionArgs.cpp
src/cascadia/TerminalApp/ActionArgs.h
src/cascadia/TerminalApp/ActionArgs.idl
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/defaults.json

The `index` action argument is now optional for `closeOtherTabs` and `closeTabsAfter`. When `index` is not defined, `index` is set to the focused tab's index.
Also, adds the non-index version of these actions to defaults.json.
Opened 4 tabs and ran closeOtherTabs/closeTabsAfter from command palette.

Make index in closeOtherTabs and closeTabsAfter optional

---

doc/cascadia/profiles.schema.json

`setColorScheme` should require `colorScheme` rather than `name`

Fix schema for `setColorScheme`

---

src/cascadia/LocalTests_TerminalApp/ColorSchemeTests.cpp
src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/AppLogic.idl
src/cascadia/TerminalApp/CascadiaSettings.cpp
src/cascadia/TerminalApp/CascadiaSettings.h
src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalApp/Command.h
src/cascadia/TerminalApp/GlobalAppSettings.cpp
src/cascadia/TerminalApp/GlobalAppSettings.h
src/cascadia/TerminalApp/GlobalAppSettings.idl
src/cascadia/TerminalApp/Profile.cpp
src/cascadia/TerminalApp/Profile.h
src/cascadia/TerminalApp/Profile.idl
src/cascadia/TerminalApp/SettingsTypes.h
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/TerminalAppLib.vcxproj.filters
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalSettingsSerializationHelpers.h
src/cascadia/WindowsTerminal/AppHost.cpp

GlobalAppSettings is now a WinRT object in the TerminalApp project.
#7141 - GlobalAppSettings is a settings object
#885 - this new settings object will be moved to a new TerminalSettingsModel project
This one was probably the easiest thus far.
The only weird thing is how we handle InitialPosition. Today, we lose a
little bit of fidelity when we convert from LaunchPosition (int) -->
Point (float) --> RECT (long). The current change converts
LaunchPosition (optional<long>) --> InitialPosition (long) --> RECT
(long).
NOTE: Though I could use LaunchPosition to go directly from TermApp to
AppHost, I decided to introduce InitialPosition because LaunchPosition
will be a part of TerminalSettingsModel soon.

Make GlobalAppSettings a WinRT object

---

src/types/UiaTextRangeBase.cpp

When attempting to select a text range from a different text buffer (such as a standard text range when in alt mode), conhost crashes. This PR checks for this case and returns `E_FAIL` instead, preventing this crash.
Ran the following lines in the NVDA Python console (NVDA+control+z) before and after this PR, and observed that Conhost no longer crashes after the change:
``` Python console
>>> # SSH to a remote Linux system
>>> ti=nav.makeTextInfo("caret")
>>> ti.move("line", -2)
-2
>>> # Switch away from the NVDA Python console, and run Nano in conhost. Then:
>>> ti.updateSelection() # Calls select() on the underlying UIA text range
Traceback (most recent call last):
File "<console>", line 1, in <module>
File "NVDAObjects\UIA\__init__.pyc", line 790, in updateSelection
File …
```

Prevent crash when attempting to select an out-of-bounds UIA text range

---

.github/actions/spell-check/dictionary/microsoft.txt
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/Jumplist.cpp
src/cascadia/TerminalApp/Jumplist.h
src/cascadia/TerminalApp/TerminalAppLib.vcxproj

This commit introduces Jumplist customization and an item for each
profile to the Jumplist. Selecting an entry in the jumplist will pretty
much just execute  `wt.exe -p "{profile guid}"`, and so a new Terminal
will open with the selected profile.
Closes #576

Add profiles to the Jumplist

---

src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/dll/TerminalApp.vcxproj
src/cascadia/TerminalApp/packages.config
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/cascadia/WindowsTerminal/packages.config
src/cascadia/WindowsTerminalUniversal/WindowsTerminalUniversal.vcxproj
src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj

Update the WinUI version which allows us to remove the workaround.
Closes #6681

Update to a newer MUX prerelease; remove workaround for compact sizing

---

doc/building.md

The versions used [here](https://github.com/microsoft/terminal/blob/master/doc/building.md#updating-nuget-package-references) are not good examples for two reasons:
- The old version is higher than the new version
- They refered to actual versions meaning they would be picked up by the script
N/A

docs: use unlikely example versions in nuget package script

---

src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
src/types/UiaTextRangeBase.cpp

Conhost expands UIA text ranges when moved. This means that degenerate
ranges become non-degenerate after movement, leading to odd behaviour
from UIA clients. This PR doesn't expand degenerate ranges, but rather
keeps them degenerate by moving `_end` to the newly-changed `_start`.
Tested in the NVDA Python console (cases with `setEndPoint` and
`compareEndPoints` described in #7342). Also ran the logic by
@michaeldcurran.
Closes #7342
Almost definitely addresses nvaccess/nvda#11288 (although I'll need to
test with my Braille display). Also fixes an issue privately reported to
me by @simon818 with copy/paste from review cursor which originally lead
me to believe the issue was with `moveEndPointByRange`.

Keep degenerate UIA text ranges degenerate after movement

---

src/cascadia/TerminalApp/Jumplist.cpp

By setting the jumplist entries to launch `WindowsTerminal.exe` out of
the package root, we've inadvertently made WindowsTerminalDev emit jump
list entries that launch the _unpackaged_ version of Terminal.
We can fix this by copying the code from the shell extension that
determines which version of the executable to launch -- wt, wtd or
WindowsTerminal -- depending on the context under which it was invoked.
Fixes #7554

jumplist: prefer the app execution alias in %LOCALAPPDATA%

---

src/cascadia/TerminalApp/AzureCloudShellGenerator.cpp

Removed Acrylic Opacity from AzureCloudShellGenerator.

Remove AcrylicOpacity from AzureCloudShellGenerator

---

src/cascadia/LocalTests_TerminalApp/ColorSchemeTests.cpp
src/cascadia/LocalTests_TerminalApp/ProfileTests.cpp
src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
src/cascadia/LocalTests_TerminalApp/TabTests.cpp
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/CascadiaSettings.cpp
src/cascadia/TerminalApp/CascadiaSettings.h
src/cascadia/TerminalApp/CascadiaSettings.idl
src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalApp/Command.cpp
src/cascadia/TerminalApp/Command.h
src/cascadia/TerminalApp/Jumplist.cpp
src/cascadia/TerminalApp/Jumplist.h
src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/ut_app/DynamicProfileTests.cpp

CascadiaSettings is now a WinRT object in the TerminalApp project.
#7141 - CascadiaSettings is a settings object
#885 - this new settings object will be moved to a new TerminalSettingsModel project
This one _looks_ big, but most of it is really just propagating the
changes to the tests. In fact, you can probably save yourself some time
because the tests were about an hour of Find&Replace.
`CascadiaSettings::GetCurrentAppSettings()` was only being used in
Pane.cpp. So I ripped out the 3 lines of code and stuffed them in there.
Follow-up work:
- There's a few places in AppLogic where I `get_self` to be able to get
the warnings out. This will go away in the next PR (wrapping up #885)
Closes #7141

Make CascadiaSettings a WinRT object

---

src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/ConptyConnection.h

This commit leverages C++/WinRT's final_release [extension point] to
pull the final destruction of ConptyConnection off onto a background
thread.
We've been seeing some deadlocks during teardown where the output thread
(holding the last owning reference to the connection) was trying to
destruct the threadpool wait while the threadpool wait was
simultaneously running its callback and waiting for the output thread to
terminate. It turns out that trying to release a threadpool wait while
it's running a callback that's blocked on you will absolutely result in
a deadlock.
Fixes #7392.
[extension point]: https://devblogs.microsoft.com/oldnewthing/20191018-00/?p=103010

Destruct ConptyConnection on a background thread

---

.github/actions/spell-check/dictionary/microsoft.txt
src/host/directio.cpp
src/host/directio.h
src/host/outputStream.cpp
src/host/outputStream.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/conGetSet.hpp
src/terminal/adapter/ut_adapter/adapterTest.cpp

This fixes an issue where two CPRs could end up corrupted in the input
buffer. An application that sent two CPRs back-to-back could
end up reading the first few characters of the first prepended CPR
before handing us another CPR. We would dutifully prepend it to the
buffer, causing them to overlap.
```
^[^[2;2R[1;1R
^^      ^^^^^ First CPR
^^^^^^ Second CPR
```
The end result of this corruption is that a requesting application
would receive an unbidden `R` on stdin; for vim, this would trigger
replace mode immediately on startup.
Response prepending was implemented in !997738 without much comment.
There's very little in the way of audit trail as to why we switched.
Michael believes that we wanted to make sure that applications got DSR
responses immediately. It had the unfortunate side …

Switch all DSR responses to appending instead of prepending

---

oss/xorg_apps_rgb/MAINTAINER_README.md
oss/xorg_apps_rgb/cgmanifest.json

We will want to add support for the x11 color names.
The name table is are MIT-licensed by the X.org Foundation.

oss: add a manifest for x11's rgb database

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.xaml

If a user clicks a link that is either invalid (cannot be parsed) or has a scheme we do not support (like file or mailto (for now)), we open up a dialog box telling them the issue.
#5001

Open up content dialogs for invalid URIs and unsupported schemes

---

src/renderer/vt/paint.cpp

Fix OSC8 termination over the PTY after SGR 0

---

src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp

This fixes a typo in the `HyperlinkIdConsistency` unit test which was causing that test to fail. It was mistakenly using a `/` instead of `\` for the string terminator sequences.
The test initially worked because of a bug in the state machine parser, but that bug was recently fixed in PR #7340.
I've run the test again and it now passes.

Fix failing HyperlinkIdConsistency unit test

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/CommandPalette.h
src/cascadia/TerminalApp/Tab.cpp
src/cascadia/TerminalApp/Tab.h
src/cascadia/TerminalApp/Tab.idl
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

Currently, `CommandPalette` creates and maintains the `SwitchToTab`
commands used for the ATS. When `Command` goes into the
TerminalSettingsModel, the palette won't be able to access `Command`'s
implementation type, making it difficult for `CommandPalette` to tell
`Command` to listen to `Tab` for changes.
This PR changes the relationship up so `Tab` now manages its
`SwitchToTab` command, and `CommandPalette` just plops the command from
`Tab` into its list.

Give Tab ownership of its SwitchToTab command

---

.github/actions/spell-check/expect/expect.txt
src/host/conimeinfo.cpp
src/host/convarea.cpp

Some IME implementations do not produce composition strings, and their
users have come to rely on the cursor that conhost traditionally left on
until a composition string showed up. We shouldn't hide the cursor until
we get a string (as opposed to hiding it when composition begins) so as
to not break those IMEs.
Related to #6207.
Fixes MSFT:29219348

Make sure we don't hide the cursor until the IME starts

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/ActionAndArgs.cpp
src/cascadia/TerminalApp/defaults.json

Disable `togglePaneZoom` as a binding. Remove it from defaults.json and the schema.
#7252 - re-enable this binding when this blocking bug is resolved
Successful deployment

[1.3 STABLE ONLY] Unbind `togglePaneZoom`

---

src/cascadia/TerminalApp/TerminalPage.xaml

It looks much better this way.

Wrap the textblock containing the "invalid" URI

---

src/cascadia/TerminalApp/Jumplist.cpp

DestListLogoUri cannot handle paths that are separated with / unless
they're actually URLs. We have to guess somewhat whether something is a
file path and if it appears to be one, normalize it.
Fixes #7706

Normalize file paths before handing them to the jumplist

---

src/host/screenInfo.cpp

Sometimes when we were sliding the viewport to fit inside the buffer, we
would end up with left > right.
That would cause us to crash down the line when rendering.
Fixes MSFT:28387423.
Fixes #7744.
Manual run through 100% repro test case.

When win32 is resizing the viewport, make sure Right > Left

---

src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/host/ut_host/TextBufferTests.cpp
src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp

This fixes a bug when moving backwards by word that resulted in #7742.
This also includes...
- a minor refactor that leverages `GetWordStart` in `MoveToPreviousWord`
- additional unit tests for movement by word
- a feature test comprised of the referenced bug report
`MoveToPreviousWord()` would...
- move backwards for each whitespace character
- then, move backwards for each regular character
This would actually result in moving to the beginning of the current "word" (as defined by a11y).
We actually need to do this process twice:
- the first time gets you to the beginning of the current word
- attempt to move back by one character
- the second time gets you to the beginning of the previous word
Rather than implementing 4 while loops, we leverage `GetWordStart()` to
attempt to move to the …

Fix and test TextBuffer::MoveToPreviousWord()

---

build/pipelines/templates/build-console-steps.yml
src/cascadia/TerminalAzBridge/TerminalAzBridge.vcxproj
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj

The WAP packaging project is sensitive to including applications that it
thinks are UWPs. The changes we made to separate WindowsStoreApp and
WindowsAppContainer weren't comprehensive enough to convince WAP that we
were not still UWPs.
Because of that, it would run sub-builds of each of these projects (and
all their dependencies) with an additional `GenerateAppxPackageOnBuild`
property set. The existence of this property caused MSBuild to think the
projects needed to be built *again*.

Fix parallel builds by specifying the application type for WAP

---

src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp

This performs a minor refactor on `TextBuffer::MoveToNextWord` that
relies more heavily on `TextBuffer::GetWordEnd`. Now, the logic is
simplified and looks more like `MoveToPreviousWord`.
This refactor required me to move the `lastCharPos` optimization down to
`GetWordEnd`. So word expansion gets this optimization for free now.
The percentages below represent the weight that a function call had. The
test scenario included moving by word on the CMD welcome message until
the last word was reached. Inspect.exe was used to limit any additional
calls that are generally performed by a screen reader.
| function   | current | branch |
| --         | --      | --     |
| `UIA:Move` | 34.55%  | 29.52% |
There is an improvement of about 5% in a release build of ConHost.
NOTE: `UIA::Move` already …

Add optimization to get a11y next word

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl
src/cascadia/TerminalCore/ITerminalApi.hpp
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/cascadia/TerminalCore/TerminalDispatch.cpp
src/cascadia/TerminalCore/TerminalDispatch.hpp

This PR makes the Windows Terminal play an audible sound when the `BEL` control character is output.
* There is a separate issue (#1608) to deal with configuring the `BEL` to trigger visual forms of notification.
* There was also an issue (#2360) requesting an option to disable the `BEL`, which should probably be reopened, because this PR does not include any such configuration.
The `BEL` control was already being forwarded through conpty, so it was just a matter of hooking up the `WarningBell` dispatch method to actually play a sound. I've used the `PlaySound` API to output the sound configured for the "Critical Stop" system event (aka _SystemHand_), since that is the sound used in conhost. 
I've manually confirmed that the terminal produces the expected sound when executing `echo ^G` in …

Add support for the BEL control in Windows Terminal

---

src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
src/types/UiaTextRangeBase.cpp

The `MovementAtExclusiveEnd` test was improperly authored for the
following reasons:
- it should have used `TEST_METHOD_PROPERTY` to cover all of the
TextUnits
- TextUnit::Document (arguably one of the most important) was ommitted
accidentally (`!= TextUnit_Document` was used instead of `<=`)
- The created range was not `EndExclusive`, but rather, the last cell in
the buffer (`EndInclusive`)
The first half of this PR fixes the test.
The second half of this PR expands the test and fixes any related issues
to make the test pass (i.e. #7771):
- `TEST_METHOD_PROPERTY` was added for it to be degenerate (start/end at
`EndExclusive`) or not (last cell of buffer)
- `utr->_start` is now also validated after moving backwards
NOTE: `utr->_start` was not validated when moving forwards because
moving …

Properly handle and test a11y movement at end of buffer

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/CommandPalette.h
src/cascadia/TerminalApp/TerminalPage.cpp

This PR enables the ATS to display the active tab as the user navigates the tab switcher. We do this by dispatching the tab switch actions as the user navigates the menu, and manually _not_ focusing the new tab when the tab switcher is open. 
* #6732 - original tab switcher PR
* #6689 - That's a more involved, generic version of this, but this PR will be enough to stop most of the complaints hopefully
Opened tabs, tabbed through the menu, verified that it did what I'd expect

Preview tab switching with the ATS

---

src/cascadia/TerminalApp/CommandPalette.cpp

#7796 and #7667 were being implemented concurrently. As a part of #7667, `Command` was moved from TermApp to TSM. This just applies that change to a line we missed in #7796 and fixes the build break.

Fix old reference to TermApp::Command

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TabRowControl.xaml
src/cascadia/TerminalApp/TerminalPage.cpp

Adds a tooltip to the new tab button to let the user know that holding alt will open a new pane instead

Inform user that holding alt opens a new pane

---

src/cascadia/TerminalControl/Resources/en-US/Resources.resw

Following up on our discussion in https://github.com/microsoft/terminal/pull/7866#issuecomment-705814434

Fix capitalization in hyperlink tooltip

---

.github/actions/spell-check/dictionary/microsoft.txt
src/cascadia/WpfTerminalControl/TerminalContainer.cs
src/cascadia/WpfTerminalControl/TerminalControl.xaml.cs
src/cascadia/WpfTerminalControl/WpfTerminalControl.csproj

Fixes various issues with autofill and resize events

wpf: fix margin calculations and resize events

---

src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp

Took this as an easy starter. The method IslandWindow::SetAlwaysOnTop is triggered once terminal settings are reloaded (in TerminalPage::_RefreshUIForSettingsReload flow). This method calls SetWindowPos without SWP_NOACTIVATE. As a result the window gets activated, the focus is set and the cursor starts blinking.
Added SWP_NOACTIVATE flag there and in few additional places in island windows. See a discussion below.
Added SWP_NOACTIVATE  in all SetWindowPos calls  from IslandWindow and NoClientIslandWindow (where it was missing). Please let  me know if this is an overkill - it is not required to fix the issue, however seems a good practice, that might help if we decide to apply more settings immediately.
* Only manual testing - please guide me to the relevant UT framework, if exists. 
* …

7571: do not activate terminal window upon settings modificaion

---

doc/cascadia/profiles.schema.json
src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp
src/cascadia/TerminalApp/AppCommandlineArgs.cpp
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h
src/cascadia/WindowsTerminal/IslandWindow.cpp

This commit introduces two new launch modes: focus and maximizedFocus. 
* Focused mode, behaves like a default mode, but with the Focus Mode
enabled.
* Maximized focused mode, behaves like a Maximized mode, but with the
Focus Mode enabled.
There two ways to invoke these new modes:
* In the settings file: you set the "launchMode" to either "focus" or
"maximizedFocus"
* In the command line options, you can path -f / --focus, which is
mutually exclusive with the --fullscreen, but can be combined with the
--maximized:
* Passing -f / --focus will launch the terminal in the "focus" mode
* Passing -fM / --focus --maximized will launch the terminal in the
"maximizedFocus" mode
This should resolve a relevant part in the command line arguments
mega-thread #4632
Closes #7124
Closes #7825
Closes …

7124: Add focus and maximizedFocus launch modes

---

.github/workflows/linter.yml
src/host/ut_host/ScreenBufferTests.cpp

For whatever reason, the super linter seems to think that any file it doesn't recognize is an EDITORCONFIG file. That means all our `cpp`, `hpp`, `h`, `resw`, `xaml`, etc files are going to get linted with different rules than the clang-format ones we already use. 
This PR disables the EDITORCONFIG linter, and has a minimal change to a cpp file to ensure that it's no longer linted by the action.
See also: 
* #7637 added this
* #7799 is blocked by this
* #7924 is blocked by this

Fix the linter for C++ files

---

src/cascadia/TerminalApp/CommandPalette.xaml

Increase the contrast ratio between the text of the keyboard shortcuts in the cmdpal and their background

Increase contrast ratio on the CmdPal shortcut text

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/CommandPalette.h
src/cascadia/TerminalApp/CommandPalette.idl
src/cascadia/TerminalApp/CommandPalette.xaml
src/cascadia/TerminalApp/Resources/en-US/Resources.resw

VsCode uses `>` as its "prefix" for the equivalent of their "action mode". This PR aligns the Terminal with their logic here. 
We have to be tricky - if we use the `>` in the actual input as the indicator for action mode, we can't display any placeholder text in the input to tell users to type a command. This wasn't an issue for the commandline mode previously, because we'd stick the "prompt" in the "no matches text" space. However, we can't do that for action mode. Instead, we'll stick a floating text block over the input box, and when the user's in action mode, we'll manually place a `>` into that space. When the user backspaces the `>`, we'll remove it from that block, and switch into commandline mode.
Played with the cmdpal in lots of different modes, this finally feels good

Swap the command palette modes for the prefix `>`

---

src/cascadia/TerminalControl/TermControl.cpp

When handling SendKey, preserve selection upon PrintScreen (VK_SNAPSHOT)
The explicitly ignores the VK_SNAPSHOT. Probably, additional keys should not alter the selection.
* Manually, took snapshot with content selected and checked that the selection is not changed. Verified that the snapshot is taken (and even contains the selection :smile:)
* Manually, checked that the old behavior is preserved for modifier and non-modifier keys

7395: do not clear text selection upon PrintScreen

---

.github/actions/spell-check/dictionary/apis.txt
.github/actions/spell-check/patterns/patterns.txt
src/terminal/parser/base64.cpp
src/terminal/parser/ut_parser/Base64Test.cpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp

This commit adds a missing conversion utf8 to utf16 in decoding base64
for handling multibyte text in copying via OSC 52.
* automatically
* Tests w/ multibyte characters
* manually
* case1
* Executed `printf "\x1b]52;;%s\x1b\\" "$(printf '👍👍🏻👍🏼👍🏽👍🏾👍🏿' | base64)"`
* Verified `👍👍🏻👍🏼👍🏽👍🏾👍🏿` in my clipboard
* case2
* Copied `👍👍🏻👍🏼👍🏽👍🏾👍🏿` by tmux 2.6 default copy function (OSC 52)
* Verified `👍👍🏻👍🏼👍🏽👍🏾👍🏿` in my clipboard
Closes #7819

Fix garbling when copying multibyte text via OSC 52

---

src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/cascadia/UnitTests_TerminalCore/TerminalApiTest.cpp
src/host/getset.cpp
src/host/ut_host/ScreenBufferTests.cpp
src/host/ut_host/TextBufferTests.cpp

It turns out that we missed part of the OSC 8 spec which indicated that
_hyperlinks with the same ID but different URIs are logically distinct._
> Character cells that have the same target URI and the same nonempty id
> are always underlined together on mouseover.
> The same id is only used for connecting character cells whose URIs is
> also the same. Character cells pointing to different URIs should never
> be underlined together when hovering over.
This pull request fixes that oversight by appending the (hashed) URI to
the generated ID.
When Terminal receives one of these links over ConPTY, it will hash the
URL a second time and therefore append a second hashed ID. This is taken
as an acceptable cost.
Fixes #7698

Hash the URI as part of the hyperlink ID

---

src/cascadia/TerminalApp/Tab.cpp

Fix for crash occurring when splitting a pane, due to tab context menu created multiple times.
#7728 
When splitting panes the `Tab::Initialize` function is called again. This rebuilt the context menu from scratch and appended the existing Close... sub-menu items to a new parent, thus causing the crash.
It is not necessary to re-create the context menu every time you split panes, it can be created only once.
Manual verification:
- Play with the context menu, the Close... submenu is functioning
- Split panes (ALT + New tab), no crash occurs and context menu still functioning

Fix crash when creating tab menu multiple times

---

src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj

This import is required to make localized resources work.

Make sure TSM pulls in the wildcard resource targets

---

src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj

This import is required to make localized resources work.

Make sure TSE pulls in the wildcard resource targets

---

.github/actions/spell-check/dictionary/names.txt
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

Let's assume the user has bound the dead key <kbd>^</kbd> to a sendInput command that sends "b".
If the user presses the two keys <kbd>^</kbd><kbd>a</kbd> it'll produce "bâ", despite us marking the key event as handled.
We can use `ToUnicodeEx` to clear such dead keys from the keyboard state and should make use of that for keybindings.
Unfortunately `SetKeyboardState` cannot be used for this purpose as it doesn't clear the dead key state.
* Enabled a German keyboard layout
* Added the following two keybindings:
```json
{ "command": { "action": "sendInput", "input": "x" }, "keys": "q" },
{ "command": { "action": "sendInput", "input": "b" }, "keys": "^" }
```
* Pressed the following keys → and ensured that the given text is printed in that order:
* <kbd>q</kbd> → x
* <kbd>´</kbd> → nothing …

Fix #5784: Key bindings won't consume dead keys

---

src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/CommandPalette.h
src/cascadia/TerminalApp/CommandPalette.idl
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

This PR changes the ATS display order to _always_ be in most recently
used (MRU) order. I chose not to give ATS the option to be displayed
in-order because that order is better served through the traditional
left-right TabRow switching. 
_Note_: `TabSearch` will stay in-order.
This means that users can only choose one order or another in their
`nextTab/prevTab` bindings. Setting `useTabSwitcher` to true will make
nT/pT open the ATS in MRU order. If it's set to false, the ATS won't
open and nT/pT will simply go left and right on the TabRow.
I'm open to getting rid of the global and making ATS its own keybinding,
but for now I figured I would keep the current behavior and open the PR
to get eyes on the code that doesn't have anything to do with the
settings.
Closes #973

Display ATS tabs in MRU order

---

src/cascadia/TerminalApp/TerminalPage.cpp

Just deleting an unnecessary call to `_UpdateCommandsForPalette`
**Note:** This only fixes slowdown when opening/closing a tab, but not upon first startup (we still need to call `_UpdateCommandsForPalette` there 
Fixes the slowdown described in #7820 for opening and closing tabs, but doesn't improve startup time dramatically.
Tested with ~100 profiles in my settings file

Fix slowdown on open/close tabs when the user has many profiles

---

build/rules/Branding.targets
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj

Our build pipeline was originally set up such that we could take any
binaries from the Terminal build and seamlessly re-package them with the
release or preview livery. My initial plan was to stamp a stable and
preview build at the same time, out of the same bits, to make ring
promotion easier.
I've never done that. For the last five releases, we've just re-cut a
new stable build along with the new preview build, usually because we
want to backport some fixes to stable.
This commit introduces preprocessor defines, detectable through CL and
RC, for any project that wants them. Right now, that's just going to be
WindowsTerminal.vcxproj (since it hosts the icons and the app entry
point). This list may be extended to include wt (the shim executable)
and the shell extension at some future …

Expose WindowsTerminalBranding to the preprocessor (optionally)

---

src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml
src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
src/cascadia/TerminalSettingsEditor/Home.xaml
src/cascadia/TerminalSettingsEditor/Interaction.xaml
src/cascadia/TerminalSettingsEditor/Keybindings.xaml
src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsEditor/Profiles.xaml
src/cascadia/TerminalSettingsEditor/Rendering.xaml

This fixes the bug where the reset/save footer covers settings.
#1564

Add scrollviewers to settings UI

---

.github/workflows/linter.yml
CONTRIBUTING.md
README.md
SUPPORT.md
build/pipelines/ci.yml
doc/cascadia/profiles.schema.json
doc/specs/#1571 - New Tab Menu Customization/#1571 - New Tab Menu Customization.md
doc/specs/#2046 - Unified keybindings and commands, and synthesized action names.md
doc/specs/#6899 - Action IDs/#6899 - Action IDs.md
doc/submitting_code.md
res/README.md
src/cascadia/CascadiaPackage/NOTICE.html

This commit fixes up all references to `master` in the source, docs,
specs and comments.
Related to #6739.

Prepare for the primary branch name to change to main

---

src/cascadia/TerminalApp/Jumplist.cpp
src/cascadia/TerminalApp/Jumplist.h
src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp

Move jumplist creation to a background thread, it does not need to be on the main thread
#7791 
We were not using the `HRESULT` return value of `UpdateJumplist` anywhere, so I changed its return type to `winrt::fire_and_forget` instead. Also replaced all `RETURN_IF_FAILED` calls in the function to `THROW_IF_FAILED` to accommodate the change in return type. 
Tracing with a release build:

Move jumplist creation to background thread

---

src/cascadia/TerminalApp/ColorPickupFlyout.xaml

Adds the color slider to the tab color picker
*Not required*

Show color slider in Tab color picker

---

src/terminal/parser/ft_fuzzwrapper/FuzzWrapper.vcxproj
src/terminal/parser/ft_fuzzwrapper/FuzzWrapper.vcxproj.filters

The intent of this PR is to resolve the dependency errors reported in
#7931. The Types project has been added as a reference to the
FuzzWrapper project, which fixes the unresolved dependency errors
reported.
For validation steps, I:
1.) Pulled down main.
2.) Rebuilt the FuzzWrapper project and observed the unresolved
dependency errors keeping it from building successfully.
3.) Added a project reference to the Types project.
4.) Rebuilt the FuzzWrapper project and verified that the dependency
errors disappeared.
Closes #7931.

Added Types project reference to the FuzzWrapper project

---

src/cascadia/WpfTerminalControl/TerminalControl.xaml.cs

This PR resolves an issue I observed in
Microsoft.Terminal.Wpf.TerminalControl.CalculateMargins(). Specifically,
on line 194 in the project. In this example, the line: `height =
controlSize.Height - (this.TerminalRendererSize.Height /
dpiScale.DpiScaleX);` is associating the height margin with
dpiScale.DpiScaleX instead of dpiScale.DpiScaleY. This PR changes the
association to DpiScaleY.
Closes #8038

wpf: base margin height off Y dpi, not X dpi

---

src/cascadia/TerminalApp/TerminalPage.cpp

Close the tab context menu when clicking on the title bar
Following #2438, hide the tabs context menu on `TerminalPage::TitlebarClicked()`. 
We don't know which of the tabs is showing the context menu, do it on all tabs.
Open the context menu from any tab, click on title bar and see the context menu disappear.
Closes #7988

Close tab context menu on titlebar click

---

doc/user-docs/ThirdPartyToolProfiles.md

MSYS2 actually has their own webpage that lists off some ways of adding MSYS2 to the Windows Terminal. I figured we should also link to it, since their documentation has some good details in it.

doc: add a link to MSYS2's WT profiles page

---

src/cascadia/TerminalSettingsEditor/Profiles.xaml

When I did the polishing I forgot to do the Advanced page under profiles. I fixed that here.

Fix spacing on profile advanced page

---

.github/actions/spell-check/dictionary/names.txt
src/types/UiaTextRangeBase.cpp
src/types/UiaTextRangeBase.hpp

In https://github.com/nvaccess/nvda/issues/11428#issuecomment-715893846,
Andre9642 reported a Conhost crash when switching to/from the alt buffer
a few times with a Braille display connected. Upon further
investigation, @carlos-zamora and I discovered that the FailFast was in
`GetText`: more checks similar to #7677 were needed for this case.
Tested with NVDA using a [Focus](https://www.freedomscientific.com/products/blindness/focus40brailledisplay/) Braille display.
Improves nvaccess/nvda#11428

UIA: throw E_FAIL for out-of-bounds text

---

src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj
src/cppwinrt.build.pre.props

C++/WinRT added a feature where it will detect a mismatch in some of its
build flags.
Because we build XAML projects and non-XAML projects, and try to link
them together in static libraries, we need those flags to always match.
C++/WinRT only respects this flag when `DEBUG` is set, so our CI missed
this.
With thanks to @carlos-zamora for letting me build/test/commit this on
his computer.

Fix the WINRT_NO_MAKE_DETECTION build break

---

src/cascadia/ShellExtension/OpenTerminalHere.cpp

This is cheaper than storing another icon in another resource fork.
Eventually, we could support high contrast just by varying the icon ID.
Fixes #6246. Looks pretty good, too.

Shell extension: Use WT's icon as our icon

---

src/cascadia/LocalTests_SettingsModel/DeserializationTests.cpp
src/cascadia/LocalTests_SettingsModel/ProfileTests.cpp
src/cascadia/LocalTests_TerminalApp/SettingsTests.cpp
src/cascadia/TerminalApp/Jumplist.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettings.idl
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/ut_app/DynamicProfileTests.cpp

This PR replaces `CascadiaSettings::_profiles` with...
- `_allProfiles`: the list of all available profiles in the settings model (i.e. settings.json, dynamic profiles, etc...)
- `_activeProfiles`: the list of all non-hidden profiles (used for the new tab dropdown)
#8018: maintaining a list of all profiles allows us to serialize hidden profiles
#1564: Settings UI can link to `AllProfiles()` instead of `ActiveProfiles()` to expose hidden profiles
Deploy and testing succeeded

Store and expose hidden profiles

---

src/buffer/out/textBuffer.cpp

Realized that we don't copy the current hyperlink id when we copy buffers, quick fix for that

Copy _currentHyperlinkId when copying the buffer

---

.github/workflows/linter.yml

All our JSON files are _actually_ JSONC files - json with comments. 
A well-behaved application that accepts JSON should accept and ignore comments. However, `jsonlint` is not a well behaved application in this regard.
So, to prevent the linter from complaining about our JSON comments, we need to disable it entirely. THAT'S RIGHT, there's not a setting to allow JSONC. 
See #8076 as an example of this working.
This will also unblock #7462.

Disable the json linter

---

build/pipelines/templates/build-console-audit-job.yml
build/pipelines/templates/build-console-ci.yml
build/pipelines/templates/build-console-steps.yml
src/common.build.post.props

This pull request switches us to the new WinDev scaleset agent pool. It
should be faster than the hosted pool, and the larger disks allow us to
get rid of our PCH cleanup step.

Move CI and audit build to the WinDev scale set pool

---

src/cascadia/TerminalSettingsEditor/MainPage.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Fixed the resizing bug where long text buttons get cut off, hid the unsaved changes warning, and changed "save" to "apply"
#1564

Change save to apply in SUI

---

src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp
src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml

This fixes the bug where on a Color Scheme change, a portion of the
color pickers will be set to the correct color, but the other portion of
the color pickers will be set to the same colors that the first portion
was set to. It looks like performing a `Clear` and `Append` confuses the
Color Pickers when they raise their `ColorChanged` events in response.
Avoiding the `Clear` and `Append` by just changing the `Color` property
allows the Color Pickers to keep their existing data bound object and
only react to their Color property changing instead of having to deal
with the whole object being swept out from under them and being given a
new one.

Fix the Settings UI Color Pickers

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

The logic of the showTabsInTitlebar setting was backwards in the settings UI.

Fix showTabsInTitlebar SUI logic

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

Fire and forget on the hyperlink handler inside the TermControl. 
In `TermControl`, `_HyperlinkHandler` is called by
`_PointerPressedHandler` which has taken a write lock for all its
friends. However, `_HyperlinkHandler` downstreams to `ShellExecute`
which can pump the message queue looking for something. That pumping of
the queue can trigger messages that also want the write lock to update
state. They get stuck. Everything hangs. 
`_HyperlinkHandler` really only needs read lock and really only for as
long as it takes to fill up its parameters before it's invoked... but
the simpler and more contained solution is to just fire and forget the
rest of the method that causes the deadlock to a continuation at the
tail of the dispatcher queue so `_PointerPressedHandler` can complete
and …

Fire and forget Hyperlink handling to break deadlock

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.xaml

A second close command (middle click on taskbar preview) overrides the warning dialog and closes the application.
When a close command is invoked (middle click on taskbar preview or 'X' button), a new flag is set. When the user wants to close again (this time only via the taskbar preview, as the 'X' button is disabled), the application is closed. If the user cancels the dialog, the flag is reset to prevent accidental closing on a subsequent close command.
I am developing with a [Windows 10 virtual machine](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) provided by Microsoft. I tested manually. I considered the 'X' button, middle click on taskbar preview, and Alt+F4. Only a middle click on the taskbar preview does override the dialog.

Double middle click on taskbar preview closes application

---

src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsEditor/Profiles.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Since we've started working on the Settings UI, a few settings have been added on `main`. This adds those missing settings over. 
Missing settings include...
- #7364: `disableAnimations`
- #7873: `launchMode` `focus` and `maximizedFocus`
- #7793: `bellStyle`
Verified that those settings appear properly in the Settings UI.

Add missing settings to Settings UI

---

src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/AppLogic.idl
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/WindowsTerminal/AppHost.cpp

Currently the value of AlwaysOnTop is read by the AppHost from AppLogic that takes this value from the root TerminalPage. However at this stage neither AppLogic nor TerminalPage are initialized, and thus the return value is always false.
This PR introduces a "GetInitialAlwaysOnTop" method to AppLogic that returns a value that is configured in the settings.
In addition, the TerminalPage creation was fixed to read the configuration value upon creation (and not just after settings reload).
* Only manual testing
* Starting the system with both initial value set to true and false
* Verifying that dynamic toggling on / off is not affected

7996: Always on Top setting does not persist

---

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp

In the focus mode the top border disappears upon resize. While this behavior is expected in the maximized / full screen mode, it should not happen in the focus mode.
_GetTopBorderHeight method returns 0 when maximized or no title bar is visible. However the existence of top border has nothing to do with whether the title bar is visible. We want to leave the border as long as the window is not in some form of maximizing (maximized / full screen)
* Manual - dragging, resizing, maximizing both in focus and non focus modes + full screen testing

7012: top margin disappears upon resize in focus mode

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp

This PR fixes a crash where looping through a NavView's items would attempt to grab a `NavigationViewItemHeader`'s null tag and crash. This for-loop wasn't needed anyway since we've gotten rid of the home page.

Remove code to navigate to home page on SUI launch

---

src/buffer/out/textBuffer.cpp

Fix #8121
When calculating the position of the matched pattern, consider the width of the characters.
However, if there are some wide glyphs in the detected hyperlink(not possible for now, for the existing regex will not match wide-character?). The repeated character in the tooltip is not fixed by this PR.
When calculating the coordinate of the match in #7691, it simply uses the `prefix.size()` as the total prefix width on the screen.
This PR fixes that behavior.
Manually Verified

Consider the GlyphWidth when calculate the postion of matched word in URL detecting

---

.github/actions/spell-check/expect/expect.txt
src/common.build.pre.props

Turns out there's an actual way to specify C++17 for MSBuild purposes
besides just passing the compile flag.
* Future C++20 support (modules)
modules.
* We've been setting C++17 with just the flag passed to the compiler
`cl.exe`. But it turns out that this particular `LanguageStandard`
option will need to be set appropriately one day for us to use C++20
modules (as evidenced by the latest VS16.8 preview that I tried out to
explore modules.) The `AdditionalOption` alone isn't enough to ensure
that modules can be "seen" by other projects after production, but
`LanguageStandard` is (and will set the compiler option as appropriate
as well as whatever internal goo that MSBuild needs to hook up other
stuff.)
* Built with it changed.

Use LanguageStandard over explicit compiler flag for C++17

---

src/renderer/base/renderer.cpp
src/renderer/dx/DxRenderer.cpp

This pull request switches up the treatment we use for pattern-detected
links and OSC 8 hyperlinks:
* Links generated via OSC 8 have a sparse dotted underline instead of a
thick dashed one
* **BEFORE**
* ![image](https://user-images.githubusercontent.com/189190/98027742-f9b1ba00-1dc1-11eb-9633-d5fa26898c81.png)
* **AFTER**
* ![image](https://user-images.githubusercontent.com/189190/98027715-edc5f800-1dc1-11eb-9ba6-73e6e40e4bc8.png)
* Links generated by pattern detection _are not underlined until they've
hovered_
* This papers over a visual glitch that is a result of us updating
the pattern matches every ~500ms (on change)
* **BEFORE**
* ![image](https://user-images.githubusercontent.com/189190/98027899-2fef3980-1dc2-11eb-898f-047b5ea46ef9.png)
* **AFTER**
* …

Make the link underline less obtrusive; don't use it for pattern

---

.github/actions/spell-check/dictionary/apis.txt
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.idl
src/cascadia/TerminalApp/TerminalPage.xaml
src/tools/scratch/main.cpp

With this PR, the Terminal will check to make sure the "Touch, Keyboard and Handwriting Panel Service" is enabled at startup. If it isn't, then the Terminal won't be able to receive keyboard input (see #4448 and the 20 linked issues to that one).
* See #4448 for more details
I manually set the service to "Disabled", restarted the machine, verified the dialog opens (and that I'm unable to type in the Terminal), then re-set the service to automatic and rebooted, and the dialog doesn't appear.

Warn the user if the keyboard service is disabled

---

src/cascadia/LocalTests_SettingsModel/DeserializationTests.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

When we get a serialization error, we "catch" it in `AppLogic` and only
`LoadDefaults()`. Since `LoadDefaults()` doesn't perform a full
validation of `CascadiaSettings`, we need to manually update our list of
active profiles (similar to how we manually resolve the default
profile).
Repro steps fixed:
1. add deserialization error to settings.json (i.e. "fontWeight": "wumbo")
2. launch WT
3. verify that dropdown is populated with active profiles
Closes #8146

Update active profiles when loading defaults

---

src/cascadia/LocalTests_TerminalApp/TabTests.cpp

A fix for UTs crashing due to bad memory access (accessing page 0).
Regression from #8153
Closes #8167

8167: Fix TabTests - use tab 0 rather than value 0

---

src/renderer/gdi/paint.cpp

There are certain cursor movement operations (in conhost) that can
result in "ghost" cursor instances being left behind, if the move causes
the viewport to scroll while the cursor is blinking off. Pressing enter
in a PowerShell prompt when at the bottom of the screen was one example
of this. This PR fixes that problem.
Whenever the cursor renders with an `InvertRect`, the affected areas of
the screen are saved in the `cursorInvertRects` variable. If the screen
is then scrolled while the cursor is visible, those rects are
"uninverted" in the `GdiEngine::ScrollFrame` method before the scrolling
takes place.
When the cursor has blinked off, though, the `GdiEngine::PaintCursor`
method won't set the `cursorInvertRects` variable, but it also doesn't
clear it. So if the screen is scrolled at …

Prevent leftover cursor fragments when scrolling in PowerShell

---

src/cascadia/TerminalSettingsEditor/Launch.xaml

Now that the IconConverter was moved to TSM, SUI has access to it. This uses the IconConverter to include an icon in the Default Profile dropdown.
#1564 - Settings UI

Include icons in SUI DefaultProfile dropdown

---

src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj

By adding these target Inputs/Outputs to TestHostApp's AfterBuild, we
can ensure that new versions of the test libraries are properly
detected. No longer will we have to delete them from disk and rebuild
TestHostApp and hope that it picks up the latest test binaries.
Oh, and I turned on a couple other optimizations (hard links, skipping
unchanged files) that were really just low-hanging fruit.

Express dependencies in TestHostApp to help rebuild

---

src/cascadia/LocalTests_TerminalApp/TabTests.cpp
src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/CommandPalette.h

In introduced a bug in #8185, due to which Command Palette sorts items
alphabetically in the tab switcher mode. This PR fixes it.
Validation:
Created tabs with different names and verified that the MRU order is
preserved
Closes #8185

8185: do not sort commands by name in tabswitcher mode

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/CommandPalette.h

This commit will teach CommandPalette to clamp the scroll page up and
scroll page down navigation so as to not wrap.
Closes #8189

Teach the command palette to clamp its indices on page up/down

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalSettingsModel/Profile.cpp

- Change `DesktopWallpaper` to `desktopWallpaper` for `backgroundImage`
to match our other settings
- Add `desktopWallpaper` to json schema

Fix desktopWallpaper background image casing

---

src/cascadia/TerminalConnection/AzureConnection.cpp
src/cascadia/TerminalConnection/AzureConnection.h
src/cascadia/TerminalConnection/Resources/en-US/Resources.resw

Fallback to powershell if "preferred shell" is not specified in the user
settings of Azure CLI.
I am still not sure what is the full set of scenarios that the problem
might occur, but for me it occurred for an "old" cloud shell account,
and didn't reproduce since I have reconfigured it. These behavior might
be explained by the fact that "preferred shell type" did not exist in
the API originally and thus was not set.  In such case, Terminal
succeeds to retrieve to the settings but then crashes when reading the
missing field.  To fix it, I handle the case where the field is missing
and fallback to powershell
* Tested manually, only once.
Closes #7056

Azure: fall back to powershell when no preferred shell is set

---

.github/actions/spell-check/expect/expect.txt
doc/cascadia/Json-Utility-API.md
src/cascadia/LocalTests_SettingsModel/CommandTests.cpp
src/cascadia/LocalTests_SettingsModel/KeyBindingsTests.cpp
src/cascadia/TerminalSettingsModel/IInheritable.h
src/cascadia/TerminalSettingsModel/JsonUtils.h
src/cascadia/TerminalSettingsModel/Profile.cpp
src/cascadia/ut_app/JsonUtilsTests.cpp

The JsonUtils changes in #8018 revealed that we need more robust,
configurable optional handling. We learned that there's a class of
values that was previously underrepresented in our API: _strings that
have an explicit empty value_.
The Settings model supports starting directory, icon, background image
et al values that are empty. That emptiness _overrides_ a value set in a
lower layer, so it is not sufficient to represent the empty value for
any one of those fields as an unset optional.
There are a couple other settings for which we've implemented a
hand-rolled option type (for roughly the same reason): foreground,
background, any color fields that override values from the color scheme
_or_ the lower layer profile.
These requirements are best fulfilled by better optional support in …

Rework JsonUtils' optional handling to let Converters see null

---

src/cascadia/LocalTests_SettingsModel/DeserializationTests.cpp

This fixes the test for when we switched `"DesktopWallpaper"` to `"desktopWallpaper"`

Fix test for desktopWallpaper

---

src/cascadia/TerminalApp/Pane.cpp

Some UTs crash with access violation, that occurs during pane animation.
The reason for this is a race, upon which the pane is closed (set to
nullptr) before the parent is animated.  Added a simple check against
null.  Doubt it can happen in production, yet worth taking care!

Avoid an access violation in pane animation if the child is closed

---

src/host/selectionInput.cpp

Fixed potential errors caused by overflow or underfow in
SectionInput.cpp
In selectionInput.cpp, there is both a potential overflow and potential
underflow. To address this issue, I casted the calculation up to int,
which is then checked because of integer promotion. Underflow and
underflow is therefore impossible because now if the calculation exceeds
SHORT_MAX, it will have exceeded bufferSize.BottomInclusive() or
bufferSize.Top() anyway, and be set to them.
Passed Unit Testing
Manual Validation

Fix potential over/underflow as noted by "TODO:" comment

---

src/terminal/parser/OutputStateMachineEngine.cpp

In `ActionOscDispatch()` in `OutputStateMachineEngine.cpp`, we had a
section for parsing and another section for dispatching. This PR
combines those two blocks since they do not need to be distinct. 
TerminalApiTests still pass

Combine the parsing & dispatch blocks for OSC actions

---

src/cascadia/TerminalApp/TerminalPage.cpp

There are two code paths for Ctrl+Tab and for everything else:
Ctrl + Tab is working perfectly
* On the first tab navigation TerminalPage::_SelectNextTab resets the
tab commands, and since palette is not visible selects the relevant
tab index
* On the second navigation Ctrl+Tab is intercepted by
CommandPalette::_previewKeyDownHandler and everything works fine
But with custom binding things are screwed:
* On the first tab navigation TerminalPage::_SelectNextTab resets the
tab commands, and since palette is not visible selects the relevant
tab index
* On the second navigation keys are not intercepted and thus
TerminalPage::_SelectNextTab is called again. It resets the commands,
but now since the palette is visible we simply invoke
CommandPalette::SelectNextItem. Which in turn misbehaves …

8247: Custom key bindings are broken for tab navigation

---

doc/cascadia/profiles.schema.json

Fixes https parsing of the latest version of `profiles.schema.json`, particularly by VS Code Intellisense.
The VS Code parsing warning below is a known and unrelated existing issue due to VS Code only supporting JSON Schema Draft 7. It does not prevent Intellisense from functioning.
> Draft 2019-09 schemas are not yet fully supported.
Manually tested and successfully validated by fixing a local copy of `profiles.schema.json` and defining it as `$schema` in `settings.json`

8249: Remove trailing commas in profiles.schema.json

---

src/cascadia/TerminalApp/CommandPalette.xaml

Fixes the clear button to clear the typed command not clickable in the
command palette.
- From the primary investigation it looked like the `TextBlock` element
introduced in #7935 was somehow blocking (appearing on top of) the
clear button.
- It was also blocking the command palette input field from being able
to access which was preventing the text in the input field from being
selected and the cursor would still show as `pointer` cursor instead
of a `text selection` cursor
- Adding `HorizontalAlignment="Left"` property to the above-mentioned
`TextBlock` element fixed the issue.
- Created the Dev build for `x64` in Visual Studio and verified the
functionality manually.
Closes #8220

align command palette prefix > to left when visible

---

src/cascadia/TerminalSettingsModel/Profile.h

This commit fixes the default value to comply with documentation.
Closes #8256

Fix default backgroundImageStretch to be `uniformToFill`

---

src/host/getset.cpp
src/host/renderData.cpp
src/host/renderData.hpp
src/host/screenInfo.cpp

This fixes a number of exceptions that can cause conhost to crash when
the buffer is resized in such a way that the viewport or cursor position
end up out of bounds.
Technically this is a fix for issue #256, although that has been closed
as "needs-repro".
The main fix was to add checks in the `SetConsoleScreenBufferSizeImpl`
and `SetConsoleScreenBufferInfoExImpl` methods, to make sure the
viewport doesn't extend past the bottom or right of the buffer after a
resize. If it has overflowed, we move the viewport back up or left until
it's back within the buffer boundaries. We also check if the cursor
position has ended up out of bounds, and if so, clamp it back inside the
buffer.
The `SCREEN_INFORMATION::SetViewport` was also a source of viewport
overflow problems, because it was mistakenly …

Fix out-of-bounds exceptions in Set...{Buffer,Screen}Size

---

src/cascadia/TerminalApp/TerminalTab.cpp

This sets the tab close button color to match the tab text color.
#8046
This sets the tab close button color to match the tab text color.
Test light theme white tab mouse hover effect:
Test dark theme white tab mouse hover effect:

Fix close button not using the tab's text color (#8046)

---

src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp
src/cascadia/TerminalApp/AppCommandlineArgs.cpp

Currently when implicit tab command is specified (i.e., we have
parameters for new-tab, but don't have the explicit subcommand name) we
fallback to parsing the entire arg list as new tab command.
However, if we also have a launch profile (or anything else that might in
the future belong to the upper scope) it is passed as a parameter to the
new tab command, failing the parsing.
The idea behind my solution is to run the parser as a prefix command -
i.e., as long as we succeed to parse [options] / [subcommand] we will
parse them (populating the fields like a launch mode), but once we will
discover something unfamiliar, like profile, we will know that the
prefix is over and will handle the remaining suffix as a new tab
command.
* UT added
* Manual run of different option
Closes #7318

Fix combining wt args and "wt new-tab" args in implicit context

---

src/cascadia/TerminalApp/Pane.cpp

Fixes a race in pane entrance animation, where the animation
completion routine processes wrong children.
Validated w/ manual testing
Closes #8230

Fix a race condition in pane animation completion that broke sizing

---

src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml
src/cascadia/TerminalSettingsEditor/CommonResources.xaml
src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
src/cascadia/TerminalSettingsEditor/Interaction.xaml
src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/MainPage.h
src/cascadia/TerminalSettingsEditor/MainPage.xaml
src/cascadia/TerminalSettingsEditor/Profiles.xaml
src/cascadia/TerminalSettingsEditor/Rendering.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

This PR performs a wholistic polish on the Settings UI by doing the following:
- Use NavigationView's header to display which page you are currently on (and style it appropriately)
- Remove back button (deemed unnecessary)
- Rely more heavily on CommonResources.xaml for consistent styling
- Replace `profile.schemes` and `profile.backgroundImageAlignment` with ComboBox controls (still not bound)
- Replace Profile-->Appearance page grid layout with a stack
- I know we desire a reflowable 2-column layout. But that's just too much work for now. I'm focusing on getting the Settings UI in a mergeable/shippable state.
- General code cleanup (particular focus on .xaml files)
Rather than posting many photos of all the changes, I suggest that you (the reviewer) just download and play with the …

Polish layout for Settings UI

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/GlobalAppSettings.h
src/cascadia/TerminalApp/defaults.json

Revert the tab switcher behavior for 1.4.
The default is once again `"useTabSwitcher":false`, since we
ninja-changed `true` to MRU switching. That was maybe a bad call.

Revert tab switching to *off* in 1.4

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalSettingsModel/GlobalAppSettings.h
src/cascadia/TerminalSettingsModel/defaults.json

@DHowett fix the commit body, it's 5pm here

Change the default tab switch mode back to inOrder

---

src/cascadia/TerminalApp/TabHeaderControl.cpp
src/cascadia/TerminalApp/TabHeaderControl.h
src/cascadia/TerminalApp/TabHeaderControl.idl
src/cascadia/TerminalApp/TabHeaderControl.xaml
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/TerminalAppLib.vcxproj.filters
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

This PR makes the Header of TabViewItem a custom user control.
Manual testing
Closes #8201

Make tab header a custom control

---

tools/bcz.cmd

Does what the title says. Now while you're building terminal projects,
the taskbar will show indeterminate progress. If the build fails, it'll
blink the error state for 500ms before returning to normal.
* Made possible by #8055 _and viewers like you_
tested manually

tools: update bcz.cmd to use the progress bar VT sequence

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.xaml

The CloseWarningDialog is now "awaitable"/async, as suggested in PR #7871.
As opening the dialog is async, the flag can be reset in the same
method. This way the flag operations occur in the same method.  The
event handlers of the buttons became obsolete and are removed.

Make CloseWarningDialog async

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/CommandPalette.h

Add a history to command palette in the command line mode.
Few considerations/limitations
1. In-memory, 10 entries hard-coded
2. MRU
3. List rather than set
4. The user needs explicitly select command from the history
* Manual testing

Add "recent commands" to Command Palette in commandline mode

---

src/cascadia/TerminalApp/TabHeaderControl.cpp
src/cascadia/TerminalApp/TabHeaderControl.h

Fix for #8365 
Adds a `_renameCancelled` bool that determines whether we raise the event for a title change. We do this because the lost focus handler for the rename box will be called _both_ when the renamer is dismissed by clicking somewhere else and by pressing enter/escape. So, the lost focus handler needs to conditionally raise the event. 
Closes #8365

Fix sending a title change event when the renamer is dismissed

---

src/interactivity/win32/windowio.cpp
src/terminal/adapter/ut_adapter/MouseInputTest.cpp
src/terminal/input/mouseInput.cpp

We had the xterm and SGR codings for meta/ctrl backwards. Oops.
This commit also fixes an observed issue in Windows Terminal where we
were passing in a console-style modifiers enum when MouseInput is
expecting MK_ constants.
I decided to unify MouseInput around the console-style modifier
constants because they have support for META (which MK_ does not) and
can differentiate between left/right alt/ctrl.
Our tests are fundamentally flawed here: they use a copy of the
modifier key generating logic _themselves_, so we got a bit of "error
carried forward."
I did not fix the tests to use known-good control sequences, I simply
replaced the character generator with another copy of the modifier code.
I did, however, extend them to test ctrl|meta and left/right modifiers.
Fixes #8291

Fix the xterm and SGR mouse encodings for CTRL, ALT, SHIFT

---

.github/actions/spell-check/dictionary/apis.txt
.github/actions/spell-check/expect/expect.txt
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/pch.h
src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/MainPage.h
src/cascadia/TerminalSettingsEditor/MainPage.idl
src/cascadia/TerminalSettingsEditor/Profiles.cpp
src/cascadia/TerminalSettingsEditor/Profiles.h
src/cascadia/TerminalSettingsEditor/Profiles.idl
src/cascadia/TerminalSettingsEditor/Profiles.xaml
src/cascadia/TerminalSettingsEditor/pch.h
src/cascadia/WindowsTerminal/AppHost.cpp

This fixes the issue with the settings UI where clicking the browse
buttons would cause an exception to be thrown when we tried to display a
picker without an originating HWND.
It turns out that pickers need a hosting/parent window, and Xaml Islands
doesn't furnish us with a CoreWindow that's set up for that use case.
Alas!
Raymond Chen's [blog post on the matter] suggests that we should
hand the HWND off through some classic COM interface. To do that
properly, Terminal's various components need to implement that interface
and propagate the HWND down where it's needed.
Thanks to a [Xaml compiler issue], we can't actually do that. To work
around that, we've begged and borrowed different methods for pushing
HWNDs around:
1. Using IInitializeWithWindow in secret
2. A member that takes a …

Propagate IslandWindow's HWND into any component that needs it

---

src/cascadia/TerminalApp/TabHeaderControl.xaml

If we try set a very long title, "rename box" UI changes max height,
corrupting the layout.  There are several ways to fix it, e.g. by
limiting the MaxHeight (e.g. by binding it to the actual height of the
title bar).
However, I went for the most straightforward approach - truncating.  I
don't think we should allow long titles (though it can be a nice hidden
storage :blush:)
I considered to truncate it to the tab header width, but we can actually
see more data in tab-switcher, so I simply went for a hard-coded value
which should be large enough.
If this approach makes sense we need to consider updating the
documentation. 
Closes #8428

Teach tab renamer to truncate tab title input

---

src/host/screenInfo.cpp
src/host/ut_host/ScreenBufferTests.cpp

When the viewport is moved to the "virtual bottom" of the buffer (via
the `MoveToBottom` method), it is important that the horizontal viewport
offset be left as it is, otherwise that can result in some undesirable
side effects.
Since the VT coordinate system is relative to the top of the viewport,
many VT operations call the `MoveToBottom` method to make sure the
viewport is correctly positioned before proceeding. There is no need for
the horizontal position to be adjusted, though, since the X coordinates
are not constrained by the viewport, but are instead relative to the
underlying buffer.
Setting the viewport X coordinate to 0 in `MoveToBottom` (as we were
previously doing) could result in the cursor being pushed off screen.
And if the operation itself was moving the cursor, that would …

Retain horizontal viewport offset when moving to bottom

---

src/cascadia/LocalTests_SettingsModel/DeserializationTests.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

The Settings UI exposes the `profiles.defaults` (PD) object. Today, we
remove PD if there's nothing in it. However, that causes problems with
the Settings UI, because we have no `Profile` object to bind to
(resulting in a crash). Rather than making the Settings UI create a PD,
and link it in the inheritance tree, it's much easier to just _always_
create and link the PD object.
#1564 - Settings UI (fixes a crash for this)
#7923 - Introduces inheritance
branch for testing)

Always create and link profiles.defaults object

---

src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp
src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsEditor/Profiles.cpp
src/cascadia/TerminalSettingsEditor/Profiles.h
src/cascadia/TerminalSettingsEditor/Profiles.idl
src/cascadia/TerminalSettingsEditor/Profiles.xaml
src/cascadia/TerminalSettingsModel/ColorScheme.idl

Binds `Profile.ColorScheme` to the list of Color Schemes available in the Settings UI.
#1564 - Settings UI
To my knowledge, there is no way to bind an `IMapView` to `ItemsSource`. `ItemsSource` requires an `IObservableVector`, so we need to manually populate `ColorSchemeList` when we navigate to the page.
`CurrentColorScheme` operates mostly like a standard getter/setter, except it needs to account for the upcoming scenario when a color scheme is renamed or deleted. For now, we fallback to Campbell if the scheme was not found. I would like to make it update automatically, but I feel that we have two approaches here:
1. TSM stores `Profile.ColorScheme` as a `ColorScheme` instead of only the name
2. When a color scheme name is modified in SUI, we iterate through all of the profiles and …

Bind Profile Color Schemes

---

doc/specs/settings-spec-template.md

I think we all agree that the current spec template doesn't always work. I thought this layout might be better for the kinds of settings discussions we have (more and more frequently now).
This is largely for discussion with the team - if there are other things we want added, changed, or if we just want to merge this in with the primary spec template, I'm all ears. 
* An example of using this spec: #8375

Add a template for discussing a settings change

---

src/cascadia/TerminalApp/CommandPalette.cpp

Skip further computations if:
* The list is empty
* No item is selected and we press "up" key 
(we do want to handle "down" key for CommandLineMode)
* Manual testing + UT

Fix crash in SelectNextItem when list is empty or no item selected

---

src/cascadia/TerminalApp/TerminalSettings.cpp
src/cascadia/TerminalSettingsModel/Profile.cpp
src/cascadia/TerminalSettingsModel/Profile.h
src/cascadia/TerminalSettingsModel/Profile.idl
src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h

`backgroundImageAlignment` is exposed as 1 setting in the JSON, but
stored as two separate settings (`HorizontalAlignment` and
`VerticalAlignment`). This PR introduces `ConvergedAlignment` as a flag
enum that can be a combination of horizontal and vertical Alignments.
TSM now solely uses this `ConvergedAlignment`, and TerminalSettings
performs a conversion from this new enum to the traditional
`HorizontalAlignment` and `VerticalAlignment` for consumption.
Manually tested changing the `backgroundImageAlignment` in my
settings.json and checking if the image updated appropriately.

Represent BackgroundImageAlignment as ConvergedAlignment

---

src/cascadia/TerminalControl/TermControl.cpp

This PR improves the clipboard handling logic of "drag and drop" in
TermControl, making it more useful and less likely to crash.
* Added support for two more categories of content, `ApplicationLink`
and `WebLink`.
* Reordered the ifs, making `StorageItem` the last clause. With WT being
a text-oriented application, I think we can safely assume that the
content being pasted is likely to be text/links.
* Catch possible exceptions during
`e.DataView().GetStorageItemsAsync()`.
Closes #7804

Improve clipboard handling in "drag and drop" scenario 

---

tools/runft.cmd
tools/runut.cmd

This corrects the path to `Terminal.Core.Unit.Tests.dll` in the `runut`
unit test script and makes the `runft` feature test script capable of
working with _Release_ builds as well as _Debug_ builds.
The path to `Terminal.Core.Unit.Tests.dll` changed when the project was
restructured, and the `runut` script was never updated to reflect that
change. That has now been corrected.
And the `runft` script used to be hard coded to look for tests in the
_Debug_ directory, but it has now been updated to use the
`%_LAST_BUILD_CONF%` environment variable, so it should work for both
_Debug_ and _Release_ builds.
I've manually confirmed that the `runut` and `runft` scripts now work as
expected.
Closes #8485

Correct paths in the the runut and runft test scripts

---

src/cascadia/TerminalCore/TerminalDispatch.cpp
src/cascadia/TerminalCore/TerminalDispatch.hpp
src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/ITermDispatch.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/termDispatch.hpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp

I was about to add `SetAnsiMode`/`ResetAnsiMode` for `SM` and `RM` when I
realized that we probably don't need yet another enum of mode types, set and
reset functions, and a mode helper for ANSI standard modes when we already have
one for DEC Private modes.
This commit:
1. Changes the enum `PrivateModeParams` to just be `ModeParams`
2. Differentiates ANSI Standard modes (IRM, KAM, SRM, ...) from DEC
Private modes (DECCOLM, DECCKM, ...) using a flag bit set in the enum
value.
3. Introduces a helper class for constructing these values much like
`VTID`. That helper takes a bitmask and applies it to an input to
produce the final enum value.
4. Dispatches all mode set/reset through a common Set/Reset and
`_ModeHelper` that uses the existing enum values.
[1] These modes are in separate …

Refactor DEC/ANSI modes to avoid duplication when we add SM/RM

---

src/host/getset.cpp
src/types/inc/viewport.hpp
src/types/viewport.cpp

When resizing the buffer in the `SetConsoleScreenBufferSize` and
`SetConsoleScreenBufferInfoEx` APIs, we have tests in place to make sure
that the resize doesn't result in the viewport extending past the bottom
or right of the buffer (since that can eventually result in exceptions
being thrown). Unfortunately these tests were using the wrong X
coordinate, so they failed to detect an overflow along the horizontal
axis. This PR corrects that mistake.
PR #8309 was where the overflow detection was initially added.
The original code was using the `Viewport::EndExclusive` method to
determine the extent of the viewport, mistakenly thinking that it
returned the bottom right coordinates (it actually returns the left
coordinate). So I've now added a `BottomRightExclusive` method to the
`Viewport` …

Correct horizontal coordinates in viewport overflow test

---

src/renderer/base/renderer.cpp

When the renderer is called on to render part of a line starting halfway
through a DBCS character (as can occur in conhost when the viewport is
offset horizontally), it could result in the character not being
displayed, and/or with following the characters drawn in the wrong
place. This PR is an attempt to fix those problems. 
The original code for handling the trailing half of fullwidth glyphs was
introduced in PR #4668 to fix issue #2191.
When the content being rendered starts with the trailing half of a DBCS
character, the renderer tries to move the `screenPoint` back a position,
so it can instead render the full character, but instructing the render
engine to trim off the left half of it.
If the X position was already in column 0, though, it would instead move
forward one position, …

Fix rendering of DBCS characters when partially off screen

---

tools/runut.cmd

This is the same root cause as #8485. We moved the output of a bunch of projects to be unified. We forgot to update all the test scripts.
In this case, the LocalTests were still using the old path that's _not_ under `bin/`

Fix the path to the local unittests in `runut`

---

src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
src/cascadia/LocalTests_SettingsModel/SettingsModel.LocalTests.vcxproj
src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/dll/TerminalApp.vcxproj
src/cascadia/TerminalApp/packages.config
src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
src/cascadia/TerminalSettingsModel/dll/Microsoft.Terminal.Settings.Model.vcxproj
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/cascadia/WindowsTerminal/packages.config
src/cascadia/WindowsTerminalUniversal/WindowsTerminalUniversal.vcxproj
src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj

This commit moves us to the Xaml prerelease (201202003) that is
equivalent to public stable release 2.5.
Remember, we need to use prereleases for some silly reason.

Update to Microsoft.UI.Xaml 2.5 "stable"

---

src/host/ft_host/InitTests.cpp

A bunch of our feature tests don't work reliably in CI. They rely on creating a new `OpenConsole.exe` window, then running the test _in that console_. As a part of that test setup, the test runner used to wait a second to attach to the newly created console. Then the test goes on it's merry way, assuming the console is ready to go. However, in CI, that might take more than a second. If it does, then the test would fail pretty immediately, as soon as it tries to get at the buffer of the new console.
This PR introduces a little retry loop to the test init. After attaching to the new console, we'll try and get at the screen buffer. If that fails, we'll wait a second and try again. We'll try 5 times total, before bailing entirely. Hopefully, this should mitigate most of the random CI failures …

Fix the feature tests with a retry

---

build/config/SignConfig.NuGet.xml
build/config/SignConfig.WindowsTerminal.xml

We've moved to the recommended internal code signing service
and no longer need these configurations.

Delete the old PackageES code signing configs

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/CommandPalette.h
src/cascadia/TerminalApp/CommandPalette.xaml
src/cascadia/TerminalApp/TerminalPage.cpp

So the implementation is somewhat dirty.
The ideas was nice - add lostFocusHandler
However it broke few things:
* In the TabSwitcher the ListItem must be focusable since otherwise 
the SingleSelectionMode behavior breaks. 
To address this I had to put the lostFocusHandler on the items as well
* When you click the flyout, the palette loses focus, 
which makes the terminal page to set the focus on the tab, closing the flyout. 
To address this I had to ensure the tab won't get focused once the flyout is open.
In addition, flyout should fix the focus before opening, 
otherwise alt+tab will put a focus on a tab row rather than on tab
* I also had to close the palette if the tab order changes.
To prevent inconsistencies.
Closes #8355

Make command palette ephemeral

---

src/cascadia/TerminalControl/SearchBoxControl.cpp
src/cascadia/TerminalControl/SearchBoxControl.h
src/cascadia/TerminalControl/SearchBoxControl.idl
src/cascadia/TerminalControl/TermControl.cpp

If a single line of text is selected, use it to populate the search box.
Closes #8307

Teach Find command to populate the search box with selected text 

---

src/cascadia/TerminalApp/TerminalTab.cpp

Made the tab icon smaller so that it is the same size as the other icons

Change tab close and rename icons to better fit the UI

---

src/cascadia/TerminalApp/TabHeaderControl.cpp

We've got similar logging around the command palette, we really should have the same logging on the tab renamer as well.
Look, it works

Add some logging around tab renamer usage

---

src/cascadia/TerminalApp/SettingsTab.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

#8420 removed `SwitchToTab()` as a responsibility of `TabBase` and replaces `_mruTabActions` with `_mruTabs` (conceptually). This PR fixes the build break by...
- replacing `TerminalPage`'s reference to the SettingsTab's SwitchToTab command, with a reference to the tab itself
- using that reference to maintain existing tab switching behavior
#1564 - Settings UI
#8420 - Command Palette + SwitchToTab refactoring
✅ Open SUI --> switch to a different tab --> try opening SUI again --> switches to existing SUI
✅ Open SUI --> switch to a different tab --> reorder tabs --> try opening SUI again --> switches to existing SUI

Fix SwitchToTab build break

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/MainPage.h
src/cascadia/TerminalSettingsEditor/Profiles.cpp
src/cascadia/TerminalSettingsEditor/Profiles.h
src/cascadia/TerminalSettingsEditor/Profiles.idl
src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h
src/cascadia/TerminalSettingsEditor/ViewModelHelpers.idl.h

It's generally accepted that in a graphical application you'll follow a
design pattern. The one this moves us towards is "MVVM" -- Model, View,
View Model.
In an ideal world, _all of our display smarts_ would be in the
ViewModel and the View would literally just be XAML. This moves us
closer to that reality.
The only thing the Profile page ViewModel does right now is proxy
requests through to the Profile behind it while adding some basic
invalidation logic and detection of a setting being set to its current
value.
We have to do this because (1) MVVM is better and (2) separation of
concerns dictates that TSM::Profile should **not** have a
Windows.UI.Xaml dependency (in IPropertyChangedNotifier). It therefore
**cannot** conform to Xaml's notion of what a ViewModel should be.
I've done this …

TSE: Replace TSM.Profile with a ProfileViewModel

---

doc/cascadia/profiles.schema.json
src/cascadia/LocalTests_TerminalApp/TabTests.cpp
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/Pane.h
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h
src/cascadia/TerminalSettingsModel/ActionArgs.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.h
src/cascadia/TerminalSettingsModel/ActionArgs.idl
src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h
src/cascadia/TerminalSettingsModel/defaults.json

Adds a "move to previous pane" and "move to next pane" keybinding, which
navigates to the last/first focused pane
We assign pane IDs on creation and maintain a vector of active pane IDs
in MRU order. Navigating panes by MRU then requires specifying which
pane ID we want to focus. 
From our offline discussion (thanks @zadjii-msft for the concise
description):
> For the record, the full spec I'm imagining is:
> 
> { command": { "action": "focus(Next|Prev)Pane", "order": "inOrder"|"mru", "useSwitcher": true|false } },
> 
> and order defaults to mru, and useSwitcher will default to true, when
> there is a switcher. So 
> 
> { command": { "action": "focusNextPane" } },
> { command": { "action": "focusNextPane", "order": "mru" } },
> 
> these are the same action. (but right now we don't support …

Support for navigating panes by MRU

---

src/cascadia/TerminalApp/TerminalPage.cpp

Upon tab close the tabview is responsible to issue tab selection for the next active tab.
However this doesn't happen when tabview is hidden.
There was a special treatment for this scenario for full screen mode.
Added the same treatment to focus mode (as the tabview is not visible in this case as well).
Manual tests

Fix next tab activation in focus mode upon tab closing

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.xaml

This changes the keyboard warning from a dialog to an `InfoBar`, which
we just got in MUX 2.5. Some users were unhappy that we'd always display
the dialog. We learned from the input team that this service _should_
always be enabled. We're also learing from users that they don't always
want it enabled. 
We're working with the Input team to help us figure out how this service
can be disabled _and the Terminal work just fine_. They're confident
that it _shouldn't_. For 99% of our users, they're right. So we don't
want to get rid of the dialog entirely, we want to understand how this
is possible. While we wait, let's make the message less aggressive.
This is instead of making a `iKnowWhatImDoingDisableTheKeyboardWarning`
setting to disable the dialog. Props to @cornem for suggesting the less …

Replace the KB Dialog with a InfoBar

---

src/host/selectionInput.cpp

In conhost there is a keyboard shortcut that applies colors to the
selected range of text, and another shortcut that searches for the
selected text, and applies colors to any matching content. The former
operation doesn't work correctly when the selection is wrapped, and both
have problems when the selected text spans DBCS characters. This PR
attempts to fix those issues.
The problem with the color section was that it applied the color to a
simple rect spanning the start and end points of the selection. I've now
updated it to use the `Selection::GetSelectionRects` method, which
correctly handles a wrapped range of lines, and makes sure that double
width characters are fully covered.
The problem with the "find-and-color" operation was in the way it
obtained the search text from the …

Fix color selection operations in conhost

---

src/buffer/out/textBuffer.cpp
src/buffer/out/textBuffer.hpp
src/cascadia/TerminalCore/TerminalSelection.cpp
src/host/ut_host/TextBufferTests.cpp

There are two issue with copy to clipboard when block is selected:
* We don't add new lines for lines that were wrapped
* We remove trailing whitespaces which is not intuitive in block selection.
Fixed the copy logic to always add newlines and not to remove
whitespaces when block is selected.
Even if shift is pressed!
* Added optional parameter to `TextBuffer::GetText` 
that allows to apply formatting (includeCRLF / trimming) 
to lines that were wrapped
* Changed `Terminal::RetrieveSelectedTextFromBuffer` 
to apply the following parameters when block is selected:
* includeCRLF = true
* trimTrailingWhitespaces = false
* apply the formatting above to all rows, including the ones 
that were wrapped 
* Manual tests for both block and standard selection
* Copy with both right-click and command …

Fix Copy to Clipboard to preserve visual structure of block selection

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/JsonUtils.h
src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h

Fix deserialization failure message of combined types

---

src/cascadia/TerminalApp/AppLogic.cpp

Calculate initial height properly

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

The tab tooltip is no longer empty when it was toggle zoomed.

Set Tab tooltip explicitly

---

doc/AddASetting.md

Merely fixed the capitalization of a word.
- Inside `doc/AddASetting.md`, on line 14, the sentence previously began with the verb "add" with a lowercase alphabet.
- I replaced "add" with "Add".
``` md
[12] ...  
[13]   2. Add matching fields to Settings.hpp
[14]     - Add getters, setters, the whole drill.
[15] ...
```

Minor grammatical fix

---

doc/cascadia/AddASetting.md

[Markdown Preview](https://github.com/microsoft/terminal/blob/dev/cazamor/sui/add-a-setting-doc/doc/cascadia/AddASetting.md)
This guide serves as a reference on how to add a setting to Windows Terminal. It covers...
- Terminal Settings Model changes
- Settings UI changes
- `TerminalSettings` changes
- Actions and action arguments
As a part of #6800 (Settings UI Follow Up Tasks)

doc: document how to add a setting to Windows Terminal

---

src/cascadia/TerminalApp/TerminalTab.cpp

Looks like recent regression:
1. Every time the tab gains focus (e.g., upon tab switching) we trigger `TaskbarProgressChanged`
2. This call results in `HideIcon` call
3. This call resets the value of Icon even if hide=false
4. This triggers reload of the image resulting in blinking

Prevent tab icon from blinking upon tab gaining focus

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

Teach terminal page to go to the last used tab in MRU mode

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.xaml

This commit introduces direct shortcut dispatch to TerminalPage, which
allows it to respond to key bindings before the command palette.
This allows the user to use shortcuts from the command palette while
it's open.
Closes #6679

Enable shortcut while CommandPalette is open 

---

src/cascadia/TerminalControl/TermControl.cpp

Closes https://github.com/microsoft/terminal/issues/5766

Allow single cell selection with Shift+Click

---

src/renderer/dx/CustomTextLayout.cpp
src/renderer/dx/CustomTextLayout.h
src/renderer/dx/CustomTextRenderer.h
src/renderer/dx/DxRenderer.cpp
src/renderer/dx/DxRenderer.hpp
src/renderer/gdi/gdirenderer.hpp
src/renderer/gdi/state.cpp

This PR adds support for the ANSI _italic_ graphic rendition attribute,
which is enabled by the `SGR 3` escape sequence.
For the GDI renderer, I've just created an additional italic variant of
the font, and then the `UpdateDrawingBrushes` method selects the
appropriate font variant into the device context based on the requested
text attributes.
It's a bit more complicated in the DX renderer, because we need both an
italic variant of the font, and a variant of the text format object. The
`CustomTextLayout` class also had to be updated to hold the two font and
format instances, and decide which of the variants to use based on a
`useItalicFont` property in the drawing context, initially set in the
`UpdateDrawingBrushes` method.
I've created some test content using a range of different …

Add support for the "italic" graphic rendition attribute

---

src/terminal/parser/stateMachine.cpp
src/terminal/parser/tracing.cpp

Fix memory leak that occurs from not dispatching the end of sequences on all actions (since it is buffering up all characters for trace reasons.) Also don't bother storing if no one is listening.
- We trace all the things leading up to the Action phase in the VT parser for ETW tracing to make debugging the parser easier, but we made two mistakes.
- At some point, three of the actions (related to print/execute) weren't dispatching the stored up sequence to tracing and not clearing it. So printing/executing in a giant run over and over caused the vector to bloat and bloat and bloat forever.
- We're storing things even when no one is listening. That's a waste.
- Watched it grow every time I did `type big.txt` under `taskman.exe`. Then watched it not do that after.
- I did technically WPR it …

Fix VT parser memory leak in tracing

---

src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

A part of the https://github.com/microsoft/terminal/issues/8415.
Very technical commit to simplify the terminal page code
towards additional steps of simplifying tab management.
No business logic should change.
A firs step in splitting https://github.com/microsoft/terminal/pull/8427

Simplify TerminalPage by introducing _GetFocusedTabImpl

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/TabPaletteItem.cpp
src/cascadia/TerminalApp/TabPaletteItem.h

Fix `TabPaletteItem` to hold only a weak reference to a tab.
This way we guarantee that the refcount of the closed tab 
gets to 0 immediately
(and that command palette cannot "raise it from the dead").
While this seems a correct thing to do, 
it is still not clear why the `FilteredCommand` itself 
(the one holding the `TabPaletteItem`) doesn't get released
until the UI is refreshed.
There is an impact of not registering to PropertyChanged event:
if the tab title changes during Tab Switcher navigation
the Tab Switcher item won't be updated immediately
(the change will apply next time the Tab Switcher is open).
Due to this change we need to make sure that the tabs binding
in https://github.com/microsoft/terminal/pull/8427
doesn't break the title / icon update.
* Manual testing
Closes #8651

Prevent Tab Switcher from increasing Tab refcount

---

src/tsf/TfEditSession.cpp

This PR fixes Korean IME to display a character being composed in conhost.

Fix Korean IME to display a character being composed in conhost

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.h
src/cascadia/TerminalSettingsModel/ActionArgs.idl
src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw

Performs a number of minor bugfixes related to the Settings UI:
- b5370a1 Dropdown bug:
- the dropdown would display the keybinding for the first `openSettings` found. So it would accidentally present and bind the one for the Settings UI.
- 91eb49e autogenerated name for opening Settings UI:
- the Settings UI keybinding would display "open settings file". This was updated to say "Open Settings UI".
- 1cadbf4 Profile Page navigation crash:
- the selected item off of a MUX navigation view returns a MUX NavViewItem (as opposed to WUX)
-  dd2f3e5 Hookup delete for Profile page navigation:
- missed a spot where we were manually navigating to the Profile page. So it wasn't hooked up properly
- 9fea6de Properly cast NavViewItem tags
- When we update the NavigationView's menu items, we were …

Polish OpenSettings action for Settings UI and Profile page navigation on refresh

---

src/buffer/out/AttrRow.cpp
src/buffer/out/AttrRow.hpp
src/buffer/out/AttrRowIterator.hpp
src/buffer/out/CharRow.hpp
src/buffer/out/textBuffer.cpp
src/host/precomp.h
src/host/tracing.cpp
src/host/tracing.hpp
src/inc/LibraryIncludes.h
src/server/ApiDispatchers.cpp
src/server/ApiMessage.cpp
src/server/ApiMessage.h

Make a few changes to memory usage throughout the application to reduce transient allocations from the `big.txt` test from ~213,000 to ~53,000.
Transient allocations are those that are new'd, used, then delete'd. Going back and forth to the system allocator for things we're just going to throw away or use rapidly again is a performance detriment. Not only is it a bunch of time to go ask the system with a syscall, it also hits a whole bunch of locks on the allocators. This PR identifies a few places where we were accidentally allocating and didn't mean to or were allocating and freeing just to turn around and allocate again. I chose other strategies to avoid this.
- Ran `big.txt` sample (~6MB file) before and after. Observed heap allocations with WPR.

Reduce Transient Allocations during Bulk Text Output

---

.github/actions/spell-check/dictionary/apis.txt
src/inc/LibraryIncludes.h
src/renderer/gdi/gdirenderer.hpp
src/renderer/gdi/paint.cpp
src/renderer/gdi/state.cpp

Converts the poly text out string and width buffers to use a memory pool since we free/alloc those every frame and are just going to reuse them over and over. 
- Sets up a PMR memory pool for the GDI Engine. It tends to alloc and free a bunch of little buffers during painting frames. The pool will likely hold onto that memory frame over frame, but we'd just be using it again and again and again anyway. So this way we avoid all the system memory allocator locks and syscalls.
- Ran `big.txt` about 10x in the window. Checked WPR/WPA profile output before/after.

Use memory pool for PolyTextOut items in GDI Renderer

---

src/interactivity/win32/SystemConfigurationProvider.cpp

* Commit f273aa679d4d9fb516678fc7ed5fc6495a8e8532 from os repository.
* We found and fixed this in November 2017, but I fumbled the replication and accidentally overwrote the commit. This digs it up from history and puts it back in our code.
* When the shortcut file cannot be read for whatever reason, we are setting the hotkey value to uninitialized data as we never initialize several members on the stack in this function. It just so happens that the one in the `dwHotkey` field is commonly `0x4c` or the letter `L` which is then sent into the window procedure to tell the OS to capture it as a global hotkey and foreground the `conhost.exe` that was started. We should realize the load failure and not set any hotkey at all and we should initialize the stack variables. This does both.

Initialize stack variables. check return code from shell lnk loading

---

.github/actions/spell-check/expect/a129ff14ec985d6b7bf09e296a831c955d41040b.txt
.github/actions/spell-check/expect/expect.txt
src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest
src/cascadia/ShellExtension/OpenTerminalHere.cpp
src/cascadia/ShellExtension/OpenTerminalHere.h
src/cascadia/ShellExtension/WindowsTerminalShellExt.vcxproj
src/cascadia/ShellExtension/pch.cpp
src/cascadia/TerminalConnection/TerminalConnection.vcxproj

This commit makes "Open in Windows Terminal" Context menu work again for
directory background even on system that OS fix is not applied.
This is a fallback solution to OS fixes mentioned in #6414.
While OS fix is on its way, we need a fallback that works on existing OS
versions.
The approach to this is: when no item is selected (nullptr for
IShellItemArray*), we use shell api to query the path of current active
Explorer window. A special case is handled for Windows Desktop. Once
we are able to obtain the path, we launch Windows Terminal with it.
1. Right click on desktop to bring up the Context menu, pick "Open in
Windows Terminal", verify that a terminal is opened with correct
initial path.
2. Open a few File Explorer windows, pick any window, navigate to a
folder, click on "Background" …

make "open terminal here" context menu work for directory background

---

src/cascadia/TerminalApp/MinMaxCloseControl.xaml

In dark mode (and high contrast mode), color animation of title bar
button uses wrong color.  Cause of this issue is using invalid data in
`ColorAnimation`.  I fixed this bug by changing `ColorAnimation` value
in XAML layout file.
According to a [forum post], `To` value of `ColorAnimation` must be
frozen. But original source code uses "color binding" which makes this
value dynamic.  As a result, the value set by default is always used,
that means, light mode.
So I added new resource named `CaptionButtonStrokeColor` and
`CaptionButtonBackgroundColor` which has static color value.
In light mode and dark mode, I set `SystemBaseHighColor` in the color
resource.  `SystemBaseHighColor` is the same as
`SystemControlForegroundBaseHighBrush.Color` which is originally used in
animation.
The …

Fix color animation bug of title bar buttons

---

src/cascadia/TerminalControl/TermControl.cpp

Enable underlining hyperlink on hover even if not focused

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/CommandPalette.h
src/cascadia/TerminalApp/CommandPalette.idl
src/cascadia/TerminalApp/TerminalPage.cpp

Following up https://github.com/microsoft/terminal/pull/8586 by @Hegunumo,
fully remove the command dispatching logic from Command Palette.
Currently Command Palette might dispatch command in Tab Switcher mode.
This leads to several inconsistencies:
* Only the commands with the same key modifier as an ATS anchor will be issued
* This command will not close the TabSwitcher 
(while commands issued from TerminalPage do).
Implementation details:
* Pass KeyMapping rather than binding to CommandPalette
* Use this mapping inside previewKeyDownHandler of ATS to detect
if previous tab or next tab bindings were engaged. 
No need to handle Ctrl+Tab explicitly anymore - 
it is handled as any other binding.
* Cleanup the logic in TerminalPage::_SelectNextTab 
that checks if CommandPalette is visible. …

Completely remove action dispatching from Command Palette

---

src/winconpty/ft_pty/ConPtyTests.cpp
src/winconpty/winconpty.cpp

It rather raises the question as to how we missed this.
Closes #8706

winconpty: close the pty host handle after terminating it

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalControl/TermControl.cpp

- Detect `\r` when warning about multi line paste
- Translate `\n` to `\r` on paste
Manual testing

Fix multi line paste detection and filtering

---

src/cascadia/TerminalSettingsModel/KeyMapping.cpp
src/cascadia/TerminalSettingsModel/KeyMapping.h

Store the order of the bindings and upon lookup prefer the binding
that was added last.
The defaults will always "loose" to user overrides.
Closes #2991

Teach flyouts and palette to prefer user bindings over defaults

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.xaml

When we display a dialog to warn the user that they are doing a
multi-line paste, we show the clipboard contents
The contents are shown in a scroll viewer with a fixed maximum height.
Closes #7997

Show clipboard contents in multiple line paste warning dialog

---

src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp
src/cascadia/TerminalApp/AppCommandlineArgs.cpp

I forgot to reset the `--size` argument to `split-pane` when I added it. This PR fixes that, and adds a test so I don't regress it again.
* Missed in #8543

Reset the `size` param between `split-pane` subcommands

---

src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
src/cascadia/TerminalSettingsModel/dll/Microsoft.Terminal.Settings.Model.vcxproj

Whenever you'd make a change to anything in the Terminal Control
project, then tried deploying the package, you'd get errors like
"Package contains two files with the same name and different content,
files are `Thing.xbf` and
`.../bin/x64/debug/TSM/TerminalControl/Thing.xbf`". It seems like
`GetPackagingOutputs` was double counting these xbfs as being both from
TerminalControl and also TSM&TSE. So if you'd change TerminalControl,
it'd change the xbf files, but not the ones in TSM/TSE, and then
eventually the wapproj would fail to put it all together.
This combination of flags seems to
* make mdmerge work
* make the packaging project work
* make a partial rebuild of TerminalControl followed by a deploy work
I'm hoping that this PR build will confirm that this works in CI as well.
Validated …

Fix the duplicate .xbf error after a TerminalControl build

---

src/cascadia/TerminalSettingsEditor/Profiles.cpp
src/cascadia/TerminalSettingsEditor/Profiles.h
src/cascadia/TerminalSettingsEditor/Profiles.xaml

Put some settings below the acrylic & background image settings. Those groups have controls that will become visible when the user enables the setting. If there's other controls below them, then it's less likely that the user has _exactly scrolled to the checkbox_. That means it's more likely that the newly visible controls will be on-screen.

Move the window settings below the acrylic settings

---

src/cascadia/TerminalSettingsEditor/Profiles.xaml

Do not allow the user to set commandline on the base layer of profiles
#8764 
Commandline option is hidden

sui: hide commandline and hidden option in base layer

---

src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Remove the setting for enabling/disabling the dialog that
shows up to confirm the closing of all tabs in the SUI
Closes #8757

Remove setting for close all tabs pop up

---

src/cascadia/TerminalSettingsEditor/EnumEntry.h
src/cascadia/TerminalSettingsEditor/Profiles.cpp
src/cascadia/TerminalSettingsEditor/Utils.h

Sorts the list of `EnumEntry`s that is used to create combo boxes and
radio buttons in the Settings UI. `INITIALIZE_BINDABLE_ENUM_SETTING`
sorts the list in increasing order of the enum values, whereas
`INITIALIZE_BINDABLE_ENUM_SETTING_REVERSE_ORDER` does so in decreasing
order.
I attempted sorting the `IObservableVector<EnumEntry>` using
`std::sort`, but I would get an error in
`winrt::Windows::Foundation::swap` (`C2665`). So instead, I did the
following approach:
- (unchanged) we're converting the `IMap` from EnumMappings into (1) a
map of localized strings and (2) the list for XAML controls
- instead of storing `EnumEntry`s to the `IObservableVector` directly,
store it to a `std::vector`
- sort the vector using `std::sort`
- _now_ initialize the …

Order enum settings according to enum values

---

src/cascadia/TerminalSettingsEditor/Profiles.cpp
src/cascadia/TerminalSettingsEditor/Profiles.h
src/cascadia/TerminalSettingsEditor/Profiles.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Add checkbox for 'inherit from parent process' for starting directory
When checked, the textbox and browse button are disabled
If the starting directory is empty, the checkbox is automatically checked

Add missing functionality to SUI

---

src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
src/cascadia/TerminalSettingsEditor/Interaction.cpp
src/cascadia/TerminalSettingsEditor/Interaction.h
src/cascadia/TerminalSettingsEditor/Interaction.idl
src/cascadia/TerminalSettingsEditor/Interaction.xaml
src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/EnumMappings.cpp
src/cascadia/TerminalSettingsModel/EnumMappings.h
src/cascadia/TerminalSettingsModel/EnumMappings.idl
src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h

Adds the tab switcher mode setting and copy format setting to the SUI
Closes #8755

Add missing settings to the settings UI

---

src/cascadia/WpfTerminalControl/TerminalControl.xaml.cs

Adds a negative value check for when the terminal window is hidden/show in VS
[Bug 1265984](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1265984): [Terminal] VS crashes when clicking the hidden terminal tab
Manual validation.

Added negative value check for resize newsize

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp
src/cascadia/TerminalSettingsModel/GlobalAppSettings.h
src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
src/cascadia/TerminalSettingsModel/TerminalWarnings.idl
src/cascadia/TerminalSettingsModel/defaults.json

Procedural solution for https://github.com/microsoft/terminal/issues/756.
Introduces a `startupActions` global setting. 
This setting is as string with the same format as actions in command line arguments.
It is used only if command line arguments were not provided
(aka running pure wt.exe).
The setting allows implicit new-tabs.
In the case of invalid syntax we show the warning dialog and ignore the setting.
The documentation PR is here: https://github.com/MicrosoftDocs/terminal/pull/217

Introduce startupActions in settings

---

src/inc/til/spsc.h
src/til/ut_til/SPSCTests.cpp

The following code didn't previously work as the assignment operators
didn't return a self reference:
```cpp
auto channel = til::spsc::channel<QueueItem>(100);
auto producer = std::move(channel.first);
channel.first = std::move(producer);
```
I've added a basic smoke test for `til::spsc`.
Closes #8695

Fix #8695: til::spsc assignment operators don't return anything

---

src/cascadia/TerminalApp/TabBase.cpp
src/cascadia/TerminalApp/TabBase.h
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

Currently the tab tool tip is the tab's title.
The PR teaches the TabBase to check if there is a switch to tab command 
associated with the current tab index,
if so concatenates the the relevant mapping to the too tip.
Of course, prefers user defined bindings to the default ones.
Moved tool tip logic to TabBase so SettingsTab has tooltip as well.

Teach tab tool tips to show key bindings

---

src/inc/til/bitmap.h
src/til/ut_til/BitmapTests.cpp

`til::details::bitmap<Allocator>` will use `Allocator` for its
`dynamic_bitset`, and it will use a rebound allocator for its run storage.
Allocator should be an allocator type storing `unsigned long long`, the
backing store type for `dynamic_bitset`.
I've introduced a type alias, `til::bitmap`, which papers over the
allocator choice for all existing code. I've also introduced a second
type alias, `til::pmr::bitmap`, which lets a consumer use the C++
polymorphic allocator system.
I chatted with @miniksa about whether to keep the "full" allocator
version in `details` or not. We decided that for the simplicity of the
`til` namespace, we would. If anybody has a compelling reason to use
`til::details::bitmap<Allocator>` directly, we can re-evaluate this
decision.

Give til::bitmap custom allocator support and add til::pmr::bitmap

---

src/cascadia/TerminalApp/TerminalPage.cpp

##Detailed Description of the Pull Request / Additional comments
A workaround for https://github.com/microsoft/microsoft-ui-xaml/issues/3945.
Thanks to @michael-hawker and @chingucoding for the suggested solution.

Fix tab selection to bring the tab into view

---

NuGet.Config

Cleans up a ton of competing and outdated sources from our NuGet.Config to improve reliability and maintainability.

Cleanup NuGet.Config file.

---

src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml
src/cascadia/TerminalSettingsEditor/CommonResources.xaml
src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
src/cascadia/TerminalSettingsEditor/Interaction.xaml
src/cascadia/TerminalSettingsEditor/Launch.xaml
src/cascadia/TerminalSettingsEditor/MainPage.xaml
src/cascadia/TerminalSettingsEditor/Profiles.xaml
src/cascadia/TerminalSettingsEditor/Rendering.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

The settings UI was _close_ to looking just right, it just needed some tweaks to adhere to the proper guidance: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/forms
This PR changes the font sizes, spacing, and layout of all of the pages to align with guidance.
Some pics:
Min width:
* Removed custom font sizing, WinUI adheres to guidance anyway
* 24px spacing between controls and 48px between groupings
* Controls shouldn't be next to each other (see Launch size)
* Technically Launch size is a grouping, so it gets upgraded to subtitle status
* Left margins for pages have been fixed to left align with the page titles
* Single checkboxes have been changed to toggle switches

Include UWP styling guidance in settings UI

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp

Upon a settings reload, we would select the correct navigation item for
a profile, but navigate to the old one. As a result, you would navigate
to the old page that points to a dead profile object. This would make it
appear like you did not discard/save the changes.
This bugfix navigates to the newly created profile, ensuring that your
changes are actually applied to the settings model's clone in use.
#8773 - Introduced the bug
- Navigate to "powershell" profile
- edit "tab title" value
- discard changes
Before: changes would persist unless you discarded changes again
Now: changes are discarded
Also verified expected behavior occurs when you click "save" instead of
"discard"

Bugfix: navigate to new profile ref on settings reload

---

.github/actions/spell-check/patterns/patterns.txt
src/cascadia/TerminalCore/ITerminalApi.hpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/cascadia/TerminalCore/TerminalDispatch.cpp
src/cascadia/TerminalCore/TerminalDispatch.hpp
src/terminal/adapter/DispatchTypes.hpp
src/terminal/adapter/ITermDispatch.hpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/adaptDispatch.hpp
src/terminal/adapter/termDispatch.hpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp

This adds the skeleton code for "bracketed paste mode" to the Windows
Terminal. No actual functionality is implemented yet, just the wiring
for handling DECSET/DECRST 2004.
References #395
Supersedes #7508

Add skeleton code for bracketed paste mode

---

src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp
src/cascadia/TerminalSettingsEditor/ColorSchemes.h
src/cascadia/TerminalSettingsEditor/ColorSchemes.idl
src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml
src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/MainPage.h
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettings.idl

This fixes a bug where renaming/deleting a color scheme would not update profiles that referenced it.
This also adds detection for renaming a color scheme to a name that is already in use, and adds appropriate UI for that.
`Model::CascadiaSettings` was updated to have a `UpdateColorSchemeReferences()` function that updates all profiles referencing the newly renamed color scheme.
`Editor::ColorSchemesPageNavigationState` now takes and exposes a `Model::CascadiaSettings`.
When a color scheme is renamed or deleted, we use `CascadiaSettings` to update our list of color schemes appropriately, then call `UpdateColorSchemeReferences()` to update the profiles.
The tricky part is that `Profile` does not store a direct reference to `ColorScheme`, but rather the name of the …

Bugfix: sync color scheme rename with profile reference

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/Profiles.xaml

This adds a "Name" text box to the Profile page in the Settings UI.
Any changes to the name/icon are propagated to the relevant
NavigationViewItem.
Base Layer does not have a "Name".

[Settings UI] Allow renaming a profile

---

src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/Pane.h
src/cascadia/TerminalApp/TabHeaderControl.h
src/cascadia/TerminalApp/TabHeaderControl.idl
src/cascadia/TerminalApp/TabHeaderControl.xaml
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

When we emit a BEL (visual or audible), show an indicator in the tab
header
If the tab the BEL is coming from is not focused when the BEL is raised,
the indicator in its header will be removed when the tab gains focus. If
the tab was already focused when the BEL was emitted, then the indicator
goes away after 2 seconds.
Closes #8106

Show indicator of bell in tab

---

src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp

This PR adds support for the `DECID` (Identify Device) escape sequence,
which allows for querying the terminal type in a way that is backwards
compatible with VT52 terminals.
This simply checks for the `ESC Z` sequence in the `ActionEscDispatch`
method of output state machine, and forwards the query to the existing
`DeviceAttributes` dispatch method, since the expected response is
identical to a `DA` report.
I've added an output engine test that verifies that the `ESC Z` sequence
is correctly interpreted as a `DA` query when in ANSI mode, and as a
VT52 identification query when in VT52 mode.
Closes #8857

Add support for the DECID report

---

src/cascadia/TerminalApp/CommandPalette.xaml

Fixing a typo I made (affecting only high contrast mode)
Closes #8884

Fix crash in command palette in high-contrast mode

---

src/cascadia/CascadiaPackage/CascadiaPackage.wapproj

Apparently, we don't need this `TargetRuntime`. That's what was causing VS to think that we were a C# project, and give us that warning. This is the solution we got from the owner of the `.wapproj` plugin.
* Introduced in c33883d8520e2efee233d4af0addff0775327e22, in PR #8062
Build and ran it fine. Changed TermControl, built and ran it fine. Now let's hope CI likes it.

Fix the erroneous TargetRuntime causing a warning in VS

---

src/cascadia/TerminalApp/TerminalPage.cpp

This is an extension of #8885. A lot of users have grown accustomed to
using `closePane` to close a tab. This adds `closePane` to the list of
keybindings accepted by #8885, and modifies the `closePane` code to
close the Settings UI if we are in a `SettingsTab`.
#6800: Settings UI Epic
#8885: PR - Settings UI should respect key bindings (temporary solution)
#8882: Issue - Settings UI should respect key bindings

Allow ClosePane to close the Settings UI

---

samples/PixelShaders/README.md

Example shows attribute `experimental.pixelShaderEffect`, should be `experimental.pixelShaderPath`

shaders: fix setting name in README.md

---

samples/PixelShaders/README.md

Just two typo fixes
No
I clicked "preview" on the markdown to make sure it renders OK 😄

Fix pixel shader typo in README 

---

src/cascadia/TerminalApp/TabHeaderControl.cpp

* We dismiss the edit each time `HeaderRenamerTextBox` loses focus
* Unfortunately, this applies also to scenario where the context menu
(copy, paste, select, etc.) is open with the right-click
* The fix is to ignore focus loss if `HeaderRenamerTextBox().ContextFlyout()` is open.
* We can do it as upon the fly-out dismiss the text box regains the focus.

Prevent context menu of tab renamer text box from canceling edit

---

src/cascadia/TerminalSettingsEditor/Interaction.xaml
src/cascadia/TerminalSettingsEditor/Launch.xaml

Properly binds `CurrentLaunchMode` and `CurrentTabSwitcherMode` in the Settings UI. The default mode is `OneTime`, resulting in the setting never being set.
I performed a regex search of all "SelectedItem" bindings and these were the only two that were not properly bound.
Modified tab switcher mode and launch mode via the settings UI. Then saved. Before, the settings would revert back and not get applied. Now they got applied.
Closes #8947

Bind LaunchMode and TabSwitcherMode properly in SUI

---

src/cascadia/TerminalControl/TermControl.cpp

If there is data being output when a tab is closed, that can sometimes
result in the application crashing, because the renderer may still be in
use at the time is it destroyed. This PR attempts to prevent that from
happening by adding a lock in the `TermControl::Close` method.
What we're trying to prevent is the connection thread still being
active, and potentially accessing the renderer, after it has been
destroyed. So by acquiring the terminal lock in `TermControl::Close`,
after we've stopped accepting new output, we can be sure that the
connection thread is no longer active (it holds the lock while it is
processing output). So once we've acquired and released the lock, it
should be safe to tear down and destroy the renderer.
While this crash is difficult to reproduce in general usage, …

Fix crash in terminal when tab closed while data is being output

---

src/cascadia/TerminalApp/TerminalPage.cpp

Oops, winrt `IVector`s need to be manually initialized, when default-constructed `std::vector`s didn't. Simple oversight.
Ran the terminal with 
```json
"schemes" :
[ {} ]
```
First the crash repro'd, now it doesn't.

Manually initialize the warnings vector to prevent a crash on launch

---

src/renderer/dx/DxRenderer.cpp
src/renderer/dx/DxRenderer.hpp

Correctly sets the time input on the pixelShaderSettings struct, which was previously hard-coded to `0.0f`. 
I added a private field to `DxEngine` to store the timestamp for when a custom shader is first loaded. The field is initialized in `_SetupTerminalEffects()`, and the calculated time value (seconds since the timestamp) passed to the actual shader is set in `_ComputePixelShaderSettings()`. 
There remains an issue with with jerky animation due to the renderer not repainting when the window contents are not updated (see discussion in the original issue).
This is basically my first time writing C++; constructive review is enthusiastically welcomed 🙂
I manually tested using a variety of simple shaders that rely on time input for animation.

Fix shader time input

---

src/terminal/input/terminalInput.cpp

Pressing Ctrl+\ produces `^\` using the US keyboard layout, thanks to Ctrl-key mappings inside the keyboard layout, whereas some layouts, like the UK extended layout, don't contain those. This causes the character value to be zero and previously caused no VT sequence to be generated under these situations. This PR employs `MapVirtualKeyW` to infer the missing characters.
As a side effect this PR effectively causes _all_ major keys on the keyboard to produce Ctrl+combinations now.
Compared all major keys in combination with Ctrl with the app store version of Terminal using `showkey` in WSL. All keys that previously worked still appear to continue to work.

Fix #8458: Handle all Ctrl-key combinations

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

This should technically be a lowercase 'u'. We don't have to merge this until after 1.6 because of localization, but I figured I'd make the PR for it.

Nit: update string in cursor shape

---

src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp

This adds the support for chaining OSC 10-12, allowing users to set all
of them at once.
**BREAKING CHANGE**
Before this PR, the OSC 10/11/12 command will only be dispatched iff the
first color is valid. This is no longer true. The new implementation
strictly follows xterm's behavior. Each color is treated independently.
For example, `\e]10;invalid;white\e\\` is effectively `\e]11;white\e\\`.
Tests added. Manually tested.
Main OSC color tracking issue: #942
OSC 4 & Initial OSC 10-12 PR: #7578
Closes one item in #942

Add support for chaining OSC 10-12

---

tools/OpenConsole.psm1
tools/tests.xml

* Fix the incorrect `terminalCore` path in `tests.xml`
* Change the `-TaefArgs` argument of `Invoke-OpenConsoleTests` and
`Invoke-TaefInNewWindow` to be `[]string`, allowing multiple arguments
to be passed to TAEF

Fix issues in tests.xml and OpenConsole.psm1

---

src/cascadia/TerminalCore/TerminalDispatch.cpp
src/cascadia/UnitTests_TerminalCore/TerminalApiTest.cpp

This PR fixes the parsing of OSC 9;9 sequences with path surrounded by
quotation marks.
Original OSC 9;9 PR: #8330 
Unit test added. Manually tested with oh-my-posh.
Closes #8930

Improve OSC 9;9 parsing logic & add tests

---

src/cascadia/TerminalControl/TermControl.cpp

Ensures that:
* All hyperlink related logic is running on unfocused pane
* All unrelated logic is not running on unfocused pane
Closes #8925

Fix hyperlink not de-underlined in unfocused pane

---

src/cascadia/LocalTests_SettingsModel/SerializationTests.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

"disabledProfileSources" is saved to `CascadiaSettings` _not_ `GlobalAppSettings` (and, even then, it's only read when it's used, never saved). This PR specifically detects if it was defined in settings.json, and copies it over when the settings are serialized.
#6800 - Settings UI epic
1. Added "disabledProfileSources" to settings.json, then serialized. --> "disabledProfileSources" is now maintained.
2. Updated `CascadiaSettings` serialization test
Closes #9032

Serialize 'disabledProfileSources'

---

src/cascadia/TerminalApp/CommandPalette.cpp

The command palette is ephemeral and is dismissed if the focus
moves to an element which is not the palette's descendant.
Unfortunately, this breaks the (right-click) context menu,
as it  is not a child of the palette
(popups are hosted on a separate root element).

Prevent command palette from closing on right click

---

.github/actions/spelling/excludes.txt
.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/types/inc/utils.hpp
src/types/ut_types/UtilsTests.cpp
src/types/utils.cpp

This adds "paste filtering" & "bracketed paste mode" to the Windows
Terminal.
I've moved the paste handling code in `TerminalControl` to
`Microsoft::Console::Util` to be able to easily test it, and the paste
transformer from `TerminalControl` to `TerminalCore`.
Supersedes #7508
References #395 (overall bracketed paste support request)
Tests added. Manually tested.

Add support for paste filtering and bracketed paste mode

---

.github/actions/spelling/dictionary/microsoft.txt
src/terminal/input/terminalInput.cpp

Fixes #5205, by replacing another use of `MapVirtualKeyW` with `ToUnicodeEx`.
The latter just seems to be much more consistent at translating key combinations in general.
In this particular case though it fixes the issue, because there's no differentiation in `MapVirtualKeyW` for whether it failed to return a character (`'\0'`) or succeeded in turning `^@` into `'\0'`.
`ToUnicodeEx` on the other hand returns the success state separately from the translated character.
This PR changes the behavior of the `Ctrl+Alt+Key` handling slightly:
⚠️ `ToUnicodeEx` returns unshifted characters. ⚠️
For instance `Ctrl+Alt+a` is now turned into `^[^a`. Due to how ASCII works this is essentially the same though because `'A' & 0b11111` and `'a' & 0b11111` are the same.
* Run `showkey -a`
* Ensured …

Fixed #5205: Ctrl+Alt+2 doesn't send ^[^@

---

src/cascadia/TerminalApp/TerminalSettings.cpp
src/cascadia/TerminalApp/TerminalSettings.h

There was a mistake in #8602, this change fixes that (`using` and `include` moved to cpp file)

Quickly fix a mistake in #8602

---

doc/specs/#597 - Tab Sizing.md

This is the spec for #597 
I am proposing the `tabWidthMode` feature be added first, then `tabWidthMin` and `tabWidthMax` be added in a later release.
PR: #3876

Spec for Tab Sizing

---

src/renderer/base/RenderEngineBase.cpp
src/renderer/base/renderer.cpp
src/renderer/dx/DxRenderer.cpp
src/renderer/dx/DxRenderer.hpp
src/renderer/inc/IRenderEngine.hpp
src/renderer/inc/RenderEngineBase.hpp

Teaches renderer base to keep thread alive if engine requests it.
`DxEngine` now requests it if shaders are on.
- The render engine interface now has a true/false to return whether the
specific renderer wants another frame to immediately follow up. The
renderer base will ask for this information as it ends the paint on
any particular engine (which is the time where invalid regions are
typically cleaned up) and just poke the render thread the same as if
an invalidation request came in from outside of render-land. That will
trigger the render thread to just keep moving in the same way as any
other invalidation.
I promised this in #8994

Teach the renderer to keep thread alive if engine requests it

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

It appears as though the optimizer is generating a sequence of
instructions on x64 that results in a nonsense std::wstring_view being
passed to SetPixelShaderPath when it's converted from a winrt::hstring.
Initially, I suspected that the issue was in us caching `_settings`
before we broke off the coroutine to update settings on the UI thread. I
implemented a quick fix for this (applying values off the new settings
object while also storing it in the control instance), but it didn't
actually lead anywhere. I do think it's the right thing to do for code
health's sake. Pankaj already changed how this works in 1.7: we no
longer (ever) re-seat the `_settings` reference... we only ever change
its parentage. Whether this is right or wrong is not for this paragraph
to discuss.
Eventually, I …

Work around a (likely) optimizer issue with SetPixelShaderPath

---

src/cascadia/LocalTests_SettingsModel/ColorSchemeTests.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp

`CascadiaSettings::UpdateColorSchemeReferences` had two bugs in it:
1. we would never check/update the base layer
2. we would explicitly set the color scheme on a profile referencing the
old name
This PR fixes both of those issues by checking/updating the base layer,
and ensuring that we check if a profile has an explicit reference before
updating it.
Since the affected code is in TSM, I also created an automated local
test.
Bug repro steps.
Specifically tested [DHowett's scenario] too.
Test added.
Closes #9094 
[DHowett's scenario]: https://github.com/microsoft/terminal/issues/9094#issuecomment-776412781

Bugfix: update color scheme references properly

---

src/cascadia/TerminalControl/TermControl.cpp

Avoid sending mouse move / wheel / release to Terminal in the first place.
This kind of short-circuiting will prevent us reaching the
attempt to send input to connection
(that could result in the warning dialog in the read-only mode)
Closes #9074

Prevent read-only warning on mouse move, wheel and release

---

src/cascadia/CascadiaPackage/CascadiaPackage.wapproj

A bug in VS 16.8 makes the WAP packaging project copy System.Core.dll
from the CLR into all WAP packages. We don't need it, and it adds 300kb
to our package (670kb uncompressed).
VS 16.9 sets the AddAdditionalExplicitAssemblyReferences to suppress
this assembly. If we do the same, we can avoid the reference *and* be
eady for VS 16.9.

Remove accidental System.Core.dll from CascadiaPackage

---

src/cascadia/TerminalApp/ColorPickupFlyout.xaml

Add the keyboard navigation to the color picker. 
Test manually.
Tested manually

Add Keyboard Navigation To Color Picker

---

src/cascadia/TerminalApp/TabHeaderControl.cpp
src/cascadia/TerminalApp/TabHeaderControl.h
src/cascadia/TerminalApp/TabHeaderControl.idl
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

After rename ends (either by enter or escape) the rename box
gets collapsed and the focus moves to the next tab stop
in the TabView (e.g., new tab button).
To overcome this:
* Added RenameEnded event to TabHeaderControl
* Forwarded it as RenamerDeactivated from TerminalTab
* Registered in the TerminalPage to focus the active control upon
RenamerDeactivated if focus didn't move to tab menu.
This means, no matter how you close the renamer,
the current terminal gains the focus.

Teach tab to focus terminal after rename

---

src/cascadia/WpfTerminalControl/TerminalContainer.cs
src/cascadia/WpfTerminalControl/TerminalControl.xaml.cs

The terminal WPF container might have a (0,0) render size when VS
eagerly attempts to initialize the terminal tool window when it is
pinned during startup, but no actual UI is shown due to the VS welcome
dialog that shows up before VS can build the terminal tool window.
We've fixed this issue previously in other areas but only recently did
we get a complete enough dump to find the corner cases for this issue. 
This should patch all the gaps that cause this bug.
I've manually validated the scenarios shown in the user dumps.

wpf: prevent a 0 size when VS builds the Terminal window too early

---

src/cascadia/TerminalApp/CommandPalette.xaml

Fixes a regression of command palette accessibility. The regression was
introduced in #8377 by setting `IsTabStop` to false. Though the commands
would light up, the focus didn't technically get on the command, so the
screen reader would just read the text box.
Opened the command palette while NVDA is active. It now reads the
commands as focus moves on them.

Fix command palette accessibility

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.xaml

Introduced PointerExited handler to nullify last hovered cell
(which will also de-underline the hyperlink if required).
Closes #9141

Ensure hyperlinks de-underline when pointer leaves terminal

---

src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl

In the FFM mode, hovering on the pane might dismiss renamer.
To address this we want to make sure that FFM is applied
only if the Terminal Tab is focused.

Fix FFM to apply only if tab is focused

---

.github/actions/spelling/dictionary/apis.txt
src/cascadia/TerminalSettingsEditor/EnumEntry.h
src/cascadia/TerminalSettingsEditor/EnumEntry.idl
src/cascadia/TerminalSettingsModel/ColorScheme.h
src/cascadia/TerminalSettingsModel/ColorScheme.idl
src/cascadia/TerminalSettingsModel/Profile.h
src/cascadia/TerminalSettingsModel/Profile.idl

`ComboBox` has a text search function that allows users to type letters, and the `ComboBoxItem` starting with those letters is shown. In order to enable this functionality, the underlying items must be `IStringable`. This exposes a `ToString()` function and fixes all of our issues.
This PR adds the `IStringable` interface to `ColorScheme`, `Profile`, and `EnumEntry`.
#8768 - Keyboard Navigation
https://github.com/microsoft/microsoft-ui-xaml/issues/4182 - discussion with WinUI about how to overcome this issue
Tested...
- Launch > Default Profile
- Color Schemes > Name
- Profile > Appearance > Color scheme
- Profile > Appearance > Font weight
Also tested radio buttons, but those still don't work, unfortunately. Looks like they don't have the same underlying …

Enable text search on combo boxes

---

src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp
src/cascadia/TerminalSettingsEditor/ColorSchemes.h
src/cascadia/TerminalSettingsEditor/ColorSchemes.idl
src/cascadia/TerminalSettingsEditor/ColorSchemes.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

This PR performs a large overall polish of the color schemes page:
- Ensures keyboard navigation is holistically improved (i.e. fully
accessible, no lost focus, etc...)
- Adds tooltips and automation properties to all controls
- Redesigns the page according to @mdtauk's approved design
([link](https://github.com/microsoft/terminal/pull/8997#issuecomment-771623842)).
Note, there are some minor modifications to the design that were
approved by @cinnamon-msft.
- Automatically reflow's the color buttons when they do not fit in
horizontal mode
- Redesign
- a data template was introduced to make color representation
consistent and straightforward
- `ContentControl` is used to hold a reference to the
`ColorTableEntry` and represent it properly using the aforementioned
data template.
- The design …

Redesign color schemes page

---

src/cascadia/TerminalApp/TerminalTab.cpp

Regardless of whether the bellstyle is set to visual,
show the bell indicator in the tab header

Always show the bell indicator when BEL is emitted

---

src/cascadia/LocalTests_TerminalApp/FilteredCommandTests.cpp

Fixes exception in FilteredCommandTests, caused due to
an attempt to instantiate PropertyChangedEventArgs on non-UI thread.
Though the diff might look scary it is just wrapping with `RunOnUIThread`

Fix FilteredCommand tests to run on UI thread

---

res/terminal/Terminal.svg
res/terminal/Terminal_Dev_HC.svg
res/terminal/Terminal_HC.svg

A header line is missing from a few `.svg` files, denying their use (via
a security error) in WordPress (if svg support is enabled). The upload
is rejected even though the web browser could display the image if it
were dragged into its own tab.
The `.svg` images appear to have been edited at different times and with
different tools.  Their contents are in a different style.  Two of them
are beautiful and the rest do not follow suit and do not function the
same.
I don't know enough to make them all the same style, but changes can be
made to three of them to make them work the way I was expecting (see
below).
- Perform the change with a text editor
- Open a new WordPress post page
- Drag-and-drop the changed file into that WordPress edit box
- (The WordPress media upload dialog appears and …

res: prepend XML line to SVG files, to pass strict svg checks

---

src/cascadia/TerminalApp/CommandPalette.xaml

The command palette's list items explicitly specify the "AcceleratorKey"
property (for UIA) and set it to the key binding. Putting it in a label
inside the list item makes Narrator read it out twice ("New Tab ...
ctrl+shift+t ... ctrl+shift+t").
Addresses #7913 (to be closed when a11y re-evaluates)

Hide the Command Palette's key binding label from UIA

---

src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h

This PR removes access to the Settings UI for v1.6 stable. Any attempts to bind the Settings UI result in a parsing error as shown below:

[v1.6 ONLY] Make Settings UI inaccessible

---

src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp
src/cascadia/LocalTests_TerminalApp/pch.h
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h

When the user executes `--help`, make sure we force the creation of a new window, so that the `MessageBox` will actually appear. 
Add tests too. 
I'm gonna have to immediately rewrite those tests for https://github.com/microsoft/terminal/projects/5#card-51431478, but this issue is ship-blocking so I don't care

Fix `wt --help`

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

It appears as though the optimizer is generating a sequence of
instructions on x64 that results in a nonsense std::wstring_view being
passed to SetPixelShaderPath when it's converted from a winrt::hstring.
Initially, I suspected that the issue was in us caching `_settings`
before we broke off the coroutine to update settings on the UI thread. I
implemented a quick fix for this (applying values off the new settings
object while also storing it in the control instance), but it didn't
actually lead anywhere. I do think it's the right thing to do for code
health's sake. Pankaj already changed how this works in 1.7: we no
longer (ever) re-seat the `_settings` reference... we only ever change
its parentage. Whether this is right or wrong is not for this paragraph
to discuss.
Eventually, I …

PICK: Work around an optimizer issue with SetPixelShaderPath

---

src/cascadia/TerminalApp/TabHeaderControl.cpp

TabHeader: put TraceLogging events in the right category

---

src/cascadia/TerminalApp/ActionPaletteItem.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalSettingsEditor/Actions.cpp
src/cascadia/TerminalSettingsEditor/Actions.h
src/cascadia/TerminalSettingsEditor/Actions.idl
src/cascadia/TerminalSettingsEditor/Actions.xaml
src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/MainPage.xaml
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/Command.cpp
src/cascadia/TerminalSettingsModel/Command.h
src/cascadia/TerminalSettingsModel/Command.idl

This was the only thing blocking me from signing off on #9224 in 1.7.
! CHANGE WARNING !
If we bind to `T.S.M.Command`s in XAML, then the compiler gets _very
angry_ at us. It generates two different versions of
`GetReferenceTypeMember_Icon` in `XamlTypeInfo.g.cpp`. Presumably
because there's an Icon on a NavViewItem and an Icon on a Command. We
don't really know why. Fortunately, the fix is "rename Command::Icon" to
"Command::IconPath". It's dumb, but it works. Thanks for the help with
that one Carlos ☺️ 
Unblocks #9224

Add a simple page for keybindings

---

src/cascadia/TerminalApp/TerminalTab.cpp

This sets the automation property (name) on the tab view item we expose in XAML.
Tested under NVDA and Accessibility Insights

Update automation properties for tab header control

---

src/cascadia/TerminalApp/CommandPalette.xaml
src/cascadia/TerminalApp/HasNestedCommandsVisibilityConverter.cpp
src/cascadia/TerminalApp/HasNestedCommandsVisibilityConverter.h
src/cascadia/TerminalApp/HasNestedCommandsVisibilityConverter.idl
src/cascadia/TerminalApp/Resources/en-US/Resources.resw

This adds help text (automation property) to command palette commands that expand to more options.
If I have a nested command called "color tab", NVDA reads it as...
"Color tab. More options. 5 of 79."

[v1.6] Add help text to 'more options' in command palette

---

src/cascadia/TerminalApp/TerminalPage.cpp

Fix for #9280 
In #8602, we started passing a child of the `TerminalSettings` to the control upon tab initialization, but forgot to do the same when new controls get created on a pane split. 
Settings reload with multiple panes works

Fix settings not updating on reload

---

src/cascadia/TerminalApp/TerminalPage.cpp

Fixes a bug introduced by #9224 where the wrong keyboard accelerator
would appear in the new tab dropdown. We were looking for the "settings
file" version of the action, as opposed to the "settings UI" version. 
#9224 - Settings UI as default

Update dropdown's settings keyboard accelerator

---

src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

Turns out we were adding the fragment source to profiles we update. This
PR fixes it so we keep the original source. 
Existing profile settings are maintained
Closes #9290

Fix updating with fragments ignoring original profile settings

---

.github/actions/spelling/dictionary/apis.txt
.github/actions/spelling/dictionary/microsoft.txt
.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json
tools/OpenConsole.psm1

I wanted to start using VScode. It wasn't easy. I wrote some tasks that allow us to build the various flavors of OpenConsole and Windows Terminal from one of the tasks. I also wrote a task that allows registration of the loose Windows Terminal package and a shortcut one to launch it. 
Also it was grinding away at its own Intellisense forever because it was indexing obj, bin, packages, etc. I excluded those.
Things should be easier now for folks in general. I expect we'll make more task types in the future.

Create settings/tasks definitions for VScode builds and registration

---

src/cascadia/TerminalSettingsEditor/Profiles.xaml

Add `Minimum` and `Maximum` for the cursor height numberbox in the SUI.
Add `Minimum` for the history size numberbox in the SUI.
Manual validation

[Settings UI] Clamp vintage cursor height and history size

---

src/cascadia/TerminalApp/TabBase.cpp

We were using the wrong close icon for the settings tab. This is a side effect of `TerminalTab` overriding `TabBase`'s implementation.
Closes #9317

Change SettingsTab close icon to be smaller

---

src/cascadia/LocalTests_TerminalApp/TabTests.cpp
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

Introduce duplicate tab menu

---

src/cascadia/TerminalControl/TermControl.cpp

Fix TermControl initialization to pre-seed working dir

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/AppCommandlineArgs.cpp
src/cascadia/TerminalApp/AppCommandlineArgs.h
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalSettings.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.h
src/cascadia/TerminalSettingsModel/ActionArgs.idl

Introduce optional `suppressApplicationTitle` in to `NewTerminalArgs`.
When set (either to true or false) overrides profile configuration.
Introduce `--suppressApplicationTitle` flag to command line arguments.
When provided for sub=command, 
sets the value in the relevant `NewTerminalArgs` to `true`

 Allow configuring suppressApplicationTitle in new tab/pane/window commands

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

The selection with shift is quite broken in 1.6.
It started with #8611 that introduces cell selection on `shift+click`.
This change resulted in the following defect:
`shift+double-click`, `shift+triple-click` select only parts  of the word.
The reason for this is that the first `shift+click` establishes the selection,
while the consequent clicks simply extend it to the relevant boundary
(aka word / line boundary)
However, the logic was broken even before #8611.
For instance, `shift+triple-click` had exactly the same handicap:
`shift+double-click` was establishing the selection and the
third click was simply extending it to the line boundary.
This PR addresses the both defects in the following manner:
upon multi-click that starts new selection we establish
a new selection on every …

Fix selection logic with shift on multi-click

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalSettingsEditor/Profiles.xaml
src/renderer/dx/CustomTextRenderer.cpp
src/renderer/dx/CustomTextRenderer.h

Change the vintage cursor height number box to a slider.
Related:  #9370
It seems like the cursor height couldn't be lower than 25 percent regardless of the given value, so I've changed the `MinCursorHeightPercent` in CustomTextRenderer header file.
Manual validation

[Settings UI] Represent Cursor Height as a slider

---

src/cascadia/TerminalApp/MinMaxCloseControl.cpp
src/cascadia/TerminalApp/MinMaxCloseControl.xaml
src/cascadia/TerminalApp/Resources/en-US/Resources.resw

Instead of displaying "Maximize" in the tooltip for the maximize/restore button even when the window is maximized, it now displays "Restore Down".
Fixes #5693

Display correct tooltip when window is maximized

---

src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TabRowControl.xaml
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

Shift+click on a profile to open a new wt window with that profile. Or, shift+click on the '+' button to open a new wt window with the default profile. 
Manual testing

Allow shift+click on a profile to open a new window

---

src/cascadia/TerminalControl/TermControl.cpp

In mouse mode:
* Underline hyperlinks
* Activate hyperlink on ctrl+click rather than sending input to VT

Allow interaction with hyperlinks in mouse mode

---

src/common.build.pre.props

Git may create folders for submodules; let's make sure they're populated.

submodule check: actually check for a real file in the repo

---

src/cascadia/Remoting/WindowActivatedArgs.h
src/cascadia/Remoting/packages.config
src/cascadia/ShellExtension/packages.config
src/cascadia/TerminalApp/packages.config
src/cascadia/TerminalAzBridge/packages.config
src/cascadia/TerminalConnection/packages.config
src/cascadia/TerminalControl/packages.config
src/cascadia/TerminalCore/packages.config
src/cascadia/TerminalSettingsEditor/packages.config
src/cascadia/TerminalSettingsModel/packages.config
src/cascadia/WinRTUtils/packages.config
src/cascadia/WindowsTerminal/packages.config
src/cascadia/WindowsTerminalUniversal/packages.config
src/cppwinrt.build.post.props
src/cppwinrt.build.pre.props

This update shrinks our binaries a little bit.
From a representative build on VS 16.8:
Note   | App     | Control | Connection | TSE     | WT     | Total   | msix (zip) |
--     | --      | --      | --         | --      | --     | --      | --         |
Before | 2610176 | 1006592 | 433152     | 1352192 | 321536 | 5723648 | 8336910    |
After  | 2532352 | 986624  | 431104     | 1312768 | 313344 | 5576192 | 8287648    |
Delta  | 77824   | 19968   | 2048       | 39424   | 8192   | 147456  | 49262      |
%Delta | 2.98%   | 1.98%   | 0.47%      | 2.92%   | 2.55%  | 2.58%   | 0.59%      |

Update C++/WinRT to 2.0.210309.3

---

.github/actions/spelling/expect/expect.txt
src/common.build.pre.props

I've also taken the opportunity to kill the xxxFullPDB trick. The
intermediate PDB is allowed to remain "vc141.pdb" or whatever it wants
to be. PDBs are now simply named after their projects, as was always
tradition.

Force DebugFull PDBs on all build types

---

src/cascadia/TerminalControl/TermControl.cpp

When working on #9403 I completely forgot that
double-click and triple-click should work even without shift.
Fixed it by allowing multi-selection even if not shift is pressed.
Closes #9453

Fix selection on multi-click with no shift

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

Since #8602 merged, we need to pass a child of the settings object to
the TermControl upon initializing it. Since this happens in a few places
in `TerminalPage`, its probably best to use a helper. 
Closes #9292

Add a helper function to initialize TermControls in TerminalPage

---

src/cascadia/LocalTests_SettingsModel/DeserializationTests.cpp
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/ShortcutActionDispatch.cpp
src/cascadia/TerminalSettingsModel/Command.cpp
src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp
src/cascadia/TerminalSettingsModel/TerminalWarnings.idl

Currently, when loading command with sub-commands that fail to parse,
we result with command that:
* Is not considered nested (has no sub-commands)
* Has no action of its own
The commit contains a few changes:
1. Protection in the dispatch that will prevent NPE
2. Change in the command parsing that will no load
a command if all its sub-commands failed to parse
3. We will add a warning in this case (the solution is somewhat
hacky, due to the hack that was there previously)
When such command is passed to a dispatch we crash with NPE.
Closes #9448

Invalidate nested command with no valid subcommands

---

src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

When loading fragments, check if the public folder is not null first
Closes #9473

Check if found folder is not null when loading fragments

---

.github/actions/spelling/dictionary/microsoft.txt
README.md

Updated README.md to add instructions for installing via the command
line. This is useful when the Microsoft Store is not available which is
the case in Windows Sandbox.
This completes what was started in #6942
Closes #9467

doc: add PowerShell install instructions added

---

tools/OpenConsole.psm1

Saw this while snooping around, the gci command on PowerShell core seems
to store the full path in the variable as oppose to just the leaf.
The other modification is to use the PowerShell module that vs ships to
setup the environment.

OpenConsole.psm1: use DevShell module; tidy up for PowerShell 6+

---

src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest
src/cascadia/ShellExtension/OpenTerminalHere.h
src/cascadia/ShellExtension/WindowsTerminalShellExt.vcxproj

Disambiguate the shell extension CLSIDs to allow usage SXS

---

tools/OpenConsole.psm1

OpenConsole.psm1 cached its root directory on import, which made it very
difficult to move into another Terminal clone and _do things_ (like code
formatting).
By resolving the root directory again per-cmdlet, we gain the ability
to...
```powershell
cd terminal
import-module ./tools/openconsole.psm1
cd ../terminal-2
invoke-codeformat
```
... and have it format the correct directory (terminal-2) instead of the
incorrect one (terminal).
This does unfortunately break the openconsole cmdlets _inside dep/wil
and dep/gsl_ because they are separate git repositories. This is taken
as an acceptable cost.

Teach OpenConsole.psm1 to support multiple terminal checkouts

---

src/cascadia/ShellExtension/OpenTerminalHere.cpp

Yeah, this one-line change shaves off almost half the binary.
Binary size savings (x64 Release):
Note   | WindowsTerminalShellExt.dll
------ | ---------------------------
Before | 130048
After  | 73728
Delta  | -56320
%Delta | -43.3%

Remove the shell extension's dependency on fmt for huge savings

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.xaml

Currently dismissing "are you sure you wish to close read-only tab or pane" 
dialog by pressing `ESC` will not abort tab closing
(aka the tab will be closed!)
The reason for this, is that we cancel, only if the "Cancel" is pressed
(aka result=PrimaryButton, while ESC returns result=None).
This PR fixes this, by doing what we usually do:
* Putting Cancel in the CloseButton (which is also triggered by ESC)
* Aborting the action if the result is not a Primary Button
However, since we want Cancel to be a default action,
we set CloseButton to be the DefaultButton  in XAML

Fix read-only tab dialog to cancel tab closing when dismissed

---

oss/fmt/cgmanifest.json
oss/fmt/include/fmt/chrono.h
oss/fmt/include/fmt/color.h
oss/fmt/include/fmt/compile.h
oss/fmt/include/fmt/core.h
oss/fmt/include/fmt/format-inl.h
oss/fmt/include/fmt/format.h
oss/fmt/include/fmt/locale.h
oss/fmt/include/fmt/os.h
oss/fmt/include/fmt/ostream.h
oss/fmt/include/fmt/printf.h
oss/fmt/include/fmt/ranges.h
oss/fmt/src/format.cc
oss/fmt/src/os.cc

{fmt} 7.1.3 includes a number of changes, which I will summarize here:
* Switched to Dragonbox for float formatting (quoted, "20-30x faster"
than ostringstream)
* Significantly improves `FMT_COMPILE` (compile-time format string)

Update {fmt} to 7.1.3

---

src/cascadia/TerminalApp/TerminalTab.cpp

Currently a repeated attempt to close a read-only tab from context menu,
will bring the terminal into invalid state if user dismisses close action.
There are two root causes for this:
1. The tab close menu triggers the closing of the root pane
(rather than invoking close tab flow in the Terminal Page).
2. Currently panes are not aware that the closing was canceled,
and thus they trigger the Closed event, putting the system in a weird state,
where the Closed handlers were invoked, but the Pane remains.
This PR mitigates #9502, by addressing the first root cause
(the fix is trivial and hopefully can be serviced).
Moreover, it addresses the only existing UI flow that can trigger the issue.
The remaining problematic flow will occur when the connection is closed.
I have created a separate …

Prevent tab context menu from closing root pane directly

---

src/inc/LibraryIncludes.h
src/renderer/vt/VtSequences.cpp
src/terminal/input/terminalInput.cpp

This reduces by 10% the binary size of OpenConsole x64 Release.
Note   | OpenConsole.exe
------ | ---------------------------
Before | 1156096
After  | 1037312
Delta  | -118784
%Delta | -10.27%

Replace conhost's fmt::format strings with FMT_COMPILEd ones

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/pch.h

This commit introduces a few different announcements to the command
palette.
When you delete the `>`, it will announce that you have entered
"command-line mode". When you reintroduce the `>`, it will announce that
you are in "action search mode."
When you enter a nested command, it will announce that you are looking
at "more options for new tab..." or "more options for select color
scheme...".
When you search and find nothing, it will announce that there were no
matching commands (or tabs!)
#7907 -- I would like to add "10 results match" or something, but ... pluralization across different languages is utterly hellish :smile:

Command Palette: announce various mode and state changes to UIA

---

doc/cascadia/profiles.schema.json
src/cascadia/LocalTests_TerminalApp/TabTests.cpp
src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.h
src/cascadia/TerminalSettingsModel/ActionArgs.idl
src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl

Currently, when the MRU is enabled we lose the keybinding allowing us to 
go forward/backward (aka right/left in LTR) in the tab view.
To fix that, this PR introduces "tabSwitcherMode" optional parameter to 
the prevTab / nextTab commands.
If it is not provided the global setting will be used.
So if you want to go to adjacent tabs, even if MRU is enabled on the
system level you can use:
```
{ "command": { "action": "prevTab", "tabSwitcherMode": "inOrder" }, "keys": "ctrl+f1"}
{ "command": { "action": "nextTab", "tabSwitcherMode": "inOrder" }, "keys": "ctrl+f2"}
```
or even
```
{"command": { "action": "prevTab", "tabSwitcherMode": "disabled" }, "keys": "ctrl+f1"}
{ "command": { "action": "nextTab", "tabSwitcherMode": "disabled" }, "keys": "ctrl+f2"}
```
if you don't want tab switcher to …

Allow overriding tab switcher mode on command level

---

src/host/CommandNumberPopup.cpp
src/host/_stream.cpp
src/host/_stream.h
src/host/cmdline.cpp
src/host/cmdline.h
src/host/misc.cpp
src/host/misc.h
src/host/readDataCooked.cpp

This commit clarifies some things inside WriteCharsLegacy by adding
comments and renaming parameter and enum names. It does not change any
logic.
`WC_ECHO` was used extensively to mean only one thing: whether to print
a control character like `\x18` (<kbd>Ctrl+X</kbd>) as `^X`. It's been
renamed to make that abundantly clear.

WriteCharsLegacy: Add some notes in comments and rename WC_ECHO

---

src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/CommandPalette.h
src/cascadia/TerminalApp/CommandPalette.xaml
src/cascadia/TerminalApp/Resources/en-US/Resources.resw

There seems to be a bug in WinUI (see microsoft/microsoft-ui-xaml#2121)
that results in heterogeneous `ModernCollectionBasePanel`  configured
with `DataTemplateSelector` and virtualization enabled
to recycle a container even if its `ContentTemplate` is wrong.
I considered few options of handling this:
* Disabling virtualization (by replacing item container template with
some non-virtualizing panel (e.g., `StackPanel`, `VirtualizingStackPanel`
with `VirtualizationMode`=`Standard`)
* Replacing `DataTemplateSelector` approach with `ChoosingItemContainer`
event handling approach, which allows you to manage the 
item container (`ListViewItem`) allocation process.
I have chosen the last one, as it should limit the amount of allocations,
and might allow optimizations in the future.
The solution …

Fix wrong item template selection in CmdPal

---

src/cascadia/TerminalApp/dll/TerminalApp.vcxproj
src/cascadia/UnitTests_TerminalCore/UnitTests.vcxproj
src/host/exe/Host.EXE.vcxproj
src/host/ut_host/Host.UnitTests.vcxproj
src/interactivity/win32/ut_interactivity_win32/Interactivity.Win32.UnitTests.vcxproj

The PlaySound functions were removed from OneCoreUAP_apiset.Lib in Windows 10 SDK 19041 because they did not actually belong there. Link to WinMM.Lib for PlaySoundW.
* Built for x64 from repository root with: `MSBuild.exe -property:TargetPlatformVersion=10.0.19041.0`
* Installed CascadiaPackage_0.0.1.0_x64_Debug.msix and launched on 19042.867

Link to WinMM.Lib for PlaySound with 19041

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalCore/Terminal.cpp

We have been seeing some crashes (#9410) originating from a
use-after-free or a double-free in the renderer. The renderer is
iterating over the dirty rects from the render engine¹ and the rect list
is being freed out from under it.
Things like this are usually the result of somebody manipulating the
renderer's state outside of lock.
Therefore, this pull request introduces some targeted locking fixes
around manipulation of the pattern buffer (which, in turn, changes the
renderer state.)
¹ This was not a problem until #8621, which made the renderer return a
span instead of a copy for the list of dirty rects.
I ran Terminal under App Verifier, and introduced a manul delay (under
lock) in the renderer such that the invalid map would definitely have
been invalidated between the renderer taking …

Add some read and write locks around pattern tree manipulation

---

src/cascadia/TerminalApp/TabHeaderControl.cpp

Prevent arrow keys from dismissing tab renamer

---

src/host/proxy/Host.Proxy.vcxproj

By default from ARM64 architecture projects, `WIN32` is not defined. It is supposed to be for this proxy stub to work. So I've set it with the preprocessor for this project.
`WIN32` appears to convey two meanings depending on who you are:
- To most of Windows, `WIN32` appears to mean the Win32 API surface and sometimes the major OS version that goes with it. (Specifically in contrast to 16-bit Windows.)
- To others, `WIN32` appears to mean a 32-bit processor or a synonym of `x86`.
This is generally not a problem for a few reasons:
- VS defines `WIN32` in the default targets/props only for the `x86` processor type. **BUT**
- Windows defines `WIN32` if it's not already defined in both `minwinbase.h` and `ole2.h` which generally speaking manage to get compiled into practically everything …

Fix ARM64 build by defining WIN32

---

src/cascadia/LocalTests_TerminalApp/CommandlineTest.cpp
src/cascadia/TerminalApp/AppCommandlineArgs.cpp
src/cascadia/TerminalApp/AppCommandlineArgs.h
src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/ActionArgs.h
src/cascadia/TerminalSettingsModel/ActionArgs.idl

Add splitMode to the args for split-pane (as -D for duplicate)

---

src/cascadia/TerminalSettingsEditor/Profiles.cpp
src/cascadia/TerminalSettingsEditor/Profiles.h

* [x ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
Validated this only by following the issue description and verified fonts appeared to be sorted alphabetically now.
Happy to add automated tests as well but would need some help where to add these since I'm probably overlooking where fonts are covered now.

Sort fonts alphabetically

---

build/Helix/PrepareHelixPayload.ps1
build/Helix/packages.config
build/packages.config
build/pipelines/templates/helix-createprojfile-steps.yml
build/pipelines/templates/helix-runtests-job.yml
doc/TAEF.md
doc/cascadia/Unittesting-CppWinRT-Xaml.md
src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
src/common.build.tests.props
src/host/ft_uia/Host.Tests.UIA.csproj
src/host/ft_uia/packages.config
src/terminal/parser/ut_parser/Parser.UnitTests.vcxproj
src/terminal/parser/ut_parser/packages.config
tools/OpenConsole.psm1
tools/razzle.cmd

Change TAEF nuget package to use new Microsoft.Taef name; Update to 10.58 release build version.

Change TAEF nuget package to use new Microsoft.Taef name; Update to 10.58 release build version.

---

src/cascadia/LocalTests_SettingsModel/pch.h
src/cascadia/TerminalControl/IControlSettings.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalCore/ICoreSettings.idl
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/pch.h
src/cascadia/TerminalSettingsEditor/ColorSchemes.cpp
src/cascadia/TerminalSettingsEditor/Profiles.idl
src/cascadia/TerminalSettingsEditor/pch.h
src/cascadia/TerminalSettingsModel/ColorScheme.cpp
src/cascadia/TerminalSettingsModel/ColorScheme.h
src/cascadia/TerminalSettingsModel/ColorScheme.idl
src/cascadia/TerminalSettingsModel/JsonUtils.h
src/cascadia/TerminalSettingsModel/Profile.h
src/cascadia/TerminalSettingsModel/Profile.idl
src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.h
src/cascadia/TerminalSettingsModel/pch.h
src/cascadia/UnitTests_TerminalCore/MockTermSettings.h
src/cascadia/UnitTests_TerminalCore/pch.h
src/cascadia/inc/cppwinrt_utils.h
src/cascadia/ut_app/precomp.h
src/inc/DefaultSettings.h
src/inc/til/color.h

This pull request introduces Microsoft.Terminal.Core.Color as an
alternative to both Windows.UI.Color and uint32_t/COLORREF in the
TerminalCore, ...Control, ...SettingsModel and ...SettingsEditor layers.
M.T.C.Color is trivially convertible to/from til::color and therefore
to/from COLORREF, W.U.Color, and any other color representation we might
need².
I've replaced almost every use of W.U.Color and uint32_t-as-color in the
above layers, with minor exception¹.
The need for this work is twofold.
First: We cannot bear a dependency from TerminalCore (which should,
on paper, be Windows 7 compatible) on Windows.UI or any other WinRT
namespace.
This work removes one big dependency on Windows.UI, but it does not go
all the way.
Second: TerminalCore chose to communicate mostly in packed uint32s …

Introduce MS.Term.Core.Color to replace W.U.Color for Core/Control/TSM

---

src/cascadia/LocalTests_TerminalApp/TabTests.cpp

Broadly, the tests were broken by #7489 because there were no `_startupActions`. They relied on the removed codepath that assumed `wt.exe` always set actions, or `AppCommandlineArgs::ValidateStartupCommands` created one by default.

Another fix for the localtests, March 2021 edition

---

src/cascadia/TerminalApp/ShortcutActionDispatch.cpp
src/cascadia/TerminalApp/ShortcutActionDispatch.h
src/cascadia/TerminalApp/ShortcutActionDispatch.idl
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalSettingsModel/AllShortcutActions.h
src/cascadia/TerminalSettingsModel/KeyMapping.idl

**Summary of the Pull Request**
This PR adds an X Macro for defining our ShortcutActions. This means that you can add the action in one place, and have the macro synthesize all sorts of boilerplate for you!
From the `AllShortcutActions.h` file:
> For a clearer explanation of how this file should be used, see:
> https://en.wikipedia.org/wiki/X_Macro
>
> Include this file to be able to quickly define some code in the exact same
> way for _every single shortcut action_. To use:
>
> 1. Include this file
> 2. Define the ON_ALL_ACTIONS macro with what you want each action to show up
>    as. Ex:
>
>    #define ON_ALL_ACTIONS(action) void action##Handler();
>
> 3. Then, use the ALL_SHORTCUT_ACTIONS macro to get the ON_ALL_ACTIONS marcro
>    repeated once for every ShortcutAction
>
> This is …

Add X Macro for fun and for profit

---

src/cascadia/TerminalSettingsEditor/Launch.xaml

Looks like we forgot to comment out the Default terminal setting from the UI.
Commented it out here.

Remove default terminal item from SUI

---

.github/actions/spelling/expect/alphabet.txt
src/renderer/dx/CustomTextRenderer.cpp

This commit introduces support for inverting all types of cursor.
To invert the display without re-rendering any text, we draw the cursor
into a command list and then compose the command list with the existing
renderer using the MASK_INVERT composition flag.
This wouldn't normally work with our renderer because there is no
_background_ color to invert in some cases (such as when acrylic is in
use.)
To work around that, we're taking advantage of @zadjii-msft's two-pass
cursor renderer.
To properly invert the cursor over a transparent background:
(Examples are given below for two cursor types, but this applies to all
of them.)
First, we'll draw a "backplate" in the user's requested background color
(with the alpha channel set to 0xFF). (`firstPass` == true)
EMPTY BOX  FILLED BOX
===== …

dx: add support for inverting all types of cursor

---

src/inc/til/replace.h

Fixed typo.
```
occurences -> occurrences
```

Fix typo in replace.h

---

doc/cascadia/profiles.schema.json

I forgot this in #9523 
* fixes #9721
* This is a docs fix
* I work here

Add `identifyWindow(s?)` to the schema

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.xaml

In exactly the same fashion as the tab renamer, handle <kbd>Enter</kbd> for committing the rename, and <kbd>Escape</kbd> for dismissing the rename.
* Added in #9662
Played with it - this feels good.

Manually handle Enter and Escape in the Window Renamer

---

src/cascadia/TerminalControl/TermControl.cpp

Fix marking of new selection start

---

src/cascadia/TerminalApp/TerminalPage.xaml

* Added in #9662
Added the thing, and just looked at it

Stylize the renamer Action button as a Accent button

---

src/cascadia/TerminalApp/TerminalPage.xaml

Huh, I guess I missed making the window renamer light-dismissable. This is a oneline fix for that.
Light dismissing is treated as a _cancel_, not as a commit. 
* Added in #9662
This feels right.

Add support for LightDismissing the renamer

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl

Disable warning about multi-line paste when brackted paste is on

---

src/cascadia/TerminalControl/TermControl.cpp
src/renderer/base/fontinfo.cpp
src/renderer/dx/DxFontRenderData.cpp
src/renderer/dx/DxFontRenderData.h
src/renderer/inc/FontInfo.hpp

Reduce instances of font fallback dialog through package font loading,
basic name trimming, and revised fallback test
- Adjusts the font dialog to only show when we attempt last-chance
resolution from our hardcoded list of font names with a flag instead
of with a string comparison by name
- Adds a resolution step to trim the font name by word from the end and
retry to attempt to resolve a proper font that just has a weight
suffix
- Adds a second font collection to font loading that will attempt to
locate all TTF files sitting next to our binary, like in our package
watched it quietly resolve to just `Cascadia Code` without the dialog.
directory for the package, set it as my desired font in Terminal, and
watched it load just fine.
pop anymore
see if dialog doesn't pop anymore
Closes #9375

Reduce instances of font fallback dialog

---

src/cascadia/TerminalSettingsEditor/MainPage.xaml

It will be a different color than the background, so it will look less
weird when it's unfocused. It also fixes the bug where the navigation
menu is transparent when acrylic is disabled systemwide.
Fixes #9337

Give our NavigationView's acrylic a fallback color

---

src/cascadia/TerminalApp/MinMaxCloseControl.xaml

The red close button animation fades to gray then to transparent, when
standard behavior skips the gray part. I manually tested in light/dark/high
contrast mode.
Closes #9762

Smoothen close caption button animation

---

src/cascadia/TerminalApp/TerminalTab.cpp

Trigger TaskbarProgressChanged every time we switch between active panes
(to update the tab header if required).
Closes #9743

Trigger taskbar progress evaluation upon pane activation

---

src/cascadia/TerminalSettingsModel/defaults.json

"ctrl+numpad_plus" command now increases font size and
"ctrl+numpad_minus" command now decreases font size.
Before this only "ctrl+=" and "ctrl+-" controlled font size. Increase in
font size follows previous convention where zooms in arbitrarily large,
but decrease in font size is capped.
I first ran "ctrl+=" and "ctrl+-" in my terminal to verify its behavior,
then compared that against "ctrl+numpad_plus" and "ctrl+"numpad_minus".
Both increased and decreased the font size by the same amount, and both
appeared to have a cap for how small they could get, but did not appear
to have a cap for how big they could get.
Closes #7518

Bind Ctrl+Numpad Plus,Minus to the font size controls

---

src/host/outputStream.cpp
src/host/outputStream.hpp
src/host/screenInfo.cpp
src/host/screenInfo.hpp
src/terminal/adapter/conGetSet.hpp
src/terminal/adapter/ut_adapter/adapterTest.cpp

This PR removes the `GetConsoleCursorInfo` and `SetConsoleCursorInfo`
methods from the `ConGetSet` interface, and the `GetScrollingRegion`
method from the `SCREEN_INFORMATION` class. None of these methods are
used anymore.
PR #2764 removed the last usage of `GetScrollingRegion`. 
The `Get/SetConsoleCursorInfo` methods don't seem to have ever been used
in the time that the terminal code has been open source, so whatever
purpose they originally served must have been replaced a long time ago.
The `GetScrollingRegion` method was originally called from the
`ScrollRegion` function, but that usage was removed in PR #2764 when the
margin handling was moved to a higher level.
I've checked that the code still compiles.
Closes #9771

Remove unused methods in ConGetSet and SCREEN_INFORMATION

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/MainPage.h
src/cascadia/TerminalSettingsEditor/MainPage.idl
src/cascadia/TerminalSettingsEditor/Profiles.cpp

This is required to maintain the modality of the dialogs, which we lost
when we moved from Pickers to IFileDialog. The HWND hosting Window API
we dreamed up is incompatible with IModalDialog, because IModalDialog
requires the HWND immediately upon `Show`. We're smuggling it in a
uint64, as is tradition.
zadjii-msft noticed this in #9760.

Propagate the hosting HWND to the new IFileDialogs

---

.vscode/settings.json
src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/IslandWindow.h
src/interactivity/win32/window.cpp
src/interactivity/win32/window.hpp
src/interactivity/win32/windowproc.cpp

This change cleans up the Fullscreen implementation for both conhost and Terminal, improving the restore position (where the window goes when exiting fullscreen).
Prior to this change the window wasn't guaranteed to restore somewhere on the window's current monitor when exiting fullscreen. With this change the window will restore always to its current monitor, at a reasonable location (and will 'double restore' (to fullscreen->maximize->restore) after monitor changes while fullscreen, which is the expected user behavior.
A fullscreen window's monitor can change.
- Win+Shift+left/right migrates a window between monitors.
- User could open settings, display, and move the monitor or change its DPI.
- The monitor could be unplugged.
- The session could be remote and be disconnected.
A …

Fix restore window position when exiting fullscreen

---

src/cascadia/TerminalConnection/AzureConnection.cpp
src/cascadia/TerminalConnection/ConptyConnection.cpp
src/host/PtySignalInputThread.cpp
src/host/VtInputThread.cpp
src/host/srvinit.cpp
src/interactivity/win32/ConsoleInputThread.cpp
src/renderer/base/thread.cpp

Add names to threads to make debugging a slight bit easier.
Thread descriptions show up as names in both the Visual Studio debugger, WinDBG debugger, and Windows Performance Analyzer. This makes it faster and easier to identify threads of interest in our processes.

Add names to threads to make debugging a slight bit easier

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

Use `ThrottledFunc` in `TermControl` to limit bell emission callback to one per second.

Limit terminal warning bells to one per second

---

src/cascadia/LocalTests_TerminalApp/TabTests.cpp
src/cascadia/TerminalApp/TerminalPage.cpp

Clearly, I didn't run these tests on my last commit where I made the toasts lazy-load.
* broken in in #9662
* 
For whatever reason, these tests are unhappy running back to back, but are just fine running isolated.

Fix the renamer tests

---

src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp

Attempts to generate a name Profile X, where X is the index of the new profile (1-based).
As long as name is already taken, generates new name by incrementing X by 1

Fix profile name generation to allocate unique name

---

src/host/ConsoleArguments.cpp
src/host/ConsoleArguments.hpp
src/host/ut_host/ConsoleArgumentsTests.cpp
src/server/IoDispatchers.cpp

Add flag that will ensure we do not handoff to a registered default console. Also for a bonus, allow double-click launches or explicit command line launches of conhost.exe with a binary argument to open with the inbox one.

Add -ForceNoHandoff for compatibility; stop handoff for double-click launches

---

src/host/outputStream.cpp
src/host/outputStream.hpp
src/host/screenInfo.cpp
src/host/screenInfo.hpp
src/host/ut_host/ScreenBufferTests.cpp
src/terminal/adapter/adaptDispatch.cpp
src/terminal/adapter/conGetSet.hpp
src/terminal/adapter/ut_adapter/adapterTest.cpp

The "virtual bottom" marks the last line of the mutable viewport area, which is the part of the buffer that VT sequences can write to. This region should typically only move downwards, as new lines are added to the buffer, but there were a number of cases where it was incorrectly being moved up. This PR attempts to fix that.
When a call is made to `UpdateBottom`, we now clamp the value so it's at least as low as the current viewport bottom (i.e. if the viewport has moved down, we want the virtual bottom to move down too), but no lower than the bottom of the buffer (we don't want it to be out of range).
There is one special case where we do actually want the virtual bottom to move up - when the scrollback has been cleared with an `ED3` escape sequence. So in that case we needed a new …

Prevent the virtual viewport bottom being moved up unintentionally

---

doc/cascadia/profiles.schema.json

Turns out we forgot to add `tabColor` to the JSON schema.

doc: Add tabColor to JSON schema

---

src/cascadia/TerminalApp/TabManagement.cpp

Not sure what is the reason for handling right button. 
But delaying it to PointerReleased seems not to regress anything.

Delay close tab on middle-click till pointer released

---

CONTRIBUTING.md

CONTRIBUTING.md currently has documentation suggesting to file a 'Community Guidance Request' if a user doesn't know how to do something.  This issue was identified by @hessedoneen in #9765 .  Per @zadjii-msft  this option has never really existed, and should be struck from CONTRIBUTING.md .  This PR does just that.
Review CONTRIBUTING.md and see that it no longer refers to filing 'Community Guidance Requests'

Del 'Community Guidance Req' from CONTRIBUTING.md

---

src/cascadia/TerminalApp/AppLogic.cpp

There is a bug in the compiler that we trip over when we handle the
exception generated by Package::Current inside a coroutine. It appears
to destruct an invalid instance of winrt::factory_guard_count.
Learned from the compiler folks: "coroutine frame pointer wasn't being
stored ... properly".
Fixes #9821

Work around a compiler bug w/ coroutines and exceptions

---

src/cascadia/TerminalApp/TabBase.cpp
src/cascadia/TerminalApp/TabBase.h
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

Add the "Close other tabs"/"Close tabs to the right" menu items straight to the tab context menu to work around #8238.
We can't add them into a dedicated sub-menu until the upstream crash is fixed.
#8238 
Moved the creation of the close menu items to a single function. Once the originating crash is fixed, the sub-menu can be restored by just replacing a few lines of code.

Add Close menu items to the context menu flyout

---

src/cascadia/TerminalSettingsEditor/Profiles.cpp

Remove an unnecessary check in `Profiles.cpp` that was preventing us from enabling the text box and browse button when the user unchecks 'use parent process directory'
Played around with it and it works.

Fix for configuring starting directory in SUI when defaults sets it to null

---

src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

Quick and dirty. 
A better solution is to allow passing all "runtime settings" upon tab creation.

[Quick and Dirty] Copy runtime tab title when duplicating tabs

---

doc/building.md
tools/OpenConsole.psm1

Commit https://github.com/microsoft/terminal/commit/dbbe820ae40d208c07c45b700fcc99063e68d1eb seems to change where OpenConsole.psm1 puts clang-format.exe but /doc/building.md still uses the path from commit https://github.com/microsoft/terminal/commit/9b92986b49bed8cc41fde4d6ef080921c41e6d9e.
Updated clang-format.exe's path and added the required steps to generate a clang-format.exe file.

doc, tools: Improve docs around using clang-format with VS

---

src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
src/host/screenInfo.cpp

When we resize the text buffer, initialize the buffer with the
_default_¹ attributes, not the _current_ ones. If we use the current
attributes, then we can get into scenarios where something like `vim` is
running, and left the attributes set to something other than the
defaults, and when we resized the buffer, we'd fill it up with color, as
opposed to whatever the default would be.
This PR instead initializes the buffers with the default colors. It also
makes sure to set the active attributes of the newly created buffers
back to whatever the current attributes of the old buffer were.
[1]: For the Terminal, the default attributes are "default on default".
For conhost, the default attributes are whatever the result of
`Settings::GetDefaultAttributes` is, which could be any combo of the …

Initialize the text buffer with the default attributes on a resize

---

src/cascadia/LocalTests_TerminalApp/TabTests.cpp
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.h

The majority of the work was already done earlier.
The fix is only in _SetFocusedTab, that runs asynchronously
and thus might result in a race or even overflow.
All other changes are decorative.
UT and manual tests

Fix TabManagement to use tab object rather than index

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalCore/ICoreSettings.idl
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalSelection.cpp
src/cascadia/TerminalSettingsEditor/Interaction.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/GlobalAppSettings.cpp
src/cascadia/TerminalSettingsModel/GlobalAppSettings.h
src/cascadia/TerminalSettingsModel/GlobalAppSettings.idl
src/cascadia/TerminalSettingsModel/TerminalSettings.cpp
src/cascadia/TerminalSettingsModel/TerminalSettings.h
src/cascadia/TerminalSettingsModel/defaults.json
src/cascadia/UnitTests_TerminalCore/MockTermSettings.h

Added global flag named `trimBlockSelection` set to `false` by default.
The setting was added to Interactions menu of the SUI.

Make whitespace trimming in block selection configurable

---

README.md

Let's add our logos to our README to spice it up.

doc: Add logos to README

---

src/cascadia/Remoting/Monarch.cpp
src/cascadia/UnitTests_Remoting/RemotingTests.cpp

We don't want it acting as the "most recent window" for windowing behavior.
The most recent window should always be some other window.
This is being made as an atomic commit because we're probably 50% sure on this
one. Maybe people do want new tabs to open up in the quake window! If they're
running from the commandline, that's easy. If they're running from the shell
context menu, that's **H**ard / impossible currently. $20 someone asks for
that if we ship this. That of course might just fall into "explorer context
menu settings" though.
* Original thread: #653
* Spec: #9274 
I mean, this one's super straightforward, not sure what else there is to add.
Played with this, it works exactly as you'd think.

Exempt the `_quake` window from glomming

---

src/buffer/out/textBuffer.cpp

Explicitly using `SHORT` instead of `auto` to prevent `int -> short` narrowing.

Fix implicitly narrowing conversion in textBuffer

---

src/cascadia/TerminalSettingsModel/Profile.cpp

#9962 was caused by a serialization bug. _Technically_, `ToJson` works
as intended: if the current layer has any values set, write them out to
the json. However, on first load, the dynamic profile `Profile` objects
are actually empty (because they inherit from base layer, then the
dynamic profile generator). This means that `ToJson` writes the dynamic
profiles as empty objects `{}`. Then, on reload, we see that the dynamic
profiles aren't in the JSON, and we write them again.
To get around this issue, we added a simple check to `Profile::ToJson`:
if we have a source, make sure we write out the name, guid, hidden, and
source. This is intended to align with `Profile::GenerateStub`.
Closes #9962

Serialize stub for dynamic profiles

---

NOTICE.md
src/cascadia/Remoting/Microsoft.Terminal.RemotingLib.vcxproj
src/cascadia/Remoting/Monarch.cpp
src/cascadia/Remoting/Monarch.idl
src/cascadia/Remoting/Peasant.cpp
src/cascadia/Remoting/Peasant.h
src/cascadia/Remoting/Peasant.idl
src/cascadia/Remoting/SummonWindowBehavior.cpp
src/cascadia/Remoting/SummonWindowBehavior.h
src/cascadia/Remoting/SummonWindowSelectionArgs.h
src/cascadia/TerminalSettingsModel/ActionArgs.h
src/cascadia/TerminalSettingsModel/ActionArgs.idl
src/cascadia/TerminalSettingsModel/TerminalSettingsSerializationHelpers.h
src/cascadia/UnitTests_Remoting/RemotingTests.cpp
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h
src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/VirtualDesktopUtils.cpp
src/cascadia/WindowsTerminal/VirtualDesktopUtils.h
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj

This adds support for the `desktop` param to the `globalSummon` action. It accepts 3 values:
* `toCurrent` (default): The window moves to the current desktop when it's summoned
* `any`: We don't care what desktop the window is on. We'll go to the desktop the window is on when we summon it.
* `onCurrent`: We'll only try to summon the MRU window on this desktop when summoning a window. 
* When combined with `name`, if there's a window matching `name`, we'll move it to this desktop. 
* If there's not a window on this desktop, and `name` is omitted, then we'll make a new window.
`quakeMode` was also updated to use `toCurrent` behavior by default.
* Original thread: #653
* Spec: #9274 
S/O to …

Add `desktop` param to `globalSummon`; set _quake = toCurrent

---

src/terminal/parser/IStateMachineEngine.hpp
src/terminal/parser/InputStateMachineEngine.cpp
src/terminal/parser/InputStateMachineEngine.hpp
src/terminal/parser/OutputStateMachineEngine.cpp
src/terminal/parser/OutputStateMachineEngine.hpp
src/terminal/parser/stateMachine.cpp
src/terminal/parser/stateMachine.hpp
src/terminal/parser/ut_parser/OutputEngineTest.cpp
src/terminal/parser/ut_parser/StateMachineTest.cpp

This PR introduces a mechanism via which DCS data strings can be passed
through directly to the dispatch method that will be handling them, so
the data can be processed as it is received, rather than being buffered
in the state machine. This also simplifies the way string termination is
handled, so it now more closely matches the behaviour of the original
DEC terminals.
* Initial support for DCS sequences was introduced in PR #6328.
* Handling of DCS (and other) C1 controls was added in PR #7340.
* This is a prerequisite for Sixel (#448) and Soft Font (#9164) support.
The way this now works, a `DCS` sequence is dispatched as soon as the
final character of the `VTID` is received. Based on that ID, the
`OutputStateMachineEngine` should forward the call to the corresponding
dispatch method, …

Introduce a mechanism for passing through DCS data strings

---

src/cascadia/WpfTerminalControl/TerminalControl.xaml.cs
src/cascadia/WpfTerminalControl/TerminalTheme.cs

When syncing terminals across users (i.e. Liveshare shared terminals),
the terminal size is synced. This leads to having unused space around
the terminal which is the same color as the terminal's background
causing confusion as to what space is usable within the terminal.
Instead this change allows consumers to set the background color of the
control, separate from the terminal renderer's background, which makes
it easier to identify the edges of the terminal.

[WPF] Allows setting the WPF control background when setting the terminal theme

---

src/cascadia/WindowsTerminal/AppHost.cpp

This is to mitigate MSFT:33035972. If you call `MoveWindowToDesktop` while an app is set to "Show windows from this app on all desktops", the OS will clear that "Show windows from this app on all desktops" state. But it _won't_ clear that state from the task view, so it'll just plain look broken.
We can mitigate this just by checking if we're already on the current desktop first. "Show windows from this app on all desktops" windows will _always_ be on every desktop, so that API will return true, and we can avoid tearing the state.
* added in #9954 
* it works again

Only move the window to the current desktop when it isn't on that one already

---

src/cascadia/TerminalApp/TerminalPage.cpp

Let the dropdown menu open downwards if there's enough space, when clicking on the down arrow.
Set the placement of the flyout to BottomEdgeAlignedLeft, as was done when opening the menu from the key binding.
Manual tests

Fix dropdown showing in up direction

---

src/cascadia/TerminalControl/TermControl.cpp

This backports ac265aab99d5f79345074fbff66c54a816120de1 to v1.8.
ControlCore's _renderer (IRenderTarget) is allocated as std::unique_ptr,
but is given to Terminal::CreateFromSettings as a reference.
ControlCore::Close deallocates the _renderer, but if ThrottledFuncs
are still scheduled to call ControlCore::UpdatePatternLocations
it'll cause Terminal::UpdatePatterns to be called, which in turn ends up
accessing the deallocated IRenderTarget reference and lead to a crash.
A proper solution with shared pointers is nontrivial and should be
attempted at a later point in time. This solution moves the teardown of
the _renderer into ControlCore::~ControlCore, where we can be certain
that no further strong references are held by ThrottledFuncs.

Backport hotfix ac265aa to v1.8

---

src/cascadia/TerminalApp/FilteredCommand.cpp

The bug is due to us using std::tolower, while the default locale is not user's locale.
The fix here is to use the same approach as upon sorting: lstrcmpi.
While there are additional methods to do locale aware comparison,
here we convert chars to string and call lstrcmpi.
While this approach seems somewhat inefficient it ensures consistency
(with the order of locales that lstrcmi tries to apply internally).

Teach CmdPal search to use user locale

---

src/cascadia/TerminalCore/ITerminalApi.hpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/TerminalApi.cpp
src/cascadia/TerminalCore/TerminalDispatch.cpp
src/cascadia/UnitTests_TerminalCore/TerminalApiTest.cpp
src/terminal/adapter/DispatchTypes.hpp

When we parse OSC 9;4, allow a trailing semicolon (i.e. allow `9;4;` or something like `9;4;3;`). 
OSC 9;4 sequences with or without trailing semicolons work

Allow trailing semicolon when parsing OSC 9;4

---

src/cascadia/TerminalSettingsEditor/Profiles.h

- When opening a profile page and selecting a random pivot, when then navigating away from the profile page to another item and navigating back to the same profile the last selected pivot was still active.
- When opening a profile page and selecting a random pivot, when then navigating away from the profile page to a second profile the last selected pivot was immediately active on the second profile.
- When selecting random pivots and navigating only between other profile pages the last selected pivot was always active on the opened profile page.
What felt a bit strange at first sight was:
- open a profile page, select a random pivot
- start adding a new profile
- the last selected pivot is immediately active and not the "General" pivot what might be the obvious pivot to show when a user …

Keep the last selected pivot active when navigating over profile pages

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlCore.h
src/cascadia/TerminalControl/TermControl.h

ControlCore::AttachUiaEngine receives a IRenderEngine as a raw pointer,
which TermControl owns. We must ensure that we first destroy the
ControlCore before the UiaEngine instance (both owned by TermControl).
Otherwise a deallocated IRenderEngine is accessed when
ControlCore calls Renderer::TriggerTeardown.
This crash was introduced in #10031.
* Run accevent.exe to cause a UiaEngine to be attached to a TermControl.
* Close the current tab
* Ensured no crashes occur

Fix crash on exit introduced in ac265aa

---

src/host/ft_host/API_MultipleInflightMessageTests.cpp
src/host/ft_host/Host.FeatureTests.vcxproj
src/host/ft_host/Host.FeatureTests.vcxproj.filters
src/host/ft_host/sources

This test has some load bearing specifics in it.
In short, it must trigger multiple boost::small_vector growths. The
vector is reused for the lifetime of the console (!) so it must be
forced to act the way the repro requires.
Oh, and the test needs to be run with Application Verifier +Heap.
This validates the fix in c0ab9cb5b55d745a1528c7429615c71e0745ed8d.

Add a test for GH-9692/MSFT-33127449

---

src/cascadia/TerminalApp/SettingsTab.cpp
src/cascadia/TerminalApp/SettingsTab.h
src/cascadia/TerminalApp/TabBase.cpp
src/cascadia/TerminalApp/TabBase.h
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

A redo of #6290. That PR was overkill. In that one, we'd toss focus back to the active control any time that the tab view item got focus. That's maybe not the _best_ solution.
Instead, this PR is precision strikes. We're re-using a lot of what we already have from #9260. 
* When the context menu is closed, yeet focus to the control.
* When the renamer is dismissed, yeet focus to the control.
* When the TabViewItem is tapped (meaning no one else handled it), yeet focus to the control.

In specific scenarios, focus the active control

---

build/pipelines/templates/build-console-ci.yml

I believe that there is a hidden "default branch" setting in Azure
DevOps, and ours is set to "master". CG only attempts to automatically
inject to builds off the default branch... and because we're a GitHub
repo running builds in AzDO we _can't change what the default branch
is_. Oops.

Make sure we run CG component detection on main

---

src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/Profile.cpp
src/cascadia/WindowsTerminal/IslandWindow.cpp

This is primarily being done to unblock #9223.
Prior to this, we'd validate that the user's `startingDirectory` existed
here. If it was invalid, we'd gracefully fall back to `%USERPROFILE%`.
However, that could cause hangs when combined with WSL. When the WSL
filesystem is slow to respond, we'll end up waiting indefinitely for
their filesystem driver to respond. This can result in the whole terminal
becoming unresponsive.
Similarly, with #9223 we want users to be able to specify WSL paths in a
profile, but this bit of validation logic totally prevents that from working,
because it'll just replace the path with `%USERPROFILE%`.
If the path is eventually invalid, we'll display warning in the
`ConptyConnection`, when the process fails to launch.
Closes #9541
Closes #9114

Disable path validation, add warning

---

src/cascadia/TerminalApp/CommandPalette.xaml
src/cascadia/TerminalSettingsEditor/AddProfile.xaml
src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/MainPage.xaml
src/cascadia/TerminalSettingsModel/IconPathConverter.cpp

Adds the profile icons to the page header. I had to manually create the header, and manually bind it to the `Icon` and `Content` of each `NavViewItem`. 
It's important that each `NavViewItem`'s icon is set as an `IconSource`, so that we can bind to it. If it's just a plain old `FontIcon`, then we can't re-use it. 
Additionally, I removed the manual sizing of all font icons to font size 12. That would make font icons _tiny_ in the header. Now, they'll properly re-use the size of the `NavigationViewTitleHeaderContentControlTextStyle` in the nav view header. This involved also manually making the icons smaller on the `AddProfile` page and in the `CommandPalette`.
As per usual, images are in Teams
* Checked (bitmap|font) icons in tabs
* …

Add the profile, page icons to the page headers

---

src/ConsolePerf.wprp
src/Terminal.wprp
src/cascadia/Remoting/Monarch.cpp
src/cascadia/Remoting/Peasant.cpp
src/cascadia/Remoting/WindowManager.cpp
src/cascadia/WindowsTerminal/IslandWindow.cpp
src/host/exe/exemain.cpp
src/host/tracing.cpp
src/inc/WilErrorReporting.h
src/inc/til.h
src/renderer/dx/DxRenderer.cpp
src/renderer/vt/tracing.cpp
src/server/ApiDispatchers.cpp
src/terminal/parser/tracing.cpp
src/types/UiaTracing.cpp

Set keyword flags on all events so those sharing a provider with
telemetry do not fire unless tracing is enabled
only other site of keywords we define in the Host project tracing
files.
I initially thought that we would need to split providers here to
accomplish this... but @DHowett helped me realize that might be a lot of
additional metadata and bloat binary size. So with help from a friend
from fundamentals, I realized that we could use Keywords to
differentiate here. We can no longer define 0 keywords as that
represents an any/all scenario. Every `TraceLoggingWrite` event now
needs a keyword. When our events have a keyword, they're not included in
any trace. Additionally, when we have an explicit keyword to check that
is different from the ones used for the telemetry pipeline, we can …

Set keyword flags on all tracelog events

---

src/cascadia/TerminalApp/AppCommandlineArgs.cpp

While a user is formulating their hex string for a `tabColor` arg
in the CommandPalette, we try to parse the string one char at
a time as it comes in. `ColorFromHexString` doesn't like anything
except a well formed hex string so it'll throw. We can probably eat
any error that comes out of this because we should only care to set 
the TabColor once the string provided is a valid hex str.
Closes #10053

Fix tabColor arg crash in CommandPalette

---

src/cascadia/TerminalControl/TSFInputControl.cpp
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControlAutomationPeer.cpp

1. The TSFInputControl may get a layout event after it has been removed
from service (and no longer has a XAML tree)
* Two fixes:
* first, guard the layour updater from accessing detached xaml
objects
* second, shut down all pending throttled functions during close
(not destruction!¹)
2. The TermControlAutomationPeer may be destructed before its events
fire.
3. The TermControlAutomationPeer may receive a notification after it has
been detached from XAML (and therefore has no dispatcher).
¹ Close happens before the control is removed from the XAML tree;
destruction happens some time later. We must detach all UI-bound events
in Close so that they don't fire between when we detach and when we
destruct.
Fixes MSFT-32496693
Fixes MSFT-32496158
Fixes MSFT-32509759
Fixes MSFT-32871913

Fix a number of shutdown crashes in TermControl

---

src/cascadia/WindowsTerminal/IslandWindow.cpp

This is a scoped implementation of "hide on minimize", only to the `_quake` window. When minimized, the `_quake` window won't appear in the taskbar. IT ALSO WON'T APPEAR IN THE TRAY, BECAUSE WE DON'T HAVE ONE YET.
I talked about this with @DHowett, and it seemed cool. Other windows will still minimize normally.
* Original thread: #653
* Spec: #9274 
* minimize to tray: #5727 
After playing with it, it is in fact, cool.
ALSO `LOG_IF_WIN32_BOOL_FALSE` should DEFINITELY not be used with `ShowWindow`. [`ShowWindow`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow#return-value) returns false if the window was previously hidden, but doesn't `SetLastError`, so that macro will _throw_.
```jsonc
{ "keys": "ctrl+`", "command": { "action": …
```

Hide `_quake` window on minimize ALWAYS

---

src/cascadia/TerminalApp/TabHeaderControl.cpp
src/cascadia/TerminalApp/TabHeaderControl.h
src/cascadia/TerminalApp/TabHeaderControl.idl
src/cascadia/TerminalApp/TerminalTab.cpp

This is a hotfix to #10048. When the tab renamer is opened, we need to make sure to not immediately steal focus from it.

Don't yeet focus to the control when the tab renamer is opened

---

src/cascadia/TerminalApp/CommandPalette.xaml
src/cascadia/TerminalSettingsEditor/AddProfile.xaml
src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/MainPage.xaml
src/cascadia/TerminalSettingsModel/IconPathConverter.cpp

This reverts commit a3a2a4102dff785ac84f0d37397113fae3ef2033.
#10046 causes a crash on save. `MainPage::UpdateSettings()` is unable to update the navigation view's selected item due to an "incorrect parameter". This is particularly strange to see because #10046 only modifies the navigation view's header, not the menu items themselves. Reverting this change fixes that crash (verified).
Reopens #9694

Revert "Add the profile, page icons to the page headers (#10046)"

---

src/cascadia/TerminalControl/TSFInputControl.cpp
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControlAutomationPeer.cpp

1. The TSFInputControl may get a layout event after it has been removed
from service (and no longer has a XAML tree)
* Two fixes:
* first, guard the layour updater from accessing detached xaml
objects
* second, shut down all pending throttled functions during close
(not destruction!¹)
2. The TermControlAutomationPeer may be destructed before its events
fire.
3. The TermControlAutomationPeer may receive a notification after it has
been detached from XAML (and therefore has no dispatcher).
¹ Close happens before the control is removed from the XAML tree;
destruction happens some time later. We must detach all UI-bound events
in Close so that they don't fire between when we detach and when we
destruct.
Fixes MSFT-32496693
Fixes MSFT-32496158
Fixes MSFT-32509759
Fixes MSFT-32871913
(cherry …

(1.9 port) Fix a number of shutdown crashes in TermControl

---

src/cascadia/TerminalSettingsModel/defaults.json

I'd personally chose to just bind `globalSummon` to <kbd>win+`</kbd>, but _I do as I'm told_.

Bind `quakeMode` to "win+`" by default

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/ThrottledFunc.h

This replaces `ThrottledFunc` with two variants:
* `ThrottledFuncLeading` invokes the callback immediately and blocks further calls for the given duration
* `ThrottledFuncTrailing` blocks calls for the given duration and then invokes the callback
* #9270 - `ThrottledFuncLeading` will allow the pane to flash immediately for a BEL, but block further BELs until the animation finished

Split ThrottledFunc into Leading and Trailing variants

---

src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

The bug that caused #9962 resulted in folks getting profiles written to
their settings that didn't contain any identifying information (name or
guid), sometimes multiple times.
These profiles look (somewhat) like this:
```json
{ "colorScheme": "Campbell" },
{},
```
An empty profile serves no purpose -- it shows up in the list as being
named "Default", and it only launches CMD (unless the commandline is the
thing that the user successfully changed.)
We can heal the settings file by simply ignoring those profiles that
have *no identifying information* (a guid or a name that can be
converted into a guid).
Validation
----------
I created a number of profiles that fit this format and made sure that
they were ignored on load and destroyed on save.

Attempt to heal settings files damaged by #9962

---

src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

Check for null before serializing the default terminal. Because the _currentDefaultTerminal is only initialized when the `Launch` page is navigated to, this _could_ be null if you navigate to another page, save, then save again. 
It crashed consistently before, it doesn't now.

Fix crash on saving the settings twice

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/Profiles.cpp
src/cascadia/TerminalSettingsEditor/Profiles.h
src/cascadia/TerminalSettingsEditor/Profiles.idl

* Preserve profile GUID upon item Tag creation. 
* Use this GUID rather than the current profile GUID to select an item
upon settings update.
So even if the profile was renamed and the GUID has changed,
the GUID in the tag remains unchanged and can be found
upon discarding.

Fix profile selection upon discarding changes in SUI

---

src/cascadia/TerminalApp/TerminalPage.cpp

Now it just launches in focus mode, but you can _leave_ focus mode just fine.
I can't iterate on this more today - VS decided that it _needed_ an update ☹️ 
see also: #8888, comments in that thread

Stop quake mode from forcing focus mode

---

src/cascadia/TerminalApp/CommandPalette.cpp

Went for option 2 proposed here:
https://github.com/microsoft/terminal/issues/10140#issuecomment-845193132. 
Disabling back space in the nested entry didn't felt as the nicest
solution.  Instead now all state that keeps track of nested commands is
cleared when switching beteen modes.
- Validated the specified issue is fixed by this change:. now after
entering a sub command and hitting backspace the palette no longer
shows the sub command item (here `< Select color scheme...` ).
- Validated that switching between all modes (command line, actions, tab
search & tab switch) still work as expected.
- Validated as well that all modes still work as expected.
Didn't add unit tests, but happy to try that out if this would be
required. 
Closes #10140

Clear all state tracking nested commands when switching command mode

---

.github/actions/spelling/allow/apis.txt
src/terminal/parser/InputStateMachineEngine.cpp
src/terminal/parser/InputStateMachineEngine.hpp
src/terminal/parser/ut_parser/InputEngineTest.cpp

Each mouse-down event's time and position is now stored, and if we
process a left-mouse-down event at the same position as the previous one
and within the double click time we set the double click flag. 
Also adds a case statement to `_UpdateSGRMouseButtonState` so that we
send hover events instead of ignoring them. 
Note: The 'right-click menu in far manager shows up at the wrong
location' bug still exists with this, as it seems to use the cursor
position as told by user32.
Related to #376
Double click in far manager works, hover in far manager works (hovering
over items in the right-click menu correctly highlights them)

Pass through double clicks and hover events in Win32 mouse mode

---

src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

This is a redux of #8882. 
From the original:
>  This is really similar to what we're doing with the `CommandPalette`. We're adding a ~~Preview~~`KeyDown` handler to the SUI `MainPage`, that connects to `TerminalPage::_HandleKey`. That allows the SUI a chance to search the keymap to dispatch actions for keybindings, similar to how the command palette does it. 
> 
> This also means it's now possible for the SUI to invoke _all_ the actions available to the Terminal. This includes the ones like `IncreaseFontSize`, which require a _Terminal_ to actually do something. So we have to make sure all the calls to `_GetActiveControl` actually check that the result is non-null before using it. 
> 
> A bunch of the actions do nothing now from a SUI tab, others behave _weird_. Like "Rename tab" / "Open …

Hook up the keybindings to the SUI, redux

---

src/host/readDataCooked.cpp
src/host/tracing.cpp
src/host/tracing.hpp
src/inc/til.h

Added trace to conhost to instrument buffers that are cooked prior to being passed to the console.
- Ensured trace is correctly logged in ETL (via TraceLog)

Add cooked data read tracing

---

src/cascadia/TerminalSettingsEditor/CommonResources.xaml
src/cascadia/TerminalSettingsEditor/Launch.xaml

Correct Default Application Selector styles for high contrast and to change with OS theme dark/light toggle
- https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/xaml-theme-resources
1. If I'm going to override colors, I need to define styles in a resource dictionary with Light, Dark, and HighContrast variants so it can be appropriate for each of those. 
2. For HighContrast, I need to not mess with text colors and let them follow the default settings. 
3. For using System Brushes, I need to use a `ThemeResource` binding not a `StaticResource` binding. The former lets it change when you flip the OS toggle Light/Dark. The latter is stuck to whatever it was when the page loaded.
- Loaded in light mode. Flipped to dark. Watched it change live. Checked both unselected and …

Correct Default Application Selector styles for high contrast and to change with OS theme dark/light toggle

---

src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/AppLogic.idl
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalPage.idl
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h

Summon the listening window when it receives an inbound connection
- We cannot just send our window to foreground by simply calling user32 on the window handle. But fortunately, the remoting behavior already has a summon window function with a workaround for the Quake functionality.
- This bubbles up an event from the TerminalApp's Page to the WindowsTerminal's Apphost so it can call the same window summoning behavior in IslandWindow as is triggered when the Monarch dictates this out of the Microsoft.Terminal.Remoting project.
- Opened the Terminal with it registered as DefTerm. Activated some other windows to the foreground. Start > Run > Cmd. Tab connects and opens in existing Terminal and it is brought to foreground.
- With no running Terminal and registered as DefTerm, do Start > Run …

Summon this window when it receives an inbound connection

---

src/cascadia/TerminalSettingsModel/DefaultTerminal.cpp
src/cascadia/TerminalSettingsModel/DefaultTerminal.h
src/propslib/DelegationConfig.cpp

Prevent crashes in Settings UI launch on OS versions before package management extensions
- On older OS versions like 18363, some of the COM interfaces we use to look up information from the OS application package management catalog (to find default terminals) are unavailable. This returns `E_NOINTERFACE`. This then ends up returning an empty list of items and null as a selected item. 
- I had intended for that to not return that particular error all the way up and just log it because the console and terminal lookup functions always return at least one element: the one representing the `conhost.exe` that is already on the machine.
- I have changed the "default packages" lookup to log instead of return failures like E_NOINTERFACE such that it can continue processing and make the "package" …

Prevent crashes in Settings UI launch on OS versions before package management extensions

---

src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/Pane.h
src/cascadia/TerminalConnection/ConptyConnection.cpp

ConptyConnection has two different failure modes:
1. We failed to initialize the pseudoconsole or create the process
2. The process exited with an error code.
Until this commit, they were treated the same way: closeOnExit=always
would force the pane/tab to be destroyed. This was very bad in case 1,
where we would display a (possibly useful) error message and then
immediately close the window.
This was made even worse by the change in #10045. We removed
startingDirectory validation and promoted it to an error message (so
that we could eventually let the connection handle startingDirectory in
its own way.) This of course revealed that a number of users had set
invalid starting directories… and those users included some who set
closeOnExit to always. Boom: instant "terminal opens and …

Ignore closeOnExit when a conn. moves from Connecting to Failed

---

src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

Stop startup crash by logging when monarch fails to register inbound connections, but still crash when COM attempted to start us
- See also #10243 
- This should stop the crash on launch until we can get the internal teams to resolve the catalog issue
- I left the COM -Embedding start fail fast though so it won't take forever to time out (as default timeout is 3-5 minutes). I will change that if it becomes necessary.
- I basically have to guess at this one based on the crash dump and Watson logs because it happens sporadically when the platform messes up on us.

Switch FAIL_FAST to LOG for starting inbound connection server on monarch startup

---

src/cascadia/TerminalControl/TermControl.cpp
src/renderer/dx/DxFontRenderData.cpp
src/renderer/dx/DxFontRenderData.h

I cannot for the life of me repro the original bug. I've got fonts with bad permissions SxS, I've tried installing a font twice, I've tried stopping the font cache service. No idea how to manually repro the original bug.
BUT theoretically, this function should never throw. So lets just switch this to a `LOG_IF_FAILED`, and hope that this goes away? 
Unclear if this can get cherry-picked trivially to 1.8. Code's pretty trivial though so if we need another PR for that, it can be arranged.

Don't throw in `GetProposedDimensions`

---

src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/IslandWindow.h

Work around an ARM64 compiler crash by splitting a coroutine up

---

src/cascadia/Remoting/WindowManager.h
src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj
src/cppwinrt.build.pre.props

C++/WinRT has a way to ensure that we use `make<>` instead of allocating
WinRT objects on the stack, but until 10.0.19041 the XAML compiler
generated code that violated that rule.
Because of how make detection is implemented, it must create a derived
type (and so WinRT implementation types can't be `final`).

Enable winrt::make<> detection

---

tools/OpenConsole.psm1

When the `runformat` script was updated to include xaml formatting, the new code failed to work if run from anywhere other than the project root. This PR updates the script so it can be run from anywhere.
There were a couple of places in the script where it was collecting the list of xaml files by doing `git ls-files **/*.xaml`. That obviously relies on the code being executed from within the root of the project. I've now updated those queries to prefix the path with the `$root` variable, which points to the project root.
I've run the `runformat` script from within the tools directory and confirmed that it now works correctly from there. I've tested by changing some formatting in both .cpp and .xaml files, and also saved some .xaml files with a BOM to make sure those were appropriately …

Make the xaml formatting script work outside the root directory

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

Just come cleanup I did not manage to get to before #9270 merged. 
Specifically:
- We only initialize the animation and timer if we need them
- We don't repeatedly destroy/create the timer
It still works

Cleanup from bell flash PR

---

src/cascadia/TerminalSettingsEditor/Actions.cpp
src/cascadia/TerminalSettingsEditor/Actions.h
src/cascadia/TerminalSettingsEditor/Actions.idl
src/cascadia/TerminalSettingsEditor/Actions.xaml
src/cascadia/TerminalSettingsEditor/CommonResources.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h
src/cascadia/TerminalSettingsModel/ActionMap.cpp

Applies feedback from https://github.com/microsoft/terminal/pull/9949#pullrequestreview-662590658
Highlights include:
- bugfix: make all edit buttons stay visible if the user is using assistive technology
- rename a few functions and resources to match the correct naming scheme
- update the localized text for a conflicting key chord being assigned
- provide better comments throughout the actions page code
#9949 - Original PR
Closes #10168

Polish code for actions page

---

doc/cascadia/profiles.schema.json

Update profiles schema to draft 2020-12 because as mentioned in https://github.com/microsoft/vscode/issues/98724#issuecomment-786502628, OpenAPI Specification 3.1 defines using JSON Schema 2020-12 and VS Code already has early implementation around it.
Basically, this just gets rid of the following error shown by VS Code when editing the settings.json file
```
Draft 2019-09 schemas are not yet fully supported.
```

Update profiles schema to draft 2020-12

---

src/common.build.pre.props

Incremental linking was disabled for debug builds only by mistake in the past.
It can't hurt to have it enabled for debug builds.

Enable incremental linking for debug builds

---

src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.manifest
src/cascadia/WindowsTerminal/WindowsTerminal.manifest
src/cascadia/ut_app/TerminalApp.Unit.Tests.manifest

Restore embedded manifests to say 18362 or unpackaged activation won't work (for helix testing.)
- Unpackaged activation uses the embedded manifest inside the exe. We use unpackaged activation to run our tests in Helix as it's easier that way. Turns out the 1903/19h1 OS thinks 19041 isn't greater than the minimum XAML islands version of 18226 and blocks the load of `TerminalApp.dll` causing a crash (fail fast) on launch. For **REASONS**, 18362 is considered greater than 18226. 
- Packaged activation will use the value in the .appxmanifest and everything is somehow still fine there even with it saying 19041 now.
- Kicking a Helix-run off on this branch: https://dev.azure.com/ms/terminal/_build/results?buildId=177336&view=results

Restore embedded manifests to say 18362

---

src/cascadia/TerminalControl/ControlCore.cpp

- Any change to the renderer engine has to be done under lock. Leonard gave me a crash where the dirty rectangles changed out from under the renderer thread. By inspection, only one spot in `ControlCore` is modifying the engine outside of lock.... here. The dump is too far along to definitively prove the issue and it's sort of a race so its difficult to repro. But the theory is sound that all writes to the dirty regions must be done under lock. So here's a fix.

Lock for writing in `ControlCore::SetBackgroundOpacity`

---

src/cascadia/TerminalSettingsEditor/Converters.idl
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj.filters
src/cascadia/TerminalSettingsEditor/PercentageSignConverter.cpp
src/cascadia/TerminalSettingsEditor/PercentageSignConverter.h
src/cascadia/TerminalSettingsEditor/Profiles.xaml

This PR adds a new PercentageSignConverter that appends the percentage sign to a number. The new converter is being used by the Acrylic opacity slider label and the Background image opacity slider label.

Add percentage sign to opacity slider values

---

src/cascadia/WindowsTerminal/AppHost.cpp

Activate window only (no toggle) when inbound connection arrives
The default for the `SummonWindowBehavior` is a toggle of the visibility state. I didn't realize that. We do not want that for inbound connections. We want always-brought-to-front.
- Made the change. Launched Terminal as default as active window. Runbox'd another command. It didn't hide itself like it used to. Stays visible.

Activate window only (no toggle) when inbound connection arrives

---

src/cascadia/WindowsTerminal/AppHost.cpp

Summon, not toggle visibility, window on command line dispatch
- This is the same as #10389, just a different route. I didn't realize it at the time.
- Opened a window. Dispatched the `wt -w 0 - p <profile>` and watched it join/summon instead of minimize the active WT.

Summon, not toggle visibility, window on command line dispatch

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

Replaces the "feedback" button in the dropdown menu with a "command palette"
button.

Replace feedback button with command palette button in dropdown

---

doc/cascadia/profiles.schema.json

Add missing keys to the schema:
- globalSummon (and args: desktop, monitor, name, dropdownDuration, toggleVisibility)
- quakeMode
- iterateOn
- commands
Also enforces required keys for commands and deprecates "keybindings"
There were some other pending keys mentioned on the issue, but I don't think they are pending anymore.
Changed the `"$schema"` value in my settings.json to point to the edited one.

profile.schema: add missing actions and commands keys

---

src/cascadia/LocalTests_SettingsModel/SerializationTests.cpp
src/cascadia/TerminalSettingsModel/ActionMap.cpp
src/cascadia/TerminalSettingsModel/ActionMap.h
src/cascadia/TerminalSettingsModel/ActionMapSerialization.cpp
src/cascadia/TerminalSettingsModel/Command.cpp

Fixes a bug where top-level iterable commands were not serialized.
- `Command::ToJson`:
- iterable commands deserve the same treatment as nested commands
- `ActionMap`:
- Similar to how we store nested commands, iterable commands need to be handled separately from standard commands. Then, when generating the name map, we make sure we export the iterable commands at the same time we export the nested commands.

Bugfix: serialize iterable commands

---

.github/actions/spelling/patterns/patterns.txt
src/features.xml
src/host/exe/exemain.cpp
src/host/srvinit.cpp
src/host/ut_host/ClipboardTests.cpp
src/host/ut_host/VtIoTests.cpp
src/interactivity/base/EventSynthesis.cpp
src/interactivity/win32/window.cpp
src/renderer/dx/DxRenderer.cpp
src/renderer/dx/ScreenPixelShader.h
src/renderer/dx/ScreenVertexShader.h
src/server/IoDispatchers.cpp

This pull request converts four of our existing `#ifdef` (or `#ifndef`)
`INSIDE_WINDOWS` blocks to til::features:
* Attempting to establish a handoff session (inside Windows only)
* The ability to *receive* a handoff session (outside Windows only)
* The DX engine (outside Windows only) and shaders (also outside only)
* Whether we use numpad event synthesis for clipboard/conpty (inside
Windows only)
Most of these are using the preprocessor verison of til::feature, only
because it is more difficult to gate the inclusion of headers on
constant expressions. I'd love to prefer the compile time version.

Convert four INSIDE_WINDOWS blocks to til features

---

build/rules/GenerateFeatureFlags.proj

It was not set to `bypass`, which gave @carlos-zamora some trouble.
This commit brings it in line with the Windows build rule.

Force the execution policy on the til::feature powershell script

---

src/cascadia/TerminalSettingsEditor/Actions.xaml

Fixes a bug where the edit button in the actions page would have white text when in light theme. Now, we just fallback to XAML's built-in value (black in light theme and white in dark theme).
#6900 - Epic
Closes #10406

Fix edit button color in light theme

---

src/cascadia/TerminalApp/CommandPalette.cpp

Immediately cancelling the preview when the user is navigating back from a nested command.
Basically 2 changes are done here:
- Allow the click handler to run for the back button when the button has focus and user hits the enter key (similarly as hitting space now).
- Now immediately cancelling the preview when the user is navigating back. Felt nicer to do it immediately at that point then keeping the preview active until the user hits cancel to close the palette. So the preview is already cancelled at step **5** instead of 6 as mentioned in the reproduction steps here https://github.com/microsoft/terminal/issues/10165#issue-899838383. But of course let me know if you're not agreeing here 😀 .
- Open 'Color Scheme' and verified preview is still working fine when selecting different …

Cancel the preview of nested commands when moving back on the stack.

---

.github/actions/spelling/allow/apis.txt
src/server/ApiMessage.cpp
src/server/ApiMessage.h
src/server/WaitBlock.cpp

This commit introduces a copy constructor/operator for
`_CONSOLE_API_MSG`. The change is not trivial as the struct contains a
union of unnamed structs that cannot be copied using regular language
features. As such a copy operator using `memcpy` was implemented.
Additionally all access specifiers were removed, as those allow a C++
compiler to reorder struct members. This would break message passing.
This commit is a good opportunity to prevent such miscompilations
proactively.
* Command prompts of WSL2 fish-shell and pwsh still work ✔️
Closes #10076

Remove CONSOLE_API_MSG::UpdateUserBufferPointers hack

---

src/cascadia/TerminalApp/CommandPalette.cpp

An exception was introduced for the 'Toggle Command Palette' action to **not** being dispatched. Otherwise the command palette that was just closed will become visible again.
- Selecting the `Toggle command palette` item in the command palette will now properly close the command palette.
- Opening and closing the Command Palette through shortcut keys is still working fine.
- Other command palette items are still working fine as well.

Don't dispatch the Toggle Command Palette action to keep the just closed Command Palette closed.

---

src/cascadia/ShellExtension/OpenTerminalHere.cpp
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/Jumplist.cpp
src/cascadia/TerminalSettingsEditor/GlobalAppearance.cpp
src/cascadia/TerminalSettingsEditor/GlobalAppearance.h
src/cascadia/TerminalSettingsEditor/GlobalAppearance.idl
src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
src/cascadia/TerminalSettingsEditor/pch.h
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/pch.h
src/cascadia/WinRTUtils/inc/WtExeUtils.h

`ApplicationLanguages::PrimaryLanguageOverride` requires packaged activation.
This PR prevents any such application crashes, by skipping any calls to `PrimaryLanguageOverride`, as well as hiding the language selector in the settings UI.
When WT is run unpackaged:
* Doesn't crash during start ✔️
* SUI doesn't show the language selector ✔️

Fix crash when unpackaged due to PrimaryLanguageOverride

---

src/cascadia/LocalTests_SettingsModel/KeyBindingsTests.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.h
src/cascadia/TerminalSettingsModel/ActionMap.cpp

#10297 found a bug in `ActionMap` where the `ToggleCommandPalette` key chord could not be found using `GetKeyBindingForAction`.
This was caused by the following:
- `AddAction`: when adding the action, the `ActionAndArgs` is basically added as `{ToggleCommandPalette, ToggleCommandLineArgs{}}` (Note the default ctor used for the action args)
- `GetKeyBindingForAction`: we're searching for an `ActionAndArgs` structured as `{ToggleCommandPalette, nullptr}`
- Since these are _technically_ two different actions, we are unable to find it.
This issue was fixed by making the `Hash(ActionAndArgs)` function smarter! If the `ActionAndArgs` has no args, but the `ShortcutAction` _supports_ args, generate the args using the default ctor.
By making `Hash()` smarter, everybody benefits from this logic! We …

Ensure equality when hashing default args and no args in actions

---

src/cascadia/ShellExtension/OpenTerminalHere.cpp
src/cascadia/ShellExtension/dllmain.cpp
src/cascadia/TerminalApp/Resources/en-US/Resources.resw

This commit introduces localization for the "Open in Windows Terminal"
menu item and differentiates it based on compile-time branding (rather
than runtime detection!).
@leonMSFT's tray icon pull request had the excellent idea to use the
TerminalApp's resource compartment for auxiliary resources for projects
that can't otherwise be localized the same way. Doing localization in
the shell extension (or WindowsTerminal.exe) would require us to use
MUIRCT and split the build process up to support mui files. That's a
huge amount of work... but this is *not* a huge amount of work.
Fixes #6112

Localize the shell extension's menu item

---

tools/OpenConsole.psm1
tools/tests.xml

Fixes the `Invoke-CodeFormat` and `Invoke-OpenConsoleTests` functions in `OpenConsole.psm1` so that they can be run directly from PowerShell.
Addresses the issues found when creating #10447.
`Invoke-CodeFormat` did not work when invoked directly from PowerShell due to a relative path being passed into the .NET function `[IO.File]::WriteAllLines()`. The working directory for .NET objects does not change when you change directory in PowerShell, so the paths were being treated as relative to the initial working directory of the shell - which was not the terminal git repo.
`Invoke-OpenConsoleTests` had 3 issues:
1. The path to `TestHostApp` was wrong.
2. It would attempt to run the "in host app" tests both in the host app and not in the host app.
3. The test configuration in `tests.xml` …

Fix code-format and test invocation through PowerShell

---

src/cascadia/PublicTerminalCore/HwndTerminal.cpp
src/cascadia/PublicTerminalCore/HwndTerminal.hpp
src/cascadia/WpfTerminalTestNetCore/MainWindow.xaml.cs

The CursorStyle enum is declared as being of type `uint` on the C# side,
but as `size_t` on the C++ side. There's a C# size_t impostor we could
use, System.UIntPtr, but I don't want to risk changing the public API of
TerminalTheme and I don't know if it can be used as a base type for an
enum.
Anyway, since we don't have more than four billion cursor types I chose
to narrow the field to a uint32_t and unpack it in TerminalSetTheme.
Fixes #10485

wpf: fix the TerminalTheme struct to marshal the same on all platforms

---

src/renderer/gdi/paint.cpp

Replace PolyTextOutW with ExtTextOutW to allow substitution of missing
glyphs from other fonts.
Why not let Windows substitute the glyphs that are missing in the
current font?  Currently the GDI renderer of conhost/OpenConsole uses
`PolyTextOutW` for drawing.  `PolyTextOutW` doesn't try to substitute
any missing glyphs, so the only way to see, say, Hiragana is to change
the _whole font_ to something like MS Gothic (which is eye-bleeding, to
be honest).
A trivial replace `PolyTextOutW` -> `ExtTextOutW` does the trick.
Switch to `PolyTextOutW` happened in Windows 7 along with introduction
of conhost.exe.  Substitution worked in previous Windows versions, where
internal NT interfaces were used.
Closes #10472

Replace PolyTextOutW with ExtTextOutW

---

src/host/ConsoleArguments.cpp
src/host/ConsoleArguments.hpp
src/host/PtySignalInputThread.cpp
src/host/PtySignalInputThread.hpp

Fix startup race of resizing ConPTY
- Depending on what the timing and ordering is of the message coming in
from the signal thread, it may be applied to the startup structure
after the I/O thread has begun initializing the console buffer
structures but before it has signaled that it is done and the signal
thread is ready to make changes directly. This likely happens because
the end of the I/O thread setup has a weird unlock/lock jog for the
input thread and the signal thread might have been scheduled in the
middle of it.
- My resolution here is to ensure that the signal thread just keeps
storing the latest resize message until it is told that everything is
initialized. Whomever comes in to tell the signal thread this
information (under lock) will pickup and run the resize if one came in …

Fix startup race of resizing ConPTY

---

doc/cascadia/profiles.schema.json

Noticed the json schema was listing the option as invalid even though it's accepted by WT. So added it to schema to remove the error.
No longer shows as invalid in VSCode.

Add Settings UI enum to json schema

---

scratch/ScratchIslandApp/SampleApp/App.base.h

Sample scratch app would not compile. It does if we apply #10335 to App.base.h in the scratch app.
Closes #10493

Replicate winrt::make<> changes in ScratchIslandApp SampleAppLib

---

src/host/outputStream.cpp

Try to throttle the cursor redrawing in the conhost world.
The motivation of this is the high CPU usage of `TriggerRedrawCursor` (#10393).
This can be seen as the conhost version of #2960.
This saves 5%~8% of the CPU time.
Supports #10462.

Throttle cursor redrawing in outputStream.cpp

---

.github/actions/spelling/expect/expect.txt
doc/cascadia/AddASetting.md
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalSettingsModel/ApplicationState.cpp
src/cascadia/TerminalSettingsModel/ApplicationState.h
src/cascadia/TerminalSettingsModel/ApplicationState.idl
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp
src/cascadia/TerminalSettingsModel/FileUtils.cpp
src/cascadia/TerminalSettingsModel/FileUtils.h
src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj

This commit introduces a basic ApplicationState class, without being used for anything yet to aid reviewers. At a later point actual usages of this new class may be added separately.
This commit is an initial step towards implementing #8324.
* Creating a `state.json` with `{"generatedProfiles":["{53e75ed9-2b63-4118-856d-0510c4f6b97e}"]}` updates the ApplicationState, as observed through a debugger ✔️
* Deleting the "generatedProfiles" field sets the corresponding field back to nullopt ✔️

Introduce a basic ApplicationState class

---

src/terminal/parser/tracing.cpp
src/terminal/parser/tracing.hpp

Passing structures larger than the register size is very expensive
due to Microsoft's x64 calling convention. We could reduce the
overhead by passing the string-view by reference, but this forces us
to allocate the parameters as static string-views on the data
segment of our binary. I've found that passing them as classic
C-strings is more ergonomic instead and fits the need for
high performance in this particular code.
This improves performance for VT-heavy output by 15-20%.

Improve parser performance by reducing tracing overhead

---

src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
src/types/UiaTextRangeBase.cpp
src/types/UiaTextRangeBase.hpp

#7960 was caused by `UiaTextRangeBase::_blockRange` not being initialized, thus pointing to random memory. In most cases, we initialize it properly in `RuntimeClassInitialize`, however, the copying version of `RuntimeClassInitialize` doesn't actually copy it over, resulting in it still containing random memory.
NVDA (and other screen readers) occasionally use `Clone` (really just the copy initializer), resulting in this bug occurring randomly.
Test failed before the change, but passes after the change.

[A11y] Initialize and copy _blockRange in UIA Clone

---

src/host/_stream.cpp
src/host/screenInfo.cpp

Don't notify a11y event when in ConPTY mode
In support of #10528

Don't notify a11y event when in ConPTY mode

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h

Previously `TermControl::Close` destroyed all `ThrottledFunc`s to ensure they're not scheduling any callbacks on the UI thread, as the call to `Close` signals the point at which the `TermControl` isn't part of the UI thread anymore. `_CursorPositionChanged` tried to prevent access to the potentially deallocated `_tsfTryRedrawCanvas` by checking the `std::shared_ptr` for nullability, but since the deallocation happens on the UI thread and the nullability check on a background thread, this check introduced a race condition.
This commit solves the issue by not deallocating any `ThrottledFunc`s anymore and instead checking the `_closing` flag inside the `ThrottledFunc` callback on the UI thread.
Additionally this commit cleans up some antipatterns around the use of `std::optional`.
* Opening …

Fix racy access to _tsfTryRedrawCanvas in TermControl

---

src/renderer/dx/CustomTextLayout.cpp
src/renderer/dx/CustomTextRenderer.h
src/renderer/dx/DxRenderer.cpp

This commit adds support for bold text in DxRenderer.
For now, bold fonts are always rendered using DWRITE_FONT_WEIGHT_BOLD
regardless of the base weight.
As yet, this behavior is unconfigurable.
References
Previous refactoring PRs: #9096 (DxFontRenderData) #9201 (DxFontInfo) 
SGR support tracking issue: #6879
Closes #109

Render SGR 1 ("intensity") as bold in the DX engine

---

src/cascadia/TerminalSettingsEditor/Actions.cpp
src/cascadia/TerminalSettingsEditor/Actions.h
src/cascadia/TerminalSettingsEditor/Actions.idl
src/cascadia/TerminalSettingsEditor/Actions.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

This adds the "add new" button to the actions page. It build on the work of #10220 by basically just adding a new list item to the top of the key binding list.
This also makes it so that if you click the "accept changes" button when you have an invalid key chord, we don't do anything.
#6900 - Actions page Epic
#9427 - Actions page design doc
#10220 - Actions page PR - set action
- `ModifyKeyBindingEventArgs` is used to introduce new key bindings. We just ignore `OldKeys` and `OldActionName` because both didn't exist before.
- `IsNewlyAdded` tracks if this is an action that was added, but has not been confirmed to add to the settings model.
- `CancelChanges()` is directly bound to the cancel button. This allows us to delete the key binding when it's clicked on a "newly added" action.
- …

Add the 'Add new' button to the Actions page

---

src/renderer/base/thread.cpp

Delay load call SetThreadDescription to restore WPF renderer on Win7
I keep forgetting that anything in the WPF control needs to keep working on Win7. Or more specifically... I remember this fact for the DX renderer, but not for the render thread base. Oops. Turns out this particular convenience method to set thread descriptions for visibility inside the debugger (to make my life easier) only works down to 1607 (see https://docs.microsoft.com/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreaddescription). Since it's just a debugging convenience... skipping it entirely when the procedure is not found should be fine. Also I don't try to load `kernel32.dll` and just get the handle of the existing module (which per the remarks at …

Delay load call SetThreadDescription to restore WPF renderer on Win7

---

src/cascadia/WpfTerminalControl/WpfTerminalControl.csproj
src/cascadia/WpfTerminalTestNetCore/WpfTerminalTestNetCore.csproj

After all, it's required for Windows 7 compatibility.

wpf: make sure to pack api-ms-win-core-synch-l1-2-0

---

src/renderer/gdi/paint.cpp

Basically, the comment says everything:
https://github.com/microsoft/terminal/blob/c90de692509b074bfde191910d67154cfe389911/src/renderer/gdi/paint.cpp#L346-L347
However, handling things above U+FFFF doesn't really require extra effort. It's enough to:
- Put *all* characters to the output buffer
- Set the first width to cluster width and the rest to 0
- Sit back and relax while Windows does the rest
```CMD
@echo off
chcp 65001
echo 𠜎𠝹𠱓𠱸𠲖𠳏𠳕𠴕𠵼𠵿𠸎
echo 👨👩👧👦
```
Save this as a UTF-8 cmd file and run.
An example of a third party app working with surrogate pairs in a patched OpenConsole:
As discussed, this change doesn't claim to be the full support for surrogate pairs (there are still corner cases possible), but brings it on par with Terminal with minimal effort.

#10477: Handle things above U+FFFF in GDI renderer

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
src/cascadia/TerminalSettingsEditor/ReadOnlyActions.cpp
src/cascadia/TerminalSettingsEditor/ReadOnlyActions.h
src/cascadia/TerminalSettingsEditor/ReadOnlyActions.idl
src/cascadia/TerminalSettingsEditor/ReadOnlyActions.xaml
src/features.xml

Adds a feature flag `Feature_EditableActionsPage` that controls whether the Actions page in the Settings UI is read-only vs editable. The editable version is disabled for `Release` builds and enabled everywhere else (i.e. Dev, Preview, etc...).
Validated using `<stage>` `AlwaysEnabled` and `AlwaysDisabled`.
#6900 - Actions Page Epic
Closes #10578

Introduce feature flag for editable actions page

---

src/host/misc.cpp

Currently, when the user changes the console codepage (manually or via a script) the GDI engine tries to find and set the "best possible" font. The "best possible" here is charset-wise, it doesn't mean that the font is actually better or more eye-candy for the user.
Example:
- Open cmd
- Set the font to Consolas
- Enter `chcp 932`
- Suddenly, a wild MS Gothic appears!
This kind of makes sense (*"if I'm changing the codepage I probably want to see the national characters"*) but it doesn't happen anywhere else - all other apps just substitute the missing glyphs.
After #10472 / #10478 this magic should finally work here as well. So, do we still need to change the whole font? Terminal doesn't do that after all.
Download [932.cmd.txt](https://github.com/microsoft/terminal/files/6697577/932.cmd. …

#10497: Do not force the font on output codepage change

---

src/host/outputStream.cpp

Ensure that the cursor blink VT sequence gets flushed to terminal when conhost is attached to a pty
Closes #10543

Fix the cursor blink VT sequence being ignored

---

src/host/CursorBlinker.cpp
src/host/_output.cpp
src/host/_stream.cpp
src/host/conimeinfo.cpp
src/host/getset.cpp
src/host/screenInfo.cpp
src/host/screenInfo.hpp
src/host/selection.cpp
src/host/srvinit.cpp
src/interactivity/base/ServiceLocator.cpp
src/interactivity/inc/IAccessibilityNotifier.hpp
src/interactivity/inc/ServiceLocator.hpp
src/server/IoDispatchers.cpp

Change accessibility notifier creation so we do not create one when we're in PTY mode. (Guard all call sites to skip math/event work when the notifier is null.) MSAA events are legacy events that are registered for globally and used by some screen readers to find content in the conhost window. The PTY mode is not responsible for hosting the display content or input window, so it makes sense for it to not broadcast these events and delegate the accessibility requirement to the connected terminal.
- #10537

Skip accessibility notifier and all event calculations when we're in PTY mode

---

src/cascadia/ShellExtension/OpenTerminalHere.cpp

Sets the working directory of the terminal when invoked from the shell extension. This ensures that new tabs opened with a starting directory of `.` open in the directory that the terminal was invoked from.
Closes #8933
Manually tested - default PowerShell profile set to use home directory, Windows PowerShell profile set to use current directory. Launched via the shell extension and the default profile opened in the explorer directory, as did a new Windows PowerShell tab.

Set working directory when invoked from shell extension

---

src/renderer/dx/DxFontInfo.h
src/renderer/dx/DxFontRenderData.cpp
src/renderer/dx/DxFontRenderData.h

Fixes the performance regression caused by DxFontInfo.
DxFontInfo introduced in #9201

Add fast lookup path for DxFontInfo

---

src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

Adds try-catch blocks to the parts where we layer a fragment onto a profile and create a new profile from a fragment. This allows us to continue looping over the remaining fragments after failing to use a badly-formed one, instead of aborting prematurely.
Non-badly formed fragments get loaded even if there is a badly formed one somewhere

Fix all fragments not loading when one is badly formed

---

.github/actions/spelling/allow/allow.txt
doc/specs/#1790 - Font features and axes-spec.md
doc/specs/Font features and axes-spec.md

Add a spec for how we could allow users to define font features and axes of variation.
References #1790

Spec for font features and axes of variation

---

src/cascadia/TerminalSettingsEditor/MainPage.cpp

When discarding or saving settings, the current navigation should be retained.
Issue introduced by #10390
`menuItemsSTL` is filled with all _non_ profile navItems, then `menuItemsSTL` fills `menuItems`, then the profile navItems are added to `menuItems`. So to include the profile nav items in the iteration, `menuItems` needs to be used
Spam discard and save buttons

Include profile nav menu items to consider for retaining position

---

tools/razzle.cmd

After the introduction of scratch.sln, the nuget restore in razzle.cmd fails. This fixes it by specifying the sln file to use.
Ran razzle

Specify sln file to use for razzle nuget restore

---

src/cascadia/LocalTests_SettingsModel/DeserializationTests.cpp
src/cascadia/LocalTests_SettingsModel/KeyBindingsTests.cpp
src/cascadia/LocalTests_SettingsModel/TestUtils.h
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalControl/KeyChord.cpp
src/cascadia/TerminalControl/KeyChord.h
src/cascadia/TerminalControl/KeyChord.idl
src/cascadia/TerminalSettingsModel/ActionMap.h
src/cascadia/TerminalSettingsModel/ActionMapSerialization.cpp
src/cascadia/TerminalSettingsModel/KeyChordSerialization.cpp
src/cascadia/WindowsTerminal/IslandWindow.cpp

Replaces `KeyModifiers` with the pretty much equivalent
`VirtualKeyModifiers` enum in winrt.
After doing this I noticed #10593 which changes the KeyChords a lot, but
it seems these PRs are still compatible
The issue also mentions replacing Vkey with
`Windows::System::VirtualKey`, but I chose not to because that enum only
includes a subset of the keys terminal supports here (no VK_OEM_* keys)
Changed key bind in config, and confirmed it still works after
restarting terminal
Closes #877

Use WinRT VirtualKeyModifiers instead of a custom enum

---

src/cascadia/TerminalSettingsEditor/MainPage.xaml

When navigating the settings (or saving/discarding) the animation of the main content overflows the bar with the save and discard buttons. If the main content is encapsulated in a ScrollView the issue goes away.
Fixes one of the issues in #10609
Clicked around a whole bunch and have not seen the overflow happen again. Verified that on tabs where scroll is necessary it can still be scrolled, and reflow of elements still functions.

Encapsulate settings main frame to prevent overflow

---

src/cascadia/TerminalSettingsModel/ActionArgs.cpp

As in #10210. This string was already in the resources (so it should already be localized!)
* closes #10210.
* I work here
* tests? we don't got no stinkin' tests

Update the `quakeMode` action name

---

scratch/ScratchIslandApp/SampleApp/SampleAppLib.vcxproj
scratch/ScratchIslandApp/SampleApp/dll/SampleApp.vcxproj
scratch/ScratchIslandApp/SampleApp/packages.config
scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj
scratch/ScratchIslandApp/WindowExe/packages.config
src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/dll/TerminalApp.vcxproj
src/cascadia/TerminalApp/packages.config
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/cascadia/WindowsTerminal/packages.config
src/cascadia/WindowsTerminalUniversal/WindowsTerminalUniversal.vcxproj
src/cascadia/WindowsTerminalUniversal/packages.config

This is required for some inbox compliance tasks regarding symbol availability.

Update Xaml Toolkit App Host to 6.1.3

---

build/Helix/PrepareHelixPayload.ps1
build/Helix/packages.config
build/packages.config
build/pipelines/templates/helix-createprojfile-steps.yml
build/pipelines/templates/helix-runtests-job.yml
src/buffer/out/TextAttribute.hpp
src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
src/cascadia/TerminalSettingsEditor/Utils.h
src/cascadia/TerminalSettingsEditor/ViewModelHelpers.h
src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp
src/cascadia/TerminalSettingsModel/CascadiaSettings.h
src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj.filters
src/cascadia/UnitTests_Remoting/RemotingTests.cpp
src/cascadia/UnitTests_TerminalCore/ScreenSizeLimitsTest.cpp
src/cascadia/UnitTests_TerminalCore/TerminalApiTest.cpp
src/cascadia/WindowsTerminal_UIATests/WindowsTerminal.UIA.Tests.csproj
src/cascadia/WindowsTerminal_UIATests/packages.config
src/cascadia/inc/cppwinrt_utils.h
src/common.build.tests.props
src/cppwinrt.build.pre.props
src/host/ft_uia/Host.Tests.UIA.csproj
src/host/ft_uia/packages.config
src/inc/WilErrorReporting.h
src/inc/consoletaeftemplates.hpp
src/terminal/parser/ut_parser/packages.config
tools/OpenConsole.psm1
tools/razzle.cmd

This commit is a preparation for upcoming changes to KeyChordSerialization for #7539 and #10203.
In order to support variadic macros, /Zc:preprocessor was enabled, which required changing unrelated parts of the project.
* Project still compiles ✔️

Enable /Zc:preprocessor

---

src/cascadia/TerminalCore/TerminalDispatch.cpp
src/terminal/adapter/adaptDispatch.cpp

Quick fix for an error made in #10602 
References #8613
Closes #10658

Don't override success value when resetting mouse mode in hard reset

---

.github/actions/spelling/allow/apis.txt
.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalSettingsModel/KeyChordSerialization.cpp
src/inc/til/static_map.h
src/inc/til/string.h
src/til/ut_til/string.cpp

This commit is a preparation for upcoming changes to
KeyChordSerialization for #7539 and #10203.  It introduces several
string helpers to simplify key chord parsing and get rid of our implicit
dependency on locale sensitive functions, which are known to behave
erratically.
Additionally key chord serialization used to depend on iteration order
of a hashmap which caused different strings to be returned for the same
key chord. This commit fixes the iteration order and will always return
the same string.
* Key bindings are correctly parsed ✔️
* Key bindings are correctly serialized ❔

Clean up KeyChordSerialization

---

src/cascadia/PublicTerminalCore/HwndTerminal.cpp
src/cascadia/PublicTerminalCore/HwndTerminal.hpp
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalCore/Terminal.hpp
src/cascadia/TerminalCore/terminalrenderdata.cpp
src/inc/til/atomic.h
src/inc/til/ticket_lock.h

`SRWLOCK`, as used by `std::shared_mutex`, is a inherently unfair mutex
and makes no guarantee whatsoever whether a thread may acquire the lock
in a timely manner. This is problematic for our renderer which relies on
being able to acquire the lock in a timely and predictable manner.
Drawing stalls of up to one minute have been observed in tests.
This issue can be solved with a primitive ticket lock, which is 10x
slower than a `SRWLOCK` but still sufficiently fast for our use case
(10M locks per second per thread). It's likely that any non-trivial lock
duration will diminish the difference to "negligible".
* It still blends ✔️

Fix output stuttering using a ticket lock

---

src/cascadia/TerminalApp/ColorPickupFlyout.cpp

Removed custom min width which caused a weird space on the right side. Corner radius and other properties should also work properly now.

Fix color picker minimum width

---

src/cascadia/TerminalSettingsEditor/Profiles.cpp

Sends the additional xaml notification when the user presses the '+' or delete button for unfocused appearances
It works now

Fix unfocused appearance editor not appearing/disappearing correctly

---

src/cascadia/TerminalSettingsEditor/Actions.cpp
src/cascadia/TerminalSettingsEditor/Actions.h
src/cascadia/TerminalSettingsEditor/Actions.idl
src/cascadia/TerminalSettingsEditor/Actions.xaml
src/cascadia/TerminalSettingsEditor/KeyChordListener.cpp
src/cascadia/TerminalSettingsEditor/KeyChordListener.h
src/cascadia/TerminalSettingsEditor/KeyChordListener.idl
src/cascadia/TerminalSettingsEditor/KeyChordListener.xaml
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj.filters
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsEditor/pch.h

Replaces the key chord editor in the actions page with a listener instead of a plain text box.
#6900 - Settings UI Epic
- `Actions` page:
- Replace `Keys` with `CurrentKeys` for consistency with `Action`/`CurrentAction`
- `ProposedKeys` is now a `Control::KeyChord`
- removes key chord validation (now we don't need it)
- removes accept/cancel shortcuts (nowhere we could use it now)
- `KeyChordListener`:
- `Keys`: dependency property that hooks us up to a system to the committed setting value
- this is the key binding view model, which propagates the change to the settings model clone on "accept changes"
- We bind to `PreviewKeyDown` to intercept the key event _before_ some special key bindings are handled (i.e. "select all" in the text box)
- `CoreWindow` is used to get the modifier keys …

Add a KeyChordListener to the Settings UI

---

OpenConsole.sln
src/host/ut_host/ApiRoutinesTests.cpp

When you use the size parameter to WideCharToMultiByte, it only
null-terminates the output string if the input string was
null-terminated within the specified range.
Burned in for 1k runs-
BEFORE
Summary: Total=1000, Passed=997, Failed=3
AFTER
Summary: Total=1000, Passed=1000, Failed=0
Fixes MSFT-34656993

Make sure we terminate the expected title string

---

src/buffer/out/cursor.cpp
src/buffer/out/cursor.h
src/cascadia/TerminalCore/Terminal.cpp

Defer cursor winrt event triggering

---

doc/cascadia/profiles.schema.json

Looks like we forgot to add `experimental.input.forceVT` to the JSON schema when it was implemented in #6309

Add `experimental.input.forceVT` to JSON schema

---

src/cascadia/TerminalApp/TerminalPage.cpp

As discussed in team sync. Is this a mysterious dark pattern we didn't know about? 
* see also #10160

Add tracelogging for drag&drop on the new tab button

---

src/cascadia/WindowsTerminal/IslandWindow.cpp

When the quake window is moved to another monitor, re-evaluate it's size for that monitor.
* Similar, but not the same: #10274
We'll probably need to do this in a few more places, but I'm breaking PRs into small chunks for easier reviews.
Summoned the window to a bunch of different resolutions. Where it would use the wrong size before, it no longer does.

Re-evaluate the size of the quake window when it's summoned to a monitor

---

src/cascadia/TerminalSettingsEditor/MainPage.xaml

Add an explicit background color to part of the settings UI to prevent animation overflow. The previous solution (adding a ScrollViewer) caused problems.
#10619 adds a ScrollViewer for one of the issues in #10609
Visually confirmed the animation doesn't overflow, changed the theme and confirmed the colors are responsive. Confirmed the extra scrollbar is gone.

Add background color to grid to prevent animation overflow

---

src/cascadia/WindowsTerminal/IslandWindow.cpp

We were making the quake window exactly the width of the monitor it was on, but that didn't account for the 1px of border on either side.		
It happened before, it doesn't anymore.

Prevent the quake window's borders from hanging onto adjacent monitors

---

.github/actions/spelling/allow/allow.txt
.github/actions/spelling/allow/apis.txt
.github/actions/spelling/expect/expect.txt
doc/cascadia/profiles.schema.json
src/cascadia/LocalTests_SettingsModel/DeserializationTests.cpp
src/cascadia/LocalTests_SettingsModel/KeyBindingsTests.cpp
src/cascadia/LocalTests_SettingsModel/TerminalSettingsTests.cpp
src/cascadia/TerminalApp/CommandPalette.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalControl/KeyChord.cpp
src/cascadia/TerminalControl/KeyChord.h
src/cascadia/TerminalControl/KeyChord.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalSettingsEditor/KeyChordListener.cpp
src/cascadia/TerminalSettingsModel/ActionMap.cpp
src/cascadia/TerminalSettingsModel/ActionMap.h
src/cascadia/TerminalSettingsModel/KeyChordSerialization.cpp
src/cascadia/TerminalSettingsModel/defaults-universal.json
src/cascadia/TerminalSettingsModel/defaults.json
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h
src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/IslandWindow.h
src/inc/til/string.h
src/til/ut_til/string.cpp
tools/GenerateHeaderForJson.ps1

This commit introduces an alternative to specifying key bindings as a combination of key modifiers and a character. It allows you to specify an explicit virtual key as `vk(nnn)`.
Additionally this commit makes it possible to bind actions to scan codes. As scan code 41 appears to be the button below the Escape key on virtually all keyboards, we'll be able to bind the quake mode hotkey to `win+sc(41)` and have it work consistently across most if not all keyboard layouts.
The following was tested both on US and DE keyboard layouts:
* Ctrl+, opens settings ✔️
* Win+` opens quake mode window ✔️
* Ctrl+plus/minus increase/decrease font size ✔️

Introduce vk() and sc() key chord specifiers

---

src/inc/til/u8u16convert.h
src/server/ApiMessage.cpp

The `_CONSOLE_API_MSG` buffer is resized to cover an entire message.
Later on any UTF-8 data is cached in a separate temporary
buffer inside `til::u8state` to prevent lone surrogate pairs.
Both cases are problematic as neither buffer is freed after the read
has finished. Passing a 100MB buffer to conhost once will thus cause it
to continue using ~220MB of physical memory until the conhost process exits.
This change releases unneeded memory as soon as the requested buffer
size has halved. In practice this means that once a command has returned
all buffers will shrink, as the shell commonly sends very small messages.
* Buffers aren't reallocated during printing ✔️
* Buffers shrink after printing finished ✔️

Release unneeded memory more eagerly from conhost

---

src/cascadia/TerminalSettingsModel/Profile.cpp

We no longer automatically write the 'hidden' field for profile stubs we create
**Note**: This does not retroactively remove the automatically generated hidden fields in current settings files
Deleted the ubuntu stub in my settings file, booted up terminal, new created stub did not have the hidden field. Created a fragment that overrides the hidden field and it worked.

Don't auto-generate the hidden field when creating profile stubs

---

src/host/srvinit.cpp

Pass inbound handoff message via heap so it cannot race out of scope by the time it reaches the ConsoleIoThread
- `OpenConsole.exe` is started in response to the OS `conhost.exe` request for a handoff and prepares an Out Of Proc Multithreaded COM server.
- A COM thread from the pool inside `OpenConsole.exe` picks up the inbound message and allocates some stack space for the `CONSOLE_API_MSG` coming in
- That COM thread calls down to set up the I/O thread that will pump the console driver handle and passes a pointer to the stack-allocated `CONSOLE_API_MSG` as the `LPVOID` parameter for starting the thread.
Now one of two things happen:
1. The I/O thread is scheduled pretty much immediately (or soon enough that the COM thread hasn't messed with the stack space), picks up the pointer to the …

Pass inbound handoff message via heap so it cannot race out of scope by the time it reaches the ConsoleIoThread

---

src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalApp/Pane.h

Uses the new logic to find visual neighbors of a pane to find which pane is the target when the move-focus commands are used. 
It sounds like this logic will be refined later to meet #4692 
Created a grid of panes and confirmed that focus movement went to the right quadrant instead of just the first child of the sibling.

Update NavigateFocus function to use new visual-based navigation

---

src/interactivity/win32/window.cpp
src/renderer/dx/DxRenderer.cpp
src/renderer/dx/DxRenderer.hpp

This commit fixes the UseDx mode for conhost.
In order to add support for UseDx without calling `SetWindowSize`,
responsibility for resizing `_invalidMap` has been moved to occur
only when the renderer itself recognizes a new size. Furthermore
`InvalidateAll` is now the central point to invalidate `_invalidMap`.
* Enabling `UseDx` enables the DxEngine for conhost ✔️
* Resizing windows in conhost works ✔️
* Resizing windows in WT works ✔️
Closes #5455

Fix conhost UseDx mode

---

src/renderer/dx/DxFontRenderData.cpp

Turns out, DWrite will automatically turn some features on even if they weren't included in the feature vector passed into it. Remove these features from our default list for easier readability.

Remove some unnecessary font features from our default feature list

---

src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalConnection/ConptyConnection.cpp

- For tabs started from the Terminal, the initial sizing information is
passed into the connection and used to establish the PTY. Those
parameters are given over to the `OpenConsole.exe` acting as PTY to
establish the initial buffer/window size.
- However, for tabs started from outside, the PTY is created with some
default buffer information FIRST as the Terminal hasn't even been
involved yet. As such, when the Terminal gets that connection, it must
tell the PTY to resize just as it connects to match the window size
it's about to use.
- Ongoing resize operations in the Terminal did and still work fine
because they transmitted the updated size with the
`ResizePseudoConsole` API.
(like with CMD `mode con` command)
`mode con` command per bug repro
Closes #9811

[DefApp] Teach connection and tab to negotiate initial size

---

.github/actions/spelling/expect/expect.txt
src/buffer/out/OutputCellView.hpp
src/buffer/out/textBufferCellIterator.cpp
src/buffer/out/textBufferCellIterator.hpp

The `+=` operator is an extremely hot path under heavily output load. This PR aims to optimize its speed.

Optimize hot path in textBufferCellIterator

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalSettingsModel/KeyChordSerialization.cpp

Fixes/implements #10058 according to directions in that issue: added support for browser navigation keys to be used in actions.
The mouse back/forward keys do not correspond to the keys added here. That would be a nice (but more complicated) addition, I'll add an issue for it.

Fix: Multimedia Key Hotkey Support

---

src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

Implementation of #6219 with a small tweak, not just passing the keys when no panes are present, but passing on the keys when there is no other pane to move to. This enables another usecase: 2 panes in terminal split vertically; in one of these panes running tmux with two panes that are split horizontally. This allows the user to still navigate between tmux panes even though they have terminal panes open.
Not that I know of
Implementation by propagating the boolean indicating success of moving focus all the way to the action handler, where this result will determine whether the action will be considered handled or not. When the action is not handled, the keychord will be propagated to the terminal.
Manual testing; all relevant unit tests still work

Passing through moveFocus keys when moving to another pane failed

---

.github/actions/spelling/allow/allow.txt
src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp

For inexplicable reasons, the top row of pixels on our tabs, new tab
button, and caption buttons is totally unclickable. The mouse simply
refuses to interact with them. So when we're maximized, on certain
monitor configurations, this results in the top row of pixels not
reacting to clicks at all.
To obey Fitt's Law, we're gonna hackily shift the entire island up one
pixel. That will result in the top row of pixels in the window actually
being the _second_ row of pixels for those buttons, which will make them
clickable. It's perhaps not the right fix, but it works.
After discussion, we think this is a fine fix for this. We don't think
anyone's going to miss the top row of pixels on the TabView. The original
bug is painful enough for the subset of users it impacts that this is an
acceptable …

Shift the island up by 1px when maximized

---

src/cascadia/WindowsTerminal/IslandWindow.cpp

When we're restoring from fullscreen, we do a little adjustment to make sure to clamp the window bounds within the bounds of the active monitor. We unfortunately didn't account for the size of the non-client area (the invisible borders around our 1px border). This didn't matter most of the time, but if the window was within ~8px of the side of the monitor (any side), then restoring from fullscreen would actually move it to the wrong place. 
As it turns out, the `_quake` window is within ~8px of the edges of the monitor _very often_.
* regressed in #9737
The repro in the bug was fairly straightforward. It doesn't happen anymore.

Account for the window borders when restoring from fullscreen

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TabRowControl.cpp

Sets the tooltip text on the '+' button based on the keyboard modifiers
when dragging and dropping.
Manually tested - dragged a directory onto the '+ button and saw that
* The text changed when `shift` was pressed
* The text changed when `alt` was pressed
* The text changed back when `shift` or `alt` were released
Closes #10722

Set drag and drop on '+' tooltip text based on keyboard modifiers

---

.github/actions/spelling/expect/expect.txt
src/buffer/out/TextAttribute.cpp
src/buffer/out/TextAttribute.hpp
src/buffer/out/TextColor.cpp
src/buffer/out/TextColor.h
src/buffer/out/lib/bufferout.vcxproj
src/buffer/out/ut_textbuffer/TextAttributeTests.cpp
src/buffer/out/ut_textbuffer/TextColorTests.cpp
src/cascadia/TerminalCore/terminalrenderdata.cpp
src/host/consoleInformation.cpp
src/host/settings.cpp
src/host/settings.hpp
src/host/telemetry.cpp

I was watching a video about vectorized instructions and I wanted to
try out some new things, as I had never written AVX code before.
This commit is the result of this tiny Thursday morning detour into
AVX land. It improves performance of `TextColor::GetColor` by about 3x.
* Default colors are still properly shifted +8 ✔️

Vectorize TextColor::GetColor

---

src/host/screenInfo.cpp
src/host/ut_host/ScreenBufferTests.cpp

When switching to the alt buffer, the starting cursor position, style,
and visibility is meant to be inherited from the main buffer. Similarly,
when returning to the main buffer, any changes made to those attributes
should be copied back (with the exception of the cursor position, which
is restored to its original state). This PR makes sure we handle that
cursor state correctly.
At some point I'd like to move the cursor state out of the
`SCREEN_INFORMATION` class, which would make this inheritance problem a
non-issue. For now, though, I've just made it copy the state from the
main buffer when creating the alt buffer, and copy it back when
returning to the main buffer.
I've added some unit tests to verify the cursor state is inherited
correctly when switching to the alt buffer and back …

Make the alt buffer inherit cursor state from the main buffer

---

src/renderer/dx/DxRenderer.cpp

The `_invalidMap` size is dependent on both `clientSize` as well
as `glyphCellSize` and must be resized when either changes.
* Changing font size with Ctrl+Mousewheel in fullscreen works ✔️

Fix font changes not resizing _invalidMap

---

src/host/getset.cpp
src/host/ut_host/ConptyOutputTests.cpp

When the `SetContoleTitle` API is called with a title containing control
characters, we need to filter out those characters before we can forward
the title change over conpty as an escape sequence. If we don't do that,
the receiving terminal will end up executing the control characters
instead of updating the title. We were already filtering out the C0
control characters, but with this PR we're now filtering out C1 controls
characters as well.
I've simply updated the sanitizing routine in `DoSrvSetConsoleTitleW` to
filter our characters in the range `0x80` to `0x9F`. This is in addition
to the C0 range (`0x00` to `0x1F`) that was already excluded. 
I've added a conpty unit test that calls `DoSrvSetConsoleTitleW` with
titles containing a variety of C0 and C1 controls characters, and which …

Sanitize C1 control chars in SetConsoleTitle API

---

src/cascadia/LocalTests_SettingsModel/CommandTests.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.cpp

Fixes dragging and dropping drive letters onto the '+' button.
Manually tested - dragging and dropping the `C:\` drive onto the '+' button works when creating a new tab, splitting or creating a new window. Dragging and dropping a regular directory still works.
Closes #10723

Fix drag and drop on '+' button for drive letters

---

src/buffer/out/TextColor.cpp

Shortly before adding the SSE2 variant I "improved" it by using
`_mm_packs_epi32`, but failed to test it again afterwards.
* `printf "\e[mNORMAL \e[1mBOLD\n"` results in correct bold white glyphs ✔️

Fix SSE2 variant of TextColor::GetColor

---

src/host/screenInfo.cpp

When switching from the alt buffer back to the main buffer, we need to copy certain cursor attributes from the one to the other. However, this copying was taking place after the alt buffer had been freed, and thus could result in the app crashing. This PR simply moves that code up a bit so it's prior to the buffer being freed.
PR #10843 added the code that introduced this problem.
I was able to reproduce the crash when using a debug build, and confirmed that the crash no longer occurred after this PR was applied. I also checked that the cursor attributes were still being correctly copied back when returning from the alt buffer.

Fix a use-after-free crash when returning from the alt buffer

---

src/cascadia/TerminalApp/AppActionHandlers.cpp
src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/TabManagement.cpp
src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h
src/cascadia/TerminalConnection/CTerminalHandoff.cpp
src/cascadia/TerminalConnection/CTerminalHandoff.h
src/cascadia/WindowsTerminal/AppHost.cpp

- Monarch no longer sets itself up as a `CTerminalHandoff` multi instance server by default
- In fact, `CTerminalHandoff` will only ever be a single instance server 
- When COM needs a `CTerminalHandoff`, it launches `wt.exe -embedding`, which gets picked up by the Monarch and then gets handed off to itself/peasant depending on user settings.
- Peasant now recognizes the `-embedding` commandline and will start a `CTerminalHandoff` single instance listener, and receives the connection into a new tab.
Closes #10358

[DefApp] Move from Monarch multi instance servers to Peasant single instance servers

---

src/cascadia/TerminalApp/AppLogic.cpp
src/cascadia/TerminalApp/AppLogic.h
src/cascadia/TerminalApp/LanguageProfileNotifier.cpp
src/cascadia/TerminalApp/LanguageProfileNotifier.h
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/TerminalAppLib.vcxproj.filters
src/cascadia/TerminalApp/pch.h

`VkKeyScanW` as well as `MapVirtualKeyW` are used throughout
the project, but are input method sensitive functions.
Since #10666 `win+sc(41)` is used as the quake mode keybinding,
which is then mapped to a virtual key in order to call `RegisterHotKey`.
This mapping is highly dependent on the input method and the quake mode
key binding will fail to work once the input method was changed.
* win+` opens quake window before & after changing keyboard layout ✔️
* keyboard layout changes while WT is minimized trigger reloaded ✔️

Reload settings when the input method changes

---

src/cascadia/TerminalControl/ControlCore.cpp

Do not invoke terminal resize logic if view port dimensions didn't change
Short-circuit `ControlCore::_doResizeUnderLock` if the dimensions of the
required view port are equal to the dimensions of the current view port

Prevent redraw upon resize if new size is equal to old

---

src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/IslandWindow.h
src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
src/cascadia/WindowsTerminal/NonClientIslandWindow.h

Turns out, we'd only ever use the non-client size to calculate the size of the window, but not the actual position. As we learned in #10676, the nonclient area extends a few pixels past the visible borders of the window. 

Account for the window frame when calculating initial position

---

src/cascadia/TerminalCore/TerminalApi.cpp
src/inc/til.h

Apparently the exception handler in TerminalApi is far too talkative. We're apparently throwing in `TerminalApi::CursorLineFeed` way too often, and that's caused an internal bug to be filed on us.
This represents making the event less talkative, but doesn't actually fix the bug. It's just easier to get the OS bug cleared out quick this way. 
* MSFT:33310649

Make the TerminalApi exception handler less garrulous

---

src/cascadia/LocalTests_SettingsModel/KeyBindingsTests.cpp
src/cascadia/TerminalApp/AppKeyBindings.cpp
src/cascadia/TerminalApp/AppKeyBindings.h
src/cascadia/TerminalControl/IKeyBindings.idl
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/TerminalSettingsModel/ActionMap.cpp
src/cascadia/TerminalSettingsModel/ActionMap.h
src/cascadia/TerminalSettingsModel/ActionMap.idl
src/cascadia/UnitTests_TerminalCore/InputTest.cpp
src/cascadia/WindowsTerminal/main.cpp

This PR implements/solves #7125. Concretely: two requests regarding alt+space were posted there:
1. Disabling the alt+space menu when the keychord explicitly unbound - and forwarding the keystroke to the terminal
2. Disabling the alt+space menu when the keychord is bound to an action
Not that I know
The issue was marked Help-Wanted. I am happy to change the implementation to better fit your (planned) architecture.
While researching the solution, I noticed that the XAML system was always opening the system menu after Alt+Space, even when explicitly setting the event to be handled according to the documentation. The only solution I could find was to hook into the "XAML bypass" already in place for F7 KeyDown, and Alt KeyUp keystrokes. This bypass sends the keystroke to the AppHost …

Adding/fixing Alt+Space handling

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControlAutomationPeer.cpp
src/cascadia/TerminalControl/TermControlAutomationPeer.h

This was missed in #10051. We need to make sure that the UIA provider can immediately know about the padding in the control, not just after the settings reload.
Checked before/after in Accessibility Insights. Before the row rectangles were the full width of the control initially. Now they're properly padded.

Initialize the padding for the Control UIA provider

---

.github/actions/spelling/expect/expect.txt
src/cascadia/LocalTests_SettingsModel/KeyBindingsTests.cpp
src/cascadia/TerminalControl/KeyChord.cpp
src/cascadia/TerminalSettingsModel/ActionMap.cpp
src/cascadia/TerminalSettingsModel/ActionMap.h
src/cascadia/WindowsTerminal/IslandWindow.cpp
tools/OpenConsole.psm1
tools/tests.xml

The quake mode keybinding is bound to a scancode. This made it
impossible to override it with a vkey-based one like "win+\`".
This commit fixes the issue by making sure that a `KeyChord` always has a vkey,
and leveraging this fact inside ActionMap, which now ignores the scan-code.
* quake mode and other keybinding still work ✔️
* Repro settings from #10875 work correctly ✔️

Fix layering of sc() keybindings with vk() ones

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalSettingsModel/FileUtils.cpp

WriteUTF8FileAtomic  overrides the content of the file "atomically"
by creating a temp file and then renaming it to the original path.
The problem arises when the original path is symbolic link,
as the link itself gets overridden by a file (rather than the link target).
This PR introduces a special handling of the symlinks:
if the path as a symlink we resolve the path and use:
1. target's directory to create a temp-file in
2. target itself to be replaced with the tempfile.
Symlink resolution is problematic when the target path does not exist,
as there is no good utility that resolves such link (canonical() fails).
In this corner case we skip the "atomic" approach of renaming the file
and write the link target directly.
Closes #10787

Fix WriteUTF8FileAtomic to preserve symlinks

---

src/host/_stream.cpp

Improve WriteCharsLegacy performance by increasing LocalBuffer size, allowing
longer runs of characters to be submitted to the remaining parts of conhost.
References #10563 -- vtebench tracking issue
* Ran `cat big.txt`, vtebench and termbench and
noted ~5% performance improvements

Improve WriteCharsLegacy performance by increasing local buffer size

---

src/cascadia/TerminalSettingsEditor/MainPage.xaml

Change settings content frame transition to drill in

---

src/types/UiaTextRangeBase.cpp
src/types/UiaTextRangeBase.hpp

Fixes a bug where interacting with Windows Terminal when using Narrator causes Windows Terminal to hang.
`UiaTextRangeBase::Move()` locks, but later calls `UiaTextRangeBase::ExpandToEnclosingUnit()` which attempts to lock again. The workaround for this is to introduce a `_expandToEnclosingUnit()` that _does not_ lock the console. Then, `Move()` calls this new method, thus only allowing one lock to be established at a time.
This bug is observed to be in v1.11.2221.0 and _not_ in v1.9.1942.0.

Prevent deadlock in UIA Move API

---

src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalSettingsModel/CascadiaSettingsSerialization.cpp

Let's say a user doesn't know that they need to write `"hidden": true` in
order to prevent a profile from showing up (and a settings UI doesn't exist).
Naturally they would open settings.json and try to remove the profile object.
This section of code recognizes if a profile was seen before and marks it as
`"hidden": true` by default and thus ensures the behavior the user expects:
Profiles won't show up again after they've been removed from settings.json.
#8324 - Application State
* settings.json/state.json are created if they don't exist ✔️
* Removing any profile from settings.json doesn't cause it to appear again ✔️
* Hitting save in SUI creates profiles with `"hidden": true` ✔️
* Removing a default profile and hitting save in SUI works ❌
An empty object is added instead.

Hide profiles by default if they aren't new

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalSettingsModel/AppearanceConfig.h

From discussion at #10678, we will ship with "intense" as bright for now until we fix text getting cut off by some bold fonts.

Render "intense" text as bright by default

---

src/cascadia/TerminalControl/ControlCore.cpp
src/cascadia/TerminalControl/ControlInteractivity.cpp
src/cascadia/TerminalControl/TermControl.cpp
src/types/UiaTextRangeBase.cpp

The bug was that Narrator would still read the content of the old tab/pane although a new tab/pane was introduced. This is caused by the automation peer not being created when XAML requests it. Normally, we would prevent the automation peer from being created if the terminal was not fully initialized.
This change allows the automation peer to be created regardless of the terminal being fully initialized by...
- `TermControl`: `_InitializeTerminal` updates the padding (dependent on the `SwapChainPanel`) upon full initialization
- `ControlCore`: initialize the `_renderer` in the ctor so that we can attach the UIA Engine before `ControlCore::Initialize()` is called (dependent on `SwapChainPanel` loading)
As a bonus, this also fixes a locking issue where logging would attempt to get the text …

Ensure automation peer is created regardless of terminal initialization

---

src/cascadia/TerminalApp/AppCommandlineArgs.cpp
src/cascadia/TerminalSettingsModel/ActionArgs.h
src/cascadia/TerminalSettingsModel/ActionArgs.idl

When creating `startupAction` use `TabSwitcherMode::Disabled` in action args
to disable the tab switcher and prevent MRU logic to be applied.
Closes #10070

Fix focus-tab --previous/next to ignore tab switcher order

---

src/cascadia/Remoting/WindowManager.cpp
src/cascadia/Remoting/WindowManager.h
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h

Some followups to #10368:
- Accidentally reverted a defapp change where the Monarch should not by default register itself as a handoff server.
- Destroy the tray icon if we're a monarch otherwise if we're a quake window we request the monarch to hide the icon.

Tray Icon PR followup

---

src/cascadia/LocalTests_SettingsModel/KeyBindingsTests.cpp
src/cascadia/TerminalControl/KeyChord.cpp
src/cascadia/TerminalControl/KeyChord.h
src/cascadia/TerminalControl/KeyChord.idl
src/cascadia/TerminalSettingsModel/ActionMap.cpp
src/cascadia/TerminalSettingsModel/ActionMap.h
src/cascadia/ut_app/JsonTests.cpp

This commit partially reverts d465a47 and introduces an alternative approach by adding Hash and Equals methods to the KeyChords class. Those methods will now favor any existing Vkeys over ScanCodes.
* Added a new test, which is ✔️
* Various standard commands still work ✔️
* Hash() returns the same value for all KeyChords that are Equals() ✔️

Make ActionMap compatible with ScanCode-only KeyChords

---

scratch/ScratchIslandApp/Package/Package.wapproj
scratch/ScratchIslandApp/SampleApp/SampleAppLib.vcxproj
scratch/ScratchIslandApp/SampleApp/dll/SampleApp.vcxproj
scratch/ScratchIslandApp/SampleApp/packages.config
scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj
scratch/ScratchIslandApp/WindowExe/packages.config
src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
src/cascadia/LocalTests_SettingsModel/SettingsModel.LocalTests.vcxproj
src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
src/cascadia/TerminalApp/App.xaml
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/dll/TerminalApp.vcxproj
src/cascadia/TerminalApp/packages.config
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
src/cascadia/TerminalSettingsEditor/packages.config
src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
src/cascadia/TerminalSettingsModel/dll/Microsoft.Terminal.Settings.Model.vcxproj
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/cascadia/WindowsTerminal/packages.config
src/cascadia/WindowsTerminalUniversal/WindowsTerminalUniversal.vcxproj
src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj

This commit moves us from MUX 2.5 to MUX 2.6. I have temporarily
disabled the new control styles in `TerminalApp\App.xaml` by setting
`ControlsResourcesVersion` to `Version1`. There is no significant expected
visual impact.
Closes #10508

Upgrade to Microsoft.UI.Xaml 2.6.2 (or equivalent)

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Reword the bold enum options for clarity

Reword bold enum options

---

src/cascadia/TerminalControl/TermControl.cpp

Pretty straightforward. Check if the scroll event is a horizontal movement. If it is, ignore it. We don't have a horizontal scrollbar.
* obviously, revisit this if we ever do #1860 
* scrolled ↑/↓ with slaptop trackpad: terminal scrolls.
* scrolled ←/→ with slaptop trackpad: terminal doesn't scroll.
* Scrolling _slightly more vertically than horizontally_ still scrolls.
* Scrolling _slightly more horizontally than vertically_ doesn't scroll.

Don't scroll vertically on horizontal scroll motions
