tools/ColorTool/ColorTool/ColorTool.csproj

Addresses issue https://github.com/Microsoft/console/issues/7

retarget csproj from net47 to net46

---

tools/ColorTool/build.bat

Added a path check for the standalone VS 2017 Build Tools

Added support for using VS 2017 Build Tools

---

tools/ColorTool/README.md

For those who just want the zip / don't have a build environment set up.

Add a link to colortool releases page

---

README.md

Small, bite-sized PR. Now that both ConPTY samples (https://github.com/Microsoft/console/pull/247 and https://github.com/Microsoft/console/pull/260) are merged, mention them on the main repository README.

Add the new ConPTY samples to the readme

---

tools/ColorTool/ColorTool/Program.cs
tools/ColorTool/ColorTool/Resources.resx

Also used path combine for schemes directory

Added location flag to colortool and updated help.

---

tools/ColorTool/README.md

I discovered this by trial and error, and it seemed worth documenting.

Document loading colortool schemes from current dir

---

tools/ColorTool/ColorTool/JsonParser.cs

added Support for parsing screen color in json

---

README.md

Hey guys, I want in on the fun. Added my twitter handle and information to the contact list.

Add myself to list of contacts on README

---

build/pipelines/ci.yml
build/pipelines/release.yml
build/pipelines/templates/build-console-ci.yml
build/pipelines/templates/build-console-int.yml
build/pipelines/templates/build-console-steps.yml
build/pipelines/templates/release-sign-and-bundle.yml
consolegit2gitfilters.json

This pull request (already reviewed internally, but now we're on GitHub!) ports our build pipeline to yaml!

Port our existing Azure Pipeline to YAML

---

README.md

Add some really basic guidance on how to get started with the Terminal project

Add some prerequisites to the readme

---

README.md

Updated "console" to "Terminal" in one of the links, see file changes for more info.

Update GitHub URL link

---

README.md

Fixes a small grammatical error in the README.

Fix grammatical error

---

samples/ConPTY/EchoCon/readme.md

minor readme fix

---

src/cascadia/TerminalApp/App.cpp
src/cascadia/TerminalApp/CascadiaSettings.cpp
src/cascadia/TerminalApp/Profile.cpp

There were 3 casts warnings, fixed now.

Fix casts warnings.

---

src/cascadia/TerminalApp/App.cpp

close one tab by press ctrl-w and hide the bar
fix #614

close one tab by press ctrl-w and hide the bar

---

src/cascadia/TerminalApp/App.cpp
src/cascadia/TerminalApp/App.h
src/cascadia/TerminalApp/AppKeyBindings.cpp
src/cascadia/TerminalApp/AppKeyBindings.idl
src/cascadia/TerminalApp/CascadiaSettings.cpp

alt-1 for the 1st tab, alt-2 for the 2nd tab, etc
fix #573

add shortcut alt-* for select tab

---

src/cascadia/TerminalApp/CascadiaSettings.cpp

Sets powershell as the default profile.
#431

Make powershell the default profile

---

src/renderer/dx/DxRenderer.cpp

See issue #677 for screenshots on how this affects the colors.

The opacity of the text background color was set to 0.9 (#677)

---

README.md

Fixes #700 
Added a new section "Debugging" to README, please review and let me know if this is not appropriate.

doc: append Debugging section with instructions to enable debugging

---

README.md

Improve the formatting of keyboard keys

---

src/cascadia/TerminalApp/App.cpp

fix tab control and tabs is not synced after focused tab is removed

---

README.md

Made bullets consistent with other bullets.

Make's README list consistent

---

src/cascadia/TerminalApp/App.cpp
src/cascadia/TerminalApp/App.h
src/cascadia/TerminalApp/App.idl
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h
src/cascadia/WindowsTerminal/IslandWindow.cpp
src/cascadia/WindowsTerminal/IslandWindow.h

Apologies for the indentation issues that might be visible here.
#627

Changes to be able to quit the application via exit inside a CLI prompt.

---

src/cascadia/TerminalApp/App.cpp
src/cascadia/TerminalApp/App.h
src/cascadia/TerminalApp/AppKeyBindings.cpp
src/cascadia/TerminalApp/AppKeyBindings.h
src/cascadia/TerminalApp/AppKeyBindings.idl
src/cascadia/TerminalApp/CascadiaSettings.cpp
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalControl/TermControl.idl

Added Keybindings for go up and go down page

---

README.md

Added the documentation policy to README.md
[#636](https://github.com/microsoft/terminal/issues/636)

Added documentation policy to README.md

---

doc/AddASetting.md
doc/ConsoleCtrlEvent.md
doc/ConsoleHostSettings.md
doc/Debugging.md
doc/ORGANIZATION.md
doc/UniversalTest.md
doc/WindowsTestPasses.md
doc/building.md

I've fixed some typo's in the docs and improved the consistency (for example in lists).

Fixed typo's and improved consistency.

---

README.md

Replace `your` with `you` due to the word `your` doesn't fit this context.
None

doc: Fix non-grammatical sentence

---

src/host/ft_host/DefaultResource.rc

[Git2Git] Merged PR 3285709: Add chafa resource into the DLL built by Windows Razzle #21439265
Add chafa resource into the DLL built by Windows Razzle #21439265

inbox: Add chafa resource into the DLL built by Windows Razzle

---

build/pipelines/ci.yml

Re-enable ARM64 in CI

---

src/cascadia/TerminalApp/App.cpp

Closing the tab shifts focus to the right

---

.vsconfig

Remove ATL from .vsconfig!

---

src/cascadia/TerminalApp/App.cpp

Fixes an incorrect `await` that slipped in with #903

fix build break from using `await` instead of `co_await`

---

src/cascadia/WindowsTerminal/IslandWindow.cpp

Remove the 🔔 when pressing Alt+key
* [🔔] Closes #819
* [🔔] CLA signed
* [🔔] Manually tested
* [🔔] Requires documentation to be updated
* [🔔] I've discussed this with core contributors already.
Shoutout to @Austin-Lamb who really deserves all the credit here

Fix the bell sound when Alt+key is pressed.

---

src/cascadia/TerminalCore/Terminal.cpp

Updated Typo in Function Comment
No

Fix Typo In Terminal.cpp Comment

---

samples/ConPTY/EchoCon/EchoCon/EchoCon.cpp
src/host/CommandListPopup.cpp
src/host/ConsoleArguments.cpp
src/host/alias.cpp
src/host/cmdline.cpp
src/host/conattrs.cpp
src/host/consoleInformation.cpp
src/host/dbcs.cpp
src/host/directio.cpp
src/host/getset.cpp
src/host/history.cpp
src/interactivity/base/InteractivityFactory.cpp
src/interactivity/base/ServiceLocator.cpp

Some spelling mistakes in comments.

Some Typo-Fixes in Comments

---

.gitignore
tools/OpenConsole.psm1

I'm not sure this is good, since I don't write a lot of powershell, and
I don't know the project very well, but hopefully it's good!

Fix OpenConsole.psm1 to use vswhere

---

build/pipelines/ci.yml
build/pipelines/release.yml
build/pipelines/templates/build-console-audit-job.yml
build/pipelines/templates/check-formatting.yml
build/pipelines/templates/release-sign-and-bundle.yml

Split the code format check into its own job so it's easier to tell if it failed.

split code format check into its own job

---

src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp

Ignore UTF-8 BOM in profile.json
If we found UTF8-BOM at the beginning of our data, we offset the pointer to ignore it.
Save `profile.json` with regular UTF-8, reload terminal.
Save `profile.json` with UTF-8 with BOM, reload terminal.

Ignore UTF-8 BOM in profile.json

---

doc/EXCEPTIONS.md

Minor changes to the `doc/EXCEPTIONS.md` file: adding code highlighting to rules 2 and 5, and changing "Encapsulate" to "encapsulate" in rule 3 to be consistent with the other rules.

Code highlighting and capitalization fix for doc/EXCEPTIONS.md

---

doc/ProfilesJSONDocumentation.md
doc/cascadia/SettingsSchema.md

Added documentation for profiles.json file.

adding profiles.json documentation

---

src/cascadia/TerminalConnection/ConhostConnection.cpp

The signal pipe must be terminated first. It is this very termination
that signals to the connected console host that it should begin exiting
in an orderly manner.
We're introducing an indefinite wait (yes, I know: it's not great) for
conhost to exit. **This matches ClosePseudoConsole in
kernelbase/winconpty.**
If it does not exit in an orderly manner, powershell (and perhaps other
.NET CLI applications) may crash immediately after conhost exits.
Fixes #1338.

Fix the total teardown order for ConhostConnection

---

src/cascadia/TerminalApp/App.cpp

Workaround C++/WinRT's multi-level composition class refcount issue

---

src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp

This stops the crash in #1318.

If we failed to get a default profile, fail the settings load

---

README.md

Update README.md with Store info

---

doc/cascadia/SettingsSchema.md

Add a link to the ColorTool for better understanding.

Add ColorTool link to profiles.json documentation

---

src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
src/cascadia/TerminalApp/Tab.cpp
src/cascadia/TerminalApp/TerminalApp.vcxproj
src/cascadia/TerminalApp/packages.config
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/cascadia/WindowsTerminal/packages.config

Move to Microsoft.UI.Xaml 2.2.109211001-prerelease

---

.github/ISSUE_TEMPLATE/Bug_Report.md

This is from discussion in triage today

Update the title of the bug report template

---

README.md

The link to docs was pointing to issues. Set it to point to the root of the repo.
Minor update to documentation. The link to the docs was pointing to the /issues tab; I updated it to point to the root which is where I believe it should go.

Updated link to docs

---

.github/ISSUE_TEMPLATE/Bug_Report.md
.github/ISSUE_TEMPLATE/Feature_Request.md
doc/bot.md

Getting tired of obvious low quality issues and I want to provide the warning that we may start closing things without further explanation as our volume is too high to deal with junk issues.

Propose banner at top of templates

---

README.md

Update the readme to clear out references to VS2017

---

doc/Niksa.md

I've made some decent explanations of stuff in comments to issue threads that could be used for future reference. As such, I'm going to stuff them into a markdown doc.

Doc of stuff I've explained.

---

README.md

Updated documentation regarding the Chocolatey package installation 
#2044
Updated documentation
N/A

(GH-2044) Updated readme to include Chocolatey package

---

src/cascadia/TerminalApp/TabRowControl.xaml

The + icon still looked big, so I made it smaller.

Shrink the + icon

---

doc/cascadia/SettingsSchema.md

Update SettingsSchema.md to fix #2121

---

src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest

This will help with our erroneous device targeting.

Change Windows.Universal to Windows.Desktop in our manifest

---

doc/ConsoleHostSettings.md

Added a line for WxH character in the documentation.

Added information on WxH character

---

doc/bot.md

We added a few more rules. Update the bot doc description.

Update bot with new rules

---

README.md

I don't think the README actually mentions that you need 18362 to run the Terminal. This is confusing to people.

Add a note about the build required to the README

---

doc/cascadia/Unittesting-CppWinRT-Xaml.md
src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/packages.config
src/cascadia/TerminalConnection/packages.config
src/cascadia/TerminalControl/packages.config
src/cascadia/TerminalCore/packages.config
src/cascadia/TerminalSettings/packages.config
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/cascadia/WindowsTerminal/packages.config
src/cppwinrt.build.post.props
src/cppwinrt.build.pre.props

wil `fbcd1d2a` -> `e8c599bc`
gsl `b74b286d` -> `1212beae`
Microsoft.VCRTForwarders.140 `1.0.0-rc` -> `1.0.1-rc`
Microsoft.Toolkit.Win32.UI.XamlApplication `6.0.0-preview6.*` -> `6.0.0-preview7`
Microsoft.Windows.CppWinRT `2.0.190605.7` -> `2.0.190730.2`

Update a number of our dependencies

---

doc/cascadia/SettingsSchema.md

Adds a list of the implemented keybindings to the docs/cascadia/SettingsSchema.md per #1984 
No
N/A
N/A

Add list of keybindings to SettingsSchema.md

---

doc/user-docs/index.md

fix typo reaons -> reasons in user-docs

---

doc/user-docs/UsingJsonSettings.md

I'm not replying to another thread where people are confused about this. Let's just add it to the docs.

Add info about adding copy/paste keybindings

---

doc/Niksa.md

This seemed like it fit the style & depth of the other Niksa posts, so I'm proposing we add it here. We could always make a `Howett.md` if that seems more reasonable

Add Dustin's comment from #632 to Niksa's Doc

---

src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.manifest
src/cascadia/WindowsTerminal/WindowsTerminal.manifest

This HARDCORE breaks unpackaged activation. So don't so this. While we don't support unpackaged activation quite yet, this will be an enormous debugging drain if you capitalize it.

TURNS OUT CASE SENSITIVITY IS IMPORTANT

---

src/cascadia/TerminalApp/CascadiaSettings.cpp
src/cascadia/TerminalConnection/AzureConnection.cpp
src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControlAutomationPeer.cpp
src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/IslandWindow.h
src/cascadia/WindowsTerminal/WindowUiaProvider.cpp
src/cppwinrt.build.pre.props

warnings as errors for cppwinrt projects and fix the warnings.

---

doc/cascadia/SettingsSchema.md

Fixes the link to the Images and Icons section, it was previously linking to the parent folder.

Update link to Background Images and Icons section

---

build/scripts/Test-WindowsTerminalPackage.ps1
src/cascadia/CascadiaPackage/CascadiaPackage.wapproj

This pull request adds some rules to our wap project that suppress existing rules that were removing vital files.
I even added a validation phase!

wap: add some workaround to ensure that our package builds on 16.3

---

doc/user-docs/index.md

* Adds some light edits throughout.
* Adds link to `winver` documentation.

Edits doc section `Installing Windows Terminal`

---

src/cascadia/TerminalApp/CascadiaSettingsSerialization.cpp

Fixes #2796
Ran it; in-person validation with an affected customer.

Don't let one bad Dynamic Profile Generator spoil the bunch

---

src/cascadia/TerminalApp/defaults.json

defaults: bind alt+f4 to closeWindow

---

doc/cascadia/Keybindings-spec.md
doc/virtual-dtors.md

N/A
just fix some typo in documentations

minor fix typo

---

README.md

Fixed a link to Roadmap & improved Readme

Fixed a link to Roadmap & improved Readme

---

doc/user-docs/UsingJsonSettings.md
doc/user-docs/index.md

Just doing a bit of maintenance work on the docs. Let me know if I'm missing anything or sound a bit weird.

Docs: Update Info on "Copy" Operation

---

doc/user-docs/UsingJsonSettings.md

Update some of the documentation regarding the guids of dynamic profiles.

add note on dynamic profile GUIDs

---

README.md

This PR updates README.md. Since version 1903 has been released for long time, let's change "wait for 1903 release" to "version 1903 or later".

Update outdated FAQ

---

README.md

Completing #2971 by changing the word "avaiable" to "available".
#2971
Changing the word "avaiable" to "available" at README.md

docs: Fix Typo in README.md

---

doc/user-docs/index.md

* Proposes using the search function to locate the app.
* Restructures as a procedure.
* Adds misc edits.

Edits doc section: Starting Windows Terminal

---

doc/contributing.md

I think it's a good idea mentioning how to report vulnerabilities in contributing.md, by pointing them to SECURITY.md. This is useful in case people only read contributing.md but not security.md, and incorrectly believe that your team prefers discussing security issues on GitHub.

[contributing.md] add how to report security bugs

---

SECURITY.md

Fixed a small issue for #hacktoberfest :)

doc: fix a small issue for #hacktoberfest

---

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp

There was a comment on #3027 that went somewhat like "why are we sure we can remove this?"
We shouldn't have removed it.

Make sure we resize the region even when the drag bar didn't change

---

src/interactivity/win32/Clipboard.cpp

conhost has been leaving the clipboard open for all HTML copies because
StringCchCopyA needs an extra byte for the null terminator and we
haven't been giving it one. We should also make sure that we always
close the clipboard (always).
Went mad on the clipboard.

html: make sure we allocate enough space for the \0, always close

---

src/cascadia/TerminalControl/UiaTextRange.cpp
src/cascadia/TerminalControl/UiaTextRange.hpp
src/cascadia/WindowsTerminal/WindowUiaProvider.cpp
src/cascadia/WindowsTerminal/WindowUiaProvider.hpp
src/cascadia/WindowsTerminal/main.cpp
src/interactivity/win32/uiaTextRange.cpp
src/interactivity/win32/uiaTextRange.hpp
src/interactivity/win32/ut_interactivity_win32/UiaTextRangeTests.cpp
src/interactivity/win32/windowUiaProvider.cpp
src/interactivity/win32/windowUiaProvider.hpp
src/types/ScreenInfoUiaProviderBase.cpp
src/types/ScreenInfoUiaProviderBase.h
src/types/UiaTextRangeBase.cpp
src/types/UiaTextRangeBase.hpp
src/types/WindowUiaProviderBase.cpp
src/types/WindowUiaProviderBase.hpp

Fixes #3209.
References #3051.
I stole a bunch of Carlos's changes from #3051. I'll help him merge them back in later.

Switch all of the UIA providers to WRL::RuntimeClass

---

doc/user-docs/index.md

Added <kbd> notations for keyboard keys.

---

src/cascadia/WpfTerminalControl/TerminalControl.xaml

Fix scrolling in the WPF control so that clicking the arrow buttons scrolls one line at a time.
Patched a test app and verified that scrolling behaved as expected.

wpf: Change scrollbar buttons to one line per click

---

tools/bcz.cmd

We have no idea why this ever worked in the first place.
We discussed this in triage

Fix a problem with `bcz.cmd`

---

src/cascadia/TerminalConnection/ConptyConnection.cpp

Expand environment variables in ConptyConnection

---

src/common.build.post.props

This makes things nicer.
It turns out that we don't need to link 300 things actually! Umbrella libs are the best.
build and dumpbin

Tree-shake the library link list

---

doc/cascadia/profiles.schema.json

adding comma to line 212

---

src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/packages.config
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/cascadia/WindowsTerminal/packages.config
src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj

Updates MUX to the latest pre-release version. This prerelease has a fix for a certain `E_LAYOUTCYCLE` bug in the TabView that was causing an untold number of crashes for us.
Thanks again @teaP!

Update to the latest MUX prerelease

---

src/cascadia/TerminalCore/Terminal.cpp

I moved the code snip down to trigger properly.

Fix suppressApplicationTitle PR #3837

---

src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj.filters

AppLib project grew up and it got hard to navigate among its files so I organized it into VS's folders.

Organize AppLib into folders in Visual Studio

---

src/renderer/dx/DxRenderer.cpp

I believe this fixes #3861 but I honestly don't know how to test that part of the code. Just from reading the issue description that @dhowett-msft provided.
Really none, I just built it and :fingers_crossed:

Initialize the selectionBackground to a `D2D1_COLOR_F`

---

README.md

Just adding my company twitter to the readme. 🐦

Adding my Socials Media

---

src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
src/cascadia/TerminalApp/lib/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/packages.config
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/cascadia/WindowsTerminal/packages.config
src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj

This latest MUX prerelease fixes the issue where the tab row wouldn't expand to fill the width of the window after shrinking the window size.
Thanks again @teaP for help fixing this
Launched the terminal, played with it a bit

Update to the latest MUX prerelease (2.3.191217003)

---

doc/user-docs/UsingJsonSettings.md

I felt inspired by #4053 to add some documentation regarding unbinding keys, since it didn't seem like we had any previously :/

Add a note regarding unbinding keys

---

src/terminal/adapter/adaptDispatchGraphics.cpp

I didn't found much to do in `InputStateMachineEngine.cpp`, though.

Replace bitwise flipping with WI_ flag helpers

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalPage.cpp

Added a link to our privacy policy inside the About dialog box
Links to https://aka.ms/terminal-privacy-policy

Add privacy policy to about dialog

---

doc/specs/#607 - Commandline Arguments for the Windows Terminal.md

spec/doc: replace split pane -h, -V with -H, -V

---

build/.nuget/packages.config
build/config/NuGet.config
build/pipelines/templates/build-console-audit-job.yml
build/pipelines/templates/build-console-steps.yml
src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
src/common.build.tests.props
src/host/ft_uia/Host.Tests.UIA.csproj
src/host/ft_uia/packages.config
src/terminal/parser/ut_parser/packages.config
tools/OpenConsole.psm1
tools/razzle.cmd

This removes some longstanding debt we've been carrying around.

Update TAEF to 10.51 and remove the private dep on Taef.TestAdapter

---

doc/user-docs/index.md

pwsh parent process has been changed, confirmations in the replies to the referenced tweet.
Updating documentation to reflect changes in pwsh parent process.

Update index.md - Tips and Tricks

---

doc/user-docs/UsingJsonSettings.md

doc: correct spelling error in UsingJsonSettings.md

---

src/cascadia/WindowsTerminalUniversal/Resources/Resources.devicefamily-core.resw
src/cascadia/WindowsTerminalUniversal/Resources/Resources.language-en.resw
src/cascadia/WindowsTerminalUniversal/Resources/Resources.resw
src/cascadia/WindowsTerminalUniversal/WindowsTerminalUniversal.vcxproj
src/cascadia/WindowsTerminalUniversal/WindowsTerminalUniversal.vcxproj.filters

This also splits our resources (for WTU) into English vs. Neutral
Fixes #4491.

Rename WTU to zTerminal using the CORE device family resource qual

---

doc/cascadia/SettingsSchema.md
doc/user-docs/index.md

I have updated the documentation so that people are not confused about acrylic transparency any more.
does not apply

doc: add useAcrylic unfocused limitation to docs

---

src/cascadia/TerminalControl/UiaTextRange.cpp

Forgot to include the scaling factor. Also went ahead and used chromium math for this portion.
Tested on 200% display and 100% display. Rects are aligned on both.

Fix UiaTextRange Misaligned Bounding Rects

---

src/types/ScreenInfoUiaProviderBase.cpp

`ScreenInfoUiaProvider::GetVisibleRanges()` used to return one range per line of visible text. The documentation for this function says that we should return one per contiguous span of text. Since all of the text in the TermControl will always be contiguous (at least by our standards), we should only ever be returning one range.
Verified using Accessibility Insights.

Make ScreenInfoUiaProvider::GetVisibleRanges() Return Only One Range

---

src/cascadia/TerminalControl/TermControl.cpp

Don't say "drop files" for things that aren't files

---

src/renderer/dx/CustomTextLayout.cpp

Reverts microsoft/terminal#4081
Reopens #696.

Revert "Fix column count issues with certain ligature."

---

src/cascadia/TerminalApp/userDefaults.json

This will improve user education by showing them where "default" settings go.
Requires #4555.

Update stock user defaults to the list+defaults style

---

src/cascadia/TerminalApp/defaults.json

This was discussed.
Fixes #4349

Turn on snapToGridOnResize by default

---

doc/user-docs/UsingCommandlineArguments.md
doc/user-docs/UsingJsonSettings.md
doc/user-docs/index.md

VSCode's markdown linter suggested a pile of fixes. 
Viewed the updated markdown to ensure nothing broken,

add linting fixes for markdown

---

doc/building.md

I missed this part in readme.md, and got a bit confused by the instructions in building.md, so let's update them from the readme.

Update building instructions

---

src/cascadia/TerminalControl/TSFInputControl.cpp
src/cascadia/TerminalControl/TSFInputControl.h
src/cascadia/TerminalControl/TSFInputControl.xaml
src/cascadia/TerminalControl/TerminalControl.vcxproj

This pull request is like #4729 but for TSFInputControl.

Convert TSFInputControl to a .xaml file

---

CODE_OF_CONDUCT.md

Adjusting the CoC to match the CoC template from Microsoft OSS team.

doc: update CODE_OF_CONDUCT.md

---

src/cascadia/TerminalApp/AppKeyBindingsSerialization.cpp

Avoid bailing on arg-free bindings

---

doc/terminal-v1-roadmap.md

Our v1 release date was outdated, so I fixed it.

doc: update roadmap with proper v1 release date

---

doc/building.md

This PR adds documentation regarding the updating nuget packages and using .nupkg files.
This adds documentation regarding updating nuget versions and using .nupkg files instead of downloading them from Nuget repository.

doc: add docs for updating nuget packages and using .nupkgs

---

src/cascadia/TerminalCore/Terminal.cpp

Seriously just read the code on this one, it's so incredibly obvious what I did wrong
Regressed with #4741 

Make sure to InvalidateAll on a resize

---

doc/user-docs/ThirdPartyToolProfiles.md

found the commandline arguments on stackoverflow
added to new profile
started Terminal
opened MSYS2 tab

doc: add MSYS2 profile to ThirdPartyToolProfiles.md

---

src/cascadia/WindowsTerminal/NonClientIslandWindow.cpp
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/cascadia/WindowsTerminal/packages.config

One of our great contributors already hooked up all the logic for this,
we just needed a theme library that could handle the request.

Make the window border actually follow the user's theme

---

doc/user-docs/ThirdPartyToolProfiles.md

Added Developer Command Prompt for VS profile in ThirdPartyToolProfiles.
Well it's not really "third party". Anyway, it works on my laptop. The only missing part is a icon.

Doc: add Developer Command Prompt for VS profile

---

src/cascadia/WpfTerminalControl/NativeMethods.cs
src/cascadia/WpfTerminalControl/TerminalContainer.cs
src/cascadia/WpfTerminalControl/TerminalControl.xaml.cs
src/host/ft_uia/AccessibilityTests.cs
src/host/ft_uia/Common/ShortcutHelper.cs
src/host/ft_uia/Elements/TabBase.cs
src/host/ft_uia/Elements/Tabs.cs
src/host/ft_uia/Elements/ViewportArea.cs
src/host/ft_uia/MouseWheelTests.cs
src/host/ft_uia/VirtualTerminalTests.cs
src/host/ft_uia/WinEventTests.cs
src/tools/vtapp/Program.cs

Every single time a PR is run, there are a bunch of warnings about whitespace in the .cs files, so I ran the code format on those files, without changing their contents, so it won't be flagged anymore.
Ran the code-format utility on the .cs files

Remove unneeded whitespace to remove compiler warnings about whitespace

---

doc/cascadia/profiles.schema.json

Add `null`, `unbound` to schema for keybindings

Add `null`, `unbound` to schema for keybindings

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/TerminalPage.xaml

Replaced the aka.ms links in the about menu and the feedback button to fwlinks.

Change aka.ms links to fwlinks

---

.github/actions/spell-check/whitelist/web.txt

ci/spelling: add ecma to the allowlist

---

README.md

Our team member list was out of date, so I updated it.

doc: update list of team members in README

---

doc/cascadia/SettingsSchema.md
doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/GlobalAppSettings.cpp
src/cascadia/TerminalApp/GlobalAppSettings.h
src/cascadia/TerminalApp/TerminalPage.cpp

This reverts commit c55d9cd62daf2a7bef5903e489e77de83e79e17b. It was merged with its corresponding specification unmerged.

Revert "Add 'copyFormatting' global setting (#5263)"

---

doc/cascadia/profiles.schema.json
src/cascadia/TerminalApp/defaults-universal.json
src/cascadia/TerminalApp/defaults.json
src/cascadia/TerminalApp/userDefaults.json

Added `copyFormatting` to defaults json files and userDefaults.

Add copyFormatting setting to all settings json files

---

src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp

This PR adds a test for #5428. Mysteriously, after #5398 merged, 5428 went away. However, I already wrote this test for it, so we might as well add it to our collection.

Add a test to cover #5428

---

doc/cascadia/SettingsSchema.md
doc/cascadia/profiles.schema.json

doc: add `disabledProfileSources` to the schema

---

doc/user-docs/UsingJsonSettings.md

Simple fix to update the example documentation with the recent changes to 0.11.

Updating to change from requestedTheme to theme

---

src/cascadia/CascadiaPackage/Resources/Resources.resw

This is part of the v1 polish.

Remove the (Preview) tag from the primary App Name

---

doc/cascadia/profiles.schema.json

The `decreaseFontSize` key binding command was replaced with `adjustFontSize`, so it should be removed from the JSON schema.

Remove `decreaseFontSize` from schema

---

doc/user-docs/UsingCommandlineArguments.md

doc: fix typo in UsingCommandlineArguments.md

---

doc/user-docs/UsingJsonSettings.md

Add a note that the user needs to hide dynamic profiles, not just delete them.
* related to discussion in #3231

Add a note that the user needs to hide dynamic profiles

---

.github/actions/spell-check/patterns/patterns.txt
.github/actions/spell-check/whitelist/web.txt
src/cascadia/TerminalApp/ColorHelper.cpp
src/cascadia/TerminalApp/Tab.cpp

I never got to fixing these in the original #3789 PR, but I messed up that branch way too many times already that I figured I'd just do it in post.

Fix a few minor typos from #3789

---

src/cascadia/CascadiaPackage/Resources/Resources.resw

Updated user docs.
* [x ] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [ N/A] Tests added/passed
* [ N/A] Requires documentation to be updated
* [ N/A] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx
Updated user docs to add `wt -d .` command to comment on Open Terminal Here reference

Add File Explorer tip to User Docs

---

doc/user-docs/index.md

Updated info on commandline options

Update docs to mention commandline args

---

src/cascadia/CascadiaPackage/Resources/en-US/Resources.resw

Add `AppDescriptionPre` to the localized resw file for the Preview build.
#5774 - add the appxmanifest for preview

Add an AppDescription for the Preview package

---

doc/user-docs/index.md

It fixes a broken markdown link in the doc/user-docs/index.md 
- none

doc: fix broken link within documentation

---

doc/user-docs/index.md

(and thanks to @bitcrazed for hinting about it!)
https://twitter.com/shanselman/status/1260467567333908481
Adding a tip about launching (toggling) the Terminal with a global shortcut.

doc: add a tip about launching WT with a Win+Number shortcut

---

doc/user-docs/index.md

Fixed the wrong issue number shown in the user-docs/index.md.

doc: fix a typo in user-docs/index.md

---

README.md

We have some new goodies from Microsoft Build 2020 that need to be in the README. 😊

Update README with 1.0 info

---

.github/actions/spell-check/whitelist/whitelist.txt
README.md

Added install instructions for winget
resolves #6159

Add `winget` instructions to README.md

---

src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest

Reintroduce accidentally removed uap7 namespace

---

README.md
doc/terminal-v2-roadmap.md

Upload the roadmap for Windows Terminal 2.0 and link to it on the README.

Upload Windows Terminal 2.0 roadmap

---

build/pipelines/ci.yml
src/til/ut_til/BaseTests.cpp

Fix the x86 build and re-enable x86 CI

---

doc/terminal-v2-roadmap.md

Tiny copy fix in the roadmap document.

doc: copyedit the roadmap a little bit

---

doc/terminal-v2-roadmap.md

Add a link to the 1.1 blog post in the milestone table in the 2.0 roadmap.

Add 1.1 blog post to 2.0 roadmap

---

.github/PULL_REQUEST_TEMPLATE.md

If people write features that require a docs update, they should file a PR on our docs site as well. 👍

Update PR template with link to docs

---

.github/PULL_REQUEST_TEMPLATE.md

We need to do a better job of updating the schema as we go. I'm hoping this might help a bit.

Add schema check to PR template

---

src/cascadia/TerminalApp/CascadiaSettings.cpp
src/cascadia/TerminalApp/CascadiaSettings.h
src/cascadia/TerminalApp/Profile.cpp
src/cascadia/TerminalApp/Profile.h
src/cascadia/TerminalApp/TerminalPage.cpp

Let's try and figure out just how many people are actually using Solarized. I emailed @DHowett about this a week ago, but otherwise we don't really have any other tasks for this.

Add some trace logging concerning which schemes are in use

---

src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
src/common.build.tests.props
src/host/ft_uia/Host.Tests.UIA.csproj
src/host/ft_uia/app.config
src/host/ft_uia/packages.config
src/terminal/parser/ut_parser/Parser.UnitTests.vcxproj
src/terminal/parser/ut_parser/Parser.UnitTests.vcxproj.filters
src/terminal/parser/ut_parser/packages.config
tools/OpenConsole.psm1
tools/razzle.cmd

Updates TAEF to 10.57.200731005-develop

Update TAEF to 10.57.200731005-develop

---

doc/Niksa.md

I've typed this up way too many times now. I'm sticking this comment in Niksa.md, and if it's ever an insufficient explanation of the differences, we can elaborate.

Add a "shell vs terminal" section to Niksa.md

---

README.md

doc: Add Pankaj to our README

---

doc/cascadia/profiles.schema.json

Adds missing elements to JSON schema.
Only updates the JSON schema with missing elements

Add startOnUserLogin & fullscreen launchMode to schema

---

doc/cascadia/profiles.schema.json

The descriptions were flipped, so I unflipped them.

schema: swap `closeTabsAfter` and `closeOtherTabs`

---

src/cascadia/TerminalApp/userDefaults.json

Since we're unifying around actions, we should unify here too.

Update userDefaults from "keybindings" to "actions"

---

src/buffer/out/TextAttribute.hpp

Fix the "visual representation" optimization for hyperlinks

---

doc/terminal-v2-roadmap.md

Updated the roadmap with new dates, release info, and feature links.

doc: Update roadmap with latest info

---

SUPPORT.md

Add SUPPORT.md to repository per guidance.

doc: add SUPPORT.md

---

CONTRIBUTING.md
doc/TAEF.md

This PR updates the doc in the repo to address how to use TAEF as part of the development workflow.
Inspired by the original issue of @german-one and his comments in #1962, I try to add more contents to the documentation that hopefully will clarify the usage of TAEF. Personally I've stumbled upon several issues when it comes to TAEF when I first started working on PRs. I think this will help the community to learn TAEF and make contributions even more easily.
Not really needed.

doc: address how to use TAEF

---

README.md

Just a simple update on the Notice emoji so that it catch people attention
Update on the emoji so that it catch people attention as I see many queries about could not run on Windows Server 2016
Either Red Circle 🔴 or Exclamation Mark ❗

doc: Update Notice emoji

---

.github/workflows/linter.yml
README.md

Updates the GH Action and makes a small update to the README to test changes.
A missing install step for Windows Terminal using Scoop has been added. The versioning of Super-Linter was also switched to v3 to allow auto-updates within the v3 series. This can be version-pinned again if a breaking change comes later. The current updates fix some bugs and bump the linters utilized. 
Validation will be shown in the build steps.

Update GH Action Super-Linter and README

---

src/cascadia/TerminalApp/Resources/en-US/Resources.resw
src/cascadia/TerminalApp/SettingsTab.cpp
src/cascadia/TerminalApp/SettingsTab.h

Fixes the last bit of missing localization for the settings UI

Add localization to settings tab

---

src/cascadia/TerminalSettingsEditor/MainPage.xaml

Updated icons for:
- Startup
- Appearance
- Color schemes (moved the palette icon from Appearance to here)
- Profiles

Update settings UI navigation icons

---

src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp

The copy wasn't checking for whether there were any args to copy - causing memory access violations sometimes
Memory access violations stopped

Quick fix for ActionAndArgs::Copy()

---

src/cascadia/TerminalApp/CommandPalette.cpp

Changed wrong comments from the last PR and also added new comments.

Updating comments in CommandPalette.cpp

---

src/cascadia/ShellExtension/packages.config
src/cascadia/TerminalApp/packages.config
src/cascadia/TerminalAzBridge/packages.config
src/cascadia/TerminalConnection/packages.config
src/cascadia/TerminalControl/packages.config
src/cascadia/TerminalCore/packages.config
src/cascadia/TerminalSettingsModel/packages.config
src/cascadia/WinRTUtils/packages.config
src/cascadia/WindowsTerminal/packages.config
src/cascadia/WindowsTerminalUniversal/WindowsTerminalUniversal.vcxproj
src/cascadia/WindowsTerminalUniversal/packages.config
src/cppwinrt.build.post.props
src/cppwinrt.build.pre.props
src/tools/U8U16Test/U8U16Test.vcxproj
src/tools/U8U16Test/packages.config

We cannot use the most recent version of C++/WinRT due to
microsoft/cppwinrt#780 (or similar).

Update C++/WinRT to 2.0.201017.1

---

src/cascadia/TerminalSettingsEditor/MainPage.xaml

Add border to footer to help differentiate content from footer.

Add border to footer in SUI

---

src/cascadia/TerminalSettingsEditor/MainPage.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Create a header for Profiles inside the nav, where dynamic profiles can populate.

Update SUI nav for profiles

---

.github/workflows/linter.yml

Sorry. It's just too noisy, and we haven't acted on any of its feedback.

Gank the linter

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

"Reset" is confusing because it could mean resetting to defaults.

Change reset button to discard changes

---

.github/ISSUE_TEMPLATE/config.yml

Expects addition/removal requests from microsoft/terminal maintainers
Configuration for GitHub Issues
~Tests added/passed~
~Documentation updated. If checked, please file a pull request on [our docs repo](https://github.com/MicrosoftDocs/terminal) and link it here: #xxx~
~Schema updated.~
The current commit does the following:
- Prevents opening blank issues (Nothing prevents from deleting the contents of an chosen issue template)
- Links to MSRC (for security vulnerabilities)
- Links to create an issue page in [MicrosoftDocs/terminal](https://github.com/MicrosoftDocs/terminal)
- Links to create an issue page in [MicrosoftDocs/console-docs](https://github.com/MicrosoftDocs/console-docs/)

Configure the options available in the issue list

---

doc/terminal-v2-roadmap.md

Added 1.6 milestone and 1.5 release blog post to the roadmap

doc: Update roadmap with 1.5 release info

---

doc/AddASetting.md

Just changed the initials of few statements to Capital Letters.

doc: Make minor grammatical fixes to AddASetting.md

---

doc/cascadia/profiles.schema.json

Addressing the following discussion: https://github.com/microsoft/terminal/pull/3575#issuecomment-735410139

schema: make rowsToScroll deprecation message mention bindings

---

doc/terminal-v2-roadmap.md

I've opened a bunch of specs for features on the roadmap. It's probably best if I actually updated the roadmap to reflect them.

Add a bunch of my specs to the roadmap

---

doc/cascadia/profiles.schema.json

* The index field should be of type `"null"` and not `null`.
* The default value should be `null` and not `""`

Make schema compliant by fixing CloseTab* index definitions

---

src/cascadia/TerminalApp/CommandPalette.cpp

Cleanup extraneous local leftover from #8194

Cleanup extraneous local leftover from #8194

---

src/cascadia/TerminalSettingsEditor/CommonResources.xaml
src/cascadia/TerminalSettingsEditor/Profiles.xaml

Fixed some of the margin alignments and increased the standard box width.

Fix margins and box width in SUI

---

.github/actions/spell-check/dictionary/README.md

Saw a phrase that has been deprecated and swapped it with a more modern one :)

Changing a phrase to "expected"

---

src/cascadia/TerminalControl/TermControl.cpp

Fix right-click paste to clear current selection

---

src/cascadia/TerminalSettingsEditor/Profiles.xaml

Enforce a min/max on the Profile page's FontSize input

---

src/cascadia/TerminalSettingsEditor/GlobalAppearance.xaml
src/cascadia/TerminalSettingsEditor/Launch.xaml

Polish for global settings in SUI
- Launch size can no longer be negative
- Reorder appearance options

Polish Global settings a bit

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Show the cursor shape next to the text for it
References #8764

Show cursor shape in SUI

---

src/cascadia/TerminalApp/TabBase.cpp
src/cascadia/TerminalApp/TabBase.h
src/cascadia/TerminalApp/TerminalTab.cpp
src/cascadia/TerminalApp/TerminalTab.h

Teach tab tool tip to show profile name

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalApp/TerminalPage.h

A temporary solution for #8882

Teach SUI tab to respect close / prev / next tab bindings

---

src/cascadia/TerminalSettingsEditor/Converters.idl
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
src/cascadia/TerminalSettingsEditor/PaddingConverter.cpp
src/cascadia/TerminalSettingsEditor/PaddingConverter.h
src/cascadia/TerminalSettingsEditor/Profiles.cpp
src/cascadia/TerminalSettingsEditor/Profiles.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Replaces the textbox used for the padding setting with a slider
References #8764

Add a slider for the padding setting in the SUI

---

doc/cascadia/profiles.schema.json

Simple JSON schema fix for 1.6 :)
`scrollToTop` and `scrollToBottom` are from #8459

Add `scrollToTop` and `scrollToBottom` actions to JSON schema

---

.github/actions/spell-check/excludes.txt

@jsoref said to do this, so I'm doing it to fix the bot.

Fix the spellcheck bot

---

doc/cascadia/AddASetting.md

Since we're following the UWP design guidance, we should recommend the community use it as well when adding new settings to the settings UI.

Add UWP docs link to AddASetting.md

---

src/cascadia/TerminalApp/TerminalPage.cpp

Fix cursor restore to happen on the tab row

---

src/cascadia/TerminalApp/TabBase.cpp
src/cascadia/TerminalApp/TerminalTab.cpp

There's a platform issue that causes it to crash.
Fixes #8944

[1.5 ONLY] Remove the close submenu

---

src/server/lib/server.vcxproj

Fix the Host Proxy DLL reference in ServerLib

---

src/cascadia/TerminalApp/CommandPalette.cpp

Re-enable navigation in ATS

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

We've received feedback from the localization team that the strings need some comments to provide more context.
Closes [MSFT-31929817](https://microsoft.visualstudio.com/OS/_workitems/edit/31929817)
#9328 - Chinese translation issues
#9238 - French translation issues

Add localization comments to settings UI

---

src/cascadia/TerminalApp/TerminalSettings.h

Fix pixel shaders not loading

---

src/cascadia/TerminalApp/TerminalTab.cpp

Fix overflow in scroll-to-bottom

---

doc/terminal-v2-roadmap.md

We're switching to a 6-week release cadence and are also shifting the 2.0 release to this winter.

Update roadmap to reflect new release cadence

---

src/StaticAnalysis.ruleset
src/inc/conattrs.hpp
src/inc/unicode.hpp
src/terminal/adapter/adaptDispatchGraphics.cpp
src/terminal/input/mouseInput.cpp
src/terminal/input/terminalInput.cpp
src/terminal/parser/InputStateMachineEngine.hpp

Supports #2941
Previous PRs: #3362 #3416

Prefer constexpr over const across the codebase

---

samples/PixelShaders/Outlines.hlsl

I accidentally the whole thing
* Heavily inspired by the original rasterbars shader.
I know it's not FHL anymore, but I couldn't help myself.
looked at it

Add a sample outline shader

---

src/cascadia/ShellExtension/WindowsTerminalShellExt.vcxproj
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/common.build.pre.props

Yes, this is why default terminal didn't work in Preview.

Move Branding into common props

---

src/cascadia/TerminalApp/TabManagement.cpp

This fixes right-click > "Close" on TerminalTab
Fixes bug bash issue.

Fix bad merge in c585a93fc (CloseRequested) that broke closing

---

src/cascadia/TerminalApp/AppActionHandlers.cpp

Handle switch to tab binding even if tab doesn't exist

---

src/cascadia/TerminalSettingsEditor/Actions.xaml

Remove the icon grid column from the Actions page

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalControl/TermControl.h
src/cascadia/TerminalSettingsModel/Profile.cpp

Fix for profiles.defaults.colorScheme not working 
Fix for background image only showing up after a settings reload
Closes #9761

Fix for some profiles.defaults settings not working

---

src/cascadia/TerminalControl/TermControl.cpp

Fixes MSFT-32485023
I ran into this crash when I _just opened a new tab._

Only update render appearance settings if there's a renderer

---

src/cascadia/TerminalApp/AppActionHandlers.cpp

Fix rename window handler to mark action as handled

---

src/cascadia/TerminalApp/TabBase.cpp
src/cascadia/TerminalControl/TermControl.xaml

Fix tab and hyperlink tooltips to wrap long text

---

README.md

Add link to "aka.ms/terminal-docs" text in README, thus making more easier to arrive the docs.

Add URL link to docs text in README.md

---

src/host/exe/exemain.cpp

Fixes code health failure since 66b9b9d6f1b600d1b25aa2339fa368113c45952b

Fix code health failure

---

CONTRIBUTING.md

Added links to folders and headers mentioned.
N/A
Added links inside `CONTRIBUTING.md` leading users to headers and sub folders mentioned.
Tested verifying links working.

doc: Added links to folders and headers mentioned

---

build/scripts/Invoke-FormattingCheck.ps1
tools/OpenConsole.psm1

openConsole.psm1: fix unapproved verb warning

---

.github/actions/spelling/expect/expect.txt
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/cascadia/WindowsTerminal/packages.config
src/common.build.pre.props

See MSFT-33187224 for more information.
This may impact debuggability; I have no idea how to tell.

Emit fixup debug info for internal tooling

---

doc/specs/#1043 - Set the initial position of the Terminal/spec.md
doc/specs/#605 - Search/spec.md

Docs have been updated (for bug fixes/features)
docs update => proper capitalisation would be better. 👍: Github
Signed-off-by: Ayushman Singh Chauhan <ascb508@gmail.com>

DOC: Fix camelCase (or capitalization)

---

doc/terminal-v2-roadmap.md

Update the 2.0 roadmap to have the 1.9 preview release blogpost link.

doc/roadmap: add 1.9 Preview Release Blogpost Link

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

This commit adds a "(requires relaunch)" suffix to the header of the language picker control.

Advice users to relaunch after changing the language

---

src/cascadia/TerminalCore/TerminalDispatch.cpp
src/terminal/adapter/adaptDispatch.cpp

RIS resets mouse mode and encoding

Update RIS to reset mouse mode and encoding

---

.github/actions/spelling/allow/allow.txt
.github/actions/spelling/allow/apis.txt
.github/actions/spelling/allow/fonts.txt
.github/actions/spelling/allow/microsoft.txt
.github/actions/spelling/expect/expect.txt
.github/workflows/spelling2.yml

Updates check-spelling to 0.0.19
https://github.com/check-spelling/check-spelling/security/advisories/GHSA-g86g-chm8-7r2p
I'm pinning `actions/checkout` to @v2 instead of micromanaging the version. We have reasonable faith that GitHub will do a good job of maintaining their version branch.
I'll probably introduce a version branch for check-spelling in the near future as well.
The job name change is for future bits -- I originally copied the name from a template and didn't understand its significance -- eventually it'll actually be used by the workflow. And if one uses `act`, having distinct / well named jobs is actually useful.
https://github.com/jsoref/terminal/actions/runs/1025581435 is a previous run where I still had some unrecognized words. …

Upgrade check-spelling to v0.0.19

---

src/buffer/out/textBuffer.cpp
src/cascadia/TerminalApp/Pane.cpp
src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/UnitTests_Remoting/RemotingTests.cpp
src/cascadia/UnitTests_TerminalCore/ConptyRoundtripTests.cpp
src/cascadia/WindowsTerminal/IslandWindow.cpp
src/host/stream.cpp
src/interactivity/base/EventSynthesis.cpp
src/interactivity/win32/windowproc.cpp
src/renderer/vt/state.cpp
src/til/ut_til/MathTests.cpp
src/til/ut_til/PointTests.cpp

Visual Studio 2022 Preview recently released the v143 toolchain.
C4189 is now flagging several unused variables, which breaks our build.
* CascadiaPackage builds ✔️
* All tests build ✔️

Fix building with v143 toolchain

---

build/pipelines/release.yml
build/pipelines/templates/build-console-audit-job.yml
build/pipelines/templates/build-console-ci.yml
build/pipelines/templates/build-console-pgo.yml

Move to 1ES engineering pools

---

src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

Updates the Settings UI tooltips to use "enabled" and "disabled" instead of "checked" and "unchecked" respectively.
Closes #10814

Update SUI tooltips from 'checked' to 'enabled'

---

scratch/ScratchIslandApp/Package/Package.wapproj
scratch/ScratchIslandApp/SampleApp/SampleAppLib.vcxproj
scratch/ScratchIslandApp/SampleApp/dll/SampleApp.vcxproj
scratch/ScratchIslandApp/SampleApp/packages.config
scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj
scratch/ScratchIslandApp/WindowExe/packages.config
src/cascadia/CascadiaPackage/CascadiaPackage.wapproj
src/cascadia/LocalTests_SettingsModel/SettingsModel.LocalTests.vcxproj
src/cascadia/LocalTests_TerminalApp/TerminalApp.LocalTests.vcxproj
src/cascadia/LocalTests_TerminalApp/TestHostApp/TestHostApp.vcxproj
src/cascadia/TerminalApp/App.xaml
src/cascadia/TerminalApp/TerminalAppLib.vcxproj
src/cascadia/TerminalApp/dll/TerminalApp.vcxproj
src/cascadia/TerminalApp/packages.config
src/cascadia/TerminalSettingsEditor/Microsoft.Terminal.Settings.Editor.vcxproj
src/cascadia/TerminalSettingsEditor/packages.config
src/cascadia/TerminalSettingsModel/Microsoft.Terminal.Settings.ModelLib.vcxproj
src/cascadia/TerminalSettingsModel/dll/Microsoft.Terminal.Settings.Model.vcxproj
src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj
src/cascadia/WindowsTerminal/packages.config
src/cascadia/WindowsTerminalUniversal/WindowsTerminalUniversal.vcxproj
src/cascadia/ut_app/TerminalApp.UnitTests.vcxproj

The upgrade to 2.6 revealed #11003 and Microsoft/microsoft-ui-xaml#5435, and is impeding
progress on PGO.
Reverts microsoft/terminal#10996

Revert "Upgrade to Microsoft.UI.Xaml 2.6.2 (or equivalent)"

---

doc/terminal-v2-roadmap.md

Update terminal-v2-roadmap links

Update terminal-v2-roadmap.md links

---

src/tools/vttests/burrito.py

Remove those imports as they are unnecessary, _template.py_ contains these too but I guess it's fine since it's a template after all

Remove `time` and `sys`

---

src/cascadia/TerminalApp/CommandPalette.cpp

Teach Command Palette to filter out duplicate command lines

---

src/common.build.pre.props

Adjust tools version for folks running on 2022

Adjust tools version for folks running on 2022

---

src/cascadia/TerminalControl/ControlCore.cpp

Clears selection render on paste
Added ```_renderer->TriggerSelection(); ``` similarly to the copy action few lines up in ```CopySelectionToClipboard``` function
Manually tested

Fix selection render on paste

---

tools/ReleaseEngineering/New-TerminalStackedChangelog.ps1

Set min version for Release Engineering script to prevent weird errors on inbox Powershell

Set min version for Release Engineering script to prevent weird errors on inbox Powershell

---

src/cascadia/TerminalApp/TerminalPage.xaml

Just read the code, it's immediately obvious what I messed up
Closes #11645
@DHowett turns out I was wrong, I could get this one done before 5 😜

Fix the cmdpal moving the infobar down

---

doc/cascadia/profiles.schema.json

Closes #11642
See also https://github.com/MicrosoftDocs/terminal/pull/435

Add trimPaste to the schema, too

---

tools/razzle.cmd

If msbuild is already on the path, we don't need to look for it.
Also,
> I know what I did. I installed VS 2022, which is a prerelease VS install. `tools\razzle` prefers the stable builds. I think I'm gonna remove that.

Prefer Preview VS builds always; use any existing msbuild if it's on the path

---

.github/actions/spelling/patterns/patterns.txt
CONTRIBUTING.md

That's what the original purpose of #865 was, but I went ahead and added some additiona text, now that we've got more of a flow for github figured out.
Closes #865

Add some details about working on assigned issues

---

README.md

Updates the readme to reference the updated Windows 11 SDK requirement.

Update readme to reference Windows 11 SDK requirement

---

build/packages.config
src/cascadia/Remoting/packages.config
src/cascadia/TerminalApp/packages.config
src/cascadia/TerminalConnection/packages.config
src/cascadia/TerminalControl/packages.config
src/cascadia/TerminalSettingsEditor/packages.config
src/cascadia/TerminalSettingsModel/packages.config
src/cascadia/WindowsTerminal/packages.config
src/common.build.post.props
src/common.build.pre.props
src/host/exe/packages.config

Only look for PGO package if build mode targeted; add packages.config dependency to ease restoration

Only look for PGO package if build mode targeted; add packages.config dependency to ease restoration

---

doc/roadmap-2022.md
doc/terminal-v2-roadmap.md

To reflect changes to the repo for the new year.

Add an updated roadmap

---

build/packages.config
build/pipelines/templates/pgo-build-and-publish-nuget-job.yml

Pass additional parameters when making PGO package

Pass additional parameters when making PGO package

---

build/Helix/OutputTestResults.ps1
build/pipelines/templates/helix-runtests-job.yml

The 19H1 pool is being decommissioned.

Move to the 21H1 Helix pool

---

src/cascadia/TerminalSettingsModel/WslDistroGenerator.cpp

The update that enables this on 20H1+, [KB5007253], went out in November
2021.
[KB5007253]: https://support.microsoft.com/en-us/topic/november-22-2021-kb5007253-os-builds-19041-1387-19042-1387-19043-1387-and-19044-1387-preview-d1847be9-46c1-49fc-bf56-1d469fc1b3af

Set the default WSL starting directory to ~

---

src/cascadia/TerminalApp/AppLogic.cpp

From a mail thread. Hoping to sneak into 1.12.

Research how often folks disable the KB warning

---

README.md

As noticed in https://github.com/microsoft/terminal/pull/12129#issuecomment-1027975112. 
Missed in #12129.

Update readme to account for minversion bump

---

dep/Console/conapi.h
dep/Console/condrv.h
dep/Console/conmsgl1.h
dep/Console/conmsgl2.h
dep/Console/conmsgl3.h
dep/Console/ntcon.h
dep/Console/winconp.h
dep/NT/ntioapi_x.h
dep/Win32K/winuserp.h

Adding missed MIT license in a few files.

Adding missed MIT license in a few files

---

src/cascadia/WindowsTerminal/WindowsTerminal.manifest

By adding another entry to our `maxversiontested`s.
Screenshots in https://github.com/microsoft/terminal/issues/12452#issuecomment-1035356054

Enable Segoe Variable

---

src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw

"Summon" was translated as a synonym for "citation" in Spanish instead
of treating it as a RPG-related word. "Show/Hide" will hopefully
allow an improved automatic translation in the future.
Closes #10691

Replace Summon with Show/Hide for improved i18n

---

build/packages.config
common.openconsole.props
src/cascadia/TerminalApp/packages.config

Fix the restore failure caused by pulling in two copies of Xaml

---

.github/actions/spelling/excludes.txt
tools/ReleaseEngineering/ServicingPipeline.ps1

This script takes pull requests from a project board, cherry-picks them,
and updates the project board. It also yells at you if there are
conflicts to resolve, and generally tries to keep track of everything.
It is quite cool.

Add ServicingPipeline.ps1, a script I use to service Terminal

---

README.md

Remove maintainers from the list

---

common.openconsole.props
dep/nuget/packages.config
scratch/ScratchIslandApp/Package/Package.wapproj
scratch/ScratchIslandApp/SampleApp/SampleAppLib.vcxproj
scratch/ScratchIslandApp/SampleApp/dll/SampleApp.vcxproj
scratch/ScratchIslandApp/SampleApp/packages.config
scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj
scratch/ScratchIslandApp/WindowExe/packages.config
src/cascadia/TerminalApp/packages.config
src/cascadia/TerminalSettingsEditor/packages.config
src/cascadia/WindowsTerminal/packages.config

This fixes a number of issues including a NavigationView crash.

Upgrade WinUI2 to 2.7.1

---

README.md

Update README.md with prerequisite of Targeting Pack

---

src/renderer/vt/paint.cpp

This commit is one of the more difficult rewrites that were necessary as part
of #4015, but still simple enough that it can be done as a separate commit.
The search for the `lastNonSpace` was replaced with a simpler
`std::string_view::find_last_not_of`.
ConPTY appears to work ✅

Reduce integer type casts in VtEngine

---

build/pipelines/templates/build-console-compliance-job.yml

Fix an issue preventing the compliance pipeline from running

---

doc/building.md

The first line errors without the fix, the other is innocuous

Fix typos in dev build script

---

doc/cascadia/profiles.schema.json

Update schema with the settings/actions added in #12948

Update schema with scroll marks actions and settings

---

doc/cascadia/profiles.schema.json

As noted in https://github.com/microsoft/terminal/pull/11511#issuecomment-1173541384.
Missed in #13035
validated manually:

Fix the bellsound schema, for real

---

build/pipelines/daily-loc-submission.yml

Port our Daily Loc Submission build out of Azure DevOps to YAML

---

README.md

I updated the `note` prefix for blockquotes with GitHub built-in styles.
- https://github.com/community/community/discussions/16925
|**Before**|![](https://user-images.githubusercontent.com/8186898/181284671-5a4998e2-f8ac-446f-8e7c-a801d87b9eb9.png)|
|--:|--:|
|**After**|![](https://user-images.githubusercontent.com/8186898/181285059-6241634e-23a2-40b6-8ca2-b64d115bb946.png)|

Use GitHub built-in style for notes

---

.github/workflows/spelling2.yml

As discussed on teams. 
Refer to https://github.com/check-spelling/check-spelling/issues/23#issuecomment-1195826414

Don't comment on commits, cause no one's using that

---

src/common.nugetversions.targets

Fix the build when the solution dir has spaces

---

README.md

VC++ v14 Descktop Framework package is required and not installed automatically when installing package manually.

Add VC++ v14 Framework dependency note

---

src/renderer/atlas/AtlasEngine.cpp

Direct3D 10.0 and 10.1 only have optional support for shader model 4.
This commit fixes our assumption that it's always present by checking
`ComputeShaders_Plus_RawAndStructuredBuffers_Via_Shader_4_x` first.
Closes #13985
* Set feature level to 10.1 via `dxcpl`
* `CheckFeatureSupport` is called and doesn't throw ✅

AtlasEngine: Properly detect shader model 4 support

---

src/host/cmdline.cpp
src/til/ut_til/RunLengthEncodingTests.cpp
src/til/ut_til/SPSCTests.cpp

Use std::ranges to simplify code

---

src/buffer/out/ut_textbuffer/ReflowTests.cpp
src/cascadia/TerminalSettingsModel/JsonUtils.h
src/inc/til/rle.h
src/inc/til/some.h
src/inc/til/spsc.h

Use _v suffix instead of the ::value suffix

Simplify types

---

build/pipelines/templates/helix-runtests-job.yml
build/pipelines/templates/pgo-merge-pgd-job.yml
build/pipelines/templates/restore-nuget-steps.yml

Use Nuget 6.x

---

oss/interval_tree/IntervalTree.h
oss/interval_tree/MAINTAINER_README.md
oss/interval_tree/cgmanifest.json

This was the last update since 2021

Update IntervalTree.h dependency

---

scratch/ScratchIslandApp/Package/Package.wapproj
scratch/ScratchIslandApp/SampleApp/SampleAppLib.vcxproj
scratch/ScratchIslandApp/SampleApp/dll/SampleApp.vcxproj
scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj

This will let those projects build. I forgot to include them last time for some reason.
See PR #14123

Update scratch projects to XAML 2.7.3

---

src/host/cmdline.cpp
src/host/cmdline.h
src/host/scrolling.cpp

This pull request adds a couple `const` keywords, simplifies a bit of boolean logic,
adds the `static` keyword to `Commandline::IsEditLineEmpty`, and a couple more things.

Generally tidy the Commandline class

---

src/cascadia/CascadiaPackage/Package.appxmanifest

Fix the Release build ProxyStubClsids from #13570

---

README.md

on line 70 I removed the equals character from that powershell line command
>I tried to install this terminal but got the following error: 0x80072eff: unknown error.
So with my solution the command line works.

README: Fix the winget install instructions

---

src/cascadia/WindowsTerminal_UIATests/Common/NativeMethods.cs
src/cascadia/WindowsTerminal_UIATests/Elements/TerminalApp.cs
src/cascadia/WpfTerminalControl/TerminalContainer.cs
src/cascadia/WpfTerminalControl/TerminalControl.xaml.cs
src/cascadia/WpfTerminalControl/TerminalTheme.cs
src/host/ft_uia/Common/NativeMethods.cs
src/host/ft_uia/Elements/CmdApp.cs

No behavioral changes, just C# modernizations.

Fix C# warnings across the project, modernize slightly

---

doc/cascadia/profiles.schema.json

Update the schema to support null.

[schema] Update allowed types for startingDirectory

---

doc/Niksa.md
doc/specs/drafts/#997 Non-Terminal-Panes.md
scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj
src/cascadia/Remoting/WindowManager.cpp
src/cascadia/TerminalSettingsModel/ActionAndArgs.cpp
src/host/ft_host/CJK_DbcsTests.cpp
src/host/ft_uia/Common/ShortcutHelper.cs
src/renderer/atlas/AtlasEngine.h

Fix spelling errors in code comments and markdown
Closes #14670

Fix some additional typos

---

.github/PULL_REQUEST_TEMPLATE.md

Dunno how to feel about this. I want to guide people, but i don't want HTML comments in my `git log`

Make the PR template less unfriendly

---

src/propslib/RegistrySerialization.cpp

We had accidentally left clang-format turned off.

Reformat RegistrySerialization.cpp

---

.github/actions/spelling/expect/expect.txt
src/cascadia/TerminalControl/TermControl.xaml

This commit updates our scrollbar template to microsoft-ui-xaml at ceeab5f.
This incorporates the bug fix for MSFT-39442675.

Update ControlsV2 scrollbar template

---

src/cascadia/TerminalSettingsEditor/Appearances.h
src/renderer/base/CSSLengthPercentage.cpp
src/renderer/base/sources.inc
src/renderer/inc/CSSLengthPercentage.h

This just removes some leftover code that I forgot to remove before the merge.
Additionally I forgot to add a newly added file to our `sources` build file.

Address remaining review feedback for #14255

---

build/pipelines/templates/helix-runtests-job.yml

The old ones are pushing up daisies.

Switch to the new Helix queues

---

OpenConsole.sln
src/cascadia/TerminalAzBridge/TerminalAzBridge.vcxproj
src/cascadia/WpfTerminalControl/TerminalControl.xaml.cs

I don't think this is the resolution for #14581, but this can't hurt

Properly configure the project dependencies for TerminalAzBridge

---

src/cascadia/TerminalSettingsModel/CascadiaSettings.cpp

Add a second way of detecting whether DefTerm is available

---

src/cascadia/TerminalControl/TermControl.cpp

Big surprise, apparently W.F.Uri can parse the empty string into garbage!

Stop the beef when you hover off a hyperlink

---

src/cascadia/ShellExtension/OpenTerminalHere.cpp

Disable the context menu command inside a zipped folder

---

src/cascadia/TerminalControl/TermControl.cpp

Make the rclick menu pre-populate "Find" with the selected text

---

src/cascadia/TerminalSettingsModel/ActionArgs.cpp
src/cascadia/TerminalSettingsModel/Resources/en-US/Resources.resw
src/cascadia/TerminalSettingsModel/defaults.json

This was in pursuit of #15156. I need an ack from OP to make sure this is good enough.
Related to #14957

Add default bindings for "move tab/pane to a new window"

---

src/cascadia/WindowsTerminal/AppHost.cpp
src/cascadia/WindowsTerminal/AppHost.h

Just move session restoration into a helper function, as suggested by Leonard.

Move session restore into a helper in AppHost

---

src/cascadia/TerminalSettingsEditor/PreviewConnection.cpp

Make the preview text 100% more accurate

---

.github/actions/spelling/allow/names.txt
README.md

Add Christopher Nguyen to Readme cc @nguyen-dows

Add Christopher Nguyen to the README

---

src/cascadia/WindowsTerminal_UIATests/Elements/TerminalApp.cs

Carlos and I spent an hour rediscovering how to make this work. I figured it'd be best to leave notes behind for future archeologists.

Add a note about how to run the UIA tests locally

---

src/cascadia/UnitTests_TerminalCore/TilWinRtHelpersTests.cpp
src/inc/til/winrt.h

It's unknown how this ever worked, or why it stopped working recently.

Fix the TilWinRT tests

---

build/pipelines/ci.yml
build/pipelines/templates-v2/job-test-project.yml
src/terminal/parser/ut_parser/OutputEngineTest.cpp

Disambiguate the test job artifact based on attempt number

---

.github/actions/spelling/expect/web.txt
doc/Niksa.md

https://github.com/microsoft/terminal/issues/15870#issuecomment-1701435579 is an important note I think deserves to be committed.

Update cmd.exe FAQ

---

src/cascadia/TerminalControl/TermControl.cpp

Fix a bug when changing EnableUnfocusedAcrylic at runtime

---

src/project.inc

It's been literally 4 years since I worked directly in the OS repo and I forgot how to build the console 🤦

Add a note on how to build the Terminal in the OS repo

---

dep/nuget/packages.config
src/common.nugetversions.targets

Upgrade Microsoft.Windows.ImplementationLibrary to 1.0.230824.2

---

README.md

This PR updates the README with information about Windows Terminal Canary.

Update README with Canary info

---

README.md

Dependency support is now GA in WinGet. Updating the instructions in README

Update note regarding WinGet installation

---

.config/dotnet-tools.json

Update xamlstyler to 3.2311.2

---

.github/workflows/addToProject.yml

Update ctions/add-to-project to version 4.0.1

Update actions/add-to-project to version 0.5.0

---

.github/workflows/similarIssues.yml

Added an if statement to similarIssues.yml so that the logic can be updated to not show as 'failure' when no similar issue is found.
None
Small change only

Fix similarIssues.yml to not fail when no similar issues found

---

src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/CascadiaPackage/Package-Pre.appxmanifest
src/cascadia/CascadiaPackage/Package.appxmanifest

This reverts commit abab8705fea32854a6b55153b5736f9fd9dacb66.
It went badly, as you might imagine.

Revert "Add magic incantation to tell Store we support Server"

---

build/pipelines/templates-v2/pipeline-onebranch-full-release-build.yml

This will prevent the build from failing every night.

build: add a tsa configuration for asyncSdl

---

build/pipelines/templates-v2/job-pgo-build-nuget-and-publish.yml
build/pipelines/templates-v2/steps-restore-nuget.yml

It keeps warning us that v0 has been deprecated.

build: switch to NuGetAuthenticate@1

---

.github/workflows/similarIssues.yml

Improved the GitGudSimilarIssues bot to include issue body info now.

Update similarIssues.yml to include issue bodies

---

src/cascadia/TerminalControl/TermControl.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.cpp
src/cascadia/TerminalSettingsEditor/ProfileViewModel.h
src/cascadia/TerminalSettingsEditor/ProfileViewModel.idl
src/cascadia/TerminalSettingsEditor/Profiles_Advanced.xaml
src/cascadia/TerminalSettingsEditor/Resources/en-US/Resources.resw

As noted in #3337, we never actually added this menu to the settings. 
Since we're planning on taking this out of "experimental" in 1.21, we should have a visible setting for it too.

Add a pile of 'experimental' settings to the profile SUI

---

.vscode/settings.json

Prevents errors generated due to unresolved headers in VSCode
- Errors messages are removed.
- Headers are resolved properly.

Add VSCode configs for better out-of-box LSP support

---

build/pipelines/ci.yml

ci: trigger builds for gh-readonly-queue/* merge queue branches

---

src/cascadia/TerminalControl/ControlCore.cpp

Yea, I used a viewport-relative mouse position, rather than the buffer-relative position. Pretty obvious in retrospect.
Closes #16423

Fix `repositionCursorWithMouse` after the viewport starts scrolling

---

src/buffer/out/textBuffer.cpp

This takes care of an edge case in regards to SGR 22: It turns off
both intense and faint attributes which means that we may need to
turn on one of the two if only one of them turned off.
Additionally, this removes the mapping for `BottomGridline` which
has no real VT equivalent anyway.
* Turn session restore on
* In pwsh write:
```pwsh
"`e[1;2mboth`e[0;1mintense`e[m`n`e[1;2mboth`e[0;2mfaint`e[m"
```
* Close the app and open the `buffer_*.txt` file next to settings.json
* It contains... ✅
```
␛[1m␛[2mboth␛[22;1mintense␛[22m
␛[1m␛[2mboth␛[22;2mfaint␛[22m
```

Buffer Restore: Fix turning off intense/faint

---

doc/building.md

This happens to me once a month, and I finally solved it.

Add some docs on how to resolve `DEP0700` errors in VS

---

src/renderer/atlas/BackendD3D.cpp
tools/ConsoleTypes.natvis

This is some test code and natvis fixes that I used to trace down
an issue during font rendering.

AtlasEngine: Improve debuggability

---

doc/cascadia/profiles.schema.json

Add action ID to schema

---

src/host/ft_host/InitTests.cpp

These feature tests continue to plague us. Seems like the most likely outcome nowadays is that the test fails to attach immediately, so we don't even get to the retry loop.
Easy enough. Let's move the AttachConsole into the loop too.

Move the AttachConsole in the feature tests in the retry loop

---

src/cascadia/TerminalApp/Resources/es-ES/Resources.resw
src/cascadia/TerminalApp/Resources/it-IT/Resources.resw
src/cascadia/TerminalControl/Resources/it-IT/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/ko-KR/Resources.resw
src/cascadia/TerminalSettingsModel/Resources/es-ES/Resources.resw

Closes #12665 
Closes #12712 
Closes #16867

Localization Updates - fix issues in Korean, Italian, Spanish

---

src/cascadia/TerminalApp/App.xaml
src/cascadia/TerminalApp/CommandPalette.xaml
src/cascadia/TerminalApp/SuggestionsControl.xaml

Exactly the same as #17247, but also just applied to the command palette. It's so much better guys.

Remove the animations from the command palette too

---

src/cascadia/TerminalApp/TerminalPage.cpp

Various fixes needed for this branch from the Action ID refactor

Fix feature/llm branch from action refactor changes

---

src/renderer/atlas/BackendD2D.cpp

AtlasEngine: Curly line redux

---

src/cascadia/WindowsTerminal/WindowsTerminal.vcxproj

Make WindowsTerminal F5-runnable

---

scratch/ScratchIslandApp/Package/Package.wapproj
scratch/ScratchIslandApp/SampleApp/SampleAppLib.vcxproj
scratch/ScratchIslandApp/SampleApp/dll/SampleApp.vcxproj
scratch/ScratchIslandApp/SampleApp/packages.config
scratch/ScratchIslandApp/WindowExe/WindowExe.vcxproj
scratch/ScratchIslandApp/WindowExe/packages.config

This simply makes the project compile again.

Update scratch project dependencies

---

src/cascadia/TerminalCore/Terminal.cpp
src/cascadia/UnitTests_TerminalCore/TerminalBufferTests.cpp

Restore the ability to disable checking for URLs

---

src/winconpty/winconpty.cpp

Swapped the `swprintf_s` with no failure checks against a
`str_printf_nothrow` with checks. I also deduplicated the
`CreateProcess` calls since they're mostly identical.
Closes #16860

ConPTY: Raise the MAX_PATH limit

---

src/features.xml

whoops. This should have been in preview after I sorted out #17366
----
I did this one on GH so let's hope CI works

Add `Feature_SaveSnippet` to preview builds

---

src/features.xml

Add `Feature_QuickFix` to preview builds

---

build/config/tsa.json

We are, quite literally, shipping the org chart.

build: fix the TSA configuration

---

src/cascadia/CascadiaPackage/Resources/cs-CZ/Resources.resw
src/cascadia/TerminalApp/Resources/cs-CZ/ContextMenu.resw
src/cascadia/TerminalApp/Resources/ko-KR/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/de-DE/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/es-ES/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/fr-FR/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/it-IT/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/ja-JP/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/ko-KR/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/pt-BR/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/qps-ploc/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/qps-ploca/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/qps-plocm/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/ru-RU/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/zh-CN/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/zh-TW/Resources.resw

Closes #17752
Closes #17764
Closes #17830

Localization Updates - main - 09/26/2024 19:14:21

---

src/cascadia/TerminalSettingsEditor/Appearances.cpp
src/cascadia/TerminalSettingsEditor/Appearances.h
src/cascadia/TerminalSettingsEditor/Appearances.xaml

Reverts microsoft/terminal#17961
Closes #17987 
Reopens #17916

Revert "Stop updating AutoSuggestBox on selection"

---

src/cascadia/TerminalApp/TerminalPage.cpp

There was an issue with the way we parse the commandline executable when the commandline contained a space (for example, the commandline `"C:\Program Files\PowerShell\7\pwsh.exe"` resulted in `Program` being the parsed out executable instead of `pwsh.exe`). This commit fixes that.
The correct executable string is obtained

[Terminal Chat] Fix getting the wrong executable when the commandline contains a space

---

src/cascadia/CascadiaPackage/Resources/cs-CZ/Resources.resw
src/cascadia/TerminalApp/Resources/cs-CZ/ContextMenu.resw
src/cascadia/TerminalSettingsEditor/Resources/de-DE/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/es-ES/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/fr-FR/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/it-IT/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/ja-JP/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/ko-KR/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/pt-BR/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/qps-ploc/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/qps-ploca/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/qps-plocm/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/ru-RU/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/zh-CN/Resources.resw
src/cascadia/TerminalSettingsEditor/Resources/zh-TW/Resources.resw

Localization Updates - 10/22/2024 03:06:53

---

.github/workflows/addToProject.yml

- build(deps-dev): bump braces from 3.0.2 to 3.0.3 
- build(deps-dev): bump @types/node from 16.18.96 to 16.18.101
- build(deps-dev): bump ts-jest from 29.1.2 to 29.1.5
- build(deps-dev): bump @typescript-eslint/parser from 7.6.0 to 7.14.1 
- build(deps-dev): bump @typescript-eslint/eslint-plugin from 7.6.0 to 7.14.1 
- build(deps-dev): bump eslint-plugin-jest from 27.9.0 to 28.6.0 
- Dependabot/npm and yarn/eslint plugin jest 28.6.0 fixes

Update actions/add-to-project 1.0.1 -> 1.0.2

---

src/cascadia/CascadiaPackage/Package-Can.appxmanifest
src/cascadia/CascadiaPackage/Package-Dev.appxmanifest
src/cascadia/WindowsTerminal/WindowEmperor.cpp

Let's use what we already got!

Simplify handle-uri window targeting

---

build/pipelines/ob-nightly.yml
build/pipelines/ob-release.yml
build/pipelines/templates-v2/steps-esrp-signing.yml

This is in support of some identity changes we need to make.

build: add a couple more signing variables to ESRP

---

tools/ReleaseEngineering/ServicingPipeline.ps1

Oops, it didn't support more than 100 items!

Teach ServicingPipeline to paginate project board items

---

build/packages.config

Removing a package due to a CG alert in a submodule: https://www.nuget.org/packages/MUXCustomBuildTasks 
build/tests
Reopened separately from https://github.com/microsoft/terminal/pull/18678

Remove unused package for missing licensing

---

src/host/_stream.cpp

We can't do the `pos.x != 0` check. Instead, I replaced it with a CR check to avoid redundant CRs during CRLF translation.
Closes #18735
* Run the repro in the linked issue

Fix CRLF translation when DISABLE_NEWLINE_AUTO_RETURN is reset

---

build/pipelines/daily-loc-submission.yml

Update to TouchdownBuildTask v5

---

build/config/tsa.json

build: fix the tsa config yet again

---

src/cascadia/TerminalSettingsModel/defaults.json

Binds the "Clear buffer" action to ctrl+shift+k
Closes #17894

Bind "Clear buffer" action to Ctrl+Shift+K

---

src/cascadia/TerminalControl/HwndTerminal.cpp

They're much prettier, but some users may not be 100% happy.

wpf: force builtin glyphs

---

src/cascadia/TerminalApp/TerminalPage.cpp
src/cascadia/TerminalControl/InteractivityAutomationPeer.cpp
src/host/ut_host/Host.UnitTests.vcxproj
src/host/ut_host/Host.UnitTests.vcxproj.filters

Looks like there's a new VS version on the build agents. This just goes through and fixes any issues they found.

Fix build errors from updated VS build agents

---

src/inc/test/CommonState.hpp

Something about FillRow tickles the compiler and causes it to ICE during LTCG.
See DD-2413379 for more.
DevCom: https://developercommunity.visualstudio.com/t/VS-2022-1714-p11-cannot-complete-a-bui/10864784

bodgy: inline FillRow in FillTextBuffer to work around DD-2413379

---

src/cascadia/TerminalSettingsEditor/Extensions.xaml

Updates the hardcoded link with a fwlink.

Replace extensions page hyperlink with fwlink

---

src/cascadia/TerminalConnection/ConptyConnection.cpp
src/cascadia/TerminalConnection/ConptyConnection.h

Closes #19152
* Set `PATH` on a linux profile
* `PATH` isn't messed up inside WSL ✅

Fix WSL PATH corruption & potential use-after-free

---

src/cascadia/TerminalApp/TerminalPage.cpp

It isn't necessary to re-lookup the profile by name when we have all the objects that already know about the Profile object.
Did some drive-by fixes to `std::filesystem::path` use as well.

[f/llm] Tidy up ActiveControlInfo, fix for new IMediaResource Icon

---

src/buffer/out/Row.cpp
src/buffer/out/Row.hpp

An alternative approach for #18291. Improves perf by ~7%.

Fix a output marks performance regression

---

src/cascadia/TerminalSettingsModel/VsDevCmdGenerator.h
src/cascadia/TerminalSettingsModel/VsDevShellGenerator.h

VsDev: reject VS instances which do not actually contain devshell/devcmd
